### PR TITLE
Add the compiler to the regular IDE package.

### PR DESCRIPTION
**Pull request by brettfo**
This will enable nightly VSIX packages to ship with compiler changes as well as F5.  Below is a screenshot of the F5 scenario showing that for both legacy and SDK projects the compiler used came from the VSIX instead of `Program Files`.

compiler

### CODE REVIEW

**Comment by brettfo** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build
@dotnet-bot test Windows_NT Release_ci_part3 Build

**Comment by TIHan** [comment]
This is absolutely fantastic.

**Comment by Pilchie** [comment]
Wait - doesn't this mean that all builds in VS will use this compiler, even in shipped products?  Is that what we want?  Do customer environment variables or other properties override this or vice versa.

This seems like a pretty significant change to take without verifying some more scenarios for it first.

**Comment by dsyme** [comment]
@brettfo Can you also check that the F# Interactive (fsi.exe, fsiAnyCpu.exe) that run in Visual Studio are the ones from the VSIX?  thanks

**Comment by cartermp** [comment]
@brettfo is this true?

> doesn't this mean that all builds in VS will use this compiler, even in shipped products? 

I would argue that we don't want this for shipping, as we want to be deliberate about compiler changes for shipped products.

Getting these out in nightlies is fantastic since it'll have more people banging on changes before they make it out, but we shouldn't be delivering compiler changes unless we rev versions of the compiler (and do so deliberately).

**Comment by Pilchie** [comment]
I'm still :-1: on this change.  There are too many risks for users who set those variables themselves.  I do not think this should be in the shipping code.

**Comment by cartermp** [comment]
Another angle here is that we've received a lot of feedback over time that nightlies contain latest compiler bits. People who wanted to test out new features earlier on didn't have a way to do that unless they built this repo themselves.

It sounds like this will not work in conjunction with the [FSharp.Compiler.Tools package](https://www.nuget.org/packages/FSharp.Compiler.Tools/), which some people use. However, we don't officially support this scenario beyond obvious issues (e.g., #3222 where this exposed the fact that the legacy project system wasn't kicking off design-time builds properly).

We'll also incur a "you moved my cheese" issue when we move away from an MSI for the compiler as well (unless we also deploy the compiler to `Program Files`).

**Comment by brettfo** [comment]
@dsyme `fsi.exe` and `fsiAnyCpu.exe` both run from the VSIX/F5 location.

**Comment by brettfo** [comment]
@Pilchie What danger do see?  The properties set in this PR happen at project creation so anything the developer sets in a .props/.targets/.fsproj will override what I set giving them their expected behavior.

**Comment by KevinRansom** [comment]
@Pilchie your issue is this?
````
        [ "FSharpPropsShim", "Microsoft.FSharp.NetSdk.props" 
          "FSharpTargetsShim", "Microsoft.FSharp.NetSdk.targets" 
          "FSharpOverridesTargetsShim", "Microsoft.FSharp.Overrides.NetSdk.targets" ] 
````

I think this is fine, because it is the initial state of these values prior to the project being run.  If the developer adds a target to his project that forces these values to a different location then nothing is altered by us having precomputed the value.

We actually do this in our tests to pick a specific compiler implementation:  https://github.com/Microsoft/visualfsharp/blob/master/FSharpTests.Directory.Build.props#L23

Because we want it to use a versy specific compiler it isn't guarded by a conditions, and so behaves as the tests would expect.  It will pick a different compiler.



.

**Comment by Pilchie** [comment]
What if the user sets it via env var?

**Comment by brettfo** [comment]
@KevinRansom and I have been digging into it and there is an issue in that the property we're setting can't be overwritten.  I'm working on a change now to use the Roslyn approach of setting `FSharpCompilerLocation` (or whatever) and keying off of that in our shim targets.  The upside is that if a user builds with `/p:FSharpTargetsPath=...` or via an environment variable, everything will work as expected.  The downside is that consuming the VSIX compiler won't work until we've shipped the shims at least once, e.g., 15.8 RTM.

**Comment by abelbraaksma** [comment]
From a user standpoint, we've often been hit by either of these scenarios:

* Downloading a Preview VS IDE, with bugs, only to find out that if you switch back to and RTM VS IDE, the new bugs are there too
* Trying out changes from a PR or in the nightlies: if you don't have a VM, it is pretty tough to find out how to do that without breaking any of your current installations (and even if you're convinced you do it right, any bug you'll find since, you'll be wondering whether you broke something by mixing installations on one system).

It is my main concern whenever I report a bug, or when others cannot repro it. Having the compiler, or essentially everything from the F# tooling in a VSIX and being able to install / use it with a specific VS instance would be a dream come true. 

Just saying: please don't let us wait until 15.8. Being able to get involved in the open source effort more easily and with less worries would mean the world to many people.

**Pull request merged**
