### PR TITLE
Various fixes for implement interface code fix

### PR DESCRIPTION
**Pull request by dungpa**
Fixed these two small issues:

 - https://github.com/Microsoft/visualfsharp/pull/2112#issuecomment-269236160
 - https://github.com/Microsoft/visualfsharp/pull/2112#issuecomment-269249640

/cc @vasily-kirichenko @KevinRansom

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@dungpa work OK to me. What about removing "explicitly" word from the title? In F# you cannot implement an interface implicitly, so this word is just noise.

**Comment by dungpa** [comment]
The word 'explicitly' is there so that people coming from C# know exactly what to expect (C# editor provides 'Implement interface' and 'Implement interface explicitly' as two choices). 

I can remove it if anyone else also thinks it's redundant?

**Comment by cartermp** [comment]
I think we can remove the "explicitly" text since there is no implicit interface implementation in F# as @vasily-kirichenko mentioned.  I think that having it there may confuse C# people, who may expect the ability to "just" implement an interface and wonder why they "have" to do it explicitly, and for people with no C# experience there's no issue in implicit v. explicit terminology.

**Comment by dungpa** [comment]
@vasily-kirichenko @cartermp Here it is https://github.com/Microsoft/visualfsharp/pull/2126

**Pull request merged**
