### PR TITLE
Add glyph to Quick Info tooltip

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
Again... :)

image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
Build error:
````
D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\QuickInfoProviderTests.fs(104,52):
  error FS0001: Type mismatch. Expecting a
    'FSharpStructuredToolTipText * TextSpan * FSharpSymbol'
but given a
    'FSharpStructuredToolTipText * TextSpan'

The tuples have differing lengths of 3 and 2

[D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\VisualFSharp.Unittests.fsproj]
Done Building Project "D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\VisualFSharp.Unittests.fsproj" (Build target(s)) -- FAILED.
Project "D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\fsharp-vsintegration-unittests-build.proj" (40) is building "D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\Resources.MockTypeProviders\DefinitionLocationAttribute\DefinitionLocationAttribute.csproj" (43) on node 1 (Build target(s)).
PrepareForBuild:

````

Full build command line:
````
CoreCompile:
  D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\Proto\net40\bin\fsc-proto.exe -o:obj\release\net40\VisualFSharp.Unittests.dll
  -g
  --debug:pdbonly
  --noframework
  --define:STRONG_NAME_AND_DELAY_SIGN_FSHARP_COMPILER_WITH_MSFT_KEY
  --define:NO_PROJECTCRACKER
  --define:TRACE
  --define:VS_VERSION_DEV15
  --define:ENABLE_MONO_SUPPORT
  --define:BE_SECURITY_TRANSPARENT
  --define:FX_LCIDFROMCODEPAGE
  --define:FSI_SHADOW_COPY_REFERENCES
  --define:FSI_SERVER
  --doc:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\release\net40\bin\VisualFSharp.Unittests.xml
  --optimize+
  --platform:x86
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\EnvDTE.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\EnvDTE80.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\release\net40\bin\FSharp.Build.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\release\net40\bin\FSharp.Core.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\release\net40\bin\FSharp.Editor.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\release\net40\bin\FSharp.LanguageService.Base.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\release\net40\bin\FSharp.LanguageService.Compiler.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\release\net40\bin\FSharp.LanguageService.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\release\net40\bin\FSharp.ProjectSystem.Base.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\release\net40\bin\FSharp.ProjectSystem.FSharp.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualFSharp.Msbuild.15.0.1.0.1\lib\net45\Microsoft.Build.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualFSharp.Msbuild.15.0.1.0.1\lib\net45\Microsoft.Build.Framework.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualFSharp.Msbuild.15.0.1.0.1\lib\net45\Microsoft.Build.Tasks.Core.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualFSharp.Msbuild.15.0.1.0.1\lib\net45\Microsoft.Build.Utilities.Core.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.CodeAnalysis.Common.2.0.0-rc2\lib\netstandard1.3\Microsoft.CodeAnalysis.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.CodeAnalysis.EditorFeatures.2.0.0-rc2\lib\net46\Microsoft.CodeAnalysis.EditorFeatures.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.CodeAnalysis.EditorFeatures.Text.2.0.0-rc2\lib\net46\Microsoft.CodeAnalysis.EditorFeatures.Text.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.CodeAnalysis.Features.2.0.0-rc2\lib\netstandard1.3\Microsoft.CodeAnalysis.Features.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.CodeAnalysis.Workspaces.Common.2.0.0-rc2\lib\netstandard1.3\Microsoft.CodeAnalysis.Workspaces.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.CoreUtility.14.3.25407\lib\net45\Microsoft.VisualStudio.CoreUtility.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Designer.Interfaces.1.1.4322\lib\microsoft.visualstudio.designer.interfaces.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Editor.14.3.25407\lib\net45\Microsoft.VisualStudio.Editor.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Language.Intellisense.14.3.25407\lib\net45\Microsoft.VisualStudio.Language.Intellisense.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.LanguageServices.2.0.0-rc2\lib\net46\Microsoft.VisualStudio.LanguageServices.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.OLE.Interop.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Shell.14.0.14.3.25407\lib\Microsoft.VisualStudio.Shell.14.0.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Shell.Design.14.3.25407\lib\net45\Microsoft.VisualStudio.Shell.Design.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Shell.Immutable.10.0.10.0.30319\lib\net40\Microsoft.VisualStudio.Shell.Immutable.10.0.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.Interop.10.0.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\VSSDK\VisualStudioIntegration\Common\Assemblies\v4.0\Microsoft.VisualStudio.Shell.Interop.11.0.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.Interop.8.0.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.Interop.9.0.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Shell.Interop.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Text.Data.14.3.25407\lib\net45\Microsoft.VisualStudio.Text.Data.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\RoslynDependencies.Microsoft.VisualStudio.Text.Internal.14.3.25407\lib\net45\Microsoft.VisualStudio.Text.Internal.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Text.Logic.14.3.25407\lib\net45\Microsoft.VisualStudio.Text.Logic.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Text.UI.14.3.25407\lib\net45\Microsoft.VisualStudio.Text.UI.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Text.UI.Wpf.14.3.25407\lib\net45\Microsoft.VisualStudio.Text.UI.Wpf.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.TextManager.Interop.8.0.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.TextManager.Interop.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.VisualStudio.Threading.14.1.131\lib\net45\Microsoft.VisualStudio.Threading.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.VSHelp.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\NUnit.3.5.0\lib\net45\nunit.framework.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\PresentationCore.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\PresentationFramework.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\System.Collections.Immutable.1.2.0\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\..\packages\Microsoft.Composition.1.0.27\lib\portable-net45+win8+wp8+wpa81\System.Composition.AttributedModel.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Configuration.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Core.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Drawing.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Numerics.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Windows.Forms.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Xaml.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Xml.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Xml.Linq.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\UIAutomationTypes.dll
  -r:D:\j\workspace\release_ci_pa---3f142ccc\release\net40\bin\VisualFSharp.Salsa.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\VSLangProj.dll
  -r:C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\VSLangProj80.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\WindowsBase.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Collections.Concurrent.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Collections.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.ComponentModel.Annotations.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.ComponentModel.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.ComponentModel.EventBasedAsync.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Diagnostics.Contracts.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Diagnostics.Debug.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Diagnostics.Tools.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Diagnostics.Tracing.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Dynamic.Runtime.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Globalization.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.IO.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Linq.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Linq.Expressions.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Linq.Parallel.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Linq.Queryable.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Net.NetworkInformation.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Net.Primitives.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Net.Requests.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Net.WebHeaderCollection.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.ObjectModel.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Reflection.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Reflection.Emit.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Reflection.Emit.ILGeneration.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Reflection.Emit.Lightweight.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Reflection.Extensions.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Reflection.Primitives.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Resources.ResourceManager.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.Extensions.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.Handles.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.InteropServices.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.InteropServices.WindowsRuntime.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.Numerics.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.Serialization.Json.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.Serialization.Primitives.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Runtime.Serialization.Xml.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Security.Principal.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.ServiceModel.Duplex.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.ServiceModel.Http.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.ServiceModel.NetTcp.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.ServiceModel.Primitives.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.ServiceModel.Security.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Text.Encoding.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Text.Encoding.Extensions.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Text.RegularExpressions.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Threading.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Threading.Tasks.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Threading.Tasks.Parallel.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Threading.Timer.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Xml.ReaderWriter.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Xml.XDocument.dll
  -r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\System.Xml.XmlSerializer.dll
  --target:library
  --nowarn:58,75
  --warn:3
  --warnaserror
  --warnaserror:76
  --fullpaths
  --flaterrors
  --subsystemversion:6.00
  --highentropyva+
  --times
  --delaysign+
  --keyfile:D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\fsharp\msft.pubkey
  C:\Users\dotnet-bot\AppData\Local\Temp\.NETFramework,Version=v4.6.AssemblyAttributes.fs
  C:\Users\dotnet-bot\AppData\Local\Temp\VisualFSharp.Unittests.4.4.1.0.AssemblyFileVersion.fs
  D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\fsharp\InternalCollections.fsi
  D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\fsharp\InternalCollections.fs
  D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\..\..\..\src\utils\CompilerLocationUtils.fs
  TestLib.Utils.fs
  TestLib.Salsa.fs
  TestLib.LanguageService.fs
  TestLib.ProjectSystem.fs
  Tests.InternalCollections.fs
  Tests.Build.fs
  Tests.TaskReporter.fs
  Tests.Watson.fs
  Tests.XmlDocComments.fs
  Tests.LanguageService.General.fs
  Tests.LanguageService.Completion.fs
  Tests.LanguageService.IncrementalBuild.fs
  Tests.LanguageService.GotoDefinition.fs
  Tests.LanguageService.NavigationBar.fs
  Tests.LanguageService.ParameterInfo.fs
  Tests.LanguageService.QuickInfo.fs
  Tests.LanguageService.QuickParse.fs
  Tests.LanguageService.Script.fs
  Tests.LanguageService.TimeStamp.fs
  Tests.LanguageService.ErrorList.fs
  Tests.LanguageService.ErrorRecovery.fs
  Tests.ProjectSystem.Configs.fs
  Tests.ProjectSystem.Miscellaneous.fs
  Tests.ProjectSystem.MultiTargeting.fs
  Tests.ProjectSystem.ProjectItems.fs
  Tests.ProjectSystem.Project.fs
  Tests.ProjectSystem.References.fs
  Tests.ProjectSystem.RoundTrip.fs
  Tests.ProjectSystem.UpToDate.fs
  ..\..\..\tests\service\FsUnit.fs
  ..\..\..\tests\service\Common.fs
  ..\..\..\tests\service\EditorTests.fs
  ..\..\..\tests\service\FileSystemTests.fs
  ..\..\..\tests\service\ProjectAnalysisTests.fs
  ..\..\..\tests\service\MultiProjectAnalysisTests.fs
  ..\..\..\tests\service\ProjectOptionsTests.fs
  ColorizationServiceTests.fs
  BraceMatchingServiceTests.fs
  HelpContextServiceTests.fs
  IndentationServiceTests.fs
  BreakpointResolutionService.fs
  LanguageDebugInfoServiceTests.fs
  DocumentDiagnosticAnalyzerTests.fs
  ProjectDiagnosticAnalyzerTests.fs
  CompletionProviderTests.fs
  SignatureHelpProviderTests.fs
  GoToDefinitionServiceTests.fs
  QuickInfoProviderTests.fs
  DocumentHighlightsServiceTests.fs
````

**Comment by vasily-kirichenko** [comment]
@KevinRansom fixed

**Comment by KevinRansom** [comment]
@vasily-kirichenko 
I'm pretty sure that this isn't related. It looks environmental.
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
Thanks mate

**Pull request merged**
