### PR TITLE
Merge --- master into coreclr --- Part 1 of many

### PR DESCRIPTION
**Pull request by KevinRansom**

### CODE REVIEW

**Comment by KevinRansom** [comment]
Dang that was hard ....

**Comment by rojepp** [comment]
I know. :)

**Comment by KevinRansom** [comment]
Okay the build error on appveyor is because the .net native installs a nugget build with it's own set of target files and that gets injected into our build chain.  It works fine if uwp is not installed into VS.  I will see if I can figure out how to disable it for our build.

**Comment by KevinRansom** [comment]
Merge completed. and checked in.

**Comment by rojepp** [comment]
Way to go!

**Comment by panesofglass** [comment]
w00t!

**Pull request merged**
