### PR TITLE
Remove dependency on FSharp.LanguageService from FSharp.ProjectSystem

### PR DESCRIPTION
**Pull request by cartermp**
Continuation of the work in #4132 

There was a lingering file, `UIThread.cs`, in FSharp.LanguageService.Base that the legacy project system ultimately depended on. I just moved it to FSharp.ProjectSystem.Base.

### CODE REVIEW

**Comment by dsyme** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please
@dotnet-bot test Windows_NT Release_ci_part1 Build please

**Comment by cartermp** [comment]
@brettfo just wanted to say that I couldn't be happier to resolve these conflicts

**Comment by cartermp** [comment]
ugh rebase sucked

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Pull request merged**
