### PR TITLE
Add issue stats

### PR DESCRIPTION
**Pull request by forki**
@dsyme suggested to add issue stats for F# projects. Some projects like Paket already have these (see https://github.com/fsprojects/Paket#build-status)

Also in Typescript: https://github.com/Microsoft/typescript

### CODE REVIEW

**Comment by sergey-tihon** [comment]
What about build stats? ;)

**Comment by forki** [comment]
@sergey-tihon I already talked to @KevinRansom about that. There is interest in making the AppVeyor / Travis build working one day. But that's still a long way. Issue stats are much easier ;-)

**Comment by forki** [comment]
but since @latkin is very careful about merging we could add a static green picture. ;-) j/k

**Comment by sergey-tihon** [comment]
Oh, I see - we have dependency on https://github.com/Microsoft/visualfsharp/pull/15
@latkin is definitely better than any ci server. ;-) not j/k

**Comment by latkin** [comment]
:+1:  Looks good to me.  This is cool GitHub magic.

**Pull request closed without merging**
