### PR TITLE
Fix debugging of code using Anonymous records

### LINKED ISSUE #6512: breakpoints doesnt work with anonymous records in .net core sdk
Setting breakpoint if the code contains anonymous records, doesnt work

I not yet tried in VS, but with latest .net core debugger and latest .net core sdks affect vscode
Ionide doesnt matter, the debugger is in MS code and i am using the VSCode Debug tab with tasks.json and launch.json

#### Repro steps

create a simple program with `dotnet new console -lang f#`

```fsharp
[<EntryPoint>]
let main argv =
    printfn "Hello World from F#!"

    // let a = {| A = 1 |}

    printfn "A"

    // printfn "%A" a

    0 // return an integer exit code
```

and set some breakpoint at the instructions.
Running in debug, it stop on breakpoint and debug works

if i uncomment the lines, the debugger doesnt stop on any breakpoint (not just anon records)

if i set debugger to stop at entry point, it stop an entry and i can step by step, but breakpoint are not enabled

image

the debug info show it cannot bind the line to breakpoint

```
Breakpoint warning: No executable code of the debugger’s target code type is associated with this line.
Possible causes include: conditional compilation, compiler optimizations, or the target architecture of this line is not supported by the current debugger code type. - e:\temp\pwa\Program.fs:6
```

#### Expected behavior

breakpoints works

#### Actual behavior

breakpoints doesnt works

#### Known workarounds

stop at entry point maybe, in vscode is done at `launch.json`

```
            "stopAtEntry": true,
```

#### Related information 

can repro in .NET Core `2.1.603` and `3.0.100-preview3-010431`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.603
 Commit:    ae71c68742

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.603\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.603 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:

  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

C# VSCode extension (who contains the debugger stuff)

```
Name: C#
Id: ms-vscode.csharp
Description: C# for Visual Studio Code (powered by OmniSharp).
Version: 1.18.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
```

### PR DESCRIPTION
**Pull request by dsyme**
This fixes #6512, debugging of code using anonymous records

@cartermp Like #6606 this should go into the fixes ASAP

The problem was with the name of the type for anonymous records in generated .NET code had an extra `'` character that was confusing the debuggers.  Just removing the character is the best fix.

### CODE REVIEW

**Comment by cartermp** [comment]
> The problem was with the name of the type for anonymous records in generated .NET code had an extra `'` character that was confusing the debuggers. Just removing the character is the best fix.

Wow, interesting!

**Comment by matthid** [comment]
I think it is early enough that we can get away with this. But do I understand this correctly that this introduces a binary breaking change for users just by updating the compiler?

**Comment by cartermp** [comment]
Thanks for bringing it up, it's worth thinking about.

@dsyme would be the expert here but my gut feel is no. The stamp in an anonymous record is calculated with a hashing function and we don't guarantee binary compatibility for a given hash function.

Here's [another take](https://github.com/Microsoft/visualfsharp/issues/1838):

>I now agree we don't need to be backwards compatible, and I've been quite surprised that the lack of determinism/stability for .NET hash codes (e.g. of strings) has not seemed to have been a problem in practice.
>
>Still, I'm not particularly keen on changing things unless we really, really have to and we address a number of known issues simultaneously. An RFC would be needed I think... And several more people than just myself approve it....

**Comment by matthid** [comment]
Just to be clear: In the hashcode example we change behavior. In this particular PR we straight up break it and execution will fail at runtime as we basically renamed the type.

Example: https://github.com/Microsoft/visualfsharp/issues/6479
After updating the compiler in the library project, I'd expect the console app to fail with a TypeNotFoundException (or something like that).
The 'fix' is to compile the console app with the new compiler as well.

By the way: Looking at the code and the error in #6479, I wouldn't be surprised if this PR fixes that issue as well.

**Comment by matthid** [comment]
(I know I'm potentially playing the 😈 here, but if a bunch of issues pop up because people started to depend on this we should at least have some idea how to move forward. Also those issues will probably pop up after some time...)

Personally I still think this PR is the right thing to do. But we should be ready to either tell everyone in the ecosystem that ' in the class-name are allowed or that this was a compiler bug breaking the IL spec and there is nothing else to do...

**Comment by cartermp** [comment]
> After updating the compiler in the library project, I'd expect the console app to fail with a TypeNotFoundException (or something like that).

This is no different than if the underlying hash generated in the name had changed due to changing the hashing function (for some reason), no?

**Comment by matthid** [comment]
> This is no different than if the underlying hash generated in the name had changed due to changing the hashing function (for some reason), no?

Yes and no. Yes because if the F# compiler depends on the hashcode this is indeed a unexpected sideeffect of the issue, which isn't mentioned in the issue. If there are such dependencies you should bring them up into the discussion (I haven't seen them but tbh. I focused on @dsyme comments).
No because we could just remove this dependency and make the compiler use it's own hash function and therefore keep the behavior stable (if we want/need). Which is not something we can do here. So I think it's unrelated.

**Comment by KevinRansom** [comment]
It’s a breaking change.  But it’s one that we can live with, the work around is to recompile the library, and then life will be fine.  The anonymous types feature first shipped in VS 16.0 which was I think less than 2 months ago.

We will add a release note, describing the issue and the work around.

Thanks

Kevin

**Comment by dsyme** [comment]
Yes, it is a binary breaking change.  Libraries compiled with a dev16.0 compiler that use public anonymous records and consumed with a dev16.1 compiler will experience a peverify/runtime failure.  The library should be recompiled with a dev16.1 compiler.

@KevinRansom is correct, we should just make this change.  Using anonymous records is rare at this stage, and using them in the API of public-facing libraries (e.g. ones pushed to nuget) even rarer, and consuming those libraries with a later compiler even rarer still.  And the adjustment needed to recompile and republish the library is fairly simple.

We should in future be much surer to check scenarios such as debugging (and not just rely on the author of the PR to do it....).

**Comment by JaggerJo** [comment]
Is there a schedule on when to expect this fix to appear as a VS Update / in the dotnet core sdk ?

**Comment by cartermp** [comment]
@JaggerJo The 16.1 VS release and associated .NET Core SDK.

**Comment by lfr** [comment]
@cartermp I just installed VS 16.1.1 today and rebuilt everything (even manually deleted obj folders) and I'm still experiencing this issue, have I done something wrong?

**Comment by cartermp** [comment]
I confirmed that this fix is in VS 16.2 and it does **not** resolve the issue.

Here I hit f5 and no breakpoint was triggered.

image

If I comment out the anonymous record, it works:

image

**Comment by cartermp** [comment]
Confirmed the full name does not have the `'`:

```
FullName = "<>f__AnonymousType1324739542`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]";
```

**Pull request merged**
