### PR TITLE
Fix for 2937 - Don't detuple lambdas during optimization based on types only

### PR DESCRIPTION
**Pull request by dsyme**
Tentative fix for https://github.com/Microsoft/visualfsharp/issues/2937

Initially we should see if this affects any existing codegen tests and examine

### CODE REVIEW

**Comment by dsyme** [comment]
OK, this is ready to go.  The two codegen changes are enough to act as testing.

* CodeGen\EmittedIL\Misc (CodeGenRenamings01.fs - NetFx40) 
* CodeGen\EmittedIL\Misc (LetIfThenElse01.fs - NetFx40) 

In both cases allocations were eliminated, so things have only improved

**Comment by dsyme** [comment]
This is ready

**Comment by forki** [comment]
@dsyme did you delete tests? It says +181 −3,080

**Comment by dsyme** [comment]
@forki There were old test files that are now u used

**Comment by dsyme** [comment]
This is ready

**Comment by dsyme** [comment]
@KevinRansom This one is ready

**Pull request merged**
