### PR TITLE
Fix Structure Service for properties

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/2190

### CODE REVIEW

**Comment by forki** [comment]
nice one

**Comment by saul** [comment]
:)

Thanks @vasily-kirichenko.

**Comment by vasily-kirichenko** [comment]
I've also fixed https://github.com/Microsoft/visualfsharp/issues/2191

image

**Comment by saul** [comment]
Thank you thank you - I don't think there are any more issues with block structure/guidelines anymore. Hopefully these can be merged into RTM.

**Comment by vasily-kirichenko** [comment]
Hm, I think we do guidelines fundamentally in a wrong way. They should mark _indentations_, not syntactic blocks. I mean it should look like this:

image

(where red rectangles are collapsing [+])

It's completely different way to do outlining and guidelines and it'd basically require rewriting all the AST traversing code.

**Comment by cartermp** [comment]
@vasily-kirichenko That's an interesting point.

My take is that we should ultimately offer two ways - indentation-based and syntax-based, and then offer the ability to toggle one or the other (or have all structure service turned off).  The default is something we could think about some more, and base off of feedback from what we're shipping at release.  Thoughts?

**Comment by vasily-kirichenko** [comment]
@cartermp I agree.

**Comment by saul** [comment]
Personally I've never seen the appeal of indentation guidelines - you already know how far you're indented by looking at the current line. I certainly don't think we should be disabling what we've got for release - I've found being able to collapse blocks really useful and it's a feature I've really missed until VS 2017.

**Comment by isaacabraham** [comment]
I think it has good educational value for new users who aren't used to whitespace significant scoping. Also - VFPT has had collapse blocks functionality for ages now.

**Comment by KevinRansom** [comment]
Thank you

**Pull request merged**
