### PR TITLE
Fixing JaroWinkler tests with InvariantCulture and fixing async tests by removing Debugger.Break()

### LINKED ISSUE #3583: The JaroWinkler tests fail on different locales
There are four JaroWinkler distance tests. These fail when run on a computer with a different locale.

### Repro steps

Run the tests under `FSharp.Compiler.Unittests.EditDistance` on a German, Dutch or basically any non-US/UK computer and you will get four failing tests, because the output uses `ToString` internally without taking care of the locale.

Suggested fix: add `Culture.InvariantCulture`. 

### Expected behavior

Any unit test should run successfully irrespective of the environments locale settings.

### Actual behavior

The following error is thrown:

```
  String lengths are both 5. Strings differ at index 1.
  Expected: "0.813"
  But was:  "0,813"
  ------------^

   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestActionCommand.Execute(TestExecutionContext context)
```

(this was one of the findings after starting investigating test coverage, see #3579)

### LINKED ISSUE #3605: The test StartAsTaskCancellation contains a Debugger.Break(), can it be removed safely?
My test runner hiccups on `Debugger.Break()` in tests (not surprisingly, a normal executable would do too). I was wondering if this break is intentional and serves a purpose, or was left their as a remnant of some temporary debugging situation.

Also, the `|> ignore` is redundant.

The test:

```F#
    [<Test>]
    member this.StartAsTaskCancellation () =
        let cts = new CancellationTokenSource()
        let tcs = TaskCompletionSource<unit>()
        let a = async {
            cts.CancelAfter (100)
            do! tcs.Task |> Async.AwaitTask }
#if FSCORE_PORTABLE_NEW || coreclr
        let t : Task<unit> =
#else
        use t : Task<unit> =
#endif
            Async.StartAsTask(a, cancellationToken = cts.Token)

        // Should not finish
        try
            let result = t.Wait(300)
            Assert.IsFalse (result)
        with :? AggregateException -> Assert.Fail "Task should not finish, jet"

        tcs.SetCanceled()
        
        try
            this.WaitASec t
        with :? AggregateException as a ->
            match a.InnerException with
            | :? TaskCanceledException as t -> ()
            | _ -> reraise()
        System.Diagnostics.Debugger.Break() |> ignore
        Assert.IsTrue (t.IsCompleted, "Task is not completed")
```

I can remove this line if nobody objects.

### PR DESCRIPTION
**Pull request by abelbraaksma**
This fixes #3583, a few tests that fail on different locales than en-US, and fixes #3605, which crashes some test runners or causes awkward popups to attach a debugger.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot Windows_NT Release_ci_part2 Build please

**Comment by abelbraaksma** [comment]
You're welcome, just a tiny fix ;)

**Comment by abelbraaksma** [comment]
Incidentally closed, reopend to allow merge.

**Comment by abelbraaksma** [comment]
Thanks for merging this 👍

**Comment by dsyme** [comment]
@abelbraaksma Thanks for providing it!

**Pull request merged**
