### PR TITLE
Improve FS0512, FS0529, FS0537

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by dsyme** [comment]
Odd there are no tests for any of these already in the code.  Add some under tests\fsharp\typecheck\sigs?

**Comment by forki** [comment]
I hoped they would have one ;-(

**Comment by dsyme** [comment]
@forki sorry :) and thanks for adding the tests...

**Comment by forki** [comment]
ok ready for review

**Comment by dsyme** [comment]
NIce, thanks

**Pull request merged**
