### PR TITLE
[wip] Elide compiler generated bindings from sequence expression

### PR DESCRIPTION
**Pull request by smoothdeveloper**
This is a look at #5073, on toy code, it succesfully elides all the variables and make the generated sequence stateless objects.

This works all due to existing implementation, I'm just adding a check to discard bindings that have `IsCompilerGenerated = true`, it somehow succeed to see that all which remains is local only.

I've compiled proto compiler and release build, the code generation for `ResolveCompletionsInTypeForItem` function is now down from 24 constructor parameters to 7!

https://github.com/Microsoft/visualfsharp/blob/4cf7aaed221a79e3aa16c11b932527cc9c2f0e1d/src/fsharp/NameResolution.fs#L4061-L4228

Currently, when you have a tuple pattern let binding in `seq { }` expression, it generates spurious values for the builder to keep track off, this probably applies to other bindings, which is an extra cost.

Those bindings, so long as they are not named (`SynPat.Named`, which is the use of `as` in a pattern deconstructor binding) should be discarded AFAIU.

If we want to move forward with this optimization, I'm looking for input on how to nail down the code generation behaviour change in our test suite, is there relevant tests I can take inspiration from?

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@dotnet-bot Test Windows_NT Release_ci_part2 Build please

**Comment by dsyme** [comment]
I'd be very surprised if this is a sound optimization. Just because something is compiler generated doesn't mean it doesn't escape into closures and form part of the state machine, e.g. that can happen because of optimization.

But it does seem like there is a very useful optimization lurking here to reduce the size of state machines

**Comment by dsyme** [comment]
The analysis needed is something like "check there are no use-occurrences of the variable except on (some conservative approximation of) the synchronous path leading to the next yield".  Since the analysis is already two-phase then you may well be able to collect the usage information on the way down the "left-hand" (i.e. synchronous) branch of the lowering, and then compare with overall usage information. That's a very rough outline though

It would be great to dig into this more, it would be a significant improvement to avoid the put more of these values on the stack

**Comment by smoothdeveloper** [comment]
Some tests failing in https://github.com/Microsoft/visualfsharp/blob/509a8a2e5fd71a9ead6a5920a2797af8983f2e5d/tests/fsharp/core/comprehensions/test.fsx

**Comment by smoothdeveloper** [comment]
> Just because something is compiler generated doesn't mean it doesn't escape into closures and form part of the state machine, e.g. that can happen because of optimization.

Right, it was my first stab at identifying the difference between:

```fsharp
let seq3 () =
  seq {
     let (a,b) = getTuple Foo
     yield! [a;b]
  }
```

and (notice use of a named pattern)

```fsharp
let seq3 () =
  seq {
     let (a,b) as c = getTuple Foo
     yield! [a;b]
  }
  ```

The failing tests are a bit hard to comprehend for me, I need to make a simpler failing test case to play with.

Also, instead of going with `IsCompilerGenerated` (which is a bit of a kitchen sink and not what I want I guess) I'd like to match on SynPat.Named, but I have no clue if this is even present or what it translates to in terms of `Val` in the typed AST, any idea how I could connect those parts?

I think this would be the first focused optimization to do while avoiding changing any behaviour on the rest.

**Comment by dsyme** [comment]
> Also, instead of going with IsCompilerGenerated (which is a bit of a kitchen sink and not what I want I guess) I'd like to match on SynPat.Named, but I have no clue if this is even present or what it translates to in terms of Val in the typed AST, any idea how I could connect those parts?

`SynPat` is long gone by this point.  At this point, you only have the TAST and have to do valid optimizations/transformations based only on the information available in that.

**Comment by dsyme** [comment]
@smoothdeveloper I don't think there's any point in updating the baselines until the analysis is a semantically correct one - and as I mentioned above you're quite a long way from that - the analysis needs to be based on usage-sites (not definition-sites) of variables in the TAST.

**Comment by smoothdeveloper** [comment]
@dsyme thanks, I've updated the code to only elide compiler generated tuple bindings, and checked the code gen on the `ResolveCompletionsInTypeForItem` ill case, we are still down to 7 parameters.

Also, the regression of my first attempt doesn't occur anymore in tests/fsharp/core/comprehensions/test.fsx with the new filtering.

I'm adding a codegen test but I'm not sure how to proceed to make CI happy with it, I've done those steps:
```shell
cd tests\fsharpqa\Source\CodeGen\EmittedIL\SeqExpressionElision
..\..\..\..\..\Release\net40\bin\fsc SeqExpressionElision1.fs
..\CompareIL.cmd SeqExpressionElision1.exe
```
to get the baseline IL but it is failing on CI server.

How should I move forward?

**Comment by dsyme** [comment]
@smoothdeveloper I'll close this since #5097 does the job.  Could you possibly check the effect of #5907 on the big bad state machines you were seeing?

**Comment by smoothdeveloper** [comment]
Thanks! yes I'll give a shot at your branch to check and report there.

**Pull request closed without merging**
