### PR TITLE
Wrong Nuget package version following version # update

### PR DESCRIPTION
**Pull request by KevinRansom**
I messed up, I got the package version number wrong for the FSharp.Core nugget package.  It should be 4.3.0 not 10.1.1
 
Also update FSharp.Core reference to 4.3

### CODE REVIEW

**Comment by isaacabraham** [comment]
Can we not finally just move over to things like Fake and automate this stuff and be done with it one and for all. This will save time and prevent human error.

**Comment by TIHan** [comment]
@isaacabraham , if we want to discuss that, we should create an issue and discuss there.

**Comment by forki** [comment]
@tihan not needed. We discussed it over and over and over again. We even had at least 2 PRs with FAKE scripts. Just ignore what @isaac_abraham said ;-)

**Comment by isaacabraham** [comment]
@TIHan is it worth me doing? If the answer will just be "no" as was in the past, I won't bother.

If however there's genuine interest in this I'll do it.

**Comment by cartermp** [comment]
@isaacabraham Though I think FAKE would be a boon personally, I don't think it solves this particular problem; it just changes where a version number lives from a targets file to somewhere else. That is, a FAKE script doesn't seem like it would prevent things like mislabeling the version number of something.

**Comment by forki** [comment]
No the script alone does not. But putting in one place for easy and predictable maintenance does help.

**Pull request merged**
