### PR TITLE
[WIP] Possible fix for 1251 - Array.blit performance

### PR DESCRIPTION
**Pull request by dsyme**
See this comment: https://github.com/Microsoft/visualfsharp/issues/1251#issuecomment-231361575

### CODE REVIEW

**Comment by rojepp** [comment]
@dsyme I tested with the code above. Is all that arg checking necessary in blit? Array.Copy should check the same things?

**Comment by forki** [comment]
@rojepp I'm working on a property based test which would "proof" that. See https://github.com/Microsoft/visualfsharp/pull/1345

**Comment by forki** [comment]
so I think we can really just use blit as alias to Array.Copy.

https://github.com/Microsoft/visualfsharp/pull/1345 shows that it's failing for the same values. So we would change the concrete exceptions, but still have exceptions for same values.

**Comment by dsyme** [comment]
I'm ok with that change (would like to see the performance tests re-run as proof that it fixes the problem)

**Pull request closed without merging**
