### PR TITLE
Report the concrete type in error msg

### PR DESCRIPTION
**Pull request by forki**
Instead of "this type" we should report the concrete type name.

### CODE REVIEW

**Comment by forki** [comment]
ready for review

**Comment by forki** [comment]
ci_part3 fail looks unrelated

**Comment by KevinRansom** [comment]
@forki   Yeah I have had a terrible weekend because of ci_part3 failures.  Something changed but I don't know what.

I will look at it.
Kevin

**Comment by forki** [comment]
thanks. the rest seems to work now

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet bot test this please

**Comment by forki** [comment]
yay. all green. thanks @KevinRansom

**Pull request merged**
