### PR TITLE
Fix #4714 (save completion data for at least as long as the completion session)

### LINKED ISSUE #4714: Description tooltip in Intellisense often empty.
image

#### Repro steps

Trigger autocompletion and go through the list with arrow keys. After a few correctly displayed descriptions empty tooltips start to show up.

#### Related information 

Recent nightlies and master. Hard to tell exactly when it broke.
This works fine in the released version.

### PR DESCRIPTION
**Pull request by dsyme**
#4714 is quite a bad bug where descriptions in VS completions timeout after 10 seconds. Mea culpa

I'm not quite sure of the right fix for this - @majocha decribes some potential fixes in the bug - I suggest we at least increase the expiration time to 2 minutes as a starting point.

### CODE REVIEW

**Comment by dsyme** [comment]
I'm looking at a better fix for this

**Comment by dsyme** [comment]
OK, I changed this to just save the data for at least as long as the completion session is active

@majocha Please take a look and check carefully, and try it if possible too

**Comment by majocha** [comment]
Thanks @dsyme! Everything looks good. Build, tested - works fine.

**Comment by dsyme** [comment]
OK, then this is ready

**Pull request merged**
