### PR TITLE
New CodeLens PR

### PR DESCRIPTION
**Pull request by realvictorprm**
I'm going to fix this later but will work on this within the next days.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@realvictorprm can you resubmit this targeting dev15.8.

**Comment by KevinRansom** [comment]
I retargeted it to 15.8, and merged it with 15.8.  I hope I didn't lose your work.

**Comment by cartermp** [comment]
There shouldn't be any difference, as this was merged into dev15.8 a while back.

**Comment by KevinRansom** [comment]
That would explain why the commits all evaporated then :-)

**Pull request closed without merging**
