### PR TITLE
Use dotnet publish to deploy fsharp.core.unittests for coreclr

### PR DESCRIPTION
**Pull request by KevinRansom**
1.  Build fsharp.core.dll to nuget package.
2.  use built nuget package for fsharp.core in fsharp.core.unittests coreclr build
3.  Get tuplesample.dll from nuget rather than local
4. remove a couple of unnecessary nuget.config files

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by forki** [comment]
Publish + unittests? Where are the unittests published to? And why?

Am 12.11.2016 09:50 schrieb "Kevin Ransom (msft)" <notifications@github.com
>:

@dotnet-bot <https://github.com/dotnet-bot> test this please

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/pull/1733#issuecomment-260110252>,
or mute the thread

**Comment by KevinRansom** [comment]
It uses dotnet publish to move the tests and required dependencies to testbin so that they can run.  Previously it was done using hacky file copies.

Kevin

**Comment by forki** [comment]
Ah Ok. I thought this was dotnet build is already doing. Thx

Am 12.11.2016 10:01 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Pull request merged**
