### PR TITLE
merge master into vs-rtm2017

### PR DESCRIPTION
**Pull request by KevinRansom**
merge master into vs-rtm2017

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build

**Comment by dsyme** [comment]
Yay ! :)

**Comment by vasily-kirichenko** [comment]
What all such merges mean? That master is going to some future update?

**Comment by forki** [comment]
Yes I wonder why the VS RTM is not just a tag or at least a fast forward
merge

Am 11.10.2017 11:13 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by dsyme** [comment]
@vasily-kirichenko Yes, that's the release branch

@forki I don't know if/why it's not fast-forward.  Sometimes there are hot release fixes in that branch

**Comment by forki** [comment]
but they should in master as well, right?

**Comment by dsyme** [comment]
@forki Yes, I believe so

**Comment by cartermp** [comment]
This branch is necessary given the current model in which VS ships, where we must keep track of different release branches internally.  One of those branches is always a future release, and that release may have breaking upstream changes that we must absorb and test on with internal builds until they are public.  Although this wasn't the case with 15.5, it may be the case with another release.  We can't impose these things in master.

**Pull request merged**
