### PR TITLE
Enable parallel build inside Visual Studio

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by forki** [comment]
Epic! ;-)

**Comment by vasily-kirichenko** [comment]
@forki I think you are right :) Huge thanks @vladima

**Comment by enricosada** [comment]
awesome @vasily-kirichenko !!

**Comment by latkin** [comment]
Wow, very cool.

@vladima - any further details that you recall from earlier experiments you mentioned?  Were there known issues that resulted in this feature being off by default? I am curious why it is turned off if it is indeed fully baked and tested, or if there are known scenarios that need some attention?

**Comment by vladima** [comment]
@latkin as I remember Brian has added this key shortly before he left so I think that this feature was never thoughtfully tested.

**Comment by vasily-kirichenko** [comment]
As so, maybe it's better to add a proper setting for this (I mean in the VS UI), at least for first F# 4 release?

**Comment by dsyme** [comment]
For those wanting to try this out you can enable it by following the instructions here: https://gist.github.com/vasily-kirichenko/84f7ebc284d92742493b

@vasily-kirichenko I'm speaking for @latkin and @KevinRansom, but my understanding is that the feature window has closed for Visual Studio 2015 RTM (they are now in "ask mode", meaning explicit approval is required for bug fixes), but that this would be considered for the first update.   

I also found some internal emails about this prototype which @latkin now has, pointing out that there is a minor thread affinity interaction with the VS type provider security warning dialog, but that was the only known issue.

**Comment by forki** [comment]
Another big plus for getting rid of the dialog ;-)

**Comment by vasily-kirichenko** [comment]
@dsyme OK, I think we can live with the regex setting for a while (however, VS removes it on regular basis, so it's a bit annoying to constantly check if the flag is still there).

**Comment by hmemcpy** [comment]
Just an FYI: modifying anything in the `_Config` will go away when Visual Studio rebuilds its cache (typically, when running `devenv /setup`, maybe in other scenarios).
Also, the manual registry tweak only works in the "main" VS hive, not any other custom ones.

A better "workaround" would be to create a `enable_fsharp_parallel_builds.pkgdef` file, like this:

    [$RootKey$\Projects\{f2a71f9b-5d33-465a-a702-920d77279786}]
    "IsMultiThreadedBuildEnabled"="1"

and place it under `$RootFolder$\Common7\IDE\Extensions`

Then, close VS, run `devenv /updateconfiguration` once from a Developer command prompt, and that's it - VS will add this automatically every time the configuration is updated.

This is a hack, but a more consistent one than manual registry manipulation.

**Comment by enricosada** [comment]
@hmemcpy an hack worthy of a wiki page, for similar issues

**Comment by latkin** [comment]
Applied to OOB branch

**Comment by dsyme** [comment]
Great!!

**Pull request closed without merging**
