### PR TITLE
Add failing test for unused opens

### PR DESCRIPTION
**Pull request by auduchinok**
Repro for #4664.

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it on live VS:

image

No exceptions.

**Comment by auduchinok** [comment]
Hm. It looks I've managed to reproduce it in the branch with using `EnclosingEntity` only and the failure here is actually unrelated.
I'll update issue/PR.

**Comment by vasily-kirichenko** [comment]
@auduchinok I still cannot reproduce it on 15.7.1

**Comment by KevinRansom** [comment]
Thanks for this PR, however it looks to be quite out of date, please reopen, if you want to continue with it.

Kevin

**Pull request closed without merging**
