### PR TITLE
Remove minimumElement and maximumElement from Set module

### PR DESCRIPTION
**Pull request by PatrickMcDonald**
Fixes Microsoft/visualfsharp#4297

If you want to take this but need an RFC as it's a surface area change then I can look after that, there are definitely better ways for you to spend your time.  Also you may not want to add a minumumElement property to the F# surface area, so feel free to just close this.

### CODE REVIEW

**Comment by dsyme** [comment]
What about the signature file?

**Comment by PatrickMcDonald** [comment]
Okay, it looks like Mim[iu]mumElement is not part of the public surface for SetModule

Am I right in thinking that if minimumElement is defined in module Set in Set.fs and not in set.fsi, then it is available in neither F# nor C# projects?

In which case we can remove MinimumElement (and MaximumElement) from SetModule and change any references to MinElement (or MaxElement) in FSharp.Core

```C#
namespace CSharpConsole
{
    internal static class Program
    {
        private static void Main(string[] args)
        {
            System.Console.WriteLine("C#");
            System.Console.WriteLine();

            var set = new Microsoft.FSharp.Collections.FSharpSet<int>(new[] { 5, 4, 7 });

            System.Console.WriteLine($"set.MinimumElement: {set.MinimumElement}");
            System.Console.WriteLine($"SetModule.MinElement(set) {Microsoft.FSharp.Collections.SetModule.MinElement(set)}");
            //Console.WriteLine($"SetModule.MinumumElement(set) {SetModule.MinumumElement(set)}"); // syntax error
            System.Console.WriteLine();
        }
    }
}
```

```F#
[<EntryPoint>]
let main argv =
    printfn "F#"
    printfn ""

    let s =
        [5; 4; 7]
        |> Set

    printfn "s.MinimumElement: %d" s.MinimumElement
    printfn "Set.minElement s: %d" <| Set.minElement s
    printfn ""

    0 // return an integer exit code
```

**Comment by KevinRansom** [comment]
@dsyme It doesn't look as if minimumElement makes it into the built assembly.  It is printed in the text version of the sigfile produced with 

-sig:foo.sig

I don't see how anyone could actually write some code dependent on it, so it would seem as if Patricks suggestion to lose it and refactor would work fine.  Is there any way a developer can actually depend on MinumumElement?

**Comment by dsyme** [comment]
@KevinRansom Correct, it can't be accessed, it's dead code.  We provided the property ``x.MinimumElement`` instead.

@PatrickMcDonald Can you adjust the PR to just remove the code instead? thanks

**Comment by PatrickMcDonald** [comment]
That was all quite confusing, hopefully it's less confusing now :)

**Comment by KevinRansom** [comment]
@PatrickMcDonald finding dead code is hard.  Thanks for taking care of this.

**Comment by KevinRansom** [comment]
@PatrickMcDonald 

Thank you for this

**Comment by realvictorprm** [comment]
This was funny to read, thanks for fixing @PatrickMcDonald :smile:

**Pull request merged**
