### PR TITLE
And then there were two compiler DLLs

### PR DESCRIPTION
**Pull request by dsyme**
Currently we have three

* ``FSharp.Compiler.dll``  (used by fsc.exe, fsi.exe, fsiAnyCpu.exe)
* ``FSharp.LanguageService.Compiler.dll`` (used by Visual F# IDE Tools)
* ``FSharp.Compiler.Service.dll`` (in nuget package, for general consumption, not used in product)

I'd like to simplify these two

* ``FSharp.Compiler.Private.dll``  (used by fsc.exe, fsi.exe, fsiAnyCpu.exe, Visual F# IDE Tools)
* ``FSharp.Compiler.Service.dll`` (in nuget package, for general consumption, not used in product))

This has **huge** long term advantages:

1. align the Visual F# Tools view of the world with the rest of the F# multiverse (with the exception that they use an internal, private build of FSharp.Compiler.Service).  

2. allow us to reasonably develop and use the FSharp.Compiler.Service component in this repo.  That applies whether 

3. allow us to progress the design and engineering of the FSharp.Compiler.Service component, e.g. start removing non-testing uses of InternalsVisibleTo, keep documenting the API and auto-publish the docs (useful for compiler developers, an old version is [her](http://fsharp.github.io/FSharp.Compiler.Service/)

### CODE REVIEW

**Comment by dsyme** [comment]
Note there are still advantage to using a differently-named internal copy of FCS, especially for fsi.exe - if we didn't do this then you could never ``#r "FSharp.Compiler.Service.dll`` from F# Interactive itself

**Comment by matthid** [comment]
> Note there are still advantage to using a differently-named internal copy of FCS, especially for fsi.exe - if we didn't do this then you could never #r "FSharp.Compiler.Service.dll from F# Interactive itself

I'm not sure I agree with this. We already had the situation for example in FAKE + FSF and it worked out better than expected. In the end, we now have a build step to rename `FSharp.Compiler.Service` to `FAKE.FSharp.Compiler.Service` which is a PIA (but we did it not for the reason you mentioned).

In the end, it all boiled down to having assembly redirection in FAKE itself so it was not possible for FAKE users to load a different `FSharp.Compiler.Service.dll` version. This was the reason we decided to do the renaming. But if you don't have those redirects I can image that it would work out OKisch?

By the way, this is a good step in the right direction, thanks!

**Comment by 7sharp9** [comment]
# **I am happy.**

**Comment by matthid** [comment]
I don't think the message/question I indended didn't was formulated as I wanted it to, sorry.

@dsyme What I wanted to know is why you think we cannot do `#r "FSharp.Compiler.Service.dll`? And is there a general solution to this? We already have this problem in the ecosystem and I'd like to have a solution if there is a problem... (Or maybe even just understand problems if they appear in this constellation)

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
> @dsyme What I wanted to know is why you think we cannot do #r "FSharp.Compiler.Service.dll? And is there a general solution to this? We already have this problem in the ecosystem and I'd like to have a solution if there is a problem... (Or maybe even just understand problems if they appear in this constellation)

From FSI.EXE you can do this and will be able to continue to do it, since FSI.EXE uses FSharp.Compiler.Service.Private.dll in its implementation.  

But you can't do it from FAKE, which uses FSharp.Compiler.Service.dll.

The underlying problem is that it is really hard to accurately load two separate copies of the FCS DLL in processes in .NET Framework.  You can do it, but it is very easy to get wrong and not a scenario I really want to support until 100% necessary

A workaround might be for us to make FSharp.Compiler.Service.Private.dll available as a (not-so-private)  nuget package specifically for inclusion as the F# implementation in scripting engines where those scripting engines might reasonably reference FSharp.Compiler.Service.dll.  You could play this "onion shell" game multiple times of course (FSharp.Compiler.Service.ReallyPrivate.dll, FSharp.Compiler.Service.ReallyReallyPrivate.dll etc.).

**Comment by matthid** [comment]
@dsyme uah thanks

**Comment by dsyme** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
This is ready to merge

**Pull request merged**
