### PR TITLE
Fix compiler generated flag for auto properties fields

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/2973

image

### CODE REVIEW

**Comment by dsyme** [comment]
@vasily-kirichenko The fix for this should be right - should I reopen and patch up the tests?

**Comment by vasily-kirichenko** [comment]
@dsyme yes, please. I just gave up trying to understand why fixing `compgen` flag for `xxx@` symbols caused read-only properties to be returned in completion inside constructors.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@vasily-kirichenko @dsyme ... is the remaining work on this just to get the tests passing?

**Comment by vasily-kirichenko** [comment]
@KevinRansom the tests are good, the code should be fixed, not the tests.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by TIHan** [comment]
@dotnet-bot test this please

**Comment by realvictorprm** [comment]
what's the problem now?

**Comment by TIHan** [comment]
The behavior of the first two failing tests do not match the reality of using VS. Therefore, these tests are not to be entirely trusted. It is worrisome that they fail and will need to dig into why it exactly fails. I will do this.

**Comment by realvictorprm** [comment]
Understood, I was already starting to look into this too so we can keep in touch to solve this problem faster if possible.

**Comment by TIHan** [comment]
The changes made in the PR do not give entirely the expected behavior based on the screenshot in the first post. While the "@"'s go away, not all the expected properties appear. But, the PR might be correct in removing the "@"'s and just so happens we are uncovering other problems with object initialization.

Example:

no_at
Here you don't see the WritableProp and we shouldn't see the ReadonlyProp.

@vasily-kirichenko It depends on what you would want to do. We can move forward with the PR and sort through the rest of the failures and accept, then fix the other issues with object initialization with more PRs. Or, in the current PR, resolve more issues with object initialization alongside removal of the "@"'s.

When this PR gets merged: https://github.com/Microsoft/visualfsharp/pull/3955 - There will be tests in there to verify correct behavior with object initialization for completions.

**Comment by realvictorprm** [comment]
@TIHan To my background here:
I'm interested in this because for the Code Lens it's needed to filter out auto-generated members, properties etc. and I noticed there that even simple examples were not marked as auto-generated although they should have been.

**Comment by TIHan** [comment]
I made a mistake when testing this as I didn't include the ending paren. Ex: ```My(foo)```

Without the ending paren, we don't know what completion context we are in. With it, we know we are calling a method.

I do see the behavior of the read-only property showing up, so I can dig into it a bit further to see what's happening.

**Comment by TIHan** [comment]
The readonly property appears in the list because the property is part of one of the captured NameResolutionEnvs and the service just so happens to be picking the environment [here](https://github.com/Microsoft/visualfsharp/blob/ee05187fa05bb400c043185e8143d27fff798acd/src/fsharp/vs/service.fs#L192).

The readonly property is added to the env [here](https://github.com/Microsoft/visualfsharp/blob/ee05187fa05bb400c043185e8143d27fff798acd/src/fsharp/TypeChecker.fs#L1555) as a "fake" valref. The ```AddFakeNamedValRefToNameEnv``` has this comment: `// This entrypoint is used to add some extra items to the environment for Visual Studio, e.g. static members ` There probably is a reason for this, but I haven't found that part yet.

There are different places where we can fix the issue. We could fix it in the CompletionProvider when calling a method by filtering out `Item.Value` that have ValRefs as properties. Or we could do the filtering [here](https://github.com/Microsoft/visualfsharp/blob/ee05187fa05bb400c043185e8143d27fff798acd/src/fsharp/NameResolution.fs#L3361) as ```IsValUnseen```.

I think ```IsValUnseen``` might be promising, but what I really want to know is why we are adding it as a "fake" valref.

**Comment by dsyme** [comment]
@TIHan The impact of the ``AddFakeNamedValRefToNameEnv`` call looks odd - I don't understand why that environment would be being selected at the _usage_ site.   The range for the subsequent ``CallEnvSink `` call for that environment is just ``vspec.Range`` - which should be a small range over just the identifier for the readonly property (it's possible that the range is wrong for the case of an auto-generated property - if so that could be an indication of the underlying problem). 

IIRC the purposes of ``AddFakeNamedValRefToNameEnv`` was just to make sure the name resolution environment contained this as the primary resolution for the name at the text of the declaration identifier.  This was in the days when we only used environments for all symbol resolution - these days we only use them as a "last resort" if no other name resolutions have been recorded at a particular source location.

**Comment by TIHan** [comment]
@dsyme I'll look into the ranges to see.

**Comment by TIHan** [comment]
Here is a little bit of what's happening:

#

```fsharp
type A() =  
    member val SettableProperty = 1 with get, set
    member val AnotherSettableProperty = 1 with get, set
    member val NonSettableProperty = 1

let _ = A(Non)
```
This will give me the NonSettableProperty.

#

```fsharp
type A() =  
    member val SettableProperty = 1 with get, set
    member val AnotherSettableProperty = 1 with get, set
    member val NonSettableProperty = 1

let x = A(Non)
```
This will not.

#

The difference is, the first one is choosing the env with the "NonSettableProperty" defined. The second one is choosing "let x". The reason why is that the first one doesn't have an env for "let _", so its best choice is the one with "NonSettableProperty".

**Comment by TIHan** [comment]
I believe the ranges are fine from my perspective. Maybe we could figure out how to grab a better env later on.

I fixed the readonly property. I found where members needed to be filtered and made those changes in this PR: https://github.com/Microsoft/visualfsharp/pull/4036

Once that PR passes, I will merge this one.

**Comment by TIHan** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build  please

**Comment by TIHan** [comment]
@vasily-kirichenko The other PR that added the fix for readonly was merged first, therefore your history of your change got squashed. I apologize that we did this. The plan was to merge yours first, then the other; that way you are listed in the commit history. I want to acknowledge this was your work that helped us figure the rest of it out.

@KevinRansom it might be a good idea to discuss squashing commits. It doesn't seem like a good idea since we lose history. If a PR has 5 contributors that did the work, and we squash the commits, then only the person who made the PR gets credit.

From https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/ 
``
When a pull request is merged and commits are squashed, only the user that merged the pull request and the user that opened the pull request receive contribution credit. No other contributors to the pull request will receive contribution credit.
``

This could be a case by case basis, but even then, it is still good to have a full history. If we are worried about clean-cut commits, then it should be the responsibility of the person making the commits for it to be clean as it can. I'm guilty of non-clean commits too.

**Pull request merged**
