### PR TITLE
Remove SQM usage

### PR DESCRIPTION
**Pull request by jaredpar**
SQM is being deprecated as our telemetry mechanism.  It is being removed entirely at this point from the Visual Studio related code bases to prevent accidental consumption.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @otawfik-ms

**Comment by heejaechang** [comment]
:+1:

**Comment by otawfik-ms** [comment]
@jaredpar there is a compiler flag and a few options that are still handling SQM logging. Shouldn't they be removed as well?

**Comment by jaredpar** [comment]
@otawfik-ms yes in the long term.  In the short term (i.e. today) we needed to verify the VS service was no longer used.  I'm going to have a follow up PR / Issue to deal with the command line section.

**Comment by otawfik-ms** [comment]
:+1:  on the follow up Issue.

**Comment by cartermp** [comment]
Flag: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/fsc.fs#L66

IIRC it ultimately calls into a `.dll` - @KevinRansom is this one it? https://github.com/Microsoft/visualfsharp/blob/master/lkg/FSharp-14.0.23413.0/bin/FSharp.VsSqmMulti.dll

**Comment by jaredpar** [comment]
@cartermp i believe that code you referenced is dead.  There are no definitions / uses of `SqmLogger` except in that specific line you tagged.

**Pull request merged**
