### PR TITLE
WIP: Trying to create minimal dependency config that works for coreclr

### PR DESCRIPTION
**Pull request by forki**
I'm trying to find out what's needed to build the project without nuget.exe. This is not meant to be merged - it's just an experiment. I would use a different project, but this is the only F# project that compiles for me on coreclr.

- [x] - committed packages folder
- [x] - removed nuget.exe

### CODE REVIEW

**Comment by forki** [comment]
@KevinRansom you have CompileProj.fsx and DeployProj.fsx but still DNX is involved for compilation. Why?

**Comment by KevinRansom** [comment]
@forki compileproj and deployproj are temporary work arounds to enable testing.  Eventually there will be tooling that takes care of those things.  For now, because we are in the middle of the development cycle we use what we can.

CompileProj is simply a helper to make building tests from the command line less painfull.  And yet it still has a hundred million parameters, sorry about that.   Deploy is simply to collect all of the necessary dependencies in a single place so I can copy them to a unix box, or test 64 bit or 32 bit windows, and make the nugets of the compiler, which are also temporary placeholders.

Eventyually the buildtools will have similar functionality I expect and so the build will be able to automagically produce the required specified deployments

Does that makes sense?

Kevin

**Comment by forki** [comment]
Yes that's helpful.

next question (sorry for being so annoying): the project.json.lock files are commited. so I assumed theproject.json files are not needed. But seems they are - otherwise I get compile error. Why is that?

**Comment by KevinRansom** [comment]
I think of the lock files as a temporary log of what the last compile did.  They needn't really be committed, I think if I used tfs with it's penchant for locking files I wouldn't commit it.  However, committing them does no harm.  You will note that fsc, fsi, coreclr and the tests all have different project json files.  I think eventually there will be no upfront nuget restore, TBH --- I can't remember now whether there is, how it's done on suave is more like how I imagine all builds will go eventually.  That is restoring seperately for each specific project build into a unified package cache.  The current F# OSS build has a very long way to go before it is what I would consider good.  Also, I expect individual binaries to be built into nugets before long, and for those nugget packages to be referenced via project.json rather than a references section in msbuild.  etc ...

But most of this is just a vague sort of goal in my head rather than a committed plan.

**Comment by forki** [comment]
ok I think I need to clarify: in the current step I don't want to get rid of the project.json.lock files. It seems all the tooling (incl. the temporary CompileProj and DeployProj) seem to be heavily depending on the files. What I want to trry is to do is get rid of the dependencies block in the project.json files.
I mean all that information is expanded into project.json.lock, right?

**Comment by KevinRansom** [comment]
I believe that the lock.json is used by tools to ensure that resolution isn't done more than once, so it doesn't really matter where the dependencies are specified and resolved, if a tool produced a project.json.lock then the remainder of the tooling would work fine.  I can't promise that of course, also I don't know if it will hold true forever, but it seems like a reasonable assumption.

**Comment by forki** [comment]
that's what I wanted to find out. But it seems that this is not the case.

In f351b53 I removed the dependencies from project.json. I still have the project.json.lock in place. But compile fails. If we can make this work, then I see a chance to make Paket work with F# coreclr projects.

**Comment by KevinRansom** [comment]
Was the failure that it didn't find any assemblies to reference?

**Comment by KevinRansom** [comment]
If it was I think you will need to have a build task that reads paket.dependencies to get the list of references, and then grok project.json to create the actual msbuild references and paths.

**Comment by forki** [comment]
I don't want to create a build task at this point. I just want to see if we can live without the dependencies block in project.json - given the project.json.lock is already there.

image

The error I get is that System.Runtime.dll can't be found

**Comment by KevinRansom** [comment]
can you paste the fsc command line that was generated by msbuild?

**Comment by forki** [comment]
can I somehow see that from https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.965 ?

**Comment by KevinRansom** [comment]
add /v:diag to the msbuild line for the fsharp-library.fsproj

**Comment by forki** [comment]
https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.966 what are we looking for?

**Comment by KevinRansom** [comment]
Would it be terribly disappointing if I said ... I don't know, but we will be looking at the references generated on the command line.

**Comment by forki** [comment]
Like line 5364 in the output? https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.966#L5364

**Comment by KevinRansom** [comment]
Okay look at this command line ...

There were no references to assemblies specified on the command line, and so the compiler couldn't find the assemblies it needed to reference:

There is a build task somewhere that reads the project json gets the list of dependencies, then reads the project lock.json to find out where the files are and builds the msbuild References list.  You will need an equivalent of that,  Although I expect you can reuse the project.lock.json from the existing msbuild implementation.

I have a meeting at 9:00 so I will go dark for a while, after that we can chat more if you want.

..\..\..\Proto\net40\bin\fsc-proto.exe -o:obj\Release\coreclr\FSharp.Core.dll -g --debug:pdbonly --noframework --baseaddress:0x05000000 --define:STRONG_NAME_AND_DELAY_SIGN_FSHARP_COMPILER_WITH_MSFT_KEY --define:RUNTIME --define:TRACE --define:OPEN_BUILD --define:FSHARP_CORE_4_5 --define:FX_NO_BEGINEND_READWRITE --define:FX_ATLEAST_45 --define:FX_ATLEAST_40 --define:FX_ATLEAST_35 --define:FX_ATLEAST_PORTABLE --define:QUERIES_IN_FSLIB --define:PUT_TYPE_PROVIDERS_IN_FSCORE --define:FX_ATLEAST_LINQ --define:FX_RESHAPED_GLOBALIZATION --define:FX_RESHAPED_REFLECTION --define:FX_RESHAPED_REFLECTION_CORECLR --define:RESHAPED_MSBUILD --define:FX_NO_CONVERTER --define:FX_NO_ARRAY_LONG_LENGTH --define:FX_NO_EXIT --define:FX_NO_DEFAULT_DEPENDENCY_TYPE --define:FX_NO_BINARY_SERIALIZATION --define:FX_NO_CUSTOMATTRIBUTEDATA --define:FX_NO_REFLECTION_MODULE_HANDLES --define:FX_NO_WEB_CLIENT --define:FX_EVENTWAITHANDLE_NO_IDISPOSABLE --define:FX_NO_EXIT_CONTEXT_FLAGS --define:FX_NO_WAITONE_MILLISECONDS --define:FX_NO_PARAMETERIZED_THREAD_START --define:FX_NO_THREAD --define:FX_NO_SECURITY_PERMISSIONS --define:NO_HEAPTERMINATION --define:FX_REDUCED_EXCEPTIONS --define:FX_NO_PDB_READER --define:FX_NO_PDB_WRITER --define:FX_NO_SYMBOLSTORE --define:FX_NO_LINKEDRESOURCES --define:FX_NO_KEY_SIGNING --define:FX_RESHAPED_REFEMIT --define:FX_NO_APP_DOMAINS --define:FX_NO_SYSTEM_CONFIGURATION --define:FX_RESHAPED_CONSOLE --define:FX_NO_RUNTIMEENVIRONMENT --define:NO_LOGGING_GUI --define:NO_WIN_REGISTRY --define:SIGNED --doc:..\..\..\Release\coreclr\bin\FSharp.Core.xml --keyfile:MSFT.snk --optimize+ 
--resource:obj\Release\coreclr\FSCore.resources 
--target:library --nowarn:69,65,54,61,75,45,55,62,75,1204 --warn:3 --warnaserror --warnaserror:76 --fullpaths --flaterrors --highentropyva-  --times --warnon:1182 --compiling-fslib --optimize --maxerrors:20 --extraoptimizationloops:1  --targetprofile:netcore --version:4.4.0.9055 --delaysign+ --keyfile:"..\..\fsharp\msft.pubkey" prim-types-prelude.fsi prim-types-prelude.fs SR.fs prim-types.fsi prim-types.fs local.fsi local.fs array2.fsi array2.fs option.fsi option.fs collections.fsi collections.fs seq.fsi seq.fs string.fsi string.fs list.fsi list.fs array.fsi array.fs array3.fsi array3.fs map.fsi map.fs set.fsi set.fs ..\..\utils\reshaped_reflection.fs reflect.fsi reflect.fs event.fsi event.fs math\n.fsi math\n.fs math\z.fsi math\z.fs ..\..\utils\sformat.fsi ..\..\utils\sformat.fs printf.fsi printf.fs quotations.fsi quotations.fs nativeptr.fsi nativeptr.fs control.fsi control.fs Linq.fsi Linq.fs MutableTuple.fs QueryExtensions.fs Query.fsi Query.fs SI.fs fslib-extra-pervasives.fsi fslib-extra-pervasives.fs ..\..\assemblyinfo\assemblyinfo.FSharp.Core.dll.fs "C:\Users\appveyor\AppData\Local\Temp\1\.NETPortable,Version=v4.5,Profile=profile7.AssemblyAttributes.fs"  (TaskId:20)

**Comment by forki** [comment]
@ctaggart @Mpdreamz @nosami does anyone know where such a task might live in coreclr land?

**Comment by forki** [comment]
Is it part of https://github.com/dotnet/buildtools?

**Comment by KevinRansom** [comment]
It's wired into msbuild here:  %ProgramFiles(x86)%\MSBuild\14.0\Microsoft.Common.Targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets

the assemblies can be found here:
%ProgramFiles(x86)%\MSBuild\Microsoft\NuGet

The source I think is on GitHub .

**Comment by forki** [comment]
Looks like I don't even have Microsoft.NuGet.ImportAfter.targets on my machine. So i guess it's https://github.com/Microsoft/visualfsharp/blob/coreclr/src/FSharpSource.targets#L792

**Comment by forki** [comment]
https://github.com/Microsoft/visualfsharp/blob/coreclr/src/FSharpSource.targets#L792 seems it's not this. If I go to  9894a13, and remove the dnx call in packageresolve.targets then everythings still works.

where is the Microsoft.NuGet.ImportAfter.targets included? Maybe I'm just not finding it.

**Comment by forki** [comment]
I also tried to grep for "Microsoft.NuGet.ImportAfter.targets" in the visualfsharp source. zero results.

**Comment by forki** [comment]
Kevin, can you please tell me where that target is referenced in the F# sources. Maybe I can then try to find it.

**Comment by forki** [comment]
image

**Comment by Alxandr** [comment]
I avoid MSBuid with everything I do, so if that's your question, then no. I have no clue. Regarding `project.json` vs `project.lock.json`, don't check in `project.lock.json`. That's begging for merge conflicts. Also the file is dependent on software installed on the end machine in many cases, so it generally needs to be re-genned at whatever node is doing the compile.

**Comment by forki** [comment]
I have no longer interest in making tis work. see https://github.com/fsprojects/Paket/issues/1230#issuecomment-157716308

**Comment by enricosada** [comment]
Really sad

**Pull request closed without merging**
