### PR TITLE
Reduce memory allocations

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
(edited: KR):  Previous PR thread:  reduce allocations #1207

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
OK, I understand the changes in scanUntilSentinel now - I hadn't noticed the function was being passed around as a first class value.

**Comment by KevinRansom** [comment]
Looks good to me,

**Comment by dsyme** [comment]
Yes, this is good - I will merge it.

**Comment by dsyme** [comment]
@vasily-kirichenko Thanks for persevering with us on this, and resubmitting  :)

**Comment by vasily-kirichenko** [comment]
:) It's only sad that it's not speed the compiler up.

**Pull request merged**
