### PR TITLE
fix anon recd creation bug (#6434)

### LINKED ISSUE #6434: Compiler crashes if an anonymous record passed as obj argument
Try to compile this:

```fsharp
module AnonRecordBug.T

let foo (_: obj) = ()

let bar() = foo {| F = 1 |}
```

Result (compiler crashes):

> parameter error FS0192: error : the anonymous record <>f__AnonymousType332488747`1' has not been generated in the pre-phase of generating this module

@dsyme

### PR DESCRIPTION
**Pull request by dsyme**
Fixes #6434 

We were missing the creation of anonymous records if they didn't appear in a type signature anywhere

Also make anonymous record generation slightly simpler and more efficient.

### CODE REVIEW

**Comment by dsyme** [comment]
Also fixes #6572 

@cartermp These can be included as part of a roll up of anon record fixes along with #6619  and #6608

**Comment by isaacabraham** [comment]
@cartermp Do you know which version of .NET Core this fix was rolled out with?

**Comment by cartermp** [comment]
@isaacabraham It's available in the latest preview, but other than that, no. We don't manually insert our compiler into the SDK anymore, so the answer to questions like this is generally, "when it undergoes automatic dependency update".

**Comment by KevinRansom** [comment]
It is in branch 16.3, so the preview for VS2019.3 should have it:
You can download it from here:
https://visualstudio.microsoft.com/vs/preview/

**Comment by isaacabraham** [comment]
Thanks both. I'm asking because I have that fix but someone else on the team doesn't - I have latest VS2019 update and NET Core 3 as well.

**Pull request merged**
