### PR TITLE
Further possible fix to reduce memory usage

### PR DESCRIPTION
**Pull request by dsyme**
@TIHan and others have noticed excessive creation of ILModuleReader.  Here's a second possible fix, to be evaluated

The first possible fix is at #6389

### CODE REVIEW

**Comment by dsyme** [comment]
@KevinRansom I prefer this one to #6389 

@TIHan What do you think?

@davidkean may also want to review

**Comment by KevinRansom** [comment]
Thanks

**Comment by brettfo** [comment]
FYI, I just had to revert this in #6468 due to a build failure in `master` (link in revert PR).

**Comment by KevinRansom** [comment]
Pr to fix build issue for #648:

**Comment by dsyme** [comment]
@auduchinok asked about this.  The use of two caches is explained by these two comments:
```
// Cache to extend the lifetime of a limited number of readers that are otherwise eligible for GC
...
// Cache to reuse readers that have already been created and are not yet GC'd
```

**Comment by TIHan** [comment]
I have evaluated this change and with the current internal project that I've been testing, this significantly reduced memory consumption after a find all refs. Before, we would reach 2.6gb in VS process, and now it hits 1.9gb specifically with this change.

This is fantastic.

I was wondering why our 16.1 preview was not hitting the 2.6gb limit.

**Pull request merged**
