### PR TITLE
[WIP] fix Internal error involving quotation of struct tuple

### PR DESCRIPTION
**Pull request by forki**
- [x] better error reporting
- [x] don't fail on struct
- [ ] emit correct structure

### CODE REVIEW

**Comment by forki** [comment]
@dsyme it looks like we don't have corresponding quotation elements. what do we do?

**Comment by dsyme** [comment]
@forki What error are you getting? My intuition (from a quick glance) is that there is an error in address-of conversion.

**Comment by forki** [comment]
It was a missing pattern match case. But I don't know what to do in that case

**Comment by dsyme** [comment]
@forki I'm closing in favour of https://github.com/Microsoft/visualfsharp/pull/3227, please review when you get the chance, thanks

**Pull request closed without merging**
