### PR TITLE
[FS-1037] Allow Union Constructor to deal with Flexible Types

### PR DESCRIPTION
**Pull request by liboz**
fixes https://github.com/fsharp/fsharp/issues/660

RFC https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1037-allow-union-constructors-to-deal-with-flexible-types.md

### CODE REVIEW

**Comment by liboz** [comment]
@dsyme @KevinRansom So, the one test that is failing has a specific case against this scenario. I've copied the relevant code below. I'm confused as to the benefit of allowing a function like `data` to work with subtyping, but not the union constructor `Data` especially since the function `data` can be defined as an alias for the union constructor `let data = Data`. Is there a specific problematic scenario we are trying to avoid here? 

```
type A() = 
    member x.P = 1

type B() = 
    inherit A()
    member x.P = 1

type Data = Data of A * A


let data (x,y) = Data (x,y)
let pAA = (new A(),new A()) 
let pBB = (new B(),new B())
let pAB = (new A(),new B())
let pBA = (new B(),new A())
pBB |> Data   // not permitted (questionable)
pAB |> Data   // not permitted (questionable)
pBA |> Data   // not permitted (questionable)
pBB |> data   // permitted
pAB |> data   // permitted
pBA |> data   // permitted
```

**Comment by dsyme** [comment]
@liboz I don't believe there's a specific reason to disallow this.  

In theory allowing it may be a breaking change, as it allows more general types to be inferred in some situations. Normally this is not a problem but perhaps the value restriction can some into play, I'm not sure.  So I'm in favor of adding this early in the F# 4.2 cycle and letting it settle.

Could you also please add tests for when the Union type is a struct, and for quotations of expressions involving ``Data`` (see quotes\test.fsx)

**Comment by liboz** [comment]
@brettfo Is that pull request related to this?

**Comment by brettfo** [comment]
No, and I offer my sincerest apologies. I'm an idiot and linked the wrong issue to the PR.

Sorry about that :smile:

**Comment by dsyme** [comment]
@liboz We should write an RFC for this - would you like to contribute that? thanks

**Comment by liboz** [comment]
@dsyme Created it here: https://github.com/fsharp/fslang-design/pull/220

**Comment by KevinRansom** [comment]
@dsyme ... can you take a look at this PR please?

**Comment by KevinRansom** [comment]
@dsyme any chance you will take a look at this?

**Comment by brettfo** [comment]
@liboz Can you rebase and retarget this PR to `master`?

**Comment by liboz** [comment]
@brettfo I did as you suggested. Can you reopen the PR?

**Comment by cartermp** [comment]
@liboz the dev15.6 branch is deleted, which disallows us from re-opening it. Once you retarget to the master branch then it can be re-opened.

**Comment by liboz** [comment]
@cartermp Should I open a new PR to do that?

**Comment by cartermp** [comment]
Yes, you can either do that or rebase and retarget this one. Either should work.

**Comment by abelbraaksma** [comment]
This was closed and the label removed for F# 4.5, without merge, is it dismissed or superseded? It is still linked from F# design suggestions, wondering if and update to the RFC is needed and/or re-linked to the superseding issue and/or closed if this wasn't pursued, see https://github.com/fsharp/fslang-design/blob/master/FSharp-4.5/FS-1037-subsumption-for-union-constructors.md

**Comment by cartermp** [comment]
@abelbraaksma The RFC is updated.

**Pull request closed without merging**
