### PR TITLE
Remove erroneously attached Obsolete attribute

### LINKED ISSUE #170: Seq.item fails compilation with "This construct is deprecated. please use Seq.item"
Verified this bug on both latest pre-release and previous one

Seq.item

Same error occurs for Seq.nth.

The implementation of Seq.item doesn't seem to be available in Seq. However according to [this](https://visualfsharp.codeplex.com/wikipage?title=Status) it looks like it should 

I am testing a little bit more will update this issue when I know more

### PR DESCRIPTION
**Pull request by mexx**
fixes #170

### CODE REVIEW

**Comment by forki** [comment]
Epic!

**Comment by forki** [comment]
I wonder why we didn't see this in the test project. IIRC we have tests for this function and run with "warnings as errors"

**Comment by mexx** [comment]
The tests in [SeqModule2.fs](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core.Unittests/FSharp.Core/Microsoft.FSharp.Collections/SeqModule2.fs) have `#nowarn "44"` turned on.
Both functions the one to be deprecated `nth` and `item` are tested in this one file, therefore this warning is not visible.

**Comment by forki** [comment]
Ok then we should extract ALL obsolete functions in new files and only suppress the warning for these explicit files.

**Comment by dsyme** [comment]
Ignore the AppVeyor failure, it wasn't properly configured.  If you'd like to re-run the job you can submit a harmless extra commit which will trigger it

**Comment by enricosada** [comment]
good use case of feature requested https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/3338653-allow-f-compiler-directives-like-nowarn-to-span

**Comment by forki** [comment]
I splitted the test modules and it seems this was the only mistake of this kind.

**Pull request closed without merging**
