### PR TITLE
Add FSI to Vsix and eliminate redundent dlls add to vsix

### LINKED ISSUE #188: EnableOpenSource VSIX does not install in VS2015 CTP 5
Build and Debug F# OSS using deployment.sln does not actually install the EnableOssDebug vsix.

### LINKED ISSUE #195: Question: Should "EnableOpenSource.vsix" contain these dlls?
When I open debug\net40\bin\EnableOpenSource.vsix as a ZIP file (after renaming it), it seems to contain a whole bunch of System.* and Microsoft.* DLLs.  Is this expected?

capture

### PR DESCRIPTION
**Pull request by KevinRansom**
fixes #188 and fixes #195 

2 commits, they overlap and would merge conflict.

1. Adds fsi to vsix, this enables oss build and debugging to integrate FSI without requiring patching.
2. Removes VS dependencies added by build to EnableOpenSourceDebug project.

untitled

### CODE REVIEW

**Comment by dsyme** [comment]
Looks good 

Do you know which FSharp.Core.{dll,optdata,sigdata} installation is being used by fsi.exe in this installation?    AFAIK the VSIX doesn't include the opdata/sigdata, so I can't figure out where fsi.exe is getting these from.

**Comment by latkin** [comment]
:+1: Thanks for removing the whitespace stuff form earlier PR :)

**Comment by KevinRansom** [comment]
@dsyme .... haha they are cunningly added to the output group of fsharp.core.proj and so are including in the vsix by the CopyToBuiltin build task.

**Comment by KevinRansom** [comment]
merged

**Pull request closed without merging**
