### PR TITLE
Turn off closed files diagnostic analysis & fix creating IncrementalBuilder when a file opens

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/2389

In short, Roslyn by default performs "closed files diagnostic" analysis, which means it calls all `DocumentDiagnosticsAnalyzer` derivatives for all file in current project, opened and closed, even if a single file changed. This resulted with calling `ParseAndCheckFileInProject` for all files, which in turn made `parseAndCheckFileInProjectCache` useless.

+ use predefined `BlockForCompletionItems` option instead of hand made one. Now completion feels  really non-blocking. 

This also fixes https://github.com/Microsoft/visualfsharp/issues/2324

1. `LanguageService.SetupProjectFile` is called every time a file is opening https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/LanguageService.fs#L298
2. It unconditionally called `UpdateProjectInfo` https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/LanguageService.fs#L307
3. The latter, in turn, called `Checker.InvalidateConfiguration` https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/LanguageService.fs#L117
4. It recreated `IncrementalBuilder` https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L2716 and replaced the old one.

I'm surprised anything worked at all :(

### CODE REVIEW

**Comment by Pilchie** [comment]
LGTM, but also tagging @heejaechang to take a look.

**Comment by dsyme** [comment]
@Pilchie @cartermp @vasily-kirichenko  This feels like it might cause considerable pain on VS2017 RTM?

**Comment by dsyme** [comment]
@vasily-kirichenko I think this also addresses https://github.com/Microsoft/visualfsharp/issues/1856? What do you think? thanks

**Comment by vasily-kirichenko** [comment]
Yes, it's a very annoying. Having your CPU busy all time is not what you like to have.

I'm not sure it turns off ProjectDiagnosticsAnalyzer (yes, it's commented out, but we will want to turn it on at some point).

**Comment by cartermp** [comment]
@dsyme Do you mean this PR, or the symptom it's addressing?  Closed File Diagnostics are off by default in C# as well, so I think this is a good change.

**Comment by dsyme** [comment]
@cartermp #1856 is not very clear and I didn't record a repro, I will close it since I think you guys are much clearer on the exact work that needs to be done :)

**Comment by heejaechang** [comment]
👍 and yes, it turns off ProjectDiagnosticAnalyzer now, but I am planning to turn it on soon.

**Comment by vasily-kirichenko** [comment]
:)

image

**Comment by dsyme** [comment]
@vasily-kirichenko That's fantastic!

**Comment by vasily-kirichenko** [comment]
@dsyme yeah, a couple of lines of code changes, but the effect is _huge_ :)

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Pull request merged**
