### PR TITLE
Avoid calling CanMemberSigsMatchUpToCheck twice

### PR DESCRIPTION
**Pull request by gmpl**
By upgrading the undo trace to an undo/redo trace we may avoid calling <code>CanMemberSigsMatchUpToCheck</code> twice in a common scenario.

If the second call to <code>FilterEachThenUndo</code> (the one for applicable methods) was performed then we can collect the effects of the call to <code>CanMemberSigsMatchUpToCheck</code> and avoid calling it again in the final checks.
The only difference between those two calls is the <code>alwaysCheckReturn</code> parameter which in the final checks must always be true, but that check can be performed by-hand after re-playing the trace.

Here's a [crazy-compile-time-test](https://gist.github.com/gmpl/5b3bda31f42ff220f4b4e265e1c407e7) with the following results:

```
val compileTime : float = 453586.2157  // before this PR (but after #1530)
val compileTime : float = 14454.7689   // after this PR
```

So in this case it will **speed up 30x** but it's clear that the speed up is exponential, so it will depend on the level of nesting.

For simple and no nested cases it's expected at least a 90% of the original time.

No other effect is expected since the modified code is equivalent to the original.

### CODE REVIEW

**Comment by forki** [comment]
Not sure if this is correct or working for real but I just wanted to say :kiss:

**Comment by gmpl** [comment]
Thanks @forki I can confirm you that this is really working !
I still need to take the time to do more benchmarks, but I can tell you that yesterday did play a bit after merging all my PRs and found out that experimental code I've written 5 years ago like [this](http://nut-cracker.azurewebsites.net/blog/2011/11/07/functions-for-n-tuples/) now it just works fine. Before it was taking insane compile times and the tuple size was bounded to 4 or 5 elements, now I can use even 8-uples and it just come back in milliseconds.
So code like that is now "usable" ;) 
When I have time I will do more benchmarks, including each PR.

**Comment by dsyme** [comment]
@gmpl Super interesting, and the technique looks sound and otherwise non-invasive to me.  Can't immediately tell why the speedup is exponential though - could you explain that more?  

A bit more documentation would be good, and move the "replay the trace" line to a ``trace.Replay`` call may make sense (so ``actions`` is only access in the type itself)

**Comment by gmpl** [comment]
Thanks @dsyme.
I think the speed-up in this and the other PRs are exponential, because for instance here <code>CanMemberSigsMatchUpToCheck</code> may internally call  <code>ResolveOverload</code> and so it will be called recursively.
It all depends if by resolving an overload x you need to resolve an overload y.
Before #1530 it was even more exponential, since it was nesting to solve the same constraint, now it's better but it depends on the client code, the example I show has nested overloads.

**Comment by KevinRansom** [comment]
@gmpl  Thank you for taking care of this.

Kevin

**Pull request merged**
