### PR TITLE
align netcore packages with netstandard1.6

### PR DESCRIPTION
**Pull request by cloudRoutine**
- fixed some project.json typos
- switched beta and preview packages to stable releases
- upgraded to netcoreapp1.1 [as suggested](https://github.com/Microsoft/visualfsharp/issues/2502#issuecomment-284269357)

### CODE REVIEW

**Comment by KevinRansom** [comment]
@cloudRoutine 

Yeah don't bother mate ...

**Comment by cloudRoutine** [comment]
did I do something wrong?

**Comment by dsyme** [comment]
@KevinRansom I'm curious too :) This may have been a preliminary step for @cloudRoutine to work on the .NET Standard 2.0 FSharp.Core - so am wondering what's up :)

**Comment by KevinRansom** [comment]
@cloudRoutine  No you did nothing wrong ...

@dsyme 
The build still requires an ancient version of dotnet.exe, uses project.json, the work to rationalize the build targets for coreclr/desktop .net is on the way.  Any of this work is very likely to be completely throw away.

The next release of the compiler will support and be built against DotNet standard 2.0 so aligning with released netstandard 1.6 packages temporarily is just churn as opposed to a necessary step.

That is all .. perhaps I should have been clearer at the time.  For that I am sorry ...

Kevin.

**Comment by dsyme** [comment]
@KevinRansom Ah ok, understood, thanks

**Comment by KevinRansom** [comment]
Apparently Ubuntu 16.04 needs :  "Microsoft.NETCore.Platforms": "1.1.0".  SO this turns out to be a timely piece of work ... thank you.

Kevin

**Comment by enricosada** [comment]
@cloudRoutine you need to use sdk `preview2.1` for netcoreapp1.1, instead of preview2

**Comment by KevinRansom** [comment]
@enricosada It's on my ever lengthening list of things to look at ... :-)

**Comment by enricosada** [comment]
@KevinRansom dont worry about that, i finished work for VSCode/FSAC, now i have plenty of time 😄 useless waste time on preview2.1, (but the @cloudRoutine fix of deps is good, but targeting netcore1.0 is better atm ihmo)

Next week i'll start to move `build coreclr` to ,net core sdk 1.0, using new fsproj (who support 1.0, 1.1 and 2.0). Obv we need to speak about goals and how to do that (with @brettfo too), but will be good (it's just a tooling update, i have idea how to share things like define with .props ).

**Comment by KevinRansom** [comment]
Sounds good.

**Comment by cloudRoutine** [comment]
fixed in https://github.com/Microsoft/visualfsharp/pull/2698

**Comment by dsyme** [comment]
@KevinRansom Just to mention that I'm keen to start looking at getting type providers up and running on .NET Standard 2.0.  But getting the build of FSharp.Core and the compiler is a pre-requisite for this.

**Pull request closed without merging**
