### PR TITLE
WIP: Create a FAKE Build

### PR DESCRIPTION
**Pull request by forki**
Orignally posted as https://visualfsharp.codeplex.com/SourceControl/network/forks/forki/fsharp/contribution/7167

I took @jack-pappas excellent work at https://visualfsharp.codeplex.com/SourceControl/network/forks/jackpappas/fsharpcontrib/contribution/7155 and converted it into a basic FAKE script.

It also contains fixes by @KevinRansom 

In order to test it run build.cmd as administrator. It then will download FAKE and run the build.fsx.

Also solves things like: https://github.com/Microsoft/visualfsharp/issues/3

I will try to rebase this and check if it still works.

### CODE REVIEW

**Comment by forki** [comment]
rebased on fsharp4

image

**Comment by forki** [comment]
I activated AppVeyor for my fork: https://ci.appveyor.com/project/SteffenForkmann/visualfsharp let's see how this works. (see also #53)

**Comment by jack-pappas** [comment]
This is great work, Steffen. I see the AppVeyor build completed successfully; is there any other work that needs to be done before merging this into the ``master`` or ``fsharp4`` branch? Anything the community can assist with?

**Comment by forki** [comment]
From my point of view: the DEVGUIDE and TESTGUIDE needs to be rewritten.

**Comment by brodyberg** [comment]
@forki Agree x1000 on devguide, added issue: https://github.com/Microsoft/visualfsharp/issues/64

**Comment by brodyberg** [comment]
Why the administrator requirement?

**Comment by forki** [comment]
https://github.com/Microsoft/visualfsharp/pull/15/files#diff-6074983490330a0aac1bd23c958232d7R57

https://github.com/Microsoft/visualfsharp/pull/15/files#diff-6074983490330a0aac1bd23c958232d7R173

**Comment by forki** [comment]
I set up a Travis build and will try to move things a bit forward. https://travis-ci.org/forki/visualfsharp

**Comment by forki** [comment]
Ok now I get:

     gacutil /i "lkg/FSharp-2.0.50726.900/bin/FSharp.Core.dll"
     Failure adding assembly lkg/FSharp-2.0.50726.900/bin/FSharp.Core.dll to the cache: gac directories could not be created, possibly permission issues.

Question is: do we really need this GACed for CI?

**Comment by dsyme** [comment]
I suspect not, though it's possible you may need a new binding redirect for one of the LKG tools if you don't have this

**Comment by latkin** [comment]
As it stands, yes you need that GACed or the powerpack tools won't run.

However, I have a change internally that removes the requirement for GACing FSharp.Core 2.0.50726.900, just need to get it checked in and that particular problem will go away.

Though adding fresh-built bits to the GAC, and NGen-ing them, will still be required to run tests. So these permissions issues still need to be resolved.

**Comment by dsyme** [comment]
@latkin @KevinRansom - Could we have a new label "Engineering Improvement" or something like that for this kind of issue and/or pull request?  (I suggest that all PRs and issues to have at least one label)

**Comment by latkin** [comment]
Have created the "infrastructure" label.

**Comment by enricosada** [comment]
removed file `tests\fsharpqa\testenv\bin\x86\diff.exe` is used by `tests\fsharp` test suite

**Comment by forki** [comment]
thanks. I restore the files.

**Comment by dungpa** [comment]
:+1:

**Comment by KevinRansom** [comment]
I think the appveyorcmd.bat, does a decent job of wrapping up the build.  It seems as if this is not really going anywhere.

Kevin

**Pull request closed without merging**
