### PR TITLE
Refactor bblock_instr2instrs to use for loops

### PR DESCRIPTION
**Pull request by forki**
@dsyme this is more a question than a real PR

What do we do if we find code that is probably working well, but looks ancient? I mean this part is using begin and end and strange while loop. It seems it's pattern matching twice against the inner list.

So the original code works, but looks not 100% idiomatic. A refactoring has risk. Should we do such thigns or should we just ignore it?

BTW: I don't claim the new one is better. Just wanted to ask for general strategy

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@forki, what does `bblock_instr2instrs` do?

are you able to call this code outside in small script / test?

I'd say before changing it for aesthetics, we should have it more thoroughly described and maybe have better grasp as expected input / output.

Are the for loops compiled with same efficiency than indexing into the array?

I think for this type of code change, small, sequential changes in separate commits will help the review:

* get rid of `ref` to favor `mutable`
* change `for to` to `for in`
* change `while` to `for to`

it preserves better guarantee that we don't change the behaviour than a single diff with more changes.

**Comment by dsyme** [comment]
@forki What you've done here is basic code sanitization and modernization from manifestly "old" code, I think it's fine to do this kind of cleanup, but yes you have to be careful w.r.t. risks.    

Basically cleanup and sanitization that can be compared line-for-line and is mechanical application of safe rules seems ok, as long as someone is willing to review it carefully.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by forki** [comment]
broken tests are unrelated

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
Thank you for taking care of this.

**Pull request merged**
