### PR TITLE
Use Jaro-Winkler distance to give better predictions - fixes #1863

### LINKED ISSUE #1863: Error message suggests strange types
image

In particular, I don't see how `Byte` can fit here.

/cc @forki

### PR DESCRIPTION
**Pull request by Rickasaurus**

### CODE REVIEW

**Comment by forki** [comment]
so happy to see this PR! 

awesome

**Comment by forki** [comment]
@Rickasaurus after you signed the CLA from https://cla.microsoft.com just close and reopen this PR. then the bot should reavaluate your CLA status and show the approriate status.

**Comment by forki** [comment]
Rick just said CLA is signed

**Comment by cartermp** [comment]
@martinwoodward looks like @Rickasaurus signed the CLI a while ago, but the bot isn't picking it up.  Any insights?

**Comment by martinwoodward** [comment]
I see the CLA was approved just over an hour ago - not sure why it took so long to come back sorry or why the bot hasn't picked it up. I'll email the CLA folks to ask but in the meantime I've manually labelled as CLA Signed.

**Comment by forki** [comment]
In other words: it was already approved and CLA is signed. So @dsyme @kevinransom please merge it ;-)

**Pull request merged**
