### PR TITLE
Highlight structs and use a higher contrast colour scheme in FSI

### LINKED ISSUE #2193: Types are not highlighted in FSI
Current master

image

### PR DESCRIPTION
**Pull request by saul**
Comparison of Windows, Mac and Ubuntu: https://imgur.com/a/q0zUA

Windows:
image

Prior to this PR, "DateTime" would not be highlighted.

Closes #2193 and #2194.

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
why not highlight records and DUs as well?

**Comment by saul** [comment]
Fixed using your colour scheme.

**Comment by forki** [comment]
please please please merge before RTM.

image

Is really hurting my eyes ;-)

**Comment by vasily-kirichenko** [comment]
Interesting, it still did not work for me until I added `UnknownType` case into the match. Now it works:

image

**Comment by vasily-kirichenko** [comment]
Hm, I've no idea why it works for records and DUs for you guys, according to https://github.com/Microsoft/visualfsharp/blob/ed948abaec8e2723c4fcafbde969a1071a4d72b1/src/fsharp/NicePrint.fs#L1580-L1584 they go to `TaggedText.UnknownType` category (I've checked in debugger).

@saul could you add `TaggedText.UnknownType` into the pattern match?

**Comment by vasily-kirichenko** [comment]
👍

**Comment by KevinRansom** [comment]
Thanks

**Comment by adelarsq** [comment]
@KevinRansom Is there any way to configure these colors? It's hard to see using light terminals.

**Pull request merged**
