### PR TITLE
Fix quick info for namespaces

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/2271

image

However, it does not show the tooltip at namespace declaration.

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
It's ready. 

Tooltip for namespace declaration is not shown in VS 2015 either. That's because there are no captured name resolutions for namespace declarations here https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L599

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by cartermp** [comment]
Very nice.

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
It's ready.

**Pull request merged**
