### PR TITLE
PrefixUnusedValueWithUnderscore code fix

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
image

### CODE REVIEW

**Comment by dungpa** [comment]
Can we do an all-occurrence fixer?

**Comment by vasily-kirichenko** [comment]
I think yes. Will try.

**Comment by vasily-kirichenko** [comment]
@dungpa it's desirable to use this base class http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs,21, which is not yet included even in `2.0.0-rc3` package https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.Features/2.0.0-rc3-61222-02 I think it's in `2.1.0-beta1`, I doubt we should use it.

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by isaacabraham** [comment]
Urgh :) can we have a variant that actually renames it to just _ as well?

**Comment by vasily-kirichenko** [comment]
@isaacabraham easy :)

**Comment by vasily-kirichenko** [comment]
@isaacabraham 

image

**Comment by isaacabraham** [comment]
Sweeet :)

**Comment by forki** [comment]
Just a question (I know it's not needed in this case): would it be possible to actually trigger a rename?

**Comment by vasily-kirichenko** [comment]
@forki the algorithm: 1. find a c#/vb code fix that does it 2. steal the implementation :)

**Pull request merged**
