### PR TITLE
show that #1020 is fixed

### PR DESCRIPTION
**Pull request by forki**
* this is the same commit as in https://github.com/Microsoft/visualfsharp/pull/1032 and it fails over there (on local build)
* this commit succeeds here

This suggests that this was indeed broken and is fixed now. Please merge this regression tests and then #1020 can be closed

### CODE REVIEW

**Comment by forki** [comment]
* this is the same commit as in https://github.com/Microsoft/visualfsharp/pull/1032 and it fails over there (on local build)
* this commit succeeds here

This suggests that this was indeed broken and is fixed now. Please merge this regression tests and then #1020 can be closed

**Comment by forki** [comment]
The first failing commit is c40ec8419e8890b3aa0d000f0eead9863587e28d "for expression optimization on lists and strings" by @mrange 
Seems it optimized a bit too much.

opt

**Comment by forki** [comment]
further testing revealed it was fixed by @dsyme in 261732c8b3d42d213710563f3ac19bb77da1600b

fixed

**Comment by dsyme** [comment]
Pulling if only because those GIFs are so great :) (and because' it's a testing issue)

**Pull request merged**
