### PR TITLE
Clarify what happens when you add existing key to Map

### LINKED ISSUE #524: Clarify what happens when you add existing key to Map
The documentation of both [`Map<'K, 'V>.Add`](https://github.com/svick/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core/map.fsi#L22) and [`Map.add<'K, 'V>`](https://github.com/svick/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core/map.fsi#L76) is silent on what happens when the key already exists in the `Map<'K, 'V>`. I believe this is an important case that should be documented explicitly.

### PR DESCRIPTION
**Pull request by svick**
Fixes #524.

### CODE REVIEW

**Comment by latkin** [comment]
I think it's ok to add a little bit of clarification here, but "overwritten" does not sit well.  Maps are immutable, the original value is still present (in the original tree), and was not overwritten:

```fsharp
let m1 = Map.ofList [ (1, "one"); (2, "two"); (3, "three") ]
let m2 = m |> Map.add 2 "new"

m1 |> Map.find 2  // "two"
m2 |> Map.find 2  // "new"
```

**Comment by svick** [comment]
So what would you suggest instead?

**Comment by PatrickMcDonald** [comment]
How about something like the following?

> If a binding with the given key already exists in the input map, the existing binding is replaced by the new binding in the result map.

**Comment by latkin** [comment]
That sounds good to me

**Comment by svick** [comment]
@PatrickMcDonald Ok, that sounds good to me too. Updated the commit.

**Comment by latkin** [comment]
Applied to OOB branch, thanks!

**Pull request closed without merging**
