### PR TITLE
Show "Move up"/"Move down" context menu items on folder nodes in the Solution Explorer

### LINKED ISSUE #2050: Move Up/Down context menu not available on folders, but Alt-Up/Down works
Move Up / Down is not available in the context menu when a folder is selected, however the functionality is there, so there seems no reason for removing it from the context menu.

## Repro steps

Rightclick on a folder in the solution explorer:

image

## Expected behavior

The options Move Up / Move Down should be available, similar to when you select a file:

image

## Actual behavior

Move Up / Move Down are not available.

## Known workarounds

Use the Alt + Up Arrow or Alt + Down Arrow key combinations.

## Related information 

The same applies to the functionality of Add Below, Add Above context menus.

* Visual Studio 2015, Update 3

### PR DESCRIPTION
**Pull request by saul**
Fixes #2050

### CODE REVIEW

**Comment by saul** [comment]
Just realised we should also have "Add Above" and "Add Below" on the folder context menu - I'm investigating now.

**Comment by vasily-kirichenko** [comment]
@saul does it work as expected?

**Comment by saul** [comment]
@vasily-kirichenko yes, see #2050 for what the problem was

**Comment by cartermp** [comment]
@saul This is great!

**Comment by KevinRansom** [comment]
@saul, when we get CPS this will need to be ported to the CPS based project system.

**Comment by KevinRansom** [comment]
@saul 

Thanks for this

Kevin

**Pull request merged**
