### PR TITLE
WIP:  TextWriter should not be called twice in fprintfn

### LINKED ISSUE #3712: Why is TextWriter called twice in fprintfn?
To me it seems that using the function` fprintfn (textWriter: System.IO.TextWriter) fmt ` first calls
`textWriter.Write(theFormatedString)`
and then 
`textWriter.WriteLine()`

wouldn't it be more idiomatic to just call ` textWriter.WriteLine(theFormatedString)`  once?

The `WriteLine(somestring`)  implementation on TextWriter seem to be not used at all.

My current implementation of TextWriter prints to the UI. It does also context switching and UI update, so calling it just once instead of twice would make sense. or not ?

https://github.com/Microsoft/visualfsharp/blob/81d162ce55bd4c4c8bcd1eb2a0832c442888ec0e/src/fsharp/FSharp.Core/printf.fs#L1346

### PR DESCRIPTION
**Pull request by forki**
Try to fix #3712

### CODE REVIEW

**Comment by forki** [comment]
image

oupsi ;-)

**Comment by forki** [comment]
Ok after debugging: printfn "%s %s" "hello" "World" is actually calling .Write 5 times and WriteLine once.

**Comment by forki** [comment]
It gets really weird for things like "%s%s" - our current approach will call write 3 times with empty string. If you do that in a loop then this meh

**Comment by forki** [comment]
And just to make it clear: it's not only calling the text writer unnecessary. It's also running through all internal printf infrastructure

**Comment by realvictorprm** [comment]
This does not sound good. I don't like unnecessary allocations :/

**Pull request closed without merging**
