### PR TITLE
[WIP] Enable graceful degradation of in-memory cross-project references when memory utilization is too high

### PR DESCRIPTION
**Pull request by dsyme**
We've known throughout VS2017 that in-memory cross project references are a memory expensive option in large solutions and we often recommend to turn this feature off for large solutions.

This uses the FCS MaxMemory check/event to turn of in-memory cross-project references and reduce active cache size when the active devenv.exe process reaches 2.3GB and F# project checking is in progress.  That figure is chosen because whenever I've seen devenv.exe get to that memory size things grind to a halt.

The message suggest to the user to explicitly turn off in-memory cross-project references

The prototype in the PR uses max memory of 400MB to trigger the condition.

TODO:
* [ ] The prototype pops a message box. Understand the right way to do this in VS.
* [ ] Localize the message
* [ ] increase the condition to 2.3GB

### CODE REVIEW

**Comment by dsyme** [comment]
@Pilchie @brettfo  Is there an easy way in VS managed code to pop a modal message box?  I presume using System.Windows.Forms.MessageBox.Show is not ok

**Comment by Pilchie** [comment]
In roslyn, import an [`INotificationService`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Notification/INotificationService.cs,2fe68887549cfdac,references).  To do it yourself, take a look at the [`VSDialogService`](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Notification/VSNotificationServiceFactory.cs,1224a8c8a22e5c01,references) implementation of it.

**Comment by saul** [comment]
Is there no way to make the notification appear as a banner rather than a dialog box? People press Space and Enter a _lot_ when they're in the IDE, which will mean this dialog box is immediately dismissed as soon as it pops up.

**Comment by cartermp** [comment]
Good idea @saul. The "Gold Bar" banner is actually already used for when VS detects a particular component affecting startup, so it would make sense to have a message there. @Pilchie is there an API we can use for that in Roslyn?

**Comment by dsyme** [comment]
I'm closing this since it's been awhile since I've seen 2GB men usage problems, and the PR is not complete

**Comment by cartermp** [comment]
@abelbraaksma I don't believe that this PR would help you unless you work with in memory cross-project references turned on at all times 😢

**Comment by dsyme** [comment]
> @dsyme, sure you want to close this? I'm above 2.3Gb multiple times a day and often forced to restart VS to get things moving again. With cross project references switched on this happens even more often.

I think it's still a good addition. However because it involves adding UI to VS (even just an alert) I'd rather the VS tools team pushes it through if customers need it. 

(My main personal work is on the compiler, language and Xamarin, and I generally focus on VS tooling to the extent that it is in good shape for my personal work, which it currently is)

I'll reopen in case someone wants to pick it up.

**Comment by dsyme** [comment]
I'm closing this.  I think we should have something like this (graceful degradation) but we discussed the use of an alert to tell the user of the condition and decided against it.

@cartermp @brettfo @TIHan @KevinRansom I'll leave this up to you guys.  I do think something like this would fundamentally improve the usabillity of the Visual F# Tools in the balance of things, though there are definitely pros and cons.

**Pull request closed without merging**
