### PR TITLE
Implement FS-1025: Improve record inference.

### PR DESCRIPTION
**Pull request by kurtschelfthout**
See [RFC](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1025-improve-record-type-inference.md).

This is my first proper fsc pull request so if I've done something odd, please point it out and bear with me, thanks!

As visible from the change, I expect this to be backwards compatible, it can only improve behaviour of the compiler: where it error'ed before, it will now work in some cases.

### CODE REVIEW

**Comment by kurtschelfthout** [comment]
The error in ci_part1 is caused by these files:

https://github.com/Microsoft/visualfsharp/blob/master/tests/fsharpqa/Source/Conformance/BasicTypeAndModuleDefinitions/RecordTypes/E_TypeInference01.fs
https://github.com/Microsoft/visualfsharp/blob/master/tests/fsharpqa/Source/Conformance/BasicTypeAndModuleDefinitions/RecordTypes/E_TypeInference01b.fs

This is exactly the case this PR is supposed to address. Any thoughts on the appropriate course of action?
* remove those tests altogether
* remove the ambiguous record types from the files (`Red` and `GRed`), I think that should make them fail as before
* something else

If not I'll try the second.

**Comment by forki** [comment]
I would go with option one. These cases are solved so no real value in keeping the tests

**Comment by kurtschelfthout** [comment]
@forki I couldn't find any other tests that check the error message when you try to instantiate a record with too few fields. So probably worth checking that.

**Comment by kurtschelfthout** [comment]
No idea why `bigint.fs` failed in the test run. Compiles locally.

**Comment by kurtschelfthout** [comment]
This test on AppVeyor seems to fail intermittently. Maybe it should be removed, or the "delta" should be made more lenient:

1) Failed : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Control.AsyncModule.AwaitWaitHandle.Timeout
  Delta is too big -16
  Expected: True
  But was:  False
at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Control.AsyncModule.AwaitWaitHandle.Timeout() in C:\projects\visualfsharp-3dtit\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Control\AsyncModule.fs:line 240
Run Settings
    RuntimeFramework: V4.0
    WorkDirectory: C:\projects\visualfsharp-3dtit\release\net40\bin
    NumberOfTestWorkers: 2

**Comment by forki** [comment]
Yes this one is unrelated

Am 13.11.2016 12:44 schrieb "Kurt Schelfthout" <notifications@github.com>:

**Comment by kurtschelfthout** [comment]
Major git screwup. Never mind.

**Pull request closed without merging**
