### PR TITLE
Fixed: no symbol use for underscored identifiers

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/2563

@dsyme do you know why type checker did not notify sink about underscored symbols?

### CODE REVIEW

**Comment by KevinRansom** [comment]
This change looks good but I will await approve from @dsyme .  Just in case there is a reason.

**Comment by dsyme** [comment]
I don't recall any good reason

**Comment by vasily-kirichenko** [comment]
The failing test:

for `member val AutoPropGetSet = 0 with get, set` 

`GetAllUsesOfAllSymbolsInFile` returns

`("__", "file1", ((27, 15), (27, 26)), []);`

image

I think it's defenetely compiler generated thing and the bug here is that `IsCompilerGenerated` is false.

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by dsyme** [comment]
Great :)

**Pull request merged**
