### PR TITLE
Try to reproduce #1296

### PR DESCRIPTION
**Pull request by forki**
references #1296

### CODE REVIEW

**Comment by forki** [comment]
fails on top of 0e1bf8dba200794245c1962cd5b64ab73b221d3f

**Comment by forki** [comment]
fails on top of 4e562f339ea4578c0ca6c9b784f2aa8f092079ac

**Comment by forki** [comment]
fails on top of 07567504d49b74bae0ab1f2955fd8eede3c1b27d

**Comment by forki** [comment]
fails on top of 790d634c09624299cecf769de5c42e41b512f960

**Comment by forki** [comment]
as @gmpl said it works on top of ba3fee7652c02512872e6e80f4d7c6b6767b15f8

**Comment by forki** [comment]
doesn't work on top of b7eb48eedb5c38bde8d7d47ef61954b9b0b00021

**Comment by dsyme** [comment]
Thank you so much for doing this.  I suspect the "mutrec" feature

**Comment by forki** [comment]
@dsyme yep that's basically what's left. I'm sure I can confirm in 10min ;-)

**Comment by forki** [comment]
doesn't work on top of f26b35b6b3963b464a6fbc7775ba738682b1da81

**Comment by forki** [comment]
works on top of 830a1d4379454d8876fd57b13c16e033c1a7eb1c but not on top of 7ff92d4c984a6a074da7a797538b256b6499c0fb

so #1132 (the mutrec thing) is definetly the cause.

I rebased this test on top of 7ff92d4c984a6a074da7a797538b256b6499c0fb

**Comment by dsyme** [comment]
Thanks.  I'll take a look today or tomorrow

**Comment by dsyme** [comment]
We ended up closing 1296 as by design, so I'll close this.  I'll add an RFC entry for the design change capture by 1296

**Comment by dsyme** [comment]
https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1018-adjust-extensions-method-scope.md

**Pull request closed without merging**
