### PR TITLE
Block Structure service

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
WIP

### CODE REVIEW

**Comment by forki** [comment]
does it belong to an issue? screenshot?

**Comment by cartermp** [comment]
@forki #1997

**Comment by vasily-kirichenko** [comment]
image

**Comment by vasily-kirichenko** [comment]
There are some quirks:

image

@cloudRoutine could you please looks at it? I remember you handled some ranges in special ways.

**Comment by cloudRoutine** [comment]
sure thing, but I probably won't get to it for a few hours. There were a few bugs in the UAST traversal I never got around to fixing and I wanted to make some adjustments so we can have it filter out the ranges for outlining and block structure simultaneously.

**Comment by vasily-kirichenko** [comment]
@cloudRoutine thanks!

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@vasily-kirichenko 

Thanks for taking care of this

Kevin

**Pull request merged**
