### PR TITLE
fix diagnostic priorities (dev 15.7)

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
I presume this is failing because we need to update roslyn version numbers

**Comment by dsyme** [comment]
Yes, we need a roslyn version number update for the new code in 15.7
```
  D:\j\w\release_ci_pa---c11de9d5\vsintegration\src\FSharp.Editor\Diagnostics\DocumentDiagnosticAnalyzer.fs(107,17): error FS0859: No abstract property was found that corresponds to this override [D:\j\w\release_ci_pa---c11de9d5\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj]
  D:\j\w\release_ci_pa---c11de9d5\vsintegration\src\FSharp.Editor\Diagnostics\SimplifyNameDiagnosticAnalyzer.fs(45,17): error FS0859: No abstract property was found that corresponds to this override [D:\j\w\release_ci_pa---c11de9d5\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj]
  D:\j\w\release_ci_pa---c11de9d5\vsintegration\src\FSharp.Editor\Diagnostics\UnusedDeclarationsAnalyzer.fs(97,17): error FS0859: No abstract property was found that corresponds to this override [D:\j\w\release_ci_pa---c11de9d5\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj]
  D:\j\w\release_ci_pa---c11de9d5\vsintegration\src\FSharp.Editor\Diagnostics\UnusedOpensDiagnosticAnalyzer.fs(38,17): error FS0859: No abstract property was found that corresponds to this override [D:\j\w\release_ci_pa---c11de9d5\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj]

```

**Comment by dsyme** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@brettfo Do you know if the the Roslyn binaries have been updated?

**Comment by cartermp** [comment]
@jasonmalinowski Should know as well.

**Comment by brettfo** [comment]
There were API changes in dev15.6 via #4037, but those changes have been in dev15.7 for a few weeks (maybe months) now.

**Comment by dsyme** [comment]
@brettfo There should be API changes coming in 15.7, corresponding to https://github.com/dotnet/roslyn/pull/24673.   We don't seem to have those yet

We really want to get this in for 15.7 if possible :) thanks

**Comment by brettfo** [comment]
I see, I was thinking of a different Roslyn change.

To consume these APIs you'll need to:

1.  Update the last line of `NuGet.config`:
``` diff
-https://dotnet.myget.org/F/roslyn-for-vs-for-mac/api/v3/index.json
+https://dotnet.myget.org/F/roslyn/api/v3/index.json
```
2.  Update `RoslynPackageVersion.txt` to a version from [here](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.Common) that starts with `2.7.0-beta3-*` that was created after dotnet/roslyn#24673 was merged, so probably any of the versions after Feb 13.

**Comment by dsyme** [comment]
@brettfo I tried 2.7.0-beta3-62707-11 but the Priority abstract member wasn't there

It is present in 2.8.0-beta2-62713-01, but there is one other change there in the signature of `QuickInfoDisplayDeferredContent` (easy to fix, but a binary API change)

Can we use `2.8.0-beta2-62713-01`?

thanks

**Comment by brettfo** [comment]
@dsyme I just checked today's build of the 15.7 preview (which version we can't exceed) and it's on `2.8.0-beta1-62707-12`, so we should choose something `<=` to that, still in the `2.8.0-beta1-*` train.

**Comment by dsyme** [comment]
@brettfo I fixed the PR so it is only pushing the diff, not stuff from master

**Comment by brettfo** [comment]
You should also update the last line of `NuGet.config`:
``` diff
-https://dotnet.myget.org/F/roslyn-for-vs-for-mac/api/v3/index.json
+https://dotnet.myget.org/F/roslyn/api/v3/index.json
```

The `roslyn-for-vs-for-mac` feed was added as a temporary stop-gap that Roslyn will eventually remove, but the `roslyn` feed will exist until the end of time.

**Comment by dsyme** [comment]
@brettfo Done - this is ready.  Will you merge back to master too?

**Comment by brettfo** [comment]
Yes.  When Dev15.7 RTM ships this branch will come back into master.

**Comment by cartermp** [comment]
WEW that was scary, since the green button in the GitHub UI said "commit merge"

**Pull request merged**
