### PR TITLE
Fix typo in printf signatures

### PR DESCRIPTION
**Pull request by taylorwood**

### CODE REVIEW

**Comment by forki** [comment]
Nice catch. LGTM.

**Comment by KevinRansom** [comment]
Nice thank you for this.

**Comment by taylorwood** [comment]
@KevinRansom I was about to delete my branch/fork but I saw this is "Closed with unmerged commits", should I keep it around until merged?

**Comment by KevinRansom** [comment]
It was committed 23 days ago, and thank you for the pr ☺

https://github.com/Microsoft/visualfsharp/pull/1001/commits/096bd0274db244e2fc3a75d423a68508df5cf15c

**Comment by taylorwood** [comment]
@KevinRansom yes committed to my fork/branch 23 days ago, but as far as I can tell these changes were never merged into the official repo? The files in the MSFT visualfsharp repo still have the typos.

**Pull request merged**
