### PR TITLE
use dirs and direct paths in fsproj over links

### PR DESCRIPTION
**Pull request by cloudRoutine**

### CODE REVIEW

**Comment by dsyme** [comment]
@vasily-kirichenko @brettfo Which do you prefer?  It feels like we just have one-file-per-feature anyway?

**Comment by vasily-kirichenko** [comment]
We used to use virtual dirs + link in VFPT and maintaining it was hard. Then I convert them to real dirs + no links and it's much more straightforward and natural. 

So I suggest to use single files laying right in project root for small features, and a real folder + bunch of files for larger ones.

**Comment by cloudRoutine** [comment]
@dsyme if we merge the features from VFPT into VF#, or implement more of the roslyn features, the amount of source files per folder will increase.  It also makes it nicer to peruse and search the code on github when the source files are grouped logically instead of everything being poured into the same box.

**Comment by dsyme** [comment]
OK. Sounds like using real folders may be the way to go.

**Comment by dsyme** [comment]
A similar question comes up for the tests.  I found myself removing the layer of virtual directories but I don't mind if they go back in.

**Comment by KevinRansom** [comment]
Thanks for taking care of this.

Kevin

**Pull request merged**
