### PR TITLE
Colorize F# signature help

### PR DESCRIPTION
**Pull request by dungpa**
Screenshot:

image

The text parsing part is ad hoc. I imagine we can make use of structured data for precise coloring once these changes landed https://github.com/Microsoft/visualfsharp/compare/master...vladima:vladima/classification

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Wow, cool.

**Comment by vasily-kirichenko** [comment]
> D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\TestLib.LanguageService.fs(361,17): error FS0074: The type referenced through 'Microsoft.VisualStudio.Text.Classification.IClassifier' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.VisualStudio.Text.Logic'. [D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\VisualFSharp.Unittests.fsproj]

**Comment by dungpa** [comment]
@vasily-kirichenko Thanks, fixed.

**Comment by cartermp** [comment]
@dungpa Awesome!

**Comment by KevinRansom** [comment]
@dungpa 
This is great thank you for this

Kevin

**Comment by vladima** [comment]
one step closer

classification in signature help
image

classfication in completion list
image

**Comment by vasily-kirichenko** [comment]
@vladima This is fantastic :) 

I think namespaces should not be colorized as types, should they? (I mean `System` namespace in "Exceptions" block on the second screenshot)

**Comment by dungpa** [comment]
@vladima Cool!

**Pull request merged**
