### PR TITLE
Cross-platform alignment: --gccerrors and --exename compiler options

### PR DESCRIPTION
**Pull request by dsyme**
This is part of a series of alignment PRs related to step (2) of the planning note https://github.com/Microsoft/visualfsharp/issues/589.

The cross-platform editions of F# (fsharp/fsharp and FSharp.Compiler.Service) implement two extra arguments:

* the ``--gccerrors`` flag which can be used to output errors in the format used by the GCC compiler, which is useful for some tooling like Emacs.

* the ``--exename`` flag that can be used to set the executable name (e.g. `fsharpi`) shown in the help text for F# Interactive - on Mono the `fsharpi` script sets this flag.

This adds these micro features to Visual F#, with the aim of long-term feature alignment and code repository alignment.  

Accepting this PR will reduce the need to always keep two separate repositories for the F# compiler and make it easier to transfer FCS code and functionality back into the Visual F# tools.

Tests for the compiler options have been added.  The options are in the category of tooling-related compiler options like `--vserrors` that are not given explicit documentation help.

### CODE REVIEW

**Comment by latkin** [comment]
I realize our test system is not an exemplar of tidy organization, but we should not be so careless to toss error format tests in with the typecheck tests, or things continue to worsen.

Something in `tests\fsharpqa\Source\CompilerOptions\fsc` would be much preferred - with some coverage for both single- and multi-line errors.

**Comment by dsyme** [comment]
Fixing this up

**Comment by dsyme** [comment]
I've fixed up the testing.

I've also included the `--exename` option used in the F# compiler open source release which improves the cosmetic appearance of the help output from F# Interactive when the `fsharpi` shell script is used to invoke Mono on fsi.exe .  (This will likely also be useful for F# on .NET Core as well if F# on .NET Core also provides an `fsharpi` script to invoke `dnx ...fsiAnyCpu.exe`)

**Comment by KevinRansom** [comment]
Committed, thank you for your contribution.

**Pull request closed without merging**
