### PR TITLE
Fix num bug in QueueList 

### LINKED ISSUE #4722: Any bug in QueueList?
https://github.com/Microsoft/visualfsharp/blob/5daaf8294ab0adcf1a19a77935966e5b3a30c32e/src/fsharp/QueueList.fs#L37
``` F#
member x.Append(ys:seq<_>) = QueueList(firstElements, (List.rev (Seq.toList ys) @ lastElementsRev), numLastElements+Seq.length ys))
```

counterexamples:
``` F#
let headQueue = ofSeq [1..5]
let tailQueue = ofSeq [1..100000]
let temp = append headQueue tailQueue
temp.ToList() |>ignore // call List.rev inside
temp.ToList() |> ignore // call List.rev again
```

### PR DESCRIPTION
**Pull request by forki**
fixes #4722

### CODE REVIEW

**Comment by brettfo** [comment]
Looks good, can you add a test?

**Comment by forki** [comment]
no. because it doesn't surface anywhere

**Comment by brettfo** [comment]
If it's not surfaced anywhere can we delete it?

**Comment by dsyme** [comment]
@brettfo Looks like the count of elements in the collection is used as part of a heuristic here: https://github.com/Microsoft/visualfsharp/pull/4727/files#diff-fdeacbc4b3c85e494b84658903f6e4f9R16

The fix is good, I don't think it will make any real difference either way but we may as well have correct code.

**Comment by forki** [comment]
Yes it only fixes the push heuristic

Don Syme <notifications@github.com> schrieb am Do., 19. Apr. 2018, 00:48:

**Pull request merged**
