### PR TITLE
Use the word "suggestions" and introduce threshold

### PR DESCRIPTION
**Pull request by forki**
This should help with https://github.com/Microsoft/visualfsharp/issues/2066

### CODE REVIEW

**Comment by KevinRansom** [comment]
@forki,

Steffen,

these compile error usability changes seem like they require a deep understanding of the compiler each time we make an improvement.  Do you think that there would be a benefit to going the Roslyn route and trying to see if we can use Analyzers to accomplish a similar outcome?

It seems to me that pursuing Analyzers have several benefits, 
1.  The most pronounced of which would be reducing the amount of Compiler knowledge in providing these additional capabilities.
2.  Allowing them to be opt-in behaviors rather than always there.
3.  Allowing the formatting to be IDE controllable rather than something dual formatted by the output mechanism behavior?

**Comment by vasily-kirichenko** [comment]
@KevinRansom I think it's a good idea. The suggestions don't play well already with Add Open Code Fix:

image

**Comment by forki** [comment]
Actually I'm much more in favor of doing proper compiler messages since
they can be used everywhere.

Am 21.12.2016 19:52 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by forki** [comment]
For the F# 4.2 time frame we could think about making this additional information available for the IDE. It was always meant as such. Currently I'm trying to make the compiler messages as useful as possible (fs 039 suggestions is only a small part) and this round is needed to reduce false positive suggestions. 

Even if we move the fs 039 suggestions to another place, this fix will be needed.

**Comment by forki** [comment]
this is ready for review/merge

**Comment by KevinRansom** [comment]
@forki 

Thanks for taking care of this

Kevin

**Pull request merged**
