### PR TITLE
Add a test and fix for #3337

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
NOTE: @matthid claims this still has a race condition

**Comment by forki** [comment]
added @matthid's race condition test

**Comment by matthid** [comment]
Added a fix, however I wanted to say that this makes the mailbox a bit slower.
Original speed of the test was 250ms and after this PR it is around 400ms.

**Comment by forki** [comment]
https://github.com/Microsoft/visualfsharp/pull/3370 fixes scan as well

**Pull request closed without merging**
