### PR TITLE
[WIP] Added PEVerifyBuiltAssembly target to build

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixing PEVerify errors in master branch in order.

### CODE REVIEW

**Comment by otawfik-ms** [comment]
@dsyme I recently added this target because I found a few peverify errors in our assemblies. The current plan is to identify/fix the errors one by one in this branch, then finally turn on the check in master.
I found a few errors related to byref returns. Can you please tell me if this is related to your recent changes?
Example:
         [IL]: Error: [C:\projects\visualfsharp-3dtit\Proto\net40\bin\FSharp.Compiler-proto.dll : Microsoft.FSharp.Compiler.AbstractIL.ILBinaryReader+MemoryMappedFile::ReadByte][offset 0x0000000C][found Native Int] Expected ByRef on the stack.
         [IL]: Error: [C:\projects\visualfsharp-3dtit\Proto\net40\bin\FSharp.Compiler-proto.dll : Microsoft.FSharp.Compiler.AbstractIL.ILBinaryReader+MemoryMappedFile::ReadInt32][offset 0x0000000A][found Native Int] Expected ByRef on the stack.
         [IL]: Error: [C:\projects\visualfsharp-3dtit\Proto\net40\bin\FSharp.Compiler-proto.dll : Microsoft.FSharp.Compiler.AbstractIL.ILBinaryReader+MemoryMappedFile::ReadUInt16][offset 0x0000000A][found Native Int] Expected ByRef on the stack.

**Comment by KevinRansom** [comment]
@Omar Tawfik<mailto:otawfik@microsoft.com> @Don Syme<mailto:Don.Syme@microsoft.com>

I know what is going on … I don’t have a fix yet, but I do know what it looks like.  PR to follow.


Kevin

**Comment by KevinRansom** [comment]
These are just using the win32 API for memory mapped files I think. We could likely switch to the standard .net wrappers for these

Sent from my Windows 10 phone

From: Kevin Ransom<mailto:Kevin.Ransom@microsoft.com>
Sent: 12 August 2016 00:19
To: Microsoft/visualfsharp<mailto:reply@reply.github.com>; Microsoft/visualfsharp<mailto:visualfsharp@noreply.github.com>; Omar Tawfik<mailto:otawfik@microsoft.com>; Don Syme<mailto:Don.Syme@microsoft.com>
Subject: RE: [Microsoft/visualfsharp] [WIP] Added PEVerifyBuiltAssembly target to build (#1415)

@Omar Tawfik<mailto:otawfik@microsoft.com> @Don Syme<mailto:Don.Syme@microsoft.com>

I know what is going on ... I don't have a fix yet, but I do know what it looks like.  PR to follow.


Kevin

**Comment by KevinRansom** [comment]
I think I can take care of it.

From: Don Syme
Sent: Thursday, August 11, 2016 4:30 PM
To: Kevin Ransom <Kevin.Ransom@microsoft.com>; Microsoft/visualfsharp <reply@reply.github.com>; Microsoft/visualfsharp <visualfsharp@noreply.github.com>; Omar Tawfik <otawfik@microsoft.com>
Subject: RE: [Microsoft/visualfsharp] [WIP] Added PEVerifyBuiltAssembly target to build (#1415)

These are just using the win32 API for memory mapped files I think. We could likely switch to the standard .net wrappers for these

Sent from my Windows 10 phone

From: Kevin Ransom<mailto:Kevin.Ransom@microsoft.com>
Sent: 12 August 2016 00:19
To: Microsoft/visualfsharp<mailto:reply@reply.github.com>; Microsoft/visualfsharp<mailto:visualfsharp@noreply.github.com>; Omar Tawfik<mailto:otawfik@microsoft.com>; Don Syme<mailto:Don.Syme@microsoft.com>
Subject: RE: [Microsoft/visualfsharp] [WIP] Added PEVerifyBuiltAssembly target to build (#1415)

@Omar Tawfik<mailto:otawfik@microsoft.com> @Don Syme<mailto:Don.Syme@microsoft.com>

I know what is going on ... I don't have a fix yet, but I do know what it looks like.  PR to follow.


Kevin

**Comment by otawfik-ms** [comment]
@KevinRansom  thanks for the investigation!

**Comment by OmarTawfik** [comment]
Closing for now.

**Pull request closed without merging**
