### PR TITLE
[RFC Needed] better warnings on mutable struct

### PR DESCRIPTION
**Pull request by dsyme**
As described in https://github.com/Microsoft/visualfsharp/issues/3923 in certain cases, the F# compiler assumes that .NET struct types are shallow-immutable when the user forgets to declare a struct value mutable using ``let mutable x = ...``.   

* This assumption is made because there is no way to analyze whether a .NET struct type is mutable, and 
performing a defensive copy in situations like `` 

* This applies to method calls like ``x.SetFoo(3)`` but not to property setters ``x.Foo <- 3``. In the latter case the operation is assumed mutating and an error is given at compile time.

* This can lead to differences in optimized and non-optimized code when ``let x = ....`` is used for a .NET struct value and a subsequent mutating operation is performed.  

The following adjustment is proposed for F# 4.x:

1. Give an optional warning (off by default) whenever a .NET struct type has been assumed to be immutable. However this is very noisy, as it triggers in very basic all property getter accessors are assumes to be immutable

2. Add a heuristic to give an improved diagnostic in some cases. Specifically if a method call has void/unit return type and starts with name "set" then give a warning (on by default) when used on a .NET struct value that has not been declared mutable.

Part (1) is fine, but part (2) of the change may be contentious: it is only a heuristic, but any name-based heuristic is unfortunate.

I'm slating this for F# 4.2 rather than pushing in the rule as a bug fix.

### CODE REVIEW

**Comment by saul** [comment]
Thanks Don - that’s a huge help when the optimiser is doing seemingly strange things that make complete sense when explained!

**Comment by dsyme** [comment]
@KevinRansom @brettfo  The build-from-source is failing when an error message is added to ``FSComp.txt``:
```
error FS0039: The field, constructor or member 'tastLikelyMutationOfConstant' is not defined. ...
error FS0039: The field, constructor or member 'tcStructTypeAssumedImmutable ...
```

Does the build-from-source rely on a checked-in version of a generated file?

**Comment by dsyme** [comment]
> @KevinRansom @brettfo The build-from-source is failing when an error message is added to FSComp.txt

What's the process for automatically updating this file please?  I tried ``build buildfromsource`` but it didn't get updated.

**Comment by dsyme** [comment]
CI seems broken - this is shown as "all checks passed" but no tests have been run

**Comment by brettfo** [comment]
CI is down for all dotnet repos (us included) until at least 12/1, 3PM PST (~6 hours after I posted this.)

**Comment by dsyme** [comment]
Brett says: 

> All affected generated files under the src\buildfromsource directory need to be updated.
> For example, if you change a value in src\fsharp\FSComp.txt, you’ll need to make the corresponding change in src\buildfromsource\FSharp.Compiler.Private\FSComp.fs and FSComp.resx.
> 
> The reason for this is that the version of the compiler that’s used to build the src\buildfromsource directory doesn’t yet have my changes to auto-generate the *.fs and *.resx files.  I’ll double-check on the versions, but I think once the source-build work upgrades to dotnet CLI 2.2 (maybe 2.1?) then the appropriate targets will be present so that we can delete the generated files.


It looks like we can just 

    copy /y src\fsharp\FSharp.Compiler.Private\obj\coreclr\* src\buildfromsource\FSharp.Compiler.Private

etc.

**Comment by dsyme** [comment]
Retarget at in master https://github.com/Microsoft/visualfsharp/pull/4576

**Comment by zpodlovics** [comment]
Would it be possible to have an attribute to control the defensive copy behaviour with an attribute? For example: ```[<AssumeImmutable>]``` and ```[<AssumeReadOnly>]``` (both because they have a different semantics). Heuristics is still remains a heuristics.

**Pull request closed without merging**
