### PR TITLE
Remove allocation from logblock

### PR DESCRIPTION
**Pull request by KevinRansom**
LogBlock used _use on a new object to defer the Log Stop message until the function being logged completed.

Because of the AsyncMaybe computation, it couldn't use struct.

This change fixes AsyncMaybe to allow structs with disposable in using blocks and uses a struct to mage the dispose.

It should be noted that box on a value type generates a new object ... thus handily eliminating the benefit of using a struct.   We now test if the type is a valuetype and only box on the object codepath.

I note that in Intrisics, dispose is declared like this:
https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L598

````
     match box resource with 
     | null -> ()
     | _ -> resource.Dispose()
````

Which will alloc for value types, therefore logging on Async Computation will still allocate an object, should I make a similar change there?

### CODE REVIEW

**Comment by TIHan** [comment]
So far this looks ok to me. The disposable structs should be internal though.

**Comment by KevinRansom** [comment]
@TIHan .  It has to return something it knows the size of, otherwise we are back in boxing land..

**Comment by TIHan** [comment]
So are you saying, making it internal it will box?

**Comment by KevinRansom** [comment]
Oh, I see what you mean.  

The Logger module is already internal, so code gen should make LogBlockDisposable     
the type internal, regardless of the annotation.  I thought you was after it returning IDisposable :-)
The il sig for LogBlockDisposable     
````

.class sequential ansi serializable sealed nested assembly LogBlockDisposable     extends [mscorlib]System.ValueType
--



````

**Comment by TIHan** [comment]
Ah I see. It's in the module itself, then that's fine too.

**Comment by KevinRansom** [comment]
@TIHan what about including a fix for intrinsics in F# Core, logging the async guy will still cause a box, I think we should fix it too.

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L598

**Comment by KevinRansom** [comment]
Updated it anyway, we can see what @dsyme thinks

**Comment by dsyme** [comment]
* What's the actual issue being fixed here?  Is it a perf or correctness problem? Or has there been a change in Roslyn to use a struct disposable and we are having trouble upgrading?

* LogBlockStart and LogBlockStop are not called in the codebase, remove them?

With regard to the intrinsic: as I understand things, the coding pattern 
```
     match box resource with 
     | null -> ()
     | _ -> resource.Dispose()
```
generates code that is understood by JITs when specialising code and will not box the value type, since the JIT always knows the result is non-null.  It's the legitimate way to test an arbitrary T for nullness.

**Comment by KevinRansom** [comment]
Don,

The checked in implementation of LogBlock allocates an object to call LogBlockStop., this happens whether anyone is listening or not.

So the first part of this turns the object into a struct to eliminate the alloc.

The checked in implementation of _Using for AsyncMaybe tests the object to Dispose against null which doesn’t work for structs.

But yes on further examination, you are correct the intrinsic generates pretty great code for the pattern on a release build


     match box resource with

     | null -> ()

     | _ -> resource.Dispose()

**Comment by dsyme** [comment]
> The checked in implementation of LogBlock allocates an object to call LogBlockStop., this happens whether anyone is listening or not. So the first part of this turns the object into a struct to eliminate the alloc.

Do we have any evidence that this allocation matters?  The code is barely used and on every code path I've seen it is surrounded by code probably doing 10,000+ allocations

**Comment by KevinRansom** [comment]
@dsyme, the logging has only just been added and so exists only in the code we are currently interested in investigating.  Eventually, we will be logging many more areas of the code.  The LogBlock is likely to be the most commonly used of the Logging API's because it can be used to log the bounds of an operation.  Because it was decided to always have the traces in the code, the allocation will happen, whether logging is happening or not.
Lastly, it is easier to remove allocations when writing code first time, than after it is already in the code.  VS is swimming in allocations none of which are particularly serious on their own, its the sum total that burns us.

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_fcs Build please

**Comment by dsyme** [comment]
@KevinRansom Well, every logging already adds at least one allocation (unless you write it carefully). For example this from [this PR](https://github.com/Microsoft/visualfsharp/pull/4878)

                 Logger.LogMessage (filename + "-Cancelling background work") LogCompilerFunctionId.Service_ParseAndCheckFileInProject

allocates the string ` (filename + "-Cancelling background work")` , regardless of whether logging is active or not.  (There are ways to code around that but code just becomes more and more obfuscated.)

So **we can assume you're not adding logging to anything perf-sensitive**, i.e. where an allocation will make a difference...  (And I can't seriously believe your changes are sensitive to the difference between one and two allocations)

There's no great harm in what you've done. But this kind of micro-optimization is not what's needed in the codebase.  It is better to learn to use the memory allocation profiler in Visual Studio and use it regularly, targeting the high-allocation results of profiling.

**Pull request closed without merging**
