### PR TITLE
Optimize unnecessary checks when computing overloads

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
This does fix https://github.com/Microsoft/visualfsharp/issues/4961, but maybe it's better to return `isOptional` flag based on abstractness of methods at https://github.com/Microsoft/visualfsharp/blob/4eed66b39d0db4c3c2d63bf11e98f4ea3f30be4c/src/fsharp/MethodOverrides.fs#L478

**Comment by vasily-kirichenko** [comment]
The perf is not improved for normal inheritance. However, the bottleneck is new: 

image

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by forki** [comment]
Can we move parts of it out and pass it in again?

**Comment by vasily-kirichenko** [comment]
@forki No, but what it does with this "set" is to check if there is exactly one meth by name and args, so I'm gonna to get the head and check that there are no duplicates, it will be O(n).

**Comment by vasily-kirichenko** [comment]
BTW, that `ListSet.setify` is a dangerous function (as well as the entire `ListSet` - all the operations are O(N^2) AFAIK. Maybe it's worth to check the codebase for its usages and eliminate them.

**Comment by matthid** [comment]
Funny how even GitHub gives up on basic colorization for src/fsharp/TypeChecker.fs

**Comment by smoothdeveloper** [comment]
> I think setify was always used under assumption that lists are small.

@forki it might be worth to put an assert checking list size there and try to see how valid the assumption is.

**Comment by forki** [comment]
Wouldn't that just break people's code completely?

Gauthier Segay <notifications@github.com> schrieb am Di., 22. Mai 2018,
19:51:

**Comment by vasily-kirichenko** [comment]
I've optimised normal inheritance as well:

untitled

It's not as smooth as with object expressions because it does need to check that all the overloads are the equivalent. I'd love to optimise it further.

**Comment by cartermp** [comment]
@vasily-kirichenko can you rename the PR to something to the effect of "Optimize unnecessary checks when computing overloads"? (Not sure of the proper title but that seems like what this work is doing)

On a side note, @dsyme do you have insights into the `ListSet` module? I agree with @vasily-kirichenko that it feels quite dangerous to use things from there, especially since certain combinators (e.g., `List.forall` exist)

**Comment by vasily-kirichenko** [comment]
@matthid 
> Funny how even GitHub gives up on basic colorization for src/fsharp/TypeChecker.fs
I've just from that file in VS - everything works tolerably fast, colorization is there.

@forki 
> Wouldn't that just break people's code completely?

I agree.

**Comment by vasily-kirichenko** [comment]
@cartermp done

**Comment by forki** [comment]
let's review ALL setify places. I think I already found one that can be improved. will send PR

**Comment by forki** [comment]
#4973

**Comment by dsyme** [comment]
Yes, the code was written on the assumption to the 20 overloads of the same name found in `WriteLine` and friends was at the upper end of what we would see.  That was 2006.

> On a side note, @dsyme do you have insights into the ListSet module? I agree with @vasily-kirichenko that it feels quite dangerous to use things from there, especially since certain combinators (e.g., List.forall) exist and appear to do the same work

Yes, nearly all traces of this have gone but there are still a few lurking.  It is vaguely useful as an ordered set for small collections.

**Comment by smoothdeveloper** [comment]
> Yes, the code was written on the assumption to the 20 overloads of the same name found in WriteLine and friends was at the upper end of what we would see. That was 2006.

In the meantime in C#:
* Better (overload resolution) in C# 2 or 3
* Better Betterness (of overload resolution) in C# 6
* Improved overload candidates and bestest betterness (of overload resolution) in C#7

@dsyme has the handling of overload resolution in F# compiler followed a same route as in C# (where I feel a lot of carefull but noticeable improvements have been made over the releases)?

It always feel that it gets in the way whenever the types are using that mechanism "creatively", I'm still challenged once in a while, even after few years of using F#, to write some calls right for the compiler to pick the correct overload, and I'm sure it trips a lot of newcomers.

**Comment by dsyme** [comment]
> @dsyme has the handling of overload resolution in F# compiler followed a same route as in C# (where I feel a lot of carefull but noticeable improvements have been made over the releases)?

Some improvements have been made, particularly in the presence of large sets of generic overloads, but we have not tracked the C# improvements since the type inference used by F# is different. There are still some overload sets that cause problems like `Task`.

**Pull request merged**
