### PR TITLE
Fix for #3267  --- Arrow keys and backspace stopped working

### PR DESCRIPTION
**Pull request by KevinRansom**
This is for vs2017-rtm branch and is a fix of the arrow keys bug.: https://github.com/Microsoft/visualfsharp/issues/3267

Don has a similar fix in master, although in master, it still repros although less frequently.  I believe there it is a threading issue.

/cc @cartermp, @dsyme, @pichie, @brettfo

### CODE REVIEW

**Comment by forki** [comment]
:kiss:

**Comment by KevinRansom** [comment]
I am terrified and almost certain it is too late for VS2017.3.

**Comment by forki** [comment]
O_o how can this bug not be a blocker?

**Comment by vasily-kirichenko** [comment]
NP, people can wait for 15.4

**Comment by KevinRansom** [comment]
DevDiv is huge, releasing a product is about managing a ton of trade offs.  I didn't say it was hopeless but it may be.

**Comment by drvink** [comment]
If this doesn't make it into 2017.3, will there be a patch/update available at the time of its release? Or are people really going to update VS only to find they can't edit F# source? (Please don't get me wrong; the failure here is not on the F# team...)

**Comment by cartermp** [comment]
Assuming this gets checked in, it will also be in the nightly builds.  Given that this has not yet been validated, we can't say if it will be available in a patch at release or not.

**Pull request merged**
