### PR TITLE
Disable in-memory project references for projects using generative type providers

### PR DESCRIPTION
**Pull request by dsyme**
Tentative fix for https://github.com/Microsoft/visualfsharp/issues/3234

Will add FCS testing for this scenario as well

### CODE REVIEW

**Comment by dsyme** [comment]
Well, it fixes the bug

image

**Comment by dsyme** [comment]
I also wanted to check that we're not triggering endless rechecks of the project.  Here is the reactot trace after a couple of one-character edits in Program.fs
```
devenv.exe Information: 0 : Reactor: enqueue CompletionProvider.ParseAndCheckFileInProject devenv.exe Information: 0 : Reactor: enqueue BraceMatching.MatchBraces (Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> BraceMatching.MatchBraces (Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- BraceMatching.MatchBraces, took 0.2023 ms
devenv.exe Information: 0 : Reactor: enqueue SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: enqueue DocumentDiagnosticAnalyzer.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SemanticColorization.ParseAndCheckFileInProject, took 0.0472 ms
devenv.exe Information: 0 : Reactor: SemanticColorization.ParseAndCheckFileInProject.CacheMiss (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs)
devenv.exe Information: 0 : Reactor: --> DocumentDiagnosticAnalyzer.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: enqueue SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: enqueue NavigationBarItem.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 1
devenv.exe Information: 0 : Reactor: enqueue DocumentDiagnosticAnalyzer.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 1
devenv.exe Information: 0 : Reactor: DocumentDiagnosticAnalyzer.ParseFileInProject.CacheMiss (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs)
devenv.exe Information: 0 : Reactor: <-- DocumentDiagnosticAnalyzer.ParseFileInProject, took 202.916 ms
devenv.exe Information: 0 : Reactor: enqueue DocumentDiagnosticAnalyzer.CheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 3
devenv.exe Information: 0 : Reactor: --> SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 2
devenv.exe Information: 0 : Reactor: <-- SemanticColorization.ParseAndCheckFileInProject, took 0.6293 ms
devenv.exe Information: 0 : Reactor: enqueue SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 3
devenv.exe Information: 0 : Reactor: --> NavigationBarItem.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 2
devenv.exe Information: 0 : Reactor: <-- NavigationBarItem.ParseFileInProject, took 0.0401 ms
devenv.exe Information: 0 : Reactor: --> DocumentDiagnosticAnalyzer.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 2
devenv.exe Information: 0 : Reactor: <-- DocumentDiagnosticAnalyzer.ParseFileInProject, took 0.0451 ms
devenv.exe Information: 0 : Reactor: --> DocumentDiagnosticAnalyzer.CheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 1
devenv.exe Information: 0 : Reactor: <-- DocumentDiagnosticAnalyzer.CheckFileInProject, took 0.046 ms
devenv.exe Information: 0 : Reactor: DocumentDiagnosticAnalyzer.CheckFileInProject.CacheMiss (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs)
devenv.exe Information: 0 : Reactor: --> SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: enqueue DocumentDiagnosticAnalyzer.CheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: <-- SemanticColorization.ParseAndCheckFileInProject, took 3.0307 ms
devenv.exe Information: 0 : Reactor: --> DocumentDiagnosticAnalyzer.CheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: enqueue SemanticColorization.TypeCheckOneFile.Fragment (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: <-- DocumentDiagnosticAnalyzer.CheckFileInProject, took 1.2037 ms
devenv.exe Information: 0 : Reactor: --> SemanticColorization.TypeCheckOneFile.Fragment (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SemanticColorization.TypeCheckOneFile.Fragment, took 2.2621 ms
devenv.exe Information: 0 : Reactor: enqueue start background, length 0
devenv.exe Information: 0 : Reactor: enqueue start background, length 0
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
devenv.exe Information: 0 : Reactor: --> background step DocumentDiagnosticAnalyzer.ImplicitlyStartCheckProjectInBackground.CheckProjectInBackground (C:\GitHub\misc\TypeProvidersBug\TestConsole\TestConsole.fsproj)
devenv.exe Information: 0 : Reactor: enqueue UnusedDeclarationsAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: <-- background step, took 2.072ms
devenv.exe Information: 0 : Reactor: --> UnusedDeclarationsAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- UnusedDeclarationsAnalyzer.ParseAndCheckFileInProject, took 0.0483 ms
devenv.exe Information: 0 : Reactor: enqueue SimplifyNameDiagnosticAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SimplifyNameDiagnosticAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SimplifyNameDiagnosticAnalyzer.ParseAndCheckFileInProject, took 0.0706 ms
devenv.exe Information: 0 : Reactor: enqueue SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable, took 2.2157 ms
devenv.exe Information: 0 : Reactor: enqueue SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable, took 0.1178 ms
devenv.exe Information: 0 : Reactor: enqueue SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable, took 0.075 ms
devenv.exe Information: 0 : Reactor: enqueue UnusedOpensAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> UnusedOpensAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- UnusedOpensAnalyzer.ParseAndCheckFileInProject, took 0.0472 ms
Exception thrown: 'System.InvalidOperationException' in FSharp.Core.dll
The thread 0x5574 has exited with code 0 (0x0).
The thread 0x556c has exited with code 0 (0x0).
The thread 0x4a50 has exited with code 0 (0x0).
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ComboBoxItem', AncestorLevel='1''. BindingExpression:Path=IsSelected; DataItem=null; target element is 'FrameworkElement' (Name='PART_VerticalIndentSpacer'); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ComboBoxItem', AncestorLevel='1''. BindingExpression:Path=IsSelected; DataItem=null; target element is 'FrameworkElement' (Name='PART_VerticalIndentSpacer'); target property is 'NoTarget' (type 'Object')
devenv.exe Information: 0 : Reactor: enqueue DocumentHighlights.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> DocumentHighlights.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- DocumentHighlights.ParseAndCheckFileInProject, took 0.0439 ms
devenv.exe Information: 0 : Reactor: enqueue DocumentHighlights.GetSymbolUseAtLocation (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: enqueue RenameUnusedValueCodeFix.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> DocumentHighlights.GetSymbolUseAtLocation (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- DocumentHighlights.GetSymbolUseAtLocation, took 0.1451 ms
devenv.exe Information: 0 : Reactor: --> RenameUnusedValueCodeFix.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- RenameUnusedValueCodeFix.ParseAndCheckFileInProject, took 0.0539 ms
devenv.exe Information: 0 : Reactor: enqueue RenameUnusedValueCodeFix.GetSymbolUseAtLocation (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> RenameUnusedValueCodeFix.GetSymbolUseAtLocation (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- RenameUnusedValueCodeFix.GetSymbolUseAtLocation, took 0.119 ms
devenv.exe Information: 0 : Reactor: enqueue BraceMatching.MatchBraces (Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> BraceMatching.MatchBraces (Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- BraceMatching.MatchBraces, took 0.465 ms
devenv.exe Information: 0 : Reactor: enqueue SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: enqueue NavigationBarItem.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: enqueue DocumentDiagnosticAnalyzer.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SemanticColorization.ParseAndCheckFileInProject, took 0.0413 ms
devenv.exe Information: 0 : Reactor: SemanticColorization.ParseAndCheckFileInProject.CacheMiss (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs)
devenv.exe Information: 0 : Reactor: --> NavigationBarItem.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 1
devenv.exe Information: 0 : Reactor: enqueue DocumentDiagnosticAnalyzer.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: NavigationBarItem.ParseFileInProject.CacheMiss (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs)
devenv.exe Information: 0 : Reactor: enqueue SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 1
devenv.exe Information: 0 : Reactor: <-- NavigationBarItem.ParseFileInProject, took 211.5132 ms
devenv.exe Information: 0 : Reactor: --> DocumentDiagnosticAnalyzer.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 2
devenv.exe Information: 0 : Reactor: <-- DocumentDiagnosticAnalyzer.ParseFileInProject, took 0.0436 ms
devenv.exe Information: 0 : Reactor: --> DocumentDiagnosticAnalyzer.ParseFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 1
devenv.exe Information: 0 : Reactor: <-- DocumentDiagnosticAnalyzer.ParseFileInProject, took 0.0489 ms
devenv.exe Information: 0 : Reactor: --> SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: enqueue DocumentDiagnosticAnalyzer.CheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 1
devenv.exe Information: 0 : Reactor: <-- SemanticColorization.ParseAndCheckFileInProject, took 3.0632 ms
devenv.exe Information: 0 : Reactor: enqueue SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 1
devenv.exe Information: 0 : Reactor: --> DocumentDiagnosticAnalyzer.CheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- DocumentDiagnosticAnalyzer.CheckFileInProject, took 0.0495 ms
devenv.exe Information: 0 : Reactor: DocumentDiagnosticAnalyzer.CheckFileInProject.CacheMiss (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs)
devenv.exe Information: 0 : Reactor: --> SemanticColorization.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: enqueue DocumentDiagnosticAnalyzer.CheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: <-- SemanticColorization.ParseAndCheckFileInProject, took 2.1621 ms
devenv.exe Information: 0 : Reactor: --> DocumentDiagnosticAnalyzer.CheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: enqueue SemanticColorization.TypeCheckOneFile.Fragment (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: <-- DocumentDiagnosticAnalyzer.CheckFileInProject, took 2.7665 ms
devenv.exe Information: 0 : Reactor: --> SemanticColorization.TypeCheckOneFile.Fragment (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SemanticColorization.TypeCheckOneFile.Fragment, took 4.2708 ms
devenv.exe Information: 0 : Reactor: enqueue start background, length 0
devenv.exe Information: 0 : Reactor: enqueue start background, length 0
The thread 0x3068 has exited with code 0 (0x0).
The thread 0x46b8 has exited with code 0 (0x0).
The thread 0x4a80 has exited with code 0 (0x0).
The thread 0x5078 has exited with code 0 (0x0).
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
devenv.exe Information: 0 : Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Reactor: --> background step DocumentDiagnosticAnalyzer.ImplicitlyStartCheckProjectInBackground.CheckProjectInBackground (C:\GitHub\misc\TypeProvidersBug\TestConsole\TestConsole.fsproj)
devenv.exe Information: 0 : Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Reactor: enqueue UnusedDeclarationsAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: <-- background step, took 19.6491ms
devenv.exe Information: 0 : Reactor: --> UnusedDeclarationsAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- UnusedDeclarationsAnalyzer.ParseAndCheckFileInProject, took 0.0495 ms
devenv.exe Information: 0 : Reactor: enqueue RenameUnusedValueCodeFix.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> RenameUnusedValueCodeFix.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- RenameUnusedValueCodeFix.ParseAndCheckFileInProject, took 0.0495 ms
devenv.exe Information: 0 : Reactor: enqueue RenameUnusedValueCodeFix.GetSymbolUseAtLocation (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> RenameUnusedValueCodeFix.GetSymbolUseAtLocation (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- RenameUnusedValueCodeFix.GetSymbolUseAtLocation, took 0.0999 ms
devenv.exe Information: 0 : Reactor: enqueue GCFinalizer.FSharpCheckFileResults.DecrementUsageCountOnIncrementalBuilder (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> GCFinalizer.FSharpCheckFileResults.DecrementUsageCountOnIncrementalBuilder (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- GCFinalizer.FSharpCheckFileResults.DecrementUsageCountOnIncrementalBuilder, took 0.3055 ms
devenv.exe Information: 0 : Reactor: enqueue SimplifyNameDiagnosticAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SimplifyNameDiagnosticAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SimplifyNameDiagnosticAnalyzer.ParseAndCheckFileInProject, took 0.0651 ms
devenv.exe Information: 0 : Reactor: enqueue SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable, took 0.812 ms
devenv.exe Information: 0 : Reactor: enqueue SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable, took 0.1043 ms
devenv.exe Information: 0 : Reactor: enqueue SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- SimplifyNameDiagnosticAnalyzer.IsRelativeNameResolvable, took 0.1384 ms
devenv.exe Information: 0 : Reactor: enqueue UnusedOpensAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), length 0
devenv.exe Information: 0 : Reactor: --> UnusedOpensAnalyzer.ParseAndCheckFileInProject (C:\GitHub\misc\TypeProvidersBug\TestConsole\Program.fs), remaining 0
devenv.exe Information: 0 : Reactor: <-- UnusedOpensAnalyzer.ParseAndCheckFileInProject, took 0.0472 ms
The program '[5392] devenv.exe: Program Trace' has exited with code 0 (0x0).
The program '[5392] devenv.exe' has exited with code -1 (0xffffffff).
```

**Comment by vasily-kirichenko** [comment]
Thank you so much for this.

**Comment by dsyme** [comment]
OK this now has a test

**Pull request merged**
