### PR TITLE
Symbol uses for namespaces

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This brings `FSharpSymbolUse` for namespaces at all places (and fixes https://github.com/Microsoft/visualfsharp/issues/3919):

image

### CODE REVIEW

**Comment by auduchinok** [comment]
@vasily-kirichenko This is awesome! Thank you.

**Comment by auduchinok** [comment]
@vasily-kirichenko It doesn't add uses of namespaces in top-level declarations. Should we count them as bindings?
```fsharp
namespace Foo.Bar

type R = { int: int }
```
screen shot 2017-11-13 at 14 07 00

**Comment by vasily-kirichenko** [comment]
@auduchinok yes. I'll look at it.

**Comment by vasily-kirichenko** [comment]
image

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
ci_part3 failed with
> 1) Invalid : FSharp.Core.Unittests, Version=4.4.1.0, Culture=neutral, PublicKeyToken=null
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

Ideas?

**Comment by vasily-kirichenko** [comment]
part3 with
```
1) Failed : FSharp-Tests-Core+CoreTests.namespaceAttributes
Error running command 'D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\..\..\release\net40\bin\fsc.exe' with args '-r:System.Core.dll --nowarn:20 --define:COMPILED --optimize+ --debug -o:test--optplus--debug.exe -g test.fsi test.fs test2.fsi test2.fs' in directory 'D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\core\namespaces'. ERRORLEVEL 1
at TestFramework.checkResult(CmdResult result) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 258
at TestFramework.exec@438-22.Invoke(CmdResult result) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 438
at TestFramework.fsc@446-1.Invoke(String flags, FSharpList`1 srcFiles) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 446
at SingleTest.singleTestBuildAndRunCore(TestConfig cfg, String copyFiles, Permutation p) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\single-test.fs:line 140
at FSharp-Tests-Core.CoreTests.namespaceAttributes() in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\tests.fs:line 73
```
What does it mean? @KevinRansom

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test Windows_NT Release_ci_part3 Build please

**Comment by vasily-kirichenko** [comment]
part 2
```
1) Error : FSharp-Tests-Core+CoreTests.load-script
System.ComponentModel.Win32Exception : Operation did not complete successfully because the file contains a virus or potentially unwanted software
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Scripting.Process.exec(CmdArguments cmdArgs, String workDir, FSharpMap`2 envs, String path, String arguments) in D:\j\w\release_ci_pa---866fd2c3\src\scripts\scriptlib.fsx:line 136
   at TestFramework.Command.exec@427-20.Invoke(CmdArguments cmdArgs) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 428
   at TestFramework.Command.outF@400-3T.Invoke(FSharpFunc`2 fCont, CmdArguments cmdArgs) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 415
   at TestFramework.execAppendIgnoreExitCode@437.Invoke(String args) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 437
   at TestFramework.execAppendIgnoreExitCode@437-2.Invoke(String x) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 437
   at FSharp-Tests-Core.CoreTests.load-script() in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\tests.fs:line 866

2) Failed : FSharp-Tests-Core+CoreTests.namespaceAttributes
Error running command 'D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\..\..\release\net40\bin\fsc.exe' with args '-r:System.Core.dll --nowarn:20 --define:COMPILED --optimize+ --debug -o:test--optplus--debug.exe -g test.fsi test.fs test2.fsi test2.fs' in directory 'D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\core\namespaces'. ERRORLEVEL 1
at TestFramework.checkResult(CmdResult result) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 258
at TestFramework.exec@438-22.Invoke(CmdResult result) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 438
at TestFramework.fsc@446-1.Invoke(String flags, FSharpList`1 srcFiles) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 446
at SingleTest.singleTestBuildAndRunCore(TestConfig cfg, String copyFiles, Permutation p) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\single-test.fs:line 140
at FSharp-Tests-Core.CoreTests.namespaceAttributes() in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\tests.fs:line 73
```
part 3
```
1) Invalid : FSharp.Core.Unittests, Version=4.4.1.0, Culture=neutral, PublicKeyToken=null
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```
I've no idea what these errors all about.

**Comment by vasily-kirichenko** [comment]
It's ready.

**Pull request merged**
