### PR TITLE
remove test dependency on peverify.exe

### PR DESCRIPTION
**Pull request by brettfo**

### CODE REVIEW

**Comment by dsyme** [comment]
Why are we doing this?  Just wondering.

**Comment by KevinRansom** [comment]
@dsyme 

The goal is to simplify the build and testing stuff, and to limit the pre-requisites for building and testing the repo.  The goal is to require just a windows install, to build and run and test the repo.

**Comment by cartermp** [comment]
Can we track each of these sub-items?  For those of us not in the
redmond office each day, this sort of work seems surprising and doesn’t
make immediate sense.

On Thu, Nov 23, 2017, at 14:01, Kevin Ransom (msft) wrote:
> @dsyme[1]


> The goal is to simplify the build and testing stuff, and to limit the
> pre-requisites for building and testing the repo.  The goal is to
> require just a windows install, to build and run and test the repo.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].> 


Links:

  1. https://github.com/dsyme
  2. https://github.com/Microsoft/visualfsharp/pull/4001#issuecomment-346702588

**Comment by KevinRansom** [comment]
You should consider most of what Brett is doing at the moment as supporting three large infrastructure related goals.

1.   Aligning with the BuildFromSource group, which has the goal of aligning the build/Infra for all of the repos.  (Necessary for the RedHat build from source)
2.  Enabling Loc in the OSS build.
3.  Getting us away from the internal build-branch so that we can do official builds straight from the GitHub repo, rather than using the internal  repo.

It is likely to be mostly ad-hoc work like this.  Since it is mostly about overcoming difficulties in the build and testing that relied on pre-requisites, that we re trying to eliminate.

Kevin

**Comment by dsyme** [comment]
@KevinRansom OK, thanks, that makes sense

**Comment by cartermp** [comment]
> It is likely to be mostly ad-hoc work like this. Since it is mostly about overcoming difficulties in the build and testing that relied on pre-requisites, that we re trying to eliminate.

I understand that, but it doesn't mean we can't track _some_ work (at least overarching goals), have some kind of traceability, and give others a quick view into what we're doing. This isn't the only PR; as a whole, our work is entirely opaque and untracked, and I really don't see a good reason why.  [This issue is a fine example](https://github.com/dotnet/project-system/issues/2789) of tracking work that is not comprised of entirely known entities.

**Pull request merged**
