### PR TITLE
Fix project reference "Not implemented" error with unloaded projects in solution

### LINKED ISSUE #2275: Add Reference from file does not work when one or more projects in the solution are unloaded
image

### PR DESCRIPTION
**Pull request by saul**
Fixes #2275.

The problem was came from this call stack:

1. Project.fs: `IVsReferenceManagerUser.ChangeReference` calls `ProjectNode.AddComponent(VSADDCOMPOPERATION.VSADDCOMPOP_ADD, ...)`
1. ProjectNode.cs: `ProjectNode.AddComponent` calls `AddReferenceFromSelectorData` for its reference container node
1. ReferenceContainerNode.cs: `ReferenceContainerNode.AddReferenceFromSelectorData` calls `ReferenceNode.IsAlreadyAdded`
1. ReferenceNode.cs: `ReferenceNode.IsAlreadyAdded` gets the `SimpleName` property of each sibling reference node
1. ProjectReferenceNode.cs: `ProjectReferenceNode.SimpleName` gets the `this.ReferencedProjectOutputPath` property
1. ProjectReferenceNode.cs: `ReferencedProjectOutputPath` calls `GetReferencedProjectOutputPath`
1. ProjectReferenceNode.cs: `GetReferencedProjectOutputPath` gets the `ReferencedProject` property
1. ProjectReferenceNode.cs: `ReferencedProject` calls `InitReferencedProject`
1. ProjectReferenceNode.cs: Call to `IVsHierarchy.GetProperty(VSConstants.VSITEMID_ROOT, ...)` fails as the project is unloaded - this throws a NotImplementedException

### CODE REVIEW

**Comment by saul** [comment]
cc @cartermp - would be really grateful if we could get this in for RTM as this bites us on a very regular basis. I believe this has been a bug since at least 2013 so it would be fantastic to get it fixed for 2017 considering how simple (& low risk) the change is.

**Comment by saul** [comment]
Bump @cartermp @KevinRansom @brettfo - again we're really hoping this will make it into RTM. This bites us on a regular basis.

**Comment by cartermp** [comment]
I doubt we could get this in, unfortunately...even though it's a low-impact change.  RTM is basically frozen aside from critical errors at this point.  I think a microupdate may make more sense here.  We'll likely be bundling up multiple changes, which hopefully also include this one.

**Comment by saul** [comment]
That's a shame - can we at least get it merged so it doesn't miss the next update

**Comment by cartermp** [comment]
Defering to @KevinRansom on getting it merged (I'm sure he'll want to review the changes), but we're still well within the window for preparing a set of changes for that update (unless something catastrophic happens).  FWIW, microupdates will be in "Ask Mode" which is a way of saying that we'll take a set of changes and make a case for them in a shiproom meeting along with an associated bug which has the benefits of these changes written out.  In general, if the changes fix bugs (such as this PR and others), they're usually accepted.  I'm confident we'll get this in pretty soon after RTM.

**Comment by saul** [comment]
Thanks for the clarification - however I'm still not fully understanding how micro updates will be released. Are these OOB VSIX releases or updates that will only be available in VS. Also will the be available as a separate download on MSDN or will they all of the microupdates be bundled with VS 2017 Update 1?

I'm asking as I'll be using VS 2017 in an environment that does not have direct internet access, so if the microupdate is not available as a separate download then it's going to be impossible for me to use.

**Comment by cartermp** [comment]
Microupdates are the in-IDE ones that are bundled alongside VS2017 updates themselves.  This will happen on a (planned) N-week cadence, where N is some positive integer closely or absolutely equivalent to 6.  I'm not sure about what plans are for offline or sometimes-online scenarios.

Having a VSIX available for installation (using the method that we have for RC3) is another angle that I'm keen on exploring.  That offers people a "use effectively the latest master" as an option.  I believe @brettfo has been reworking infrastructure internally so that we can easily produce a signed VSIX when master build successfully.  From then, it's just a matter of publishing it as a GitHub release on a relatively frequent cadence.

**Comment by saul** [comment]
Thanks again :) Is there an issue to track having the F# VSIX released OOB on GitHub? That'd be really useful considering the pace of changes we have at the minute.

**Comment by cartermp** [comment]
Now there is!  #2355

**Pull request merged**
