### PR TITLE
Add colours to FSI output

### PR DESCRIPTION
**Pull request by saul**
FSI results can now be coloured thanks to #2070:

image

The colours are up for discussion. In particular I think keywords should be a brighter colour than blue, maybe green or magenta. I just stuck to VS defaults as a first go.

### CODE REVIEW

**Comment by cartermp** [comment]
Ultimately colors should be configurable/conform to set profiles, but I think that VS defaults are fine for now.  Any idea how much it would take to add some basic configuration in Tools|Options|F# Interactive?

**Comment by saul** [comment]
Definitely - this PR is for the console window only though. There's no integration for VS FSI yet. Any ideas as to where the colour settings should live?

**Comment by vasily-kirichenko** [comment]
About colors, switch to the dark theme in VS and grab colors from there, they should be much more readable compared to the current ones.

It would be very much appreciated if you enable the coloring in VS FSI, too. I don't think many people use the console FSI.

**Comment by vasily-kirichenko** [comment]
@dungpa I think you were tried to color VS FSI (in some hacky way :) ). Could you give some points on how to do it?

**Comment by KevinRansom** [comment]
Adding VFSI support for colours is a separate issue.  Please start an issue .. for that.

Kevin

**Comment by saul** [comment]
@KevinRansom with regards to #2163, how do you want to move forward with this? Are we happy with the colours as is?

I'd personally prefer keywords to be green so they stand out on black. It should be worth noting that colours can be disabled with the current mechanism (command line option of `--consolecolors-`).

**Comment by KevinRansom** [comment]
@saul yes colours as is is fine.  There are some baseline file errors that need fixing ...

**Comment by saul** [comment]
The baseline changes are due to newlines being consistently used for FSI errors and output. Previously there was no consistency. Now there's only ever a blank line after output/error and before the next prompt.

**Comment by KevinRansom** [comment]
@saul ... excellent.

Thank you

**Comment by saul** [comment]
@KevinRansom tests are green 👍

**Comment by KevinRansom** [comment]
Colourfull FSI ... what a thing ....

@saul 
We need an issue to allow the configuration of these colours and the ability to select themes.
We need an issue to reproduce this colourful loveliness in VSFSI.

**Comment by KevinRansom** [comment]
Thank you for taking care of this

**Pull request merged**
