### PR TITLE
Cleanup code

### PR DESCRIPTION
**Pull request by enricosada**
refactor to simplify the code

### CODE REVIEW

**Comment by KevinRansom** [comment]
This code cleanup looks great.  I wonder if it is the best use of our time right now, what do you think?

**Comment by dsyme** [comment]
LGTM. I’m ok with a steady stream of quality-improving, non-destabilizing, low-risk, local cleanup (any other criteria needed?). The F# compiler codebase needs to gradually be made "better" - more readable, more maintainable.

This is fits the criteria 

* Quality improving: Yes
* Non-destabilizing: Yes
* Low-risk: Yes
* Local: Yes
* Carefully reviewed: Yes


Thanks
Don

**Comment by enricosada** [comment]
Exactly my idea @dsyme , little improvements

Maybe another criteria to add:

- not a style cleanup only (formatting/indentation/etc )

Clean style with new code, but always try to minimize diff (whitespace/indentation) to make it easier to sync in openfsharp/fcs

**Comment by KevinRansom** [comment]
merged into vs2015, coreclr and master, thank you for taking care of this.

Kevin

https://github.com/Microsoft/visualfsharp/commit/95c02dde81f6548b754453309c594fd524c8b3ab

**Pull request closed without merging**
