### PR TITLE
Fix the build events property page and the targetframework dropdown in the application page

### LINKED ISSUE #3276: The targetframework dropdown in the application prop page is empty for .NET Core projects
After this PR https://github.com/dotnet/project-system/pull/2522, the application page shows up for CPS projects but the TargetFramework dropdown will be empty for .NETCore\.NET STandard projects,

This is because it asks the multi-targeting service for the TFMs and the multi-targeting service doesn't know about .NET Core\Standard. We made [a change to C#\VB pages ](https://github.com/dotnet/project-system/pull/2097/commits/aee40ba336d0b94a20f416060213e0b9cf6369a1) to augment that list from the SDK. The same change needs to be repeated for the F# application page.

### LINKED ISSUE #3277: Build Events page is broken for CPS projects
This [line](https://github.com/Microsoft/visualfsharp/blob/6afc4f9776a5dba903ca6b11965a206fb8bc23d8/vsintegration/src/FSharp.ProjectSystem.PropertyPages/PropertyPages/BuildEventsPropPage.vb#L215) needs to be fixed - when the RunPostBuildEvent property is not set, the old PS returned a special missing value where CPS returns an empty string. That code needs to account for the empty string.

### PR DESCRIPTION
**Pull request by srivatsn**
The target framework is populated by asking the multi-targeting service for the TFMs and the multi-targeting service doesn't know about .NET Core\Standard. We now also query a property that's set by the SDK that lists the known .NET Core\.NET STandard version. This change is similar to [the change to C#\VB pages ](https://github.com/dotnet/project-system/pull/2097/commits/aee40ba336d0b94a20f416060213e0b9cf6369a1) 

The build events prop page was failing to load because the RunPostBuildEvents property is not set normally and in that case, CPS returns an empty string whereas the old project system returned a specific missing value. This changes the page to handle both cases.

@KevinRansom @brettfo @Pilchie @dsyme 

Fixes #3276, Fixes #3277

### CODE REVIEW

**Comment by dsyme** [comment]
@srivatsn I don't know what's up with that failed job, it looks sort of unrelated?  The project system code shouldn't be loaded when building FSharp.Tests.FSharpSuite.DrivingCoreCLR

```

"D:\j\workspace\release_ci_pa---c6929ad7\build-everything.proj" (default target) (1) ->
"D:\j\workspace\release_ci_pa---c6929ad7\tests\fsharp\FSharp.Tests.FSharpSuite.DrivingCoreCLR\FSharp.Tests.FSharpSuite.DrivingCoreCLR.fsproj" (Build target) (41) ->
(dotnetpublishfsccompiler target) -> 
  EXEC : error : Unable to resolve 'runtime.osx.10.10-x64.runtime.native.System.Net.Security (>= 4.3.0)' for '.NETCoreApp,Version=v1.0 (osx.10.10-x64)'. [D:\j\workspace\release_ci_pa---c6929ad7\tests\fsharp\FSharp.Tests.FSharpSuite.DrivingCoreCLR\FSharp.Tests.FSharpSuite.DrivingCoreCLR.fsproj]
  EXEC : error : Unable to resolve 'runtime.ubuntu.14.04-x64.runtime.native.System.Net.Security (>= 4.3.0)' for '.NETCoreApp,Version=v1.0 (ubuntu.14.04-x64)'. [D:\j\workspace\release_ci_pa---c6929ad7\tests\fsharp\FSharp.Tests.FSharpSuite.DrivingCoreCLR\FSharp.Tests.FSharpSuite.DrivingCoreCLR.fsproj]
  D:\j\workspace\release_ci_pa---c6929ad7\src\FSharpSource.targets(284,5): error MSB3073: The command "D:\j\workspace\release_ci_pa---c6929ad7\src\..\Tools\dotnetcli\dotnet.exe restore DeployCompiler\fsc\project.json" exited with code 1. [D:\j\workspace\release_ci_pa---c6929ad7\tests\fsharp\FSharp.Tests.FSharpSuite.DrivingCoreCLR\FSharp.Tests.FSharpSuite.DrivingCoreCLR.fsproj]
```

**Comment by dsyme** [comment]
@dotnet-bot test Windows_NT Release_ci_part3 Build please

**Comment by Pilchie** [comment]
We'll need to cherry-pick this into the VS release branch, right?

**Comment by KevinRansom** [comment]
Yes, there will likely be a couple more too.

**Comment by KevinRansom** [comment]
@Pilchie @cartermp @brettfo We will need to cherry pick this.

**Comment by KevinRansom** [comment]
Tagging @MattGertz, @Pilchie for approval to insert to VS
Customer scenario:
This upgrades the F# pproject system to enable property pages for the F# project properties. It contains fixes that enable Property pages for dotnet SDK project to edit a number of properties that are not IDE editable without this change.
Workarounds, if any:
A developer can edit the project file to Manually set these values
**Performance impact : **
None
Root cause analysis : Not yet implemented. This is the first release to support dotnet sdk projects.
How was this bug found?: Adhoc testing

**Pull request merged**
