### PR TITLE
Activate FCS build on CI

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
anyone know why it would not start Release_fcs ?

**Comment by forki** [comment]
@cartermp @KevinRansom  can you please summon soneone who can activate Release_fcs on the jenkins?

**Comment by dsyme** [comment]
@forki I'm not sure but it might be we have to integrate before it picks up the new groovy CI spec.

**Comment by forki** [comment]
Then I'm for merging this ;-)

Am 19.10.2017 01:33 schrieb "Don Syme" <notifications@github.com>:

**Comment by forki** [comment]
ok I temporarily hijacked the Release_net40_no_vs target and it did nothing. So yes it seems it uses the groovy from master

**Comment by KevinRansom** [comment]
Once we check-in the ci will pick up the new groovy script.

**Comment by forki** [comment]
Cool. Then please merge and I try to continue to make it work

Am 20.10.2017 07:51 schrieb "Kevin Ransom (msft)" <notifications@github.com
>:

*@KevinRansom* approved this pull request.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/pull/3769#pullrequestreview-70748923>,
or mute the thread

**Comment by KevinRansom** [comment]
It’s already merged mate.

**Comment by forki** [comment]
Hugs

Am 20.10.2017 07:54 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Pull request merged**
