### PR TITLE
Align rebalance functions

### PR DESCRIPTION
**Pull request by forki**
* Unifies the code for rebalance of sets and maps
* applies inlining as found in OCaml versions

### CODE REVIEW

**Comment by forki** [comment]
I'm planning to apply the same changes to the versions in map.fs and set.fs

The only open question is why MapOne and SetOne are not used consistently. Should we remove these?

**Comment by forki** [comment]
OK this is ready

**Comment by dsyme** [comment]
@forki Do you have tests that showing the inlining makes a difference?  I'm not opposed to doing it, but would not normally inline a function as large as ``mk`` without performance evidence. thx

**Comment by dsyme** [comment]
> The only open question is why MapOne and SetOne are not used consistently. Should we remove these?

MapOne and SetOne increase lookup time (more discrimination) but decrease memory usage (I think by about 1/4).  There's no right or wrong here - we went back and forth on this - and we landed where we are, and shouldn't really change it without good reason

**Comment by forki** [comment]
mk and height are very similar in size. One pattern match and a return value.
At this point it's more about making things symmetrical.

regarding MapOne: I find weird that it's not used consistently in both versions of map

.

**Comment by dsyme** [comment]
There's a big performance suite for Map/Set at https://github.com/fsharp/fsharp/tree/master/tests/perf/MapSet, please give that a go.

> At this point it's more about making things symmetrical.

I don't think that's a methodology we can apply beyond garnering inspiration/ideas.  StandardML, OCaml, .NET runtimes etc. have different performance profiles and I don't think we can take lessons from one and apply them to the other without backing evidence.  And we also don't know any performance assumptions of the code - was it tested on 32bit? 64bit? Multi-core stress loads?  

> regarding MapOne: I find weird that it's not used consistently in both versions of map

Yes, IIRC we went back and forth but there wasn't really much difference either way.  However we decided to make the compiler use a copy of the Map/Set code so it could diverge if we wanted it to, e.g. because it can be optimized under the assumption that it is only being used by the workloads presented by the compiler itself.

**Comment by dsyme** [comment]
@forki I don't think we'll take this one - at least, we'd need hard performance figures to indicate the changes are worth the (small) churn

**Pull request closed without merging**
