### PR TITLE
Try to reproduce #351

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
@KevinRansom why is CI not picking this up?

**Comment by forki** [comment]
@dotnet-bot test this please

**Comment by forki** [comment]
As expected: 0c4e54c timed out

**Comment by forki** [comment]
so this PR proves that @gmpl's https://github.com/Microsoft/visualfsharp/pull/1530 fixes the endless loop reported in #351

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by forki** [comment]
closed because it's already applied

**Pull request closed without merging**
