### PR TITLE
Fix Inline Rename for properties

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I've made another attempt to fix this old dreadful bug:
 


Unfortunately, I've not find any differences in our implementation and http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/InlineRename/AbstractEditorInlineRenameService.cs

@Pilchie Do you have _any_ ideas what could cause such behavior? The bug is reproduced only if the last symbol usage are very close to the end of the document.

**Comment by dsyme** [comment]
> @Pilchie Do you have any ideas what could cause such behavior? The bug is reproduced only if the last symbol usage are very close to the end of the document.

Is it sensitive to the exact number of characters from the end of the identifier to the end of the document?  It looks like it.

If so it's surely that a source range is being checked against the original document, not the updated document?

**Comment by Pilchie** [comment]
What @dsyme said sounds plausible to me.

**Comment by cartermp** [comment]
I keep getting this assertion in a hive when typing out the code to try the fix with:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------




   at Microsoft.FSharp.Compiler.ErrorLogger.newIsInstalled@450.Invoke(Unit unitVar0)

   at Microsoft.FSharp.Compiler.ErrorLogger.chkErrorLogger@451.DiagnosticSink(PhasedDiagnostic phasedError, Boolean isError)

   at Microsoft.FSharp.Compiler.LexFilter.LexFilterImpl.pushCtxt(TokenTup tokenTup, Context newCtxt)

   at Microsoft.FSharp.Compiler.LexFilter.LexFilterImpl.hwTokenFetch(Boolean useBlockRule)

   at Microsoft.FSharp.Compiler.LexFilter.loop@2262-33.Invoke(Unit unitVar0)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.createLexerFunction@1485.Invoke(a arg00)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.matchBraces@1513-1.Invoke(FSharpList`1 stack)

   at Microsoft.FSharp.Compiler.Lexhelp.reusingLexbufForParsing[a](LexBuffer`1 lexbuf, FSharpFunc`2 f)

   at Microsoft.FSharp.Compiler.Lexhelp.usingLexbufForParsing[a](LexBuffer`1 lexbuf, String filename, FSharpFunc`2 f)

   at Microsoft.FSharp.Compiler.SourceCodeServices.Parser.matchBraces(String source, String fileName, FSharpParsingOptions options, String userOpName)

   at <StartupCode$FSharp-Compiler-Private>.$Service.MatchBraces@2853.Invoke(Unit unitVar)

   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)

   at <StartupCode$FSharp-Core>.$Control.loop@125-37.Invoke(FSharpFunc`2 action)

   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)

   at Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)

   at Microsoft.FSharp.Control.TaskHelpers.continuation@1184.Invoke(Task`1 completedTask)

   at Microsoft.FSharp.Control.TaskHelpers.continueWith@1194.Invoke(Task`1 delegateArg0)

   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by vasily-kirichenko** [comment]
@cartermp this assertion is on master as well.

**Comment by cartermp** [comment]
Can confirm that this fixes the issue.  I moved this issue into a new one rather than the old one, and it's linked

**Comment by cartermp** [comment]
This appears to also fix #3493

**Comment by vasily-kirichenko** [comment]
So you guys have not found 5 minutes for a whole week to merge this safe, transparent, pure bug fix PR.

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by cartermp** [comment]
Thanks @vasily-kirichenko

**Pull request merged**
