### PR TITLE
Make the Result type a struct and allow multi-case struct unions

### PR DESCRIPTION
**Pull request by dsyme**
This extracts the key part of https://github.com/Microsoft/visualfsharp/pull/1395 which we should consider taking for F# 4.1 - where multi-case struct unions are allowed, and the Result type is marked as a struct.

The introduction of StructOption and StructChoice types and their use as return types of active patterns can be done at a later point (though this checkin would allow these types to be defined in user code, as the patterns test case shows)

### CODE REVIEW

**Comment by KevinRansom** [comment]
Don
````
1) Failed : FSharp-Tests-Typecheck+Sigs.sigs
Error running command 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharpqa\testenv\bin\diff.exe' with args 'neg95.err neg95.bsl normalize' in directory 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\typecheck\sigs'. ERRORLEVEL 1 ERRORLEVEL 1
at NUnitConf.checkTestResult(Result`2 result) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\nunitConf.fs:line 14
````
Probably the baseline file needs updating.

**Comment by KevinRansom** [comment]
Surface area tests are failing.  Some public apis have changed.

**Comment by KevinRansom** [comment]
@dsyme,

Nope baselines still broken.  I will take care of it in the morning.

Kevin

**Comment by dsyme** [comment]
@KevinRansom Baselines now properly updated

**Comment by KevinRansom** [comment]
@dsymeThank you for this contribution.

**Comment by wallymathieu** [comment]
Nice!

**Pull request merged**
