### PR TITLE
whitespace cleanup

### PR DESCRIPTION
**Pull request by dsyme**
Make whitespace consistent in a few files, especially space after comma

### CODE REVIEW

**Comment by dsyme** [comment]
@KevinRansom thx (now all the FCS code is finally aligned it's a good time to do this)

**Comment by KevinRansom** [comment]
Well we should use a tool, didn't dungpa have a source code formatter?

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
> Well we should use a tool, didn't dungpa have a source code formatter?

Yes, it's called Fantomas. Among modern IDEs only Rider currently has it integrated (Ctrl+Alt+L).

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
Yes, we should integrate Fantomas and stress test it on the compiler code itself.  It would do much, much more reformatting than the changes made here, but perhaps we could drive it little by little

**Comment by forki** [comment]
First there would be VF# integration needed. Otherwise it's hard to do.


Am 01.09.2017 12:04 nachm. schrieb "Don Syme" <notifications@github.com>:

**Comment by dsyme** [comment]
> First there would be VF# integration needed. Otherwise it's hard to do.

Which integration do you mean?  Updating Fantomas to FCS latest?

**Comment by forki** [comment]
No. Putting it in VS so that everyone sees the suggestions

Am 01.09.2017 12:10 nachm. schrieb "Don Syme" <notifications@github.com>:

**Comment by dsyme** [comment]
> No. Putting it in VS so that everyone sees the suggestions

Still not quite sure what you mean :)

**Comment by vasily-kirichenko** [comment]
> We would do source-code inclusion of a specific version of Fantomas, then update it step by step.

Looks good to me. However, [the license](https://github.com/dungpa/fantomas/blob/master/LICENSE.md) is Apache 2.0, would it be OK to copy code from there? 

/cc @dungpa

**Comment by KevinRansom** [comment]
@dsyme, @vasily-kirichenko, @dungpa

yes we could pull the Fantomas code into this repo.  The Apache license allows that, there are things we have to do when we pull it, book-keeping type stuff.  It would be a really useful addition to the FCS, and then enabling it inside VS would be a super great.

Alternatively we may just be able to use it as a separate library acquired via nuget.  I have no idea which is preferable.

**Pull request merged**
