### PR TITLE
Remove double lookups from ConstraintSolver

### PR DESCRIPTION
**Pull request by forki**
extends #4731

### CODE REVIEW

**Comment by dsyme** [comment]
Oh it's red - the code looked ok but there must be a glitch there

**Comment by forki** [comment]
Yeah. Something weird happened.

Don Syme <notifications@github.com> schrieb am Do., 19. Apr. 2018, 00:46:

**Comment by forki** [comment]
ok will try to send separate PRs

**Comment by KevinRansom** [comment]
@forki Thanks for this.

**Pull request merged**
