### PR TITLE
fix syntax errors and transitive errors in scripts

### PR DESCRIPTION
**Pull request by dsyme**
This fixes a bunch of issues with error reporting in scripts

* Transitive missing script files not showing: https://github.com/Microsoft/visualfsharp/issues/1962
* Errors not going away: https://github.com/Microsoft/visualfsharp/issues/1925

The second was caused by recent F# 4.1 fixes to replay errors from the load closure computation.  We need to be more selective about which errors we replay (do not replay parsing errors, which may not be valid for cached entries in the loadClosure cache).

We also had a bad cache key in script LoadClosure computation (we were not keying on  the full set of ``#load`` directives which support the LoadClosure computation, and were not keying on unresolved assembly references)

Some testing needs to be added, will look at that tomorrow

I added some cleanup for diagnostics processing in general, unifying the "Error" and "Warning" paths into single "Diagnostic" paths, passing the ``isError`` parameter.  Some paths were using ``warn`` == ``not isError`` and these are switched around to just use ``isError``

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dsyme Please don't Pull any PR's for a while.

**Comment by forki** [comment]
@KevinRansom couldn't just use another branch for release preparation? This would not stop the time for others.

**Comment by KevinRansom** [comment]
@forki we could have, and will next time around ... it's just that the insanity of the last few weeks meant we wanted to stay with what we had until too late to change.

**Comment by forki** [comment]
From what I can see I have to say the last 2 or 3 weeks were awesome for
the project ;-)

Am 07.12.2016 22:44 schrieb "Kevin Ransom (msft)" <notifications@github.com
>:

@forki <https://github.com/forki> we could have, and will next time around
... it's just that the insanity of the last few weeks meant we wanted to
stay with what we had until too late to change.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/pull/1963#issuecomment-265583020>,
or mute the thread

**Comment by dsyme** [comment]
@KevinRansom No problem.  
* If you could use an rc2 branch (``git push visualfsharp master:rc2``) that would be great but I'm totally ok either way.  
* I pushed a branch ``bleeding-edge`` containing a bunch of new the features.  I'll aim to keep it up to date

**Comment by KevinRansom** [comment]
We will use rc3 for the next release and master.  Brett has to generate the necessary VSO build goop ... and we will be golden.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@KevinRansom I'm bringing this PR up-to-date, thanks

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by cartermp** [comment]
Woot!  Happy to see this merged.

**Comment by dsyme** [comment]
Super, thanks for merging

**Pull request merged**
