### PR TITLE
build portable PDBs from SDK projects and convert to Windows PDBs after build

### PR DESCRIPTION
**Pull request by brettfo**
Follow-up to #4521 and #4524.

### CODE REVIEW

**Comment by brettfo** [comment]
@dotnet-bot test Ubuntu16.04 Release_fcs Build

**Comment by dsyme** [comment]
@brettfo I'm getting this error when building from Visual Studio.  AFAIK the only difference is that Visual Studio uses a multi-proc build be default.  Could that be causing this?

```
15>C:\GitHub\dsyme\visualfsharp\build\targets\ConvertPortablePdbs.targets(17,5): error MSB3073: The command ""C:\Users\dsyme\.nuget\packages\Microsoft.DiaSymReader.Pdb2Pdb\1.1.0-roslyn-62714-01\tools\Pdb2Pdb.exe" "C:\GitHub\dsyme\visualfsharp\vsintegration\Utils\LanguageServiceProfiling\bin\Debug\LanguageServiceProfiling.exe" /out "C:\GitHub\dsyme\visualfsharp\Debug\net40\bin\ConvertedPdbs\LanguageServiceProfiling.pdb" /verbose /srcsvrvar SRC_INDEX=public" exited with code 3.
15>Done building project "LanguageServiceProfiling.fsproj" -- FAILED.
```

**Comment by KevinRansom** [comment]
You need to do a git clean then a rebuild

**Comment by dsyme** [comment]
@KevinRansom @brettfo I still get the same error after 

   git clean -xfd
   .\build vs debug

the building VisualFSharp.sln from the IDE

```
40>The system cannot find the path specified.
40>C:\GitHub\dsyme\visualfsharp\build\targets\ConvertPortablePdbs.targets(17,5): error MSB3073: The command ""C:\Users\dsyme\.nuget\packages\Microsoft.DiaSymReader.Pdb2Pdb\1.1.0-roslyn-62714-01\tools\Pdb2Pdb.exe" "C:\GitHub\dsyme\visualfsharp\vsintegration\src\FSharp.LanguageService\bin\Debug\FSharp.LanguageService.dll" /out "C:\GitHub\dsyme\visualfsharp\Debug\net40\bin\ConvertedPdbs\FSharp.LanguageService.pdb" /verbose /srcsvrvar SRC_INDEX=public" exited with code 3.
40>Done building project "FSharp.LanguageService.fsproj" -- FAILED.

```

**Comment by KevinRansom** [comment]
It must be a timing thing then, because I just did exactly the same and the build worked

**Comment by dsyme** [comment]
Full IDE build log here https://gist.github.com/dsyme/a97d9e969c56084c384be07079faf636

```
========== Build: 32 succeeded, 12 failed, 7 up-to-date, 0 skipped ==========
```

Second time I get 11 project failures: https://gist.github.com/dsyme/dd32ab38723f1ba038c9bc3a1cb96ae5

BTW we have to get multi-proc build robust since Visual Studio uses it by default, and AFICS there's no way to turn it off at the solution level

**Comment by dsyme** [comment]
@KevinRansom @brettfo It's 100% repro for me.  This is dev15.6.  I have a nightly installed, I'll try to remove that

**Comment by KevinRansom** [comment]
@brettfo can you look again at the vb project symbol generation?

**Comment by brettfo** [comment]
The error message (error code 3) is from the `<Exec>` task because `Pdb2Pdb.exe` can't be found, so it looks like it's either a restore issue, or an issue with locating the package after restore.  I'm cleaning and taking a look now.

**Comment by dsyme** [comment]
```
 Directory of C:\GitHub\dsyme\visualfsharp\packages\microsoft.diasymreader.pdb2pdb\1.1.0-roslyn-62714-01\tools

13/03/2018  18:50            27,552 Pdb2Pdb.exe
               1 File(s)         27,552 bytes
```

**Comment by brettfo** [comment]
Ahh, found it.  We restore packages to the `packages` directory, but the `$(NuGetPackageRoot)` variable was falling back to `%USERPROFILE%\.nuget\packages` because the `NUGET_ROOT` environment variable isn't set in VS.

I'll update the computation of `$(NuGetPackagesRoot)` and see if that fixes it.

**Comment by dsyme** [comment]
@brettfo Thanks

**Comment by brettfo** [comment]
As an update the error code 3 (`Pdb2Pdb.exe` can't be found) is fixed with my better computation of `$(NuGetPackageRoot)` but now I'm getting a different issue where a command-line build of the property pages assembly (VB) creates a portable PDB, but an IDE build creates a Windows PDB which then fails the tool because the `$(DebugType)` property is still `portable`.  I'll spend a few minutes looking into that and if I can't figure anything out then I'll switch just the property pages assembly to explicitly set `<DebugType>full</>` until the real issue can be found.

**Comment by brettfo** [comment]
Just created #4548 which should fix the building in VS issues.  #4541 is still an issue that I'll be addressing.

**Pull request merged**
