### PR TITLE
Fix SignatureHelpProviderTests

### PR DESCRIPTION
**Pull request by forki**
Current master is broken since @cartermp's commit 50e7a829c5ca46976d62866eed2884498dfbfec7

This is an attempt to fix it, but I'm not sure if the test is broken or the code itself

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
image

image

**Comment by forki** [comment]
So what does it mean? Fixing tests or code?

**Comment by vasily-kirichenko** [comment]
Before:

image

image

**Comment by vasily-kirichenko** [comment]
Looks the same.

**Comment by vasily-kirichenko** [comment]
Why are "arg0" and "An object to write using format" on different lines? It should be fixed.

**Comment by dsyme** [comment]
@vasily-kirichenko @forki There's something in Roslyn method displays we can't control here - I'm sure we can get them to change it eventually

``arg0`` is the name of the parameter in the .NET metadata

```
.method public hidebysig static void  WriteLine(string format,
                                                object arg0) cil managed noinlining
{
  .permissionset linkcheck
             = {class 'System.Security.Permissions.HostProtectionAttribute, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' = {property bool 'UI' = bool(true)}}
  // Code size       13 (0xd)
  .maxstack  8
  IL_0000:  call       class System.IO.TextWriter System.Console::get_Out()
  IL_0005:  ldarg.0
  IL_0006:  ldarg.1
  IL_0007:  callvirt   instance void System.IO.TextWriter::WriteLine(string,
                                                                     object)
  IL_000c:  ret
} // end of method Console::WriteLine

```

**Comment by vasily-kirichenko** [comment]
@dsyme what I don't like here is that "arg0" and its XML Doc are on different lines, that's all.

**Comment by forki** [comment]
ok seems there are more to come. but since I can't compile this it will take some time until I have the tests fixed

**Comment by forki** [comment]
ok changed test a bit to actually report all issues.

**Comment by forki** [comment]
this should become green now and therefore fix the build on master. @dsyme / @KevinRansom / @cartermp please take a look and merge if you think it's ok

**Comment by cartermp** [comment]
@forki Thanks.  Not sure why this went wrong, but I imagine the document created temporarily by the tests _on the server_ is different than that on my machine when I updated these tests.  That would explain the discrepancy in `TextSpan`s.

I think that first item in the tuple can just be outright ignored.  I don't think that verifying that the correct `TextSpan` is the same is very meaningful from a test perspective.  The important bit is that the current argument and total number of arguments is accurate.

@dsyme @vasily-kirichenko I don't think that behavior is going to change in Roslyn, or at least not for vs2017 RTM.  To clarify, what this means is that you would be requesting that F# be treated as a special case on signatures to show _all parameters for a given method at all times_, (something we currently generate in our codebase, but would likely have to pass off to Roslyn) and have Roslyn highlight the current parameter of that set.  I very much disagree that this is the correct thing to do, but there is a discussion at #1910.

**Comment by dsyme** [comment]
@cartermp Right now I think I'm just totally focusing on recovering parity with VS2015 rather than working out what's actually right/wrong :) 

I think one key post RTM is to implement other relevant navigation aids (go to generated signature, F1 help etc), and cleanup quick info too.

**Comment by cartermp** [comment]
@dsyme I figured it out; it's entirely on our end and has nothing to do with Roslyn.

**Comment by forki** [comment]
Tbh most important right now is green build ;-)

Am 06.12.2016 6:25 nachm. schrieb "Phillip Carter" <notifications@github.com

**Comment by cartermp** [comment]
@forki Agreed, this is tangential and not related to this PR

**Comment by cartermp** [comment]
AppVeyor failures don't seem to be an issue.  @KevinRansom can you verify and pull this if it's all good?  This fixes a test in CI that's been going red for unrelated PRs.

**Comment by forki** [comment]
Please please merge.

**Pull request merged**
