### PR TITLE
[WIP] add new sdk fsproj

### PR DESCRIPTION
**Pull request by enricosada**
Added `.netcore.fsproj` for .net core sdk 1.0

this is going to be a 1-1 conversion of `build coreclr`, to just replace project.json with new sdk.
So build output will go in usual directories `bin\release\coreclr` etc

- `FSharp.Core`
- `FSharp.Compiler`
- `fsc`

this semplify build a lot in the future for new dev

```
cd src\fsharp\Fsc
dotnet restore Fsc.netcore.fsproj
dotnet build Fsc.netcore.fsproj -c Release
dotnet bin\Release\netcoreapp1.1\fsc.dll
```

msbuild can be used too, just `msbuild /t:Restore` and `msbuild /t:Build` instead of `dotnet build/restore`. Same on mono

Same fsprojs can be used to build `netstandard2,0` and fsc `netcoreapp2.0` later.

## TODO

- [x] fix internal visible error signing assemblies, otherwise fsc doesnt work
- [ ] install .net core sdk 1.0.1 in build script
- [ ] replace `build coreclr` completly
- [x] use proto-compiler (it's really needed @dsyme? atm just use `FSharp.Compiler.Tools`)
- [ ] check `dotnet`/msbuild vs/mono
- [ ] replace `FsSrGen`
- [ ] just one `--keyfile`
- [ ] copy `default.win32manifest` to out dir
- [ ] create AssemblyFileVersion file, until https://github.com/dotnet/netcorecli-fsc/issues/93 is fixed

/cc @KevinRansom @cartermp @dsyme @brettfo

### CODE REVIEW

**Comment by saul** [comment]
Does this mean we can get rid of the project.json files? I'm not too clued up on this.

**Comment by enricosada** [comment]
@saul yes, this will replace the project.json (who are a prerelease of dotnet cli).
pratically all `build coreclr`.
In the future the same fsproj can build all frmeworks too, because new sdk support multi target framework, so `netcoreapp2.0`, `net45`, etc

**Comment by enricosada** [comment]
I need a bit of help.
i am stuck with internal visibile afaik.

```
Unhandled Exception: System.MethodAccessException: Attempt by method 'Microsoft.FSharp.Compiler.CommandLineMain.main(System.String[])' to access method 'Microsoft.FSharp.Compiler.ErrorLogger+BuildPhase.get_Parameter()' failed.
   at Microsoft.FSharp.Compiler.CommandLineMain.main(String[] argv) in e:\github\fsharp\src\fsharp\fscmain.fs:line 52
```

i think arguments are ok (i checked with current `build coreclr`).
i added both

```
         --delaysign+
         --keyfile:e:\github\fsharp\src\fsharp\FSharp.Core\..\..\fsharp\msft.pubkey
```

in the current `build coreclr` there is

```
  --keyfile:e:\github\fsharp\Tools\MSFT.snk
  ...
  --delaysign+
  --keyfile:e:\github\fsharp\src\fsharp\FSharp.Core\..\..\fsharp\msft.pubkey
```

yes, keyfile is written two times. i trid with both. and define is `STRONG_NAME_AND_DELAY_SIGN_FSHARP_COMPILER_WITH_MSFT_KEY`

i checked others fsc args from `build coreclr` and `dotnet build -v n` and seems ok..

**Comment by KevinRansom** [comment]
Debug build on coreclr does not work due to a coreclr bug.

It has recently been fixed.

https://github.com/dotnet/coreclr/issues/3541

**Comment by enricosada** [comment]
@KevinRansom i am doing always `dotnet build -c Release` (to do exactly like `build coreclr`), i tried also `Debug` but that doesnt work either.

**Comment by enricosada** [comment]
I'll try the .net core sdk 2.0, let's see if is fixed there so.
It's strange works with build `coreclr`.
@KevinRansom alternative is make things public? so we ignore the internal visibile for now?

**Comment by KevinRansom** [comment]
@enricosada I am working on porting the build to dotnet standard 2.0 right now.  It should have happened long before now, but I had "distractions".  It's probably easier if I take care of it.

**Comment by enricosada** [comment]
@KevinRansom  i understand 2.0 is important, but i'd like to have a `netcoreapp1.1` fsc because is needed for some so where .NET Core Runtime is only 1.1
And is possibile easly to have both, sdk1.0 and 2.0 because are compatibile.
Use only 2.0, who is not yet a public preview drop, is a bit annoying.

Also this alreay works, with `build coreclr`, so i just want to do the same.

i tried set `<DebugType>pdbonly</DebugType>`
because that set jittracking to false (ref [source](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/CompileOptions.fs#L470) )

But same error. any other flag i can set to workaround that error?

**Comment by enricosada** [comment]
You to be sure. 
if i have `STRONG_NAME_AND_DELAY_SIGN_FSHARP_COMPILER_WITH_MSFT_KEY` compiler define, what keyfile should i use? atm in build log there are both as `--keyfile` is normal? or just one is used?
and `--delaysign+` is ok with that too.

**Comment by enricosada** [comment]
@KevinRansom @cartermp success :D

recf-fsc-1

I replicated exactly same `build coreclr` args.
Now i just need to cleanup a bit.

And works if i use built `bin\Release\netcoreapp1.1\fsc.dll` as `FscToolPath`/`FscToolExe` in to build a new console app!

**Comment by enricosada** [comment]
@KevinRansom with https://github.com/Microsoft/visualfsharp/pull/2971/commits/2673cf4df1ef4fc39f9ce27c61783d2771d5950a i added `netstandard2.0` tfm to `FSharp.Core.netcore.fsproj`, **it doesnt compile**  (compile errors), but invoke `proto-fsc` normally, with .net standard 2.0 references, so maybe is easier for develop.
Anyway was just to check we can use same fsproj for both sdk (1.0 and 2.0-preview1)
The `NuGet.netcore2.config` contains the dev feed for .net core 2.0 and the f# sdk package for build `netstandard2.0` (is just he same as 1.0.4, but doesnt fail at restore becase missing `netstandard2.0` targetfw)

```
dotnet restore FSharp.Core.netcore.fsproj --configfile ..\..\..\NuGet.netcore2.config /p:TargetFramework=netstandard2.0
dotnet build FSharp.Core.netcore.fsproj -f netstandard2.0 -v n
```
the `/p:TargetFramework=netstandard2.0` override the prop defined in fsproj, so i dont need to use crossgen `<TargetFrameworks>` and works ootb with 1.0 (i need to check if i can add a condition based on sdk version, to use both with TargetFrameworks)

Atm fails, (i tried a bit with defines, but is not this current issue so i stopped) anyway is:

```
Build FAILED.

       "e:\github\fsharp\src\fsharp\FSharp.Core\FSharp.Core.netcore.fsproj" (Build target) (1) ->
       (CoreCompile target) ->
         e:\github\fsharp\src\fsharp\FSharp.Core\quotations.fs(1726,17): error FS0001: This expression was expected to have type    'Patterns.ModuleHandle'    but here has type    'ModuleHandle' [e:\github\fsharp\src\fsharp\FSharp.Core\FSharp.Core.netcore.fsproj]

    0 Warning(s)
    1 Error(s)
```

**Comment by dsyme** [comment]
Do you need to delete this define? https://github.com/Microsoft/visualfsharp/pull/2971/files#diff-42e40e4c9233edc86b0ee6fb12574488R43

**Comment by enricosada** [comment]
@dsyme i tried, but with that i get another error, so i stopped, is a bit out of topic.

```
"e:\github\fsharp\src\fsharp\FSharp.Core\FSharp.Core.netcore.fsproj" (Build target) (1) ->
(CoreCompile target) -> 
   FSC : error FS2014: A problem occurred writing the binary 'e:\github\fsharp\src\fsharp\FSharp.Core\obj\Debug\netstandard2.0\FSharp.Core.dll': Error in GetMethodRefAsMethodDefIdx for mref = (".ctor", "Microsoft.FSharp.Core.FSharpInterfaceDataVersionAttribute"), error: Exception of type 'Microsoft.FSharp.Compiler.AbstractIL.ILBinaryWriter+MethodDefNotFound' was thrown. [e:\github\fsharp\src\fsharp\FSharp.Core\FSharp.Core.netcore.fsproj]
```


for sure it's not an easy work, so i want to just consolidate sdk1.0 to generate a fsc `netcoreapp1.1` (needed for some oss) and simplify infra.
that example was for @KevinRansom maybe can help his netcore2 work. or not.

**Pull request closed without merging**
