### PR TITLE
Fix to pass tests with only VS2015 installed

### PR DESCRIPTION
**Pull request by dsyme**
Tests fail when you only have Dev14 (VS2015) installed.  

(nb. We aim to allow development with VS vCurrent  and VS vNext.  Right now vCurrent = VS2015)

I'm trying to run tests on my local machine now to see if it works

@forki  @otawfik-ms  Note that AppVeyor CI was testing with VS2015 installed (I think).  I guess that's one reason to continue to enable that CI.

### CODE REVIEW

**Comment by dsyme** [comment]
Tests certainly get a lot further now, and this is otherwise non-intrusive, so merging

**Comment by otawfik-ms** [comment]
@dsyme I see 2 FSharpQA tests failing because of that change. Did I miss something?

**Comment by KevinRansom** [comment]
@dsyme @otawfik-ms I re-enabled AppVeyor it is useful as a double check against Jenkins, I will keep it going for at least another month.  Omar will enable a couple of Dev 14 build and test runs for PR checkins.  So that we can verify both.

Kevin

**Comment by dsyme** [comment]
Thanks, sounds good

**Pull request merged**
