### PR TITLE
Fix 3317 - don't apply line directives when analyzing files for editing

### PR DESCRIPTION
**Pull request by dsyme**
This is a tentative fix for https://github.com/Microsoft/visualfsharp/issues/3317

The change means that, for the language service "foreground" requests (ParseAndCheckFile, MatchBraces etc.), all ranges reported when analyzing files that contain ``#line`` directives are reported w.r.t. the original file and not the designated file.  All the AST and TAST spans (ranges) reported will be w.r.t. the original file.  This is the correct information to report for use by editing clients.

I've tested the fix by hand and it is sound enough to try if you are hitting the crash in #3317 often

### CODE REVIEW

**Comment by dsyme** [comment]
Test added, this is now ready

**Comment by dsyme** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please

**Comment by cartermp** [comment]
@dsyme For unrelated reasons I had to remove my fork of VF# and local repo, but after a fresh clone and build of this PR I get the following error:

```
"C:\repos\visualfsharp\VisualFSharp.sln" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj" (default target) (13) ->
(CoreCompile target) ->
  FSC : error FS0193: Could not find file 'C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\obj\net40\ProjectResourc
es.rc.res'. [C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj]

    6 Warning(s)
    1 Error(s)
```

**Comment by dsyme** [comment]
@cartermp looks unrelated though

**Comment by cartermp** [comment]
Ugh, no idea why this would be happening.  I'll see if I can resolve that later before verifying the fix as well

**Comment by vasily-kirichenko** [comment]
@cartermp maybe it's the old issue with resource compilation? I believe you need to install the c++ sdk.

**Comment by cartermp** [comment]
Yeah, I have that installed which is weird.  I'm just going to pave my machine and start over.

**Comment by dsyme** [comment]
@cartermp Thank you so much for validating.  

@KevinRansom this is ready

**Pull request merged**
