### PR TITLE
Keep the reference icons when opening references

### PR DESCRIPTION
**Pull request by dungpa**
Close https://github.com/Microsoft/visualfsharp/issues/559.

### CODE REVIEW

**Comment by forki** [comment]
WTF!? That's the change? Crazy.

**Comment by latkin** [comment]
lol, nice. Honestly seems like *we* are doing the right thing and C# should change... Ah well, LGTM.

**Comment by dungpa** [comment]
I don't mind either way. Visually, I think C# project system does the right thing. We shouldn't display a folder as a reference group; it's quite confusing.

**Comment by dungpa** [comment]
BTW, it's fun to send two one-liner PRs in a row :sunglasses:

**Pull request closed without merging**
