### PR TITLE
Typed Unused Opens analyzer

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This is a rewrite of the analyzer. It uses `EntityRef list` corresponding to each open declaration, gets its  content and check if any symbol is used in the open declaration scope. No more long id fiddling and such. It should work precisely, always (no false positives, no missed unused opens).  

As a side effect, module usages are now found in open declarations:

image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by vasily-kirichenko** [comment]
Another side effect: simplify name now works on open declarations:

image

**Comment by dhwed** [comment]
This is awesome; thanks.

The only issue I've found so far is with C# style extension methods:

```fsharp
open System.Linq

module Test =
    let _ = [].ToList()
```

Here, `System.Linq` is grayed out even though `ToList()` is an extension method defined in `System.Linq.Enumerable`.

**Comment by vasily-kirichenko** [comment]
@dhwed Thanks for testing! :) Will try to fix it. There is another very subtle bug, will fix it today.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
It needs almost 2 minutes to process TypeChecker.fs.

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test Ubuntu14.04 Release_fcs Build please

**Comment by vasily-kirichenko** [comment]
It's ready. It's slow on large files, but works correctly. As @dsyme implements https://github.com/fsharp/FSharp.Compiler.Service/issues/830, it will be very easy to make this analyzer very fast. 

We should push Roslyn team to implement priority and parallel execution of analyzers. Any progress on this?

**Comment by KevinRansom** [comment]
@dotnet-bot build this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
I'm not sure whether the _fsc failures are expected to pass?

Certainly pr's today have beem green.

@forki?

**Comment by forki** [comment]
It reports fcs tests errors. Not sure. @vasily-kirichenko could you please rebase and if things are still red we need to take a look at that unit test

**Comment by vasily-kirichenko** [comment]
Fixed.

**Comment by forki** [comment]
So it really caught its first bug?

Am 28.10.2017 16:49 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by forki** [comment]
Lol. You are welcome.

But on more serious note: it's good to deal with this early. Maybe that
takes a bit of work away from @dsyme when he does the merges

Am 28.10.2017 19:52 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
@dsyme I cannot see why the FCS repo is needed anymore now.

**Comment by KevinRansom** [comment]
@vasily-kirichenko 

Thanks for this

Kevin

**Comment by dsyme** [comment]
@vasily-kirichenko Re FCS - see https://github.com/fsharp/FSharp.Compiler.Service/issues/834 and let's discuss there.

**Pull request merged**
