### PR TITLE
Tests shouldnt open windows

### LINKED ISSUE #1099: Build opens flickering command line windows
If I run `build.cmd all` on my Windows 10 machine I see command line windows popping up during build. This is a bit annoying since it steals my concentration when I run the full build in background.

I think we discussed this before and saw improvement of this. But somehow this is back. I assume it's related to nunit 3, but I'm not completely sure. /cc @enricosada

### PR DESCRIPTION
**Pull request by enricosada**
fix #1099

Windows opened:

fsharp suite:

- [X] fsc.exe
- [x] blue window form

### CODE REVIEW

**Comment by dsyme** [comment]
Looks like the blue window form is here  C:\GitHub\dsyme\visualfsharp\tests\fsharp\regression\656\form.fs?

I think just deleting the run.bat would be ok, or making it so it doesn't run the program.  Running this program isn't achieving any additional significant testing.

**Comment by enricosada** [comment]
removed all flickering windows in fsharp suite, ready for review/merge

**Comment by dsyme** [comment]
Looks good

**Comment by enricosada** [comment]
@dsyme removed the run, just build

**Comment by enricosada** [comment]
i checked the others tests with `.Show(` , `Application.Run` too, but these are all commented out or not run, just build

**Comment by enricosada** [comment]
btw i'll check fsharpqa in another pr, no time now and no need to wait it
Meanwhile this is pr ok to review/merge

**Comment by dsyme** [comment]
Merging as this is test stuff

**Pull request merged**
