### PR TITLE
Fix for issue #276: Combinding struct field with units of measure will result managed type instead of unmanaged type

### PR DESCRIPTION
**Pull request by andrewjkennedy**
Fix for https://github.com/Microsoft/visualfsharp/issues/276

### CODE REVIEW

**Comment by enricosada** [comment]
this pr contains a merge commit e644ddd 
If you rebase aganist fsharp4 you can cleanup the pr (and squash commits if needed)

**Comment by dsyme** [comment]
I mentioned to Andrew that Lincoln could probably fix this up when squashing/merging.  Rebasing is such a pain.

**Comment by latkin** [comment]
@andrewjkennedy -- I see "unit tests to follow" in the commit comment, do you have ETA?

**Comment by latkin** [comment]
I added a quick test covering the original bug before applying this, per offline sync with @andrewjkennedy

**Pull request closed without merging**
