### PR TITLE
Revert "update vsix package authoring to use the latest tools"

### PR DESCRIPTION
**Pull request by brettfo**
This reverts commit 24de4a9350bba475ccc30e6104124a62baa164c2 and makes building/testing on Dev14 work again.

### CODE REVIEW

**Comment by rojepp** [comment]
@dsymes addition should be reversed to?

**Comment by brettfo** [comment]
Good catch, just did that directly in `master`.  FYI, I'm doing a full writeup of what happened and posting it in #1967 in just a few minutes if you're interested.

**Comment by dsyme** [comment]
> ... and makes building/testing on Dev14 work again.

Do you mean Dev15 RC (Dev14 hasn't worked for a long time)? thanks!

**Comment by brettfo** [comment]
Yes, thank you; Dev15 RC.

**Pull request merged**
