### PR TITLE
Add an extra Unused Opens analyzer test

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
:(

**Comment by KevinRansom** [comment]
@vasily-kirichenko yeah the CI seems to be still in transit.   Oh well .

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test Windows_NT Release_fcs Build please

**Comment by vasily-kirichenko** [comment]
@dotnet-bot  test Ubuntu14.04 Release_fcs Build please

**Pull request merged**
