### PR TITLE
Use lazy evaluation for useMethodImpl

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by KevinRansom** [comment]
@forki 
ci_part4 fails, can you check it out pls:
````
018-10-03T05:37:20.7984797Z Failed   Test request for parse and check doesn't check whole project
2018-10-03T05:37:20.7986109Z Error Message:
2018-10-03T05:37:20.7986946Z    Expected: true
2018-10-03T05:37:20.7987886Z Actual: false
2018-10-03T05:37:20.7988735Z   Expected: True
2018-10-03T05:37:20.7989523Z   But was:  False
2018-10-03T05:37:20.7990393Z 
2018-10-03T05:37:20.7991202Z Stack Trace:
2018-10-03T05:37:20.7992049Z    at FsUnit.shouldEqual[a](a x, a y) in D:\a\1\s\tests\service\FsUnit.fs:line 19
2018-10-03T05:37:20.7993231Z    at Tests.Service.ProjectAnalysisTests.Test request for parse and check doesn't check whole project() in D:\a\1\s\tests\service\ProjectAnalysisTests.fs:line 5099
2018-10-03T05:37:20.7994595Z 
2018-10-03T05:37:22.3161133Z Skipped  Test symbol uses of type-provided types
2018-10-03T05:38:01.3868710Z Results File: D:\a\1\s\fcs\FSharp.Compiler.Service.Tests\TestResults\VssAdministrator_factoryvm-az377_2018-10-03_05_33_36.trx
2018-10-03T05:38:01.3869574Z 
2018-10-03T05:38:01.3869790Z Total tests: 233. Passed: 212. Failed: 1. Skipped: 20.
2018-10-03T05:38:01.3871094Z Test Run Failed.
2018-10-03T05:38:01.3871926Z Test execution time: 4.5059 Minutes
2018-10-03T05:38:01.4622601Z 
2
````

**Comment by forki** [comment]
Wow that's surprising.

**Comment by KevinRansom** [comment]
@forki,

I quite like this change, the code is uglier, but I think the logical short circuit evaluation will be beneficial.
It will take a bit more of a look to determine that the logic is the same, and probably a squint at the il to see what is generated.


Kevin

**Comment by forki** [comment]
It's now green. I didn't change anything since that red build. I only restarted it since I was rather confident that it was same logic. So we must hit a flaky test or something.

**Comment by KevinRansom** [comment]
@forki … agreed.  I will take a look at the details over the weekend.

**Comment by KevinRansom** [comment]
@forki 

Thank you

**Pull request merged**
