### PR TITLE
Use CDN to install dotnetcli ---- should be much quicker

### PR DESCRIPTION
**Pull request by KevinRansom**
Yeah ... we were installing these the slowest way possible.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot build this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by forki** [comment]
Urgs please no Powershell

**Comment by KevinRansom** [comment]
@forki 
This is from the dotnet cli repo.  not something we will ever have to muck with.

The old one was a batch file ... surely that is not better.

Kevin

**Pull request merged**
