### PR TITLE
Remove fsiPackage.fs

### PR DESCRIPTION
**Pull request by cartermp**
The file is empty

### CODE REVIEW

**Comment by cartermp** [comment]
ngen failure wat

**Comment by cartermp** [comment]
Seemingly unnrelated FCS test failure: 

```
2018-10-30T03:31:46.9607278Z Total tests: 234. Passed: 230. Failed: 0. Skipped: 4.
2018-10-30T03:31:46.9607819Z Test Run Successful.
2018-10-30T03:31:46.9608434Z Test execution time: 33.6183 Seconds
2018-10-30T03:31:46.9984608Z Test run for D:\a\1\s\fcs\FSharp.Compiler.Service.Tests\bin\Release\netcoreapp2.0\FSharp.Compiler.Service.Tests.dll(.NETCoreApp,Version=v2.0)
2018-10-30T03:31:47.0453646Z Microsoft (R) Test Execution Command Line Tool Version 15.8.0
2018-10-30T03:31:47.0454029Z Copyright (c) Microsoft Corporation.  All rights reserved.
2018-10-30T03:31:47.0454221Z 
2018-10-30T03:31:47.1079881Z Starting test execution, please wait...
2018-10-30T03:31:54.3270943Z Skipped  Ctor test
2018-10-30T03:31:54.3271793Z Skipped  Different namespaces with the same short name equality check
2018-10-30T03:31:54.3272198Z Skipped  Different types with the same short name equality check
2018-10-30T03:31:54.3272609Z Skipped  Test that csharp references are recognized as such
2018-10-30T03:31:54.3272933Z Skipped  Test that symbols of csharp inner classes/enums are reported
2018-10-30T03:32:17.4408328Z Failed   Test request for parse and check doesn't check whole project
2018-10-30T03:32:17.4408957Z Error Message:
2018-10-30T03:32:17.4409316Z    Expected: true
2018-10-30T03:32:17.4409621Z Actual: false
2018-10-30T03:32:17.4411308Z   Expected: True
2018-10-30T03:32:17.4411830Z   But was:  False
2018-10-30T03:32:17.4412154Z 
2018-10-30T03:32:17.4412482Z Stack Trace:
2018-10-30T03:32:17.4412876Z    at FsUnit.shouldEqual[a](a x, a y) in D:\a\1\s\tests\service\FsUnit.fs:line 19
2018-10-30T03:32:17.4413227Z    at FSharp.Compiler.Service.Tests.PerfTests.Test request for parse and check doesn't check whole project() in D:\a\1\s\tests\service\PerfTests.fs:line 67
```

**Comment by cartermp** [comment]
Test passes locally 😕

**Comment by cartermp** [comment]
@dsyme I have no idea what's going on, an unrelated FCS test fails in CI but passes locally as a result of removing an empty and unused file in an unrelated solution.

**Comment by dsyme** [comment]
@cartermp re-running tests to see if it's transient

**Pull request merged**
