### PR TITLE
import remaining FCS code

### PR DESCRIPTION
**Pull request by dsyme**
This is the start of the work to allow the FSharp.Compiler.Service component to be developed in this repository

This will take a while to get into shape..

Notes about this PR:

1. There are subtle differences between FSharp.Compiler.Service.dll (public API), FSharp.Compiler.dll (internal to fsc.exe and fsi.exe) and FSharp.LanguageService.Compiler.dll (internal to VS, some things trimmed out).   Because of this we don't try to unify these, but I expect we'll be able to in a subsequent round of work

2. FCS includes the "Project Cracker".  It's unclear if we should bring the code for that back as part of this PR.  Probably we should for completeness so we can retire https://github.com/fsharp/FSharp.Compiler.Service/

3. FCS included a number of changes in fsi.fs to turn that into an API.  Those changes hadn't yet been brought into this repo, and some of the changes use the Symbols API 

4. FCS includes the "FSharpExpr" API which hadn't previously been brought into this repo.    It's pretty well-tested through Fable so is reasonable to bring in, and there are additional tests as part of this PR

5. The project files didn't use a Proto compiler so some changes were needed there.

6. the FCS assembly is currently strong named with the Microsoft key.  Whether this key is used in the long run is another matter (the community built nuget packages used no strong name)

Currently you compile the FSharp.Compiler.Service.dll for .NET 4.x using

    msbuild fcs\FSharp.Compiler.Service\FSharp.Compiler.Service.fsproj

### CODE REVIEW

**Comment by dsyme** [comment]
Notes to self about this PR:

1. There are subtle differences between FSharp.Compiler.Service.dll (public API), FSharp.Compiler.dll (internal to fsc.exe and fsi.exe) and FSharp.LanguageService.Compiler.dll (internal to VS, some things trimmed out).   Because of this we don't try to unify these, but I expect we'll be able to in a subsequent round of work

2. FCS includes the "Project Cracker".  It's unclear if we should bring the code for that back as part of this PR.  Probably we should for completeness so we can retire https://github.com/fsharp/FSharp.Compiler.Service/

3. FCS included a number of changes in fsi.fs to turn that into an API.  Those changes hadn't yet been brought into this repo, and some of the changes use the Symbols API 

4. FCS includes the "FSharpExpr" API which hadn't previously been brought into this repo.    It's pretty well-tested through Fable so is reasonable to bring in, and there are additional tests as part of this PR

5. The project files didn't use a Proto compiler so some chagnes were needed there.

**Comment by dsyme** [comment]
Note to self: Still a lot of errors in the VS unit tests, I need to track them down, the list is here https://gist.github.com/dsyme/4215d12211d6423d7622de15ff3e3352

**Comment by KevinRansom** [comment]
@dsyme small conflict.

**Comment by dsyme** [comment]
@KevinRansom this is now ready.  It's a large PR but after this the codebases are aligned, at least where they overlap.  There is still a lot of work to do before we can build valid FCS packages - and there are a lot of other things to do to - but after this we can channel all contributions to FCS via this repo.

**Comment by 7sharp9** [comment]
A single source of truth would indeed be great, even in just the cognitive load of knowing whats been fixed where, what compiler mono is using etc.

**Pull request merged**
