### PR TITLE
Fix 1012 - remove pointless code

### PR DESCRIPTION
**Pull request by dsyme**
This should be the fix for https://github.com/Microsoft/visualfsharp/issues/1012.  It needs to be tested manually.

### CODE REVIEW

**Comment by rojepp** [comment]
This looks good. We know that ParseCanonicalName is slow,
so maybe this method could be optimized as part of this PR? https://github.com/dsyme/visualfsharp/blob/fix-1012/vsintegration/src/FSharp.ProjectSystem.FSharp/Project.fs#L1751 
It should only call ParseCanonicalName is propid is one we care about.

**Comment by dsyme** [comment]
@rojepp Thanks for taking a look!  That code is only ``#if DESIGNER`` which is old code which should be deleted

**Comment by rojepp** [comment]
Ok then, then LGTM I suppose! :)

**Comment by KevinRansom** [comment]
The open repo does not Set Design at all so.  Why not remove all of the code under #if Designer?

**Pull request merged**
