### PR TITLE
[WIP] RFC FS-1007 - Additional Option module functions

### PR DESCRIPTION
**Pull request by andredublin**
This pull request relates to the [additional option module functions RFC ](https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1007-additional-Option-module-functions.md)

I'd like to add this PR  so that discussion and development of the RFC can progress

### CODE REVIEW

**Comment by veikkoeeva** [comment]
> +1 I always hated getOrElse because it made me look stupid since I never know what it does. I don't want to look stupid.

Feels almost like a threat!

**Comment by forki** [comment]
Lol

**Comment by KevinRansom** [comment]
The failure is because a public API has been added to fsharp core.

**Comment by neoeinstein** [comment]
I think this is no longer WIP. (/ping @dsyme)

Functions added to `OptionModule`:
* `map2`
* `map3`
* `defaultIfNone`
* `defaultIfNoneFrom`
* `orElse`
* `orElseFrom`

I've added two other PRs for `contains` (#1778) and `flatten` (#1779).

**Comment by dsyme** [comment]
Closing in favour of https://github.com/Microsoft/visualfsharp/pull/1781

**Pull request closed without merging**
