### PR TITLE
Update nuget metadata

### PR DESCRIPTION
**Pull request by KevinRansom**
Write Preview 
Update nuget metadata per RFC 1005 ---- https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1005-package-signing.md

````
    <id>FSharp.Core</id>
    <version>4.3.5</version>
    <title>FSharp.Core for F# 4.1</title>
    <authors>Microsoft and F# Software Foundation</authors>
    <owners>Microsoft and F# Software Foundation</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <licenseUrl>https://github.com/Microsoft/visualfsharp/blob/master/License.txt</licenseUrl>
    <projectUrl>https://github.com/Microsoft/visualfsharp</projectUrl>
    <iconUrl>http://fsharp.org/img/logo.png</iconUrl>
    <description>FSharp.Core redistributables from Visual F# Tools version 10.1 For F# 4.1
                Supported Platforms:
                    .NET 4.5+           (net45)
                    netstandard1.6      (netstandard1.6)
                    netstandard2.0      (netstandard2.0)
                Commit hash: [developer build].</description>
    <summary>FSharp.Core for F# 4.1</summary>
    <copyright>(C) Microsoft Corporation. All rights reserved.</copyright>
    <language>en-US</language>
    <tags>Visual F# Compiler FSharp functional programming</tags>

````

### CODE REVIEW

**Comment by dsyme** [comment]
summary too

**Comment by KevinRansom** [comment]
Oh well … see … this is in the branch master which is still F# 4.1.

Those changes should be already in dev 15.8:

Check out here:
https://github.com/Microsoft/visualfsharp/blob/dev15.8/src/fsharp/FSharp.Core.nuget/FSharp.Core.LatestNuget.nuspec#L6

**Comment by cartermp** [comment]
Another nit:

`.NET 4.5+`

Should be:

`.NET Framework 4.5+`

Since .NET <> .NET Framework

**Comment by KevinRansom** [comment]
Sigh !!!!

**Pull request merged**
