### PR TITLE
Fixed binary reader error message

### PR DESCRIPTION
**Pull request by ncave**
Make all binary reader error messages the same (like [this one](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/CompileOps.fs#L3941)) so they show the actual error, otherwise the actual error is obscured and hidden.

### CODE REVIEW

**Comment by KevinRansom** [comment]
That's kind of a weird failure: @dotnet-bot test this please.

**Comment by KevinRansom** [comment]
@ncave 
It fails the same way on appveyor and in ci_part1 so I think there is something in the PR.
to repro: 
build ci_part1

**Comment by ncave** [comment]
@KevinRansom Tests had to be fixed.

**Comment by ncave** [comment]
@dotnet-bot test this please

**Comment by ncave** [comment]
@KevinRansom I think the error in the AppVeyor ci_part2 build is unrelated to this PR, because I see the same error in a lot of recent PRs:

`Error running command 'C:\projects\visualfsharp-3dtit\tests\..\release\net40\bin\fsiAnyCPU.exe' with args ' -r:System.Core.dll --nowarn:20 --define:INTERACTIVE --maxerrors:1 --abortonerror test.fsx' in directory 'C:\projects\visualfsharp-3dtit\tests\fsharp\core\members\incremental'. ERRORLEVEL -1073740771 ERRORLEVEL -1073740771`

**Comment by KevinRansom** [comment]
@ncave ... yep I agree.

Thank you for taking care of this

Kevin

**Pull request merged**
