### PR TITLE
Better error message for list/array init

### PR DESCRIPTION
**Pull request by forki**
for the following:

image

we now have:

image

/cc @isaacabraham

### CODE REVIEW

**Comment by 0x53A** [comment]
1) Does this also work with yield? ``[ yield 1 ; yield "2" ]``
2) Does this also work with seq?
image

**Comment by vasily-kirichenko** [comment]
Is "but here has type ..." a correct English?

**Comment by forki** [comment]
@0x53A no and no. but feel free to extend it.

@vasily-kirichenko /shrug

**Comment by KevinRansom** [comment]
@forki conflicts.

**Comment by KevinRansom** [comment]
@vasily-kirichenko yes, it could use a comma, but this layout has always irked me a bit.  I can't deny though that it is much easier to see the error when laid out this way.

**Comment by forki** [comment]
@KevinRansom added comma and rebased

**Comment by KevinRansom** [comment]
Thanks mate ....

Thanks  Steffen.

**Pull request merged**
