### PR TITLE
Remove weird recursive function

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
mmm tbf I don't know if this makes sense at all!?

**Comment by enricosada** [comment]
@forki ihmo seems the original idea (from hints like `rec go`, `SizeOfValueInfos` plural) was to find the max value inside array.
So maybe is a bug in original code. or just a lazy fix to make it work on first value only.

**Comment by forki** [comment]
yes that's what I thought. so I removed all that to make it very obvkous what we do right now. @KevinRansom or @dsyme can comment if it's a bug

**Comment by KevinRansom** [comment]
Looks fine to me.

**Comment by dsyme** [comment]
> @forki ihmo seems the original idea (from hints like rec go, SizeOfValueInfos plural) was to find the max value inside array. So maybe is a bug in original code. or just a lazy fix to make it work on first value only.

Yeah this was surely a bug in the original code

**Comment by forki** [comment]
Yes that's what I thought. My change was preserving the original
functionality and made it more obvious. So the bug is still there

Am 05.06.2017 16:24 schrieb "Don Syme" <notifications@github.com>:

**Pull request merged**
