### PR TITLE
Fix name-mangling of provided types

### PR DESCRIPTION
**Pull request by forki**
This is similar to #101 but also fixes the mangling of the type names.
It won't generate the trailing comma - see cf897f5

### CODE REVIEW

**Comment by latkin** [comment]
This seems like a good change to me. Main thing I'd be worried about is if there are any hidden dependencies elsewhere (other parts of the codebase, or exposed in previous versions) on the old mangled format.

**Comment by forki** [comment]
> other parts of the codebase

VFPT says it's the only place. It seems it's only used for TPs.

> exposed in previous versions
yep that's the reason I didn't put it in the first PR. 

But I think the use case was broken in older versions, so even compiled code wouldn't work. But since we fix both (mangle and demangle) maybe even older code might magicaly work now. Or not ;-)

**Comment by dsyme** [comment]
The change looks good, but why do you mention #101?

**Comment by forki** [comment]
I meant #102

**Comment by dsyme** [comment]
post-15706-1201114036

**Pull request closed without merging**
