### PR TITLE
try to reproduce async choice error revealed in #1378

### PR DESCRIPTION
**Pull request by forki**
/cc @eiriktsarpalis 
I run the sample A LOT and it seems to be failing

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
```
Failed : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Control.AsyncModule.Async.Choice repro
  Expected: less than or equal to 4
  But was:  5
at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Control.AsyncModule.Async.Choice repro() in C:\projects\visualfsharp-3dtit\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Control\AsyncModule.fs:line 438
```

**Comment by eiriktsarpalis** [comment]
@forki Could you try adding this?
```fsharp
ThreadPool.SetMinThreads(100,100)
```
http://stackoverflow.com/questions/17429246/preventing-thread-pool-starvation-with-a-timer-running-at-same-time-as-parallel

**Comment by forki** [comment]
@KevinRansom this is not compiling on coreclr!? but I have the code under 

    #if !(FSHARP_CORE_PORTABLE || FSHARP_CORE_NETCORE_PORTABLE)

any ideas why it's still in the coreclr build?

**Comment by forki** [comment]
Build timed out (after 120 minutes). Marking the build as aborted.

It looks like this actually fixed the test. So let me remove the brute-force test and keep the `ThreadPool.SetMinThreads(100,100)` for the property-based test. This should remove a bit of flakyness.

**Comment by forki** [comment]
ok I think this is ready to go in

**Pull request merged**
