### PR TITLE
remove comment

### PR DESCRIPTION
**Pull request by KevinRansom**
Remove a comment.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dsyme, lol, I have a bunch more tweaks to do, but I guess I will do another PR now :-)

**Comment by dsyme** [comment]
@KevinRansom The PR did what it said on the tin :)

**Comment by KevinRansom** [comment]
I know, i ain't that imaginative.

**Comment by realvictorprm** [comment]
So sorry 😅

**Pull request merged**
