### PR TITLE
[RFC FS-1050]  TryGetValue on map

### PR DESCRIPTION
**Pull request by dsyme**
Adds the TryGetValue method to `Map`.  

* RFC at https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1050-trygetvalue-map.md

### CODE REVIEW

**Comment by forki** [comment]
❤️

**Comment by forki** [comment]
I'm planning to send a pull request on top of this that replaces all compiler internal calls from TryFind to TryGetValue

**Comment by forki** [comment]
@dsyme can you please add Map.tryGetValue? The one on the map module?

**Comment by KevinRansom** [comment]
@dsyme Bugger, I meant to send you a PR, unfortunately it updated this one instead.

Anyway ... the goal of the last commit is to eliminate duplicated code, by using tryGetValue from tryFind and find.

Sorry about that.

Kevin

**Comment by forki** [comment]
It's now red

**Comment by KevinRansom** [comment]
@forki  Package issue with nuget. For instance, if the package is unable to be found 
Sigh!!!
@dotnet-bot Ubuntu16.04 Release_default Build

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default please

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default please

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Comment by forki** [comment]
@kevinransom there is no package issue. There is only an issue with your package manager client which does not retry.

**Comment by KevinRansom** [comment]
Targeting dev15.8

**Comment by dsyme** [comment]
> Anyway ... the goal of the last commit is to eliminate duplicated code, by using tryGetValue from tryFind and find.

It's not totally clear that doing it that way is faster, since it's passing 4 arguments instead of 3 down the recursive chain.

**Comment by KevinRansom** [comment]
@dsyme, I'm with you on whether it's faster, I have no real intuition about that.  I do think that having three copies of essentially identical code is a bit of a smell, and now we only have to optimize tryGetValue and it benefits all three.

**Comment by dsyme** [comment]
> @dsyme, I'm with you on whether it's faster, I have no real intuition about that. I do think that having three copies of essentially identical code is a bit of a smell, and now we only have to optimize tryGetValue and it benefits all three.

Yes, it's ok. I think Map.add is the one that is really performance sensitve (and we should likely solve that by adding a builder that adds multiple elements simultaneously)

**Comment by forki** [comment]
can we get this in please?

**Pull request merged**
