### PR TITLE
Target files change case

### PR DESCRIPTION
**Pull request by KevinRansom**
Somehow, over the years, Microsoft.FSharp.Targets became targets with a lower case t.  As did Microsoft.Portable.FSharp.targets.  This is not so great cross platform.  This change ensure that we consistently use .Targets for these legacy target files.

Kevin

### CODE REVIEW

**Comment by matthid** [comment]
Shouldn't we instead use lower case file-extensions everywhere?
Or is it `Targets.targets`?

**Comment by KevinRansom** [comment]
@matthid 

I wish ... :-)

It has been lower case in the repo as long as we have been open source.  So I expect it has been lower case in the internal repo forever as well.

The existing project templates spell it Microsoft.FSharp.Target.  and I know that people used them on Mono.  I believe the mono packaging must have copied them with an uppercase T.

@enricosada in his FSharp.Compiler.Tools package certainly re-cased them to Target.

In order to maintain compatibility with existing unix packagings we need to use T.  In order to have a saner and more consistence experience we should always use lower case t for targets.

Anyway to cut a short story shorter I went with compatibility with existing Linux projects, and decided to make sure we at least are consistent within the repo.

It's a wart but probably not that ugly.

There is an alternative and that would be to ship a shim with the Uppercase T that immediately delegates to the one with the lowercase T.  But I think that's just unnecessary confusion.

Kevin

**Comment by enricosada** [comment]
@matthid see https://github.com/fsharp/fsharp/issues/564 for more info.

**Comment by matthid** [comment]
@KevinRansom Thanks for the explanation, I agree with all you said :)

Yeah an ugly situation... @enricosada I don't get why we need to upper case them in the nuget package? I thought nuget/paket will handle that? (with upper case I'm not even sure if paket will accept that).

If we could change the casing in the NuGet package we would have a clear path forward without breaking anyone...

fsharp/fsharp#564 doesn't talk about the NuGet package.

**Comment by KevinRansom** [comment]
@matthid ... no @enricosada did the right thing.  The project files with a badly cased .Targets has to work and that is the real problem.

Code like this has been in the product since at least 2013
````
  <Choose>
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
      <PropertyGroup Condition=" '$(FSharpTargetsPath)' == '' AND Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets') ">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition=" '$(FSharpTargetsPath)' == '' AND Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets') ">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </Otherwise>
  </Choose>
````

And this is from the fs scaffold on GitHub: https://github.com/fsprojects/ProjectScaffold/blob/master/src/FSharp.ProjectTemplate/FSharp.ProjectTemplate.fsproj

````
  <Choose>
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </Otherwise>
  </Choose>
````

And they preexisted the compiler tools.  Enrico did, exactly what we are doing now.  If I had my way, case sensitive file systems would be outlawed.  But I am old and have used windows all of my working life, and so I am probably super biased about that :-)

Kevin

**Comment by dsyme** [comment]
@KevinRansom Hopefully this gets us to the right place :) 

Historically this has caused a world of pain for http://github.com/fsharp/fsharp and the Mono distribution.  TBH even attempting to change the case in github has had horrific effects, so I'm somewhat nervous of more pain from this downstream.....

**Pull request merged**
