### PR TITLE
Use Roslyn line numbers only in lexer cache

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@dotnet-bot please test this

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@vasily-kirichenko 
to repro
````
build vs vstest
````
I think these may be related to the change.


`````
Errors and Failures

1) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentHighlightsServiceTests.ShouldHighlightAllQualifiedSymbolReferences
  Expected is <Microsoft.VisualStudio.FSharp.Editor.FSharpHighlightSpan[2]>, actual is <Microsoft.VisualStudio.FSharp.Editor.FSharpHighlightSpan[0]>
  Values differ at index [0]
  Missing:  < <{IsDefinition = false;
 TextSpan = [21..29);}>, <{IsDefinition = false;
 TextSpan = [54..62);}> >
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentHighlightsServiceTests.ShouldHighlightAllQualifiedSymbolReferences() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentHighlightsServiceTests.fs:line 93

2) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentHighlightsServiceTests.ShouldHighlightAllSimpleLocalSymbolReferences
  Expected is <Microsoft.VisualStudio.FSharp.Editor.FSharpHighlightSpan[2]>, actual is <Microsoft.VisualStudio.FSharp.Editor.FSharpHighlightSpan[0]>
  Values differ at index [0]
  Missing:  < <{IsDefinition = true;
 TextSpan = [10..13);}>, <{IsDefinition = false;
 TextSpan = [47..50);}> >
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.DocumentHighlightsServiceTests.ShouldHighlightAllSimpleLocalSymbolReferences() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\DocumentHighlightsServiceTests.fs:line 75

3) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.GoToDefinitionServiceTests.VerifyDefinition
Incorrect information returned for fileContents=<<<
type TestType() =
    member this.Member1(par1: int) =
        printf "%d" par1
    member this.Member2(par2: string) =
        printf "%s" par2

[<EntryPoint>]
let main argv =
    let obj = TestType()
    obj.Member1(5)
    obj.Member2("test")>>>, caretMarker=<<<printf "%d" par1>>>, expected =<<<Some (3, 3, 24, 28)>>>, actual = <<<<null>>>>
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.GoToDefinitionServiceTests.VerifyDefinition() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\GoToDefinitionServiceTests.fs:line 107

4) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.QuickInfoProviderTests.ShouldShowQuickInfoAtCorrectPositions
  Expected: <Some(val x : int
Full name: Test.x)>
  But was:  null
at Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.QuickInfoProviderTests.ShouldShowQuickInfoAtCorrectPositions() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\QuickInfoProviderTests.fs:line 104
````

**Comment by vasily-kirichenko** [comment]
Fixed.

**Comment by forki** [comment]
CI error is unrelated. Please merge asap

**Comment by KevinRansom** [comment]
@vasily-kirichenko, would you resolve the conflicts please.

Kevin

**Comment by vasily-kirichenko** [comment]
this code was merged to https://github.com/Microsoft/visualfsharp/pull/2102 and further refactored to Lexer class, so merging this PR would create conflicts and it's needed anymore anyway.

**Comment by forki** [comment]
So the crash on last line is gone?

Am 28.12.2016 1:55 nachm. schrieb "Vasily Kirichenko" <
notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
@forki Yes.

**Comment by vasily-kirichenko** [comment]
I'm reopening this as I closed https://github.com/Microsoft/visualfsharp/pull/2102, which included "out of range" bug fix merged from this PR.

**Pull request merged**
