### PR TITLE
show inherited interfaces in tooltips

### PR DESCRIPTION
**Pull request by cloudRoutine**
fixes https://github.com/Microsoft/visualfsharp/issues/2646

**Before**

**After**

### CODE REVIEW

**Comment by saul** [comment]
Does this produce a valid fsi file? I think I'm right in saying that this same code is used to generate signature files by the compiler.

**Comment by dsyme** [comment]
@saul @cloudRoutine Looking at the code fix it only applies to .NET (IL) type definitions, not to F# type definitions.  I'm not sure how this relates to the screen shot above though which are for F# type definitions - I think those are already shown?

@cloudRoutine I'm pretty sure you will want to avoid showing implemented interfaces if the interface type is internal to an assembly and is inaccessible from the point of use.  Some of the WinForms types are good examples of this IIRC.  

Really, the NicePrint code should should not differ for "IL" and "F#" types, but instead should be written in a neutral way over any TyconRef.  This would make many things more orthogonal.

@saul Re signature files - as the fix is only for .NET (IL) type definitions we don't generate signature files for this.

**Comment by cloudRoutine** [comment]
@dsyme you're right that already worked for F# types, I should have posted 

**Before**


**After**


But the cases I'm most interested in are ones like 







Where the inherited interfaces are used to classify the service as this will be helpful while working on VFT

**Comment by KevinRansom** [comment]
thank you for this change.

Kevin

**Pull request merged**
