### PR TITLE
[ F# 4.2 ] Type extensions should not need generic type constraints

### LINKED ISSUE #1635: Type extensions should not need generic type constraints, or throw a more descriptive FS0957
If you extend a type that has a generic type constraint on one or more of its generic type parameters, you will receive a (not very helpful) error message, like:

> FS0957: The declared type parameters for this type extension do not match the declared type parameters on the original type 'Map<\_,\_>'
### Repro steps

A simple example of getting this error is:

```
// seems valid enough (here extending the F# Map type)
type Map<'U, 'V> with
    static member merge map1 map2 = Map.fold (fun acc key value -> Map.add key value acc) map1 map2
```
### Expected behavior

I don't think this error should be raised, the constraints can be inferred from the original type and it is impossible to have two type names with the same generic type parameters, but different constraints.

If the error _must_ be raised, I suggest a different, or improved error message, something like:

> FS0957: One or more of the declared type parameters for this type extension have a missing or wrong type constraint not matching the original type constraints on 'Map<\_,\_>'
### Actual behavior

An error is raised as mentioned above.
### Known workarounds

Add the type constraint is the only logical workaround, but I think it oughtn't be necessary. With more complex type constraints (like member constraints) this can even be a real pain to get right.
### Related information

Tested and seen with VS2015, Update 3, F# 4.0.

### PR DESCRIPTION
**Pull request by forki**
fixes #1635

### CODE REVIEW

**Comment by forki** [comment]
There was already a test which checked exactly this. I relaxed that test

**Comment by forki** [comment]
ready for review

**Comment by dsyme** [comment]
@forki Yeah, I'm not sure we want this. Perhaps, but we need to be sure. I think we should not push a change for this into F# 4.1 but rather wait and sort it out after the dust settles.

**Comment by forki** [comment]
yes definetly a 4.2 thing

**Comment by forki** [comment]
4.1 is done so I think this is now ready to go in

**Comment by forki** [comment]
Ping

**Comment by KevinRansom** [comment]
@forki @dsyme 

We currently have no plans to  rev the FSharp.Core version for the VS2017.3 release.  Possibly we will do that before the end of the year, we have a number of changes backed up, that need to get in a new release with a version number change.  And the next FSharp.Core version number will likely be 4.3 due to the FSharp.Core.nuget version taking 4.2.*.

Kevin

**Comment by forki** [comment]
@KevinRansom @dsyme this is a compiler change. Does it really need a new FSharp.Core? I thought we delayed it in order to not introduce possible bugs in 4.1 where we didn't have time to fix it again.

**Comment by dsyme** [comment]
@forki No, it doesn't need a new FSharp.Core.  But it's a language update.  i think it's ok to leave it in the pipeline for a bit

**Comment by KevinRansom** [comment]
I hope to make the release after the next one a language and library change.  TBH I had hoped to make this release one, but there wasn't much traction.

Anyway thanks for this, I want to Jam it in, but we have to wait a short while longer.

Kevin

**Comment by dsyme** [comment]
@forki I took a look at #3248 and I think the best thing or now is to just give a better error message.  If we don't enforce the constraints, the type parameters won't get the right constraints.

We could change approach to infer the constraints.  But in the future, we might decide to support constrained extensions (which you can do with C#-style extension methods), e.g. 

```
type List<int> with 
    ...
```

In that case you can't infer...  And there are thing half way in between like
```
type Dictionary<'T,int> with 
    ...
```

**Comment by dsyme** [comment]
@forki So I'll close this PR in favour of the other - thx :)

**Pull request closed without merging**
