### PR TITLE
Fix type providers on VS2017 RC

### LINKED ISSUE #1758: Type Providers are broken in the editor, even though they will execute just fine.
1. Install VS 2017 RC1 Community on a clean machine.
2. Install .NET Desktop workload.
3. Install the FSharp.Data package.
4. Enter the following code in the editor:

```fsharp
open FSharp.Data

type JsonContext = JsonProvider<""" { "name":"John", "age":94 } """>

let json = JsonContext.Parse(""" { "name":"John", "age":94 } """)

[<EntryPoint>]
let main argv = 
    printfn "Age: %d.  Name: %s" json.Age json.Name
    printfn "%A" argv
    0 // return an integer exit code

```

Expected: No red squiggles and IntelliSense when "dotting" into `json`.

Actual:

tp-appears-broken

### PR DESCRIPTION
**Pull request by dsyme**
Work in progress to fix #1758 where type providers are broken in Visual Studio 2017

I'm testing with FSharp.Data current release.  Currently working through a number of issues

### CODE REVIEW

**Comment by dsyme** [comment]
And fixed!  At least for FSharp.Data in  a script

capture3

FSharp.Data and the type provider starter pack uses a bunch of odd things to get some things to work, I'll put them under test to make sure we don't break them in the future.

**Comment by dsyme** [comment]
And fixed for the case reported in the bug:

capture4

**Comment by dsyme** [comment]
This is ready to go in apart from needing some extra testing to pin down this in the future

**Comment by cartermp** [comment]
Awesome

**Comment by dsyme** [comment]
Since this fixes the problems I'm going to merge this.  Some testing is included in the PR. There is one more test I want to add, I'll do that separately tomorrow.

**Pull request merged**
