### PR TITLE
¯\_(ツ)_/¯

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
Lol it's needed

**Comment by smoothdeveloper** [comment]
RIP, I think you removed the historical first line of the implementation of that function, when measures emerged.

**Comment by forki** [comment]
@smoothdeveloper @cartermp the issue is there is code under compiler directive that uses g - so it's only ued for soem compile runs. Other runs would flag it as "Unused parameter" and let the build fail. This is a clever trick to make sure it's "used" all the times.

**Comment by smoothdeveloper** [comment]
mmh I see EXTENSIONTYPING, let's keep `g` but we can move ignore g in the `#else` or just leave a comment for saving next one to try to remove it :)

**Comment by forki** [comment]
Ok tried to make situation more clear

**Comment by smoothdeveloper** [comment]
@forki you should also thank @dotnet-bot for helping you getting the code right :)

**Comment by KevinRansom** [comment]
@smoothdeveloper We all owe dotnet bot gratitude for that.  @dotnet-bot is one hard working engineer.

**Pull request merged**
