### PR TITLE
Move the legacy language service to the "vsintegration/tests" folder

### PR DESCRIPTION
**Pull request by dsyme**
AFAIU the legacy language service is now only used for testing - rename it and put it out of the way

cc @cartermp

### CODE REVIEW

**Comment by dsyme** [comment]
@cartermp Actually, there seem to be still dangling references around, I'm closing this until they are removed

**Comment by cartermp** [comment]
@dsyme which references? I know that the legacy language service project depends on a few projects in `vsintegration/`, but I don't recall other `vsintegration/` projects which depend on this still

**Comment by dsyme** [comment]
@cartermp These

* https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/FSharp.Editor.fsproj#L99
* https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.ProjectSystem.FSharp/ProjectSystem.fsproj#L48
* https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/Vsix/VisualFSharpFull/VisualFSharpFull.csproj#L90
* https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/Vsix/VisualFSharpFull/VisualFSharpFull.csproj#L100

**Comment by cartermp** [comment]
Ah, that's for the LanguageService.Base project. We can't kill our dependency on that for FSharp.Editor until #4116. For that, we'll need to update our VSSDK dependencies to 15.6. It's a tedious and error-prone process but I can probably give it a go at some point

**Comment by dsyme** [comment]
@cartermp OK, I see.  

Could you remove FSharp.LanguageService.dll from the setup please? That should just be removing this line:
* https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/Vsix/VisualFSharpFull/VisualFSharpFull.csproj#L100

**Pull request closed without merging**
