### PR TITLE
Port NUnit based tests to Core CLR

### PR DESCRIPTION
**Pull request by PatrickMcDonald**
PR for #690 

This version keeps NUnit 3.0 as the test framework.

The Core CLR version of FSharp.Core.Unittests now compiles to an exe, and uses NUnitLite as the test runner.

Alternative to #699, which uses xUnit.net

### CODE REVIEW

**Comment by KevinRansom** [comment]
This is really nice!!!!

**Comment by KevinRansom** [comment]
Yesterday @PatrickMcDonald I updated all of the project jsons to use the latest RC2 version of the .Net framework.  That may!!!! explain the failures.

Kevin

**Comment by enricosada** [comment]
great job @PatrickMcDonald !!

**Comment by KevinRansom** [comment]
@PatrickMcDonald, @enricosada --- hey guys, I love this PR, the changes look great, although I expect you have both stomped over similar sets of files.  What additional work is needed before I pull this.  Or should I just pull it and fixup the issues?

Kevin

**Comment by enricosada** [comment]
I'll update my pr if you pull this one.
This pr is really good, if this doesnt build and you want to pull in, i'll check this weekend and fix issues. 
Is nice yo have nunit runner working in coreclr, i can use that for fsharp suite

**Comment by PatrickMcDonald** [comment]
There's just the 2 tests failing, both due to Reflection errors I think, but I'm not sure how to fix them.. Upgrading to Core CLR RC2 did not fix.  The choices are to fix or ignore the tests or leave them failing. I'd welcome guidance on how to proceed!

**Comment by enricosada** [comment]
I think you can disable the failing tests and open an issue with details about failure.
For example there are some failing tests with  `NO_CI` tags. 
So pr can be merged and we can fix later.

**Comment by KevinRansom** [comment]
Okay I am going to try to bring these into the coreclr branch ....
wish me luck :-)

**Comment by PatrickMcDonald** [comment]
hehe, good luck!

**Comment by KevinRansom** [comment]
Thank you so much for this, its awesome.

**Comment by enricosada** [comment]
:+1: great!

**Comment by dsyme** [comment]
fab

**Pull request merged**
