### PR TITLE
Fix enum/union cases not having the correct container type

### LINKED ISSUE #2719: Fields are not shown as being part of their encapsulating type in 'Go to'
image

I'm expecting the red boxed "namespace Library1" to read "type MyRecord".

P.S. apologies for the influx of reports - I spend my day using the F# nightlies at work and take note of all the issues I'm finding.

### PR DESCRIPTION
**Pull request by saul**
Fixes #2719 

image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
BTW, do you have an idea why "details" bottom pane does not show for F# symbols?

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by saul** [comment]
Any chance we could get this merged before the nightly now that the tests are green? 

Also @vasily-kirichenko the details panel does work for me :o

**Comment by KevinRansom** [comment]
Thanks for this.

**Comment by saul** [comment]
Thanks @kevinransom. Do you also have any idea why there wasn't a nightly build yesterday?

**Comment by cartermp** [comment]
@saul Hard to say.  It's an automatic process, so something likely didn't make it past validation.  @KevinRansom was saying that there were some issues with our CI that he was looking into.

**Pull request merged**
