### PR TITLE
Fix 12 and 84 - stepping for array and list loops

### PR DESCRIPTION
**Pull request by dsyme**
This fixes our two oldest "Fix Soon" bugs - poor debug stepping for loops over arrays

    https://github.com/Microsoft/visualfsharp/issues/12
    https://github.com/Microsoft/visualfsharp/issues/84 

animation

### CODE REVIEW

**Comment by dsyme** [comment]
@otawfik-ms @KevinRansom Any idea why Jenkins build/tests are not showing?

**Comment by otawfik-ms** [comment]
I can see it here:
http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part1_windows_nt_prtest/706/
@mmitche  Any idea why it is not showing in GitHub?

**Comment by dsyme** [comment]
Close/reopen triggered them

**Comment by KevinRansom** [comment]
D:\j\workspace\release_ci_pa---3f142ccc\tests\fsharpqa\Source\Optimizations\GenericComparison>..\..\..\testenv\bin\ILComparer.exe "Hash03.il.netfx4.bsl" "Hash03.il" 

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'D:\j\workspace\release_ci_pa---3f142ccc\tests\fsharpqa\Source\Optimizations\GenericComparison\Hash03.il.netfx4.bsl'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Program.File2List@10(String filename) in D:\j\workspace\release_ci_pa---3f142ccc\tests\fsharpqa\testenv\src\ILComparer\Program.fs:line 11
   at Program.main(String[] argv) in D:\j\workspace\release_ci_pa---3f142ccc\tests\fsharpqa\testenv\src\ILComparer\Program.fs:line 19

D:\j\workspace\release_ci_pa---3f142ccc\tests\fsharpqa\Source\Optimizations\GenericComparison>exit /b -532462766 
Fail to execute the POSTCMD. FAIL

**Comment by dsyme** [comment]
Seems like there's some problem running coreclr tests: 
```
D:\j\workspace\release_ci_pa---866fd2c3\tests\..\release\net40\bin
"D:\j\workspace\release_ci_pa---866fd2c3\tests\..\release\net40\bin\Fsi.exe" --exec --nologo "D:\j\workspace\release_ci_pa---866fd2c3\tests\Convert-NUnit2Args-to-NUnit3Where.fsx" -- "" "NOOPEN,Expensive"
""D:\j\workspace\release_ci_pa---866fd2c3\tests\testbin\release\coreclr\win7-x64"\corerun.exe" "D:\j\workspace\release_ci_pa---866fd2c3\tests\testbin\release\coreclr\fsharp.core.unittests\FSharp.Core.Unittests.exe"
'""D:\j\workspace\release_ci_pa---866fd2c3\tests\testbin\release\coreclr\win7-x64"\corerun.exe"' is not recognized as an internal or external command,
operable program or batch file.
Saved errorlevel 9009
The system cannot find the file specified.
Error: 'RunTests.cmd release coreunitcoreclr ' failed 
Build step 'Execute Windows batch command' marked build as failure
```

**Comment by forki** [comment]
jenkins builds are really flaky right now. They don't trigger on every push.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
AppVeyor gave this error: ``FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Control.AsyncModule.OnCancel.RaceBetweenCancellationHandlerAndDisposingHandlerRegistration``

When a test aimed at testing a race condition fails we should probably take note.   But it may also have been because Appveyor was running on a slow machine and a timeout in the test was reached

**Pull request merged**
