### PR TITLE
package automagic, spelling error and fsharp.core reference bug.

### PR DESCRIPTION
**Pull request by KevinRansom**
Spelling error for DisableImplicitSystemValueTupleReference and not using DisableImplicitFSharpCoreReference

### CODE REVIEW

**Comment by KevinRansom** [comment]
@mmitche Do you know why the ci didn't fire for this PR?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@KevinRansom We hit our rate limits....it should appear periodically

**Comment by KevinRansom** [comment]
@mmitche thanks

**Pull request merged**
