### PR TITLE
Rename nocopyfsharpcore to copyfsharpcore, implement copyreferences

### PR DESCRIPTION
**Pull request by dsyme**
There may be future scenarios where we will want to explicitly enable copyfsharpcore, for example cases where it is off because of some other condition, but we want to explicitly turn it on.  So to future proof things lets call the flag ``--copyfsharpcore`` and you turn it off by using ``--copyfsharpcore-``.

(Note I suspect copyfsharpcore should be off by default for compilations from MSBuild using the Fsc task, since it is subverting the ``CopyLocal`` settting coming from the FSPROJ fie)

Likewise, there are scenarios where it is useful to copy other (non-system) references to the output directory.  In particular, this is useful for scripting where you compile a script and want all its resolved ``#r`` dependencies to go with the script. 

So this implements a ``--copyreferences`` flag that is off by default.

I also adjusted both pieces of code to work with finalized assembly resolutions, rather than assembly references

### CODE REVIEW

**Comment by dsyme** [comment]
Note it's possible that we will decide to take only the first part of this (the flag renaming).  There are open questions about the second part, e.g.

* are PDBs and XMLs copied
* is it possible for a ``#r`` reference to specify "do not copy local"

We could still accpet the PR for the feature as is and resolve these issues later.

A previous PR [deleted some MSBuild resolution logic](https://github.com/Microsoft/visualfsharp/pull/1593/files#diff-5053496cd629aa2c714ad874f52f3d56L407) which can be used to determine things like "what PDBs should we copy", which I why I'm mentioning this.

**Comment by KevinRansom** [comment]
Can we hold fire on this ... in the coreclr world there may be different implementations per platform, there may be reference and implementation assemblies.  This really satisfies only the current windows scenario.  We kind of need a publish mechanic ... dotnet.exe might be the mechanic or perhaps the model.

Kevin

**Comment by dsyme** [comment]
Yes sure, fair point. I'll strip out the part that is the flag rename and submit it separately

**Comment by dsyme** [comment]
I suspect we should pass copyfsharpcore- from Fsc task, agreed?

**Comment by KevinRansom** [comment]
I need to update the build task with a bunch of new flags anyway.  So I will take care of that.

**Comment by KevinRansom** [comment]
I don't think we want the compiler to have /copyreferences until we figure out an approach.  
/nocopyfsharpcore was added to give msbuild a way to disable fsharpcore copy by the compiler.
renaming the switch is fine, the build task will not set it.  The targets file should set it the build task can have an option to set it for the build task.

**Comment by dsyme** [comment]
> I don't think we want the compiler to have /copyreferences until we figure out an approach.

Agreed

> /nocopyfsharpcore was added to give msbuild a way to disable fsharpcore copy by the compiler.
renaming the switch is fine, the build task will not set it. The targets file should set it the build task can have an option to set it for the build task.

Agreed.  Only think I request is that the flag be renamed to ``/copyfsharpcore``.  The flag would remain on by default, The Fsc task would pass ``/copyfsharpcore-``.  It's just a syntax thing.

**Comment by dsyme** [comment]
I'll close this and we can do the flag rename separately

**Pull request closed without merging**
