### PR TITLE
Improve error reporting: property setter in constructor expression

### LINKED ISSUE #1112: Improve error reporting: property setter in constructor expression
## What

Sometimes, user wants to assign properties in a constructor expression:

````fsharp
type MyClass() =
    member val MyProperty = "" with get, set

let c = MyClass(Property = "")
```

gives:

`The member or object constructor 'MyClass' has no argument or settable return property 'Property'. The required signature is new : unit -> MyClass.`

## Why

Given the compiler has exact information about `MyClass`, it could yield more information about what is possible to do in context of constructor expression.

## How

 `The member or object constructor 'MyClass' has no argument or settable return property 'Property', did you mean to assign 'MyProperty' or (*) instead. The required signature is new : unit -> MyClass.`

(*) list X other properties (see discussion) that aren't already listed in the constructor expression in decreasing order of likeliness.

#1103

### PR DESCRIPTION
**Pull request by forki**
fixes #1112

image

### CODE REVIEW

**Comment by forki** [comment]
I think this one is ready for review.

**Comment by KevinRansom** [comment]
Looks, good, probably the message needs tweaking though:

The object constructor 'MyClass' has no argument or settable property named 'Property'.  The required 
signature is new : unit -> MyClass.
Consider:
    MyProperty
    MyProperty2
    ABigProperty

**Comment by isaacabraham** [comment]
I thought we were dropping ' for types?

Kevin- do we really need "object constructor" or can "constructor" suffice?

**Comment by forki** [comment]
@KevinRansom the "maybe you want part" is from the little helper that we brought in for "elm like" suggestions. We should change it to something that works everywhere. I agree the text should start with "Consider" since that is what we did for other messages as well.

**Comment by cartermp** [comment]
@isaacabraham 

> I thought we were dropping ' for types?

I'm wasn't aware of this.  In that case, would we then want to update other PRs to not longer use ' for types, such as #1219 and #1229?  I'm fine with any approach so long as it's consistent.

**Comment by forki** [comment]
I think we didn't really come to a conclusion about wrapping types in ',
yet.  But since generic types ''a' look weird there is room to improve
that.

**Comment by isaacabraham** [comment]
Sorry - wasn't my intention to come across so strong there :) Agree 100% consistency - thought ppl had agreed upon no quotes but I guess I wasn't correct there :)

**Comment by isaacabraham** [comment]
One thing I wish we had done before we started this is define the style of error messages we wanted, like slightly refined from what we have now or the whole shebang like Elm.

**Comment by KevinRansom** [comment]
@isaacabraham I'm okay with us iterating towards the best style.  Already we understand a lot more about these messages than we did at the start.  The bug fixes are easy to implement, try out and discuss.  I think we are now in a much better state than we were and the more bugs we look at the better our understanding.

Right now we quote replaceable types in messages.  We could change that, it is however, a painful experience, given the various different types of tests we have.

**Comment by forki** [comment]
rebased

**Comment by dsyme** [comment]
Merged on behalf of @KevinRansom who is heads-down in tuples, and @otawfik-ms who is heads down in Roslyn Workspaces :)

Thanks for the great contribution @forki, and for @isaacabraham too for kicking off this error message initiative

**Pull request merged**
