### PR TITLE
Fix editor support for backticked symbols

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by forki** [comment]
03:43:50 (8,20-8,22): error FS0001: The type 'int ( [] )' is not compatible with the type 'System.IDisposable'

    03:43:50 *** The following necessary lines were never matched:
    03:43:50 ***	\(8,20-8,22\):.+error FS0001:.+The type 'int \[\]' is not compatible with the type 'System\.IDisposable'$

Looks that the reported errors are now a bit weird

**Comment by vasily-kirichenko** [comment]
@forki fixed

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@vasily-kirichenko ci_part1 and ci_part2 issues.

**Comment by vasily-kirichenko** [comment]
I forget what it fixes. Closing it.

**Pull request closed without merging**
