### PR TITLE
[WIP] Add simple snippet support for VS

### PR DESCRIPTION
**Pull request by brettfo**
### What's included in this PR:
- Snippet's can be inserted with `Edit -> Insert Snippet`, the `Ctrl+K, Ctrl+X` keyboard shortcut, or the `Edit.InsertSnippet` DTE command.
- The snippets are packed inside the VSIX to enable F5 testing on developer boxes.
### Shortcomings of these changes and the next steps:
- Only one snippet is included for the `match` expression.  This was added to lay the groundwork for others to add many more snippets with relatively few changes.  E.g., to add a new snippet, simply add a `.snippet` XML file next to `match.snippet` and update `FSharpSnippets.targets` and `snippets.swr`.
- Multi-line snippets aren't properly formatted/indented.  The fix for this is to (1) enable the `Preferences.EnableFormatSelection` option, and (2) implement [`ReformatSpan()`](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.LanguageService.Base/Source.cs#L622).
- No tests were added.

Addresses #1498.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
If localization is not intended in this PR, then I suggest adding it as an unlocalized component outside of the setup\* authoring, and only include it in the vsix (vsintegration/vsix) projects. This will make sure:

* it gets installed with the core VSIX.
* it is available for F5 debugging on developer boxes
* it is not dependent on setup, since it will never be involved in swix packages/localization workflow.

Hooking it up to the locale/LCID format/paths is not necessary as it will cause problems when integrating this with localized builds.

**Comment by KevinRansom** [comment]
@dotnet-bot please test this

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by brettfo** [comment]
@OmarTawfik: I've removed the locale-specific stuff in the latest commit.

**Comment by dsyme** [comment]
@brettfo Can we resurrect this or should we ditch it? Thanks!

**Comment by brettfo** [comment]
I'd like to bring this back eventually; I've just been busy with setup related work, recently.

**Comment by dsyme** [comment]
@brettfo Super, thanks

**Comment by KevinRansom** [comment]
@brettfo,
Closing for now ... please reopen when you get time to get back to it.

Thanks

Kevin

**Comment by xperiandri** [comment]
@brettfo, any updates?

**Comment by brettfo** [comment]
This fell off my list when I was originally working on it because other stuff came up, but I was thinking about this just the other day.  I plan on getting back to it as soon as my current work item is done, ETA a week or two.

**Comment by realvictorprm** [comment]
YAY! thank you @brettfo

**Comment by xperiandri** [comment]
We pray for you 😉😄
Have a productive week

**Pull request closed without merging**
