### PR TITLE
Fix QuickInfo problems related to resource loading (#4695)

### LINKED ISSUE #4695: Types/names not visible in tooltip in latest nightly
Using the latest nightly (15.6.20180406.3), types/names are frequently not visible in mouseover tooltips (it seems to work occasionally, but mostly not).

image

image

image

This one seems to work fine:

image

### PR DESCRIPTION
**Pull request by majocha**
This fixes #4695.

Dynamically loading XAML resources in a Visual Studio extension was a bad idea. Experimental  instance and nightlies loaded from wrong/old assembly. It worked for quite some time but broke each time the assembly content differed from the released version. 
Should be fixed for good from now on.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot Ubuntu16.04 Release_default Build please

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build

**Comment by KevinRansom** [comment]
Thank you

**Comment by brettfo** [comment]
Thanks for the fix!  I've manually queued another build of our nightly VSIX package to hopefully unblock people a little sooner so they don't have to wait until tomorrow.  ETA is 90 minutes after this message was posted.

**Pull request merged**
