### PR TITLE
Update mono props: support OSX and more .NET Framework versions

### PR DESCRIPTION
**Pull request by baronfel**
A potential solve for #6180 that uses msbuild built-ins to determine the target OS and pivots off of that to set the FrameworkPathOverride.  I included a `MonoRoot` property to allow for easy integration into the build process that fsharp/fsharp uses, which allows for a 'floating' mono root.

Testing this locally on my OSX laptop seems to have the intended effect: for all TFMs below I can pivot to the correct -api folders, and supplying a `MonoRoot` via MSBuild parameter influences the search paths as expected.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@brettfo, can you run your eyes over this pls

Thanks

Kevin

**Comment by brettfo** [comment]
If we add this I'd like a test leg to ensure it continues to work.  I'm not positive, but I think the Linux VMs for our CI server have mono installed.

Can you add the following to [`.vsts-pr.yaml`](https://github.com/Microsoft/visualfsharp/blob/master/.vsts-pr.yaml):

``` diff
 jobs:
 - job: Linux
   pool:
     vmImage: ubuntu-16.04
   timeoutInMinutes: 90
   strategy:
     maxParallel: 2
     matrix:
       dotnet_sdk:
         _command: make
         _args: Configuration=release
+      mono:
+        _command: xbuild # or `mono` or however you invoke this
+        _args: fsharp.proj # this might contain too many projects to work on mono
-      # disabled until it can be properly fixed
       release_fcs:
         _command: ./fcs/build.sh
         _args: Build
 steps:
 ...
```

**Comment by baronfel** [comment]
It'd be good to add a `dotnet build` for a net4X-targeting project, I can add that straightaway.  Is there such a thing as an MacOS runner for VSTS? That's the other part of the change that's added here.

**Comment by cartermp** [comment]
There should be a hosted macOS (the CLI uses one) but I'm not sure how to hook it up

**Comment by baronfel** [comment]
Ok, I found the vm identifier for the macOS runner on VSTS, I've added a matching set of jobs for that OS, and added a job that does a .net-framework build of some part of the repository at all to verify the FrameworkPathOverride changes (as well as fighting with case-sensitivity at least 10 times). Now to just iterate on that to get the build green.

**Comment by baronfel** [comment]
Actually, per @KevinRansom's comments on another thread, I think I'll remove the 'build-netframework-anything' job for now because it's going to require additional work and may conflict with upcoming build system changes that @brettfo has. So given that, I think adding the macOS runner and having it run the same jobs as the linux runner is an acceptable next step for this.

**Comment by baronfel** [comment]
The failed build was a nuget download error on linux. What do?

**Comment by cartermp** [comment]
This!

**Comment by baronfel** [comment]
I don't know what this single test failure is on the windows FCS tests, and it hasn't failed before. This is mildly irritating.

**Comment by cartermp** [comment]
The FCS tests are very flaky, so sometimes it just takes a while 😕

**Comment by baronfel** [comment]
Glory be, they are green!

**Comment by KevinRansom** [comment]
@baronfel,

Thanks for this

Kevin

**Pull request merged**
