### PR TITLE
Test revert of #4173 

### PR DESCRIPTION
**Pull request by dsyme**
It is possible that we should revert #4173 until we understand the issues better and to ensure stability between F# 4.1 and its update releases.

See customer-reported issue https://github.com/Microsoft/visualfsharp/issues/4343

This is trialling a revert of combined commit f9893b6ad7c90aea37fe25e721840f8ea2033075.

### CODE REVIEW

**Comment by dsyme** [comment]
@brettfo Close this since we have #4348 ?  I assume you integrate dev15.6 --> master?

**Comment by dsyme** [comment]
@brettfo Is it OK if we apply this to the master branch too?  I just want the core compiler logic to be in sync, so we can integrate it to Mono etc. (Mono release repo http://github.com/fsharp/fsharp is formed by integrating "master" branch here)

**Comment by brettfo** [comment]
Yes we plan on merging `dev15.6` back into `master`, but it might be a few weeks so having this separate PR is probably a good idea.

**Comment by dsyme** [comment]
@brettfo Thanks. Merging since it was green before I opened it

**Pull request merged**
