### PR TITLE
Fix build errors not being shown in the Error List

### LINKED ISSUE #2548: F# compile errors appear as "IntelliSense", not as "Build", in Error List pane of VS 2017
In order to see F# compiler errors, I have to select "Build + IntelliSense" in the Error List pane of VS 2017.

Why isn't output from the F# compilation for the build visible when only "Build" is selected in the Error List pane?

When compilation is finished, there are lots and lots of errors in the Error List pane, coming from IntelliSense. There are also error squiggles in the source, from IntelliSense. This in spite of the Output pane reporting a successful build with no errors.

#### Repro steps

Compile a simple F# test project in VS 2017. Toggle the setting between "Build" and "Build + IntelliSense" in the Error List pane, and watch what happens while editing and compiling with and without errors in the source.

#### Expected behavior

Errors from the F# compiler should be visible in the Error List pane when "Build" is selected.

F# IntelliSense shouldn't flood the Error List pane with all sorts of normal compiler errors.

#### Actual behavior

Errors relating to F# is only visible when "Build + IntelliSense" is selected in the Error List pane, and the pane behaves in a way that indicates that IntelliSense is at work, independently from the build compilation. 

F# compilation can report a successful build in the Output pane, while there are errors listed by IntelliSense in the Error List pane.

F# compilation can report errors in the Output pane, while the Error Pane lists 0 errors for the entire solution.

#### Known workarounds

No known workaround that makes it practical for me to work continuously in VS 2017 with a large solution with a mix of C# and F# projects. Have to rely on VS 2015 as backup until this is solved.

#### Related information 

Provide any related information 

F# 4.0 (4.4.0.0)

* Operating system : Windows 10
* .NET Runtime, CoreCLR or Mono Version : .NET Framework 4.5.2
* Editing Tools (e.g. Visual Studio Version) : VS 2017 first release

### PR DESCRIPTION
**Pull request by saul**
Fixes #2548

This was happening because we were trying to get IOleComponentManager too eagerly. I think something must have changed in the ordering of MEF services in VS 2017 as at project package instantiation (before Initialize is called), the service is null.

This change makes the lookup of IOleComponentManager lazy, and I've added an assertion to make sure this is caught in future instead of being silently swallowed.

I've also made some steps towards making the errors that IntelliSense returns and the errors that VS build returns be exactly the same. For example, ensuring that we're consistent in our line endings for multi-line error/warning messages.

Unfortunately this still hasn't triggered Roslyn to merge our IntelliSense and Build Errors, even when they're exactly the same error. See the screenshot below. I will ping @heejaechang when he is back in the office next week as supposedly he is more familiar with the de-duplication logic in the Error List.

image

### CODE REVIEW

**Comment by cartermp** [comment]
@KevinRansom since Heejae is OOF, is there someone else who may be able to unblock @saul  here?

**Comment by saul** [comment]
@cartermp don't block this PR on the errors being de-duplicated - I'm pretty sure this is now on parity with VS 2015. I'll open a separate issue for getting them de-duplicated.

**Comment by KevinRansom** [comment]
````
  D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\CompileOps.fs(1428,5): error FS0034: Module 'Microsoft.FSharp.Compiler.CompileOps' 

contains
    val internal OutputPhasedDiagnostic<'a> : errorStyle:'a -> os:StringBuilder -> err:PhasedDiagnostic -> flattenErrors:bool -> unit

but its signature specifies
    val internal OutputPhasedDiagnostic : ErrorStyle -> StringBuilder -> PhasedDiagnostic -> isError:bool -> unit

The respective type parameter counts differ 

[D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\FSharp.Compiler-proto\FSharp.Compiler-proto.fsproj]

````

**Comment by saul** [comment]
Thanks @KevinRansom - I've pushed a potential fix. However I'm struggling to get builds working locally at the minute. I keep getting:

> FSC : error FS0193: The module/namespace 'Microsoft.FSharp.Core' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'string' [C:\Code\visualfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]

Does this look familiar?

**Comment by dsyme** [comment]
> @cartermp don't block this PR on the errors being de-duplicated - I'm pretty sure this is now on parity with VS 2015. 

I do know that VS2010-2015 all did de-duplication - they called it "Error List Unification" or something.  I wasn't involved in the implementation. 

But I don't know anything about how to achieve this with Roslyn.

cheers!

**Comment by cartermp** [comment]
Calling @vladima as a shot in the dark to see if someone knows 😄

**Comment by dsyme** [comment]
> FSC : error FS0193: The module/namespace 'Microsoft.FSharp.Core' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'string' [C:\Code\visualfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]

I saw this.  I think I rebuilt "proto" and it went away.  But i don't understand why we would be getting this error.

**Comment by saul** [comment]
I'm more concerned that the CI is failing with an error that I can't reproduce locally :/

@dotnet-bot test this please

**Comment by cartermp** [comment]
@dotnet-bot test this please

Yeah @saul I don't know what's up.  Jenkins says no identified problem...

**Comment by saul** [comment]
Okay the remaining failures are because the suggested errors are no longer collapsed in --vserrors mode. I'll get onto fixing these tests

**Comment by heejaechang** [comment]
this is de-duplication happens by Roslyn? the error from build doesn't have error code, so, I am not sure how Roslyn will do de-duplication?

**Comment by saul** [comment]
@heejaechang there's no way to supply the error code with [DocumentTask](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.package.documenttask.aspx). It's worth pointing out that the de-duplication worked in VS 2015 and prior.

See [IDEBuildLogger.cs](https://github.com/Microsoft/visualfsharp/blob/d8253cc4c3f03269410c90613dcdf51a43a1e331/vsintegration/src/FSharp.ProjectSystem.Base/Project/IDEBuildLogger.cs#L336-L341) for where the project system passes build errors to the platform.

**Comment by heejaechang** [comment]
@saul is VS 2015 and prior used Roslyn? at the time, they might have their own way to do so, but Roslyn uses error code as one of way to do de-duplication. so without it, I dont think it will work.

**Comment by heejaechang** [comment]
@KevinRansom @brettfo who should I talk about these issue? need to know how fsharp build errors are flown into Roslyn to see how we can do proper de-duplication.

**Comment by saul** [comment]
@heejaechang I can answer that. F# build errors are passed to the IDE via the [ErrorListProvider](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.errorlistprovider.aspx), which is wrapped by a Microsoft.VisualStudio.Shell.TaskProvider. See [DocumentTask.cs@506](https://github.com/Microsoft/visualfsharp/blob/d8253cc4c3f03269410c90613dcdf51a43a1e331/vsintegration/src/FSharp.LanguageService.Base/DocumentTask.cs#L506) in the F# code.

I think the correct solution for this is to move over to Roslyn's ProjectExternalErrorReporter. We currently don't report any errors through this, but this class implements IVsLanguageServiceBuildErrorReporter2 so we can report build errors through the ReportError2 method. This is what the Roslyn project system does.

**Comment by saul** [comment]
@dsyme @brettfo How do I change the FSharpQA tests to test for multiline errors? It looks like the test runner is making the regexes match the whole line.

**Comment by saul** [comment]
@cartermp @KevinRansom this is now green :) I'll raise a ticket for fixing the duplication once this is merged

**Comment by cartermp** [comment]
@saul I'm away from my machine at the moment; do the changes to error messages change lightbulb behavior for misspelled tokens?

**Comment by saul** [comment]
@cartermp no, the errors reported via the compiler when --vserrors is supplied (like when you do Build Solution in the IDE) have been made so that they match the errors reported via IntelliSense. Lightbulb fixes are unaffected, this is just a step towards being able to unify the errors reported by IntelliSense and the compiler in the Error List,

**Comment by cartermp** [comment]
Makes sense.  Was just curious since you touched the error message files themselves.  I'll try this out tonight, but otherwise this all looks good.

**Comment by dsyme** [comment]
@saul @cartermp Slightly off topic: I was using the latest nightly and for the first time with VS2017 saw some issues where error messages weren't appearing in the error list, (and no red suigglies) for some files that definitely contained errors. Strangely quickinfo and autocompelte were still correct and updating, which made it feel like some problem with processing diagnostics Perhaps fixed by this PR< perhaps not.

I figured I should mention it so we can keep an eye out for problems.

**Comment by BentTranberg** [comment]
Some observations that will perhaps be of help while verifying any fix.

I have been running VS 2017 on an Intel NUC D54250WYK from the day of release, and that's not a particularly powerful machine. I have been thinking that perhaps this makes it easier to observe these problems. Perhaps the Intellisense has low priority, and tends to loose the races on a less powerful machine. Just a thought.

As I have previously reported in #2548, the situation on my machine has been hugely improved from around one month ago, and has been negligible since then. However, I did see something remarkable last week when I started to slash source away in huge chunks from the big solution I am working on, in order to create a minimal repro for another issue here. That turned out to be an incredibly effective way to provoke #2839 (this) and #2548. It was as bad as day one, with hundreds of errors and warnings being there when they shouldn't or vice versa. Some went away given a few minutes, and some just stuck until the solution was reopened. Have also observed the same on lesser scale earlier.

**Comment by dsyme** [comment]
Just to say I've been using the nightly (from two days ago) on FSharp.sln and the error list has some severe problems - lots of errors and red-squigglies were missing (intellisense errors, not build errors - I wasn't building from the IDE).

I'm not sure if it will improve with this PR or if it is orthoginal.  Will try the new nightly with this change when it is avaiable

**Comment by cartermp** [comment]
I've noticed that as well.  It appears at the very top of the file.

**Comment by cartermp** [comment]
e.g., in `Salsa.fs`:
```
Problem reading assembly 'C:\repos\visualfsharp\Debug\net40\bin\FSharp.ProjectSystem.FSharp.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 1063; Id 1064; Id 1065; Id 1066; Id 1067|], Id 1069,
 false, None)).	VisualFSharp.Salsa	C:\repos\visualfsharp\vsintegration\tests\Salsa\Salsa.fs
```

**Pull request merged**
