### PR TITLE
Speed up Constraint Solver's overload resolution (II)

### PR DESCRIPTION
**Pull request by gmpl**
This will **speed up to 2x overload resolution** in cases like [this](https://github.com/gmpl/FsControl/blob/f125b96d252080f722a1ff7a9efcfaf53420a339/FsControl.Core/Samples/Converter.fsx#L57).

This PR is a follow-up of #1530 where it was discussed that ideally the constraint solution can be committed a bit early.

The problem was that knowing the solution early would make some very exotic cases like [this one](https://gist.github.com/gmpl/453e55a0a615644561fbec1a0a771f62) to fail.

After analysing the problem I found that cases like that would fail because the first overload that is considered would succeed if the constraint is assumed as solved, when in fact it should fail (false positive).

Assuming that specific constraint solution makes impossible to solve the nested overload resolution called by <code>SolveMemberConstraint</code> which is expected to fail and indeed it fails, but because that result is ignored, it's marked as a false positive and the compilation breaks later by not being able to decide between 2 overloads: the good one and the bad one which is treated as good.

The proposed change adds an internal exception to signal the calling function (in the analysed case it was called from <code>solveTypMeetsTyparConstraints</code>) an unresolved overload and make the whole assumption fail.

The tests I made show no performance degradation but an improvement in some cases, which is  logically expected because we will be using a shortcut in some cases.

But the improvement went a bit further since now by signaling an inconsistent case it also discards early some paths and I wouldn't be surprised if it fixes some existing bugs which were consequence of this previously ignored result.

Here's a [test](https://gist.github.com/gmpl/13cafa9d3ca871b05443583f8f053610) I run with the following results:

```
(* before #1530 *)  val compileTime : float = 20613.1785
(* after #1530 *)   val compileTime : float = 563.0135
(* after this PR *) val compileTime : float = 280.0141
```

### CODE REVIEW

**Comment by gmpl** [comment]
The test that is failing was the example that was added on #1530 which was never ending to compile before that PR, then after #1530 it fails with unresolved overload.

Now with this PR it will fail with "this value is not a function ..." which I think makes sense by reading the code, since it's a <code>()</code> value.

It looks like with this PR type inference goes a bit further.

**Comment by gmpl** [comment]
@dsyme I did the changes you requested in the other PRs but still didn't have any feedback on this, did you have the chance to have a look?

**Comment by dsyme** [comment]
This change looks great. Approved.

**Comment by gmpl** [comment]
@dsyme I found a small issue with this PR but it's fixed now.

The original reasoning was to observe the result only when calling from <code>solveTypMeetsTyparConstraints</code>.

Intuition and extensive testing showed that <code>permitWeakResolution</code> could be used for this purpose however I just came up with [a snippet](https://gist.github.com/gmpl/a7ab48fbb69837b9cfe4c5a680302d4d)  that will fail.

To avoid that, we need to pass an additional parameter and that's exactly what I did.

**Comment by KevinRansom** [comment]
Thank you for taking care of this

**Pull request merged**
