### PR TITLE
[WIP] Fix #669 - Initialization soundness checks don't work for base constructor calls from primary constructors

### LINKED ISSUE #669: Initialization soundness checks don't work for base constructor calls from primary constructors
It appears that the compiler doesn’t check arguments to base class constructors for recursive references:

``` fsharp
type Parent(o:obj) = class end
type Broken() as self = inherit Parent(self)
```

Attempting to call the constructor for Broken will fail with a null reference exception.  However, I would have expected this to be picked up by F#’s initialization soundness checks, and to at least throw a more meaningful InvalidOperationException.  This only appears to affect primary constructors.  For instance, with the following definition of Broken, the expected error is generated:

``` fsharp
type Broken = 
    inherit Parent
    new() as self = { inherit Parent(self) }
```

Worse, the broken soundness checks for primary base constructor calls also breaks some valid uses of self references:

``` fsharp
type Parent<'t>(t:'t) = 
    member val T = t

type Ok() as self = inherit Parent<unit->Ok>(fun () -> self)

// inexplicably fails
Ok().T()
```

Note that once again using an explicit constructor improves things:

``` fsharp
type Ok = 
    inherit Parent<unit->Ok>
    new() as self = { inherit Parent<unit->Ok>(fun () -> self) }

// works
Ok().T()
```

### PR DESCRIPTION
**Pull request by kurtschelfthout**
The reason this failed is detailed in #669 - this fixes the issue. But to be honest I don't understand the construction sequence in enough detail to be 100% confident about this fix.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by kurtschelfthout** [comment]
@KevinRansom  Sorry for the lull here. To clarify, I still have to look at the failing tests, they did look material. To be honest I went from "not 100% confident that this is right" to "almost 100% confident that this is wrong" :) hence added the WIP.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please.

@kurt is this still an active PR, Has your confidence in the rightness of this approach returned?

**Comment by KevinRansom** [comment]
@kurtschelfthout 

3 failures ...

````
1) Failed : FSharp-Tests-Core+CoreTests.members-basics-hw
Error running command 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\..\..\release\net40\bin\fsc.exe' with args '-r:System.Core.dll --nowarn:20 --define:COMPILED --optimize+ --debug -o:test--optplus--debug.exe -g test.fsx' in directory 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\core\members\basics-hw'. ERRORLEVEL 1
at TestFramework.checkResult(CmdResult result) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 239
at TestFramework.exec@418-22.Invoke(CmdResult result) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 418
at TestFramework.fsc@426-1.Invoke(String flags, FSharpList`1 srcFiles) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 426
at SingleTest.singleTestBuildAndRunCore(TestConfig cfg, String copyFiles, Permutation p) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\single-test.fs:line 122
at FSharp-Tests-Core.CoreTests.members-basics-hw() in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\tests.fs:line 935

2) Failed : FSharp-Tests-Core+CoreTests.members-basics-hw-mutrec
Error running command 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\..\..\release\net40\bin\fsc.exe' with args '-r:System.Core.dll --nowarn:20 --define:COMPILED --optimize+ --debug -o:test--optplus--debug.exe -g test.fs' in directory 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\core\members\basics-hw-mutrec'. ERRORLEVEL 1
at TestFramework.checkResult(CmdResult result) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 239
at TestFramework.exec@418-22.Invoke(CmdResult result) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 418
at TestFramework.fsc@426-1.Invoke(String flags, FSharpList`1 srcFiles) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 426
at SingleTest.singleTestBuildAndRunCore(TestConfig cfg, String copyFiles, Permutation p) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\single-test.fs:line 122
at FSharp-Tests-Core.CoreTests.members-basics-hw-mutrec() in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\tests.fs:line 939

3) Failed : FSharp-Tests-Core+CoreTests.topinit
Error running command 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\..\..\release\net40\bin\fsc.exe' with args '-r:System.Core.dll --nowarn:20 --define:COMPILED --optimize- -o test_static_init.exe test0.fs test1.fs test2.fs test3.fs test4.fs test5.fs test6.fs static-main.fs' in directory 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\core\topinit'. ERRORLEVEL 1
at TestFramework.checkResult(CmdResult result) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 239
at TestFramework.exec@418-22.Invoke(CmdResult result) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 418
at TestFramework.fsc@426-1.Invoke(String flags, FSharpList`1 srcFiles) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 426
at FSharp-Tests-Core.CoreTests.topinit() in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\tests.fs:line 1277

Run Settings
    RuntimeFramework: V4.0
    WorkDirectory: D:\j\workspace\release_ci_pa---866fd2c3\release\net40\bin
    Verbose: True
    NumberOfTestWorkers: 4

Test Run Summary
    Overall result: Failed
   Tests run: 333, Passed: 330, Errors: 0, Failures: 3, Inconclusive: 0
     Not run: 2, Invalid: 0, Ignored: 2, Explicit: 0, Skipped: 0
  Start time: 2017-02-03 20:13:24Z
    End time: 2017-02-03 20:44:11Z
    Duration: 1847.221 seconds


````

**Comment by kurtschelfthout** [comment]
Sorry, I gave up on this one a bit.

I'm confident the bit I changed is the source of the problem, but I'm equally confident that my change is not the right thing to do. So the test failures are undoubtedly real and this should not be merged.

I'll close for now.

**Pull request closed without merging**
