### PR TITLE
add diagnostics

### PR DESCRIPTION
**Pull request by dsyme**
Some PRs are hitting a corner-case where our binary writer reports
```
  FSC : error FS2014: A problem occurred writing the binary ... EmitZUntaggedIndex: too big for small address or simple index 
```
This adds some diagnostics so that next time this happens we can find out a bit more about why

### CODE REVIEW

**Comment by dsyme** [comment]
I am also using this PR to add some extra diagnostics and a possible fix for the "type provider smoke tests" which fail from time to time

**Comment by KevinRansom** [comment]
@dsyme the only changes in the one file are to the unit tests, perhaps you need to add a file to the commit.

**Comment by dsyme** [comment]
> @dsyme the only changes in the one file are to the unit tests, perhaps you need to add a file to the commit.

Most of the changes were incorporated into #6316 , this is the last part of the diagnostics in one of the flaky unit test

**Comment by dsyme** [comment]
Dodgy test: `AwaitTaskCancellationAfterAsyncTokenCancellation`

**Comment by dsyme** [comment]
The SmokeTests failed again, but this time we got a little more information:
```
Failed   TypeProvider.Disposal.SmokeTest1
Error Message:
   Check3, countCreations() = i, iteration 35, countCreations() = 36
  Expected: True
  But was:  False
```
(It's very odd that this is erratic: there are more creations than interations.???...)

**Comment by dsyme** [comment]
I updated this with improvements to make the TypeProvider disposal smoke test less flaky

**Comment by dsyme** [comment]
CI is no longer being triggered on Push for some reason.....

**Comment by dsyme** [comment]
This is ready - some diagnostics and some changes to reduce test flakiness

**Pull request merged**
