### PR TITLE
Name resolution environment captures last ident range instead of full range in long ident 

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
For

```fsharp
module M =
    let _x = System.Collections.Generic.List<int>()

[<EntryPoint>]
let main argv = 
    0
```

image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
The CI does not trigger. @cartermp @KevinRansom

**Comment by brettfo** [comment]
All of our (our = F# + dotnet + others) Jenkins machines are currently down; it's being worked on, but I haven't heard an ETA yet.

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by TIHan** [comment]
@dotnet-bot test this please

**Comment by cartermp** [comment]
@dotnet-bot test this please

**Comment by cartermp** [comment]
Also, conflicts

**Comment by vasily-kirichenko** [comment]
It’s not finished. @auduchinok promised to work on it.

**Comment by KevinRansom** [comment]
@auduchinok is this something you are interested in finishing off?

**Comment by KevinRansom** [comment]
This is a promising work item, however, we are trying to reduce the number of PRs that seem to have been abandoned.

Please reopen or resubmit, when you feel that you are able to complete the work.

Thank you,

Kevin

**Pull request closed without merging**
