### PR TITLE
Structure guidelines fixes

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by cloudRoutine** [comment]
@vasily-kirichenko how do you want to approach outlining with all of this stuff taken out?

**Comment by vasily-kirichenko** [comment]
@cloudRoutine these stuff, which has been taken out, places guidelines in wrong positions, it's good for outlining, but the primary goal of this service is guidelines, so I don't care if some outlining become not so fancy, I think we should turn some of them off actually.

**Comment by cloudRoutine** [comment]
Now we're back to the terrible collapsing, which is why I think we should do the outlining like we were in VFPT, it worked better and looked a lot nicer.

I get that it's just for the guidelines right now, but we should be able to adjust it so that it can be used for both.

**Comment by vasily-kirichenko** [comment]
I've looked at BlockSpan again and it seems it's HintSpan property http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Structure/BlockSpan.cs,24 is used for defining outlining, while TextSpan is for guidelines. Could you try to set it and look if it helps?

**Comment by cloudRoutine** [comment]
I'll work on getting it all to work in the block structure service today and try to fix those bugs

**Comment by vasily-kirichenko** [comment]
@cloudRoutine OK, I agree the current state of this service is not good, I'm closing this PR in favor of your work.

**Pull request closed without merging**
