### PR TITLE
This closes #765 by removing an invalid nuget reference to Microsoft.…

### LINKED ISSUE #765: Invalid nuget version number listed for Microsoft.DotNet.BuildTools
This line of code:
https://github.com/Microsoft/visualfsharp/blob/4598abfdd07eab392f76e7670af4d35305415a12/packages.config#L4
references version '1.0.25-prerelease-00085' which does not exist.  This causes a build of the proto-compiler to fail.  Commenting out this line allows the build of the proto-compiler to succeed.

### PR DESCRIPTION
**Pull request by WilliamBerryiii**
…DotNet.BuildTools

### CODE REVIEW

**Comment by KevinRansom** [comment]
Thanks for this I just noticed the same thing this weekend.

**Comment by mexx** [comment]
Sorry, but what about the `myget.org dotnet-buildtools` package source referenced in [`NuGet.Config`](https://github.com/Microsoft/visualfsharp/blob/4598abfdd07eab392f76e7670af4d35305415a12/.nuget/NuGet.Config#L8)? For me the referenced version was successfully retrieved from this server.

**Comment by WilliamBerryiii** [comment]
When running the following command on a fresh checkout of the repository:

```msbuild -v:diag src\fsharp-proto-build.proj```

the diagnostic output from msbuild is:

```Task "Exec" (TaskId:5)
  Task Parameter:Command=.\.nuget\NuGet.exe restore packages.config -PackagesDirectory packages (TaskId:5)
  Task Parameter:WorkingDirectory=..\..\.. (TaskId:5)
  .\.nuget\NuGet.exe restore packages.config -PackagesDirectory packages (TaskId:5)
  Unable to find version '1.0.25-prerelease-00085' of package 'Microsoft.DotNet.BuildTools'. (TaskId:5)
C:\foo\visualfsharp\src\FSharpSource.targets(761,5): error MSB3073: The command ".\.nuget\NuGet.exe restore packages.config -PackagesDirectory packages" exited with code 1. [C:\foo\visualfsharp\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj]
Done executing task "Exec" -- FAILED. (TaskId:5)
Done building target "BeforeBuild" in project "FSharp.Build-proto.fsproj" -- FAILED.: (TargetId:4)
```

So it would appear that Nuget.exe is not using the supplied configuration sitting next to the executable with the MyGet defs.

**Comment by KevinRansom** [comment]
the reference is only necessary for the coreclr build, which is in the coreclr branch.  Somehow I inadvertently messed the packages.config on master.

**Comment by KevinRansom** [comment]
Thank you for taking care of this it was merged: https://github.com/Microsoft/visualfsharp/commit/f3a0d7d54db0f881bb39f94c57420db0413fcbb0

**Pull request closed without merging**
