### PR TITLE
Adding FsCheck tests for all regular collections functions

### PR DESCRIPTION
**Pull request by forki**
based on #372 I started to add more and more test for https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/ListSeqArrayAdditions.md

I already discovered #501

### CODE REVIEW

**Comment by latkin** [comment]
As discussed earlier, this should be implemented as new test cases in the existing core unit test project.

**Comment by forki** [comment]
Yep, but that didn't work well. Maybe I try again when I'm done

**Comment by theimowski** [comment]
It looks good to me, great work @forki. feel free to proceed with removing [WIP] prefix

**Comment by forki** [comment]
So I think I'm ready with this. 

It tests all functions in [Regular functional functions](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/ListSeqArrayAdditions.md#regular-functional-functions)

We now have 148 property-based tests with 100 tests each.

I kept it as as separate project for two reason:
  * we don't mess with the current unit tests (we use slightly different tools and whatever I tried I always end up with broken unittest project)
  * runtime of the tests is > 100s and we don't need this for all platforms. Whenever we detect a bug we would still add another concrete unittest

**Comment by vasily-kirichenko** [comment]
Wow. Great stuff.

**Comment by tpetricek** [comment]
Very cool :). I think Microsoft will basically need to send you a full set of kitchen utensils for this one.

**Comment by eiriktsarpalis** [comment]
:+1:

**Comment by latkin** [comment]
Great work!

I still think this should live together with the current core unit tests.  If someone is adding/fixing/optimizing and API and wants to add tests, or review what tests there are, it's *much* easier if all cases live next to each other.

What is blocking the integration, specifically? In the CI build I see that it builds cleanly for desktop but fails for portable47.  Do you know if it works for portable 7/78/259?  Does FsCheck simply not support portable profiles? We can always conditionally compile it only for desktop, while we work on getting FsCheck to properly support portable profiles.

**Comment by forki** [comment]
it's always failing to load libs at runtime. and no idea which one.

**Comment by forki** [comment]
added tests for https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/ListSeqArrayAdditions.md#regular-functional-functions
==> 156 passed

**Comment by kurtschelfthout** [comment]
FsCheck does not compile for portable profiles. Well, I've tried 259 and there's a bunch of things that don't work, in particular reflection. I'm not very familiar with portable class libraries. 

Which profile do you need it to build with, i.e. which one is the most restrictive? Or is this going to be a conditional compilation affair?

**Comment by latkin** [comment]
Visual F# ships FSharp.Core.dll for profiles 47, 7, 259, and 78.

Profile 47 is "old style" portable, which is quickly falling out of fashion over here (though probably still used by many in the wild). So I suppose it's safe to say it's the lowest priority profile to look at (at least from our perspective).

Profiles 7, 78, and 259 are pretty similar, so once you get one of those it should be quick to get the others.  I think you are correct that 259 is the most restrictive, but I'm not positive.

**Comment by kurtschelfthout** [comment]
Folks, I just released Fscheck 2.0.3 which has support for 7/78/259. Please give it a try, thanks.

**Comment by forki** [comment]
wow that sounds very cool. maybe I find some time tomorrow.

**Comment by forki** [comment]
mhm. it seems it's still not working with portable47

**Comment by kurtschelfthout** [comment]
no, didn't do portable47 yet. Didn't compile on quick try, not sure why. So that's expected.

**Comment by forki** [comment]
@latkin what can we do to go forward?

**Comment by latkin** [comment]
If it's working for desktop and 7/78/259 portable, I think that's enough for now.  If/when fscheck gets 47 support we can add that here, too.  So I'd say the fscheck reference and the property test sources should just be conditionally added in the project file so that they are skipped for 47.

**Comment by forki** [comment]
could you please review 6460dae? Is that correct?

**Comment by forki** [comment]
@latkin should I rebase this on a different branch?

**Comment by latkin** [comment]
@forki Don't worry about it. If the merges get too complex I'll ask for help, otherwise I'm happy to patch up the conflicts myself.

**Comment by latkin** [comment]
@forki I've merged this, however I can't get it to run.  NUnit crashes out with exception saying it is unable to load FSharp.Core.Unittests.dll, which is rather bizarre. Not sure if I'm under-caffeinated or what, but so far I haven't been able to debug this.

Fusion log viewer shows failed bind from `nunit-agent.exe`, but succesful bind from spawned `Tests_12345...` (logs [here](https://gist.github.com/latkin/b343db6e9e87006f2832)).  Everything works fine for portable47 tests without FsCheck, in that case `nunit-agent.exe` never attempts to bind to FSharp.Core.Unittests.dll at all.

@kurtschelfthout or @forki, any ideas why adding fscheck would cause NUnit to get over-eager about loading the assembly? Maybe I'm missing something obvious?

**Comment by tpetricek** [comment]
Just a wild guess - but I always had troubles with NUnit + FsCheck because of some FSharp.Core.dll issues. So perhaps NUnit loads a wrong version of FSharp.Core (the one needed by FsCheck and not the one needed by the library it's testing)?

**Comment by latkin** [comment]
@tpetricek FSharp.Core is resolved ok and loaded w/o issue from what I'm seeing.

The issue has something to do with the surface area of the tests themselves. If I omit ListProperties.fs and CollectionModulesConsistency.fs, NUnit happily loads everything (i.e. ArrayProperties and SeqProperties are fine).  If I add either of those back, it starts failing again.  This repros on both of my machines, however it seems the CI build was fine :confused: 

Current guess is that if test case methods contain F#-specific types in their signatures, nunit has a harder time loading/resolving things.

**Comment by latkin** [comment]
Issue is that FsCheck binaries are not strong-named, but unit test assembly is. If I remove the strong-naming on the unit tests it works fine.  I'm curious how this ever worked for @forki and CI?

**Comment by forki** [comment]
Oh I removed strong-naming in my separate lib. Maybe it got lost during
merge into the combined unittest project.

**Comment by latkin** [comment]
But CI build worked, and looking at the build log, unit tests indeed ref FsCheck and include new cases, and are also signed...

Well, AFAIK the core unit tests don't require strong-naming (they don't have internalsvisibleto for anything), so I will just remove it.

**Comment by latkin** [comment]
Ok I finally see what happened - @forki added `#if portable7 || portable78 || portable259` to all of the new cases.  That means they were only compiled for portable profile, *not for `net40`*, which is the only target framework that's actually run.

**Comment by latkin** [comment]
Took a bit more refactoring of build stuff to get portable working, but it's done and merged to OOB branch.  Great work!

**Comment by forki** [comment]
Very very cool. Thanks @latkin

**Comment by theimowski** [comment]
Great stuff @forki! Glad I could be (merely) part of it ;)

**Comment by forki** [comment]
@theimowski thanks for getting this started. Now we as a community should always write some property-based tests for new (and old) code. Should be much easier to get that accepted now.

**Pull request closed without merging**
