### PR TITLE
Fix missing intellisense #2962 

### PR DESCRIPTION
**Pull request by dsyme**
This fixes the missing intellisense regression https://github.com/Microsoft/visualfsharp/issues/2962 using the technique mentioned at the end of that discussion

https://github.com/Microsoft/visualfsharp/issues/2970 also seems fixed - perhaps not by this though

### CODE REVIEW

**Comment by saul** [comment]
Thanks @dsyme!

**Comment by vasily-kirichenko** [comment]
@dsyme #2970 is not fixed:

image

**Comment by dsyme** [comment]
@vasily-kirichenko Thanks, looking into it. It seemed ok when I checked last night

**Comment by vasily-kirichenko** [comment]
@dsyme It works OK on release VSIX, but never - on debug on.

**Comment by dsyme** [comment]
@vasily-kirichenko Strange - Intellisense works for me in Project.fs.  Are you doing anything special, e.g. reloading the solution, or cleaning the directories, or ...?

**Comment by dsyme** [comment]
Ah, I see, debug is the problem.  Will take a look

**Pull request merged**
