### PR TITLE
fix order of file items in FSharp.Core

### LINKED ISSUE #3621: FSharp.Core project is broken
image

### PR DESCRIPTION
**Pull request by brettfo**
Fixes #3621.

### CODE REVIEW

**Comment by brettfo** [comment]
@dotnet-bot test this please

**Comment by brettfo** [comment]
ci_part2 timed out on Jenkins, but everything else passed.  I'll run ci_part2 locally and merge if it passes so others aren't blocked anymore.

**Comment by abelbraaksma** [comment]
@KevinRansom: I'm not sure if the project system is at fault. When I run all tests locally it usually hangs on the GeneratedTests in FSharp.Core.UnitTests. It doesn't hang if I select smaller sets, or if I run everything sequentially (but that takes forever, just trying that now). Just saying, perhaps Jenkins has the same problems as the test runners I am using and then the cause may very well be with a bug in the code/compiler or something.

**Comment by KevinRansom** [comment]
Hmm ... there is something awry that's for sure.

**Pull request merged**
