### PR TITLE
[RFC FS-1054] less strict indentation on common DSL pattern

### PR DESCRIPTION
**Pull request by dsyme**
Implements this relaxation of the F# indentation rules:

https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1054-undent-list-args.md

The change just a couple of lines.

### CODE REVIEW

**Comment by cartermp** [comment]
Love this change. I think that the current lack of undentation on `[...]` and `[|...|]` violates the principle of least surprise for newcomers, too.

**Comment by dsyme** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please

**Comment by dsyme** [comment]
This is ready

**Comment by abelbraaksma** [comment]
This may be a small change but it is very welcome, not just for beginners. I often struggle with nicely laying out the code in three cases and I think this helps readability. Thanks!

**Pull request merged**
