### PR TITLE
Update documentation for debug flags

### LINKED ISSUE #311: FSC and FSI usage text and code comments inaccurate regarding debug defaults
Both FSI and FSC print the following usage info for the `--debug` flag:

```
                - CODE GENERATION -
--debug[+|-]                   Emit debug information (Short form: -g)
--debug:{full|pdbonly}         Specify debugging type: full, pdbonly. ('full' is the default and enables attaching a
                               debugger to a running program).
```
It says `full` is the default debug setting.  However this is not true, either in FSC or in FSI.

(note that `-g` ==  `--debug+` == `--debug:full`)

-----

In FSC the [relevant code](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/fsc.fs#L322-L325) reads:

```fsharp
    // Preset: --optimize+ -g --tailcalls+ (see 4505)
    SetOptimizeSwitch tcConfigB On
    SetDebugSwitch    tcConfigB None Off
    SetTailcallSwitch tcConfigB On 
```
The call to `SetDebugSwitch` is actually equivalent to `--debug-`, so both the usage text and the comment are incorrect.

-----
In FSI the [relevant code](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/fsi/fsi.fs#L2147-L2150) reads:

```fsharp
    // Preset: --optimize+ -g --tailcalls+ (see 4505)
    do SetOptimizeSwitch tcConfigB On
    do SetDebugSwitch    tcConfigB (Some "pdbonly") On
    do SetTailcallSwitch tcConfigB On  
```
The call to `SetDebugSwitch` is actually equivalent to `--debug:pdbonly`, so both the usage text and the comment are incorrect

-----

We should either
- Modify the true defaults so they match the documentation/comments
- Modify the documentation/comments so they match the true defaults

### PR DESCRIPTION
**Pull request by jwood803**
This should fix #311

### CODE REVIEW

**Comment by latkin** [comment]
Hi @jwood803, thanks for taking a look at this. Have you submitted a CLA yet? https://cla.msopentech.com/

Your changes appear to only be updating the tests, they don't actually change the product behavior. Required changes will be in [fscopts.fs](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/fscopts.fs#L301-L305) and [FSComp.txt](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/FSComp.txt#L874-L875)

**Comment by jwood803** [comment]
I haven't heard back from the manager yet but I'll ask about it today.

And sorry about that. I didn't realize there were more places to update. I'll see if I can make them tonight.

**Comment by jwood803** [comment]
CLA has been submitted. I think I just messed up this branch now, though...

**Comment by latkin** [comment]
When you run `fsc.exe /?` on bits built with your change, does the output look right?  My suggestion on a better usage message is [here](https://github.com/Microsoft/visualfsharp/issues/311#issuecomment-85198522), you can use that if you like.

I'd recommend doing something like this:
- Update `optsDebug` message in FSComp.txt to contain all text for the debug flag
- In the implementation in fscopts.fs, [change one of the debug options to have a `None` message](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/fscopts.fs#L302), so that the debug flag isn't listed twice like it is today
- Rename `tagFullPDBOnly` to, say, `tagDebugOptions` and change its value to `[+|-|:full|:pdbonly]`

To get the output just right you'll need to create a new option type, say, `OptionStringNoColon` [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/build.fs#L5136-L5150) and handle printing it [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/build.fs#L5170) (similar to `OptionString` but omitting the colon).

**Comment by jwood803** [comment]
Thanks @latkin! I really appreciate the help with this. Sorry if I've taken too long on it.

I'll try to give an update over the weekend.

**Comment by jwood803** [comment]
Not sure why this auto-closed. I'll try to fix this...

**Comment by jwood803** [comment]
I think [this](https://help.github.com/articles/closing-issues-via-commit-messages/) is what happened causing it to auto-close when merging with master and some commits there have "fix" in it. Can this be reopened or should I just do another PR?

I'm at a lost why it says it's been merged, though.

**Comment by latkin** [comment]
It's probably easier to just open a new PR

**Comment by jwood803** [comment]
That's what I was thinking. Apologies for the confusion here. I'll reference this with the other so it can all be tracked.

**Pull request closed without merging**
