### PR TITLE
[WIP] Using MiscellaneousFilesWorkspace to handle single files

### PR DESCRIPTION
**Pull request by TIHan**
**Edited(New):**
We now use the MiscellaneousFilesWorkspace properly for single files. This solves a lot of issues we had with script files and gets rid of cruft.

**Original:**
Refactoring how we handle single files in the workspace. Eventually, this will be switched over to Roslyn's Miscellaneous Workspace.

### CODE REVIEW

**Comment by dsyme** [comment]
@TIHan What validation have you done for this one, e.g.

* Create new .fsx script - both before and after loading an F# project - does it work, give errors, intellisense etc?
* Open existing .fsx script - both before and after loading an F# project - does it work, give errors, intellisense etc?  Does it work if the script is in a project with build action None and/or Compile?
* Rename script - this is broken today so we don't expect it to start working

**Comment by TIHan** [comment]
@dsyme 

I've tested the scenarios:

- Create new .fsx script, make sure tooling works. Then create a project, then create a .fsx to verify tooling works.
- Rename script is still broken.

I will do more testing to verify more behavior.

The changes are just a refactoring rather than a re-design.

**Comment by smoothdeveloper** [comment]
Feels like ground work to integrate #4122 is ongoing :slightly_smiling_face: the changes here are definitely not something I'd would have come up with given 0 exposure to roslyn.

**Comment by saul** [comment]
@TIHan see my changes here: https://github.com/saul/visualfsharp/commit/eedfcea5c3416b49f3c30bd35ed0a9dab5df95f3#diff-cdf0a4fbb7615b8029d78133924259c3

I fixed .fsx script opening and renaming a while back, by essentially copying/pasting MiscellaneousFilesWorkspace out of Roslyn. The pertinent parts are in the IVsRunningDocTableEvents implementation. I had to do this at the time as MiscellaneousFilesWorkspace was internal to Roslyn, but in 15.3 it got made public - we should definitely just use that. It removes a load of cruft that we currently have.

**Comment by TIHan** [comment]
@saul that is some good work. Yes, we should use MiscellaneousFilesWorkspace. I'll see if we can just use it, but I have a feeling we might have to wait for https://github.com/dotnet/roslyn/pull/26931.

**Comment by TIHan** [comment]
Getting MiscellaneousFilesWorkspace to work was actually quite easy and fixes issues with script files rename as well. Actually, this solves a lot of problems.

This changed from a refactor to a different design (a much better one).

**Comment by cartermp** [comment]
@TIHan and I validated:

* Renaming script file
* Renaming source to script
* Renaming script to source

**Comment by TIHan** [comment]
So, I've received some information regarding the MiscellaneousFilesWorkspace. It doesn't kick off analyzers. This means no error + warning reporting, unused declaration/opens, etc. This is a big problem for us. After some discussion, it may be that the MiscellaneousFilesWorkspace is actually not right for us and we were almost doing the right thing to begin with.

**Comment by saul** [comment]
@TIHan You can replicate the miscellaneous files workspace using IVsRunningDocumentTable as I did in my PR.

**Comment by TIHan** [comment]
@saul that is what I'm going to look into.

**Comment by dsyme** [comment]
My main request for this sort of thing is to make sure we haven't regressed performance on large solution load. And also scripts with large numbers of transitive references to other scripts and assemblies.

See tests\projects\stress for the former.  We should add a stress test there for scripts with large numbers of transitive references to other scripts and assemblies

**Comment by TIHan** [comment]
@dsyme I agree. We definitely shouldn't regress performance. Adding stress tests would help us ensure that.

**Comment by TIHan** [comment]
I'm closing this as we are going to make similar changes in the dev16.0 branch.

**Pull request closed without merging**
