### PR TITLE
add option to disable in-memory cross-project references

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by dsyme** [comment]
I put the option on the “Intellisense” page for simplicity, we should probably have it on a new page of its own for “Language Service Performance”

image

**Comment by vasily-kirichenko** [comment]
It would be great if you describe what this setting changes exactly, I mean what features degrade if it turned on.

**Comment by dsyme** [comment]
@vasily-kirichenko Yes, will do.  The change is part of an investigation for a problem with a particular user, it's not for immediate pull

**Comment by dsyme** [comment]
@vasily-kirichenko Here are my notes from an internal email. Thanks for reminding me to be transparent

... a scenario of excessive memory usage in a large solution is described via private screenshots ... My response below, slightly edited

--------

I believe there are several things potentially going on here:

1. Using stale results. 

   In VS2015 we allowed the use of “stale” typechecking results in intelliisense. In VS2017 we initially did not, but in this PR switched to allow the use of stale results after 1 second timeout.  I presume that PR is in the bits being used.

2. Allowing in-memory cross-project references without on-disk DLLs. 

   In VS2015 we required referenced projects to be compiled to DLLs and we read metadata from those DLLs

   In VS2017 we use in-memory cross-project references where we typecheck the code in memory, see this PR.

   This means that if you have a chain in projects A8 -> A7 -> … -> A1 (arrows represent direction of references) and you make a change in project A1 then go to project A8 then different things happen in VS2015 and VS2017:
                
   - In VS2015, you have to manually rebuild A1.  Experienced Visual F# users are used to this and it is hardwired in their brain. After you have rebuilt A1.dll, then you then go to A8, the language service will immediately pick up the changes to A1.dll, without rebuilding A2…A7.  And things will be pretty fast if A8 is small.

   - In VS2017, you don’t have to manually rebuild A1.  However the LS will recheck all of A1…A7 before the changes will appear in A8.  

In-memory cross-project references can also use significantly more memory. People who had the Visual F# Power Tools installed in VS2015 would experience overall less memory usage, because VFPT in VS2015 used a duplicate copy of the language service state  with cross-project references enabled.  However in the scenario described, the Visual F# Power Tools are not enabled.

3. Long delays in language service availability when changes have happened to referenced projects. 

   The changes in (2) above meant that, in some cases, requests submitted to the language service had large chunks of time where they were not cancellable (i.e. not checking IsCancellationRequested) – especially when dependent projects (A1 … A7) were being re-checked.  This meant that the usage of stale results (see #1) would not kick in, because the compiler service was busy processing a non-cancellable chunk of work. 

   This problem was present in VS2015, but was made worse by enabling in-memory cross-project references.  

   I believe this issue is entirely fixed by https://github.com/Microsoft/visualfsharp/pull/3063 but we have not yet pulled that.

So I believe (2) is the primary cause of the behaviour in the scenario. Essentially we are paying the cost for eliminating the manual builds of project references – i.e. doing things “right” but much more slowly in large solutions.

Tactically, I believe the two things would be 

1. Have the customer build and trial of VFT with cross-project references optionally disabled.  Unfortunately we didn’t include an option to disable this feature in 15.3 – I kept meaning to do it since I was suspicious of it, but ran into problems understanding what was going on with the options page.  To add the option, you would need to add a checkbox in the UI, propagate the flag and then change this:

        let referencedProjectFileNames, referencedProjectOptions = 
            referencedProjectsOf(tryGetOptionsForReferencedProject, projectSite, extraProjectInfo, serviceProvider, useUniqueStamp) 
            |> Array.unzip

To this:

        let referencedProjectFileNames, referencedProjectOptions = 
            if inMemoryCrossProjectReferencesEnabled then
                [| |], [| |]
            else
                referencedProjectsOf(tryGetOptionsForReferencedProject, projectSite, extraProjectInfo, serviceProvider, useUniqueStamp) 
                |> Array.unzip


If we verify that disabling this solves the problem, I would recommend that the ``inMemoryCrossProjectReferencesEnabled`` option be enabled by default, and that the documentation say something like this:

> disabling this option may reduce memory usage and increase response time for language service features, but will require manual rebuilds of dependent projects before changes are propagated to the rest of the solution

I will prepare a PR which the customer can pull or we can pull into master

2. Have the customer build and trial VFT with the [Cancel background work PR](https://github.com/Microsoft/visualfsharp/pull/3063) pulled.  Note this isn’t a thing that can easily be turned on/off, and step 1 should be performed independently to verify things.  If we verify this helps improve LS availability then we should also just pull that PR into master so people using nightlies are testing it

**Comment by dsyme** [comment]
this is ready

**Comment by dsyme** [comment]
@vasily-kirichenko I'm not sure if you're in the mood but you might be interested in these if they are helpful to you as a user:

> add an option to reduce the project cache size, which is currently set to 200 (in VS2015 it was only 3, because in-memory cross-project references were not enabled)

> add an option to enable the funky MaxMemory feature, which basically says “if the process memory reaches 2.3GB, flush all caches and reduce the project cache size to 1”. Or even enable it by default.

**Comment by vasily-kirichenko** [comment]
On this PR error highlighting does not update until the project is built:



(I'm not sure if the bug is introduced in this PR, I've not tested VFP for about a month or more).

**Comment by vasily-kirichenko** [comment]
Also, "go to definition" does not work for `FSharpChecker.Create` from FSharp.Editor project:

image

**Comment by dsyme** [comment]
> On this PR error highlighting does not update until the project is built:

With in-memory cross-project references enabled or disabled?

**Comment by dsyme** [comment]
> On this PR error highlighting does not update until the project is built:

I think this is #3047

**Comment by vasily-kirichenko** [comment]
> With in-memory cross-project references enabled or disabled?
Disabled.

**Comment by dsyme** [comment]
Closing in favour of https://github.com/Microsoft/visualfsharp/pull/3330

**Pull request closed without merging**
