### PR TITLE
Use UTC timestamps in the compiler and service

### PR DESCRIPTION
**Pull request by auduchinok**
Edited: getting Utc timestamps works faster and is used in ReSharper APIs and Roslyn.

Please note this is a breaking change for clients implementing a file system shim.
/cc @Krzysztof-Cieslak  @nosami

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
The main reason is performance I guess?

**Comment by auduchinok** [comment]
@vasily-kirichenko Yes.
Another reason is ReSharper document APIs use Utc. According to [this post](https://blogs.msdn.microsoft.com/kirillosenkov/2012/01/10/datetime-utcnow-is-generally-preferable-to-datetime-now/) Roslyn has moved to Utc as well, although I didn't check it.

**Comment by auduchinok** [comment]
@KevinRansom Looks like the part2 build is hanging for the second time today.

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please

**Comment by auduchinok** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please

**Comment by vasily-kirichenko** [comment]
@auduchinok part2 is rather slow, it's better to wait a bit longer.

**Comment by auduchinok** [comment]
@vasily-kirichenko Looks like the previous run wasn't actually cancelled as it had finally timed out and PR became red, so I asked the bot to run it again.

**Comment by auduchinok** [comment]
Funny enough, it was all green and now some previous run has timed out.

**Comment by auduchinok** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please

**Comment by KevinRansom** [comment]
Thank you for this.

**Pull request merged**
