### PR TITLE
Fast array partition

### PR DESCRIPTION
**Pull request by jackmott**
A partition function for arrays that runs about twice as fast and uses about half as much memory. This should be true for all cases, I believe.

Test results using BenchmarkDotNet, with a partition predicate of `fun x -> x % 2 = 0` on random int arrays.

```ini

Host Process Environment Information:
BenchmarkDotNet=v0.9.8.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4712HQ CPU 2.30GHz, ProcessorCount=8
Frequency=2240907 ticks, Resolution=446.2479 ns, Timer=TSC
CLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1590.0

Type=SIMDBenchmark  Mode=Throughput  Platform=X64  
Jit=RyuJit  GarbageCollection=Concurrent Workstation  

```
       Method | ArrayLength |              Median |            StdDev | Scaled | Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
------------- |------------ |-------------------- |------------------ |------- |------ |------ |------ |------------------- |
    **Partition** |          **10** |         **180.8758 ns** |        **16.3650 ns** |   **1.00** |  **0.01** |     **-** |     **-** |             **185.22** |
 NewPartition |          10 |          76.6145 ns |         1.2114 ns |   0.42 |  0.01 |     - |     - |              90.38 |
    **Partition** |         **100** |         **993.5865 ns** |        **17.6074 ns** |   **1.00** |  **0.06** |     **-** |     **-** |             **773.14** |
 NewPartition |         100 |         546.2619 ns |        21.6442 ns |   0.55 |  0.03 |     - |     - |             422.67 |
    **Partition** |       **10000** |     **117,268.5175 ns** |     **1,064.2667 ns** |   **1.00** |  **6.40** |     **-** |     **-** |          **99,742.26** |
 NewPartition |       10000 |      79,020.6291 ns |       474.4149 ns |   0.67 |  2.64 |     - |     - |          43,572.00 |
    **Partition** |     **1000000** |  **14,447,233.3078 ns** |   **205,852.6672 ns** |   **1.00** |  **6.93** |     **-** | **79.49** |       **5,919,035.36** |
 NewPartition |     1000000 |   9,908,404.2756 ns |   115,392.7494 ns |   0.69 |     - |     - | 78.45 |       3,587,942.38 |
    **Partition** |    **10000000** | **154,545,402.8213 ns** | **3,116,253.3692 ns** |   **1.00** |     **-** |     **-** | **62.02** |      **59,133,643.66** |
 NewPartition |    10000000 |  98,768,489.7225 ns |   726,198.4079 ns |   0.64 |     - |     - | 34.00 |      29,686,956.03 |

### CODE REVIEW

**Comment by forki** [comment]
"A partition function for arrays that runs about twice as fast and uses about half as much memory."

joker

**Comment by jackmott** [comment]
merging latest master into this and cleaning some things up, stand by.

**Comment by jackmott** [comment]
All done here unless someone has suggestions.

**Comment by KevinRansom** [comment]
Looks great to me.  I will probably pull it later this evening.

**Comment by dsyme** [comment]
Wow. Superb.

**Pull request merged**
