### PR TITLE
automate adding required Visual Studio components

### PR DESCRIPTION
**Pull request by ctaggart**
This should save time getting the required software installed to build everything. It could also serve as the concrete list for required software to build Visual F#. Please review the list of components to see if I got it right.

To get a list of components you currently have installed:
``` powershell
$vs = Get-VSSetupInstance
$vs.Packages | where Type -eq Component | sort Id | select Id, Version
```

### CODE REVIEW

**Comment by ctaggart** [comment]
@dotnet-bot test Ubuntu14.04 Release please

**Comment by ctaggart** [comment]
@dotnet-bot test Ubuntu14.04 Release Build please

**Comment by ctaggart** [comment]
Moved to scripts. Did I get the components right? I guess we will find out if people use it.

**Comment by ctaggart** [comment]
@dotnet-bot test Ubuntu14.04 Release Build please

**Comment by KevinRansom** [comment]
@ctaggart This adds in more components that are necessary.  But I still get failures, building and running all of the tests, after running the script.  So it's going to need more work

**Comment by KevinRansom** [comment]
I wonder what happened to my changes.  nm i'll merge this and fix it.

**Pull request merged**
