### PR TITLE
Upgrade fsharp test suite to nunit3 final

### PR DESCRIPTION
**Pull request by enricosada**
upgrade nunit final

TODO:

- [X] use nunit3-console.exe instead of nunit-console
- [X] disabled failing tests (11/1018)
- [x] convert powershell script to fsx
- [x] use nunit 2 xml test results format (instead of v3)
- [x] parallelize test suite

### CODE REVIEW

**Comment by enricosada** [comment]
i configured nunit to run the fsharp tests suite in [parallel](http://nunit.org/index.php?p=parallelizable&r=3.0) by test fixtures. In this suite that mean parallel by directory.

That reduced the duration to less than half, using default values ( test executors = [processor count](http://nunit.org/index.php?p=levelOfParallelism&r=3.0) ). 
Now in my machine one processor is 100% (was 25%), but the other is not, so maybe we can tweak that a bit.

I think we can try to configure the others nunit test suites too, that should give a good speedup in `appveyor-build.cmd`.

About tests, current status:

summary post

I'll details each failure because i think i need a bit of help /cc @KevinRansom @dsyme

**Comment by enricosada** [comment]
About `core/members/basics`

The bat files concat a list of files inside the directory, there is SOURCES = `test.fsi test.fs`

the command the bat runner execute is:

```batch
fsiAnyCPU.exe  -r:System.Core.dll --nowarn:20 --define:INTERACTIVE --maxerrors:1 --abortonerror  < test.fsi test.fs 
```

the problem is 
`fsiAnyCPU.exe < test.fsi test.fs` 
because how redirect works, from command line execute like
`fsiAnyCPU.exe test.fs`
so fsi load the `test.fs` ( fsi print `[Loading tests\fsharp\core\members\basics\test.fs]` ), and that works.

if i try to execute

`fsiAnyCPU.exe  -r:System.Core.dll --nowarn:20 --define:INTERACTIVE --maxerrors:1 --abortonerror < test.fs`

that fails (like in the nunit test runner)

```
warning FS0075: The command-line option '--abortonerror' is for test purposes only

Microsoft (R) F# Interactive version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

>
  #nowarn "62"
  ^

stdin(5,1): error FS0010: Unexpected start of structured construct in definition
. Expected '=' or other token.
```

So the nunit runner is correct, the STDIN redirect tests should fail.

**Comment by KevinRansom** [comment]
@enricosada 
We have a paid OSS account and so we get two cores, so parallel testing on appveyor should take that into account.

**Comment by enricosada** [comment]
ok disabled failing tests with `NO_CI` tag

If ok to merge i'll add an issue about these

**Comment by enricosada** [comment]
ready to review :smile:

**Comment by enricosada** [comment]
I know @KevinRansom you have done lot of merge today, but if you can check this one, i'd like to use the fix in coreclr branch and in openfsharp ( we can get some help to fix OS X/Linux useful for coreclr too )

**Comment by ctaggart** [comment]
:+1:

**Comment by KevinRansom** [comment]
Thanks for taking care of this merged into master/vs2015/coreclr

**Pull request closed without merging**
