### PR TITLE
use .NET SDK 2.1.201 to build FCS

### PR DESCRIPTION
**Pull request by dsyme**
Simple update to use 2.1.201 when building FCS

### CODE REVIEW

**Comment by dsyme** [comment]
This SDK update is causing a failure when compiling .NET 4.5 binaries on Linux. It's unclear if the problem is with Mono or the .NET SDK or our project files:

The error is:
```
     5>/tmp/.NETFramework,Version=v4.5.AssemblyAttributes.fs(2,26): error FS1108: The type 'ValueType' is required here and is unavailable. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. [/mnt/j/w/Microsoft_visualfsharp/master/release_fcs_ubuntu16.04_prtest/fcs/FSharp.Compiler.Service.ProjectCrackerTool/FSharp.Compiler.Service.ProjectCrackerTool.fsproj]
```
The CoreCompile is:
```
         /home/dotnet-bot/.local/share/dotnetcore/sdk/2.1.201/FSharp/RunFsc.sh -o:obj/Release/net45/FSharp.Compiler.Service.ProjectCrackerTool.exe
         --debug:portable
         --noframework
         --define:TRACE
         --define:CROSS_PLATFORM_COMPILER
         --define:ENABLE_MONO_SUPPORT
         --define:RELEASE
         --define:NET45
         --optimize+
         -r:/home/dotnet-bot/.nuget/packages/fsharp.core/4.1.19/lib/net45/FSharp.Core.dll
         -r:/mnt/j/w/Microsoft_visualfsharp/master/release_fcs_ubuntu16.04_prtest/fcs/FSharp.Compiler.Service.ProjectCrackerTool/../../src/../fcs/dependencies/MSBuild.v12.0/Microsoft.Build.dll
         -r:/mnt/j/w/Microsoft_visualfsharp/master/release_fcs_ubuntu16.04_prtest/fcs/FSharp.Compiler.Service.ProjectCrackerTool/../../src/../fcs/dependencies/MSBuild.v12.0/Microsoft.Build.Engine.dll
         -r:/mnt/j/w/Microsoft_visualfsharp/master/release_fcs_ubuntu16.04_prtest/fcs/FSharp.Compiler.Service.ProjectCrackerTool/../../src/../fcs/dependencies/MSBuild.v12.0/Microsoft.Build.Framework.dll
         -r:/mnt/j/w/Microsoft_visualfsharp/master/release_fcs_ubuntu16.04_prtest/fcs/FSharp.Compiler.Service.ProjectCrackerTool/../../src/../fcs/dependencies/MSBuild.v12.0/Microsoft.Build.Tasks.v12.0.dll
         -r:/mnt/j/w/Microsoft_visualfsharp/master/release_fcs_ubuntu16.04_prtest/fcs/FSharp.Compiler.Service.ProjectCrackerTool/../../src/../fcs/dependencies/MSBuild.v12.0/Microsoft.Build.Utilities.v12.0.dll
         -r:/usr/lib/mono/4.5-api/mscorlib.dll
         -r:/usr/lib/mono/4.5-api/System.Core.dll
         -r:/usr/lib/mono/4.5-api/System.Data.dll
         -r:/usr/lib/mono/4.5-api/System.dll
         -r:/usr/lib/mono/4.5-api/System.Drawing.dll
         -r:/usr/lib/mono/4.5-api/System.IO.Compression.FileSystem.dll
         -r:/usr/lib/mono/4.5-api/System.Numerics.dll
         -r:/usr/lib/mono/4.5-api/System.Runtime.Serialization.dll
         -r:/home/dotnet-bot/.nuget/packages/system.valuetuple/4.3.1/lib/netstandard1.0/System.ValueTuple.dll
         -r:/usr/lib/mono/4.5-api/System.Xml.dll
         -r:/usr/lib/mono/4.5-api/System.Xml.Linq.dll
         --target:exe
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --subsystemversion:6.00
         --highentropyva+
         --targetprofile:mscorlib
         --version:22.0.3
         --staticlink:FSharp.Core
         --simpleresolution
         --nocopyfsharpcore
         /tmp/.NETFramework,Version=v4.5.AssemblyAttributes.fs
         ProjectCrackerOptions.fs
         ProjectCrackerTool.fs
         Program.fs
```

**Comment by cartermp** [comment]
Link #5023

**Comment by haf** [comment]
How do I get this fix?

**Comment by haf** [comment]
Will this fix:

```
"/Users/h/dev/logibit/logary/src/Logary.sln" (default target) (1) ->
"/Users/h/dev/logibit/logary/src/services/Logary.Services.Rutta.Tests/Logary.Services.Rutta.Tests.fsproj" (default target) (47) ->
"/Users/h/dev/logibit/logary/src/services/Logary.Services.Rutta.Tests/Logary.Services.Rutta.Tests.fsproj" (Build target) (47:2) ->
  /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.Common.Mono.After.targets(37,9): warning MSB3912: INTERNAL WARNING: Could not find the replacement assembly (System.Globalization.Extensions.dll) for the Windows specific reference /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/xbuild/Microsoft/Microsoft.NET.Build.Extensions/net461/lib/System.Globalization.Extensions.dll. Please file a bug report at https://bugzilla.xamarin.com . [/Users/h/dev/logibit/logary/src/services/Logary.Services.Rutta.Tests/Logary.Services.Rutta.Tests.fsproj]
  /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/xbuild/15.0/Microsoft.Common.targets/ImportAfter/Microsoft.Common.Mono.After.targets(37,9): warning MSB3912: INTERNAL WARNING: Could not find the replacement assembly (System.Threading.Overlapped.dll) for the Windows specific reference /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/xbuild/Microsoft/Microsoft.NET.Build.Extensions/net461/lib/System.Threading.Overlapped.dll. Please file a bug report at https://bugzilla.xamarin.com . [/Users/h/dev/logibit/logary/src/services/Logary.Services.Rutta.Tests/Logary.Services.Rutta.Tests.fsproj]
```

as well?

**Comment by haf** [comment]
Do you think your organisation could set up a CI build of Logary with the SDK and latest F#? I keep running into compiler problems when maintaining the project. Furthermore, the project has a heap of dependencies and is a pretty good smoke test. I know I've asked for this of Xamarin before, but they've always ignored the possibility.

**Comment by dsyme** [comment]
@haf I don't think this will fix any specific issue - the fix here is just to manually reference some facade DLLs when using the .NET SDK to compile .NET 4.x code on Linux

> Will this fix .. as well?

No, that looks unrelated

**Comment by haf** [comment]
> the fix here is just to manually reference some facade DLLs

So in this case, I have this fsproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\netfx.props" />
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <AssemblyName>Xenogloss</AssemblyName>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\paket-files\fsprojects\FSharp.TypeProviders.StarterPack\src\ProvidedTypes.fsi">
      <Paket>True</Paket>
      <Link>ProvidedTypes/ProvidedTypes.fsi</Link>
    </Compile>
    <Compile Include="..\..\..\paket-files\fsprojects\FSharp.TypeProviders.StarterPack\src\ProvidedTypes.fs">
      <Paket>True</Paket>
      <Link>ProvidedTypes/ProvidedTypes.fs</Link>
    </Compile>
    <Compile Include="..\..\..\paket-files\logibit\EmParsec\EmParsec.fs">
      <Paket>True</Paket>
      <Link>EmParsec/EmParsec.fs</Link>
    </Compile>
    <Compile Include="AssemblyInfo.fs" Condition="Exists('AssemblyInfo.fs')" />
    <Compile Include="Core.fs" />
    <Compile Include="Xliff.fs" />
    <Compile Include="Icu.fs" />
    <Compile Include="Render.fs" />
    <Compile Include="MessageInfoEx.fs" />
    <Compile Include="Xenogloss.fs" />
    <None Include="paket.references" />
    <Reference Include="System.Globalization" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
```

With this warning at compile time:

```
/usr/local/share/dotnet/sdk/2.1.105/Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Globalization". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/Users/h/dev/logibit/qvitoo.api/src/libs/Xenogloss/Xenogloss.fsproj]
/usr/local/share/dotnet/sdk/2.1.105/Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3243: No way to resolve conflict between "System.Globalization, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Globalization". Choosing "System.Globalization, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily. [/Users/h/dev/logibit/qvitoo.api/src/libs/Xenogloss/Xenogloss.fsproj]
```

Shouldn't it be enough just to manually add the above ref to System.Globalization?

**Comment by cartermp** [comment]
From the new Logary license:

> Usage together with ASP.Net/Kestrel/Internet Information Services (IIS) or in conjunction with any/all Microsoft web stacks requires a commercial license.

Does this meany one or more of the following?

* May not be used such that Logary is called from a project that runs on a Microsoft web stack
* May not be used in a solution where a Microsoft web stack also runs, even if the logging is called only from a non-Microsoft component
* May not be included in a solution as a package reference, even if unused, where one or more components has a Microsoft web stack
* May not be used in a solution that uses the .NET Core SDK, as the SDK itself bundles ASP.NET Core

With the license change, considering something like [running logary as a part of F# and .NET Core validation](https://github.com/Microsoft/visualfsharp/pull/5025#issuecomment-393094326) sounds like it may be problematic. I agree that it would make a good smoke test, and although adding it to CI may not necessarily be on the table, it's trivial for me to add a web project that uses Logary in a few ways to our existing daily manual scenario-based validation for F# and .NET Core. In such an arrangement, I'd like file an issue when something comes up and it's not clear that the issue lies in something we or the .NET Core team can control.

**Comment by haf** [comment]
It can be used on all of those scenarios with a commercial license, but without one, only your first point. If you're open to running it as a CI setup I can give you a license to do that?

**Pull request merged**
