### PR TITLE
Add dotnet-ci Integration

### PR DESCRIPTION
**Pull request by otawfik-ms**
@mmitche

### CODE REVIEW

**Comment by otawfik-ms** [comment]
test ci please

**Comment by mmitche** [comment]
LGTM

**Comment by forki** [comment]
Groovy?

**Comment by smoothdeveloper** [comment]
@forki apparently continuous integration is jenkins based: https://github.com/dotnet/dotnet-ci/blob/master/docs/CI-SETUP.md#how-does-the-net-ci-model-work

**Comment by forki** [comment]
Yep.

I hope we can keep it as a super thin layer that shells out. Sad that they
don't use yaml like the other CI servers.

(also sad that we didn't get FAKE in...)

**Comment by mmitche** [comment]
@forki That's mostly because the job DSL language that creates jobs is in groovy.  You could put a yaml layer on top of it if you wanted to though.  However, the power of the scripting language is the ability to create wide combinations of jobs in relatively little code.  For instance, CoreFx and CoreCLR have around a hundred jobs apiece.  There are workflows that run on multiple machines, etc.  This is a lot easier to do in the scripting language.

**Comment by forki** [comment]
I don't question the power of a scripting language. forget about the comment ;-)

**Comment by mmitche** [comment]
@forki I will say that for 'simple' workflows though, the yaml approach is better, but working with what we have :)

**Comment by enricosada** [comment]
README badges!!!! :smile:

**Comment by enricosada** [comment]
@forki jenkins has lot of options, depends on plugins, from ui based to groovy.
For example i really like the [literate plugin](https://wiki.jenkins-ci.org/display/JENKINS/Literate+Plugin) using a md file, for simple workflow

It really depends on what jenkins plugin you use for build matrix, versioning, artifacts, etc, but the flow is always the same, a build script inside repo is called after the jenkins job choose parameters.

Maybe with better build scripts... :smile:

**Pull request merged**
