### PR TITLE
Revert - [RFCs FS-1037] allow flexible inference (subsumption) at union construction #5030 

### PR DESCRIPTION
**Pull request by KevinRansom**
Test case for reversion because it broke overload resolution

Should fail.

### CODE REVIEW

**Comment by cartermp** [comment]
Link #5246

**Comment by KevinRansom** [comment]
Sweet … correctly fails, lets do the revert now.

````
1) Failed : FSharp-Tests-Core+RegressionTests.OverloadResolution-bug-FSC_BASIC
Error running command 'D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\..\..\release\net40\bin\fsc.exe' with args '-r:System.Core.dll --nowarn:20 --define:COMPILED --optimize+ --debug -o:test--optplus--debug.exe -g test.fs' in directory 'D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\regression\OverloadResolution-bug'.
---- stdout below --- 
Microsoft (R) F# Compiler version 10.2.0 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.

---- stderr below --- 
1 . ERRORLEVEL 1
at TestFramework.checkResult(CmdResult result) in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\test-framework.fs:line 235
at TestFramework.exec@417-24.Invoke(CmdResult result) in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\test-framework.fs:line 417
at TestFramework.fsc@425-1.Invoke(String flags, FSharpList`1 srcFiles) in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\test-framework.fs:line 425
at SingleTest.singleTestBuildAndRunCore(TestConfig cfg, String copyFiles, Permutation p) in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\single-test.fs:line 149
at FSharp-Tests-Core.RegressionTests.OverloadResolution-bug-FSC_BASIC() in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\tests.fs:line 1634

2) Failed : FSharp-Tests-Core+RegressionTests.OverloadResolution-bug-FSI_BASIC
Error running command 'D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\..\..\release\net40\bin\fsi.exe' with args '-r:System.Core.dll --nowarn:20 --define:INTERACTIVE --maxerrors:1 --abortonerror test.fs' in directory 'D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\regression\OverloadResolution-bug'.
---- stdout below --- 

Microsoft (R) F# Interactive version 10.2.0 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

[Loading D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\regression\OverloadResolution-bug\test.fs]

---- stderr below --- 
1 . ERRORLEVEL 1
at TestFramework.checkResult(CmdResult result) in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\test-framework.fs:line 235
at TestFramework.exec@417-24.Invoke(CmdResult result) in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\test-framework.fs:line 417
at TestFramework.fsi@435-3.Invoke(String flags, FSharpList`1 sources) in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\test-framework.fs:line 435
at SingleTest.singleTestBuildAndRunCore(TestConfig cfg, String copyFiles, Permutation p) in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\single-test.fs:line 96
at FSharp-Tests-Core.RegressionTests.OverloadResolution-bug-FSI_BASIC() in D:\j\w\release_ci_pa---b76f5d70\tests\fsharp\tests.fs:line 1637
````

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build  please

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Comment by cartermp** [comment]
test Ubuntu16.04 Release_default Build

**Comment by KevinRansom** [comment]
test Ubuntu16.04 Release_default Build

**Comment by cartermp** [comment]
Mono keeps crashing on the CI server. In the essence of time, I suggest just merging this anyways.

**Pull request merged**
