### PR TITLE
Check constructor in FSharpMemberOrFunctionOrValue(SymbolEnv, MethInfo)

### PR DESCRIPTION
**Pull request by auduchinok**
Covers few cases in FSharpMemberOrFunctionOrValue where MethInfo param can be a constructor.

### CODE REVIEW

**Comment by dsyme** [comment]
Are there test cases which show the difference in behaviour? thanks

**Comment by KevinRansom** [comment]
@auduchinok it would be helpful, if you can add some tests.  
Thanks.

Kevin

**Comment by auduchinok** [comment]
@dsyme @KevinRansom Sorry, it got merged before I read these comments. I'll add some tests as a part of #6711 or a separate PR.

**Comment by dsyme** [comment]
@auduchinok Thanks

@KevinRansom Please make sure all adjustments to the behavior of the FCS API have tests before merging - especially those parts of the API which aren't exercised by the Visual F# Tools.

**Pull request merged**
