### PR TITLE
use index comparison instead of pointer comparison

### PR DESCRIPTION
**Pull request by chillitom**

### CODE REVIEW

**Comment by forki** [comment]
this will change the type of the result right?

**Comment by forki** [comment]
Ok this is now using 2 additional List operations. Not sure if that's buying us anything. But maybe if you recator the usage directly below as well...

**Comment by chillitom** [comment]
yep you're right, flying blind here a little as can't get the solution to build.  Also would it be more efficient to use Seq.choose, Seq.forall, Seq.map and then List.ofSeq?  If any of this is useful i'll squash these commits to keep things pretty.

**Comment by forki** [comment]
> as can't get the solution to build

why not? can you please open an issue with the error you are seeing?

also since this PR will probably become bigger can you please sign https://cla.microsoft.com/
thanks!

**Comment by chillitom** [comment]
I don't see how the indexed list can be of use in the rest of the function, am I missing something?

Could decide that pointer comparison is acceptable, maybe moving it into the better function so the decision is made in one place..
```
                let better (candidate:CalledMeth<_>, candidateWarnCount, _) (other:CalledMeth<_>, otherWarnCount, _) = 

                    // include candidate in results
                    if candidate === other then 1 else
```
Alternatively we could use the list index as in this PR at the cost of a List.indexed operation.

Or just forget about it altogether, it works as is and to be honest isn't particularly ugly or sinful.

**Comment by dsyme** [comment]
Thanks @chillitom  - a great first contribution, always good to get rid of these warts :)

**Pull request merged**
