### PR TITLE
Enable gcAllowVeryLargeObjects on FsiAnyCpu

### LINKED ISSUE #100: Enable gcAllowVeryLargeObjects for fsiAnyCpu
Setting app config for 64-bit fsi (fsiAnyCpu.exe) to handle very large arrays could unblock handling of large datasets in fsi with default settings. See  docs for description of gcAllowVeryLargeObjects. 

See also
- [http://richardminerich.com/tag/gcallowverylargeobjects/](http://richardminerich.com/tag/gcallowverylargeobjects/)
- [http://www.centerspace.net/blog/nmath/large-matrices-and-vectors/](http://www.centerspace.net/blog/nmath/large-matrices-and-vectors/)

### PR DESCRIPTION
**Pull request by saul**
Fixes #100.

The documentation for this feature states:

> Before enabling this feature, ensure that your application does not include unsafe code that assumes that all arrays are smaller than 2 GB in size. For example, unsafe code that uses arrays as buffers might be susceptible to buffer overruns if it is written on the assumption that arrays will not exceed 2 GB.

I had a scan through the FSI code and took a look through the rest of the solution but found nothing of the sort.

### CODE REVIEW

**Comment by KevinRansom** [comment]
I believe the warning applies also to libraries that are referenced using #r.   I wonder whether this should be the only choice for 64 bit FSI or should it be an IDE option?

**Comment by saul** [comment]
Kevin if that's the case, then can't the user remove that line from the app config in the same way users currently add it?

I can't imagine libraries that are assuming the maximum sizes of arrays are plentiful, especially so ones that are used often. Even if it were the case, it sounds like a bug with the library as opposed to FSI.

**Comment by KevinRansom** [comment]
@saul 
The thing is I don't really know why the default for 64 bit CLR apps is off.  I will root around upstairs and see if I can find someone who can give me a cogent explanation.  I can think of a few possibilities ... however, the ones I come up with in my head don't really hold water.

Without a decent explanation I don't know that I feel comfortable changing the default for FSI.  Now I would be fine if there was an option in the VS tools to easily switch it.

As for whether it's a bug or not in the library, it could be.  However, it's a bug that an app developer would have to go out of his way to provoke, and so it may just be a thing.

I would also guess that as well as switching the flag an ngen would be required for anything that is ngened.   Anyway, let me have a root around and see if I can find ut why the default is the way it is.

Kevin

**Comment by KevinRansom** [comment]
@jankotas

Hey Jan do you have any idea why the default for the 64 bit managed process gc has allow very large object false?

Are there performance or compatability penalties associated with this option? 

Thanks

Kevin

**Comment by KevinRansom** [comment]
@saul 

I chatted with Vance.  We can't think of any real issue with enabling this always in 64 bit FSI.

**Comment by KevinRansom** [comment]
@saul 

Thank you for pushing on this.

Kevin

**Pull request merged**
