### PR TITLE
Re-enable FCS build on Jenkins Ubuntu

### PR DESCRIPTION
**Pull request by dsyme**
As part of #4368 I had to disable the FCS build on Jenkins Ubuntu due to Mono version. This should now be addressed since moving to Ubuntu 16.04

### CODE REVIEW

**Comment by dsyme** [comment]
I ended up having to 

1. simplify a .NET-SDK a few more project files under `fcs`
2.  find a solution for https://github.com/dotnet/sdk/issues/335 (where `dotnet` can't build .NET Framework projects out of the box on Linux/OSX - you can workaround by pointing it to the right reference assemblies).

The good news is that **all** of the following now work on **both** OSX and Windows (CI will test Linux) and all of them build/test/pack **both** netstandard2.0/netcoreapp2.0 and net45/net46.  

    dotnet restore fcs/FSharp.Compiler.Service.sln
    dotnet build fcs/FSharp.Compiler.Service.sln
    dotnet test fcs/FSharp.Compiler.Service.Tests/FSharp.Compiler.Service.Tests.fsproj
    dotnet pack fcs/FSharp.Compiler.Service.sln

**Comment by dsyme** [comment]
@dotnet-bot Test Ubuntu16.04 Release_default Build please

**Comment by dsyme** [comment]
WiIl merge, it's all fcs/...

**Comment by forki** [comment]
Awesome. Thanks for that

Am 27.02.2018 01:56 schrieb "Don Syme" <notifications@github.com>:

**Pull request merged**
