### PR TITLE
Improved project folder support

### LINKED ISSUE #2048: Ctrl-X/Ctrl-V causing NullReferenceException, load errors on next start, invalid file reference compile order in *.fsproj
If your `fsproj` file contains two or more references to a file in a folder and between those files there's an item from another folder or from the root, the project file cannot be opened. 

In other words, using regular commands or menu actions, the `fsproj` file can get corrupted like as follows, which **compiles fine but cannot be opened in Visual Studio**:

1. `somefolder\source1.fs`
2. `source2.fs`
3. `somefolder\source3.fs`

Detailed (and, even though there's a lot of text, quite straightforward) repros follow: 

### "Manual" repro method:

1. Create a project, add three `*.fs` files to the project next to the default `Program.fs`
2. Create a folder (either manually and refresh, or use the Powertools extension to create a folder)
3. Move two `*.fs` files to the folder (either manually, or again using the FS Powertools _"Move to folder"_ command)
4. Open the `*.fsproj` file for editing and put the remaining file in the root (from step (1)) between the two files in the folder. Your `fsproj` file looks something like this:

```
<Compile Include="New\One.fs" />
<Compile Include="Three.fs" />
<Compile Include="New\Two.fs" />
<Compile Include="Program.fs" />
```

Reopening the project is now impossible and you'll receive an error.

### "Accidental" repro method

This is one of many ways to accidentally get to the same as above, this works without any addins installed (i.e., in SafeMode).

1. Create a project by step 1-3 above
2. Select and Ctrl-X a file from the root
3. Select the folder and Ctrl-V the file

You will now get a popup "Object reference not set to an object", i.e., a `NullReferenceException`.

You will also see that the `Ctrl-X` had no effect, it acted as a `Ctrl-C` (copy) and paste. The filename will have `Copy of` prepended, even though that is not necessary as it appears in a new folder.

4. Save the project (Ctrl-Shift-S)
5. Reopen the project (either close VS or reload in solution explorer)
6. Same error as before will pop up now
7. If you inspect the `fsproj` file you will find the `copy of` file on top of all file references

#### Remarks/alternates/related bugs

1. If, between step 4 and 5 above you would empty the copied file (put an empty namespace + module in it), the solution compiles
2. If, after successful compilation, you would try to reopen the solution, the same error shows up
3. Doing Ctrl-C/Ctrl-V with any file in a folder shows the file at the bottom of the folder, raises `NullReferenceException` and places the new reference on top in the `fsproj` file (leading to load errors next time)
4. Same as (3), doing Ctrl-X/Ctrl-V in a folder has the same effect
5. Doing Ctrl-C/Ctrl-V or Ctrl-X/Ctrl-V in the root folder shows that file at the bottom in solution explorer, but places the copied file on the top in the `fsproj` file. No load errors (but possible compile errors)
6. **Suprisingly**, doing the Ctrl-C/Ctrl-V with a file from a _different_ project within the same solution works correctly (places it at the bottom of selected folder, or root folder, both in solution explorer and `fsproj` file)

#### Notes:

1. There are many ways to accidentally come to this situation (but I don't recall them all and some are caused by NuGet adding files, or plugins doing their "magic")
2. It seems to be impossible to properly to copy/paste or cut/paste, however it _appears_ to be supported when you use these keys

## Expected behavior

1. The `NullReferenceException` should not happen, for sure. The other error is surprising, especially if it is possible to have a loaded project that compiles, and that, upon reopening, is invalid.
2. The popup error on _"Rendering a folder multiple times"_ makes sense (if the `fsproj` file is improperly edited), except that it can be made clearer.
3. The same popup error does not make sense if you do "normal" copy/paste in the solution folder
4. If the project compiles, you would expect it to also load if you reopen it
5. Ctrl-X / Ctrl-V should **cut-n-paste** the file, not **copy-n-paste**
6. The expected location in a folder is above the selected file in the selected folder (same as C# projects), or at the bottom in the selected folder if the folder is selected and not an actual file.

## Actual behavior

(the following items correspond numerically with the ones under _Expected behavior_)

1. If you Ctrl-X/Ctrl-V you see this (reminiscent of a `NullReferenceException`):

    image

2. You see errors when reloading:
    1. You get the following error in a popup when you reopen or reload such project:

        > The project 'Experiments.fsproj' could not be opened because opening it would cause a folder to be rendered multiple times in the solution explorer. One such problematic item is 'New\Two.fs'. To open this project in Visual Studio, first edit the project file and fix the problem.

        image

    2. In the solution explorer you'll see the following:

        image

4. An invalid project file compiles fine
5. Ctrl-X does not cut, it leaves the original file in place and copies instead
6. The location shown in Solution Explorer does not match the location in the `fsproj` file
    1. The location in the `fsproj` file is invalid
    2. Reopening the solution throws an error (see above)
    3. Or reopening does not throw an error but shows a different order of the files in the solution explorer

## Known workarounds

1. Fix the `fsproj` file manually by reordering the items or removing the offending ones.
2. Do not use `Ctrl-X/Ctrl-V` or `Ctrl-C/Ctrl-V` or the corresponding menu items
3. Whenever you need to reorder items in the solution explorer, do it manually (open the `fsproj` file and rearrange the items, and at the same time rearrange them on disk)
4. Basically: be very careful before you rely on the solution explorer and use a good version control system to be able to rollback easily any inadvertently edited and wronged `fsproj` files.

## Related information 

I have written two repro ways above, though it is possible this has been reported and/or is reproducible with different repro steps. 

I realize this error is caused by Visual Studio not being able to render a directory multiple times (it would lead to two identical directory entries in the solution explorer). I don't know if this can be resolved by the F# team. However, the root cause of this error can definitely be mitigated, i.e. by making sure that Ctrl-X / Ctrl-V either works correctly, or doesn't work at all (drop the feature).

### Worries

While there is something to say for the error to popup (apart from the NRE), being able to continue working when the error _does not popup_ means you can edit in an incorrect environment for a long time, which may lead to hard-to-resolve issues later (apart from the surprise when you find you cannot reopen your project).

### Suggestions

If we have influence on the error, I would like to discuss a better text. If not, we should strive to prevent it from happening in the first place.

Reproducible:

* With Visual Studio 2015, F# 3.x / 4.x, Update 1-3

### LINKED ISSUE #2178: Adding new or existing items to folders in the Solution Explorer is broken
#### Repro steps

1. Select a file that is within a folder node in the Solution Explorer
2. Right-click, Add Above|Before > New Item

#### Expected behavior

File is created in the folder.

#### Actual behavior

File is added to the end of the project. If you look in the project file, the <Compile> element is added to the correct place, but as the file is created at the project root, doesn't work.

For example, if I were to select Foo.fs and add a new file below called Qux.fs, the project file would look like:

```
<Compile Include="Folder\Foo.fs">
<Compile Include="Qux.fs">
<Compile Include="Folder\Bar.fs">
```

#### Repro steps

1. Select the project node in the Solution Explorer
2. Right-click, Add > New/Existing Item
3. Add a file in a folder

#### Expected behavior

File is created in/added from the folder.

#### Actual behavior

File is added to the end of the project, but does not include the folder.

## Known workarounds

Create the file outside of VS and manually update the project file :(

## Related information 

Affects VS 2015 and VS 2017 RC and master (not sure about pre 2015).

### PR DESCRIPTION
**Pull request by saul**
Fixes #2178, #2048, #2539, #1095 and #732

## Folder node selected

- Add Above
  - [x] ✨ Add New: **added support**
  - [x] ✨ Add Existing: **added support**
  - [x] ✨ Add Folder **added support**
- Add Below
  - [x] ✨ Add New: **added support**
  - [x] ✨ Add Existing: **added support**
  - [x] ✨ Add Folder **added support**
- [x] ✨ Add Above/Add Below on an empty folder

## File node selected

- Add Above
  - Add New
    - [x] 🐞 Within sub-folder: **fixed**
    - [x] At root: already supported
  - Add Existing
    - [x] 🐞 Within sub-folder: **fixed**
    - [x] At root: already supported
- Add Below
  - Add New
    - [x] 🐞 Within sub-folder: **fixed**
    - [x] At root: already supported
  - Add Existing
    - [x] 🐞 Within sub-folder: **fixed**
    - [x] At root: already supported

## Cut & Paste

copy and paste

- [x] 🐞 Fix null reference exceptions (#2048) **fixed**
- [x] 🐞 Ctrl+X, Ctrl+V adds "Copy ..." prefix to filename **fixed**
- [x] 🐞 Solution Explorer/fsproj order is mismatched on paste **fixed**

## Add > Add Existing...

create intermediate

- [x] 🐞 *Add > Add Existing...* on the project node should place the file in the correct subfolder **fixed**
- [x] ✨  *Add > Add Existing...* anywhere in the project tree should place the file in the correct subfolder **added**
- [x] ✨  *Add > Add Existing...* should create any necessary intermediate directories **added**
- [x] 🐞  *Add > Add Existing...* now works with files that are outside of the project hierarchy **fixed**

## "Add Folder"

new folder

- [x] ✨ *Add Above/Below > New Folder* menu item **added**
- [x] ✨ Enable "Add Folder" on project node **added**

## Miscellaneous

- [x] 🐞 Better support for non-Windows style directory separators in .fsproj **fixed**
- [x] ✨ *Add Above/Below > Add Existing...* should fail early if the file is in a different subtree **added**
- [x] 🔬 Test multiple folders with the same name
- [x] 🔬 Fix all bugs with linked files
- [x] ✨ If the folder exists on disk, use it instead of throwing an error
- [x] 🐞 Deleting a folder with links to files elsewhere on disk is deleting those files

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
This is great.

No "Add folder" menu

image

**Comment by saul** [comment]
@vasily-kirichenko is that a feature request or a regression? :)

**Comment by vasily-kirichenko** [comment]
That was a feature request :)

"Add new item" into a folder adds it to the end in the project file:

image

image

**Comment by vasily-kirichenko** [comment]
...then I tried to move `File1.fs` up:

image

**Comment by saul** [comment]
Ah. I know why this is. The path separators need to be backslash

**Comment by vasily-kirichenko** [comment]
So... I think it should work with both types of slashes since it's very likely `/` is used on linux and mac (if you open a project created in, say, Xamarin on Mac).

**Comment by dsyme** [comment]
Wow, it would be great to get this in.

**Comment by cloudRoutine** [comment]
right now it'll put it in the right folder if you click on the folder itself and do add item

**Comment by vasily-kirichenko** [comment]
@cloudRoutine that's what I did.

**Comment by cloudRoutine** [comment]
¯\\\_(ツ)\_/¯
it hasn't happened to me once in the last 10 times I built and launched it on this branch

**Comment by cloudRoutine** [comment]
bizarre, this is the only way that works consistently for me

**Comment by saul** [comment]
@cloudRoutine it's because Vasily had Linux-style directory separators in some of the files in his .fsproj - I'm fixing that now

**Comment by saul** [comment]
@vasily-kirichenko @cloudRoutine fixed in 4d33380

I've also just re-enabled support for "Add folder" on the project node:
empty folder

**Comment by forki** [comment]
Wow this is so cool. Thanks so much for doing this.

**Comment by vasily-kirichenko** [comment]
awesome! will test it tomorrow.

**Comment by saul** [comment]
Just fixed cut/copy and pasting files around:

copy and paste

cc @abelbraaksma

**Comment by cartermp** [comment]
@saul You're a rockstar.  Love it!

**Comment by vasily-kirichenko** [comment]
@saul everything works great. Very cool :) Any plans to add drag-n-drop support? :)

**Comment by forki** [comment]
Can we try to get the first batch in? It would immediately be helpful. Further improvements like draggedy-droppery-mousy-minkie could be added in another PR.

**Comment by saul** [comment]
@forki my plan is to just fix the stuff that's there for the minute (see my incomplete check boxes in the PR description

**Comment by saul** [comment]
A bit more progress - coming close for this to be merged.

I've reworked how the Solution Explorer and project file are synchronised. Any operation on a file in the Solution Explorer is no longer attempted to be 'replayed' on the project file (e.g adding a file to the Solution Explorer would try to move it to where we expected it in the project file). Instead, the file is added to the Solution Explorer to the most reasonable place, and then moved elsewhere if possible. Wherever the file ends up, the build project will replicate. This means it should no longer be possible for the Solution Explorer and project file to become 'out of sync'.

An example error is shown below:

**Comment by saul** [comment]
@vasily-kirichenko as requested :)

new folder

**Comment by saul** [comment]
@KevinRansom @cartermp expecting 8dd0672 to go green, this PR is now ready to merge

**Comment by saul** [comment]
Agh I'm a fool. I'll get to this tomorrow evening - it looks like a surface API change. The tests run so slowly on my laptop

**Comment by cloudRoutine** [comment]
when I went to add a group of files as links to a folder they were added both to the folder and at the top of the item group causing the dreaded VS "unable to render" error

**Comment by saul** [comment]
@cloudRoutine do you have exact repro steps? I'll take a look

**Comment by cloudRoutine** [comment]
i clicked on the folder, add existing item, selected 4 files and did add as link

**Comment by saul** [comment]
@KevinRansom @cartermp @dsyme I'm not sure how to proceed with the "Add Existing" functionality.

In C#, when you "Add Existing" on the project node or a folder node, it *copies* the file to either the project root/the folder you had selected in the Solution Explorer.

With this PR, "Add Existing" will create the folder structure in the Solution Explorer if it doesn't already exist. It no longer copies files to the folder. I'm planning on making a change whereby files that are *outside* of the project directory will be copied.

If we do decide to copy the files to the folder you selected in the Solution Explorer, we need to think how you would add an existing file that is in a pre-existing folder structure to the Solution Explorer. There is no way currently in VF# (or C#) to do this.

**Comment by saul** [comment]
@cloudRoutine latest commit fixes linked files

**Comment by cloudRoutine** [comment]
excellent 👍 
do you think it'd be possible to move a contiguous selection of files as a block? Sure there won't be that many time when you want to move a large amount of files, but signatures and implementations have to stay in order and adjacent to one another, so it'd be good for moving them together.

**Comment by KevinRansom** [comment]
So this is great ... however, when we migrate to CPS ... much of this code will need to be ported to that.

One thing I would really like you to think about is how in a tree with folders do we make it possible for developers to specify the exact file ordering.  This has long been the real issue with enabling this and I'm not certain I know what what the answer is.

**Comment by saul** [comment]
@KevinRansom I think I've already got a solution that means we can use the standard Solution Explorer, have a fixed compile order and allow files to be specified in any order. 

Underneath the "References" node in the Solution Explorer, we should have a "Compilation Order" node. This node contains a flat list of <Compile Include="..."> files - in the exact order that they're in the MSBuild file, including their relative paths. 

The rest of the Solution Explorer is just as a C# project - we can use this as is. We just need to make sure that when a file is added, we add it to the Compilation Order node. Likewise for deletion. 

I think this method is simple, clear and solves many of the weird edge cases we have with rendering multiple folders etc. It will also be a huge boost to just use as much as Roslyn's project system as possible without us having to hack around it for our snowflake compilation. 

Thoughts? :)

**Comment by smoothdeveloper** [comment]
@saul I like the idea of having a node with all files listed in a list, right in the solution explorer rather than a tab in project settings, and having this be independant of the physical file structure which we can show like C#.

Can we still consider defining logical groups in that list (through `ItemGroup` nodes?), this will be helpful for bigger projects, you can see how fsharp compiler projects are laid out, and having a single flat list will be cumbersome when the number of files becomes large.

Files should have their relative path to the project file, and maybe we'd need another way for linked files.

In C#, there is a Properties node, maybe it is a better fit than under References? or maybe "Project Settings" which will hold package references, compilation order and other project level settings.

**Comment by saul** [comment]
@smoothdeveloper when I said "beneath" the References node, I meant below it - a sibling, sorry if that wasn't clear. 

I wouldn't be averse to allowing grouping, that's a neat idea. 

I've also got an idea as to how this would look UI wise. After any Add New/Add Existing, a dialog would pop up asking where you wanted to place the file in the build order. This would only appear if you added the file from the physical file structure view in the Solution Explorer. The Add Above/Add Below options would still be available in the "Compilation Order" node.

**Comment by saul** [comment]
Let's carry on the future work discussion in https://github.com/dotnet/roslyn-project-system/issues/1875

**Comment by KevinRansom** [comment]
@saul ... I think an additional tree node with a list of files giving the compilation order would work pretty well for enabling a developer to specify compilation order.  It would certainly make folders more usable, and would probably mean we don't have to push for a CPS to change the way they render project source files either.

Perhaps we can add it to the current project system, so we could all get a feel for how it works, not this PR though. it's fine as is.  I would like to see it without any grouping first, once we have usable folders then we can see what else is needed to improve it's utility. Does that make sense?

Kevin

**Comment by vasily-kirichenko** [comment]
I don't like the extra node idea. It would be a constant disturbing thing for seasoned devs and a super unusual and not obvious one - for beginners, like 'why the hell _I_ must tell the compiler in what order it should compile my files?!'. It reminds me a C# error message "You miss semicolons at the end of statement" - a thing that should be handled by compiler itself if it's smart enough to produce such a precise error message.

**Comment by KevinRansom** [comment]
@vasily-kirichenko 

like you I worry about beginners, I do believe though that seasoned F# devs are more than capable of dealing with the node, they may not like it, but they should rarely have to use it, and can always type directly into the project file as they would today.  

For beginners the node is easier to deal with than editing the project file directly, the real problem is discovery, when they need to reorder a file.  I think the prototype would help us flesh out how to improve that aspect.,

The current shipping product does not deal with folders, unless a developer edits the project file and adds it manually.  So what we have to today is perfect ... no folder or ordering issues.

When we add, as this PR seeks to do gestures for adding folders, we now have the issue of how to using the project dialog specify the order the files need to be supplied to the compiler.  File ordering is an intrinsic part of the F# language, and we still have not got a decent language proposal to address it.

I think you are really suggesting that we should change the compiler so that it doesn't require the files to be submitted in a specific order.  I would dearly love to fix that, and I think in his heart of hearts Don does too, however that is a really hard problem and so until we fix that we have an issue with how to surface that dependency in the IDE, with multiple folders in a project.

@saul has proposed a pretty decent approach, it never occurred to me to do it that way, I kept wanting to have numbers printed by each file identifying it's ordinal position which is of course silly, and one of the reasons I'm not great at designing IDE features.

**Comment by cloudRoutine** [comment]
this seems like an unnecessary constraint, if the folder exists it should just use that folder

**Comment by KevinRansom** [comment]
@cloudRoutine this happens after you have said add a folder with this name.
Surely it's helpful to tell you that the name you picked is already in-use.  Just click okay and add new files in that directory.

**Comment by cloudRoutine** [comment]
@KevinRansom that's not what's happening 

folder-fail

it won't let you use it

**Comment by cloudRoutine** [comment]
Also the folders are being created on disk before they have any contents added to them, this means that the only way to create a virtual folder inside VS is by manually editing the `.fsproj`

folder-fail2

This is not how we did it for VFPT. 
- If the folder existed on disk already we notified you that the folder existed and that it would be used. 
- If the folder didn't exist we created a virtual folder
- If you added a concrete item to a virtual folder we created a folder on disk and added the item
- If you added a linked item to a virtual folder it stayed virtual

I think this a better approach than the current functionality

**Comment by cloudRoutine** [comment]
@saul deleting a folder with links to files elsewhere on disk is deleting those files, this should not be happening under any circumstances

Either the dialog that pops up should have the option of whether you want to delete the folder and its contents (it needs to say this explicitly) or to remove the folder, or we should add another menu item to the right click menu that says `Remove`

**Comment by srivatsn** [comment]
The tree is still ordered here right? If so. how would a project that looks like below get rendered? Will the folder A show up twice? A then B and then A again?

```
   <Compile Include="A\a.fs" />
   <Compile Include="B\b.fs" />
   <Compile Include="A\c.fs" />
```

**Comment by cloudRoutine** [comment]
@srivatsn VS with throw up an error dialog, the project won't load, and you'll have to manually edit the xml so that all the files in a folder are in a contiguous block before the project can load again.  The F# compiler doesn't care, but VS does.

**Comment by saul** [comment]
@srivatsn that's the whole problem. That's why I think we should move away from this model and have an explicit "Compile Order" node instead of trying to make the folder structure view also match the compile order specified in the MSBuild file.

**Comment by cloudRoutine** [comment]
Then why even have folders at all? you need to have contiguous blocks to have logical groups that can collapse together, it's an important organizational tool

**Comment by saul** [comment]
In response to everyone's comments:

@kevinransom I'm happy to mock it out in the new project system, hopefully I'll get around to that soon

@cloudroutine I agree that the VFPT functionality makes more sense, especially around creating folders - I'll do that asap. 

@vasilykirichenko I think it makes more sense if the folder view represents the file system - that's the most natural and intuitive representation. Then the order is done separately. Nobody's complained about F# in VS Code not showing the files in the folder view in compile order - it's a restriction that gets hairy when you have folders and need a non-standard order. 

Anyway I'll get to fixing the tests on this PR and get a prototype mocked up on the new project system. 

Thanks

**Comment by forki** [comment]
> Nobody's complained about F# in VS Code not showing the files in the folder view in compile orde

I think that's not true. Many people complained but since it's an issue with VS code itself....

**Comment by vasily-kirichenko** [comment]
If solution explorer does not reflect compilation order, then it (compilation order) does not make any pros anymore and should be fixed on compiler level (no order is needed). Otherwise, it's just ridiculous restriction and fiddling files in that special folder is weird and unnatural.

**Comment by saul** [comment]
Also as I said before can we continue this discussion on https://github.com/dotnet/roslyn-project-system/issues/1875? None of this talk is related to this PR ATM and it'd be good to have it consolidated in the right place

Thanks

**Comment by forki** [comment]
Yes absolutely. Let's bring in this PR, iterate on it if needed and talk about new project system behavior in another discussion. Thanks again for the great work

**Comment by dsyme** [comment]
> ... should be fixed on compiler level (so no order is needed). 

Yes, this discussion always arises in the context of the Solution Explorer views in visual tooling.  (reasonably)

If some language/compiler addition were made it would be one of these three, I don't think there are any other options:

* [Optionally specify file order by a fileorder file](https://github.com/fsharp/fslang-suggestions/issues/95)
* [Syntactically describe dependencies between files (by using '#requires', '#load' or extending 'open' syntax) ](https://github.com/fsharp/fslang-suggestions/issues/309)
* [Allow all declarations to be mutually referential and the compiler takes files in any order](https://github.com/fsharp/fslang-suggestions/issues/7)

All three have met fierce resistance ("implicitly cyclic software by default? [no way in F#!](https://fsharpforfunandprofit.com/series/dependency-cycles.html)") or "it's just too tasteless" or "ugh it feels like header files" reactions. 

It's odd because at some level file order is "just tooling".  I think the problem is that the industry-standard visual displays very strongly bias the developer's expectations towards a relational (rather than linear-additive) view of how software is put together.  Programmers who grow up with tools with Solution-Explorer-like views find file orderings difficult to cope with, programmers who grow up with command line + editor find them more natural, but don't like implicitly cyclic software.

I wonder if we just need to be more creative in the tooling.  Perhaps it's just possible to use a different visual display and do none of the above.  For example, what if the visual tooling allowed the user to trivially switch between four views (no "extra tab", just different views)

1. alphabetical directory structure
2. alphabetical directory structure + a number added in the display indicating the position of the file order number sequence 
3. files laid out in order with directory nodes, repeating directory nodes where needed
4. files laid out in order with no directory nodes and names "A\b.fs"

Just supporting views 1 and 3 would be enough.

There's no technical reason stopping all 4 views being implemented.  It's just code. For example just because Solution Explorer implementations so far always assumed that directory nodes have unique names doesn't mean that's set in stone (which is I guess what we're discussing)

**Comment by cloudRoutine** [comment]
>  Nobody's complained about F# in VS Code not showing the files in the folder view in compile order - it's a restriction that gets hairy when you have folders and need a non-standard order.

This has been a constant and incessant complaint, we bugged the vscode team about it for months and they started working on a preview customizable node tree API that looked really nice, but we're still waiting for it to come out.

> I think it makes more sense if the folder view represents the file system - that's the most natural and intuitive representation. 

@saul did you not know that we already have that?

**Comment by lambdakris** [comment]
@dsyme Forgive me if this is a dumb idea... but for the sake of being different, would it be possible to have a process by which the compiler scans all files and figures out the file order for itself based on the dependence of types, and then a language service that editors use to validate the dependence of the types the developer is working on, such as when they are using types that are not defined (neither in the current file or in another file that would then be established as an antecedent file) or when they create a cyclical dependency (though perhaps that is where the difficulty arises, as how does the loop terminate)?

Even if my exact idea doesn't make sense, something about the idea that explicit file order is a necessary condition to avoid implicitly cyclic software seems suspicious...

**Comment by dsyme** [comment]
> @dsyme Forgive me if this is a dumb idea... but for the sake of being different, would it be possible to have a process by which the compiler scans all files and figures out the file order for itself based on the dependence of types, and then a language service that editors use to validate the dependence of the types the developer is working on, such as when they are using types that are not defined (neither in the current file or in another file that would then be established as an antecedent file) or when they create a cyclical dependency (though perhaps that is where the difficulty arises, as how does the loop terminate)?

I think that's not possible without doing at least name resolution of unqualified identifiers in F# code (which might even involve full type checking - but probably not), and even then there would be corner cases involving ``open`` where a unique order can't be determined (though those cases are generally pathological or "bad smell code") - i.e. multiple orderings exist that give different meanings,

I think such a thing could plausibly be added to existing tooling as a "recompute file order" feature that is explicitly invoked by the user.  I think such a feature could fit with either the existing project file format or the other options above.

**Comment by vasily-kirichenko** [comment]
I like the idea of automatic file ordering very much. So when you add a new file, it's placed above all other files and it dynamically changes its position (both in project file and on "file order" view) as you add code into it that uses other symbols in this project. So, 1. you don't have to order files manually 2. files are always perfectly ordered 3. you have two views, both automatic: folder structure and compilation order. Hell, it's just perfect :)

**Comment by dsyme** [comment]
> Hell, it's just perfect :)

Just make sure the implementation is in FSharp.Compiler.Service API, so Ionide and others can use it too :)

**Comment by srivatsn** [comment]
If the order dynamically changes in the background, it might be disconcerting, probably leading to surprises. I'd love for it to be a codefix for the type not found error. So a "Reorder file to fix the dependency" fix just like a add-open fix so that users take an easy explicit action to put it in the right place.

**Comment by saul** [comment]
Guys - *please* can we continue this discussion on dotnet/roslyn-project-system#1875 😆

**Comment by dsyme** [comment]
> Guys - please can we continue this discussion on dotnet/roslyn-project-system#1875 😆

Or on the F# RFCs linked above - I'd love more comments on those

**Comment by nelak** [comment]
@dsyme An idea regarding project files and compilation. I recall once using the compiler to build .fsx which was using the #load directive to reference the files. Wouldn't it be possible to relay on this to improve the xplat story and removing the file ordering issues? I found it quite intuitive after having worked with nodejs.
What are your thoughts on it?

**Comment by dsyme** [comment]
> .... using the #load directive to reference the files. Wouldn't it be possible to relay on this to improve the xplat story and removing the file ordering issues? 

@nelak Yes, see the suggestion links above - please add your comments there.

**Comment by cloudRoutine** [comment]
@saul I hope you haven't given up on this PR in favor of CPS work, which is all well and good but [it'll be months before we get our hands on it](https://github.com/Microsoft/visualfsharp/pull/2776#issuecomment-291029684). 

Whereas this makes some really useful material gains that can be taken advantage of today (I merge this PR into my custom tools branch, no nightlies for me 😉 )

**Comment by dsyme** [comment]
@cloudRoutine @saul @KevinRansom In the context of open source working, I think there can be "prime the pump" advantages to accepting feature work like this, even if it is later thrown away and replaced when CPS comes.  

Specifically, it can help familiarize contributors with a feature area, making it easier to implement/debug/extend/correct/... the feature second time around.  And people get to use and debug the UX for the feature early.  And people also get _very_ motivated to ensure the feature works in the later version as well.

I think the community experience with VFPT was somewhat similar - although built with the pre-Roslyn VS integration, the lessons, code, UX and so on were all incredibly valuable.  And it was/is a highly valuable set of tools in its own right.  So VFPT was definitely "worth it" as it primed the pump for the Roslynized version, as well as being useful in its own right.

**Comment by cartermp** [comment]
I agree that this would be good to get in.  The CPS work is currently scheduled for 15.3, which will be in a July timeframe, but as that work progresses we may have to cut scope.  I'm also not convinced that we'll be able to completely switch over to that project system for .NET Framework projects in that time frame.  Since .NET Framework represents the _vast_ majority of projects in .NET, improvements like this are wonderful.

**Comment by cartermp** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dsyme @saul I want to accept this.  I think the CI failures where what was holding me back so far.  I am also particularly keen to see a prototype of the compilation order node.  Since that offers a solution to our long existing issue with file ordering and folders.

Kevin

**Comment by saul** [comment]
@cloudRoutine @KevinRansom I don't think this will be completed this week. Time constraints are making this week particularly difficult, but next week I'm hoping to have this (and the rest of my PRs!) merged.

Apologies for the delay, but rest assured I haven't given up on this.

**Comment by saul** [comment]
I think the following tasks should be moved to a separate issue/PR:

- If the folder doesn't exist, create a virtual folder
- If you add a concrete item to a virtual folder create a folder on disk and add the item
- If you add a linked item to a virtual folder it stays virtual

I think they're great things to have but I think this is feature creep. 'Virtual folders' don't exist as a concept within the project system at present, so it'd be a lot of new code to add this.

Also will take a look at the failing tests soon then this will be ready to merge.

**Comment by saul** [comment]
Also @cloudRoutine as requested, here's what happens when you try to rename a folder (that is not empty) to a folder that already exists:

image

Note if the folder you're trying to rename is empty, it does it without complaining now.

**Comment by cloudRoutine** [comment]
> I think they're great things to have but I think this is feature creep. 'Virtual folders' don't exist as a concept within the project system at present, so it'd be a lot of new code to add this.

I don't know what you mean by "exist as a concept" but you can definitely have virtual folders within a project.



```xml
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Library1.fs" />
    <None Include="Script.fsx" />
    <Content Include="packages.config" />
    <Compile Include="one.fs">
      <Link>virtual-folder\one.fs</Link>
    </Compile>
    <Compile Include="two.fs">
      <Link>virtual-folder\two.fs</Link>
    </Compile>
  </ItemGroup>
```



You see a folder node in the project tree, there is no corresponding folder on disk.
All I want is that if I add another linked item to that "virtual folder" there shouldn't be a new folder created on disk.

@saul  whatever you're thinking of is way more complicated than it needs to be

**Comment by saul** [comment]
No idea what the build error is here because I can't even view the whole file

**Comment by majocha** [comment]
@saul 
```
Errors and Failures

1) Failed : Tests.ProjectSystem.ProjectItems.AddNewItem.ItemAppearsAtBottomOfFsprojFileEvenIfUnknownItemWithSameName
Expected
["orig.fs"; "a.fs"]
but got
["a.fs"; "orig.fs"]
```

**Comment by saul** [comment]
@majocha Thanks - but how in god's name did you find that?

**Comment by majocha** [comment]
@saul I saved `view as plain text' link  to text file :)

**Comment by charlesroddie** [comment]
@saul
The screenshots here look great!
But please don't make the solution order different from compile order.

**Comment by saul** [comment]
Removed the failing test as it's impossible to reproduce in a real-world scenario. The test was doing the following:

In a project with the following MSBuild:

```
                <ItemGroup>
                    <Unknown Include="a.fs" />
                    <Compile Include="orig.fs" />
                </ItemGroup>
```

It was simulating adding the "a.fs" to the project. Now in VS proper this is a no-op - VS detects that the file is already in the project and does nothing. The test was simulating this about 5 layers deep and so some assumptions were failing. I don't believe they need addressing as the scenario can't be reproduced in a real-life scenario anyway.

**Comment by KevinRansom** [comment]
@saul is it your recommendation that this is reviewable.

**Comment by saul** [comment]
@KevinRansom reviewable and in a state to be merged

**Comment by KevinRansom** [comment]
@saul Thanks for this it looks great.

Kevin

**Pull request merged**
