### PR TITLE
apply source-build patches

### PR DESCRIPTION
**Pull request by brettfo**
Applying the relevant source-build patches from [here](https://github.com/dotnet/source-build/tree/92d5528050f58b06d3016db5623d0a296f6c5d0d/patches/fsharp).

### CODE REVIEW

**Comment by crummel** [comment]
I'm trying this out now, I think there was a conflict with MSBuild that was causing it.  I think you can skip them for now.

**Comment by crummel** [comment]
Yes, MSBuild removed netcoreapp2.0 from their TFMs.  At the time, F# built with that change, I'm looking into why that changed now.

**Comment by brettfo** [comment]
We currently rely on 15.8.166 of the MSBuild packages which support netstandard2.0; only some of the newer 16.x packages dropped that in favor of netcoreapp2.1.  Do we need to update our dependencies to MSBuild 16.x to match (and as a consequence, update to netcoreapp2.1)?

**Comment by crummel** [comment]
The 3.0 previews have upgraded to MSBuild 16, so if that's possible for you I think it would be the most correct route.  Alternatively, if they're only used as ref packages, @dseefeld might know when we could look at replacing them that way.

**Comment by brettfo** [comment]
I just updated our MSBuild packages (and the corresponding `netcoreapp2.1` TFM changes) so we'll see where that gets us.

**Pull request merged**
