### PR TITLE
whitespace cleanup

### PR DESCRIPTION
**Pull request by dsyme**
More bike shedding in the morning.

This is all whitespace cleanup.

Why use one space when we could randomly scatter multiple spaces throughout our codebase?

### CODE REVIEW

**Comment by dsyme** [comment]
Ugh, this test is still flaky: 
```

Failed   TypeProvider.Disposal.SmokeTest2
Error Message:
   Check6b, at end, countCreations() = countDisposals() after explicit clearing
  Expected: True
  But was:  False

Stack Trace:
   at Tests.LanguageService.Script.UsingMSBuild.TypeProviderDisposalSmokeTest(Boolean clearing) in D:\a\1\s\vsintegration\tests\UnitTests\LegacyLanguageService\Tests.LanguageService.Script.fs:line 1662
   at Tests.LanguageService.Script.UsingMSBuild.TypeProvider.Disposal.SmokeTest2() in D:\a\1\s\vsintegration\tests\UnitTests\LegacyLanguageService\Tests.LanguageService.Script.fs:line 1670
```

**Comment by KevinRansom** [comment]
While doing this can you get rid of the random whitespace at the end of lines.  Because that triggers my OCD big time.

**Comment by baronfel** [comment]
If we put an .editorconfig in the repo root with 5he correct configuration, most editors these days will enforce constraints like 'trim spaces at end of line' and 'newline at end of file'. Might be a simple way to bring the repo into alignment and ensure consistency going forward.

**Comment by dsyme** [comment]
> While doing this can you get rid of the random whitespace at the end of lines. Because that triggers my OCD big time.

Let's do that in a separate PR, once for all.

**Comment by NatElkins** [comment]
If you do end up doing it, I added a test for trailing whitespace a long time ago which could probably be re-added: https://github.com/Microsoft/visualfsharp/pull/1421

**Comment by dsyme** [comment]
@NatElkins Thanks!

@TIHan or @KevinRansom , can you approve then we can get about integrating this into PRs etc.? thanks

**Comment by BentTranberg** [comment]
`<rant>` I don't understand why VS don't strip whitespace from the end of lines and end of files. I have complained to MS about this many times through the years, to no avail. I don't remember having used any other code editor that lacks this feature. In large teams this is essential to prevent many meaningless changes in commits, and it is a nuisance to have to ask the entire team to install extensions for such basic functionality. `</rant>`

**Comment by dsyme** [comment]
> @TIHan or @KevinRansom , can you approve then we can get about integrating this into PRs etc.? thanks

Ping :) the longer we leave it dangling the more integration pain we get :)

**Pull request merged**
