### PR TITLE
add menu entry "Open folder in File Explorer" on Folder nodes

### PR DESCRIPTION
**Pull request by enricosada**
like on project menu

### CODE REVIEW

**Comment by forki** [comment]
Wow. That's super useful. I hope "add file" will work as well.

**Comment by enricosada** [comment]
this was a test, an easy cherry-pick from pytools. 

i think the best long term solution is to align fsharp with the shared  vs codebase of pytools (like nodejstools). see http://pytools.codeplex.com/SourceControl/latest#Common/Product/SharedProject/ ).

Is the same codebase of fsharp, see [pytools OAProperties.cs](http://pytools.codeplex.com/SourceControl/latest#Common/Product/SharedProject/Automation/OAProperties.cs) vs [f# OAProperties.cs ](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/vs/FsPkgs/FSharp.Project/Common.Source.CSharp/Project/Automation/OAProperties.cs)

there are lot of features (drag drop/show all files/etc) who can be imported without much work.

we can do like mono with bcl reference source, add a  submodule (or code drop in a subdir) and reference new classes, one class at time

pro: we can upgrade easy new features

**Comment by KevinRansom** [comment]
This would make a great VS feature request for VS 2015 IDE.  I'm not sure that it makes much sense if only a single VS language supports it.

**Comment by forki** [comment]
we are talking about the following, right?

image

which is already available for C# in VS2013

**Comment by enricosada** [comment]
Every language (c# Python Node vb) support this. 
Is enabled in base class for project node and vs query every node if support this feature. 
But i think is disabled for folder nodes because a folder can be virtual ( no directory in file system )

**Comment by enricosada** [comment]
Yea @forki is that menu entry

**Comment by latkin** [comment]
Cool!

Does it work for "virtual" folders created solely by Link items? e.g. like the projects in this repo.  Wondering if there needs to be perhaps `if (File.Exists(this.Url))` or something.

**Comment by forki** [comment]
So since every other languages supports this: +100 from me

You can earn my personal "open source hero award" TM if you manage to port
the "add existing file" and "add new file" features for folders and make
these work reliable. ;-)

**Comment by KevinRansom** [comment]
In that case, since it is already there for C# and VB, we should indeed have it.

**Comment by enricosada** [comment]
added check to validate whether the directory exists (and relative visibility of the menu entry)

tried with:

```xml
  <ItemGroup>
    <Compile Include="File1.fs" />
    <Compile Include="subdir\File2.fs" />
    <Compile Include="subdir\File3.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="invalid dir\" />
    <Folder Include="empty dir\" />
  </ItemGroup>
```

where:
-  ``invalid dir`` not exists
- ``empty dir`` exists (tried to delete it, work ok) 
- ``subdir`` is created without a Folder msbuild node



@latkin what do you mean by: 
> Does it work for "virtual" folders created solely by Link items? e.g. like the projects in this repo. 

solution folders?

**Comment by rojepp** [comment]
@enricosada He means the 'Solution items' folder that isn't really a folder. You get it by adding an existing file a to a solution node instead of a project/folder node.

**Comment by dsyme** [comment]
Hi @enricosada and all

Just to mention that we got these three requests for solution-explorer-related micro features on fslang.uservoice.com.  I'll ask them to be moved to the Visual F# Tools user voice (since that's what they are about) but I thought I'd mention them here in case they are easy and have corresponding code in the Python tools


> 1.	Ability to rename files
> I just want to rename files. If I do this, my content type changes to none, and the file floats to the top. So not only can I not just click and drag (see other request), but I still have to go into the .fsproj file again and chance the type back to Content. You really should just make F# easier to deal with, I know there is fancy stuff people want, I want it to, but my goodness I would kill for these simple features!
> 
> 2.	Ability to add web file types to project
> I am building an enterprise FSharp web application with Web API and I can't even add a simply .html page to my solution without cracking open the FSProj file every time.  I spend more time in the FSProj file than actually writing FSharp code.
> 
> 3.	Ability to simply move files in the Solution Explorer
> I just want to click, drag and move files around in the solution explorer. As of today I have to unload my solution, edit my fsproj file and move on. 



cheers!
don

**Comment by dungpa** [comment]
@enricosada There are many projects out there using virtual folders by modifying project files manually e.g. https://github.com/fsharp/FSharp.Compiler.Service/blob/5bfa88d4b244fcae9e2f55f4ef356ba90cda1195/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj#L535-L537. Have you tested with this?

**Comment by enricosada** [comment]
it does not work with `Solution items`, because it can contain files from multiple directories

I can make it work for files, like `Open containing folder` but is another pr

@dungpa i'll check

**Comment by enricosada** [comment]
no, doesnt work for Link item. 

With:

```xml
  <ItemGroup>
    <Compile Include="..\..\external folder\FileExt.fs">
        <Link>Service/FileExt.fs</Link>
    </Compile>
    <Compile Include="..\..\another external folder\FileExtOrig.fs">
        <Link>Service/FileExt2.fs</Link>
    </Compile>
  </ItemGroup>
```

query directory `Service` and not exists -> no menu entry, as expected

I dont it should work, virtual folder can contain files from multiple sources. 
I can check use the distinct of children node directories ( `external folder` and `another external folder` in my example) and ask user ( or open all )
Or open the directory if distinct length = 1

But maybe you want the "Open containing folder" on files, i can add that and use real directory of file

**Comment by forki** [comment]
I think "open containing folder" would also be very useful. But this should be done in different pull request

**Comment by enricosada** [comment]
@dsyme i try to cherry-pick from pytools, but i think is a good idea to start migrate `ProjectSystem.Base` to pytools codebase (is the same codebase, classes can be migrated one by one after codedrop). 

pytools and nodejstools (it use pytools shared codebase) just work.

**Comment by latkin** [comment]
I think this behavior is fine, doing fancy stuff like sniffing for unique directories of files in virtual nodes just adds complexity that doesn't add much value (IMO).

Looks good to me at this point :shipit:

**Comment by latkin** [comment]
Merged in https://github.com/Microsoft/visualfsharp/commit/36e0ec8a56e6ed37b2daed80ce66462474465c1a

**Comment by KevinRansom** [comment]
merged

**Pull request closed without merging**
