### PR TITLE
Optimize Mapfold

### PR DESCRIPTION
**Pull request by liboz**
@dsyme 
Can you run the compilerperf script to see if this makes a difference?

This is attempt to optimize the `mapFold` function in `illib`, which is called a lot. 

I first measured the size of the lists that get passed into it by using `fsc` to compile the `FSharp.Core` library and having it output to console the size of the lists. I found that around 42% of all the lists passed in are empty, 39% of all the lists passed in have size 1, and 14% of all lists passed in have size 2. Here's a graph displaying it (note the log scale). 
a

Because of this I added in extra conditions to optimize for the null and size 1 cases. For larger lists, I use `List.mapFold` because that prevents us having to use `List.rev`, which is quite expensive. Below are my benchmark results and the [script ](https://gist.github.com/liboz/b17cc1740f5bdfdd0bc516df72b55081)I used to generate it. It is marginally faster for size 0 and 1 lists and much faster for lists larger than that.

|         Method |       Jit | Platform | count |        Mean |    StdDev |  Gen 0 | Allocated |    Gen 0 |
|--------------- |---------- |--------- |------ |------------ |---------- |------- |---------- |--------- |
| mapFoldLibrary | LegacyJit |      X86 |     0 |   **7.9820 ns** | 0.1351 ns | 0.0084 |      28 B |   232.09 |
|            old | LegacyJit |      X86 |     0 |  10.2546 ns | 0.0811 ns | 0.0081 |      28 B |   197.42 |
| mapFoldLibrary |    RyuJit |      X64 |     0 |   **9.8685 ns** | 0.2399 ns | 0.0170 |      56 B |   372.15 |
|            old |    RyuJit |      X64 |     0 |  12.6970 ns | 0.3386 ns | 0.0170 |      56 B |   342.35 |
| mapFoldLibrary | LegacyJit |      X86 |     1 |  **36.0709 ns** | 0.6886 ns | 0.0173 |      60 B |   476.19 |
|            old | LegacyJit |      X86 |     1 |  38.5328 ns | 0.4145 ns | 0.0174 |      60 B |   412.70 |
| mapFoldLibrary |    RyuJit |      X64 |     1 |  **22.1181 ns** | 0.1698 ns | 0.0339 |     112 B |   774.00 |
|            old |    RyuJit |      X64 |     1 |  25.6891 ns | 0.3070 ns | 0.0339 |     112 B |   684.60 |
| mapFoldLibrary | LegacyJit |      X86 |     2 |  **50.4253 ns** | 0.4492 ns | 0.0259 |      92 B |   609.00 |
|            old | LegacyJit |      X86 |     2 |  76.3954 ns | 0.3959 ns | 0.0361 |     124 B |   953.79 |
| mapFoldLibrary |    RyuJit |      X64 |     2 |  **40.0407 ns** | 0.2898 ns | 0.0518 |     168 B | 1,100.36 |
|            old |    RyuJit |      X64 |     2 |  49.3331 ns | 0.1614 ns | 0.0706 |     232 B | 1,543.40 |
| mapFoldLibrary | LegacyJit |      X86 |     3 |  **58.8695 ns** | 0.4564 ns | 0.0364 |     124 B |   947.50 |
|            old | LegacyJit |      X86 |     3 | 106.5111 ns | 1.2117 ns | 0.0483 |     172 B | 1,047.20 |
| mapFoldLibrary |    RyuJit |      X64 |     3 |  **50.3711 ns** | 0.7742 ns | 0.0680 |     224 B | 1,488.60 |
|            old |    RyuJit |      X64 |     3 |  67.6240 ns | 0.3922 ns | 0.0985 |     320 B | 2,128.60 |
| mapFoldLibrary | LegacyJit |      X86 |     4 |  **67.2295 ns** | 0.1917 ns | 0.0464 |     156 B |   950.80 |
|            old | LegacyJit |      X86 |     4 | 136.2848 ns | 0.5413 ns | 0.0634 |     220 B | 1,750.15 |
| mapFoldLibrary |    RyuJit |      X64 |     4 |  **61.6003 ns** | 0.2595 ns | 0.0859 |     280 B | 1,714.00 |
|            old |    RyuJit |      X64 |     4 |  86.0856 ns | 0.6507 ns | 0.1234 |     408 B | 3,057.18 |
| mapFoldLibrary | LegacyJit |      X86 |     5 |  **76.8845 ns** | 0.3080 ns | 0.0565 |     188 B | 1,248.60 |
|            old | LegacyJit |      X86 |     5 | 167.2817 ns | 2.7596 ns | 0.0786 |     268 B | 1,905.00 |
| mapFoldLibrary |    RyuJit |      X64 |     5 |  **71.2625 ns** | 0.4908 ns | 0.1035 |     336 B | 2,296.93 |
|            old |    RyuJit |      X64 |     5 | 104.8573 ns | 0.6288 ns | 0.1507 |     496 B | 4,261.38 |
| mapFoldLibrary | LegacyJit |      X86 |    10 | **124.1846 ns** | 3.7853 ns | 0.1039 |     348 B | 2,373.00 |
|            old | LegacyJit |      X86 |    10 | 327.2854 ns | 4.6879 ns | 0.1485 |     508 B | 4,220.00 |
| mapFoldLibrary |    RyuJit |      X64 |    10 | **120.4639 ns** | 1.4605 ns | 0.1894 |     616 B | 4,213.29 |
|            old |    RyuJit |      X64 |    10 | 205.6105 ns | 3.1472 ns | 0.2851 |     936 B | 5,714.40 |

### CODE REVIEW

**Comment by forki** [comment]
wow

**Comment by liboz** [comment]
I reran the benchmark with the latest commit, which uses an `OptimizedClosure` even for lists of size 1, which makes quite a big difference for x86. I also included a list of size 200.

|         Method |       Jit | Platform | count |          Mean |     StdDev |        Median |  Gen 0 | Allocated |     Gen 0 |
|--------------- |---------- |--------- |------ |-------------- |----------- |-------------- |------- |---------- |---------- |
| mapFoldLibrary | LegacyJit |      X86 |     0 |     **8.4156 ns** |  0.2867 ns |     8.3025 ns | 0.0086 |      28 B |     20.17 |
|            old | LegacyJit |      X86 |     0 |    10.5356 ns |  0.0431 ns |    10.5390 ns | 0.0087 |      28 B |     18.37 |
| mapFoldLibrary |    RyuJit |      X64 |     0 |     **8.9394 ns** |  0.0521 ns |     8.9444 ns | 0.0175 |      56 B |     34.45 |
|            old |    RyuJit |      X64 |     0 |    11.3318 ns |  0.0449 ns |    11.3378 ns | 0.0175 |      56 B |     37.61 |
| mapFoldLibrary | LegacyJit |      X86 |     1 |    **20.1550 ns** |  0.0729 ns |    20.1465 ns | 0.0185 |      60 B |     36.50 |
|            old | LegacyJit |      X86 |     1 |    37.5498 ns |  0.1217 ns |    37.5273 ns | 0.0185 |      60 B |     35.28 |
| mapFoldLibrary |    RyuJit |      X64 |     1 |    **22.6510 ns** |  0.0547 ns |    22.6488 ns | 0.0351 |     112 B |     73.50 |
|            old |    RyuJit |      X64 |     1 |    25.0650 ns |  0.0735 ns |    25.0641 ns | 0.0350 |     112 B |     81.65 |
| mapFoldLibrary | LegacyJit |      X86 |     2 |    **47.1284 ns** |  0.3933 ns |    47.2077 ns | 0.0281 |      92 B |     55.07 |
|            old | LegacyJit |      X86 |     2 |    74.3761 ns |  0.1504 ns |    74.3878 ns | 0.0384 |     124 B |     73.24 |
| mapFoldLibrary |    RyuJit |      X64 |     2 |    **37.9762 ns** |  0.1207 ns |    37.9530 ns | 0.0528 |     168 B |    103.35 |
|            old |    RyuJit |      X64 |     2 |    48.4527 ns |  0.1928 ns |    48.4350 ns | 0.0727 |     232 B |    142.39 |
| mapFoldLibrary | LegacyJit |      X86 |     3 |   **55.9078 ns** |  0.7202 ns |    55.7897 ns | 0.0385 |     124 B |     81.38 |
|            old | LegacyJit |      X86 |     3 |   103.7128 ns |  0.5762 ns |   103.5408 ns | 0.0526 |     172 B |    114.98 |
| mapFoldLibrary |    RyuJit |      X64 |     3 |    **47.8466 ns** |  0.4055 ns |    47.7283 ns | 0.0702 |     224 B |    143.80 |
|            old |    RyuJit |      X64 |     3 |    65.6070 ns |  0.6674 ns |    65.8029 ns | 0.1007 |     320 B |    204.67 |
| mapFoldLibrary | LegacyJit |      X86 |     4 |    **64.7824 ns** |  0.6187 ns |    64.5236 ns | 0.0484 |     156 B |     93.75 |
|            old | LegacyJit |      X86 |     4 |   132.1718 ns |  1.2091 ns |   132.4878 ns | 0.0679 |     220 B |    135.02 |
| mapFoldLibrary |    RyuJit |      X64 |     4 |    **57.9229 ns** |  0.5386 ns |    57.7049 ns | 0.0880 |     280 B |    171.88 |
|            old |    RyuJit |      X64 |     4 |    84.8074 ns |  0.2946 ns |    84.7772 ns | 0.1285 |     408 B |    241.08 |
| mapFoldLibrary | LegacyJit |      X86 |     5 |    **73.1281 ns** |  0.2990 ns |    73.0463 ns | 0.0587 |     188 B |    115.19 |
|            old | LegacyJit |      X86 |     5 |   162.0976 ns |  1.6367 ns |   161.7521 ns | 0.0831 |     268 B |    168.11 |
| mapFoldLibrary |    RyuJit |      X64 |     5 |    **67.3089 ns** |  0.2145 ns |    67.3206 ns | 0.1056 |     336 B |    223.13 |
|            old |    RyuJit |      X64 |     5 |   102.7672 ns |  0.7567 ns |   102.9256 ns | 0.1555 |     496 B |    310.49 |
| mapFoldLibrary | LegacyJit |      X86 |    10 |   **117.1620 ns** |  1.4002 ns |   116.7370 ns | 0.1084 |     348 B |    222.90 |
|            old | LegacyJit |      X86 |    10 |   314.5876 ns |  2.6753 ns |   315.1066 ns | 0.1578 |     508 B |    333.40 |
| mapFoldLibrary |    RyuJit |      X64 |    10 |   **117.6482 ns** |  0.3742 ns |   117.6242 ns | 0.1937 |     616 B |    384.30 |
|            old |    RyuJit |      X64 |    10 |   201.4086 ns |  0.5629 ns |   201.4625 ns | 0.2932 |     936 B |    552.23 |
| mapFoldLibrary | LegacyJit |      X86 |   200 | **1,789.0379 ns** |  6.4853 ns | 1,789.4405 ns | 2.0108 |   6.43 kB |  4,174.38 |
|            old | LegacyJit |      X86 |   200 | 5,941.7822 ns | 49.1143 ns | 5,953.1631 ns | 2.9492 |   9.63 kB |  5,797.00 |
| mapFoldLibrary |    RyuJit |      X64 |   200 | **1,996.1305 ns** |  6.7861 ns | 1,997.3284 ns | 3.5443 |  11.26 kB |  7,476.49 |
|            old |    RyuJit |      X64 |   200 | 3,747.8527 ns | 14.4366 ns | 3,749.0509 ns | 5.5487 |  17.66 kB | 11,528.85 |

**Comment by dsyme** [comment]
@liboz I added some perf results here https://github.com/dsyme/visualfsharp/blob/2c3cece77c1287c5c0464d6f59759700d3cf4e70/tests/scripts/compiler-perf-results.txt

Some of the numbers look erratic - but overall I see only very small differences at the most for commit ``38e74ec89ada4bdd277be989a8aecfd855d1aaff ``, e.g. 30.4 instead of 30.9 for ``parseonly-to-check``.  Certainly there's no harm done but I think that ``mapFold`` doesn't dominate overall time

**Comment by KevinRansom** [comment]
@liboz @dsyme 

Do you have any recommendations for this PR?

Kevin

**Pull request merged**
