### PR TITLE
Highlight disposable types

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
image

(the default color is the same as for other types)

### CODE REVIEW

**Comment by cloudRoutine** [comment]
@vasily-kirichenko I merged this into https://github.com/Microsoft/visualfsharp/pull/2452/commits/a177ef9f95d188a498e9d9e146dbb61619f28d0a to deal with the conflicts so you can close this PR

**Comment by vasily-kirichenko** [comment]
I'd like to close it when your PR is merged :)

**Comment by saul** [comment]
This looks fantastic 👍 

As a separate issue, how much work would it be to add a code fix for not using 'use' with IDisposable?

**Comment by vasily-kirichenko** [comment]
@saul it was discussed several times already. In short, since using let is totally legit, such a warning / fix is not desirable.

**Comment by KevinRansom** [comment]
@vasily-kirichenko Because I merged rather than squashed there is no need to close this :-)

**Pull request merged**
