### PR TITLE
Highlight active patterns as functions instead of as DUs

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
image

### CODE REVIEW

**Comment by forki** [comment]
Nice!

**Comment by drvink** [comment]
That was fast. :)

**Comment by dsyme** [comment]
My comment I just wrote [here](https://github.com/Microsoft/visualfsharp/pull/2722#issuecomment-290446802) is kind of relevant:

> It goes back to a point I made a couple of days ago: in user code, F# generally emphasizes similarity (e.g. between classes and records, or between an active pattern and regular pattern, or a method and a property, or an F# call and a .NET call, or a method and a function value etc.. etc. etc.) rather than difference. The tooling should generally try to do this too - or take care when highlighting differences.

So my gut feeling on first look is that I'd want it to be off by default. 

Important: don't take this feedback too seriously - you guys, @cartermp. @KevinRansom, @brettfo  and others are in charge of the visual F# tooling :) Between you I totally trust that you'll tune the defaults the right way :)

**Comment by dsyme** [comment]
Couple extra thoughts:

- looking at the highlighting above, my first reaction was "whoa, there's a bug in that code, the patterns aren't being highlighted".  I had to mentally process things to work out "ah, that's an _active_ pattern, I get it..."  That might (or might not?) be an indication that extra variations in highlighting can increase mental burden

- Generally, I'm really liking how thigh highlighting in the new tooling gives me this constant sense of additional validation about my code - when I see name highlighting kick in i know that the compiler has resolved the name.  So the highlighting really becomes part of my trust relationship with the tooling in the inner loop of my coding.

**Comment by isaacabraham** [comment]
Silly question maybe - but why should APs be highlighted as functions?

**Comment by dsyme** [comment]
@isaacabraham 
> Silly question maybe - but why should APs be highlighted as functions?

Because they are function calls.  But they are also patterns.

**Comment by vasily-kirichenko** [comment]
I agree. We just were discussing APs on slack and I had an idea that I don't like APs "opaquness" in a sense that they look like DUs but may hide a lot of untriviasl (and even non pure) logic behind. But looking at my screenshot I now see that it's very inconssitent. We'd better forget about this idea.

**Comment by isaacabraham** [comment]
Yes. You also can't use them the same as "regular" functions in terms of composition e.g. here's a sample of a partial AP that checks a SQL Exception for a specific error number and string: -

```fsharp
let (|PrimaryKeyException|_|) : exn -> _ =
    tryFindSqlException 2627 "PRIMARY KEY" >> Option.map(fun ex -> PrimaryKeyException ex)
```
(`tryFindSqlException` has signature (`int -> string -> SqlException option`)

The problem is that you can't "simplify" the Option.map bit as you would do with a normal function: -

```fsharp
let (|PrimaryKeyException|_|) : exn -> _ =
    tryFindSqlException 2627 "PRIMARY KEY" >> Option.map PrimaryKeyException
    // Error: This expression was expected to have type 'SqlException -> 'a' but here has type 'unit'. 
```

So the behaviour of APs isn't *exactly* the same as "normal" functions - so I'd be wary of putting this on by default for sure. Certainly I treat them as just a slightly more different form of DU, although I get the fact that they are functions in a sense.

**Comment by cartermp** [comment]
I agree with @dsyme's opinions here, though I will say that this is definitely something to consider as configurable in the future.  It's an interesting point if we should make Active Patterns distinct from other patterns.  My impression is that they're _supposed_ to be used as a way to hide some basic functionality behind something which is conceptually just a pattern, and having anything complex behind that pattern is generally a no-no.  Given that, treating them as if they were "normal" patterns in semantic highlighting would make sense to me.

**Comment by isaacabraham** [comment]
@vasily-kirichenko certainly having the ability to override the colour of APs compared to "normal" DUs has value. For example, you might change the colour to *slightly* darker, or bold or italise it so that they don't look so different from standard DUs.

**Pull request closed without merging**
