### PR TITLE
initial version of completion for named parameters

### PR DESCRIPTION
**Pull request by vladima**
This PR tracks the work of adding completion for named parameters\settable properties in methods.
Pending work: add tests
parametercompletion

### CODE REVIEW

**Comment by forki** [comment]
Wow. Very cool

**Comment by enricosada** [comment]
I dont understand `Anchor`. Is shown because is a setter property of the return value of MakeForm?

**Comment by vladima** [comment]
@enricosada yes, this is correct. In F# named argment syntax can be used to specify value of the input parameter and settable property\field on the return value

**Comment by dsyme** [comment]
The code looks great - wonderful to see this drop out reasonably smoothly.  

Looking forward to the tests :)

**Comment by dsyme** [comment]
This is awesome

The one extra thing I'd like for both parameters and settable fields is to pin down what happens when the trailing ")" is removed - e.g. 

- if there is whitespace to end-of-line and then nothing
- if there is whitespace to end-of-line and then another "let" at the start of the next line
- if there is whitespace to end-of-line and then another "type" at the next un-indented position on the next line

I'm not too concerned if we don't give perfect results in these scenarios, but I'd really like to pin down what does/doesn't work to make sure we know if we regress something in the future.

This extra testing ould be added as a separate PR though.

thanks!
don

**Comment by vladima** [comment]
Yes, I'll add a separate PR with tests for broken code

**Comment by latkin** [comment]
This results in additional errors being output in test `fsharp\typecheck\sigs\neg61.fs` (tests negative cases for query expressions).  Can you take a look?

**Comment by vladima** [comment]
@latkin, good catch - I've updated the code

**Pull request closed without merging**
