### PR TITLE
[Experiment] Compound open statement

### PR DESCRIPTION
**Pull request by duncanmak**
Here is a patch to the parser to allow compound open statements.

This is how it works:

```
Microsoft (R) F# Interactive version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> open System.(_, Collections.Generic, Text);;
> Console.WriteLine(ASCIIEncoding().BodyName);;
us-ascii
val it : unit = ()
```

With this change, namespaces with the same prefix can be grouped together, and a special case for `_` is there for importing the base namespace as well.

For example, `open System.(_, Collections.Generic, Text)` expands into
```F#
open System
open System.Collections.Generic
open System.Text
```

I'm open to suggestions and other modifications.

Thanks to @lambdageek for helping me to craft this patch.

### CODE REVIEW

**Comment by TIHan** [comment]
Is there a RFC for this?

**Comment by TIHan** [comment]
Spoke to @cartermp , seems we may get a RFC soon and @duncanmak can hack away on this. :)

**Comment by auduchinok** [comment]
> E.g. having actual namespace System._ would make your sample ambiguous.
> Maybe using System.(*, Collections.Generic) would be better instead?

I'd expect `_` to mean something ignored here.
That `*` would look ambiguous for Java people. :)

Anyway, I _think_ we should talk about the syntax in RFC as it looks quite different to what we have in F#/C#/Kotlin/etc now and I can't say I'd vote for this syntax pulled in.

**Comment by BentTranberg** [comment]
I didn't find an issue for this in fslang-design.

I have an idea for a syntax which I believe is quite readable and compact, even when expressing a large hierarchy.

```
open System
open System.Collections.Generic
open System.Collections.ObjectModel
open System.Collections.Concurrent
open System.Text
open System.Linq
open System.Linq.Expressions

// becomes

open System.(Collections(Generic|ObjectModel|Concurrent)|Text|Linq.(Expressions))

```
I found mixing dots and commas less readable, and think vertical bar is better (than a comma). Also the dot now has a special meaning.

When there is a dot, it means that this level is also opened. When no dot, only the sublevels are opened. So in this case, System and Linq is opened, but not Collections.

The syntax is perhaps not that logical from a language designers point of view, but I think it is rather quick and easy to analyze when you read. You only need to look for dots before each opening parenthesis.

**Comment by duncanmak** [comment]
Talking about this with @lambdageek, here's an alternative that's pretty easy to implement.

`System.(., Text, Collections.(Generic, Concurrent))` expands into

```
open System
open System.Collections.Generic
open System.Collections.Concurrent
```

So instead of `_` to refer to the _null_ string, we use `.` - this, I think will address @ForNeVeR's concern.

This proposal does a little more than my original patch, it allows nested `multiPaths` in the `open` statement.

**Comment by duncanmak** [comment]
I wrote up my original design (and what's implemented in this PR) as a suggestion here - https://github.com/fsharp/fslang-suggestions/issues/657

**Comment by KevinRansom** [comment]
@duncanmak,

pleasase resubmit this when the language design process has been completed.  The code looks good and it looks achievable, but I can see this is one of those features that will require persistent design effort to get to the point that most are happy with it.

Kevin

**Pull request closed without merging**
