### PR TITLE
[WIP] remove deprecated bat files of fsharp test suite

### PR DESCRIPTION
**Pull request by enricosada**
remove bat files of cambridge suite
- [x] remove bat files
- [x] fix build.cmd and runtests.cmd
- [ ] check suite with coreclr works

ref #1074

### CODE REVIEW

**Comment by dsyme** [comment]
+10000

**Comment by forki** [comment]
@dsyme it's not +10000 - it's +1 −6,026 ;-)

**Comment by dsyme** [comment]
Looks like some "Invalid" tests are being generated?

```
[00:23:16] 1) Invalid : FSharp-Tests-Core+NetCore+Netcore259.netcore259
[00:23:16] System.Exception : test directory 'C:\projects\visualfsharp-radou\tests\fsharp\core\netcore\netcore259' does not exists
[00:23:16]    at NUnitConf.FSharpTestSuite.setProps@194.Invoke(String message) in C:\projects\visualfsharp-radou\tests\fsharp\nunitConf.fs:line 194
[00:23:16]    at NUnitConf.FSharpTestSuite.setProps(String dir, IPropertyBag props) in C:\projects\visualfsharp-radou\tests\fshar
[00:23:16] p\nunitConf.fs:line 194
[00:23:16]    at NUnitConf.FSharpSuiteTestAttribute.NUnit-Framework-Interfaces-IApplyToTest-ApplyToTest(Test test) in C:\projects\visualfsharp-radou\tests\fsharp\nunitConf.fs:line 217
[00:23:16] 
[00:23:16] 
[00:23:16] 2) Invalid : FSharp-Tests-Core+NetCore+Netcore7.netcore7
[00:23:16] System.Exception : test directory 'C:\projects\visualfsharp-radou\tests\fsharp\core\netcore\netcore7' does not exists
[00:23:16]    at NUnitConf.FSharpTestSuite.setProps@194.Invoke(String message) in C:\projects\visualfsharp-radou\tests\fsharp\nunitConf.fs:line 194
[00:23:16]    at NUnitConf.FSharpTestSuite.setProps(String dir, IPropertyBag props) in C:\projects\visualfsharp-radou\tests\fshar
[00:23:16] p\nunitConf.fs:line 194
[00:23:16]    at NUnitConf.FSharpSuiteTestAttribute.NUnit-Framework-Interfaces-IApplyToTest-ApplyToTest(Test test) in C:\projects\visualfsharp-radou\tests\fsharp\nunitConf.fs:line 217
[00:23:16] 
[00:23:16] 
[00:23:16] 3) Invalid : FSharp-Tests-Core+NetCore+Netcore78.netcore78
[00:23:16] System.Exception : test directory 'C:\projects\visualfsharp-radou\tests\fsharp\core\netcore\netcore78' does not exists
[00:23:16]    at NUnitConf.FSharpTestSuite.setProps@194.Invoke(String message) in C:\projects\visualfsharp-radou\tests\fsharp\nunitConf.fs:line 194
[00:23:16]    at NUnitConf.FSharpTestSuite.setProps(String dir, IPropertyBag props) in C:\projects\visualfsharp-radou\tests\fshar
[00:23:16] p\nunitConf.fs:line 194
[00:23:16]    at NUnitConf.FSharpSuiteTestAttribute.NUnit-Framework-Interfaces-IApplyToTest-ApplyToTest(Test test) in C:\projects\visualfsharp-radou\tests\fsharp\nunitConf.fs:line 217
```

**Comment by KevinRansom** [comment]
Closing because no change since May.

**Comment by isaacabraham** [comment]
Closing a PR that has a comment "+10000" in it? Maybe better to find out why there's not been any activity on it. Is there a blocker on this? Does the OP need help to complete it?

**Comment by dsyme** [comment]
@isaacabraham We will remove these files eventually.  I'm OK with closing this. Long-term open PRs have a significant mental burden for repo owners.

* The deletion is easy enough, we don't need an open PR to track it. 

* The blocker is that we don't yet have a way to run the F# compiler for CoreCLR as part of our NUnit-based unit testing.

* I spoke with Keven and there is also an issue that repro-ing test failures for the NUnit-based tests is really hard.  It makes it realy hard for active developers to move away from the batch files. 

* So I think we need to augment the testing process with output of step-by-step logs needed to repro the test failure independently.

I'll take a look at this as we most definitely need those batch files to go.

**Comment by enricosada** [comment]
@isaacabraham it's me, i didnt update this pr, it's easy to continue work anyway.
I'll try to send a pr when ready and i have time to finish it (if someone doenst do that before me 😄 )


> I spoke with Keven and there is also an issue that repro-ing test failures for the NUnit-based tests is really hard. It makes it realy hard for active developers to move away from the batch files.

the `dotnet test` can help in near future (.netcore/.net fw/mono ready).
 
Now is possibile to:
- use visual studio test runner to reexecute only a single test 
- a single test can be executed from command line too, need documentation in dev guide

**Pull request closed without merging**
