### PR TITLE
fix 3033 - correct order for project references

### PR DESCRIPTION
**Pull request by dsyme**
Potential fix for 3033

### CODE REVIEW

**Comment by dsyme** [comment]
@dotnet-bot Test Windows_NT Release_ci_part2 Build please

**Comment by dsyme** [comment]
@KevinRansom I barely tested these changes, they should have been marked WIP

**Comment by KevinRansom** [comment]
@dsyme reverted

**Comment by KevinRansom** [comment]
@dsyme 

https://github.com/Microsoft/visualfsharp/commit/5573f6f8005add122df07b8daa0fe2fe41b02da8

**Pull request merged**
