### PR TITLE
WIP: Nameof operator

### PR DESCRIPTION
**Pull request by forki**
ThispPull request was moved from https://visualfsharp.codeplex.com/SourceControl/network/forks/forki/fsharp/contribution/7698 (see discussion there)

https://fslang.uservoice.com/forums/245727-f-language/suggestions/5900625-add-nameof-operator-to-follow-c-vb-update suggests we implement a "nameof" operator which is something similar to the typeof operator.

This feature was "approved in principle" by Don.

Small outline:
* I added a nameof to env.fs
* In opt.fs we rewrite the typed AST to const string expressions with the name
* In check.fs we raise compiler errors for all unknown cases
* prim-types.fs shows we will throw if we couldn't inline the nameof operator
* src/fsharp/FSharp.Core.Unittests/NameOfTests.fs contains samples for all the known cases

Open questions:
* How can we write unittests for the cases we don't want to support?
  * I'd like to write a test which shows tha "nameof(6)" fails with compiler error
* The C# spec for nameof shows cases that retrieve names for types. Do we want this too?
* ...   

Related information:

C#/VB spec for nameof: https://roslyn.codeplex.com/discussions/570551
Mads showing the nameof operator: http://channel9.msdn.com/Events/Visual-Studio/Connect-event-2014/116 (at 5:35)

>> Latkin: F# 4.0 triage – This PR is not being considered for F# 4.0, but will be left open for the time being to allow for community feedback.

### CODE REVIEW

**Comment by KevinRansom** [comment]
Thanks for moving this over Steffen.

**Comment by ctaggart** [comment]
Looking forward to this functionality being added at some point. I think it will be a great addition. I could really use it for some logging I'm doing right now.

**Comment by forki** [comment]
Could you please describe your scenario with a small code sample?

**Comment by dsyme** [comment]
This won't be in F# 4.0, and needs further work, so I suggest we "archive" this PR for now by closing it, and then revisiting it later.

**Comment by dungpa** [comment]
Could you add some sort of labels e.g. "archived", "deferred", etc. so that it is easier to track these issues.

**Comment by dsyme** [comment]
Yes, we would need an "archived" label.  The feature is still in http://fslang.uservoice.com of course

**Comment by forki** [comment]
(just a small technical note: the branch should be kept in at least one repo, otherwise it might get lost after closing)

**Comment by latkin** [comment]
"archived" it is

**Comment by xperiandri** [comment]
What is the status of this feature?
Does someone do any work on this?

**Comment by forki** [comment]
I created a prototype, but there are many open edge cases.

**Comment by bluemmc** [comment]
Look forward to this feature. I assume it will work also doing interop with C# code.

**Comment by bluemmc** [comment]
**Example usecase:**
<ReflectedDefinition(true)>]
let foo (x) = ...

let fooType = foo.GetType().DeclaringType.GetMethod(**nameof(foo)**)

**Comment by forki** [comment]
@bluemmc yes there are many usecases, but team decided against it for now.

**Comment by bluemmc** [comment]
Yes, could read that it would not make it for F# 4.0 - but that is out  now. What about next F# versions - has that been decided ?

**Comment by forki** [comment]
@KevinRansom @otawfik-ms @NumberByColors ?

**Comment by 7sharp9** [comment]
Would of been nice to have the open edge cases listed so that anyone interested could look at them etc.

**Comment by forki** [comment]
Unfortunately I can't reopen this after @latkin closed it. 

IIRC we had some discussion over there. It was mostly that we don't support all the positions where nameof can be used in C# (e.g. in attributes)

**Comment by forki** [comment]
From the discussion here you can tell that the interest inside ms is rather low ;-)

**Comment by bluemmc** [comment]
Yes, unfortunately no response from the F# team.

Nameof is the one of few place where C# has a strong advantage language-wise. It is highly annoying that F# still forces developers to use a string anti-pattern when referencing stuff.

@dsyme Is it possible to clarify if there are any plans for Nameof support in F# ?

**Comment by enricosada** [comment]
well, i think this pr it's dead (need rebase anyway). 
But i think it's possibile to reboot a `[WIP]` pr if someone want to try implement it.

It's a really nice feature to have, and a good base implementation by @forki

**Comment by forki** [comment]
Ok I will try to rebase. The we can let it rot again.

**Comment by bluemmc** [comment]
>RE: IIRC we had some discussion over there. It was mostly that we don't support all the positions where nameof can be used in C# (e.g. in attributes)

@forki Would be better to release something a partial fix, rather then letting it rot as you write. Hopefully the F# team can see the benefits of your contribution after a rebase and another look?

**Comment by enricosada** [comment]
i really hope not @forki, it's a really nice feature. 
And now VS 2015 shipped, so less problems

**Comment by forki** [comment]
rebased version at #908

**Pull request closed without merging**
