### PR TITLE
 [FS-1037] Allow Union Constructor to deal with Flexible Type

### PR DESCRIPTION
**Pull request by liboz**
rebased #2382
fixes fsharp/fsharp#660 

RFC https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1037-allow-union-constructors-to-deal-with-flexible-types.md

### CODE REVIEW

**Comment by cartermp** [comment]
Thanks @liboz

**Comment by KevinRansom** [comment]
Targeting 15.8

**Comment by dsyme** [comment]
@liboz I believe this PR will be subject to the same issue as mentioned in https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1055-subsumption-for-yield-in-sequence-expression.md, that is some existing code may become more generic.  For example

```
type C = C of System.IComparable

let g3 xs = C (Seq.head xs)
```
Previously this would give type
```
val g3 : seq<IComparable> -> C
```
but will now give
```
val g3 : seq<#IComparable> -> C
```
There is some logic in this, but it in the extreme it can be considered a breaking change.  The fix is the same as for https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1055-subsumption-for-yield-in-sequence-expression.md

I will test this out. Assuming I am I propose to merge this PR with #1055 to allow them to take advantage of the same underlying approach to ensure 100% compatibility, rather than making one dependent on the other

**Comment by liboz** [comment]
@dsyme Do you need to be do anything to merge it or will you handle that?

**Comment by dsyme** [comment]
@liboz I will handle it, I will merge with https://github.com/Microsoft/visualfsharp/pull/4930

**Comment by dsyme** [comment]
Merged into #4930

**Comment by liboz** [comment]
@dsyme So I pulled the latest from the `dev15.8` branch and attempted to try the simple example that led to this PR: 
```
type Foo = Items of seq<int>
[1;2;3] |> Items```

However I seem to be getting errors when attempting that. Did I do something wrong or was this not directly merged yet?

**Comment by cartermp** [comment]
cc @brettfo who may know more

**Comment by dsyme** [comment]
It looks like I didn't push the commits for the union constructors (RFC FS-1037), they are now in #5030

**Pull request closed without merging**
