### PR TITLE
Added "You must add a reference to '<assembly>'" code fixer

### PR DESCRIPTION
**Pull request by saul**
### Project references

image

### Assembly references

image

### Remaining work

- [x] Localise text
- [x] Copy 'metadata' references from other projects in the solution if we can't find any matching projects
- [x] Fix assertion failure when adding the reference
- [x] Removing references are not reflected in the Roslyn workspace until solution reload

### CODE REVIEW

**Comment by saul** [comment]
I've opened this PR to get some help/pick the brains of others. The problem is that ProjectSysten.OAReferences.AddProject is being called with Library1, i.e. it's attempting to add a reference to Library1 from Library1.

We must be reporting our projects to Roslyn incorrectly, as the names are correct on the Roslyn end (as shown in the screenshot). [ApplyProjectReferenceAdded](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs,386daeac72987856) is the first in the call-stack before we enter the F# project system code.

I have a feeling that we're calling `projectInfoManager.UpdateProjectInfo` with the correct project GUID but the incorrect site. My very preliminary debugging indicated that we're passing in the correct data, though.

**Comment by vasily-kirichenko** [comment]
@saul sorry for offtopic, I cannot find the place where you started the work to enable F# <-> C# Go to Definition. Have you suspended or given up on it? We'd like to join the effort if you are stuck or something.

**Comment by saul** [comment]
@vasily-kirichenko it's very WIP state on my desktop (I'm only on my laptop for a few days). I'll push what I've got onto a branch on Sunday night/Monday. It's certainly not suspended/given up on :)

**Comment by saul** [comment]
8228545 raised a bit of a doozy in our Roslyn workspace setup code. When we setup the project references, we were passing in the *dependent* project as the hierarchy for the *dependency*. How this hasn't caused more issues is beyond me!

**Comment by saul** [comment]
Added support for metadata references:

image

**Comment by saul** [comment]
This is now ready to merge 👍

**Comment by saul** [comment]
I've screwed my rebase up again... I really should read up on how to do this properly.

**Comment by cloudRoutine** [comment]
just checkout a new branch off of master and cherry pick the important commits and you'll be back to status quo in a few mins

**Comment by saul** [comment]
@dotnet-bot test this please

**Comment by cartermp** [comment]
Ugh "The value, namespace, type or module 'CommonRoslynHelpers' is not defined." makes no sense

@dotnet-bot test this please

**Comment by saul** [comment]
@cartermp it's because I'm an idiot - fixed

**Comment by cartermp** [comment]
Looks like there's a merge conflict now.  Unrelated to the build error, though.

**Comment by saul** [comment]
It's green!!

**Comment by saul** [comment]
@KevinRansom it is localised - see the latest commits

**Comment by saul** [comment]
@dotnet-bot test this please

**Comment by saul** [comment]
@KevinRansom you did a dodgy merge - fixed and merged master again. Hopefully this will be the final time -.-

**Comment by saul** [comment]
@cartermp @KevinRansom can this be merged?

**Comment by KevinRansom** [comment]
looking at it right now.

**Comment by KevinRansom** [comment]
Thank you for this, it looks great.,

**Comment by psfinaki** [comment]
Hey @saul, I know it's been 6 years, but maybe do you remember how to repro this? I would like to add some tests for this code fix but, whatever I am doing, I am either getting FS0039 or the the assembly is discovered and added automatically. So I wonder if this is still relevant.

**Comment by saul** [comment]
From memory, I think this would repro when you had a reference (on .NET Framework, before SDK-style projects judging by the year) onto Library2, which in turn referenced Library3 and exposed it through its public API (e.g. method parameters).

I think nowadays assembly references are rare, and in the age of SDK-style projects, project references are transitive. This may be quite a difficult scenario to stumble upon now.

**Comment by psfinaki** [comment]
Ohhhhhh this thing. Okay yeah, my brain has already purged the memories of those days and those project files :D 
Yeah, I downloaded VS2017 and verified in on that scenario - this still works. 

Thanks @saul for such a prompt response - you saved me a lot of time.

**Pull request merged**
