### PR TITLE
Fix #68 - filter out type initializer from Type.GetConstructor portable ...

### LINKED ISSUE #68: F# 3.1 / Profile 259: <@ System.Exception() @> causes AmbiguousMatchException at runtime
A Universal App or unit test executing code like `<@ System.Exception() @>` in an F# 3.1 / Profile 259 portable class library will result in an `AmbiguousMatchException` at runtime. Stacktrace looks something like

>   at Microsoft.FSharp.Core.ReflectionAdapters.commit[a](a[] results)
>   at Microsoft.FSharp.Core.ReflectionAdapters.Type.GetConstructor(Type this, Type[] parameterTypes)
>   at Microsoft.FSharp.Quotations.PatternsModule.bindCtor(Type tc, FSharpFunc`2 argTypes, FSharpList`1 tyargs)
>   at Microsoft.FSharp.Quotations.PatternsModule.u_constSpec@1424-40.Invoke(FSharpList`1 tyargs)
>   at Microsoft.FSharp.Quotations.PatternsModule.u_Expr@1305-2.Invoke(BindingEnv env)
>   at Microsoft.FSharp.Quotations.PatternsModule.u_Expr@1327-7.Invoke(BindingEnv env)
>   at Microsoft.FSharp.Quotations.PatternsModule.deserialize(Type localAssembly, FSharpList`1 types, FSharpList`1 splices, Byte[] bytes)
>   at Microsoft.FSharp.Quotations.FSharpExpr.Deserialize(Type qualifyingType, FSharpList`1 spliceTypes, FSharpList`1 spliceExprs, Byte[] bytes)
>   at ...

### PR DESCRIPTION
**Pull request by stephen-swensen**

### CODE REVIEW

**Comment by dsyme** [comment]
This looks good and ready to go to me.

**Comment by KevinRansom** [comment]
Passes all of the tests.

**Comment by KevinRansom** [comment]
Will pull when we get confirmation of CLA.  I expect it to be threading its way through the system.

**Comment by KevinRansom** [comment]
Fixes #240

**Pull request closed without merging**
