### PR TITLE
Suggest Record labels and Union cases

### PR DESCRIPTION
**Pull request by forki**
image

image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I this "Replace with" suffix is not needed.

**Comment by forki** [comment]
How is C# doing this? The text is from earlier commit. But we can change it.

**Comment by forki** [comment]
ready for review

**Comment by cartermp** [comment]
Hmmm.  Not sure I like surfacing the possibility of something completely unrelated, like `GetHashCode` when we're specifically trying to fix a Record label or DU case.  That's likely going to result in quite a few people logging bugs with the feedback tool.

**Comment by forki** [comment]
The GetHashCode can probably be filtered out here since it's not a static method.

**Comment by cartermp** [comment]
Okay.  I think if we can filter out non-static members on types then all the suggestions should seem relevant.

**Comment by forki** [comment]
just took a quick look. this is not easy to determine at this location since we don't know if we are invoked in static or member position. So since this PR only improves the current situation it should still be merged. I have an idea for the filtering and will apply that later.

**Comment by cartermp** [comment]
Sounds good.

**Comment by forki** [comment]
Ok need to fix couple of tests tomorrow

**Comment by forki** [comment]
Ok all tests fixed

**Comment by forki** [comment]
@cartermp since I saw your list on twitter. This pr is not for the analyzer. It's actually just the error message improvement. 
But since the code fix stuff is already merged this error message is automatically used in the analyzer. Ionide will profit as well automatically when this got merged to FCS.

**Comment by cartermp** [comment]
Good to know!

**Pull request merged**
