### PR TITLE
[WIP] use Layout as a source data of classification related tasks

### PR DESCRIPTION
**Pull request by vladima**
**Early WIP**
F# compiler uses `Layout` structure for pretty printing but ultimately outputs result as a string. This become a culprit in classification related scenarios since in order to colorize everything nicely we have to effectively recover original `Layout`. This PR introduces `TaggedText` annotations for text chunks in `Layout`. Later annotated text chunks can easily be converted from the `Layout` to Roslyn `TaggedText`.

Remaining items:
- [ ] - add glyphs to quick info. Possible approach is proposed [#1](https://github.com/vladima/visualfsharp/pull/1) but I think we can do this without doing extra request for symbol.
- [x] - make sure that formatting in final result matches current version (though differences might be ok if they improve the experience)
- [x] - fix existing tests
- [x] - clean-up API surface - currently PR changes shapes/signatures of existing types and methods which will be a breaking change for anyone who consumed previous version of the compiler. Existing API that deal with string should be reverted back and new API that use `Layout` should be added instead of replacing existing ones.

per @vasily-kirichenko' comment:
- [ ] - bugfixes

Quick info:
image

Signature help:
image

Completion details:
image

### CODE REVIEW

**Comment by dungpa** [comment]
Woohoo! I've been waiting for this PR for so long.

**Comment by vasily-kirichenko** [comment]
It's just fantastic 🥇 🥇 🥇

**Comment by vasily-kirichenko** [comment]
As you have not mentioned any bugs in the to do list, I feel free to report first ones :)

Here `type` should be highlighted as keyword:

image

The namespace should not be highlighted, `bool` keyword is not highlighted, `ThreadPool` type is not highlighted:

image

**Comment by saul** [comment]
This look absolutely fantastic!

Another issue is that the indentation seems to be lost:
sketch 13

**Comment by vasily-kirichenko** [comment]
@vladima do I understand right that this color information can be used for normal semantic code highlighting in the editor?

**Comment by vladima** [comment]
I'm not sure that I understand the question: compiler uses layouts to pretty print various kinds of messages but it is not used to format the source text itself. For classification in the editor one should use `IEditorClassificationService` which I think F# language service already does

**Comment by saul** [comment]
Another bug - type parameters include the apostrophe prefix in the colouring. The editor doesn't colour the apostrophe when doing syntax highlighting - I'm not sure which is the preferred option here.

Another positive is that FSI's output can now be colourised too:
image

**Comment by cloudRoutine** [comment]
@saul including the apostrophe is correct, the current highlighting in the editor is wrong

**Comment by vladima** [comment]
per F# spec:
>typar :=
 _ -- anonymous variable type
 'ident -- type variable
 ^ident -- static head-type type variable

so I read it as `'` is considered part of the name

**Comment by vladima** [comment]
status update: fixed indentation and classification of types inside xml doc comments
image

image

**Comment by saul** [comment]
Another small issue - I've always noticed that "Full name: XXX" seems to be indented by a couple of spaces. I'm not sure whether this is by design or not, but it's always looked a bit strange. This is the case on master without your PR, just wondering if you'd be interested in fixing it if it's a bug.

**Comment by dsyme** [comment]
Wow, this is fantastic!

**Comment by dsyme** [comment]
> - clean-up API surface - currently PR changes shapes/signatures of existing types and methods which will be a breaking change for anyone who consumed previous version of the compiler. Existing API that deal with string should be reverted back and new API that use Layout should be added instead of replacing existing ones.

I think this is OK as long as FSharp.Core is stable - for various reasons we have been making pretty regular breaking changes in the surface arera of FSharp.Compiler.Service, and bumping major version numbers on the nuget package when we do.

**Comment by dsyme** [comment]
If anyone wants to make some basic improvements like 

* replacing ``struct/end`` by ``[<Struct>]``
* eliding ``interface/end`` altogether
* eliding ``class/end`` altogether

etc that would also be great

**Comment by vladima** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
Instance members are indented:

image

But static members sometimes are not:

(ok)
image

(wrong)
image

Actually I've found the only case where it's broken - `Async` type. The tooltip is huge, maybe it's the root cause.

**Comment by vasily-kirichenko** [comment]
Another catch - `namespace` keyword is not highlighted: 

image

**Comment by vladima** [comment]
Colors for module and namespace keywords are fixed. As for indentation I do agree that it is inconsistent with other cases however I'd prefer to fix this in a separate PR. Reasons:
- technically this is not a regression since it matches existing behavior for types with hidden representation
- current PR is already quite big and adding more things to it will make its review more complicated.

// cc @KevinRansom and @dsyme for opinions.

**Comment by saul** [comment]
One last issue @vladima:

image

Note that there are no blank lines around the separator, and there is no separator at the end of the tooltip. See @vasily-kirichenko's first screenshot in his last comment:
image

**Comment by cartermp** [comment]
@vladima Agreed re: indentation - unless it's a minor change, adding more improvements to this PR will make it more difficult to review and get merged.

**Comment by cartermp** [comment]
@vasily-kirichenko I've noticed the Async tooltip exploding in size in #1973 as well.  Perhaps there's some strange code path executed where it's not truncated, because in most situations it cuts off with a `...` about 1/3 of the way through listing all the members.

**Comment by vladima** [comment]
turned out fix is fairly simple:
image

**Comment by dsyme** [comment]
This looks good to me.  Unless there are other concerns I think we should accept this

**Comment by KevinRansom** [comment]
@vladima 

Thank you this is awesome work ...


Kevin

**Pull request merged**
