### PR TITLE
 Improve perf for common cases in setify

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by dsyme** [comment]
I don't think this complexity is worth it without evidence - and even if it mattered in particular cases I would  just say "get rid of the use of setify", as you've been doing

**Comment by forki** [comment]
Trying to come up with a benchmark.net "proof" soon.

Don Syme <notifications@github.com> schrieb am Mi., 23. Mai 2018, 19:13:

**Comment by vasily-kirichenko** [comment]
I'm for getting rid of it and removing from the codebase (or at least renaming and adding an XML doc comment with clear warning).

**Comment by dsyme** [comment]
> Trying to come up with a benchmark.net "proof" soon.

Yeah, this wouldn't rock it :) I'd need proof that the few remaining actual calls in the codebase were important (and when we discovered they were, we'd eliminate the use of the thing)

**Comment by forki** [comment]
I already looked at the remaining cases and I didn't find an obvious
improvement, yet. I mean setify actually is a good idea ;-)

Don Syme <notifications@github.com> schrieb am Mi., 23. Mai 2018, 19:28:

**Comment by KevinRansom** [comment]
@forki, @dsyme,  I am closing this because it has been inactive since May, and wasn't a strong contender even then, please reopen if you wish to pursue this further.

Thanks

Kevin

**Pull request closed without merging**
