### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by KevinRansom**
FX_NO_CANCELLATIONTOKEN_CLASSES is no longer used.

This was in for FSharp.Core 2.0 on Silverlight.

### CODE REVIEW

**Comment by dsyme** [comment]
Great

**Comment by dsyme** [comment]
Presumably FX_NO_TASK can also go, and others too?

**Comment by KevinRansom** [comment]
I think there are a bunch but have yet to do the analysis.

**Comment by KevinRansom** [comment]
@dsyme yep FX_NO_TASK  too.

**Comment by dsyme** [comment]
@ncave Do you need any of these kept around for Fable? (I doubt it)

**Comment by dsyme** [comment]
Suspect also 

    #if FX_NO_OPERATION_CANCELLED
    #if FX_NO_EXCEPTIONDISPATCHINFO

**Comment by KevinRansom** [comment]
I’m going through the list right now ☺

**Comment by ncave** [comment]
@dsyme I don't think Fable is using FSharp.Core directly, so it should be ok.
A lot of these flags can be employed to target netstandard1.3 or [work around](https://github.com/ncave/dotnet-js/blob/master/src/FSharp.Core/FSharp.Core.fsproj) shallow corlib implementations, but what's been cut so far seems fine.

**Comment by KevinRansom** [comment]
Good grief there is a ton of this stuff.

**Comment by dsyme** [comment]
-1000 so far.  You're winning

**Comment by cartermp** [comment]
It's so beautiful I might cry

screen shot 2017-08-22 at 9 11 53 pm

**Comment by vasily-kirichenko** [comment]
awesome :)

**Comment by matthid** [comment]
A bit late but is this something people like Fable or [fex](https://github.com/kjnilsson/fez) are using? At least parts of it?
/cc @kjnilsson @alfonsogarciacaro.

**Comment by KevinRansom** [comment]
@matthid.   It is unlikely, these were all modifications to fsharp core that allowed us to build different versions targeting different FSharp.Core.dlls.

If there are any modificationss that are needed can certainly be re-submitted, we can use id's that identify their use outside of this repo..

**Comment by dsyme** [comment]
Final score: +33 -1607.  Well done!

**Comment by saul** [comment]
Fantastic work, the best code is no code!

**Comment by kjnilsson** [comment]
[fez](https://github.com/kjnilsson/fez) mostly use the type AST to transform fsharp to core erlang so unless there were changes to the TAST it shouldn't be affected.

**Pull request merged**
