### PR TITLE
TypeChecker notifies name resolution sink about IL constant fields

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/3610

image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
It also fixed the same issue with literal module and class values:

image

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by dsyme** [comment]
@vasily-kirichenko Great work. Oddly there was no issue under https://github.com/fsharp/FSharp.Compiler.Service/issues tracking this.

Could you add a test please, under ``tests\service``?  Thanks

**Comment by vasily-kirichenko** [comment]
Done.

**Comment by dsyme** [comment]
Great - approved, once CI green

**Comment by dsyme** [comment]
@dotnet-bot Test Windows_NT Release_ci_part2 Build please

**Pull request merged**
