### PR TITLE
Merge mono fix to dev15.7

### PR DESCRIPTION
**Pull request by brettfo**
This is to hopefully fix the master to dev15.7 merges.  Once this is done I'll finish the others.

### CODE REVIEW

**Comment by brettfo** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please

**Comment by brettfo** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please

**Comment by brettfo** [comment]
Hanging test is `FSharp.Core.UnitTests.FSharp_Core.Microsoft_FSharp_Control.AsyncType.CancellationPropagatesToGroupImmediate` and can be run with:

``` bash
.\packages\NUnit.Console.3.0.0\tools\nunit3-console.exe --work:release\net40\bin release\net40\bin\FSharp.Core.UnitTests.dll --test=FSharp.Core.UnitTests.FSharp_Core.Microsoft_FSharp_Control.AsyncType.CancellationPropagatesToGroupImmediate
```

**Comment by dsyme** [comment]
Is that test passing on master?

**Comment by brettfo** [comment]
It doesn't exist in `master`, but it passes in current `dev15.6` and passes in current `dev15.7`, just not with this PR applied, and I have no idea what the difference is.  Test is [here](https://github.com/Microsoft/visualfsharp/blob/dev15.6/tests/FSharp.Core.UnitTests/FSharp.Core/Microsoft.FSharp.Control/AsyncType.fs#L346) and was added in #2534.

**Pull request merged**
