### PR TITLE
coreclr target for FSharp.LanguageService.Compiler

### PR DESCRIPTION
**Pull request by ncave**
Enabled coreclr target for FSharp.LanguageService.Compiler, and removed a few internal modifiers here and there to support Fable etc.

### CODE REVIEW

**Comment by dsyme** [comment]
@ncave FSharp.LanguageService.Compiler is a cut-down version of FSharp.Compiler.Service which is private to the Visual F# Tools.  It is not meant to have a public API.

Could you instead submit this to http://github.com/fsharp/FSharp.Compiler.Service as part of a larger PR to enable a coreclr build of that component?

(It is possible we should move all FSharp.Compiler.Service development to this repo but we're not there yet, partly to avoid this repo becoming a logjam for all work in this area).

**Comment by dsyme** [comment]
I'll close this since we can't remove the "internal" identifiers from this particular component.

**Comment by 7sharp9** [comment]
Could this be added to FCS instead perhaps?

**Comment by ncave** [comment]
@dsyme: Thank you for responding so quickly, can you please clarify what is the best way to maintain the three repositories in sync, as the language evolves? Should FCS be merged into fsharp/fsharp, can we make a coreclr branch in fsharp/fsharp that has FCS as well? What is the flow between fsharp/fsharp and ms/visualfsharp when not in sync?
It does make sense for the compiler service to be in the same repository with the compiler since they share so much code, so there will be less code to maintain.
The internal modifiers can be handled with defines to only expose modules in the compiler service, not in the compiler itself, if that's a requirement.

**Comment by 7sharp9** [comment]
I single repo is really needed, it makes working on compiler features a massive pain, not one I enjoy.   Maintaining three repos to test and develop is not good.

**Comment by dsyme** [comment]
@ncave  The FCS issue to discuss CoreCLR support is here: https://github.com/fsharp/FSharp.Compiler.Service/issues/465.  It's been dormant for a while but it's probably time to bring it to life again.  

The relationship between repositories is explained here:http://fsharp.github.io/2014/06/18/fsharp-contributions.html.  

Basically:

* We regularly merge from Microsoft/visualfsharp --> fsharp/fsharp --> fsharp/FSharp.Compiler.Service.  

* We reverse integrate some functionality from fsharp/FSharp.Compiler.Service. to Microsoft/visualfsharp opportunistically

* However some more nascent FCS functionality (like the typed expression trees that Fable uses) has not been brought across.  In effect the FCS repo is a proving ground for FCS features which is sufficiently high quality (or fast-to-fix) for the F# community tools such as Visual F# Power Tools, but which needs a lot of proofing in this repo.

@7sharp9 It's work. It's also culture change at Microsoft (e.g. do we have the energy to support our repos being compiled into Mono editions of things? Are we willing for community people to have the right to accept pull requests into this repo? ) 

We're gradually getting there. But honestly, don't expect that it would make things "easy".  if we merged all FCS and F# Mono work into this repo then it would become a real logjam: and build, test, bug tracking and CI would become harder. 

Of course, one repo would mean no integration.  But you might find that even mid-quality FCS PRs are just not accepted for fear of destabilization.  At Microsoft it only takes one bad bug in a shipping RTM or Update of Visual Studio to make people very cautious.

TBH I don't actually find it that hard to work on compiler features here, as it lets me focus on Windows and CoreCLR support at Microsoft quality levels.  I think it is, however, very hard to do language/compiler work on a non-Windows machine (which I think is what you do).  That is changing with CoreCLR support in this repo.

**Comment by ncave** [comment]
Thank you for the extensive response, I'll wait for [fsharp/fsharp#558](https://github.com/fsharp/fsharp/pull/558).

**Comment by dsyme** [comment]
@ncave Let's follow up on https://github.com/fsharp/FSharp.Compiler.Service/issues/465

**Pull request closed without merging**
