### PR TITLE
Fix for 82 - Scope of types for named values in attributes improperly set 

### PR DESCRIPTION
**Pull request by dsyme**
This is a preliminary fix for #82. Testing involves the WSDL type provider so is a bit tricky.  @vladima - do you have advice?

### CODE REVIEW

**Comment by vladima** [comment]
@dsyme using WSDL type provider should not be necessary, I'll try to come up with a small isolated example

**Comment by dsyme** [comment]
Thanks @vladima!!

**Comment by vladima** [comment]
source code for the repro can be found in [this gist](https://gist.github.com/vladima/4f1b6c248ec21ff45fa1)

1. compile program.dll out of program.cs
2. compiler mirror.dll out of mirror.fs and provided types API (not included in gist) - result mirror.dll is a type provider assembly that will merge types from program.dll into the assembly that consumes type provider
3. compile client.exe out of client.fs - type `Client+T` in this assembly will have method `Run` annotated with  `FaultContractAttribute` and type of property `ProtectionLevel` of this attribute will be incorrect because of the original bug

**Comment by latkin** [comment]
This has been idle for over 2 months, closing out.

Please re-open when the fix is ready and tests are implemented, we'd be happy to include in an update release.

**Comment by dsyme** [comment]
This is a real bug that we shouldn't leave lying around.  The fix is good AFAIK, we should either test manually and apply or add the automated testing.

**Comment by latkin** [comment]
Ok if you think it's no longer in the "prelim" stage then we should take it. Are you planning to add tests, or should I do that myself when I merge it?

**Comment by dsyme** [comment]
I believe the fix to be good in principle, I just haven't tested it even by hand.  I suppose we should add the bespoke test mentioned by @vladima above.  I'd hoped there would be a test that didn't involve a type provider though.

**Comment by dsyme** [comment]
Closing to resubmit to OOB

**Pull request closed without merging**
