### PR TITLE
Struct Records and Unions have ValueType super type

### PR DESCRIPTION
**Pull request by thinkbeforecoding**
This is a fix for #2609 .

It works with Nullable and the example with UnmanagedMemoryAccess from FileMappings I added in the comments.

I should probably add tests, but I'll need a hint to find where other tests on the topic can be found.

### CODE REVIEW

**Comment by thinkbeforecoding** [comment]
I'm adding conformance tests to check that Nullable with struct records and unions compile correctly

**Comment by thinkbeforecoding** [comment]
The NT Release ci part2 build is failing because the connection with the agent went offline:
04:12:58 Agent went offline during the build
04:12:58 ERROR: Connection was broken: java.io.IOException: Connection aborted

Appart from that, the PR seems ok.

**Comment by thinkbeforecoding** [comment]
Now checks pass !

**Comment by dsyme** [comment]
LGTM - thanks @thinkbeforecoding !

**Comment by dsyme** [comment]
Thanks again @thinkbeforecoding

**Pull request merged**
