### PR TITLE
Swap AppVeyor badge

### PR DESCRIPTION
**Pull request by GeorgeHahn**
Swap AppVeyor badge for one from http://shields.io/ to match the PR and issue badges.

I didn't see a 'minimum bar' for doc changes in the contributing guidelines; sorry if I missed it.

### CODE REVIEW

**Comment by KevinRansom** [comment]
Hi George.  Thank you for this Pull Request, I'm afraid that before we can review it further you will need to sign a CLA.  
* You can find the CLA here: https://cla.msopentech.com/
* You can find the Contributions page here: https://github.com/Microsoft/visualfsharp/blob/master/CONTRIBUTING.md


I notice that the front page doesn't mention this requirement, I apologise for that, we are still in our early days on Github.

Thanks

Kevin

**Comment by KevinRansom** [comment]
Oh yes easily possible, thanks for that.

**Comment by latkin** [comment]
This looks great, we'll apply it as soon as the CLA gets through and the lawyers mark it approved (should be within a day or two).

**Comment by latkin** [comment]
I'm still not seeing a CLA on file.  It usually appears in the list pretty quickly, even as "tentative" status before final approval.  Are you sure it's been signed by your employer and fully submitted?

**Comment by GeorgeHahn** [comment]
I think I filled the 'projects' field out incorrectly, so I just resubmitted it. Sorry about that! I suppose I should have just filed this as an issue :cat:

**Comment by KevinRansom** [comment]
Thank you for this contribution.

**Pull request closed without merging**
