### PR TITLE
Don't suggest types that are not accessible

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
ok I think the suggestions are fixed.

Regarding reporting of multiple errors:

image

@dsyme this looks supicious. we want do error recovery here, but the error was already reported

**Comment by forki** [comment]
This fixes the part of #1548 where inaccessible types where reported

**Comment by forki** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by forki** [comment]
@kevin_c_ransom all PRs have to rebased for the tests to succeed. That's nuget for you

**Comment by forki** [comment]
rebased.

**Comment by dsyme** [comment]
```
1) Failed : FSharp-Tests-Core+TypecheckTests.sigs neg group13
Error running command 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\..\fsharpqa\testenv\bin\diff.exe' with args 'neg15.err neg15.bsl normalize' in directory 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\typecheck\sigs'. ERRORLEVEL 1
at TestFramework.checkResult(CmdResult result) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 243
at SingleTest.fsdiff@185-2.Invoke(String a, String b) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\single-test.fs:line 190
at SingleTest.singleNegTest(TestConfig cfg, String testname) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\single-test.fs:line 195
at FSharp-Tests-Core.TypecheckTests.negGroup(IEnumerable`1 negs) in D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\tests.fs:line 1705
```

**Comment by forki** [comment]
fixed!

**Comment by dsyme** [comment]
This file has been added:

    tests/fsharpqa/Source/Warnings/Repro1548.dll

I don't think it should be there?

**Comment by forki** [comment]
IIRC (it's long time) but that file is needed for the repro. Please take a
look at the corresponding test.

Am 24.11.2016 11:00 nachm. schrieb "Don Syme" <notifications@github.com>:

**Comment by dsyme** [comment]
Oh yes https://github.com/Microsoft/visualfsharp/pull/1552/files#diff-982e344f51d5cf82b7b82545f89e871dR32

**Comment by dsyme** [comment]
Merged, great to have this in.

**Pull request merged**
