### PR TITLE
Deprecate dictionary.of list

### PR DESCRIPTION
**Pull request by smoothdeveloper**
Addresses #2297

The initial reasoning was when I compared performance of those snippets of code:

```fsharp
let inline ofList l = 
    // original code in compiler
    let dict = new System.Collections.Generic.Dictionary<_,_>(List.length l, HashIdentity.Structural)
    l |> List.iter (fun (k,v) -> dict.Add(k,v))
    dict

let inline ofSeqWithKnownCount (n: int) s  =
    let dict = new System.Collections.Generic.Dictionary<_,_>(n, HashIdentity.Structural)
    for kvp: KeyValuePair<_,_> in s do
      dict.Add(kvp.Key, kvp.Value)      
    dict

let makeDict1 (n:int) =
  [for i in 0 .. n do yield i,i ] |> ofList

let makeDict2 (n: int) =
  // winner
  let dict = Dictionary<_,_>(n)
  for i in 0 .. n do
    dict.Add(i,i)
  dict

let makeDict3 (n: int) =
  seq { for i in 0 .. n do yield KeyValuePair<_,_>(i,i) } |> ofSeqWithKnownCount n

let makeDict4 (n: int) =
  [ for i in 0 .. n do yield KeyValuePair<_,_>(i,i) ] |> ofSeqWithKnownCount n

let makeDict5 (n: int) =
  [| for i in 0 .. n do yield KeyValuePair<_,_>(i,i) |] |> ofSeqWithKnownCount n
```

I compared with populating dictionaries of same size I've noted from evaluating a small set of scripts.

Using FSI and `#time`, the procedural code doesn't generate much garbage and ran about 10x faster of worst one, but this is totally out of context of the compiler workload.

I think it is good to get rid of leaky abstraction:
* call to List.length, some lists were about 1k elements in my test
* procedural code replacing the old code isn't much longer or less readable
* with such helpers available, there is opportunity for getting into pitfalls in new places

The end result of those changes is basically 0% performance change, I've noticed 0.3% variation between master and this (mostly in favor of master) but this was on underpowered laptop (i7 2.1ghz), if you have feeling there is opportunity to do better measurement or think there is a risk with proposed changes, please let me know.

### CODE REVIEW

**Comment by FunctionalFirst** [comment]
The helper used HashIdentity.Structural for the comparer, but the new code doesn't. Is that an issue?

**Comment by smoothdeveloper** [comment]
@FunctionalFirst thanks for the review, it is my mistake and I'm going to fix it.

**Comment by KevinRansom** [comment]
@smoothdeveloper is this still a live PR?

thanks 

Kevin

**Comment by smoothdeveloper** [comment]
@KevinRansom there is no visible performance gain in this PR, but the deprecated construct is quite wasteful (we now save a call to List.length + all allocations done to build the throwaway list).

I prefer the construct not be available in case it would be used in place where it could actually hurt the performance.

The only place I wonder if I made the correct choice is in src/fsharp/MethodCalls.fs where I pass `paramVars.Length`, but I think that default is fine (there shouldn't be more than few dozens of parameters).

I have no objection at discarding the PR if this doesn't meet requirements for visible improvement or other reason.

**Comment by smoothdeveloper** [comment]
@dotnet-bot test this please

**Comment by smoothdeveloper** [comment]
The CI error are getting myself concerned... What build commands should I issue to get a good grasp of what is going wrong locally?

**Comment by dsyme** [comment]
@smoothdeveloper Look at the raw logs in each of the CI runs

**Comment by smoothdeveloper** [comment]
@dsyme / @KevinRansom I fixed issues it is green on Jenkins, but AppVeyor is queued for a long time now.

Note that this PR contains #2296 that I closed.

Thanks for bearing with me.

**Pull request merged**
