### PR TITLE
Build stability --- remove maxcpucount from msbuild switches

### PR DESCRIPTION
**Pull request by KevinRansom**
Build has been quite unstable, locally and on the CI for a few days.

trying to revert the maxcpu change.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test this please : passed let's try again.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please : passed let's try again.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please : passed let's try again.

**Comment by KevinRansom** [comment]
Okay that seems to work relatively well. Going to merge it.

**Comment by dsyme** [comment]
Hmmm.. Would be good to solve the underlying issue at some point :) Any links to unstable build logs?  

Note that building VisualFSharp.sln in Visual Studio uses multi-proc build by default so contributors are exposed to any problems

**Comment by KevinRansom** [comment]
The build is going to get obliterated shortly.   The move to netstandard2.0 will change the way we do virtually everything.  So I would just hold off trying to fix it for now.

**Comment by dsyme** [comment]
> The build is going to get obliterated shortly.   The move to netstandard2.0 will change the way we do virtually everything.  So I would just hold off trying to fix it for now.

Okey dokey.

**Pull request merged**
