### PR TITLE
[WIP, Upstream bug] InlineRenameService adds/removes double backtickes automatically

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by KevinRansom** [comment]
@vasily-kirichenko is this wip or done?

**Comment by forki** [comment]
It's WIP and needs work upstream in roslyn. From #2232:

> Roslyn does support amending new symbol name, but it's apparently broken, see dotnet/roslyn#16460. 
> I cannot see how we can implement this request at the moment.
> /cc @CyrusNajmabadi @Pilchie

**Comment by saul** [comment]
I'll take a look at getting this fixed in Roslyn this weekend.

**Comment by saul** [comment]
PR for getting the upstream bug is open at dotnet/roslyn#16809.

**Comment by forki** [comment]
:kiss:

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@vasily-kirichenko 
Thanks for this work

Kevin

**Pull request merged**
