### PR TITLE
Test CI job after update to netci.groovy

### PR DESCRIPTION
**Pull request by dsyme**
See https://github.com/Microsoft/visualfsharp/pull/4371

### CODE REVIEW

**Comment by dsyme** [comment]
If anyone can tell me why this says "Ubuntu14.04 Release_fcs Build" I'd be very glad. The netci.groovy file in master clearly specifies Ubuntu16.04, and there is no mention of Ubuntu14.04

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@mmitche Sorry - Note that I reversed the update Ubuntu 14.04 in a subsequent PR. https://github.com/Microsoft/visualfsharp/pull/4373.  However that PR includes a change to get a specific version of Mono, so we should be able to see if the changes are taking effect

**Comment by dsyme** [comment]
@mmitche Looking at a recently completed build such as https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/release_fcs_ubuntu14.04_prtest/962/consoleText it seems to me that recent changes to netci.groovy are not having any effect.

**Comment by dsyme** [comment]
@mmitche Could it be we're taking our netci.groovy from another branch, e.g. dev15.5 or dev15.6?

**Comment by dsyme** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@mmitche OK, so Ubuntu16.04 is showing, but  Ubuntu14.04 is still showing too.  Any magic I need to do to flush this?

**Comment by mmitche** [comment]
Jenkins can't delete it.  The status is simply a mapping of hash->string->status.  You can push a new commit and these will go away.

**Comment by dsyme** [comment]
> You can push a new commit and these will go away.

ok thanks

**Comment by dsyme** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
sudo is not enabled by default on most of the VM images.  The outerloop images do have this enabled.  The image version (usually 'latest') can be set to 'outer-latest' in this case to enable passwordless sudo, which would enable your scenario.

**Comment by dsyme** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@mmitche OK, trying to set that here: https://github.com/Microsoft/visualfsharp/pull/4382

**Comment by dsyme** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@dotnet-bot test ci please

**Comment by dsyme** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@dotnet-bot test Windows_NT Release_net40_no_vs Build please

**Comment by dsyme** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build  please
@dotnet-bot test Windows_NT Release_net40_no_vs Build

**Comment by dsyme** [comment]
@dotnet-bot test Windows_NT Release_ci_part4 Build please

**Comment by dsyme** [comment]
For the record:
* Part 1 =  34 min total from scheduled to completion.
* Part 2 = 47 min total from scheduled to completion.
* Part 3 = 27 min total from scheduled to completion.
* Part 4 = 30 min total from scheduled to completion.

**Pull request closed without merging**
