### PR TITLE
Make ErrorStrings properties instead of evaluating them in cctor

### PR DESCRIPTION
**Pull request by vbfox**
While investigating the `Argu` performance problem described in https://github.com/fsprojects/Argu/pull/105 one of the things that was hard to optimize away was that `fsharp.core!<StartupCode$FSharp-Core>.$Prim-types..cctor()` is taking between 30 and 70ms to load satellite assemblies as soon as an F# application uses some specific parts of F# core (`Seq.distinct` in Argu case) and the reason is that LanguagePrimitives.ErrorStrings are static properties defined as let members and so they are present in the static constructor generated for the `Prim-types` file.

While a few dozen milliseconds aren't a problem for big applications, during startup for command lines applications that might run in hundreds of milliseconds it's a big part of their runtime. It's also one of the only case I could find where the strings are resolved in the static constructor, all other calls to SR.GetString are done directly without any caching.

The consequence for speed on a simple Argu usage can be seen here in the top left (`OTHER <<mscorlib.ni!S` is  `OTHER <<mscorlib.ni!System.Resources.ResourceManager.GetString(...)>>`) :

flame graph

* As the members are part of the public signature of FSharp.Core I kept the same signature (The surface area files haven't been touched).
* Regarding the behavior it should be the same except that the culture used for the error messages will be the current one at the time of the call instead of whatever was the current culture when the static constructor was called (But it sounds like a bugfix to me 😉)

### CODE REVIEW

**Comment by forki** [comment]
giphy 4

@vbfox for the noobs like me. can you please explain the flame graph? what are we seeing?

**Comment by vbfox** [comment]
@forki First this flamegraph is without the optimization (As it's the one I did while measuring Argu)

Vertical axis is call stack depth, horizontal is run-time (So not clock time, things on the left didn't occur before things on the right)

The left right order is actually just time-spent, over a parent box children are organized with the one taking the longest time on the left.

So the width of the boxes give how much time they took and their height how far did the rabbit hole goes.

Two constructs are interesting to look for:
* Plateau like on the top left here where a single call goes out of the app code and take a long time (GetString)
* multi-candle structures where lot of small successive very deep calls accumulate (Calling reflection on a lot of small DUs here)

**Comment by enricosada** [comment]
I think is ok. awesome work.

I tried fix it some times ago but my way (use method instead of files) introduced a regression in FSharp.Core (https://github.com/Microsoft/visualfsharp/issues/486 for fsharp.core 4.x and https://github.com/Microsoft/visualfsharp/pull/497 for fsharp.core 3.x), breaking binary compatibility.
But i used methods instead of static properties, dunno why i was sure these where static fields, not properties.

This way i think make the thing possibile do to it.

But please check these scenario so this change doesnt add a regression. issue is explained in https://github.com/Microsoft/visualfsharp/pull/694#issuecomment-149828712

Issue was, these properties get inlined into built assemblies, like for `Array.last` directly.

> As the members are part of the public signature of FSharp.Core I kept the same signature (The surface area files haven't been touched).

AWESOME!

> Regarding the behavior it should be the same except that the culture used for the error messages will be the current one at the time of the call instead of whatever was the current culture when the static constructor was called (But it sounds like a bugfix to me 😉)

it is :D fix https://github.com/Microsoft/visualfsharp/issues/159

**Comment by vbfox** [comment]
@enricosada Didn't know this had been already tried, I'll look at the past issues and try to reproduce them.

If they can't be ""moved"" to properties (They are already properties at the assembly level but this changes a few of the attributes) I'll look at splitting the module in a separate file to get a separate static constructor.

**Comment by vbfox** [comment]
@eiriktsarpalis I agree that the static constructors should be per-module (well per-module-per-file) I was actually surprised it wasn't the case when investigating this. Don't know why it's the case.

**Comment by enricosada** [comment]
> If they can't be ""moved"" to properties (They are already properties at the assembly level but this changes a few of the attributes) I'll look at splitting the module in a separate file to get a separate static constructor.

Last time my change was move invasive (changed to methods). maybe now is ok, i just added that comment to check the previous regressions to be sure.
Again awesome work, i think this is a real perf issue for fast console app (long running doesnt care), so a nice scenario to fix.

**Comment by matthid** [comment]
What is concerning is that this pops up the second time after hours of investigation ;)

We don't know how many have given up or did not sent a PR...

It would be nice if we could fix it this time :)

**Comment by eiriktsarpalis** [comment]
@vbfox alternatively you could just make the offending values lazy

**Comment by KevinRansom** [comment]
I really like this change and would dearly love to take it.  However, It will break existing compiled code for example when a developer is using one of the inlined function, which expects the value to be retrieved from a field, that has been replaced by a property.

This could happen if you built against 4.1 FSharp.Core used one of the inlined functions that expects this field to exist.  And then a binding redirect updated you to a more recent FSharp.Core with this changed to a property.  You would end up with a MissingFieldException.

So this is definitely a breaking change, that would quite likely break an application.

What I suggest is that we
1.    Keep the current module as it is, add a dirty great comment that it is purely to service inlined code in existing compiled binaries.
2.    Add a new type that looks just like the one in this PR, with the properties.
3.    Update all existing FSharp.Core code to use the new properties.

This would mean that we bug fix the culture issue.  And get the lazy recource load for the exact error that only occurs on an actual error.

**Comment by cartermp** [comment]
@KevinRansom how would we feel about slapping an `[<Obsolete>]` attribute on the module?

**Comment by KevinRansom** [comment]
Yes ... that would definitely be the right thing to do.  It would remind us not to use it :-)

**Comment by vbfox** [comment]
@KevinRansom Theses let bindings being fields in the current version doesn't match what I'm seeing. Maybe there is something stupid that i'm missing but here is an IL DASM of FSharp.Core before my changes (4.4.1.0 here) :

```asm
.method public specialname static string 
        get_AddressOpNotFirstClassString() cil managed
{
  // Code size       6 (0x6)
  .maxstack  8
  IL_0000:  ldsfld     string '<StartupCode$FSharp-Core>'.'$Prim-types'::AddressOpNotFirstClassString@656
  IL_0005:  ret
} // end of method ErrorStrings::get_AddressOpNotFirstClassString

.property string AddressOpNotFirstClassString()
{
  .custom instance void Microsoft.FSharp.Core.CompilerMessageAttribute::.ctor(string,
                                                                              int32) = ...
  .custom instance void Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype Microsoft.FSharp.Core.SourceConstructFlags) = ( 01 00 09 00 00 00 00 00 ) 
  .get string Microsoft.FSharp.Core.LanguagePrimitives/ErrorStrings::get_AddressOpNotFirstClassString()
} // end of property ErrorStrings::AddressOpNotFirstClassString
```

And after:

```asm
.method public specialname static string 
        get_AddressOpNotFirstClassString() cil managed
{
  // Code size       23 (0x17)
  .maxstack  8
  IL_0000:  call       class [mscorlib]System.Resources.ResourceManager Microsoft.FSharp.Core.SR::get_ResourceManager()
  IL_0005:  ldstr      "addressOpNotFirstClass"
  IL_000a:  call       class [mscorlib]System.Globalization.CultureInfo Microsoft.FSharp.Core.SR::get_Culture()
  IL_000f:  tail.
  IL_0011:  callvirt   instance string [mscorlib]System.Resources.ResourceManager::GetString(string,
                                                                                             class [mscorlib]System.Globalization.CultureInfo)
  IL_0016:  ret
} // end of method ErrorStrings::get_AddressOpNotFirstClassString

.property string AddressOpNotFirstClassString()
{
  .custom instance void Microsoft.FSharp.Core.CompilerMessageAttribute::.ctor(string,
                                                                              int32) = ...
  .get string Microsoft.FSharp.Core.LanguagePrimitives/ErrorStrings::get_AddressOpNotFirstClassString()
} // end of property ErrorStrings::AddressOpNotFirstClassString
```

A few attributes changed because I can't use them but they are properties in both cases.

Here is part of a call to List.max compiled against 4.4.3.0 that was inlined :

```asm
  IL_0023:  stloc.1
  IL_0024:  ldloc.1
  IL_0025:  call       instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<int32>::get_TailOrNull()
  IL_002a:  brfalse.s  IL_002e
  IL_002c:  br.s       IL_003e
  IL_002e:  call       string [FSharp.Core]Microsoft.FSharp.Core.LanguagePrimitives/ErrorStrings::get_InputSequenceEmptyString()
  IL_0033:  ldstr      "list"
  IL_0038:  newobj     instance void [mscorlib]System.ArgumentException::.ctor(string,
                                                                               string)
```

Once this program was compiled I replaced FSharp.Core with my modified version and there was no problems. I it too with the exact same code compiled in VS 2015 against 4.4.0.0 and it also worked.

**Comment by vbfox** [comment]
BTW it has been a property since a long time, here is FAKE 1.46 from feb 2011 build against FSharp.Core 2.0.0.0

```asm
      // [267 11 - 267 107]
      IL_0046: call         string [FSharp.Core]Microsoft.FSharp.Core.LanguagePrimitives/ErrorStrings::get_InputSequenceEmptyString()
      IL_004b: ldstr        "source"
      IL_0050: newobj       instance void [mscorlib]System.ArgumentException::.ctor(string, string)
      IL_0055: throw        
      IL_0056: nop          
```

**Comment by KevinRansom** [comment]
They are indeed static property gets, which kind of surprises me a bit, I believe that means this should work fine even for the binding redirect case

**Comment by vbfox** [comment]
After fighting binding redirects and framework version upgrade I managed to get FAKE 1.46 running against my patched FSharp.Core and showing the error message :

```
G:\temp\oldfake>fake test.fsx
FakePath: .\FakeLib.dll
FAKE - F# Make - Version 1.46.1.0
LocalBuild
FAKE Arguments:
("test.fsx", "1")

FSI-Path: fsi.exe
MSBuild-Path: c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
Running Buildscript: test.fsx
fsi.exe test.fsx
System.ArgumentException: The input sequence was empty.
Parameter name: source
   at Fake.TargetHelper.WriteTaskTimeSummary[a](a total) in D:\Builds\Fake\master\src\app\FakeLib\TargetHelper.fs:line 174
   at <StartupCode$FSI_0001>.$FSI_0001.main@()
Stopped due to error

---------------------------------------------------------------------
Build Time Report
```

**Comment by dsyme** [comment]
@vbfox @KevinRansom We need to double check something...

You're correct that cross-module references to "module let bindings" are via property-getters.

However it's not just about IL binary compatibility. There is also the question of the F# metadata blob (containing the inline data), and whether that information carried in assemblies that have inlined references to these things, and in turn expose them, can still be correctly resolved.

The metadata blob in FSharp.Core is not an issue, since of course that is updated, but the metadata blobs in previously compiled F# libraries may contain a relevant reference.

Please test as follows:

1. put this code in a library lib.fs:

```fsharp
namespace Statistics 

module Seq = 
    let inline statistics x = (Seq.average x, Seq.sum x)
    let inline statisticsBy f x = (Seq.averageBy f x, Seq.sumBy f x)
```

2. Compile this library against FSharp.Core nuget package 4.0.0.1

3. Reference the library from **an application that references your new FSharp.Core at compile time** containing this:

```
open Statistics
let stats = Seq.statistics (Seq.empty: double seq)
printfn "stats = %A" stats

```

4. If it compiles, you're ok (the inlined references coming from the optimization blob of the library have been resolved correctly).  But also check it runs and gives the exception "System.ArgumentException: The input sequence was empty" which is the string we're after

We also need to add scenarios like this as basic tests.

**Comment by vbfox** [comment]
@dsyme thanks that's the information I was looking for about what could go wrong. I'll test that :)

**Comment by vbfox** [comment]
Ah now I have the following error : 

```
FSC: error FS0193: The module/namespace 'ErrorStrings' from compilation unit 'FSharp.Core' did not contain the val '{MemberParentMangledName = null; MemberIsOverride = false; LogicalName = "InputSequenceEmptyString"; TotalArgCount = 0;}'
```

I'll move the current module to a separate file, obsolete it and create a new version with functions instead. It'll pollute the public API a bit but it's safer.

**Comment by dsyme** [comment]
> I'll move the current module to a separate file...

Moving to a separate file might be hard because of compilation-order reasons for FSharp.Core (the first 2-3 files of FSharp.Core are sensitive in regard to this)

**Comment by vbfox** [comment]
I'm open to suggestions :)

But I don't want to end in the "Too complex so we're slow forever because compat" slot.

Other solutions I see are :
* Fake the metadata somehow so that the static-property version looks like the val version
* Write the module & it's metadata entirely in IL (is it possible ?)
* Change the compiler so that cctor are generated per-file-per-module instead of per-file (With the bonus that it might solve this kind of problems in other places too)
* Rewrite the IL after the build to remove the cctor parts and replace the properties.

**Comment by dsyme** [comment]
@vbfox Ah I understand now - sorry.

hmmm... the module can't be moved to a separate file because it is a nested module of ``LanguagePrimitives``

```
namespace Microsoft.FSharp.Core
    ...
    module LanguagePrimitives =  
        ...

        module (* internal *) ErrorStrings =
           ...
```
Let me think about this one.

**Comment by vbfox** [comment]
@dsyme Thinking about it there is also a "Meh" solution to that problem, that has the advantage of being simple:

Replacing the values in this static class by their literal string equivalent in english.

Previously compiled binaries running against that version and that use one of inlined methods will get the english error message (so it's a small compat change) but it has the big advantage of being extremely simple.

**Comment by matthid** [comment]
> Replacing the values in this static class by their literal string equivalent in english.

Maybe that in combination what @KevinRansom suggested above?

**Comment by vbfox** [comment]
> Maybe that in combination what @KevinRansom suggested above?

Yes essentially marking the current module obsolete with big comment saying just don't touch it ever, adding a new type with properties or functions, using it across the codebase :)

**Comment by matthid** [comment]
@dsyme Can we patch the compiler that it accepts such a IL compatible changes even when it gets old metadata? I think no-one would expect that to fail. Or is it a problem for `FSharp.Core` only?

**Comment by dsyme** [comment]
> @dsyme Can we patch the compiler that it accepts such a IL compatible changes even when it gets old metadata? I think no-one would expect that to fail. Or is it a problem for FSharp.Core only?

In theory yes, but FSharp.Core we publish must typically work with previous-generation F# compilers - we don't promise it, but we'd like that to be the case where possible as nuget tooling will recommend them.

I guess you should try to move all of LanguagePrimitives module into a separate file and see if the .cctor gets triggered in the cases you care about. Looking through the API of LanguagePrimitives it is things like UnboxGeneric and generic equality which will trigger it, but that's not so bad I suppose.

You might need three files - one for everything in prim-types.fs up to LanguagePrimitives, one for LanguagePrimitives, and one for the rest.

We should also add some kind of test to pin down and gradually reduce the use of startup bindings (i.e. .cctor) in FSharp.Core.  I'm annoyed with myself because I knew right from the start of F# that .cctor's was best avoided for maximum perf, but we didn't test for that and it crept back in over time.

**Comment by matthid** [comment]
> In theory yes, but FSharp.Core we publish must typically work with previous-generation F# compilers - we don't promise it, but we'd like that to be the case where possible as nuget tooling will recommend them.

Yes I assumed that, but I also feel like we should add that change anyways in order to make it easier in the future? While I feel like it belongs to this fix/discovery we can track that in a separate issue.

**Comment by vbfox** [comment]
Sadly *generic equality* is the thing that was triggering it for me.

So here is what I propose (essentially what I mentioned before)

* `ErrorStrings` module is kept, but with english constants, and it's obsolete.
* A new `ErrorStringGetters` module is introduced  with the methods versions
* Old code that inlined the methods will work as before except that the errors strings will always be in english
* New code will get the correct behavior, fixing #159
* In any case the static constructor won't contain the GetString calls so they won't slow down startup

That's what I did in the new commits I pushed.

**Comment by KevinRansom** [comment]
@vbfox, @dsyme 

So ... MacDonalds is not a great place to think, when I got home, I had a bit more of a think and I believe this may be what you are looking for:
https://github.com/Microsoft/visualfsharp/pull/4482

All I did was turn the module into a type, and give it static members. It matches the original module well enough for the clr to load it.  Anyway this seems like it might have the lazy qualities you need.

You might want to try it out?

I have a little console.writeline "Hello" in there to convince myself the resource fetch didn't happen before main started.  Just print some text in main, and then provoke the error.
If hello comes up after the in main line, you know it occurred afterwards.

````
        type (* internal *) ErrorStrings =

            // inline functions cannot call GetString, so we must make these bits public

            static member AddressOpNotFirstClassString with get () = SR.GetString(SR.addressOpNotFirstClass)

            static member NoNegateMinValueString with get () = SR.GetString(SR.noNegateMinValue)

            // needs to be public to be visible from inline function 'average' and others

            static member InputSequenceEmptyString with get () = SR.GetString(SR.inputSequenceEmpty) 

            // needs to be public to be visible from inline function 'average' and others

            static member InputArrayEmptyString with get () = System.Console.WriteLine("Hello"); SR.GetString(SR.arrayWasEmpty) 

            // needs to be public to be visible from inline function 'average' and others

            static member InputMustBeNonNegativeString with get () = SR.GetString(SR.inputMustBeNonNegative)


````
This is the simple program I tested it with, I compiled it with the released compiler, then copied in the new FSharp.Core.dll and observed it work.

````
open System


[<EntryPoint>]
let main argv =
    printfn "In main"
    let x = Array.empty<float> 
    printfn "%A" (Array.average x)
    0 // return an integer exit code

````

produces this output:
````
c:\kevinransom\visualfsharp>c:\users\kevinr\source\repos\ConsoleApplication12\ConsoleApplication12\bin\Debug\ConsoleApplication12.exe
In main
Hello

Unhandled Exception: System.ArgumentException: The input array was empty.
Parameter name: array
   at Program.main(String[] argv) in c:\users\kevinr\source\repos\ConsoleApplication12\ConsoleApplication12\Program.fs:line 9

c:\kevinransom\visualfsharp>
````
note: In Main followed by Hello.

Let me know what  you think?

Kevin

**Comment by dsyme** [comment]
@KevinRansom The 'add a new class' approach doesn't solve the performance problem alone because the cctor is triggered for accessing anything in the _file_. Initialization in F# is on a file-by-file basis. 

@vbfox Perhaps another approach is to use hardwired strings if the appropriate locale is English, which may be a much quicker startup check. Other locales could be similarly hardwired. The key thing would be to avoid resource cracking in the cctor I presume?

**Comment by vbfox** [comment]
@dsyme I was assuming that localization in such an edge case (that is already buggy) wasn't so important. But yes we can hardcode all current locales not only English. The big perf problem is the IO for assembly loading. A single lookup in a table would be ok.

**Comment by vbfox** [comment]
@dsyme Here is a version hardwiring all languages I found in the codebase :)

I tried a few solutions but as this code is really early in the compiler there aren't a lot of choice as not a lot of things are available (equality, tuples, ...)

In the end I generated a simple sequence of `if` without trying for any generalization.

**Comment by KevinRansom** [comment]
@dsyme 
Does it solve the perf issue described in the snip below for everything except error paths that use those strings?

Or is there someway these satellite assemblies and the resource groveling will happen in a non-error code path?

<snip>
While investigating the Argu performance problem described in fsprojects/Argu#105 one of the things that was hard to optimize away was that fsharp.core!<StartupCode$FSharp-Core>.$Prim-types..cctor() is taking between 30 and 70ms to load satellite assemblies as soon as an F# application uses some specific parts of F# core (Seq.distinct in Argu case) and the reason is that LanguagePrimitives.ErrorStrings are static properties defined as let members and so they are present in the static constructor generated for the Prim-types file.
</snip>

**Comment by dsyme** [comment]
@vbfox Wow, thanks

That said, my belief is we can really take the change as it was at commit 70326e7 (English-only).  The suggestion about non-English strings was really a last-resort suggestion

At that commit:
* the perf problem is solved for all cases AFAICS
* the error messages are always in correct languages (except for the rare case of old binaries that run as parts of apps containing a binding redirect to new FSharp.Core.dll *and* use inlined List.sumBy etc. code *and* throw one of these exceptions in a user-visible way)
* binary/source compat is preserved 
* we don't insert a bunch of non-English strings into the source code for FSharp.Core.dll

> Does it solve the perf issue described in the snip below for everything except error paths that use those strings?
> Or is there someway these satellite assemblies and the resource groveling will happen in a non-error code path?

My understanding is that the PR at commit 70326e7  (or also at e3b2aeb) solves the perf problem in all non-error cases - there will be no satellite assembly loading or resource grovelling in non-error cases, for any code that runs using this FSharp.Core at runtime.

**Comment by KevinRansom** [comment]
@dsyme, @vbfox 

Folks, I have an alternate proposal over here: https://github.com/Microsoft/visualfsharp/pull/4503

This proposal makes a modification to the compiler, which tells it to generate a Top Value with a property but no backing field.  The compiler only does this for Values marked with the ValueAsStaticProperty attribute, and it only works when building for fsharp.core.dll.

The nice thing about this, is ther are no new API's, the inlined stuff works, and there are no scenarios when the .cctor can eagerly execute that code.  Whats more, if there are other FSharp.Core .cctor related startup issues we can use the same technique if necessary.

Let me know what you think

Kevin

**Comment by dsyme** [comment]
@vbfox I think @KevinRansom's PR is the way to go.  It is hacking the compiler to do what we need, but using a fairly well established compiler feature  to do that.  Let's continue the discussion over there?

**Comment by vbfox** [comment]
👍

**Comment by KevinRansom** [comment]
@vbfox thanks for this work.  I learned quite a bit about inlined F# scenarios from it that I only partially understood before.  The subtlety of inlining an implementation, that itself uses inlined F# core code more or less blew my mind.

Kevin

**Pull request closed without merging**
