### PR TITLE
Enable coreclr surfacearea tests

### PR DESCRIPTION
**Pull request by KevinRansom**
It looks like these tests have never run.
This enables them.

### CODE REVIEW

**Comment by PatrickMcDonald** [comment]
These were disabled in #748 385ac5dbf7c59bfaa55fad9347cf57a333047b08 as I didn't know how to get them to pass at the time.

It looks like I disable 2 tests (https://github.com/Microsoft/visualfsharp/search?utf8=%E2%9C%93&q=%22Failing+in+coreclr%22&type=Code)

**Comment by KevinRansom** [comment]
@PatrickMcDonald

Hey mate, it was fine that they were disabled at that time.  Now we need to be a bit more intentional about adding APIs to FSharp.Core for the coreclr.

I loved your original PR and still love it even today.

Kevin

**Comment by KevinRansom** [comment]
@PatrickMcDonald opened issue:  https://github.com/Microsoft/visualfsharp/issues/2462

**Comment by PatrickMcDonald** [comment]
Thanks @KevinRansom, it was great to play a small part in the Core CLR work, seems like so long ago now

**Pull request merged**
