### PR TITLE
Remove trailing semicolon analyzer & code fix and Refactor lexer logic in helpers into a MEF class

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
image

- [ ] use the cached lexer result to find last `;` token
- [ ] keep own cache of <line number -> `FSharpTokenizerLexState * Location`>, if a `FSharpTokenizerLexState` has changed since last time, ask the lexer cache for `all tokens * FSharpTokenizerLexState` and update our cache

### CODE REVIEW

**Comment by forki** [comment]
This one should be run against the compiler itself ;-)

**Comment by cartermp** [comment]
Renamed the PR to reflect that this PR is two things:

* Semicolon analyzer and code fix
* Refactoring of lexer logic into a MEF class to be used in other IDE services

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@vasily-kirichenko conflicts +  ton of errors

Kevin

**Comment by vasily-kirichenko** [comment]
@KevinRansom done

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by KevinRansom** [comment]
@vasily-kirichenko 
Sorry mate , more conflicts.

**Comment by vasily-kirichenko** [comment]
Fixed.

**Comment by KevinRansom** [comment]
@vasily-kirichenko 
sorry conflicts :-(

**Comment by vasily-kirichenko** [comment]
Fixed.
 
I experience this behavior on this PR:



I'm not sure if it's the same on master, will check.

**Comment by vasily-kirichenko** [comment]
Everything is ok in master. I'll remove the code fix, it seems it makes more harm than usefulness.

**Comment by vasily-kirichenko** [comment]
Oookey, `Lexer` is broken in some subtle way, I'm closing this PR. Sorry that wasted your time, guys.

**Pull request closed without merging**
