### PR TITLE
fix five debugger issues

### PR DESCRIPTION
**Pull request by dsyme**
This fixes three debugging issues
* [For tupled functions it's possible to break/step before the arguments have correct debug display](https://github.com/Microsoft/visualfsharp/issues/92)
* [Debug tip shows wrong value on variables with same name](https://github.com/Microsoft/visualfsharp/issues/3141)
* [FSharp emitting incorrect sequence point in debug info](https://github.com/Microsoft/visualfsharp/issues/3036)

There were two other issues fixed along the way
* The body of a `let rec` did not have a sequence point placed. That is fixed.  
* When partial applications were made, such as ``printfn "..." a b ``, the allocation of the format string was done prior to the printf.  That could cause odd step-through behaviour.

The changes are
* Be more careful about using a [FeeFee debug point](https://blogs.msdn.microsoft.com/jmstall/2005/06/19/line-hidden-and-0xfeefee-sequence-points/) at the prolog to a method while arguments are being unpacked. This was the cause of #92 
* Be more careful about using a FeeFee point when local functions are being allocated.  This was the cause of #3036
* Be more careful about emitting the "start scope" of a let-bound variable only just before the variable is actually assigned. This was the cause of #3141 

Testing is mostly through codegen tests - nearly all will need to be updated because along the way a ``nop`` instruction has disappeared from the top of most methods, because of the fix to #92 .  I've also updated [TheBigFileOfDebugStepping.fsx](https://github.com/Microsoft/visualfsharp/tree/master/tests/walkthroughs/DebugStepping) with new examples and manually done step-through for the whole file.

### CODE REVIEW

**Comment by cartermp** [comment]
Oh wow, this is great!

**Comment by dsyme** [comment]
@cartermp You (or someone else) might want to step the TheBigFileOfDebugStepping.fsx on .NET Core, just to check things are ok.  Also in VSCode/Ionide.

I compile using ``release\net40\bin\fsc.exe --optimize- --debug+ TheBigFileOfDebugStepping.fsx`` then run ``devenv /debugexe TheBigFileOfDebugStepping.exe``

**Comment by dsyme** [comment]
A horrible number of test baselines needed updating about 150 files

**Comment by cartermp** [comment]
Ugh, I can't test anything.  Nothing will build on my machine with { 15.3.3, VSSDK, Win10 SDK, F# support }, after a `git clean -xdf` even.

```
C:\repos\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26201\tools\vssdk\Microsoft.VsSDK.targets(966,5): error : CreatePkgDef : error : ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve t
he LoaderExceptions property for more information. [C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj]
```

**Comment by cartermp** [comment]
Okay, I got it to build after uninstalling nightlies and using VS command prompt in admin mode.  Not sure which of that fixed it.  Argh.  Anyways, I can test this this week

**Comment by dsyme** [comment]
@dotnet-bot test this

**Comment by dsyme** [comment]
Well, I updated about 250 code generation test files (and simplified the naming of some others).

I took a look through as many of these as I could and basically all seemed to be the 'nop' removal. For example [this one](https://github.com/Microsoft/visualfsharp/pull/3561/files#diff-ed2a9f478c964e6e1a3029ccd91e1cafL65) clearly has had one opode removed.

It's possible that something is being hidden by such a large test update.  But I think it's still ready for merge, there's not a l;ot more we can do here besides staring at the diffs and manual testing.

**Comment by dsyme** [comment]
@KevinRansom I think we may as well merge this - review welcome for the src\fsharp files

**Comment by KevinRansom** [comment]
I already looked, I forgot to approve ... sorry.

**Comment by dsyme** [comment]
@KevinRansom You did approve, I just didn't notice it

**Pull request merged**
