### PR TITLE
Compat fix for 6258 and fix deterministic flag

### PR DESCRIPTION
**Pull request by dsyme**
This makes desktop fsc.exe 32-bit again, see #6258.  It includes #6223 which is not yet in master.  

See https://github.com/Microsoft/visualfsharp/issues/6258#issuecomment-467649981 for the rationale as to why.

The .NET Core fsc.exe remains 64-bit.

(Separately it would be good to know the perf implications either way, mainly out of curiosity as I don't think we'll change either choice.  I guess if 64-bit is faster we could add a fscAnyCpu to the build and use it as the default desktop compiler going forward, leaving the other for stack-size/type-provider compat scenarios?)

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dsyme, longer term we will want to shift to the coreclr as the default compiler, and interactive, and keep the desktop around for legacy projects.

The coreclr is mostly going to be 64 bit, the 32 bit compiler is often not used or even installed.

**Comment by dsyme** [comment]
> @dsyme, longer term we will want to shift to the coreclr as the default compiler, and interactive, and keep the desktop around for legacy projects. The coreclr is mostly going to be 64 bit, the 32 bit compiler is often not used or even installed.

Yes understood

**Comment by KevinRansom** [comment]
@dsyme 
````
CompilerOptions\fsc\determinism (14) -- failed
CompilerOptions\fsc\determinism (15) -- failed
CompilerOptions\fsc\determinism (16) -- failed
````

**Comment by dsyme** [comment]
```
+++ CompilerOptions\fsc\determinism (14) +++
PRECMD: [fsc --deterministic                  dummy.fs && fsiAnyCPU copyArtifacts.fsx]
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
--------------------------------------------------------
Error from hosted compiler
Exit code: 0
Error:     0
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
--------------------------------------------------------
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
Peverify: [D:\a\1\s\tests\fsharpqa\Source\..\..\..\artifacts\bin\PEVerify\Release\net46\PEVerify.exe dummy.exe ]
Running: [ dummy.exe ]

POSTCMD: [fsiAnyCPU --nologo --quiet --exec binaryCompare.fsx true]
Expected D:\a\1\s\tests\fsharpqa\Source\CompilerOptions\fsc\determinism\dummy.exe and D:\a\1\s\tests\fsharpqa\Source\CompilerOptions\fsc\determinism\dummy2.exe to be same
Fail to execute the POSTCMD. FAIL
+++ CompilerOptions\fsc\determinism (15) +++
PRECMD: [fsc --deterministic --debug:portable dummy.fs && fsiAnyCPU copyArtifacts.fsx]
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
--------------------------------------------------------
Error from hosted compiler
Exit code: 0
Error:     0
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
--------------------------------------------------------
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
Peverify: [D:\a\1\s\tests\fsharpqa\Source\..\..\..\artifacts\bin\PEVerify\Release\net46\PEVerify.exe dummy.exe ]
Running: [ dummy.exe ]

POSTCMD: [fsiAnyCPU --nologo --quiet --exec binaryCompare.fsx true]
Expected D:\a\1\s\tests\fsharpqa\Source\CompilerOptions\fsc\determinism\dummy.exe and D:\a\1\s\tests\fsharpqa\Source\CompilerOptions\fsc\determinism\dummy2.exe to be same
Fail to execute the POSTCMD. FAIL
+++ CompilerOptions\fsc\determinism (16) +++
PRECMD: [fsc --deterministic --debug:embedded dummy.fs && fsiAnyCPU copyArtifacts.fsx]
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
--------------------------------------------------------
Error from hosted compiler
Exit code: 0
Error:     0
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
--------------------------------------------------------
Microsoft (R) F# Compiler version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
Peverify: [D:\a\1\s\tests\fsharpqa\Source\..\..\..\artifacts\bin\PEVerify\Release\net46\PEVerify.exe dummy.exe ]
Running: [ dummy.exe ]

POSTCMD: [fsiAnyCPU --nologo --quiet --exec binaryCompare.fsx true]
Expected D:\a\1\s\tests\fsharpqa\Source\CompilerOptions\fsc\determinism\dummy.exe and D:\a\1\s\tests\fsharpqa\Source\CompilerOptions\fsc\determinism\dummy2.exe to be same
Fail to execute the POSTCMD. FAIL

```

**Comment by dsyme** [comment]
It's weird, I can't repro this failure in the `determinism` tests locally

```
.\build net40 debug

cd tests\fsharpqa\Source\CompilerOptions\fsc\determinism

..\..\..\..\..\..\artifacts\bin\fsc\Debug\net46\fsc.exe --deterministic dummy.fs
fsiAnyCpu copyArtifacts.fsx
..\..\..\..\..\..\artifacts\bin\fsc\Debug\net46\fsc.exe --deterministic dummy.fs
fsiAnyCpu --quiet --exec binaryCompare.fsx true
```
This shows identical binaries are being produced

**Comment by dsyme** [comment]
@brettfo @KevinRansom Have you guys ever seen these tests fail?

**Comment by KevinRansom** [comment]
@dsyme   … no.

**Comment by dsyme** [comment]
I think it's that 
1. the HostedCompilerServer used by the `fsharpqa` tests to produce dummy.exe was running x64 
2. the `fsc.exe` used by the same tests to produce `dumym2.exe` was running x86

Surprisingly the output binaries seem to differ slightly when the compiler runs as x86 v. x64.  

@KevinRansom @brettfo any idea why this may be the case?  

A vague guess is that this is because the PDB generation library writes slightly different entries

**Comment by KevinRansom** [comment]
If it's creating desktop pdbs then who knows.  If it's portable pdbs, then they should be consistent.

**Comment by dsyme** [comment]
OK, well, the tests pass now, but there must be some small difference.  I'll see if I can figure it out

**Comment by dsyme** [comment]
@KevinRansom There was a bug in `--deterministic` - it was [using `hash` on a integers and strings](https://github.com/Microsoft/visualfsharp/blob/master/src/absil/ilwrite.fs#L2860) but these hashes are not consistent between x64 and x86 (indeed .NET hashes on strings are not even the same from day to day AFAIK)

I will add the fix here

**Comment by KevinRansom** [comment]
@dsyme , good eyes.

**Comment by dsyme** [comment]
> @dsyme , good eyes.

2 hours looking at hexdumps of binaries....

**Comment by cartermp** [comment]
@KevinRansom @Pilchie We should consider servicing this in an RC service. I'll queue up a bug.

**Comment by dsyme** [comment]
BTW we could make the desktop fsc.exe and fsi.exe "anycpu, 32-bit preferred".  They are currently x86.

I don't really see any technical downside to doing that - it means that if they happen to be launched as 64-bit processes then they will launch and run correctly.

**Comment by Pilchie** [comment]
I don't see a bug yet.

**Comment by cartermp** [comment]
I'll write one up - one-handed 🤕

**Pull request merged**
