### PR TITLE
Improve error reporting: Let as last line in block

### LINKED ISSUE #1162: Improve error reporting: Let as last line in block
## What
(From @tpetricek). The following code snippet leads to the resulting error message: -
```fsharp
let sum = 0
for x in 0 .. 10 do
    let sum = sum + x
```
```error FS0588: Block following this 'let' is unfinished. Expect an expression.```

## Why
The above error message, whilst factually correct, does not explain to the beginner what this is and why it occurs. There are of course two errors here - one that the user is trying to mutate a value (which should be ignored from this issue as it is covered elsewhere) and the second which is that there is no result from the block.

## How
Suggest: ```Every code block is an expression and must have a result. 'let' is not an expression and cannot be the final code element in a block. Consider returning something explicit from this block.```

### PR DESCRIPTION
**Pull request by forki**
fixes #1162

image

### CODE REVIEW

**Comment by dsyme** [comment]
Per other error message discussions, please follow the "_Error_. _Explanation_. _Suggestion_" format.  

(e.g. Try reading your error message interpreting the first sentence as a description of an error - i.e. a negative - rather than the positive explanation you intend).

**Comment by dsyme** [comment]
Oh, also be careful of using the word ``return``.  That will be misinterpreted to mean a C-like return, e.g. ``return 3``.

Together those two observations would give something like:

    The block following this '%s' is unfinished. Every code block is an expression and must have a result. '%s' cannot be the final code element in a block. Consider giving this block an explicit result.

**Comment by forki** [comment]
Error message is changed to @dsyme's proposal. Appveyor is green. Jenkins is red because of unrelated issue (see https://github.com/Microsoft/visualfsharp/issues/1169).

ready for review

**Comment by dsyme** [comment]
@forki When you update the error message could you update the screen shot too?  Or just remove it.  Thanks

**Comment by dsyme** [comment]
The code and new message look good to me, it's ready to go (as far as I can see :) )

**Comment by forki** [comment]
something is strange with appveyor - @KevinRansom @otawfik-ms

**Comment by forki** [comment]
it's green and ready

**Pull request merged**
