### PR TITLE
[CompilerPerf] [NotForCheckin] check cost of fat values

### PR DESCRIPTION
**Pull request by dsyme**
One theory about compiler perf is that the core data structures ``Val``, ``Entity`` and ``Typar`` are too "fat"

This PR tests that theory negatively by deliberately doubling the size of ``Val`` nodes. We will do some compiler performance test runs and see if they register a slowdown, and if so by how much.  This will give us one indication of whether it is worth putting more time into making these values "thin"

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
CI thinks they are too fat ;)

**Comment by dsyme** [comment]
According to these results from my machine there is really no difference:
```
https://github.com/Microsoft/visualfsharp master                       ba63403cb5898596c5e875a14ce22b33ef618c01 ba63403cb5898596c5e875a14ce22b33ef618c01 208.39 10.60                29.52                46.71                62.16                52.44               
https://github.com/dsyme/visualfsharp.git abperf1                      99ba671f32efc6163b290b5c5720ac112a946737 ba63403cb5898596c5e875a14ce22b33ef618c01 198.60 10.59                30.23                45.53                61.69                52.02               
```
the figures are pretty noisy but the one with fat values is showing up as faster :)

**Comment by 7sharp9** [comment]
So the work done on TPL years back to reduce side of the Task structures may not apply to F# async?

**Comment by 7sharp9** [comment]
And does adding `Unchecked.defaultof<_>` actually double the types footprint.

**Comment by dsyme** [comment]
> So the work done on TPL years back to reduce side of the Task structures may not apply to F# async?

You can't draw general conclusions from this - there are many, many other factors involved.

For example another conclusion might be that the size of "Val" nodes is not so important, but the size of "Entity" nodes or many other allocated objects might be

Another suggestion is that there is a lower object size where positive cache effects kick in.  Though this test indicates that we don't seem to be close to such a limit on the upper size range.

> And does adding Unchecked.defaultof<_> actually double the types footprint.

Yes, all the fields are of type string. Though there are subtleties. The CLR puts all ref-types fields together (for easier GC scanning) so all these end up in the same place in each object.

**Pull request closed without merging**
