### PR TITLE
Fix for #2373

### PR DESCRIPTION
**Pull request by liboz**
Attempts to fix https://github.com/Microsoft/visualfsharp/issues/2373

### CODE REVIEW

**Comment by KevinRansom** [comment]
@liboz Any chance we could add a regression test, to ensure we keep it working?

Kevin

**Comment by liboz** [comment]
I'm not sure how to add a test that uses peverify because the weird thing about this case is that the compilation step works for the broken code, but it fails peverify.

**Comment by vasily-kirichenko** [comment]
@liboz I believe there are many tests that compile and peverify, search the codebase.

**Comment by dsyme** [comment]
@liboz See for example https://github.com/Microsoft/visualfsharp/blob/master/tests/fsharp/tests.fs#L1418

**Comment by liboz** [comment]
@vasily-kirichenko  @dsyme Thanks for pointing me in the right direction.

**Comment by KevinRansom** [comment]
@liboz 
ty

**Pull request merged**
