### PR TITLE
implement IDisposable interfaces explicitly 

### PR DESCRIPTION
**Pull request by ncave**
added some missing IDisposable interfaces

### CODE REVIEW

**Comment by forki** [comment]
Cool

**Comment by KevinRansom** [comment]
@ncave 

How would this change actually be consumed?  What code today needs this change, or what will this change enable?

Thanks

**Comment by ncave** [comment]
@KevinRansom Any code that obtains sequence enumerators and then tries to dispose the enumerator (e.g. with a [use statement](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/seq.fs#L492)).

**Comment by KevinRansom** [comment]
with this change:

The generated enumerator doesn't really need collection.  It is implemented as:
````
member __.Dispose () = () 
````

Dispose may be necessary if one were to generate a derived class with an enumeration over a COM collection.  But since that would be special code it should add IDisposable to the derived class.

````
let main argv = 
    use x = [ for x in 0 .. 10 -> x * x]

    printf "%A" x

    0 // return an integer exit code


d:\ncave\visualfsharp\release\net40\bin\temp>..\fsc Program.fs
Microsoft (R) F# Compiler version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

Program.fs(6,9): error FS0193: Type constraint mismatch. The type
    'int list'
is not compatible with type
    'System.IDisposable'
````

**Comment by ncave** [comment]
@KevinRansom `use` on sequence enumerators, not lists. Most of the sequence enumerators already have the IDisposable interface ([here](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/seq.fs#L280), [here](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/seq.fs#L280), [here](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/seq.fs#L404), etc.), this just fixes the ones where it was missed.

**Comment by dsyme** [comment]
@ncave Generated classes like [this](https://github.com/Microsoft/visualfsharp/pull/3447/files#diff-5470ddaa52d99663f8d391a77ae04f0dL5319) do all have the IDisposable interface, it's just not listed explicitly.  It's implied by inheritance via the ``IEnumerator<T>`` interface.  F# lets you implement inherited interfaces in the listing of methods for a sub-interface.

However it may be that Fable translation wants to see these as explicit interface implementations?  I don't mind making this explicit.  

The one change we can't take is that change to the public API surface of the  ``DIspose`` helper function.

**Comment by dsyme** [comment]
@KevinRansom As  long as [this change](https://github.com/Microsoft/visualfsharp/pull/3447/files#diff-e56f7c54b96af89dbcb25c1abd8b072dL1108) is undone then AFAICS this is simply code cleanup, making interfaces that are already implemented more explicit.

**Comment by ncave** [comment]
@dsyme I'll take it out, but do you mind elaborating a bit, as this Dispose is only supposed to be called by compiled code? The change I made preserves existing functionality and fixes some use cases when code is generated to dispose things that don't implement IDisposable.

**Comment by KevinRansom** [comment]
Oh wow ...  I didn't know that about IEnumerator<T> and I think it's kind of silly, however, are we going to teach the compiler to work for:

````
let main argv = 
    use x = [ for x in 0 .. 10 -> x * x]

    printf "%A" x

    0 // return an integer exit code


d:\ncave\visualfsharp\release\net40\bin\temp>..\fsc Program.fs
Microsoft (R) F# Compiler version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

Program.fs(6,9): error FS0193: Type constraint mismatch. The type
    'int list'
is not compatible with type
    'System.IDisposable'
````

**Comment by ncave** [comment]
@KevinRansom If we add IDisposable.Dispose somewhere [here](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L3499), then yes, why not.

**Comment by dsyme** [comment]
> however, are we going to teach the compiler to work for..

To be clear, this PR doesn't do that.   IDisposable is only implied by ``IEnumerator<T>``

**Comment by ncave** [comment]
@dsyme @KevinRansom Ok, Dispose change reverted. It really does help alleviate some code generation issues on lesser platforms, so it's a nice to have, but yeah, I'll leave it at that. Thanks for reviewing!

**Comment by dsyme** [comment]
> @dsyme @KevinRansom Ok, Dispose change reverted. It really does help alleviate some code generation issues on lesser platforms, so it's a nice to have, but yeah, I'll leave it at that. Thanks for reviewing!

@ncave does this change help Fable in some way, e.g. by making the IDisposable implementation explicit in the generated classes?

**Comment by ncave** [comment]
@dsyme I'm sure it will, in a way, in the sense that it makes all the sequence enumerators consistent (most of them already have the explicit IDispose). It's just a code cleanup, as you said, but it also helps platforms that can't handle non-explicit interfaces.

**Comment by dsyme** [comment]
> ... helps platforms that can't handle non-explicit interfaces.

So Fable can't handle non-explicit interfaces?  We should add an implement-all-interfaces-explicitly option, at least to Fable compiler?

**Comment by ncave** [comment]
@dsyme Sorry, perhaps I was unclear, wasn't talking about Fable but other projects like [this](https://github.com/ncave/dotnet-js).

**Pull request merged**
