### PR TITLE
Minor Config fixes

### PR DESCRIPTION
**Pull request by cloudRoutine**

### CODE REVIEW

**Comment by KevinRansom** [comment]
@cloudruntime, I'm in the process of testing some rollbacks, on package versions, System.Immutable and Microsoft.Diasymreader.PortablePdb the updates break the compiler and portable pdb generation.

Kevin

**Comment by cloudRoutine** [comment]
yea there was one last place i couldn't find that was causing an assembly conflict. could it be the lkg?

**Comment by cloudRoutine** [comment]
in general the package management with nuget is such a finicky mess. I really hope we can switch to paket at some time in the future.

**Comment by cloudRoutine** [comment]
@KevinRansom also for future reference, is there a way that I can check that I haven't accidentally broken them again in the future? I figured I was good when I passed all of the CI tests

**Pull request closed without merging**
