### PR TITLE
merge `master` into `vs2017-rtm`

### PR DESCRIPTION
**Pull request by brettfo**

### CODE REVIEW

**Comment by dsyme** [comment]
@brettfo Should we be doing this given the number of existing regressions we have?  I'm not sure we are where we need to be.

**Comment by KevinRansom** [comment]
@dsyme It looks to me as if the bugs currently labelled regressions, are regressions against VS2015 .  It's not clear to me that they are regressions against the RTM release of VS2017.

If we pull these changes we get the last six weeks worth of updates. Which includes a fix to at least one regression.  And puts in place the necessary pieces to consume the dotnet sdk.

**Comment by cartermp** [comment]
Many of them (most?) are regressions against VS2017, but the way I see it, there are more regressions in VS 2017 RTW than there are in master today.  And we also have some runway to address regressions up until Preview 3 of VS 2017 Update 3.

**Comment by dsyme** [comment]
> @dsyme It looks to me as if the bugs currently labelled regressions, are regressions against VS2015 . It's not clear to me that they are regressions against the RTM release of VS2017.

I believe several are regressions against VS2017 (e.g. the slowness reports, and configuration change), but it is hard to distinguish to be honest. We should just get back to VS2015 quality....

**Comment by KevinRansom** [comment]
@dsyme 

I wish we could have a ZBB effort.  Or a month of quality ... or something ... but if we don't ship Net Standard 2.0 support we will just slip further and further behind.

Perhaps we should do a quality month, and only accept bug fixes with no new features for a month?

**Comment by dsyme** [comment]
> I wish we could have a ZBB effort. 

Well that would be fantastic.  ZBB on all "Now" and "Soon" bugs would be wonderful

**Comment by cartermp** [comment]
Just to offer more for the case to merge here, this includes [tens of these closed issues](https://github.com/Microsoft/visualfsharp/milestone/9?closed=1) which are not in RTW today.  Cherry-picking the .NET Core support is a possibility, but that won't get us any closer to quality than this PR will right now.

**Comment by dsyme** [comment]
> Just to offer more for the case to merge here, this includes tens of these closed issues which are not in RTW today. Cherry-picking the .NET Core support is a possibility, but that won't get us any closer to quality than this PR will right now.

OK, that's a very good point :)

**Comment by brettfo** [comment]
Tagging @Pilchie and @MattGertz  for approval.

**Pull request merged**
