### PR TITLE
Fix helloWorldCSharp on jenins

### PR DESCRIPTION
**Pull request by KevinRansom**
magic.dll has no need to go in the gac ... so don't put it there.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test Windows_NT Release_ci_part1 please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by forki** [comment]
Hi Kevin, is there a different way to restart the build? Maybe a button in the UI of the CI server (like in travis or appveyor)? Github is sending a mail everytime someone triggers a build with such a comment. This gets annoying very quickly ;-) 
So it would be really great if you can find another way. Thank you very much.

**Comment by KevinRansom** [comment]
@forki ... I believe you can unsubscribe from the thread using the button to the right labelled Unsubscribe.

**Comment by forki** [comment]
I know, but this happening on many threads I need to unsubscribe from all of these. And then I don't get the important notificaions. using github comments to trigger CI feels completely wrong. I hope you find a better way (click in CI server ui, use hubot or whatever).

**Comment by forki** [comment]
Also I'm slightly concerned about the fact that we have a thing called magic.dll

**Comment by KevinRansom** [comment]
It's just a test dll, blame the chap who wrote it in the first place.  My issue is it was added to the GAC.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by isaacabraham** [comment]
@KevinRansom I tend to agree with @forki here. It seem like a small thing but in the interests of clarity can't this just do what most other repos do that have a CI server? Is there a blocker or maybe someone can help out to improve this?

**Comment by KevinRansom** [comment]
The dotnet-ci OSS repo is here: https://github.com/dotnet/dotnet-ci.

**Comment by KevinRansom** [comment]
Well now we are running the tests on Jenkins.  That was way harder than it should have been.

**Pull request merged**
