### PR TITLE
Remove portable library templates from Visual Studio

### PR DESCRIPTION
**Pull request by KevinRansom**
We are joining VB and C# in deprecating support for creating new portable profile projects.

### CODE REVIEW

**Comment by KevinRansom** [comment]
Per:  https://github.com/Microsoft/visualfsharp/issues/3185

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
I think we should only deprecate this once we support creating and editing ,.NET Standard libraries.

Until then can't we take the path that the templates remain (perhaps deprecated) referencing the FSharp.Core 4.1.x nuget package?

**Comment by KevinRansom** [comment]
I can leave the templates.  But freeze the portable fsharp.cores that still achieves what I want to, which is to stop having to build them in the build.
How does that sound?

**Comment by dsyme** [comment]
> I can leave the templates. But freeze the portable fsharp.cores that still achieves what I want to, which is to stop having to build them in the build. How does that sound?

That sounds just fine.  Will you use fixed frozen copies of the DLLs for the install, or will you use the nuget package? thanks

**Comment by KevinRansom** [comment]
@dsyme,

Our desktop installer MSI will still install them to ref assemblies.  Otherwise existing projects won't work without modifications.  Also the multi-targeting options on our property pages rely on the current layout.

Kevin

**Comment by dsyme** [comment]
Ok, that's just fine

**Comment by 7sharp9** [comment]
There's support on xs/vs4mac to do this currently (create / edit F# net
std).  I wonder if depreciating them there will happen soon.

**Comment by KevinRansom** [comment]
@7sharp9 I'm not familiar with the project plans for Xamarin.  Except that dotnetstandard 2.0 is a firm commitment.

The dotnet team are basing portable scenarios off of dotnet standard definitions rather than portable libraries.

And so the long term aim is to move people onto dotnet standard and away from plibs.  You can see this in VS 2017, where support for new plib projects has been elidid already.

Kevin

**Pull request closed without merging**
