### PR TITLE
fixed: CommonHelpers.tryClassifyAtPosition return wrong result at the end position

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This remove the ugly `tryGotoAtPosition` and the similar stuff from QuickInfo service. Same should be done for Inline Rename and Highlight Document after merging this.

### CODE REVIEW

**Comment by dsyme** [comment]
Oh that's a really nice fix.  Making things simpler is soooo much better.

**Comment by dsyme** [comment]
Bunch of failures, here are the first 3:

```
1) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.ColorizationServiceTests.InactiveCode("Inactive Code1*)le","excluded code")
  Classification data doesn't match for end of marker
  Expected string length 13 but was 10. Strings differ at index 0.
  Expected: "excluded code"
  But was:  "whitespace"
  -----------^

2) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.ColorizationServiceTests.InactiveCode("Inactive Code2*)le","excluded code")
  Classification data doesn't match for end of marker
  Expected string length 13 but was 10. Strings differ at index 0.
  Expected: "excluded code"
  But was:  "whitespace"
  -----------^

3) Failed : Microsoft.VisualStudio.FSharp.Editor.Tests.Roslyn.ColorizationServiceTests.InactiveCode("Inactive Code3*)le","excluded code")

**Comment by cartermp** [comment]
This is a great change.  Looking forward to seeing this in.

**Comment by KevinRansom** [comment]
@vasily-kirichenko  I reverted this due to test failures.  

build vs vstest to repro

**Comment by vasily-kirichenko** [comment]
Yes, I know there are failing lexer tests. I don't think this PR is a good one since it touches such a core things. Maybe it's better to find a simpler way to fix the initial problem.

**Pull request merged**
