### PR TITLE
FCS alignment: FileSystem, parameter ident ranges and miscellaneous (attempt 2)

### PR DESCRIPTION
**Pull request by dsyme**
There was a regression in a unittest from the cleanup https://github.com/Microsoft/visualfsharp/commit/0214e3b8de10a2049f0ecc2b59329d9f8d551564

I switched the order of some code to do with setting up thread locals for error reporting when hosted inside VS.   The thread locals weren't set up at the point the error was reported.  

This reapplies the whole PR (since it has been reverted in the meantime)

### CODE REVIEW

**Comment by KevinRansom** [comment]
Thanks for this Don

**Comment by KevinRansom** [comment]
Still seems to hang: here is the stacktrace:
FSharp.LanguageService.dll!Microsoft.VisualStudio.FSharp.LanguageService.LanguageServiceState.ExecuteBackgroundRequest(Microsoft.VisualStudio.FSharp.LanguageService.BackgroundRequest req, Microsoft.VisualStudio.FSharp.LanguageService.IdealSource source) Lin...

**Comment by dsyme** [comment]
The individual NUnit test that was hanging runs ok for me.  I'll now run the full ideunit tests to see

**Comment by dsyme** [comment]
all tests passed - could you check you rebuilt the IDE FSharp.LanguageService.COmpiler.dll and IDE tests?

**Comment by KevinRansom** [comment]
I just rebuilt everything.  And ran the tests again, it seems to have hung at the same point.
````
Not Flagged	>	10756	10	Worker Thread	TestRunnerThread	FSharp.Core.dll!Microsoft.FSharp.Control.AsyncImpl.ResultCell<Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ResultOrException<Microsoft.FSharp.Core.Unit>>.TryWaitForResultSynchronously	Normal
 	 	 	 	 	 	mscorlib.dll!System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle waitableSafeHandle, long millisecondsTimeout, bool hasThreadAffinity, bool exitContext)	 
 	 	 	 	 	 	mscorlib.dll!System.Threading.WaitHandle.WaitOne(int millisecondsTimeout, bool exitContext)	 
 	 	 	 	 	 	FSharp.Core.dll!Microsoft.FSharp.Control.AsyncImpl.ResultCell<Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ResultOrException<Microsoft.FSharp.Core.Unit>>.TryWaitForResultSynchronously(Microsoft.FSharp.Core.FSharpOption<int> timeout) Line 1213	 
 	 	 	 	 	 	FSharp.Core.dll!Microsoft.FSharp.Control.FSharpMailboxProcessor<Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ReactorCommands>.TryPostAndReply<Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ResultOrException<Microsoft.FSharp.Core.Unit>>(Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Control.FSharpAsyncReplyChannel<Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ResultOrException<Microsoft.FSharp.Core.Unit>>, Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ReactorCommands> buildMessage, Microsoft.FSharp.Core.FSharpOption<int> timeout) Line 2499	 
 	 	 	 	 	 	FSharp.Core.dll!Microsoft.FSharp.Control.FSharpMailboxProcessor<Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ReactorCommands>.PostAndReply<Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ResultOrException<Microsoft.FSharp.Core.Unit>>(Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Control.FSharpAsyncReplyChannel<Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ResultOrException<Microsoft.FSharp.Core.Unit>>, Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.ReactorCommands> buildMessage, Microsoft.FSharp.Core.FSharpOption<int> timeout) Line 2502	 
 	 	 	 	 	 	FSharp.LanguageService.Compiler.dll!Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.Reactor.SyncOp(Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Core.Unit> op) Line 213	 
 	 	 	 	 	 	FSharp.LanguageService.Compiler.dll!Microsoft.FSharp.Compiler.SourceCodeServices.Reactor.Reactor.RunSyncOp<Microsoft.FSharp.Compiler.SourceCodeServices.CheckOptions>(Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Compiler.SourceCodeServices.CheckOptions> f) Line 229	 
 	 	 	 	 	 	FSharp.LanguageService.Compiler.dll!Microsoft.FSharp.Compiler.SourceCodeServices.BackgroundCompiler.GetCheckOptionsFromScriptRoot(string filename, string source, System.DateTime loadedTimestamp, string[] otherFlags) Line 1997	 
 	 	 	 	 	 	FSharp.LanguageService.dll!<StartupCode$FSharp-LanguageService>.$Servicem.backgroundRequestData@1071.Invoke(Microsoft.FSharp.Core.Unit unitVar) Line 1073	 
 	 	 	 	 	 	mscorlib.dll!System.Lazy<Microsoft.VisualStudio.FSharp.LanguageService.ExecuteBackgroundRequestData>.CreateValue()	 
 	 	 	 	 	 	mscorlib.dll!System.Lazy<Microsoft.VisualStudio.FSharp.LanguageService.ExecuteBackgroundRequestData>.LazyInitValue()	 
 	 	 	 	 	 	mscorlib.dll!System.Lazy<Microsoft.VisualStudio.FSharp.LanguageService.ExecuteBackgroundRequestData>.Value.get()	 
 	 	 	 	 	 	FSharp.LanguageService.dll!Microsoft.VisualStudio.FSharp.LanguageService.LanguageServiceState.ExecuteFSharpBackgroundRequest(Microsoft.VisualStudio.FSharp.LanguageService.FSharpBackgroundRequest req, Microsoft.VisualStudio.FSharp.LanguageService.IdealSource source) Line 1215	 
 	 	 	 	 	 	FSharp.LanguageService.dll!Microsoft.VisualStudio.FSharp.LanguageService.LanguageServiceState.ExecuteBackgroundRequest(Microsoft.VisualStudio.FSharp.LanguageService.BackgroundRequest req, Microsoft.VisualStudio.FSharp.LanguageService.IdealSource source) Line 1196	 
 	 	 	 	 	 	Salsa.dll!Salsa.Salsa.Privates.SimpleOpenFile.TryExecuteBackgroundRequest(Microsoft.VisualStudio.FSharp.LanguageService.BackgroundRequest pr) Line 1214	 
 	 	 	 	 	 	Salsa.dll!Salsa.Salsa.Privates.SimpleOpenFile.ExecuteBackgroundRequestForScope(Microsoft.VisualStudio.FSharp.LanguageService.BackgroundRequest pr, bool canRetryAfterWaiting) Line 1221	 
 	 	 	 	 	 	Salsa.dll!Salsa.Salsa.Privates.SimpleOpenFile.OnIdleTypeCheck() Line 1243	 
 	 	 	 	 	 	Salsa.dll!Salsa.Salsa.Privates.SimpleOpenFile.OnIdle() Line 1200	 
 	 	 	 	 	 	Salsa.dll!Salsa.Salsa.Privates.SimpleVisualStudio.Salsa.Salsa.IVisualStudio.Salsa-Salsa-IVisualStudio-OnIdle() Line 917	 
 	 	 	 	 	 	Salsa.dll!Salsa.Salsa.Privates.SimpleVisualStudio.Salsa.Salsa.IVisualStudio.Salsa-Salsa-IVisualStudio-TakeCoffeeBreak() Line 923	 
 	 	 	 	 	 	Salsa.dll!Salsa.Salsa.Privates.SimpleOpenFile.ReplaceAllText(Microsoft.FSharp.Collections.FSharpList<string> replacementLines, bool takeCoffeeBreak) Line 1546	 
 	 	 	 	 	 	Salsa.dll!Salsa.Salsa.Models.MSBuildWithFlavor@1677-38.Invoke(System.Tuple<Salsa.Salsa.OpenFile, Microsoft.FSharp.Collections.FSharpList<string>, bool> tupledArg) Line 1677	 
 	 	 	 	 	 	Salsa.dll!Salsa.VsOpsUtils.ReplaceFileInMemory(Salsa.Salsa.OpenFile file, Microsoft.FSharp.Collections.FSharpList<string> lines) Line 145	 
 	 	 	 	 	 	Unittests.dll!UnitTests.TestLib.LanguageService.LanguageServiceBaseTests.CreateSingleFileProject(Microsoft.FSharp.Collections.FSharpList<string> content, Microsoft.FSharp.Core.FSharpOption<Microsoft.FSharp.Collections.FSharpList<string>> references, Microsoft.FSharp.Core.FSharpOption<Microsoft.FSharp.Collections.FSharpList<string>> defines, Microsoft.FSharp.Core.FSharpOption<UnitTests.TestLib.LanguageService.SourceFileKind> fileKind, Microsoft.FSharp.Core.FSharpOption<Microsoft.FSharp.Collections.FSharpList<string>> disabledWarnings, Microsoft.FSharp.Core.FSharpOption<string> fileName) Line 311	 
 	 	 	 	 	 	Unittests.dll!UnitTests.Tests.LanguageService.ScriptTests.createSingleFileFsxFromLines(Microsoft.FSharp.Collections.FSharpList<string> code) Line 24	 
 	 	 	 	 	 	Unittests.dll!UnitTests.Tests.LanguageService.ScriptTests.Fsx.InvalidMetaCommandFilenames() Line 1273	 
 	 	 	 	 	 	[Native to Managed Transition]	 
 	 	 	 	 	 	[Managed to Native Transition]	 
````

**Comment by KevinRansom** [comment]
When I reverted the PR, the test started passing, so please take a look and resubmit the original PR when the ideunit tests can run without hanging.

Thanks

**Comment by dsyme** [comment]
Hmm... I ran the tests to completion twice after this change - I'm fairly confident its the correct one though I may be wrong of course.

**Comment by dsyme** [comment]
Ah, ok, there was an uncommitted change in my fix (I thought it wasn't the fix, but it was!) See https://github.com/dsyme/visualfsharp/commit/0cdd740b8ac809736db76fe05193e77795cd6d9d

This PR now contains the cleanup.

**Comment by dsyme** [comment]
For posterity, the original PR which got committed then reverted was here: https://github.com/Microsoft/visualfsharp/pull/588

**Comment by KevinRansom** [comment]
The number of times that orphaned files happens to me is high, and it is super annoying.

Thanks for taking care of this.

**Comment by KevinRansom** [comment]
Committed, thanks for taking care of this.

Kevin

**Pull request merged**
