### PR TITLE
Enable codegen for exception filters by default

### PR DESCRIPTION
**Pull request by jack-pappas**
I was reading an article about C# 6.0 last week which included wording along the lines of "VB.NET and F# have already had exception filters for years now" and remembered I'd looked at the codegen implementation for pattern guards on F# ``try/with`` expressions a while back and was surprised to find it used ``catch`` and the ``rethrow`` instruction instead of a real filter handler.

I took another look at the codegen and the logic is already in place to generate bona-fide exception filters; they can even be enabled in the release versions of the F# compiler via the ``--generate-filter-blocks`` flag. A comment in fscopts.fs says the logic was disabled by default due to Mono bugs related to exception filters.

Would it be reasonable to re-enable this logic by default? I don't know whether the Mono bugs were ever fixed, but exception filters are going to become much more widespread now thanks to C# 6.0 -- so if the bugs haven't yet been fixed, it seems like there will be new motivation to do so.

The reason we may want to re-enable exception filters by default -- filters better preserve stack traces and improve debugging experience [1].

Some interesting links with more info about exception filters:
* [1] https://roslyn.codeplex.com/discussions/541301
* [2] http://gregbee.ch/blog/why-doesnt-c-sharp-have-exception-filters
* [3] https://smellegantcode.wordpress.com/2009/02/26/fatal-exceptions-and-why-vb-net-has-a-purpose/
* [4] http://blogs.msdn.com/b/dotnet/archive/2009/08/25/the-good-and-the-bad-of-exception-filters.aspx
* [5] https://web.archive.org/web/20091218171254/http://blogs.msdn.com/clrteam/archive/2009/02/05/catch-rethrow-and-filters-why-you-should-care.aspx

### CODE REVIEW

**Comment by latkin** [comment]
Please include codegen tests covering the new behavior, and update any that relied on old behavior.

From a quick grep I can see that there are existing tests which use the removed `--generate-filter-blocks` switch, those will clearly need updating.

**Comment by jack-pappas** [comment]
@latkin Ok, I've updated the tests which check for the presence of the old flag, or explicitly rely on the old behavior. I still need to run the full test suite to look for any tests which *implicitly* rely on the old behavior.

**Comment by jack-pappas** [comment]
I've added a codegen test to verify the IL produced when the ``--exnfilters+`` switch is specified (this PR makes it the default).

Are there any other changes that need to be made for this?

**Comment by dsyme** [comment]
@latkin - could you kick of a full Windows test run with this change?

I don't know of any specific reason _not_ to do this.  However 

1. it would be good to re-check the exception-handling-debugging experience we get with this, both with "First chance" excepitons and "Just my code" on/off in Visual Studio

2. We need some kind of validation on Mono.  That may be easiest by also sending this as a trial PR to the fsharp4 branch http://github.com/fsharp/fsharp where we do AppVeyor Linux testing.  That branch contains most of the fsharp4 work from here so the commits should slot in pretty easily.

**Comment by latkin** [comment]
Validating now.

**Comment by latkin** [comment]
There are still 25 tests failing (across codegen and compiler options) in fsharpqa.

Looks like it is a broad range of list/seq comprehension tests and query tests that have been affected - the generated code for the backing IEnumerables is changed to rely on filters now.

**Comment by jack-pappas** [comment]
Thanks @latkin. I'll try to fix those failing tests soon so we can get this merged.

**Comment by jack-pappas** [comment]
I pushed these changes to fsharp/fsharp as Don suggested, and the build passed successfully on Mono+Linux (x86). See fsharp/fsharp#396 for details.

**Comment by jack-pappas** [comment]
I'm running the *fsharpqa* tests locally and can see that some of them are failing; however, the test infrastructure deletes the generated files so I can't use them to create new baselines. I'm keeping the existing tests/baselines and modifying them to use the ``--exnfilters-`` flag when compiling.

Is there an easy way of creating baseline (``*.bsl``) files for the codegen tests? I imagine it involves compiling each test script twice (netfx20 and netfx40) then running the result through ildasm -- I'm just wondering if you have a script or other tool to automate the process.

**Comment by jack-pappas** [comment]
I think the *fsharpqa* CodeGen tests should be fixed now.

**Comment by latkin** [comment]
Thanks for updating the codegen tests.  After looking into it a bit more, I'm fairly certain we cannot just turn this on by default.

The main issue is that exception filters are not simply a built-in catch+test+rethrow optimization, they actually have different semantics which result in different order of execution.  F# exception pattern guards have until now represented the runtime semantics and operation order of catch+test+rethrow. We can't just flip a switch and cause existing F# code to behave differently like this.

e.g. consider this code

```fsharp
let cond () = printfn "condition"; true

try
  try
    printfn "throw"
    failwith "boom"
  finally
    printfn "finally"
with
   e when cond() -> printfn "caught"
```
Behavior until now is as you would probably expect:
```
throw
finally
condition
caught
```
With filters enabled, the output is (with extra * added):

```
throw
condition
finally
condition*
caught
```

[The * line is interesting - I assume it's a bug in the codegen, but maybe it's some attempt to work around the changed order of operations.]

`condition` changing places to execute before `finally` is actually correct and expected, if the guard clause is codegened as a filter. The blog post linked in [[4]](http://blogs.msdn.com/b/dotnet/archive/2009/08/25/the-good-and-the-bad-of-exception-filters.aspx) above explains this pretty well - the CLR executes `filter` blocks all the way up the stack until one of them returns true, before *any* `finally` blocks are executed.  This is in contrast to checks inside of `catch` blocks, which always execute after any enclosed `finally` blocks.

It's even worse if a `finally` block has a side effect or itself throws a different type of exception - the filter which originally said it would process the exception might no longer be valid at all.

I don't think it's acceptable to make a behavior change like this without distinct syntax or opt-in from the user.

**Comment by KevinRansom** [comment]
Lincoln is quite correct about this.  The exception filter change is certainly observable to applications and so a change in behavior would be considered breaking.  If we want to add filters I believe a specific exception filter syntax would be the way to go.

@dsyme do you have any thoughts on this.

**Comment by dsyme** [comment]
Thanks for the fantastic analysis everyone.

Given that this is indeed a breaking change (and one that gives a very different semantics), I would be happy with the feature as an opt-in feature, enabled by a command-line option, but which is off by default.  (I could well imagine enabling this feature in many libraries and production systems due to the better crash dumps and other debugging stack traces)

I don't know if the feature can be reconfigured in time to make the cut for F# 4.0 - I will leave it to @KevinRansom  and @latkin to decide

don

**Comment by latkin** [comment]
This is already present as an opt-in feature, via the `--generate-filter-blocks` flag.  The flag is marked as deprecated, so you get a warning, but it works.  The warning can be disabled with `--nowarn:75`.

I think that's probably where it should stay for now.  Per my examples above, it seems there are still implementation bugs, so it doesn't seem prudent to un-deprecate this yet.

**Comment by latkin** [comment]
Closing this out as we can't take the change as proposed.  Fixes for the filter codegen implementation or modifications to how the flag is handled can be handled in dedicated PRs/issues.

**Comment by mattmccutchen-microsoft** [comment]
> [The * line is interesting - I assume it's a bug in the codegen, but maybe it's some attempt to work around the changed order of operations.]

Indeed, the generated code re-does the pattern matching in the catch block.  I imagine that was easiest to implement.  If we wanted to avoid that, the filter would have to remember which pattern matched and the values of all the variables bound by the pattern, and the catch block would have to execute the corresponding expression based on the saved information.

**Pull request closed without merging**
