### PR TITLE
Fixes #9, Internal error in FSI: FS0192: binding null type in envBindTyp...

### LINKED ISSUE #9: Internal error in FSI: FS0192: binding null type in envBindTypeRef
Opened by: [swlaschin2](https://www.codeplex.com/site/users/view/swlaschin2)

I can reproduce this error in FSI in VS2012 , VS2013 and in tryFsharp.org
* In VS2012 and VS2013 
error FS0192: internal error: binding null type in envBindTypeRef
* In tryFsharp.org (as of 2014-12-09) 
error FS0193: internal error: Error 0x2115.
Here is a minimal example that causes the error:
````fsharp
// fails to compile
// error FS0192: internal error: binding null type in envBindTypeRef
let ``1,`` x = 
    [||] |> Array.fold (+) ","
````
But minor variants of the code do compile! 
````fsharp
// remove comma from function name and it compiles, so the function name is involved?        
let ``1`` x = 
    [||] |> Array.fold (+) ","
// change fold to map and it compiles, so something to do with fold as well?        
let ``1,`` x = 
    [||] |> Array.map ((+) "")
````
Not sure if it is related to: https://github.com/Microsoft/visualfsharp/issues/10

### LINKED ISSUE #10: internal error: binding null type in envBindTypeRef
Opened by [henke](https://www.codeplex.com/site/users/view/henke)

In Fsi: 
[Loading X:\logary\src\Logary\WinPerfCounters.fs] 
error FS0192: internal error: binding null type in envBindTypeRef: Generic IKEv1, AuthIP, and IKEv2 

In C:\Program Files (x86)\Microsoft SDKs\F#\3.0\Framework\v4.0\Fsi.exe, Windows 8.1. 
[On this line of code:](https://github.com/logary/logary/blob/723996baa8fad748205dfb1c9203cdf2be7068db/src/Logary/WinPerfCounters.fs#L2654) 

Steps to repro: 
 1) start fsi 
 2) #load "WinPerfCounters.fs"

screen shot 2014-08-11 at 18 33 19

>comments
>henke wrote Aug 11, 2014 at 9:36 AM [x] 
>Also, IntelliSense doesn't show the symbols even after changing the commas to underscores.

### PR DESCRIPTION
**Pull request by KevinRansom**
Fixes #9, internal error: binding null type in envBindTypeRef
Fixes #10, internal error: binding null type in envBindTypeRef

Both issues were caused by the same underlying issue.  RefEmit automagically applies escaping to names that
contain a ','  So ``,`` becomes ``\,``.

When we tried to create a ref to a nested type we didn't add the ',' escaping so we couldnot bind to the created type.

The fix is very straightforward, change BasicQualifiedName to correctly escape names with comma's.

### CODE REVIEW

**Comment by latkin** [comment]
1-line fix FTW!

Banging on this, I see some related issues with pickling/de-pickling quotations containing types with commas.  They don't seem to be caused by this change, though, so I'll open as separate bugs.

Have you checked how this affects type providers? They rely on comma-encoding in the type name to handle static parameters, so might be worth a careful look.

For the tests - the bug was with FSI only, but current tests won't be run through FSI (at least not usually). Rather than add a new core area, it might be a better fit to expand existing backtick stuff at `fsharpqa\source\Conformance\LexicalAnalysis\IdentifiersAndKeywords`. You can add 2 lines to the env.lst file, one that runs via FSC, one via FSI (add `FSIMODE=EXEC`).

**Comment by KevinRansom** [comment]
I'm looking at some type provider stuff right now, so I can move right on to the new bugs.
I was in two minds about re-using an existing test area.  Although I concluded that item names have a bunch of test holes, they may not be terribly important, for example there are a number of banned characters that are not yet validated.  I was thinking of adding a bug to get those test holes fixed.
Good call on the fsimode-exec.

**Comment by dsyme** [comment]
Nice work!

**Comment by KevinRansom** [comment]
Closed Fixes #9 and Fixes #10

**Comment by ovatsus** [comment]
Hi, I started hitting this FS0192 problem recently, even when testing on latest release of 4.0:

https://github.com/tpetricek/FSharp.Formatting/issues/272

**Comment by latkin** [comment]
@ovatsus, looks like everything is cleared up in that issue, can you confirm? Turns out to be unrelated?

**Comment by ovatsus** [comment]
It's still a very bad error message for missing a reference, but yes, it is fixed now. Thanks

**Pull request closed without merging**
