### PR TITLE
fix appveyor build badge of master branch

### PR DESCRIPTION
**Pull request by enricosada**
the target was branch fsharp4

### CODE REVIEW

**Comment by enricosada** [comment]
master is failing atm

**Comment by KevinRansom** [comment]
Pretty sure this is because all of the extra diagnostic spew causes the build time to exceed the allowed appveyor. build time.

**Comment by enricosada** [comment]
not this time

```
[00:36:19] cwpmew901: YES
[00:36:19] cwpmew901: YES
[00:36:19] cwpmew901: YES
[00:36:19] Testing DllImport: Win32 GetLastError() = 126
[00:36:19] testing....
[00:36:19] testing....
[00:36:19] testing....
[00:36:19] testing....
[00:36:19] testing....
[00:36:19] testing....
[00:36:19] testing....
[00:36:19] Testing DllImport: Win32 GetLastError() = 126
[00:36:19] Test Passed
[00:36:19] The system cannot find the batch label specified - WRAPPER_NAMESPACE
[00:36:19] 
[00:36:19] FAILED: call to run.bat failed
[00:36:19] Error: 'RunTests.cmd release fsh
[00:36:19] arp Smoke' failed 
[00:36:19] Command exited with code 1
```

**Comment by enricosada** [comment]
i think that's because i changed

```
rem This can be set to 1 to reduce the number of permutations used and avoid some of the extra-time-consuming tests
set REDUCED_RUNTIME=0
```

was 1, that's to run all tests, but locally works and on pr build too, dunno

**Comment by KevinRansom** [comment]
I will see what needs to happen, if you fix it first let me know :-)

**Comment by enricosada** [comment]
Sent a pr, let's see

Inviato da Outlook




On Mon, Nov 16, 2015 at 11:05 AM -0800, "Kevin Ransom (msft)" <notifications@github.com> wrote:
I will see what needs to happen, if you fix it first let me know :-)


---

**Comment by KevinRansom** [comment]
Sweet

**Comment by KevinRansom** [comment]
Thank you for taking the time to fix this.

**Pull request merged**
