### PR TITLE
Simplify Name analyzer and code fix

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Current status: it diagnose all `FSharpSymbolUse`s as "unnecessary":

image

Now we need a list of opened namespaces and modules _at point in document_ to decide what part of qualified name may be omitted. 

@dsyme any points how to get namespaces and modules (with "has RequireQualifiedAccess attribute" and "has AutoOpen attribute") at a point in document? Maybe it's better to put them right into `FSharpSymbolUse`?

**Comment by vasily-kirichenko** [comment]
A crazy idea. Given a (partially) qualified name line `Ns1.Ns2.M1.M2.foo`, cut parts from the left until the remain name is still resolvable. The question is: how to try to resolve a long ident?

**Comment by dsyme** [comment]
> @dsyme any points how to get namespaces and modules (with "has RequireQualifiedAccess attribute" and "has AutoOpen attribute") at a point in document? Maybe it's better to put them right into FSharpSymbolUse?

This has come up before. I think you just have to plumb this down through the type checker.  The DisplayEnv (denv) active at any particular point contains an approximate list of opened prefix paths, but IIRC it's not exactly what you want, but close.  You might be able to modify it to get precisely what you need.  Then log that (in the TcSink), or it may be being logged already in the active name resolution environment.

**Comment by vasily-kirichenko** [comment]
@dsyme I've added a method that returns opened `ModuleOrnamespaceRef []` at point. Now the plan is:

* `FindAllUsageOfAllSymbolsInFile` (done)
* filter out symbol uses at definition 
* filter out symbol uses which has single part in their `LongIdent`
* get `Symbol.FullName`, parse it to `string []`

for each symbol use:

* cut first part from symbol use's `LongIdent`
* get all opened namespaces and modules at `SymbolUse.RangeAlternate.Start`
* for each ns or module:
  * concatenate ns/module `FullName` with what's left in the symbol use's `LongIdent`
  * if the result of ^^ equals to the symbol's `FullName`, then we are done - this part of `LongIdent` may be cut

All this does not feel very natural to me. May it be better to try something like 

* cut the first part as before
* `NameResolution.TryResolve(pos, LongIdent) |> List.isEmpty |> not` (I've no idea if such a function available though) 

?

**Comment by vasily-kirichenko** [comment]
image

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by forki** [comment]
image

**Comment by forki** [comment]
just tried it. but doesn't work for me:

image

**Comment by forki** [comment]
scratch that. somehow VS didn't load my VSIX. Now it works! Good job!

**Comment by forki** [comment]
mhm it doesn't work correctly for me:

image

**Comment by vasily-kirichenko** [comment]
@forki your screenshot looks totally OK for me. What do you find wrong on it?

**Comment by vasily-kirichenko** [comment]
Ah, yes. Reproduced.

**Comment by forki** [comment]
Also the suggestion text should be improved.

F#:

image

C#:

image

**Comment by vasily-kirichenko** [comment]
Found the bug, will fix in an hour.

Duplicates will also gone.

**Comment by forki** [comment]
cool.

so regarding the text: 

* The C# diagnostic reports "IDE0001 - Name can be simplified"
* The C# codefix has title "Simplify name '%s'"


    <data name="Simplify_name_0" xml:space="preserve">
      <value>Simplify name '{0}'</value>
    </data>

...

    <data name="Name_can_be_simplified" xml:space="preserve">
      <value>Name can be simplified.</value>
    </data>

**Comment by forki** [comment]
this is what they use for the DiagnosticsDescriptor:

        new DiagnosticDescriptor(
            IDEDiagnosticIds.SimplifyNamesDiagnosticId,
            s_localizableTitleSimplifyNames,
            s_localizableMessage,
            DiagnosticCategory.Style,
            DiagnosticSeverity.Hidden,
            isEnabledByDefault: true,
            customTags: DiagnosticCustomTags.Unnecessary);

**Comment by forki** [comment]
what about the other way around - graying out unused open directives?

**Comment by vasily-kirichenko** [comment]
@forki It was done in VFPT and it's very complicated and 100% correct. If we are gonna implement it, we should find a (much) better way.

**Comment by CyrusNajmabadi** [comment]
> if I understand correctly then DiagnosticCategory.Style maps to localized text "Style". Correct?

I'm not exactly sure what DiagnosticCategory is for.  Maybe @mavasani can shed some light here.

**Comment by vasily-kirichenko** [comment]
@forki all done, please test.

**Comment by vasily-kirichenko** [comment]
now it's done...

**Comment by forki** [comment]
@vasily-kirichenko this is great work, but 2 questions:

image

1) there is still the IDE0001 title missing
2) M2 could be simplified as well, right? It was proposed from the IDE in you last version

**Comment by forki** [comment]
damn, I love that feature. I just hope it makes the cut for RTM. It's just awesome.

**Comment by forki** [comment]
ok will send you a PR regarding the texts

**Comment by forki** [comment]
so that's fixed.

@KevinRansom please merge

image

**Comment by vasily-kirichenko** [comment]
I've fixed the bug with `M2`.

**Comment by forki** [comment]
yes that looks great:

image

**Comment by forki** [comment]
@vasily-kirichenko 

the following is technically correct:

image

But I think we should not suggest to remove the type name for unions - even if they don't have RQA.

**Comment by forki** [comment]
just tested Unions with RQA set. that works.

**Comment by vasily-kirichenko** [comment]
@KevinRansom thanks. Any chance it will come to RTM?

**Comment by KevinRansom** [comment]
Pretty close to zero.  But Update 1 is not far away.

**Comment by vasily-kirichenko** [comment]
@forki hm. It's interesting case. I think we should discuss non-RQA types in an issue.

**Comment by vasily-kirichenko** [comment]
@KevinRansom ok

**Comment by forki** [comment]
a bit unrelated: how do we know what already got merged for RTM?

**Comment by KevinRansom** [comment]
So far the cut-off date is 3rd January.  It may take some hardcore politicking to get more in.  Regardless of that I believe everything makes the cut for Update 1 and so update 1 is going to be a genuinely cool update to take.

Kevin

**Comment by forki** [comment]
or in other words: RTM will suck pretty badly ;-(

**Comment by KevinRansom** [comment]
@forki,

I can tell that you are a "The glass is half empty kind of guy".  We have a process of continuing improvement, and areas we know that Update 1 is going to be an improvement.  I expect Update 2 and 3 will be even better than the release preceding them.

Be happy that things will improve and quite quickly, or sad that things are not perfect right now ... the choice is up to you ... I'm going with the former .

**Comment by forki** [comment]
It's not about the glass being half-empty. I'm talking about the many many regression that we as group tried to solve. Iit's about not fucking up completely. MS and espcially the  community spend the last couple of weeks a crazy amount of time to make that roslyn switch smooth.

But especially the fixes in the last week were super important. TBH working on RC2 is basically impossible - not even simplest things work. There are situations were you can even have workaround other than using VS code or Vs2015/VS2013.

So I really hope Update 1 comes very very very soon. Sorry to sound so negative - but you know I'm meaning well.

**Comment by CyrusNajmabadi** [comment]
@forki That seems like an orthogonal issue to getting this specific feature in.  You are choosing to conflate them.

**Comment by forki** [comment]
@CyrusNajmabadi sorry I hijacked the issue for other things. Can you please rephrase the question - I'm a bit out of concext. (Really sorry)

**Comment by CyrusNajmabadi** [comment]
I'm also in the optimistic camp.  I'm super happy that we've put in work here to leverage the work that Roslyn has invested in.  It means we can improve the languges much more quickly.  But it has certainly come at a cost and it doing things like unification certainly is a lot of work.

But, just consider that by doing this we've actually been able to do these sorts of features without each language having to invest hundreds or thousands of hours into duplicating (incompletely) what C#/VB/TS/JS have produced.

**Comment by forki** [comment]
@CyrusNajmabadi @KevinRansom the problem is: a lot of the stuff already worked. Now we have really severe bugs in a RTM. That's just not what you as MS should find acceptable.

**Comment by CyrusNajmabadi** [comment]
@forki you said> or in other words: RTM will suck pretty badly ;-(

This was in reply to the statement that this feature would not make it in for update 1.  When you provided more information you explained that you were unhappy because  "I'm talking about the many many regression that we as group tried to solve."

To me, these are orthogonal issues.  Whether or not this feature makes it in, won't address your concerns about "the many many regression".  If you're upset about the state of F# as you see it in RTM, that's fine.  But it's nonsensical to get upset that new feature work won't get in.  If anything, we should be expecting that as the norm so that we can spend time investing in the areas of concern first.

**Comment by forki** [comment]
@CyrusNajmabadi absolutely. The new features don't need to be merged.
But things like setting a breakpoint in a IF condition would be really nice.

**Comment by CyrusNajmabadi** [comment]
I'm ok with it.  Because i'm taking a long term view on things.  I see the benefit we get from this work and how it can lead to better features and a better experience coming to users faster.  Previously there were many saying it was unacceptable that F# lagged in features behind C#/VB/etc. so much.  This is an attempt to get us to a state where F# can move along with the other languages with reasonable cost.  Where we share common infrastructure and can all collectively benefit.

But that has come at a cost.  Moving entirely from one architecture to another is no easy thing, and with our schedules it has been difficult.  I'm optimistic though that as we continually improve from update to update this will have been absolutely worth it.

**Comment by forki** [comment]
@CyrusNajmabadi how much F# do you write on a daily basis? I personally don't find it acceptable to have such regressions - that's why we tried to fix as many as possible.

**Comment by CyrusNajmabadi** [comment]
> I personally don't find it acceptable to have such regressions

That's fine.  I feel differently.

If RTM feels like too much of a step back for you, then i hope you will be able to use the existing versions of VS that you're using until we're able to lift the product up to a suitable level for you.

**Comment by forki** [comment]
but that said: @CyrusNajmabadi I'm really really happy that you and your team are helping us to get there. I personally appreciate that a lot and I must confess that I actually enjoyed that last minute sprint. Kudos!

I personally won't have too much trouble with the RTM since I know most of the workarounds - but there are so many more people out there....

**Comment by forki** [comment]
just to make that super clear: I am disappointed that we didn't get more fixes in for F# in time, but I'm very happy with the help of the roslyn team members. I hope we can continue on that. Thank you guys.

**Comment by smoothdeveloper** [comment]
Continuing off-topic, how easy will it be for those relying on F# to install the side line tooling (from this repository) when RTM is out?

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper CI must have fresh VS SDK installed. Having this done, it's easy to build and publish the open source vsix as an artifact of each successful build.

**Comment by forki** [comment]
I just diffed master with vs2017-rtm - ouch. this RTM will hurt!

**Comment by isaacabraham** [comment]
@CyrusNajmabadi I think we're all optimistic about the future of Visual F#. I surprised to see you say that you think it's acceptable to release a new version of VS that is actually *worse* than the current version though - which is essentially what we'll have in RTM.

**Comment by matthid** [comment]
To bring something positive into the discussion. @KevinRansom did not say there is zero chance for fixes to go in. How about opening a separate issue with a list of all the critical things we really should bring in? Maybe that makes it more easy to decide and can be transformed to a known issues/workarounds list later...

@KevinRansom would you be open for something like that?

**Pull request merged**
