### PR TITLE
Better error message when a record was given

### LINKED ISSUE #1280: Improve Error Reporting: Record does not match type when using Record Expressions
#### What

    type Record = {field:int}
    let l : int = {field=0}

Compiler says:
> The type 'int' does not contain a field 'field'

OR

    type Record = {field1:int; field2:int}
    let l : int = {Record.field1=0; field2=1}

Compiler says:
> The type 'int' does not contain a field 'field2'

#### Why

The error message doesn't tell you what the actual error is.
Of course, the above example is trivial, but for example if you pass a record expression to a library function that needs a list, you get really confused.

    type Record = {field1:int; field2:int}
    let doSomething (xs) = List.map (fun {field1=x} -> x) xs

    doSomething {Record.field1=0; field2=0}

> The type 'Record list' does not contain a field 'field2'

#### How
The usual error message when a type does not match:

> This expression was expcted to have type
> &nbsp; &nbsp; 'a list
> but here has type
> &nbsp; &nbsp; Record

### PR DESCRIPTION
**Pull request by forki**
fixes #1280

image

### CODE REVIEW

**Comment by forki** [comment]
ok the error shows this is harder than expected.

**Comment by forki** [comment]
ready for review

**Comment by KevinRansom** [comment]
@forki @dsyme 
I think the compiler is actually displaying the wrong error message for this scenario.
The record definition is fine, the problem is that the argument is not incompatible with Record it's that it is incompatible with list.

Please see samples below for reasoning.

````
type Record = {field1:int; field2:int}  
let doSomething (xs) = List.map (fun {field1=x} -> x) xs  


- //If we call the code correctly it might look like this:
- doSomething [{Record.field1=0; Record.field2=0}] ;;
val it : int list = [0]
>
- //or this:
- doSomething [{field1=0; field2=0}] ;;
val it : int list = [0]
>
- //or this:
- doSomething [{Record.field1=0; field2=0}] ;;
val it : int list = [0]
>
````

So to introduce the bug, it is that the argument to doSomething is not a list:

````
- //introduce bug, not a list it might look like this:
- doSomething {Record.field1=0; Record.field2=0} ;;

  doSomething {Record.field1=0; Record.field2=0} ;;
  ------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin(7,13): error FS0001: This expression was expected to have type
    'Record list'
but here has type
    'Record'
>
- //or this:
- doSomething {field1=0; field2=0} ;;

  doSomething {field1=0; field2=0} ;;
  ------------^^^^^^^^^^^^^^^^^^^^

stdin(10,13): error FS1129: This expression was expected to have type 'Record list' but here an incompatible record type was given.
>
- //or this:
- doSomething {Record.field1=0; field2=0} ;;

  doSomething {Record.field1=0; field2=0} ;;
  ------------^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin(13,13): error FS1129: This expression was expected to have type 'Record list' but here an incompatible record type was given.
>
````

We see that for the first error we get a clear actionable accurate message:
````
stdin(77,13): error FS0001: This expression was expected to have type
    Record list
but here has type
    Record
````
But the other two entries, give a bogus error message:
````
stdin(13,13): error FS1129: This expression was expected to have type 'Record list' but here an incompatible record type was given.
>
````

**Comment by forki** [comment]
Yes, I thought about raising a proper type unification error. But it wasn't
available at this position. I need to rewrite a bit more to make that work,
but I could try.

**Comment by forki** [comment]
a small bit of background:

the issue is that `typ` in https://github.com/Microsoft/visualfsharp/pull/1283/files#diff-dbb9e59b8ac1e1e04e1b00282a91ec97R2549 is given as `Record list`. That is because the `overallTy` is already resolved to this. Now the label resolution function tries to resolve the labels according to this type and sees that the type has no matching labels.

In the last bit we then seee that `typ` is not a record type so we give a bit better error message.

In the sample with `{Record.field1=0; Record.field2=0}` there is one level more in the resolution process and therefor the `typ` for the label resolution is `Record` and only the later type unification is failing.

**Comment by forki** [comment]
Ok I managed to make it a type unification error, but this change needs more review. 

My strategy:
* if we can't resolve to the given overallTy then we might just try to resolve to any record type and let the type checker fail directly after label resolution. I *think* this should work and should actually give the good error.

**Comment by forki** [comment]
fixed

**Pull request merged**
