### PR TITLE
nudge

### PR DESCRIPTION
**Pull request by KevinRansom**

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@mmitche Hey matt, how come I get Windows_NT Debug and Windows_NT Release as my build jobs.  I think they should be Windows_NT Debug, Windows_NT release_ci_part1 and Windows_NT ci_part2

I believe they were correctly generated: http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/master/job/GenPRTest/job/generator_prtest/7/console

Here is my netci.groovy file:https://github.com/Microsoft/visualfsharp/blob/master/netci.groovy

Kevin

**Comment by mmitche** [comment]
Can you try closing and reopening this PR?  The update isn't instantaneous, it's possible it just wasn't finished regenerating when you opened this PR.

**Comment by mmitche** [comment]
there it goes

**Pull request merged**
