### PR TITLE
fixed #3474 : change the sliceTake and sliceSkip behavior

### LINKED ISSUE #3474: arr.[..a]  != arr.[0..a]    and    arr.[a..(arr.Length-1)] != arr.[a..]
#### Repro steps

```fsharp
let arr = [1;2;3;4]
arr.[0..2] // [1;2;3;]   === arr.[..2]
arr.[0..1] // [1;2] === arr.[..1]
arr.[0..0] // [1] === arr.[..0]
arr.[0..-1] // []  ~~~~~~~~~   arr.[..(-1)] fail to an execaption.

arr.[1..3] // [2;3;4] === arr.[1..]
arr.[2..3] // [3;4] === arr.[2..]
arr.[3..3] // [4] === arr.[3..]
arr.[4..3] // []  ~~~~~~~~~  arr.[4..] fail to an execaption.
```

#### Expected behavior

i think the `arr.[..a]`  and the `arr.[0..a]` should has  same behavior.  both fail , or both return an empty slice.

#### Actual behavior

`arr.[0..a]`  return `[]`  and `arr.[..a]` goes to an execaption.

#### source in FSharp.Core 

    let sliceTake n l =
            if n < 0 then outOfRange()  //  <----- here should be []
            match l with
            | [] -> outOfRange()
            | x::xs ->
          // ..............
           match lst with
                | _ when i = 0 -> lst
                | _::t -> loop (i-1) t
                | [] -> outOfRange()  //  <----- here should be []
            loop n l

or : 

       member l.GetSlice(startIndex: int option, endIndex: int option ) = 
            match (startIndex, endIndex) with
            | None, None -> l
            | Some(i), None -> PrivateListHelpers.sliceSkip i l
            | None, Some(j) -> PrivateListHelpers.sliceTake j l
            | Some(i), Some(j) ->
                if i > j then [] else    // <---- change [] to outOfRange()
                PrivateListHelpers.sliceTake (j-i) (PrivateListHelpers.sliceSkip i l)

### PR DESCRIPTION
**Pull request by syeerzy**
fixed #3474 :

they will not throw for a  n < 0  and  n > list.Length. they return []
instead.

this make arr.[..a] always the same with arr.[0..a]
arr.[a..(arr.Length-1)]   === arr.[a..]

### CODE REVIEW

**Comment by KevinRansom** [comment]
@syeerzy, @dsyme 

Whilst I believe this is not really a breaking change, there is really a conceptual difficulty with this change.  Whether an API so should fix and go with bad input, or whether it should signal an error.

I am sure we can all produce examples of each type of behavior in FSharp.Core and and the base class libraries, however, I believe that in the main we tend to signal with an exception on input error.  For a developer who wants these APIs to behave in this way it is very relatively easily wrap them.

I am inclined to reject this change, what are your thoughts?

**Comment by KevinRansom** [comment]
And yes, I realize I have flip-flopped since March.  It's a good job I'm not a language designer. :-)

**Comment by dsyme** [comment]
@KevinRansom Definitely best to discuss on an RFC thread, but unfortunately that hasn't been created yet

Looking through https://github.com/Microsoft/visualfsharp/issues/2643 I am inclined to accept the change - the argument based on consistency under reasonable change is a sensible approach to design. 

For example, the argument that    ``l.[..x]`` is defined to be the same as ``l.[0..x]`` is quite sensible. Or, as the issue puts it, "``l.[..x]`` does not currently satisfy any reasonable definition"

**Comment by dsyme** [comment]
Actually RFC is here: https://github.com/fsharp/fslang-design/issues/217 and discussion is linked from there

**Comment by KevinRansom** [comment]
@dsyme ...
Oh it seems like we currently do the wrong thing on invalid indexes anyway.  So yes ... this makes things more consistent and easier to reason about.

@dotnet-bot test this please

**Comment by dsyme** [comment]
@syeerzy You have to update this ``Slicing`` test which is now failing, e.g. at this line, perhaps others too https://github.com/syeerzy/visualfsharp/blob/master/src/fsharp/FSharp.Core.Unittests/FSharp.Core/Microsoft.FSharp.Collections/ListType.fs#L235

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by syeerzy** [comment]
build failing on Ubuntu14.04 Release Build ,  the log said:

./autogen.sh --prefix=/usr
Please install autoconf
./autogen.sh: 4: ./autogen.sh: autoreconf: not found
Error: ./autogen.sh failed
Build step 'Execute shell' marked build as failure

what does it mean, and how to fix it?

**Comment by charlesroddie** [comment]
Does this PR only affect lists? So the work on arrays (1D and 2D), strings is still to be done?

**Pull request merged**
