### PR TITLE
[FS-1045] F# 4.x: Add ToFSharpFunc overloads for Func<...>, especially for .NET Core

### PR DESCRIPTION
**Pull request by dsyme**
RFC https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1045-func-to-fsharpfunc-overloads.md

Addresses https://github.com/Microsoft/visualfsharp/issues/1847 - ToFSharpFunc(Func) missing in .NET Core. 

Adds
```
    type FuncConvert = 
        static member  inline ToFSharpFunc       : converter:Func<'T,'U>          -> ('T -> 'U)
        static member  inline ToFSharpFunc       : converter:Func<'T1,'T2,'U>          -> ('T1 * 'T2 -> 'U)
        static member  inline ToFSharpFunc       : converter:Func<'T1,'T2,'T3,'U>          -> ('T1 * 'T2 * 'T3 -> 'U)
        static member  inline ToFSharpFunc       : converter:Func<'T1,'T2,'T3,'T4,'U>          -> ('T1 * 'T2 * 'T3 * 'T4 -> 'U)
        static member  inline ToFSharpFunc       : converter:Func<'T1,'T2,'T3,'T4,'T5,'U>          -> ('T1 * 'T2 * 'T3 * 'T4 * 'T5 -> 'U)
        static member  inline ToFSharpFunc       : converter:Func<'T1,'T2,'T3,'T4,'T5,'T6,'U>          -> ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 -> 'U)
        static member  inline ToFSharpFunc       : converter:Func<'T1,'T2,'T3,'T4,'T5,'T6,'T7,'U>          -> ('T1 * 'T2 * 'T3 * 'T4 * 'T5 * 'T6 * 'T7 -> 'U)

```

There was no good way to create an FSharpFunc object from C# on .NET core with a method call.

### CODE REVIEW

**Comment by dsyme** [comment]
@cartermp @neoeinstein  Just to note this will need an RFC since this also adds more overloads for ToFSharpFunc on .NET Framework

**Comment by KevinRansom** [comment]
Surface area change ... FSharp 4.2?

**Comment by dsyme** [comment]
Hmmm... Yes in principle.  But we should get the missing functionality into our FSharp.Core for .NET Core sooner than that I think.  I'll look if we can add just the one overload somehow

**Comment by KevinRansom** [comment]
@dsyme I'm okay with reving the version number, there are a number of PR's we would take if we do this.

**Comment by KevinRansom** [comment]
@dsyme can you resolve the conflicts pls.

**Comment by dsyme** [comment]
@KevinRansom resolved

**Comment by dsyme** [comment]
@cartermp @KevinRansom I've written the RFC https://github.com/Microsoft/visualfsharp/pull/3013/

However as noted in the RFC this is a breaking change for some C# code, **so don't merge this until we resolve that design question**

**Comment by dsyme** [comment]
See comment [here](https://github.com/Microsoft/visualfsharp/issues/1847#issuecomment-350317134) and in the RFC - I think we should not go ahead with this because it is a breaking change, and instead we should provide a .NET Standard 2.0 build of FSHarp.Core.dll where System.Converter is available.  Then we can keep the FuncConvert API the same as it has always been.

**Comment by 0x53A** [comment]
Everything except ``System.Func<'T,'U>`` can be safely taken, right?

In that case, why not just skip it?

IF the user proves an inline lambda, then the C# compiler will happily map it to a Converter instead of a Func.

IF the user wants to pass-through an existing Func delegate, then he would need to wrap it once - but I don't think that would be a killer-downside.

**Comment by KevinRansom** [comment]
@dsyme ... what do you want to do with this PR?

**Comment by brettfo** [comment]
@dsyme, can you retarget this to `master`?  I deleted the `dev15.6` branch (which this was targeting) because it's old and we have a tag for it.

**Comment by dsyme** [comment]
@brettfo Are you sure you don't want this at `dev15.8`?  It needs to target a branch that can bump the FSharp.Core version number

**Comment by dsyme** [comment]
Continued at https://github.com/Microsoft/visualfsharp/pull/4815

**Pull request closed without merging**
