### PR TITLE
Fix xunit test result call

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@enricosada Fixes an issue with your netci.groovy file.

**Comment by enricosada** [comment]
thx /cc @otawfik-ms

**Comment by enricosada** [comment]
@mmitche we dont use xunit btw, this enable it. i think should be `false` instead of `'false'`

**Comment by otawfik-ms** [comment]
Thanks @mmitche ! I see the change in your API here:
https://github.com/dotnet/dotnet-ci/commit/03c884956cfb7a2033c9ca3da38021fe67aef60b#diff-dde0e994d5b4274ecd0214ebe6f66580

CC @TyOverby

**Pull request merged**
