### PR TITLE
Fix 1373: add checks for famANDassembly visibility

### PR DESCRIPTION
**Pull request by 0x53A**
see https://github.com/Microsoft/visualfsharp/pull/1547#issuecomment-282570862

-----------------------
Edit: the current failure is 

```
+++ Import (FamAndAssembly.fs) +++
Microsoft (R) F# Compiler version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.
Peverify: [peverify.exe FamAndAssembly.dll ]

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

 [HRESULT 0x80070002] - The system cannot find the file specified.

1 Error(s) Verifying FamAndAssembly.dll
PeVerify Failed the test
FAIL
```

and I have no idea what causes that.
It looks like compilation is successful (or there should be any error from fsc), but it then can't find the dll.

### CODE REVIEW

**Comment by dsyme** [comment]
>  [HRESULT 0x80070002] - The system cannot find the file specified.

I think this means a referenced file like AccessibilityTests.dll is not being found.  I'm not sure, I'll try your PR locally

**Comment by dsyme** [comment]
@0x53A I fixed up the FamAndAssembly test - you had compiled "AccessibilityTests.dll" as "Accessibility.dll" and then renamed the file - just needed to recompile that DLL

**Comment by dsyme** [comment]
@0x53A Note the two FamOrAssembly tests are still commented out

**Comment by 0x53A** [comment]
@dsyme thanks! I was stuck with the peverify error and didn't have the environment set up for running the tests locally (no perl). No idea why I did the rename, that was a long time ago.

> just needed to recompile that DLL

did you fix the binary after compilation? Originally I used dnSpy to change the accessibility for the two properties, because you can't actually specify FamOrAssembly  / FamAndAssembly in C#.

> Note the two FamOrAssembly tests are still commented out

yes, that was on purpose because they failed - see https://github.com/Microsoft/visualfsharp/issues/2496.

**Comment by dsyme** [comment]
> did you fix the binary after compilation? Originally I used dnSpy to change the accessibility for the two properties, because you can't actually specify FamOrAssembly / FamAndAssembly in C#.

No, I didn't - could you fix that up?

**Comment by dsyme** [comment]
Currently this failure is showing: Import (FamAndAssembly_NoIVT.fs) -- failed

Perhaps that's expected given I didn't patch the binary

**Comment by dsyme** [comment]
@0x53A @KevinRansom I believe this is ready

**Comment by dsyme** [comment]
@0x53A We will squash

**Pull request merged**
