### PR TITLE
change implementation of List.Min from Seq.Min to List.reduce

### PR DESCRIPTION
**Pull request by AviAvni**
Changing the implementation of List.min from Seq.min that use IEnumerable
to List.reduce which is more native way to traverse the list implemented by recursion
that compiles to while loop
benchmarks: https://gist.github.com/AviAvni/0a3576a619ff9bf4acf1958b8ca1c63b

### CODE REVIEW

**Comment by KevinRansom** [comment]
Avi, thanks for theis PR: 
the error is:
[00:21:37] 1) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.ListProperties.min is opposite of max
[00:21:37] System.Exception : Falsifiable, after 1 test (0 shrinks) (StdGen (3867478,296137611)):
[00:21:37] Original:
[00:21:37] []
[00:21:37]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:21:37]    at FsCheck.Runner.check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 269
[00:21:37]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.ListProperties.min is opposite of max() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\ListProperties.fs:line 436
[00:21:37] 
[00:21:37] 2) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.ListProperties.minBy id is same as min
[00:21:37] System.Exception : Falsifiable, after 1 test (0 shrinks) (StdGen (5898733,296137611)):
[00:21:37] Original:
[00:21:37] []
[00:21:37]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:21:37]    at FsCheck.Runner
[00:21:37] .check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 269
[00:21:37]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.ListProperties.minBy id is same as min() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\ListProperties.fs:line 456
[00:21:37] 
[

**Comment by forki** [comment]
@KevinRansom @otawfik-ms do you know why this doesn't break the jenkins builds?

**Comment by AviAvni** [comment]
Because I made seperae PR to min and max the error (as @latkin suggested)
and the error mesage was changed from
Error "The input sequence was empty.
Parameter name: source"
to
Error "The input list was empty.
Parameter name: list"
which is more correct som when the 2 of the PR accepted then this will be ok

**Comment by forki** [comment]
No that's not what I meant. My question is why does the appveyor build detect the difference, but the Travis build does not. This is not really related to your change. But this suggests that property based tests are not run on TravisCI (and there might even be a good reason for this)

**Comment by KevinRansom** [comment]
It does not yet run all of the tests, I pay attention to appveyor right now.

**Comment by latkin** [comment]
@AviAvni the fix is fine, but you might want to consider combining the `min` and `max` PRs into 1 so that the tests stay happy.

**Pull request closed without merging**
