### PR TITLE
use shared MEF components instead of static fields

### PR DESCRIPTION
**Pull request by vladima**

### CODE REVIEW

**Comment by KevinRansom** [comment]
The CI is a bit borked right now and we are in the middle of an office move.

Kevin

**Comment by forki** [comment]
@KevinRansom I think it's kind of important to have that fixed right now.

**Comment by isaacabraham** [comment]
Confused. What does office move have to do with CI server?

**Comment by Pilchie** [comment]
None of the people in redmond are allowed in the building, and many are in fact off work yesterday and today...

**Comment by forki** [comment]
Still don't understand what this has to do with a CI server. ;-)

**Comment by isaacabraham** [comment]
Self hosted in the corner of said office? ;)

**Comment by dsyme** [comment]
@forki @isaacabraham I'm on it.

**Comment by dsyme** [comment]
OK, well, this change looks good to me.  Total MEF voodoo :)

**Pull request merged**
