### PR TITLE
Proper structs and interfaces colorization

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes some of bugs reported in https://github.com/Microsoft/visualfsharp/issues/2410

image

image

### CODE REVIEW

**Comment by jack-pappas** [comment]
Awesome! I've been wanting this in F# for a long time.

**Comment by KevinRansom** [comment]
@vasily-kirichenko conflicts.

**Comment by vasily-kirichenko** [comment]
@KevinRansom Fixed.

**Comment by KevinRansom** [comment]
@vasily-kirichenko 

Thanks mate

Kevin

**Pull request merged**
