### PR TITLE
List sum, sumBy perf

### PR DESCRIPTION
**Pull request by AviAvni**
Changing the implementation of List.sum/sumBy from Seq.sum/sumBy that use IEnumerable
to implementation like List.fold which is more native way to traverse the list implemented by recursion
that compiles to while loop
benchmarks: https://gist.github.com/AviAvni/0a3576a619ff9bf4acf1958b8ca1c63b

### CODE REVIEW

**Comment by dsyme** [comment]
A few comments

* Basically - great to see this address

* I'd rather see an explicit loop + mutable accumulator, rather than ``fold``.  ``fold`` is not guaranteed to be inlined so I don't expect it to be as fast as possible

* A single PR dealing with ``average/averageBy``, ``sum/sumBy``, ``max/maxBy`` and ``min/minBy`` would be great - all of these currently call Seq.

**Comment by AviAvni** [comment]
@dsyme I'm happy to contribute to the F# compiler repo
@latkin  is my mentor on the FSSF program and I asked him to help me do that
please look at the gist with the benchmarks the mutable implementation of sum is slightly slow
then the functional style implementation

I merged the sum and sumBy PR
Implemented the averageBy and both average and averageBy in the same PR
and merged max and min to the same PR
now I'm working on minBy and maxBy on the same PR as min and max

**Comment by radekm** [comment]
> look at the gist with the benchmarks the mutable implementation of sum is slightly slow
then the functional style implementation

This is interesting. It would be nice to see additional measures like standard deviation. Some benchmarking libraries like [BenchmarkDotNet](https://github.com/PerfDotNet/BenchmarkDotNet) can compute it automatically. [Here](https://github.com/Microsoft/visualfsharp/pull/879#issuecomment-174072092) is an example how to use the library in F#.

Additionally it seems that the code from the [gist](https://gist.github.com/AviAvni/0a3576a619ff9bf4acf1958b8ca1c63b/b99d6496a69838a28c7a285ff65898b339f64afa) eg.

```fsharp
let inline sumBy f list = 
    match list with 
    | [] -> invalidArg "source" "Error"
    | _ ->
        let rec loop xs sum = 
            match xs with 
            | [] -> sum
            | h::t -> loop t (Checked.(+) sum (f h))
        loop list LanguagePrimitives.GenericZero< 'U >
```

raises when `list` is empty but actual `List.sumBy` from the standard library works just fine (eg. `List.sumBy (fun i -> i) ([] : list<int>)` returns 0).

**Comment by AviAvni** [comment]
@radekm thank I update the function implementation and the gist
and i'm looking at the benchmark liberary

**Comment by AviAvni** [comment]
MSBOT please build and test

**Comment by AviAvni** [comment]
MSBOT please test

**Comment by AviAvni** [comment]
MSBOT test please

**Pull request merged**
