### PR TITLE
Detect incorrect module declarations

### LINKED ISSUE #1214: Improve error reporting: Detect module declarations that incorrectly end with `=`
Depending on whether you have a namespace or not, a module declaration may or may not require an `=`. This caught me out today (it's been a long time since I did any F#); I created a new file and deleted the namespace and got this compile error:

> Files in libraries or multiple-file applications must begin with a namespace or module declaration

As I had some F# code open in my browser that had `module blah =` I copied it and continued to get the same message:

fsharp2

In hindsight, the example given in the message doesn't have an `=` so I should've figured it out, but it actually took much googling and finding [a comment on this answer](http://stackoverflow.com/a/2250463/25124) that made me realise the issue.

I think it might be worthwhile calling this out in the message (or ideally, detecting when there is a module declaration with an `=` that shouldn't be there and giving a specific message). It seems effort is going into improving messages in #1103.

### PR DESCRIPTION
**Pull request by forki**
fixes #1214 

image

### CODE REVIEW

**Comment by KevinRansom** [comment]
__Failures, probably related:__
+++ Conformance\ImplementationFilesAndSignatureFiles\NamespacesFragmentsAndImplementationFiles\basic (E_NoNamespaceModuleDec02a.fs) +++
Microsoft (R) F# Compiler version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.
(7,1): error FS0222: Files in libraries or multiple-file applications must begin with a namespace or module declaration. When using a module declaration at the start of a file the '=' sign is not allowed. If this is a top-level module, consider removing the = to resolve this error.

*** The following necessary lines were never matched:
***	\(7,1\):.+error FS0222:.+Files in libraries or multiple-file applications must begin with a namespace or module declaration, e\.g\. 'namespace SomeNamespace\.SubNamespace' or 'module SomeNamespace\.SomeModule'\. Only the last source file of an application may omit such a declaration\.$


*** The following necessary lines were incorrectly matched:

Unexpected Compiler Output 
FAIL




+++ Warnings (ModuleWithoutNamespace.fs) +++
Microsoft (R) F# Compiler version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.
(5,12): warning FS0988: Main module of program is empty: nothing will happen when it is run

*** The following necessary lines were never matched:
***	\(10,5\):.+error FS0193:.+Type constraint mismatch. The type


*** The following necessary lines were incorrectly matched:

Unexpected Compiler Output 
FAIL

**Comment by forki** [comment]
I will continue to work on this on Monday.
On May 28, 2016 01:34, "Kevin Ransom (msft)" <notifications@github.com>
wrote:

*Failures, probably related:*
+++
Conformance\ImplementationFilesAndSignatureFiles\NamespacesFragmentsAndImplementationFiles\basic
(E_NoNamespaceModuleDec02a.fs) +++
Microsoft (R) F# Compiler version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.
(7,1): error FS0222: Files in libraries or multiple-file applications must
begin with a namespace or module declaration. When using a module
declaration at the start of a file the '=' sign is not allowed. If this is
a top-level module, consider removing the = to resolve this error.

*** The following necessary lines were never matched:
*** (7,1):.+error FS0222:.+Files in libraries or multiple-file applications
must begin with a namespace or module declaration, e.g. 'namespace
SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the
last source file of an application may omit such a declaration.$

*** The following necessary lines were incorrectly matched:

Unexpected Compiler Output
FAIL

+++ Warnings (ModuleWithoutNamespace.fs) +++
Microsoft (R) F# Compiler version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.
(5,12): warning FS0988: Main module of program is empty: nothing will
happen when it is run

*** The following necessary lines were never matched:
*** (10,5):.+error FS0193:.+Type constraint mismatch. The type

*** The following necessary lines were incorrectly matched:

Unexpected Compiler Output
FAIL

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/pull/1220#issuecomment-222274716>,
or mute the thread
<https://github.com/notifications/unsubscribe/AADgNNcyhFQL65fuOrVdMsWuPYpTU5-Wks5qF39ogaJpZM4ImlmM>
.

**Comment by forki** [comment]
I think this one is ready.

**Comment by KevinRansom** [comment]
This looks great.

**Comment by KevinRansom** [comment]
Thanks Steffen for taking care of this.

Kevin

**Pull request merged**
