### PR TITLE
[Jenkins] Added NUnit Test Results/Running Smokes for now

### PR DESCRIPTION
**Pull request by otawfik-ms**

### CODE REVIEW

**Comment by otawfik-ms** [comment]
test ci please

**Comment by otawfik-ms** [comment]
@dotnet-bot test ci please

**Comment by otawfik-ms** [comment]
@dotnet-bot test ci please

**Comment by otawfik-ms** [comment]
@mmitche can you please take a look?

**Comment by mmitche** [comment]
LGTM

**Comment by enricosada** [comment]
that's going to fail, if you use `cambridge_suite,smoke_only` as test profile a directory `d:\jenkins\cambridge_suite,smoke_only\` is created, and that fail the build like `net40,portable..` because of `,` in path

you need to sanitize name or map profile name -> appveyor argyments

**Comment by mmitche** [comment]
@otawfik-ms Yeah good point.  Also keep in mind that path length limits on WIndows sometimes cause problems, so keeping them (relatively) short is good.

**Comment by otawfik-ms** [comment]
@dotnet-bot test ci please
@mmitche @enricosada  I see. Thanks for pointing this out.

**Comment by smoothdeveloper** [comment]
@enricosada, I'm curious what would be the changes needed in test suite so it can be run from folders containing comma in it? What are the other things which should currently not be in path names?

**Comment by otawfik-ms** [comment]
@dotnet-bot test ci please

**Comment by enricosada** [comment]
@smoothdeveloper

```
06:11:11   C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:0169,0067,1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE;TRACE /highentropyva+ /reference:"d:\j\workspace\Microsoft_visualfsharp\net40,portable7,portable47,portable78,portable259,vs_prtest\Release\net40\bin\FSharp.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /debug+ /debug:pdbonly /optimize+ /out:obj\Release\DefinitionLocationAttribute.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /warnaserror+ /utf8output ArtificalEventInfo.cs ArtificialConstructorInfo.cs ArtificialMethodInfo.cs ArtificialParamInfo.cs ArtificialType.cs ArtificialPropertyInfo.cs TypeProviderInCSharp.cs ..\Helpers.cs "C:\Users\dotnet-bot\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
06:11:11 
CSC : error CS0006: Metadata file 'd:\j\workspace\Microsoft_visualfsharp\net40' could not be found [d:\j\workspace\Microsoft_visualfsharp\net40,portable7,portable47,portable78,portable259,vs_prtest\vsintegration\src\unittests\Resources.MockTypeProviders\DefinitionLocationAttribute\DefinitionLocationAttribute.csproj]
```

problem is not with test suite, it's the csc compiler. 

i think it's trying to split `,` to use an assembly qualified name as reference, like `mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`.

**Comment by smoothdeveloper** [comment]
@enricosada thanks, should it be filed as a bug over http://github.com/dotnet/roslyn?

I tried to reproduce by referencing an assembly in a folder containing `,` but it does build from VS 2015.

```
C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702,2008 /nostdlib+ /platform:anycpu32bitpreferred /errorreport:prompt /warn:4 /define:DEBUG;TRACE /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:"C:\tmp\roslyn,bug\ConsoleApplication1\ClassLibrary1\bin\Debug\ClassLibrary1.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Net.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.Linq.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\ConsoleApplication1.exe /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:exe /utf8output Program.cs Properties\AssemblyInfo.cs "C:\Users\gauthier.segay\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cs" obj\Debug\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs obj\Debug\\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs obj\Debug\\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs
```

Do you know what else I would need to make a simple reproduce and open upstream bug?

**Comment by enricosada** [comment]
nope, sry, i only read the build log. i think it's a roslyn bug, but dont know how to minimize the repro

**Pull request merged**
