### PR TITLE
WIP: Fix 1373: add checks for famANDassembly visibility

### PR DESCRIPTION
**Pull request by 0x53A**
fixes https://github.com/Microsoft/visualfsharp/issues/1373

I have done a positive manual test that the linked code now compiles.

If you can give me some guidance where an appropriate place would be, I would also like to add some tests.

### CODE REVIEW

**Comment by forki** [comment]
did you do that at remmidemmi hackathon?

**Comment by forki** [comment]
You could put your fs file + the manipulated dll in https://github.com/Microsoft/visualfsharp/tree/master/tests/fsharpqa/Source/Import and hook it up in the env.lst in that folder. Look into other env.lst files to see how to add the dll to the compiler call. If you don't get it working then I'm happy to help

**Comment by 0x53A** [comment]
@forki yes.

Adding a test seems straightforward, thanks. (I can just redo what you did in https://github.com/Microsoft/visualfsharp/pull/1552/files).

Will try it when I have some time (this evening or tomorrow).

**Comment by 0x53A** [comment]
Ok I think the unit tests should now be correct - but there is one failure:

The following code, which to the best of my knowledge should compile, fails:

```F#
// #Regression #NoMT #Import 

namespace NS

// note: the assembly 'Accessibility' has an IVT to this assembly

type T() =
    inherit Accessibility()
    member x.Test() = base.FamOrAssembly

module M =
    let Test() = Accessibility().FamOrAssembly

```

image

It looks like the compiler only looks at the FAM part, and ignores the Assembly part.

**Comment by KevinRansom** [comment]
@0x53A @dsyme 

Do we have any plans to continue working on this PR.  It has been quiet for quite a while.

Kevin

**Comment by KevinRansom** [comment]
@0x53A 

Thank you for submitting this PR, I am closing it because it has been quiescent since October.  Please reopen or resubmit when you have time to get back to this.

Thank you

Kevin

**Comment by 0x53A** [comment]
Hi @KevinRansom,
sorry for not responding earlier, this kind of got off my radar ...

This PR contained two things:

* fixed check for famANDassembly 
* unit tests for both famANDassembly  and famORassembly

The famANDassembly stuff seems to work, but one unit test for famORassembly failed.

I tried debugging into the failure, and while I think I found the cause, I have no idea how to fix it.

So ...

my plan is to resubmit the famANDassembly stuff, including the famANDassembly UT, but excluding the failing famORassembly UT ...

and create a new issue for famORassembly .

**Pull request closed without merging**
