### PR TITLE
Bug fix to allow RebuildShapeCombination for indexed static property gets

### PR DESCRIPTION
**Pull request by alan-geller**
The current implementation of RebuildShapeCombination fails if there are parameters passed to a StaticPropGetOp. The match pattern requires the arguments to be an empty list, even though the code for that match doesn't require this, and indeed mkStaticPropertyGet explicitly supports indexed properties and non-empty args lists.

All that is required is to replace the [] in the match with _, so that any list (whether empty or not) will match.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@alan-geller could you add a regression test case so that we can keep this working?

Thanks

Kevin

**Comment by smoothdeveloper** [comment]
would it make it easier to diagnostic issues in this code if 

https://github.com/Microsoft/visualfsharp/pull/2512/files#diff-68af4b41d78e9577b6a461499c202298R2201

was also printing `%A` of `op,args`?

**Comment by smoothdeveloper** [comment]
Should we format that whole pattern match which is a bit difficult to comprehend due to misalignment?

**Comment by dsyme** [comment]
The fix is correct, just needs the regression test

**Comment by alan-geller** [comment]
I pushed a unit test. I think it's correct and in the right place, although it's a bit hard to be sure.

**Comment by KevinRansom** [comment]
@alan-geller That's great, thanks, I will take care of the hand-waving to make sure the test is situated well.


Kevin

**Comment by alan-geller** [comment]
Thanks, @KevinRansom !

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
Thank you for this

**Pull request merged**
