### PR TITLE
Trace errors in from fsdiff

### PR DESCRIPTION
**Pull request by forki**
I used this to fix bugs that are not reproducible on my system.

I wonder if we can upload the .err file to jenkins instead of tracing it

### CODE REVIEW

**Comment by dsyme** [comment]
We should really just remove all calls to fsdiff (at least from FSHarpSuite) and use direct calls to the logic.  THere's only pain in having this exe.

I'm not sure if it's used by the FSharpQA suite too though

**Comment by forki** [comment]
Good point. Will try to do that. That code looks like it's in need of a big clean up anyways

**Comment by forki** [comment]
@enricosada could you please review this? thx

**Comment by enricosada** [comment]
@forki seems ok :+1:
As a note, for language sensitive tests (with diff usually) we can also pass `--preferreduilang:en` to `fsc`, that should fix for everyone (like me in italian)

**Comment by forki** [comment]
@dsyme can we get this in? would help to understand errors in ci_part2

**Comment by dsyme** [comment]
Sure

**Pull request merged**
