### PR TITLE
[WIP] Reproduce #485 - External function arguments flagged as unused

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
if not alreadyDone &&
       cenv.reportErrors && 
       not v.HasBeenReferenced && 
       not v.IsCompiledAsTopLevel &&
       not (v.DisplayName.StartsWith("_", System.StringComparison.Ordinal)) &&
       not v.IsCompilerGenerated &&
       ??? 
    then

@dsyme any ideas what's missing here?

**Comment by forki** [comment]
so with v.IsLinked the errors are gone. But is that correct?

**Comment by forki** [comment]
test errors suggest it's not the correct flag ;-)

**Comment by dsyme** [comment]
I suspect the problem with Extern functions is that the RHS (right-hand-side) expression of the corresponding binding is just not a proper lambda containing the arguments.  

Normally `let f x = rhs`` becomes ``Binding(f,  x-as-a-pattern, (fun x -> rhs)`` roughly speaking.  The syntactic lambda's are constructed via ``PushPatternToExpr``.

But for an extern binding there is just this - and it's not a lambda:

```
        let rhsExpr = SynExpr.App(ExprAtomicFlag.NonAtomic,
                                  false, 
                                  SynExpr.Ident(ident("failwith",rhs parseState 6)),
                                  SynExpr.Const(SynConst.String("extern was not given a DllImport attribute",rhs parseState 8),rhs parseState 8),
                                  mRhs)
```

For codegen purposes that doesn't matter.  But for tracking whether arguments are used it will.  I suspect the best fix might be a special case for ``DllImport`` attributed functions in ``CheckBinding``.

**Comment by vasily-kirichenko** [comment]
@forki any progress on this? :)

**Comment by forki** [comment]
Implemented in https://github.com/Microsoft/visualfsharp/pull/2032

**Pull request closed without merging**
