### PR TITLE
Fix crash from #3168

### LINKED ISSUE #3168: Can't open any F# project settings anymore
With VF# tools from master I can't open any F# project settings anymore. I always see:

image

### PR DESCRIPTION
**Pull request by forki**
fixes #3168

### CODE REVIEW

**Comment by davkean** [comment]
Without ConnectionPointContainer support the property pages won't sync the changes from the project when they are changed? Has this support always been missing? Why did it only start crashing now?

**Comment by forki** [comment]
Saw the crash first time after reinstall of vs2017 earlier this week

**Comment by davkean** [comment]
Maybe it's always been missing and you it just started asserting because you've got debug bits installed?

**Comment by forki** [comment]
I have debug bits installed since Vs2017 hit first public prerelease.

Am 01.06.2017 1:22 nachm. schrieb "David Kean" <notifications@github.com>:

**Comment by saul** [comment]
Yeah commenting the assert definitely isn't the fix here - we should figure out why it's being hit.

**Comment by forki** [comment]
@saul ;-)

**Comment by forki** [comment]
ok. reinstall VS worked. lol

**Pull request closed without merging**
