### PR TITLE
Avoid referencing several System.Collections.Immutable

### LINKED ISSUE #5572: 8 warnings on master
**Update:**

```
"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj" (Build target) (11) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.PropertyPages\FSharp.PropertiesPages.vbproj" (default target) (14:2) ->
(ResolveAssemblyReferences target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.Threading" that could not be resolved.  These reference conflicts are listed in the build log when
log verbosity is set to detailed. [C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.PropertyPages\FSharp.PropertiesPages.vbproj]

"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj" (Build target) (11) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj" (default target) (16:2) ->
(ResolvePackageAssets target) ->
  C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605: Detected package downgrade: Microsoft.VisualStudio.Language.StandardClassification from 15.8.238-preview to 15.6.27740. Reference the package directly from the project to select a different version.
C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605:  FSharp.Editor -> Microsoft.CodeAnalysis.EditorFeatures 2.9.0-beta8-63208-01 -> Microsoft.VisualStudio.Language.StandardClassification (>= 15.8.238-preview)
C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605:  FSharp.Editor -> Microsoft.VisualStudio.Language.StandardClassification (>= 15.6.27740)
  C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605: Detected package downgrade: Microsoft.VisualStudio.Language.Intellisense from 15.8.238-preview to 15.6.27740. Reference the package directly from the project to select a different version.
C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605:  FSharp.Editor -> Microsoft.CodeAnalysis.EditorFeatures 2.9.0-beta8-63208-01 -> Microsoft.VisualStudio.Language.Intellisense (>= 15.8.238-preview)
C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605:  FSharp.Editor -> Microsoft.VisualStudio.Language.Intellisense (>= 15.6.27740)

"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj" (Build target) (11) ->
(ResolveAssemblyReferences target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.Threading" that could not be resolved.  These reference conflicts are listed in the build log when
log verbosity is set to detailed. [C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj]

"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj" (Build target) (19) ->
(ResolvePackageAssets target) ->
  C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj : warning NU1603: Microsoft.VisualStudio.Language.Intellisense 15.8.525 depends on Microsoft.VisualStudio.ImageCatalog (>= 15.8.27731) but Microsoft.VisualStudio.ImageCatalog 15.8.27731 was not found. An approximate best
match of Microsoft.VisualStudio.ImageCatalog 15.8.27828 was resolved.
  C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj : warning NU1603: Microsoft.CodeAnalysis.EditorFeatures 2.9.0-beta8-63208-01 depends on Microsoft.VisualStudio.Language.Intellisense (>= 15.8.238-preview) but Microsoft.VisualStudio.Language.Intellisense 15.8.238-preview
was not found. An approximate best match of Microsoft.VisualStudio.Language.Intellisense 15.8.525 was resolved.
  C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj : warning NU1603: Microsoft.CodeAnalysis.EditorFeatures 2.9.0-beta8-63208-01 depends on Microsoft.VisualStudio.Language.StandardClassification (>= 15.8.238-preview) but Microsoft.VisualStudio.Language.StandardClassificati
on 15.8.238-preview was not found. An approximate best match of Microsoft.VisualStudio.Language.StandardClassification 15.8.525 was resolved.
  C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj : warning NU1603: Microsoft.VisualStudio.Language 15.8.525 depends on StreamJsonRpc (>= 1.3.6) but StreamJsonRpc 1.3.6 was not found. An approximate best match of StreamJsonRpc 1.3.23 was resolved.

    8 Warning(s)
    0 Error(s)
```

`build vs`:

```
"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\src\fsharp\FSharp.Compiler.Private\FSharp.Compiler.Private.fsproj" (Build target) (4) ->
(ResolveAssemblyReferences target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Collections.Immutable". Check to make sure the assembly exists on disk. If this reference is requ
ired by your code, you may get compilation errors. [C:\repos\visualfsharp\src\fsharp\FSharp.Compiler.Private\FSharp.Compiler.Private.fsproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3243: No way to resolve conflict between "System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Collections.Immutable".
Choosing "System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily. [C:\repos\visualfsharp\src\fsharp\FSharp.Compiler.Private\FSharp.Compiler.Private.fsproj]


"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj" (Build target) (11) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.PropertyPages\FSharp.PropertiesPages.vbproj" (default target) (14:2) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.Threading" that could not be resolved.  These reference conflicts are listed in the build log when
log verbosity is set to detailed. [C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.PropertyPages\FSharp.PropertiesPages.vbproj]


"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj" (Build target) (11) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj" (default target) (16:2) ->
(ResolvePackageAssets target) ->
  C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605: Detected package downgrade: Microsoft.VisualStudio.Language.StandardClassification from 15.8.238-preview to 15.6.27740. Reference the package directly from the project to select a different version.
C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605:  FSharp.Editor -> Microsoft.CodeAnalysis.EditorFeatures 2.9.0-beta8-63208-01 -> Microsoft.VisualStudio.Language.StandardClassification (>= 15.8.238-preview)
C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605:  FSharp.Editor -> Microsoft.VisualStudio.Language.StandardClassification (>= 15.6.27740)
  C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605: Detected package downgrade: Microsoft.VisualStudio.Language.Intellisense from 15.8.238-preview to 15.6.27740. Reference the package directly from the project to select a different version.
C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605:  FSharp.Editor -> Microsoft.CodeAnalysis.EditorFeatures 2.9.0-beta8-63208-01 -> Microsoft.VisualStudio.Language.Intellisense (>= 15.8.238-preview)
C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj : warning NU1605:  FSharp.Editor -> Microsoft.VisualStudio.Language.Intellisense (>= 15.6.27740)


"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj" (Build target) (11) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp.Editor.fsproj" (default target) (16:2) ->
(CoreCompile target) ->
  C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\Navigation\NavigateToSearchService.fs(185,32): warning FS0044: This construct is deprecated. Use INavigateToSearchService_RemoveInterfaceAboveAndRenameThisAfterInternalsVisibleToUsersUpdate instead. [C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp
.Editor.fsproj]
  C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\Navigation\NavigateToSearchService.fs(240,15): warning FS0044: This construct is deprecated. Use INavigateToSearchService_RemoveInterfaceAboveAndRenameThisAfterInternalsVisibleToUsersUpdate instead. [C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp
.Editor.fsproj]
  C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\Navigation\NavigateToSearchService.fs(240,15): warning FS0044: This construct is deprecated. Use INavigateToSearchService_RemoveInterfaceAboveAndRenameThisAfterInternalsVisibleToUsersUpdate instead. [C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp
.Editor.fsproj]
  C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\Navigation\NavigateToSearchService.fs(240,15): warning FS0044: This construct is deprecated. Use INavigateToSearchService_RemoveInterfaceAboveAndRenameThisAfterInternalsVisibleToUsersUpdate instead. [C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\FSharp
.Editor.fsproj]


"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj" (Build target) (11) ->
(ResolveAssemblyReferences target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.Threading" that could not be resolved.  These reference conflicts are listed in the build log when
log verbosity is set to detailed. [C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj]


"C:\repos\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\repos\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj" (Build target) (20) ->
(ResolvePackageAssets target) ->
  C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj : warning NU1603: Microsoft.VisualStudio.Language.Intellisense 15.8.525 depends on Microsoft.VisualStudio.ImageCatalog (>= 15.8.27731) but Microsoft.VisualStudio.ImageCatalog 15.8.27731 was not found. An approximate best
match of Microsoft.VisualStudio.ImageCatalog 15.8.27828 was resolved.
  C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj : warning NU1603: Microsoft.CodeAnalysis.EditorFeatures 2.9.0-beta8-63208-01 depends on Microsoft.VisualStudio.Language.Intellisense (>= 15.8.238-preview) but Microsoft.VisualStudio.Language.Intellisense 15.8.238-preview
was not found. An approximate best match of Microsoft.VisualStudio.Language.Intellisense 15.8.525 was resolved.
  C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj : warning NU1603: Microsoft.CodeAnalysis.EditorFeatures 2.9.0-beta8-63208-01 depends on Microsoft.VisualStudio.Language.StandardClassification (>= 15.8.238-preview) but Microsoft.VisualStudio.Language.StandardClassificati
on 15.8.238-preview was not found. An approximate best match of Microsoft.VisualStudio.Language.StandardClassification 15.8.525 was resolved.
  C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj : warning NU1603: Microsoft.VisualStudio.Language 15.8.525 depends on StreamJsonRpc (>= 1.3.6) but StreamJsonRpc 1.3.6 was not found. An approximate best match of StreamJsonRpc 1.3.23 was resolved.

    14 Warning(s)
    0 Error(s)**
```

Looks like bad references to:

* System.Collections.Immutable
* Microsoft.VisualStudio.Threading
* Microsoft.VisualStudio.Language.IntelliSense
* NavigateToSearchService gives a deprecation warning

### PR DESCRIPTION
**Pull request by rojepp**
Partly fixes #5572

### CODE REVIEW

**Comment by cartermp** [comment]
Changing title due to CI not running

**Comment by rojepp** [comment]
@cartermp Are these CI failures caused by this PR? Looks like no PRs are building properly. 
btw, did I do something to avoid kicking off CI?

**Comment by cartermp** [comment]
@rojepp, nope, we have a CI issue that @KevinRansom was looking at. This PR (and others) won't be merged until #5564 is merged.

As for not kicking off CI, there was actually an endpoint migration this week that we missed for a day. Just had to update the webhook.

**Comment by rojepp** [comment]
@dsyme fixed this in https://github.com/Microsoft/visualfsharp/pull/5584, closing.

**Pull request closed without merging**
