### PR TITLE
First try locally before recursive step

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@forki what is the background for this change and do you know where this is used / what this code is for?

This looks good.

**Comment by forki** [comment]
@smoothdeveloper I'm reading the code and wondered. This is more for discussion ;-)

**Comment by dsyme** [comment]
@forki Is that function used anywhere?

**Comment by forki** [comment]
lol good catch @dsyme - I removed the thing

**Comment by KevinRansom** [comment]
Nice ... thanks for this mate

Kevin

**Pull request merged**
