### PR TITLE
Crop extension

### PR DESCRIPTION
**Pull request by KevinRansom**
Update for cropextension to reduce the number of times it calls validate path character.

Also contains revert nunit.consolerunner to 3.0.0

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by forki** [comment]
I doesn't look correct - something seems wrong with your git repo. I assume you should rebase this on origin/master and hard rest your master  on origin/master

**Comment by dsyme** [comment]
@forki - see #1631

**Comment by forki** [comment]
Yes but without proper rebase and hard resets they will always come back...

**Comment by dsyme** [comment]
@forki Yes, though the use of squash-and-merge means that they don't enter the commit history (though they keep appearing in the squash-merge messages unless they get edited out)

**Comment by forki** [comment]
True squashing is a way to keep these hashes out. But I vote to require everyone to fix up their history in order to have proper diff here on github. It's just super hard to review with broken history.

**Comment by dsyme** [comment]
approved (with squash :) )

**Pull request merged**
