### PR TITLE
Update Roslyn References to 2.0 (Dev15)

### PR DESCRIPTION
**Pull request by otawfik-ms**

### CODE REVIEW

**Comment by otawfik-ms** [comment]
@dotnet-bot test ci please

**Comment by forki** [comment]
I guess this one needs to be rebased. Also can you please describe a bit what you are doing here?
Otherwise it's hard to review.

**Comment by otawfik-ms** [comment]
@forki I'm doing some work to update roslyn branch to have master changes, and merge the recent coreclr changes in. I'll be doing some rebasing and fixing any CI test/build failures. Will remove the [WIP] when it is done.

**Comment by otawfik-ms** [comment]
@Microsoft/fsharp-compiler This PR is now ready to merge. TODO:

- Get VSIX project to be debug-able in Dev15
- Start implementing language services.

Jenkins build is failing because this branch's Jenkins configuration is out of date. It should be green with the next merge.

**Pull request merged**
