### PR TITLE
Fixed Alt+Enter for standalone F# script files before F# interactive is open

### PR DESCRIPTION
**Pull request by TIHan**
This converts the FSharpEditorFactory and TextViewCreationListener to F#. They are also moved to the FSharp.Editor project. The editor factory is registered when the FSharpPackage loads.

The reason for doing this is that, for one, they don't belong in the legacy project system. Also, the editor factory would only get instantiated until the legacy project system loads first; which has been changed to whenever the FSharpPackage loads, the FSharpEditorFactory get loaded.

We also moved the attributes that were on FSharpEditorFactory to the FSharpPackage.

This is intended to fix the bug [here](https://github.com/Microsoft/visualfsharp/issues/3092).

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
Is it ok to be unsuspicious of all the `|> ignore`? it seems those API can return something else than VS_OK, is there a point in checking the return values?

**Comment by TIHan** [comment]
I was thinking that this morning. There are places where we don't do this in our repo, e.g. fsiSessionToolWindow.fs; perhaps we should stop and apply some asserts/checks.

**Comment by TIHan** [comment]
We may have to keep our ```|> ignore``` because we don't know the intention of the original code that was ignoring the result.

**Comment by TIHan** [comment]
Accidentally closed this.

**Pull request merged**
