### PR TITLE
Propose Uppercase for FS0053

### PR DESCRIPTION
**Pull request by forki**
image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I'm pretty sure you should start an Inline Rename session for this fix, because without it you do not change all the DU case occurences:

image

See
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/RenameTracking/RenameTrackingTaggerProvider.cs,39

However, this code is not from a Code Fix, maybe we should find all symbol references on our own and "change" all documents where it's used to get nice multi-file preview. Or maybe not. Could you look for a Code Fix that changes multiple documents in the Roslyn sources? 

Looks like we should use this overload, which expect us to return the whole new `Solution`:

image

**Comment by forki** [comment]
Mhm not sure if can do this right now. If you think you see a solution then could you please try it? You have much more experience with the VFPT features.

**Comment by vasily-kirichenko** [comment]
@forki I've send a PR, looks like this:

**Comment by forki** [comment]
That's awesome

**Comment by forki** [comment]
As discussed in different channel: @vasily-kirichenko will extract the "find references" logic soon since we believe this will be used in many code fixes.

**Comment by forki** [comment]
ready for review.

**Comment by forki** [comment]
thanks @vasily-kirichenko for refactoring. @KevinRansom this is ready

**Comment by forki** [comment]
appveyor fail is unrelated

**Pull request merged**
