### PR TITLE
skip more coreclr steps on plain build.cmd

### PR DESCRIPTION
**Pull request by dsyme**
This skips some test preparation steps on a plain ``build.cmd``, is an extension of #1047

### CODE REVIEW

**Comment by KevinRansom** [comment]
Yes, LGTM

**Comment by dsyme** [comment]
@KevinRansom The jenkins build is failing, I'm not sure why.  The proto compile is not being run as a CoreCLR  compiler in the jenkins build, is it?

**Comment by KevinRansom** [comment]
Omar is the Jenkins Guru.

**Comment by otawfik-ms** [comment]
According to the latest build I can see:
http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/master/job/release_windows_nt/23/console

`08:35:29 d:\j\workspace\release_windo---886c0951\lkg\FSharp-14.0.23413.0\bin\Microsoft.FSharp.Targets(155,9): error MSB6004: The specified task executable location "..\..\..\lkg\bin\Debug\dnxcore50\win7-x64\publish\fsc.exe" is invalid. [d:\j\workspace\release_windo---886c0951\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj]
`

@KevinRansom this something the LKG compiler is building?

**Pull request merged**
