### PR TITLE
Make jenkins green

### PR DESCRIPTION
**Pull request by enricosada**
ref #859

### CODE REVIEW

**Comment by enricosada** [comment]
@otawfik-ms i cannot change project names, but this one should build only, no tests

**Comment by oamsath** [comment]
How about doing one build definition then (since all three are doing the same thing, just build)?
If this succeeds, I'll look into the test failures on Monday and add them to the jenkins_build script.

**Comment by enricosada** [comment]
done like that, see https://github.com/Microsoft/visualfsharp/issues/859#issuecomment-170139948

**Comment by otawfik-ms** [comment]
We can regenerate that with a command.
Can you please restrict the jobs back to Windows for now?
I think we should bring up all the tests (including FsharpQA) and make them report to Jenkins first.

**Comment by enricosada** [comment]
@otawfik-ms the build is windows only, the other os are commented out. 

```groovy
def osList = ['Windows_NT'] //'Ubuntu', 'OSX', 'CentOS7.1'
```

I think we need xplat it soon (pls coreclr osx buld :smile: ),.
Like dotnet/cli groovy script, we need to add the new os to `osList` and add a `jenkins-build.sh` script to repo.

i really like have tests, but can we pls make a green build ( `build_only` ) in master, and fix test in another pr? 
you can now try tests changing the `jenkins-build.bat` **inside a new pr**, no need to change jenkins job defs or leave the build red.
Or change `jenkins-build.cmd` to run the test suites and leave build red meanwhile, your call.

**Comment by otawfik-ms** [comment]
@dotnet-bot test ci please

**Comment by otawfik-ms** [comment]
Running the job definition build now.

**Pull request merged**
