### PR TITLE
remove ngen dependencies

### PR DESCRIPTION
**Pull request by brettfo**

### CODE REVIEW

**Comment by KevinRansom** [comment]
@brettfo will this slow down builds using the proto compiler?

**Comment by brettfo** [comment]
Possibly on the first launch (the hot path should be jitted for subsequent invocations), but only if you were running as admin, which I don't think anybody actually is.

**Comment by KevinRansom** [comment]
@brettfo 

I think most of us do open administrator command windows.  The Jit would have to compile virtually all of the FSharp.Compiler.Private.dll and FSharp.Core.dll every single dll or .exe it builds.  It comes close to doubling the build time.

When we move over to the coreclr proto compiler if we can figure out crossgen, we can probably do this, otherwise it's painful.

Kevin

**Comment by KevinRansom** [comment]
Scary error message:
````
1) Error : FSharp-Tests-Core+CoreTests.load-script
System.ComponentModel.Win32Exception : Operation did not complete successfully because the file contains a virus or potentially unwanted software
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Scripting.Process.exec(CmdArguments cmdArgs, String workDir, FSharpMap`2 envs, String path, String arguments) in D:\j\w\release_ci_pa---866fd2c3\src\scripts\scriptlib.fsx:line 136
   at TestFramework.Command.exec@420-20.Invoke(CmdArguments cmdArgs) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 421
   at TestFramework.Command.outF@393-3T.Invoke(FSharpFunc`2 fCont, CmdArguments cmdArgs) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 408
   at TestFramework.execAppendIgnoreExitCode@430.Invoke(String args) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 430
   at TestFramework.execAppendIgnoreExitCode@430-2.Invoke(String x) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 430
   at FSharp-Tests-Core.CoreTests.load-script() in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\tests.fs:line 871
````

**Comment by brettfo** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please // a single test humorously [failed](https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part2_windows_nt_prtest/4710/) with `Operation did not complete successfully because the file contains a virus or potentially unwanted software`, possibly due to conflicting AV on the Jenkins image; test passes locally.

**Comment by brettfo** [comment]
On a related note I'm timing `.\build.cmd ci_part1` now, both with and without `ngen` (as admin) to see what the real difference is.

**Comment by dsyme** [comment]
I would like want the compiler NGEN'd on my normal compiler development loop.  (Obviously it has to be ngen'd on Visual Studio install as well but I assume that's not changing)

TBH I'd also expect it NGEN'd on our CI automated test runs  - I haven't checked if that's the case though.  There is always a thin chance of an NGEN bug being exposed by our testing and if so we would like to catch it as early as possible

**Comment by brettfo** [comment]
`ngen.exe` gives a pretty big boost to local development so I'll close this PR.  I've also merged #4002 which switches back to delay signing because those can actually be ngen'ed.

**Pull request closed without merging**
