### PR TITLE
Make generic parameter instantiations available in language service

### PR DESCRIPTION
**Pull request by dsyme**
This is work in progress to support https://github.com/Microsoft/visualfsharp/issues/2905.  It doesn't actually implement the feature but collects and propagates the necessary information at least for generic method calls.

This work required extensive plumbing of information.   I'm submitting it as a PR to get comprehensive CI checking. This change shouldn't in theory cause any tests to fail, but the changes needed are enough that early CI checking of that is useful.

### CODE REVIEW

**Comment by dsyme** [comment]
The formatting is not where we want it, but this shows that at least in some cases the type information is now being propagated to the IDE - see the "T: int" in the quickinfo 

image

I'm wondering if we should commit the core changes to the compiler here, without the actual propagation to the IDE, after adding some FCS testing.  Then do the IDE changes separately.

**Comment by dsyme** [comment]
I pushed through the visuals for this, see below.  

The feature is only currently enabled for type parameters for generic methods (F# and C#/IL).  Not for type parameters for generic classes, nor F# functions, nor F# operators,

image

This is getting much closer to being ready.

**Comment by dsyme** [comment]
I've added tests.  Once this is green I recommend we integrate this to get it in the bank.  We can later address the cases of F# generic functions and F# operators

(Note that one of the most important cases here is hovering over generic symbols "+" and seeing the inferred input and return types.  I also think this feature can make a major difference to the usability of type-class/implicit-like mechanisms and other proof inference, to show the inferred additional arguments)

**Comment by vasily-kirichenko** [comment]
@dsyme what about inlining concrete types? Look:

C# Rider

image

C# VS

image

C# Code

image

**Comment by dsyme** [comment]
@vasily-kirichenko It's possible.  See mock-up [here](https://github.com/Microsoft/visualfsharp/issues/2905#issuecomment-296489738) which I was really following. 

As mentioned in the discussion, we also already inline for class type parameters when looking at method signatures. Is your suggestion to always inline?  The long signatures feel very problematic for F# - massive tuple types, anonymous types etc.  I can easily imagine types a page long.

Or is the suggestion something like "inline ground types" or "inline types whose textual display is < 10 characters" or ...? Technically we could do any of these relatively easily.  It's just a matter of deciding what we want.

**Comment by dsyme** [comment]
@KevinRansom @brettfo  This is orthogonal, and we could isolate it out, but please take a look at the project file change here: https://github.com/Microsoft/visualfsharp/pull/2929/files#diff-2e36256ae69634c7be82544e75e60231R328 that is in this PR

Basically we have a strange situation where the build of "ProjectSystem.fsproj" seems to convince MSBuild that it needs to CopyLocal System.Colleections.Immutable 1.2.1 from the MSBuild15 directory to the output bin directory.  All projects which transitively reference this project also seem to force the same CopyLocal behaviour.  This meant we ended up with the wrong System.Collections.Immutable in the "bin" directory (1.2.1 not 1.2.0) once you've done a "build vs".

The setup already forces the version included in the VSIX to be 1.2.0, so it seems OK to add these references to force the build to copy that version across and no other.

**Comment by dsyme** [comment]
@vasily-kirichenko BTW most of the work in this PR is orthogonal to how we decide to present the information - it's really about propagating the explicit instantiations up the the FCS layer.  So I think we could bank this and then iterate.  I actually think a heuristic is best - there are definitely some F# cases where full expansion would be really bad.

**Comment by dsyme** [comment]
Note that one side effect of **not** substituting is that we show type variable names, even for inferred type  parameters.  This may encourage users to use "better" names for these., e.g. by changing

    let f x y = (x,y)

to 

    let f<'Left,'Right> (x: 'Left, y: 'Right) = (x,y)

However this is quite intrusive and doesn't really either fit F# methodology nor make the code actually better.  It's case where showing information can lead programmers to change their code in ways that may not be what we want.

**Comment by vasily-kirichenko** [comment]
@dsyme I agree, the current implementation is OK for now. I don't think that automatic switching between inlined concrete types and the way it's in this PR now is a great idea because it'd introduce inconsistency - the used would expect one of the ways to always work.

**Comment by vasily-kirichenko** [comment]
@dsyme It seems not working for me:

image

**Comment by dsyme** [comment]
@vasily-kirichenko See this:

> The feature is ... not enabled for type parameters for generic classes, nor F# functions, nor F# operators,

I will do F# functions/operators next - those are essential and very valuable

**Comment by dsyme** [comment]
@vasily-kirichenko Here is the screengif for F# generic values and operators.  I'll add testing tomorrow.

I'm still very unconvinced that we always want to show an explicit instantiation.  e.g. for operators like ``+`` there is just toooooo much information for beginners.  Perhaps a rule like "always substitute type variables that are only used once in the signature".  

cap gif

**Comment by dsyme** [comment]
Things to do, or things I just noticed. Will fix tomorrow

* [ ] Testing
* [ ] The "Full name" information shown for F# values is now misaligned. 
* [ ] Separate issue: Scripts are not showing XML documentation for entries from FSharp.Core
* [ ] Separate issue: The code fix for the unused value ``this`` in ``member this.X = 1`` replaces with a single underscore ``_`` which is not legal F#.  Suggesting to replace by double underscore would be correct.

**Comment by dsyme** [comment]
This is ready to go in (once green - there are a few glitches in the unit tests to iron out)

**Comment by vasily-kirichenko** [comment]
I encounter https://github.com/Microsoft/visualfsharp/issues/2942 on this PR.

**Comment by vasily-kirichenko** [comment]
Also, no colors in full name:

image

**Comment by vasily-kirichenko** [comment]
I agree that single type parameter should be inlined, for example the following tooltip would benefit from inlining a lot:

image

**Comment by saul** [comment]
I'm not convinced by substituting them inline. How would I know if the method was generic or whether it'd been constrained? I think that's a step too far. 

Also @dsyme this looks fantastic! Can't wait to try this out. I have two very minor nit picks though - can we change "Generic Parameters" to "Generic parameters" to be consistent with "Full name". Also put a space after the type name (before the colon) to be consistent with val foo : type?

**Comment by dsyme** [comment]
> I'm not convinced by substituting them inline. 


> How would I know if the method was generic or whether it'd been constrained? 

For "+" it says that it's overloaded in the docs.   Also any generic use of a method shows the generic signature, e.g. the method list or declaration list.

I think it's very important to think of beginners here.  A 10 year old should be able to use F# ``+`` and see ``int -> int -> int`` and ``float -> float -> float`` as quickinfo a callsite without learning about constrained generics.  (c.f. There are reasons why F# doesn't show full type signatures all the time, it abbreviates some constraints)

> can we change "Generic Parameters" to "Generic parameters" to be consistent with "Full name". 

Done, thanks

> Also put a space after the type name (before the colon) to be consistent with val foo : type?

I use ``val foo: type`` and generally recommend that style.  However this has made me wonder if ``'T = int`` might be better.

**Comment by vasily-kirichenko** [comment]
Yeah, `'T = int` looks better to me. It's more consistent with, say, property initializing syntax in constructors where C# uses semicolons, but F# uses the equal sign.

**Comment by saul** [comment]
I'm not convinced by `'T = int`, it looks strange considering types are always after a colon in F#. Maybe `'T is int`, in the same vein as C#?

**Comment by majocha** [comment]
Colon is consistent with type constraints syntax. OTOH equals suggests a type alias which also fits here. Hard to choose.

**Comment by dsyme** [comment]
``'T is int`` would be fine by me.  Human is better for quickinfo

**Comment by dsyme** [comment]
@KevinRansom This is now ready to review and merge

**Comment by vasily-kirichenko** [comment]
Maybe inline types if they are explicitly shown in code at least?

image

**Comment by vasily-kirichenko** [comment]
@dsyme I found a bug:

image

`'Collection` type argument does not appear anywhere in signature, but is listed in `Generic parameters:` section.

**Comment by KevinRansom** [comment]
@dsyme CAN YOU RESOLVE CONFLICTS, AND DO YOU INTEND FIXING @vasily-kirichenko 's bug?

Thanks

Kevin

**Comment by isaacabraham** [comment]
My two cents on the presentation of this...

If we stick with the "generic parameters" section, I would prefer (as @saul originally suggested) having `'T : concrete` (i.e. space before and after the colon).

However, my preference would be to inline the arguments in the top-level type signature wherever possible to avoid people still having to do a mental "find and replace" by looking at the generic parameters section and mapping that to the type signature. Understand the concern regarding "huge signatures" which become unreadable - putting ellipses after n characters could help e.g. `seq<string * string * ...>`. The alternative would be to leave them in there fully - the user is free to make a type alias to make it easier to read (this could actually be a good signal to the user that a type alias may be useful).

Having said that, there *are* times when you might want to retain the 'T / 'U style - particularly if both of them resolve to the same concrete type.

**Comment by vasily-kirichenko** [comment]
@isaacabraham If we formatted signatures as Xamarin does (giving each parameter its own line), we would always inline types without fear.

**Comment by saul** [comment]
@isaacabraham absolutely - I find seeing the generic arguments really useful. In fact I usually use it to make sure that the compiler is keeping code generic instead of casting them down to obj sometimes. If we do inline them I think we need a way to denote that they're type parameters and not any old concrete type.

**Comment by 0x53A** [comment]
I prefer them explicit, but mostly don't care.

One area which should always be explicit, IMO, is anonymous records.
That's the one case where C# is also explicit.

**Comment by dsyme** [comment]
> @dsyme can you resolve the conflicts and do you intend fixing @vasily-kirichenko 's bug?

Conflicts resolved.  I think we should pull this and then refine. It is usable as-is - though may indeed show implied type variables.

@vasily-kirichenko Interesting find.  For the case of ``Seq.collect`` the ``Collection`` type variable is in the signature, see https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/seq.fsi#L162.  The type printing code has decided to elide it because it could well as have been a ``#`` type (it is only used in one location in the signature and is constrained by only one type).  But there will be other cases where ``#`` types are used that the implied type variable is shown.

**Comment by isaacabraham** [comment]
@saul wouldn't that be signified by angle-brackets e.g. `Seq<int * string>`?

**Pull request merged**
