### PR TITLE
AllMethInfosOfTypeInScope with shortcut of extension methods

### PR DESCRIPTION
**Pull request by forki**
When we check for method or property Infos we often don't need all Infos but only the first one. This pr avoids looking though all inheritance layers all the time.

### CODE REVIEW

**Comment by dsyme** [comment]
@forki The code looks fine - but what's the reason for the change?  e.g. write the description for the PR :) thanks!

**Comment by forki** [comment]
Fone

**Comment by dsyme** [comment]
@forki Done with fone? :)

**Comment by forki** [comment]
Fatfingered lol

**Comment by cartermp** [comment]
@forki looks like there are conflicts. Is this PR still good? Looks like it is on the surface at least

**Comment by forki** [comment]
Will try to rebase later today.

Am Fr., 8. Feb. 2019, 18:29 hat Phillip Carter <notifications@github.com>
geschrieben:

**Comment by forki** [comment]
rebased. let's see if it becomes green

**Comment by forki** [comment]
@KevinRansom it looks like the build succeeded but some error during fcs publishing happened. ist this related?

**Comment by cartermp** [comment]
The FCS CI has some flakiness to it. As you've found, just close/re-open ought to solve it.

**Comment by cartermp** [comment]
@dsyme you said the code looks fine, does that count as a sign-off?

**Comment by forki** [comment]
would be good to double check the AtMostOnce calls. but I think I was very conservative about this here

**Comment by cartermp** [comment]
Ugh I have half a mind to just delete that flaky test

**Comment by dsyme** [comment]
Why is NameResolution.fsi showing as 100% change in this PR?

**Comment by forki** [comment]
I think my VS changed encoding. But I checked and now it's same as other
files around it

Am Di., 19. Feb. 2019, 01:45 hat Don Syme <notifications@github.com>
geschrieben:

**Comment by forki** [comment]
rebased again.

**Comment by forki** [comment]
and rebased yet another time.
@KevinRansom I'd appreciate if we can either close it or get it in. Rebase/merges are a bit annoying right now with all that cleanup happening in those files.

**Comment by forki** [comment]
and another time..

**Comment by KevinRansom** [comment]
@forki,

thank you for this.

**Pull request merged**
