### PR TITLE
Fix 159

### LINKED ISSUE #159: LanguagePrimitives error strings are initialized in default culture before usage in different culture
Ref #141 

Some localized error strings in [prim-types.fs](https://github.com/microsoft/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core/prim-types.fs#L660-L669) are declared as module values, which causes them to be statically initialized long before they might be used. This means they might be initialized in a different culture than when they are actually used, which is not desirable.

Fix is to refactor these to be evaluated on-demand.

``` fsharp
    try
        Seq.min []
    with e -> 
        printfn "%A" e //use default currentUICulture of process

    // change culture now
    System.Threading.Thread.CurrentThread.CurrentUICulture <- new CultureInfo("it-IT")

    try
        Seq.min []
    with e -> 
        printfn "%A" e // e message is wrong, because is not of 'it-IT' culture
```

### LINKED ISSUE #486: F# Interactive v14 backward incompatibility: Error FS0193 when calling inlined Array.init
Hi. I have Visual Studio Community 2013 Update 4 and 2015 RC on my system. While I was experimenting with F# 4.0, I encountered a problem with the new F# Interactive (v14.0.22810.0).

I did my best to isolate the problem into a minimal example. Here are the steps to reproduce:

 1) Compile an F# library with the code

```fsharp
namespace Library1

module Test =
    let inline init1 n f = Array.init n f
    let init2 n f = Array.init n f
```

targeting FSharp.Core 4.3.1.0.

2) Have a script file where you call `Test.init1`

```fsharp
#r "./bin/Debug/Library1.dll"
open Library1

let a = Test.init1 4 (fun _ -> 4.)
```

and run it within F# Interactive 14.0.22810.0.

You get:
```fsharp
error FS0193: The module/namespace 'ErrorStrings' from compilation unit 'FSharp.Core' did not contain the val '{MemberParentMangledName = null;
 MemberIsOverride = false;
 LogicalName = "InputMustBeNonNegativeString";
 TotalArgCount = 0;}'
```

whereas if you run it with F# Interactive 12.0.30815.0 it runs fine:

```fsharp
val a : float [] = [|4.0; 4.0; 4.0; 4.0|]
```

Here is some extra information:

1) If you call `Test.init2`, which has the same type with `Test.init1`, with F# Interactive 14.0.22810.0, there is no error and it runs fine. So, there is something to do with `inline`.

2) When you call `Test.init1` from an F# console application

```fsharp
open Library1

[<EntryPoint>]
let main argv = 

    let a = Test.init1 4 (fun _ -> 4.)
    printfn "%A" a
```

there is no error. So, the error is about F# Interactive.

3) When you compile the library code targeting FSharp.Core version 4.4.0.0, there is no error with F# Interactive 14.0.22810.0. So, this is a backward compatibility problem of the new F# Interactive with existing libraries compiled for FSharp.Core 4.3.1.0, I think.

### PR DESCRIPTION
**Pull request by enricosada**
fix #159 , see also #486 

see discussion/review on pr #488 , i created a new pr because i cannot change the target branch of pr 

I updated the code a bit, using a public function 

```fsharp
val SharedResources.GetString: string -> string
```

instead of return a `System.Resources.ResourceManager`, so only a `string` is added to surface area

REMARKS

This fix the bug, but the new compiled assembly require the new version of FSharp.Core (because use the new SharedResources.GetString function in the inlined code).
An assembly compiled with old FSharp.Core continue to work with new FSharp.Core

that mean this code need to wait for F# 4.1 or 5? dunno

### CODE REVIEW

**Comment by KevinRansom** [comment]
Did we give any thought to just reverting the in-lines that cause this behavior?

**Comment by enricosada** [comment]
Is a bug, @latkin reverted my fix for multitargeting compatibility ( old code compiled was not runnjng with new fsharp.core )
This pr fix the bug, but now compiled code require the new fsharp.core, you can not compile with new fsharp.core and use an old one. 
Is a binary breaking change, required to fix the bug. 
Maybe better wait next major version? @dsyme ?

**Comment by KevinRansom** [comment]
We have no plans to revise the assembly version at this time.  I'm pretty sure even then we wouldn't want to add a public API to get resources so that inline will work.  Although it is fair to say that it is a workable solution.  I think the real fix here should be when the compiler is inlining a public API detect the use of non-visible API's and issue warning and disable the inline - The developer then has the opportunity to rewrite the inlined function, choose a different one or disable the warning.

Does that make sense?

**Comment by enricosada** [comment]
No, we cannot issue a warning, because is not a developer vs compiler problem, the inlined functions are inside `FSharp.Core` assembly, like `Array.last` 

I referenced the wrong issue number, you can see the bug in #159

Recap:
Resource strings are already exposed by `FSharp.Core.ErrorStrings` module and used by inlined function like `Array.last`, but are static fields, cannot change values if UICulture change (the bug).
I tried to use properties instead of fields with 52a7252, but broke binary compatiblity (previous compiled code expected fields but found properties)
My fix was rolled back and the bug is open.
We cannot fix it without breaking compatibility ( code compiled with Fsharp.Core 4.1 require 4.1, cannot use 4.0).

I cleaned up the code, rebased on latest master and now works but break compatibility. 

Nothing we can do, we need a *function* to get string resources, and there is none in old api. New inlined code will use this new api, so break compatibility.

So add a tag `major-version` or `breaking-api-change` and let's wait the next major version to fix this bug.

**Comment by dsyme** [comment]
Yes this should wait for the next version update to FSharp.Core (whenever that is)

> . I think the real fix here should be when the compiler is inlining a public API detect the use of non-visible API's and issue warning and disable the inline 

Just to clarify that the compiler does do this already

**Comment by KevinRansom** [comment]
These are the api's brok

**Comment by dsyme** [comment]
@Kevin - Yes, inlining will make an absolutely enormous difference on min, minBy, average, averageBy, max and maxBy, because the numeric type is resolved statically.  This is why we chose (deliberately) to expose the error strings - we were aware of what we were doing here in F# 2.0.

**Comment by KevinRansom** [comment]
I am skeptical about the use of the word enormous.  These apis all operate of collections, and as such the cost of iterating the collection will likely swallow the benefit of inlining.  But as you say, it's done now.

**Comment by dsyme** [comment]
The perf difference between generic versions is 50x. For generic code, the computation is dominated by the static resolution of the numeric comparison operation.  

See https://gist.github.com/dsyme/8a0d3edfb31217dfa927

You can always recover the perf by limiting the operation to specific numeric types (e.g. LINQ limits to integers, decimal, float etc.)

**Pull request closed without merging**
