### PR TITLE
[CompilerPerf] [WIP] trial: suppress needless uses of callvirt 

### PR DESCRIPTION
**Pull request by dsyme**
PR to reassess the perf impact of using ``call`` instead of ``callvirt`` in some situations.  See context at https://github.com/Microsoft/visualfsharp/issues/2844 and https://github.com/Microsoft/visualfsharp/issues/468

### CODE REVIEW

**Comment by dsyme** [comment]
Well, turning on this flag doesn't seem to hurt performance, see https://github.com/Microsoft/visualfsharp/blob/master/tests/scripts/compiler-perf-results.txt#L76

```
startup-to-parseonly parseonly-to-check   check-to-nooptimize  check-to-optimize    nooptimize-to-debug
10.75                28.57                42.86                56.34                52.50
```

v. some recent times on master:

```
10.12                30.98                45.96                61.91                51.16               
10.31                30.51                46.54                62.74                51.05               
```

That may even indicate an improvement, e.g. three of the phases seem to improve  - but note that the times are pretty flaky - regular +/- 10% - so each are within the margin of error.  I'll do more test runs.

**Comment by KevinRansom** [comment]
@dsyme 
What do you plan to do with this?

**Comment by dsyme** [comment]
@KevinRansom  I'm not sure yet.   Let's leave it open and I'll get more perf data (the compiler perf scripts analyze the master branch plus any open PRs with ``[CompilerPerf]`` in the title)

**Comment by KevinRansom** [comment]
@dsyme ... do you want to revisit this PR?

**Comment by KevinRansom** [comment]
Actually looks like nothing much left of it.

**Pull request closed without merging**
