### PR TITLE
Add Map.count

### PR DESCRIPTION
**Pull request by robertpi**
As requested by https://fslang.uservoice.com/forums/245727-f-language/suggestions/12880398-add-map-count

### CODE REVIEW

**Comment by KevinRansom** [comment]
@robertpi  you have run in to the Surface area verification test, you added a new API to fsharp.core.dll and so you need to update the list of APIs for the Surface area tests : FSharp.Core.Unittests.SurfaceArea.SurfaceAreaTest.VerifyArea

Just add this line:0

````
Microsoft.FSharp.Collections.MapModule: Microsoft.FSharp.Collections.MapModule: Int32 Count[TKey,T](Microsoft.FSharp.Collections.FSharpMap`2[TKey,T])
````
between these two:
````
Microsoft.FSharp.Collections.MapModule: Boolean IsEmpty[TKey,T](Microsoft.FSharp.Collections.FSharpMap`2[TKey,T])
Microsoft.FSharp.Collections.MapModule: Int32 GetHashCode()

````

In:
````
   src\fsharp\FSharp.Core.Unittests\SurfaceArea.net40.fs
   src\fsharp\FSharp.Core.Unittests\SurfaceArea.portable7.fs
   src\fsharp\FSharp.Core.Unittests\SurfaceArea.portable47.fs
   src\fsharp\FSharp.Core.Unittests\SurfaceArea.portable78.fs
   src\fsharp\FSharp.Core.Unittests\SurfaceArea.portable259.fs
````
Thanks

Kevin

**Comment by dsyme** [comment]
See RFC here: https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1010-add-map-count.md

Robert - please the take time to fill in the RFC and if necessary have a discussion on this.  For example, people may want to discuss whether other functions should be added at the same time in an overall update to the Map module.

**Comment by KevinRansom** [comment]
@dsyme @robertpi  so ... this PR looks good to me, let me know if you want to do more work on it.

**Comment by KevinRansom** [comment]
@robertpi @dsyme Please provide an RFC to allow us to examine the context for this PR ... the code looks good, it looks like something we would want to take.  But we want to examine how it fits.

Don has provided a template here:
https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1010-add-map-count.md

**Comment by dsyme** [comment]
Just to add - I think we're petty much going to require RFCs for API and language additions from now on.  RFCs allow us to:

* track what changes have happened, when, why and with exact links to the PRs and history
* discuss the changes from a design point-of-view.  For example, is the design change complete? consistent? 
* gives a future reference point that people can find to understand the change.

**Comment by robertpi** [comment]
Thanks and apologies, I thought I filled in the in RFC, but can find no
evidence of this.
 
Thanks,
Rob
 
 
On Mon, Apr 18, 2016, at 09:33 PM, Kevin Ransom (msft) wrote:
> Merged #1007[1].
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[2]
>
 

Links:

  1. https://github.com/Microsoft/visualfsharp/pull/1007
  2. https://github.com/Microsoft/visualfsharp/pull/1007#event-631842801

**Pull request merged**
