### PR TITLE
[EXPERIMENT|DONTMERGE] Expand NameResolution to properties and methods without knowing the type

### PR DESCRIPTION
**Pull request by forki**
This is an experiment to expand name resolution to cases where we don't have type info yet.

image

image

this is based on the idea to expand the trick that makes the following resolution possible today:

image

### CODE REVIEW

**Comment by isaacabraham** [comment]
Without any thoughts to the difficulty in working around overload resolution and so on - this would be a super feature if it could be added - bringing type inference in for things like the BCL would be awesome. This could eventually be supplemented by tooling in an IDE to open a namespace for the appropriate type based on the member.

**Comment by drvink** [comment]
In discussion with @forki he noted that a similar hack is already used for record fields: the most recent one that came into scope is chosen; the difference here (as currently implemented) is that the first candidate from the current name resolution environment is taken. I feel like this could generate surprising (or even dangerous) results, and that the current approach of requiring the user to supply an annotation was probably chosen with this in mind (let alone the inherent problem of inferring types in the presence of nominal subtyping). That said, I heavily sympathize with how much of a nuisance it is to have to annotate in these cases--I have written easily a few hundred `inline` free function wrappers by now around parts of the BCL and other object-disoriented libraries, in addition to what I use from @gusty's [FSharpPlus](https://github.com/gusty/FSharpPlus), which brings me to something I have been exploring since my earliest dealings with F#.

If we restrict this to `inline` functions, this takes on new and compelling possibilities: not only do we not risk introducing surprising (or worse) results to ordinary functions, but we can take advantage of some machinery that already exists and try to transform dot expressions into boring member constraints--basically "SRTP for free", similar to how C++ templates work by using a combination of name- and type-directed resolution to collapse/resolve their points of instantiation to a single candidate. Example:

```fsharp
let inline f x = x.y + 1
// becomes
let inline f x = (^a : (member y : _) x) + 1
// and in fact this already works in F# today: the result is
val inline f : x : ^a -> int when ^a : (member get_y : ^a -> int)
```

The search here is trivial: we look for something that would typecheck in the context of `val (+) : _ * int -> int`, and we know to only look for `member` properties, because `static member` properties cannot be referred to via dot syntax. (Remember that `member __.y = n` and `member val y = n with get` are equivalent, and that only `member __.y z = n`, `member __.y() = n`, etc. are actual "methods".)

In C++, template resolution is very complicated: templates themselves can be overloaded, "specialized" (effectively a form of pattern matching on template parameters), recursively expanded, nested in other templates, take parameters variadically, be passed as parameters themselves (achieving a poor man's encoding of higher-kinded types), and more--type-level integers, associated types, uncomfortable interaction with pre-template-era C++ type system features are but only a few of the things we do not need to contend with in SRTP, which is a mixed blessing in terms of expressive power, but is significantly easier to implement and for users to understand and less of an antagonist to fast compile times.

In particular, the fact that SRTP constraints are *directly stated* rather than arising as an emergent property of the complicated rules of template resolution dovetails nicely with the proposal for type classes in F#; since we _started_ with ML-style global type inference and the notion of specifying constraints explicitly (with inference filling in the blanks wherever possible), we do not have the problem C++ currently has: trying to construct--in reverse!--a procedure for type inference for a language that lacked it as well as trying to codify a notion of being able to specify explicit constraints directly (for the purposes of better compilation times, better user diagnostics, and less "magic" to understand about how templates work). The contrast in the amount of code and degree of wizardry needed to implement [a simple type-safe polymorphic printer in C++ vs. F#](https://gist.github.com/drvink/391116136757abdacebe) is staggering. I would go so far as to say that the fancy template things SRTP currently lacks would be feasible to add in an ergonomic way as a result compared to how they exist in C++, though I do not necessarily propose this should be done.

@dsyme, others, thoughts?

For your amusement, here is a (admittedly corner case) situation in which a peculiarity of F#--you can alternately pronounce this, every time, for every F# "peculiarity", as "something stupid or unfortunate inherited from .NET"--can *presently* blow up despite these ideas being otherwise sound:

```fsharp
let inline f (x : ^a) = (^a : (member ToString : unit -> string) x)
// which is
val inline f : x: ^a -> string when  ^a : (member ToString :  ^a -> string)

let () = printfn "%s" (f 1)
(*
System.NullReferenceException: Object reference not set to an instance of an object.
   at <StartupCode$FSI_0003>.$FSI_0003.main@()
Stopped due to error
*)
```

This, however, works fine:

```fsharp
let inline f x = (^a : (member ToString : unit -> string) (x :> obj))
(* harmless warning about ^a being solved to obj *)
val inline f : x:'a -> string
```

...and of course, constraints not involving bowels of .NET tend to be far better behaved already:

```fsharp
let inline g x = (^a : (member Hoopty : unit -> string) x)
// which is
val inline g : x : ^a -> string when ^a : (member Hoopty : ^a -> string)

let _ = g 1
(*
  g 1;;
  --^

stdin(16,4): error FS0001: The type 'int' does not support the operator 'Hoopty'
*)
```

**Comment by realvictorprm** [comment]
I would say genius idea. I'm in favour of it :)

**Comment by forki** [comment]
@drvink regarding "last type that came into scope" I think the current approach could be changed to that as well. All I'd need to do is to keep yet another list in the name resolution environment and add a type that comes into scope to the list. Then I'd use that list for searching. Instead of the map that I'm using right now.

**Comment by dsyme** [comment]
@forki Can you add this as a language suggestion please and keep a private branch?  It's not really right for a PR to this repository...

**Comment by forki** [comment]
the problem with this experiment is that I don't know if I want a language suggestion at all ;-)
and private branches don't have CI....

**Comment by dsyme** [comment]
> the problem with this experiment is that I don't know if I want a language suggestion at all ;-) and private branches don't have CI....

Yeah, I know, we should just put a appveyor.yml in the repo so you can turn on appveyor CI for your own forl if you want.

**Comment by forki** [comment]
not the same thing...

**Comment by smoothdeveloper** [comment]
What do you think if instead it was code suggestion to fix the code (add the type in the signature or the expression, the same way we have add open statement) instead of having the compiler accept the code?

**Comment by forki** [comment]
Code suggestions still create Code that you need to maintain. That is not without cost

**Pull request closed without merging**
