### PR TITLE
Replacing short-lived options with ValueOption

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by TIHan** [comment]
I think this is fine. One thing to be aware of is that we start trying to return ValueOption types that hold a big struct, in which case an Option would probably be better; but I doubt there will be a case like that.

**Comment by forki** [comment]
These are all pretty small - and tbh they should actually be treated like
the TryGetValue case and even the struct should be eliminated.

Will Smith <notifications@github.com> schrieb am Di., 2. Okt. 2018, 20:07:

**Comment by forki** [comment]
I mean that's not happening right now, but I think such an optimization
rule can be done.

Steffen Forkmann <sforkmann@gmail.com> schrieb am Di., 2. Okt. 2018, 20:17:

**Comment by KevinRansom** [comment]
@forki,

Thank you for this.

**Pull request merged**
