### PR TITLE
fix paste of multiple files (from another project or windows explorer)

### LINKED ISSUE #104: Using Paste to add files to an F# project causes the order of files in the project and on the UI to get out of sync
Repro:
1.Create a new F# Console Application 
2.Create 3 F# source files (.fs) on disk 
3.Select all three files using windows explorer and paste them on to the F# project in Solution Explorer, note the files are appended to the project in the display. 
4.select program.fs 
5.use alt+down arrow to move it to the bottom of the source file list 
Image 
6.build project and note the build error similar to:

C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe TypeThree.fs TypeTwo.fs Program.fs TypeOne.fs

c:\temp\ConsoleApplication1\ConsoleApplication1\Program.fs(4,1): error FS0222: Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration.
On close inspection of the command line you will see that TypeOne.fs appears after program.fs even though in the ui, TypeOne,fs is at the top and program.fs is at the bottom

qh1w8cd

comments

>ovatsus wrote Jun 28, 2014 at 11:35 AM [x] 
>I get this all the time. I copy paste a file to create a new one, and half the times things won't compile until I unload and load the project again and fix the ordering.

### PR DESCRIPTION
**Pull request by enricosada**
fix #104 

i tried with both paste from project and windows explorer

### CODE REVIEW

**Comment by KevinRansom** [comment]
I will try this out shortly, thank you for doing this.  I did a little chair dance when I saw this come in.  I have no Idea why I am so attached to this bug, and am even more mystified why I have never got around to looking at it.

**Comment by latkin** [comment]
Does this fix the original single-file problem? Seems like the same code is executed as before when there is only 1 file.

**Comment by enricosada** [comment]
@latkin paste only one file work ok in my tests

i dunno why, only the first element was moved to bottom, now the loop move all files

**Comment by latkin** [comment]
Ok I misunderstood the original bug - the problem is only with pasting multiple files.  Sorry for confusion.

I synced your fix and tried in VS, works well.

**Pull request merged**
