### PR TITLE
Highlight reference cells as mutables

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
Finally sort it out, exploring completion on `Tastops.is|` :)

image

### CODE REVIEW

**Comment by dsyme** [comment]
This is OK - refs and mutables are different to other variables.

Can I check where this is going.  Do we do Dictionary and arrays too?  I wouldn't want that on by default....

**Comment by cartermp** [comment]
@dsyme You raise a good point.  I'm of a mind that we should also highlight those, but that all of this needs to be controlled by settings.  I'm inclined to agree that it should be turned off by default, but given the cadence for VS 2017 updates changing dramatically compared to previous VS releases, we're more able to iterate and gather feedback about things like this.  Might be worth turning it on by default and listening for feedback.

**Comment by vasily-kirichenko** [comment]
@dsyme Don, we had exactly the same discussion when I was adding refs highlighting as mutables into VFPT :) I stopped on mutables + refs and everybody has been happy for years. Let's do the same here.

**Comment by dsyme** [comment]
@vasily-kirichenko ok, thanks :)

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
Thank you for this.

**Pull request merged**
