### PR TITLE
LOC CHECKIN | visualfsharp - xliff | 20171113

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by forki** [comment]
what's this about?!

**Comment by v-zbsail** [comment]
This is an initial XLF localization handback from Moravia.

**Comment by brettfo** [comment]
@forki We're moving all of our localization support into this repo (it's currently in a private one) and this is part of that work.  Once I've done some other checks I'll merge this back into `master` which will enable:

1.  Community-provided translations for strings (pending review of our localization team for conformance with company standards.)
2.  Much faster turn-around for official builds.  E.g., eventually our nightly packages won't be nightly anymore, but every merge into `master` will produce a new package, which means there will be less lag between merge and a signed build.

**Comment by vasily-kirichenko** [comment]
I found a very poor (and even wrong) Russian translations here. Will PRs to localizations be accepted in the future?

**Comment by auduchinok** [comment]
@vasily-kirichenko Ouch. This translation is completely misleading.
Is there a way to disable translations on non-English OS?

**Comment by cartermp** [comment]
@vasily-kirichenko PRs should generally be accepted.  We'll see what we can do about getting the guidance @brettfo alludes to mentioned in this repo.  In the meantime, let's assume that fixing technical inaccuracies will be accepted.

**Pull request merged**
