### PR TITLE
fix upload of test results

### LINKED ISSUE #767: Appveyor Error running tests\Upload-Results.ps1
The appveyor build is throwing errors 'fileName' is null when calling Upload-Results.ps1.  Please see example from lines 3900+ here: https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.1126

### PR DESCRIPTION
**Pull request by mexx**
fixes #767

### CODE REVIEW

**Comment by mexx** [comment]
Unfortunately it's now failing due a server error on appveyor test result upload endpoint.

**Comment by enricosada** [comment]
i think is a dupe of #754

**Comment by mexx** [comment]
@enricosada right, haven't seen this one.

**Comment by enricosada** [comment]
my bad, i didnt opened an issue, only a pr.

**Pull request closed without merging**
