### PR TITLE
Reproduce #3376

### PR DESCRIPTION
**Pull request by forki**
Reproduce #3376

### CODE REVIEW

**Comment by dsyme** [comment]
@forki Thanks for making the repro

**Comment by forki** [comment]
urgs. it's not failing for the correct reason. Investigating...

**Comment by forki** [comment]
ok it's now reporting the correct error

**Comment by forki** [comment]
I'm not planning to fix it. It's just the repro

**Comment by cartermp** [comment]
Closing because #3520 fixes #3376

**Pull request closed without merging**
