### PR TITLE
replace list.Length = 0 with isNil

### PR DESCRIPTION
**Pull request by smoothdeveloper**
This is tiny optimization and code cleaning around empty list checks

* inline function AbstractIL.IL.isNil used to call to List.isEmpty (not inline), replace it with property access list.Length
* harmonize empty list comparison `list.Length = 0` across the code (only in places which had AbstractIL.IL open already) to always use isNil

Please use isNil

### CODE REVIEW

**Comment by rojepp** [comment]
This will slow things down as List.length will need to traverse the whole list.

**Comment by smoothdeveloper** [comment]
@rojepp if I'm correct, List.Length is just reading a property, and is the same as List.isEmpty implementation. In F#, each list node has a Length property.

**Comment by smoothdeveloper** [comment]
Oops, let me fix isNil then, you are right!

**Comment by smoothdeveloper** [comment]
@rojepp thanks a lot for review, so now I reverted isNil change but there are still 13 places with list traversal which I have replaced by a null check 😃, baffling there were so many expensive traversals to check the list was empty...

We should have a obsolete attribute on `list.Length` when used in F# compiler codebase.

**Comment by rojepp** [comment]
Now it should be slightly faster. isNil everywhere looks weird to me, and certainly no faster than List.isEmpty.

**Comment by forki** [comment]
We prefer isNil over isEmpty in compiler to keep things consistent

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Pull request merged**
