### PR TITLE
Add DesignTimeBuild=true  to legacy build from ProjectSystem

### PR DESCRIPTION
**Pull request by KevinRansom**
This replaces:  PR #4395.

Fixes: #3222 

The project system wasn't setting the DesignTimeBuild flag when running design time builds.  This PR addresses that issue.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@forki this does not impact dotnet sdk projects.

**Comment by 0x53A** [comment]
@KevinRansom I think this is related to https://github.com/Microsoft/visualfsharp/issues/1559.

In that issue, ``$(SolutionDir)`` is unset, I would guess that it would also need to be set here?

**Comment by KevinRansom** [comment]
@0x53a I can take a look separately at the $(SolutionDir) issue.  But it seems like that would not be something the project system is supposed to provide.

I imagine that this may speed up performance load for legacy projects.  I will take a look once I get tests passing.

Kevin

**Comment by cartermp** [comment]
@KevinRansom I believe the stress test that @saul mentioned is located here: https://github.com/Microsoft/visualfsharp/tree/master/tests/projects/stress

So it should be pretty easy to measure against baselines under `notes.txt`

**Comment by KevinRansom** [comment]
@0x53A Looks like a 10-12 % reduction in time when loading huge dense solution.

from (51.40, 52.51, 51.97, 51.96) seconds to (45.51, 45.68, 45.10, 45.32) seconds.

Time to semantic colorization.

**Comment by KevinRansom** [comment]
@0x53A 

This should be in tomorrows nightly build drop. Since I am about to pull it.  It won't make it int 15.6, but should first appear in a 15.7 preview when they come on stream.

Thanks for sticking at this, it yielded a nice improvement.

Kevin

**Comment by dsyme** [comment]
Can someone explain what setting the DesignTimeBuild flag does, roughly speaking? Thanks

**Pull request merged**
