### PR TITLE
Improved performance of splitAroundQuotation

### PR DESCRIPTION
**Pull request by TIHan**
This increases perf of `splitAroundQuotation` up to 50% and reduces GC 0 allocation counts by 60-70% roughly.

### CODE REVIEW

**Comment by cartermp** [comment]
@Horusiath this is the hot path for the report you sent us. When this is merged and a nightly is produced, would you be interested in trying out the nightly when using your code that makes use of Type Providers? Based on some perf testing we think this should help.

**Comment by cartermp** [comment]
FYI in our own testing, we saw an order of magnitude reduction in gen0 allocations with this change.

The trace analyzed had 50% of CPU time focused on GC collections, almost all from gen0
image

So this should hopefully make things better when working with Type Providers that produce large numbers of provided types.

**Comment by vasily-kirichenko** [comment]
@cartermp What is the tool that produces that table with profiling results?

**Comment by cartermp** [comment]
PerfView: https://github.com/Microsoft/perfview

* Load an ETL trace
* The table is in GCStats

**Pull request merged**
