### PR TITLE
fix add file reference (com dll)

### LINKED ISSUE #278: NullReferenceException when trying to add some COM references
When I try adding 'Microsoft Windows Installer Object Library' as a COM reference to my F# project it fails with "Object reference not set to an instance of an object":
image

Well, when I try doing that for a C# project if fails too, although with a different error:
image

However for a C# I can "Browse..." to a DLL directly by "C:\Windows\System32\msi.dll" and this adds COM reference just fine, but for F# this approach still fails with the same NullReferenceException.

### PR DESCRIPTION
**Pull request by enricosada**
lcid is an integer
fix typelib registry path, the lcid part is the hexadecimal string representation of the lcid value
added exception on failed add reference
fix nre on if registry key not found

fix #278

### CODE REVIEW

**Comment by latkin** [comment]
Is there an easy way to add an IDE unit test for this? If there are standard COM libs that trigger the issue it would be cool to have a test that validates "add reference" for one of those (assuming there is unit test support for the "add reference" action, maybe there isn't)

**Comment by enricosada** [comment]
maybe @lasandell can help us choose a suitable com class (he wrote the [COM typeprovider](https://github.com/fsprojects/FSharp.ComProvider) ) or give a feedback about com status in vs extension or tests needed.
In the [test](https://github.com/fsprojects/FSharp.ComProvider/blob/53698e4f9f5d0726d0be468bec89f61dc7bc3eb5/tests/FSharp.Interop.ComProvider.Tests/Script.fsx#L4-L7) they use COM.`Microsoft Shell Controls And Automation`.`1.0`.`ShellClass`

**Comment by enricosada** [comment]
added test

**Comment by enricosada** [comment]
the build failure is not related to this pr

    Build execution time has reached the maximum allowed time for your plan (40 minutes)

**Comment by latkin** [comment]
This is applied.

**Pull request closed without merging**
