### PR TITLE
Improve warning for ignored values in sequence expressions - fixes #4228

### LINKED ISSUE #4228: Improve warning for ignored values in sequence expressions
// stupid things to make the sample compile
    let div _ _ = 1  
    let subView _ _ = [1; 2]

    // elmish view
    let view model dispatch =
       [
           yield! subView model dispatch
           div [] [] // <- warning
           div [] [] // <- warning
       ]

This code gives famous the famous "The result of this expression is implicitly ignored" message and suggests to bind to a let binding. This is wrong advice and not helpful for newcomers in elmish apps. 

Instead we should improve the warning when we are inside of list comprehsions to something more useful.

### PR DESCRIPTION
**Pull request by forki**
fixes #4228

image

### CODE REVIEW

**Comment by forki** [comment]
I used a new error number so that we can built quickfixes on top of it.

**Comment by vasily-kirichenko** [comment]
Please, add type of the ignored expressing into the warning message.

**Comment by forki** [comment]
good point.

image

**Comment by vasily-kirichenko** [comment]
Excellent, it's in conjunction with the recent Don's PR which added ignored type names into all warning messages.

**Comment by forki** [comment]
@dsyme this is weird:

    src\fsharp\TypeChecker.fs(847,43): error FS0039: The field, constructor or member 'unitTypeExpectedInSequenceExpression' is not defined. 

for `src\buildfromsource\FSharp.Compiler.Private\FSharp.Compiler.Private.fsproj` in ci_part3 - but it's clearly there

**Comment by forki** [comment]
@vasily-kirichenko @dsyme another question: I see isListTy and isArrayty but no general isSeqTy. Do we hve something like that for TType?

**Comment by forki** [comment]
@kevinransom do you see by any chance why CI build 3 does not see the error message?

**Comment by KevinRansom** [comment]
Probably the way that text is converted to resources is  not quite wired up the same.  I will take a look later today.

**Comment by forki** [comment]
Thank you.

Am 23.01.2018 20:39 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by KevinRansom** [comment]
@forki Okay, I pushed a fix.

The reason this happened is because the build failed in the build from source projects.  Those guys are for RedHat integration.

That build depends on released product, and the build task that converts from  txt file to resx and generates the .fs file is not yet the build of the dotnet cli that they use.  Because of this, we just copy the transformed resx and .fs files.  As soon as they update their base build tools we will modify the buildfrom source build to use the buildtask.

Sorry for the inconvenience ... 

Kevin

**Comment by forki** [comment]
ok cool. so basically I need to touch these 2 files as well and things will be fine?

**Comment by KevinRansom** [comment]
@forki, yes, until the build from source uses a recent compiler, then it will be automagic like it should be.

**Comment by forki** [comment]
ok. this is done.

**Comment by cartermp** [comment]
ping @KevinRansom @dsyme for review

**Comment by dsyme** [comment]
Awesome work, thank you

It's possible a similar improvement could be made for async expressions?

**Pull request merged**
