### PR TITLE
Update fsharp.core.unittests

### PR DESCRIPTION
**Pull request by KevinRansom**
1.  Enable nunit from nuget for all OSS unittests
2. Update nunit to 2.6.4
3. Add iSurfaceArea verification for all profiles.
4. Separate SurfaceArea into separate project

### CODE REVIEW

**Comment by latkin** [comment]
Can you put your changes in a separate branch so that this doesn't get mixed in with the rest of what's happening on fsharp4? That's the normal PR workflow.

Seems like 2 unrelated things are happening here. Can you split this into 2 PRs?

- Migrating to nuget
- Changing the FSharp.Core surface area tests

I'm curious why a whole new test suite is needed just for the surface area test cases?  What is the problem with the existing approach? (granted I know it's a bit stale at the moment, but that's a small fix)

**Comment by KevinRansom** [comment]
I can split it up sure.  The unit tests run against the specific fsharp.core, whereas the surface area test reflects over the target fsharp.core and compares the types and methods against a known good list.

**Comment by dsyme** [comment]
@KevinRansom -  Ignore the AppVeyor failure, it wasn't properly configured.  If you'd like to re-run the job you can do that from https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/1.0.5 (since you have admin rights on the AppVeyor project)

**Comment by dungpa** [comment]
@KevinRansom Could you add Don and Lincoln as users/collaborators at https://ci.appveyor.com/team (see http://help.appveyor.com/discussions/questions/569-allow-github-project-collaborator-to-configure-appveyor-project-configuration)? It will be easier if more people have access to the CI build.

**Comment by latkin** [comment]
I have a less invasive fix for the surface area guys, will send PR shortly. We just need to properly add them to the existing portable unit test suites.

**Pull request closed without merging**
