### PR TITLE
Fix Literal values bug

### PR DESCRIPTION
**Pull request by AviAvni**
See https://github.com/Microsoft/visualfsharp/pull/4485
I Added a test to check that the problem is tested

### CODE REVIEW

**Comment by forki** [comment]
Ok cool. Test is red.

**Comment by AviAvni** [comment]
@forki ILComparer should throw error that the generated IL from the test code is different from the generated IL from LKG compiler

**Comment by forki** [comment]
Ah so it's testing against last compiler. Not the actual value. Interesting.

**Comment by forki** [comment]
But it's now green? While nothing in the sources changed?

**Comment by AviAvni** [comment]
My fault I need to prepare a file to compare the il I'll do it later

**Comment by AviAvni** [comment]
@forki @dsyme @KevinRansom ok now I think the test failed because of il diff

**Comment by KevinRansom** [comment]
@AviAvni I think we probably also need to ensure we do the right thing on coreclr and desktop and under fsi.

I'm currently looking at reflection code similar to:

````
open System
open System.Linq
open System.Reflection

module public MyLiteralFields =
    [<Literal>]
    let public literalFieldX = 7

[<EntryPoint>]
let main argv = 

    printfn "MyFields.literalFieldX = %d" MyLiteralFields.literalFieldX

    // Use dotnet reflection to verify that x is a Literal Constant
    // This works on full desktop / coreclr and also fsi
    let asm = Assembly.GetExecutingAssembly()
    let typ =  asm.GetTypes() |> Array.filter(fun t -> t.FullName.EndsWith("+MyLiteralFields")) |> Array.tryLast

    let result =
        match typ with
        | Some typ ->
            // Gets literalFieldX checks to see if it is marked "Literal"
            let fieldInfo = typ.GetTypeInfo().DeclaredFields |> Seq.tryFind(fun fi -> fi.Name.StartsWith("literalFieldX"))
            match fieldInfo with
            | Some fieldInfo -> 
                if fieldInfo.IsLiteral = true then 0 else 2
            | None -> 
                printfn "Failed to find fieldliteralFieldX ="
                3
        | None ->
            printfn "Failed to find module public MyLiteralFields ="
            1
    if result = 0 then printfn "Succeeded" else printfn "Failed: %d" result
    result

````
result is 2 without the fix and 0 with the fix on the desktop runnung under fsi.
However the reflection code is still desktop and netstandard 2.0, so it needs converting to netstandard1.6 because we still test on that puppy.

I will send you a pr with this to incorporate in your testing if you would like.

**Comment by AviAvni** [comment]
@KevinRansom ok waiting for your pr

**Comment by AviAvni** [comment]
@KevinRansom I added you as collaborator to my fork

**Comment by KevinRansom** [comment]
thanks.

**Comment by KevinRansom** [comment]
@AviAvni on ci_part2 and ci_part3 that tests fails with this output,:

````
1) Error : FSharp-Tests-Core+RegressionTests.literal-value-bug-1-FSC_BASIC
System.Exception : Invalid path regression/literal-value-bug-1/test.il.bsl
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at TestFramework.diff(Boolean normalize, String path1, String path2) in D:\j\w\release_ci_pa---c6929ad7\tests\fsharp\test-framework.fs:line 454
   at FSharp-Tests-Core.RegressionTests.literal-value-bug-1-FSC_BASIC() in D:\j\w\release_ci_pa---c6929ad7\tests\fsharp\tests.fs:line 1473


````

**Comment by AviAvni** [comment]
@KevinRansom thanks I'm working on it

**Comment by AviAvni** [comment]
@KevinRansom I fixed the comparison
one thing left I don't understand when I run the unit test I get
```
'C:\Users\aviav\Source\Repos\visualfsharp\tests\fsharp\regression\literal-value-bug-1\test.il' and 'C:\Users\aviav\Source\Repos\visualfsharp\tests\fsharp\regression\literal-value-bug-1\test.il.bsl' differ; "diff between [C:\Users\aviav\Source\Repos\visualfsharp\tests\fsharp\regression\literal-value-bug-1\test.il.bsl] and [C:\Users\aviav\Source\Repos\visualfsharp\tests\fsharp\regression\literal-value-bug-1\test.il]
line 40
 -  // MVID: {5AA663EB-D9C1-2E4E-A745-0383EB63A65A}
 + // MVID: {5AA66C86-D9C1-2E4E-A745-0383866CA65A}
diff between [C:\Users\aviav\Source\Repos\visualfsharp\tests\fsharp\regression\literal-value-bug-1\test.il.bsl] and [C:\Users\aviav\Source\Repos\visualfsharp\tests\fsharp\regression\literal-value-bug-1\test.il]
line 46
 - // Image base: 0x02BF0000
 + // Image base: 0x00910000
diff between [C:\Users\aviav\Source\Repos\visualfsharp\tests\fsharp\regression\literal-value-bug-1\test.il.bsl] and [C:\Users\aviav\Source\Repos\visualfsharp\tests\fsharp\regression\literal-value-bug-1\test.il]
line 55
 -   .field public static literal int32 x = int32(0x00000007)
 +   .field public static int32 x = int32(0x00000007)
```
the MVID and  Image base always changing the other change is what we looking for

**Comment by KevinRansom** [comment]
@AviAvni It looks to me as if you inadvertently added an extra space at the start of the mvid line:
https://github.com/AviAvni/visualfsharp/blob/845e4c0b12ddbd7c73021dcd350273edbfc46ce6/tests/fsharp/regression/literal-value-bug-1/test.il.bsl#L40

**Comment by AviAvni** [comment]
@KevinRansom Ilcomparer is doing it and it only used in fsharpqa test and I didn't figure out how it run
fsdiff don't ignore comments and in FsharpTestSuite there is no use of ilcomparer

**Comment by KevinRansom** [comment]
@AviAvni 
Durn it, our test suites are not great.  I think the reflection tests will catch the error. but you could add your test over here:   https://github.com/Microsoft/visualfsharp/tree/master/tests/fsharpqa/Source/CodeGenEmittedIL/

There are plenty of examples there how to check against a baseline.

**Comment by AviAvni** [comment]
@KevinRansom ok i moved the test to fsharpqa waiting to see the build result

**Comment by AviAvni** [comment]
@KevinRansom ok so now I think my test didn't run because your test failed so when you finish with your pr we can build this again and check that all test passed

**Comment by KevinRansom** [comment]
I will merge my  pr into this one, and close mine then we will be Golden :-)

**Comment by AviAvni** [comment]
@KevinRansom If I can help with something ping me

**Comment by KevinRansom** [comment]
Thank you for everything you have done I really appreciate it.

Kevin

**Comment by KevinRansom** [comment]
@dsyme, @AviAvni , @brettfo, @TIHan please review this.

Thanks

KEvin

**Comment by forki** [comment]
I added the similar refactor for the marshal case. It wasn't broken, but now it's same pattern

**Pull request merged**
