### PR TITLE
Replace pattern matches inside async blocks with AsyncMaybe CE

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This PR removes a lot of boilerplate.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@vasily-kirichenko conflicts mate.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
I'm guessing this is at the heart of where you work.

More conflicts.

**Comment by vasily-kirichenko** [comment]
@KevinRansom fixed.

**Comment by cartermp** [comment]
Awesome!  Great to have this in.  Definitely makes a lot of things look nicer, since the "asynchronous operation that returns an option" is so common in this project.

**Pull request merged**
