### PR TITLE
merge vs2017-rtm branch into master

### PR DESCRIPTION
**Pull request by brettfo**

### CODE REVIEW

**Comment by brettfo** [comment]
Building and running tests locally now.

**Comment by KevinRansom** [comment]
@brettfo any progress on this.

**Comment by brettfo** [comment]
I've been delayed by VS setup issues, but as soon as I get that dumpster fire put out I'll be back on this.

**Comment by brettfo** [comment]
Manually completed by a982ecfc1e235b9711350924697f2faff2f05ab9.

**Comment by brettfo** [comment]
Inline rename works again, lets just hope I didn't break anything else.

**Pull request merged**
