### PR TITLE
Cleanup use of internal functions

### PR DESCRIPTION
**Pull request by forki**
I think we should use the collection APIs where possible.

### CODE REVIEW

**Comment by forki** [comment]
dk:

     are those just stylistic changes?

forki:

    nope. I'm replacing internal functions with the ones from FSharp.Core
    these are sometimes better optimized (at least people try to do this) and sometimes get inlined
    so this could be beneficial for compiler perf

**Comment by tldrlol** [comment]
On a shallow examination all changes seem to preserve existing logic.

My only nitpick is `not (List.isEmpty ...)` repetition everywhere. I would consider letting `nonNil` live on.

**Comment by KevinRansom** [comment]
My preference is how Steffen has it now, it is clearer and not really many more characters.

**Comment by forki** [comment]
The real advantage is that we got rid of a couple of these manual helper
functions that we have everywhere

Am 23.08.2016 19:40 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by forki** [comment]
ok I think it's ready to go in.

**Comment by KevinRansom** [comment]
Looks good to me.

**Pull request merged**
