### PR TITLE
[WIP] ConstraintSolver internal error fix

### PR DESCRIPTION
**Pull request by TIHan**
Resolving this issue: https://github.com/Microsoft/visualfsharp/issues/5580

Should not regress: https://github.com/Microsoft/visualfsharp/issues/4343#issuecomment-365300858

### CODE REVIEW

**Comment by cartermp** [comment]
cc @gusty

**Comment by gusty** [comment]
I'm more than happy to see this reverted.

@TIHan What's the difference between this reversion and the one I attempted in #4173, in order to keep #4343 working?

**Comment by TIHan** [comment]
@gusty this one is slightly different, instead of returning the `Locally` type, I just return the `UnresolvedOverloading` error in `SolveMemberConstraint`. That seems to fix the issue and not regress, but it seems it is also breaking other stuff.

This one is going to be very tricky. It seems even a slight tweak will change behavior in a way that isn't expected.

**Comment by gusty** [comment]
I know it's gonna be tricky, the way I see it is that if it's not possible to fix it in such a way `(b)` will be the only option.

**Comment by cartermp** [comment]
IIRC the break that eventually caused a re-reversion has had that project undergo changes so that they weren't dependent on the broken behavior, so I do lean towards (b), since it is a major language change where we'll be doing other "invasive" things (Nullable References).

**Comment by TIHan** [comment]
`(b)` is most likely what we will do.

**Comment by KevinRansom** [comment]
@TIHan 

Is this still WIP?  It looks okay to me.  It's targeting the de15.9 branch and so we need to prioritize getting it done.  OR are we going to instead target this at dev16.0?

If we are aiming at 15.9 do we have a bug in TFS for tracking this?

/cc @cartermp, @Pilchie, @dsyme

**Comment by TIHan** [comment]
This is still WIP and will not be in dev15.9. It could have been if the fix was quick and didn't break other stuff; but unfortunately it did. The correct fix will take considerable more time to figure out.

**Comment by gusty** [comment]
Why was this closed?
Is this issue solved somewhere else or was finally decided to revert the offending PR?

**Comment by brettfo** [comment]
Looks like it was auto-closed when I cleaned up the `dev15.9` branch; sorry about that.  You should be able to rebase this onto `master` and re-open or re-create.

**Comment by gusty** [comment]
Since this was not solved, can we revert again to the correct behavior and use the language switch for F# 4.7?

**Comment by cartermp** [comment]
@gusty  or @TIHan could you re-open this and target master?

I agree that with LangVersion in we can reconsider a fix like this.

**Pull request closed without merging**
