### PR TITLE
Remove quickparse from VS.FSI

### PR DESCRIPTION
**Pull request by cartermp**
None of these code paths are active and there is a `QuickParse.fs` in the language service that does useful things, should the half-implemented IntelliSense for FSI ever be completed.

### CODE REVIEW

**Comment by cartermp** [comment]
Same FCS test failure as #5838 - @dsyme why would removing a file in VS.FSI cause an unrelated test in FCS to fail?

**Comment by dsyme** [comment]
> Same FCS test failure as #5838 - @dsyme why would removing a file in VS.FSI cause an unrelated test in FCS to fail?

I don't know, I glanced at the test and it shouldn't.  Is it failing in a no-op PR sometimes?

**Comment by cartermp** [comment]
Yep, looks like a transient failure.

**Comment by cartermp** [comment]
@KevinRansom This is ready.

**Pull request merged**
