### PR TITLE
Fix test failures, restoring tests matrix

### PR DESCRIPTION
**Pull request by otawfik-ms**

### CODE REVIEW

**Comment by enricosada** [comment]
great job @otawfik-ms !

**Comment by enricosada** [comment]
as a side node about build matrix:

fsharp suite (smoke)

| Before parallelization | After parallelization |
|  22 min                      | 15 min                     |

and that's because there are some test, but few test directories ( parallelization work by directory )

**Comment by enricosada** [comment]
btw @otawfik-ms , if you want you can do merge `cambridge_suite` and `qa_suite` in a single job

```
- BUILD_PROFILE: cambridge_suite,qa_suite,smoke_only
```

it's 7 minutes less ( the base download+compilation for a job is 7 minutes )

**Comment by otawfik-ms** [comment]
@enricosada Strangely, it took more on my private build:
https://ci.appveyor.com/project/otawfik-ms/visualfsharp/build/0.0.1.8
I'll let it run for a few builds, and then combine them if they're consistently faster.

**Comment by KevinRansom** [comment]
56 minutes for the verification --- kind of sucks.

**Comment by enricosada** [comment]
The private build is oss ( or are you pro user? ) and run on a less powerful machine, i think. My private build for sure are slower

Inviato da Outlook Mobile




On Fri, Dec 18, 2015 at 11:01 AM -0800, "Omar Tawfik" <notifications@github.com> wrote:





@enricosada Strangely, it took more on my private build:
https://ci.appveyor.com/project/otawfik-ms/visualfsharp/build/0.0.1.8
I'll let it run for a few builds, and then combine them if they're consistently faster.

---

**Comment by enricosada** [comment]
Maybe after coreclr we can use also the jenkins build servers. 
Otherwise the only solution is buy another build worker = 25 min.

**Comment by enricosada** [comment]
Is really funny. Appveyor run in azure :smile:

**Comment by KevinRansom** [comment]
@enrico OSS is the same as PRO just half price or at least it was at the time.

**Comment by KevinRansom** [comment]
I am beginning to suspect though that our setup is not running on dedicated hardware like it should, instead it maybe running in the cloud.

**Comment by KevinRansom** [comment]
Hmm!!!! Pro is one concurrent job, so no parallel jobs without the premium plan.

**Comment by otawfik-ms** [comment]
@KevinRansom, actually, running in parallel with this speed means that we will be running all the tests (in this PR) in less than 30 minutes. I'm looking into all the options now to see if there is something we are missing.

**Comment by KevinRansom** [comment]
I suppose 1 concurrent Job, could mean one job + another concurrently.  It's not the way I would have read it.

**Comment by KevinRansom** [comment]
Okay we will pull this in, and we can work with it, while you figure out how to make it faster :-)

**Pull request merged**
