### PR TITLE
update swix plugin

### PR DESCRIPTION
**Pull request by brettfo**
This just updates an internal build tool to the latest version.  Changes to this tool have had a tendency to break us in the past, but I've done a full internal build (verifying that this specific version was used) and everything was green.

FYI @KevinRansom

### CODE REVIEW

**Comment by brettfo** [comment]
@KevinRansom, any reason this was closed without being merged?

**Comment by dsyme** [comment]
reopening just in case so we don't lose track of it  :)

**Comment by brettfo** [comment]
@dotnet-bot test this please

**Comment by brettfo** [comment]
@mmitche, can I get your thoughts on this?  The [Jenkins failure](https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part1_windows_nt_prtest/2740/consoleFull#1712435700eb4140aa-ed80-458c-9ba3-2306d2e3cafd) is that the Swix 1.0.147 package could not be found, presumably because it's an internal-only package.  Is there a package URL that can be added that the Jenkins machines have access to?  Or is there additional machine setup that needs to be done?  I can get this package locally, but only after jumping through some manual auth hoops, and the official signed build can obviously get it, just not this.

**Comment by mmitche** [comment]
@brettfo I don't know enough about the package URLs, but here are the restrictions on the Jenkins machines.  If you can figure out a way to work within these boundaries then the issue should be solveable
- They don't have domain access
- They don't have manual user interaction

Other than that, they can access most anything.  Is this something that could be solved by changing the base VHD?

**Comment by brettfo** [comment]
> Is this something that could be solved by changing the base VHD?

Yes, but it'd be a terrible hack; manually populate the local NuGet cache with this package.  Older versions of this package have all been made publically available, just not the latest.  I'll start a conversation with the package owners to see their proposal.

**Comment by brettfo** [comment]
@dotnet-bot test this please

**Comment by brettfo** [comment]
Now that package issues have been fixed (internally mirroring), ping to @KevinRansom for any review before I merge this tomorrow morning.

**Pull request merged**
