### PR TITLE
Handle "Blue (high contrast)" theme

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by cartermp** [comment]
@brettfo is this PR still necessary with the internal PR you created?

**Comment by brettfo** [comment]
My internal change is still required to handle Windows high contrast settings, but this one is still a good idea because it fixes the color issue for most users and will be available in the next nightly (once it's merged.)  My change won't be available until the next update to VS ships (and I don't know when that is.)

**Comment by cartermp** [comment]
Makes sense.  This PR looks right assuming that the VS underneath has your PR in it.  I'll remove the WIP prefix unless there are any objections.

**Comment by cartermp** [comment]
🎉 Thanks @vasily-kirichenko

**Pull request merged**
