### PR TITLE
Migrate a set of fsharpqa tests to new test suite (overload resolution error messages)

### PR DESCRIPTION
**Pull request by smoothdeveloper**
This PR intends to migrate fsharpqa tests that are going to be impacted by #6596. 

My plan is to be able to rebase the other PR once those tests from fsharpqa have been migrated to new suite.

Adjusting fsharpqa tests for multiline error message is too much effort, and it would save me some effort if this PR is pertinent.

* [x] duplicate the relevant fsharpqa tests into the fsharp test suite
* [x] update baseline files
* [x] remove those tests from fsharpqa
* [x] get all green

Note: I'm using .fsx files for the tests, the main reason is that the tooling picks up errors on the spot even if the files aren't loaded from a project; I can't get this behaviour to work in VS2019 with .fs files.

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
Master fsharpqa: https://dev.azure.com/dnceng/public/_build/results?buildId=167958
```
3176 tests passed (100.00%)
0 tests failed (0.00%)
0 tests were cascaded failures (0.00%)
0 tests returned "no result" (0.00%)
0 tests timed out (0.00%)
0 tests had test errors (0.00%)
========
3176 Total executed tests
```

this PR:

```
3164 tests passed (100.00%)
0 tests failed (0.00%)
0 tests were cascaded failures (0.00%)
0 tests returned "no result" (0.00%)
0 tests timed out (0.00%)
0 tests had test errors (0.00%)
========
3164 Total executed tests
```

-12 expected

Master Windows desktop_release: https://dev.azure.com/dnceng/public/_build/results?buildId=173798

```Total tests: 392. Passed: 389. Failed: 0. Skipped: 3.```

this PR:

```Total tests: 404. Passed: 401. Failed: 0. Skipped: 3.```

+12 expected

This is ready

**Comment by smoothdeveloper** [comment]
Thanks for the feedback @KevinRansom, I wasn't able to run the migrated tests successfully under .netcore + failure on CI so I disabled them with the #define used in the tests.fs for now.

the error where it failed:
> parameter error FS0193: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

https://dev.azure.com/dnceng/public/_build/results?buildId=173542

Maybe you'll know better if we can fix this and enable them on core compiler target.

I'm also wondering about the status of giving .fsx files to fsc.exe, the migrated fsharpqa tests are under .fsx for tooling reason (opening the file shows the errors, not if it is a .fs).

I’ve migrated that exact set of tests:
https://github.com/Microsoft/visualfsharp/pull/6596#issuecomment-486070137

I double checked it in the .lst changes, but it would be great to have it cross checked as well.

**Comment by KevinRansom** [comment]
I was just telling @brettfo, I would see what it took to make the singlenegtest handle coreclr as a weekend, fun/misery.  Project before long.

**Comment by smoothdeveloper** [comment]
Thanks @brettfo there we go, -12 fsharpqa tests, +12 potentially multi target and easier to maintain tests 🙂.

**Comment by smoothdeveloper** [comment]
@brettfo @KevinRansom would you happen to know why the .bsl (& .err) files have redundant CR compared to textual output from the compiler?

It would be worth fixing it if we know the reason and it is not a big change (the diff in .bsl files will be big though).

**Comment by KevinRansom** [comment]
I think it's best to treat those tests as a big blob of "Here there be dragons" … and cautiously migrate out the tests.  However, there is a big problem with doing that … the fsharpqa tests can use the F# compiler server, so we don't constantly spin up a new compiler for the tests that need compilation.  the Cambridge tests don't do that.  So migrating them earns us a slow down.

too much to do.

**Pull request merged**
