### PR TITLE
Enable IsModule test for Core CLR

### PR DESCRIPTION
**Pull request by PatrickMcDonald**
Fixes https://github.com/Microsoft/visualfsharp/issues/2462

### CODE REVIEW

**Comment by KevinRansom** [comment]
@PatrickMcDonald 
Lol ... well that was a pretty nice fix.

Thanks

Kevin

**Comment by PatrickMcDonald** [comment]
@KevinRansom I must admit I was pretty sure when it didn't fail that it hadn't run :D

**Comment by KevinRansom** [comment]
@PatrickMcDonald 
Yes ... the test ran ...

I added an assert to fail in the test method  and it indeed failed ...

````
1) Failed : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Reflection.FSharpTypeTests.IsModule
  Expected: False
  But was:  True
at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Reflection.FSharpTypeTests.IsModule() in c:\microsoft\visualfsharp\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Reflection\FSharpReflection.fs:line 768
````

**Comment by KevinRansom** [comment]
@PatrickMcDonald 

Thank you for doing this ...

**Pull request merged**
