### PR TITLE
Port a test from Paket over to FSharp.Core tests

### PR DESCRIPTION
**Pull request by forki**
This test was added to Paket by @Thorium in August 2016 and worked up to FSharp.Core 4.1.17 but hangs in 4.2.1.

/cc @eiriktsarpalis @dsyme @matthid @Thorium

### CODE REVIEW

**Comment by forki** [comment]
ok it seems to work on master.

**Comment by forki** [comment]
Mhm it also seems to work against the 4.2.1 branch. I'm lost

**Comment by forki** [comment]
Correspondign Paket branch: https://github.com/fsprojects/Paket/pull/2553

**Comment by forki** [comment]
Ok it clearly hangs in paket when we update fsharp.core.

**Comment by forki** [comment]
Ok so it seems that it's not test what's hanging. I commented that test out from paket's test suite and it's still hanging. So I still believe the new fsharp.core is flawed, but not with this test here. @matthid and myself will investigate further. 

Anyway @kevinransom please feel free to merge this test here. It's good to have it in the code base.

**Comment by KevinRansom** [comment]
@forki 
Thanks mate

**Pull request merged**
