### PR TITLE
WIP: Integrate CoreCLR with latest changes from master

### PR DESCRIPTION
**Pull request by rojepp**
This doesn't build yet, for the same reason, it seems, that others can't build the CoreCLR branch. 
Some help with fixing that up would be nice. I think it has something to do with myget and/or versions of dnx. 
Proto-compiler at least builds.

### CODE REVIEW

**Comment by dsyme** [comment]
Great! Some of the errors I see in the build

```
[00:00:31] WARNING: Unable to find version '1.0.0-beta6-12032' of package 'dnx-coreclr-win-x86'.
[00:00:31] WARNING: Unable to find version '1.0.0-beta5-12077' of package 'dnx-mono'.
[00:00:31] Unable to find version '1.0.0-beta6-12032' of package 'dnx-coreclr-win-x86'.
[00:00:31] Unable to find version '1.0.0-beta5-12077' of package 'dnx-mono'.


[00:01:01]   Unable to resolve System.Security.SecureString (� 4.0.0-beta-23225) for DNXCore,Version=v5.0.

[00:02:48] The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.

[00:02:51]   EXEC : warning : Unable to find version '1.0.0-beta6-12032' of package 'dnx-coreclr-win-x86'. [C:\projects\visualfsharp-radou\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj]

[00:03:08] C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(89,5): error : Couldn't find the required information in the lock file. Make sure you have .NETFramework,Version=v4.5 mentioned in your targets. [C:\projects\visualfsharp-radou\src\fsha


```

**Comment by KevinRansom** [comment]
I will look at this, this evening, I apologize for the delay, I am currently swamped on Update 1 preparations. I think the fix will likely be teeny tiny.

And thanks for looking at this, I was dreading the merge.

Kevin

**Comment by rojepp** [comment]
It may well be that there are still errors left after these first issues are resolved. It was a messy merge. :)
If you haven't resolved this by Saturday, I'll probably take a closer look then.

**Comment by KevinRansom** [comment]
@rojepp Hi, I have checked in an updated project.json and an updated tests/fsharp/single-test-buildandDeploy.fsx.

@rojepp 

This should fix the nuget portion of the build.] errors.  Yes, it was a very messy merge, which was I dreaded it.  I really should have put a stop to the refactorings until the coreclr was completed.  But Don was having such a good time :-)

I am going to remain slammed for at least the remainder of this week and probably the first half of next week.  If you need me to look at something I can fit it in in the evenings though.

Let me know how it goes.

Thanks for looking at this,

Kevin

**Comment by rojepp** [comment]
@KevinRansom :+1: 
Interesting to note that the coreclr branch also no longer builds. So we're trying to solve two problems at once (building and integrating latest changes). :/ 
I'll take a look at getting the base coreclr to build.

**Comment by rojepp** [comment]
Current error if we ignore a ton of warnings: 

>Build started 10/14/2015 12:01:51 PM.
>The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (156,61)" does not exist in the project, and will be ignored.
>Project "C:\projects\visualfsharp-radou\src\fsharp-library-build.proj" on node 1 (default targets).
>Project "C:\projects\visualfsharp-radou\src\fsharp-library-build.proj" (1) is building "C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core\FSharp.Core.fsproj" (2) on node 1 (Build target(s)).
>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(89,5): error : Couldn't find the required information in the lock file. Make sure you have .NETFramework,Version=v4.5 mentioned in your targets. [C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
>Done Building Project "C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core\FSharp.Core.fsproj" (Build target(s)) -- FAILED.
>Done Building Project "C:\projects\visualfsharp-radou\src\fsharp-library-build.proj" (default targets) -- FAILED.

**Comment by dsyme** [comment]
@KevinRansom  - the refactorings were actually not large :) There was little structural change in the code, just localized cleanup and file renames.  

In truth the compiler needs much more cleanup, refactoring and documentation to put it on a really good technical basis going forward and address some of the key issues. I think it's really good that you have started to allow this kind of work to happen...  Branches are inevitably affected by cleanup integrations, but that's just the nature of things :)

**Comment by KevinRansom** [comment]
@rojepp CORECLR branch should build fine.  There is however, an issue with deploying the compiler for tests because the nuget package format has changed, with implementation files now being in different packages, one per platform and pointed to by a runtime.json file.

@dsyme ... I agree the work is necessary, It's just my luck to be in a separate branch and mucking with the same code while it happens.  And anyway it's important that we all have a good time, except Robert who unwisely volunteered to ease my pain :-)

Kevin

**Comment by KevinRansom** [comment]
@rojepp it looks like nuget is not resolving some of the packages correctly.  And nuget has an opaque configuration story so maybe I have a local configuration that is allowing them to resolve on my laptop but not from the ci machine.  I will see if I can figure it out.

Kevin

**Comment by rojepp** [comment]
@KevinRansom Right now it's unclear that I'm easing anyones pain. :) I'll keep looking for errors in my branch then, since compilation still fails there.

**Comment by KevinRansom** [comment]
@rojepp A pain shared is a pain doubled my friend :-)

**Comment by KevinRansom** [comment]
@rojepp if you want I will take a stab at doing the merge.  At least that way, I will have some chance of figuring out why I changed the code that caused the conflict.

Kevin

**Comment by rojepp** [comment]
Absolutely!

**Comment by ctaggart** [comment]
@rojepp That error that you got is something that I just got around in #687 by adding a bunch of `/p:ResolveNuGetPackages=false` in [appveyor-build.cmd](https://github.com/ctaggart/visualfsharp/commit/967daadcf2f1b71acaf95f9a5f37594b92ae90a7#diff-5fc5e8ed89677a3a023a4c1b9ba5f54d).

**Comment by rojepp** [comment]
@ctaggart Interesting, thanks. Resolving nuget packages should be a good thing though?

**Pull request closed without merging**
