### PR TITLE
Fix 32: add general check for escaping typars to check phase

### PR DESCRIPTION
**Pull request by dsyme**
This (partly) addresses the class of conditions like #32 which give "undefined type variable" internal errors by adding an earlier check to check.fs which gives a user-visible error in this case.

These conditions can in some cases indicate problems with type inference, though in the case of #32 the check is actually the best way to detect the escape condition.

Output from the neg91.fs needs to be updated.

### CODE REVIEW

**Comment by dsyme** [comment]
A full test pass will be needed to check that this error doesn't trigger on any existing known code.

**Comment by latkin** [comment]
I'm seeing two tests that previously passed, and are now failing with the new error. Both have a non-trivial amount of code, so I won't paste it here.
 - `tests\fsharpqa\source\Conformance\TypesAndTypeConstraints\TypeParameterDefinitions\ValueTypesWithConstraints01.fs`

- `tests\fsharpqa\source\Misc\ConstraintSolverRecursion01.fs`

Just compile each source file with no flags to repro.

**Comment by dsyme** [comment]
Thanks, I'll take a look.

**Comment by dsyme** [comment]
I've updated this - thanks. This line is the relevant addition: https://github.com/dsyme/visualfsharp/commit/3c3708fda6d0c16c45f68caed09a05a38c41f746#diff-7044d4e85f35657f78a245e763e92ddcR146. I'm glad we flushed out that particular problem.

Another full test run is needed I'm afraid, sorry about that. it's just one of those things. 

Cheers!
Don

**Comment by latkin** [comment]
Ok, tests are all green now.  GIven that, do you feel this is a safe enough fix that we can apply it this late?

**Comment by dsyme** [comment]
I'm OK with putting this off to vNext (e.g. first OOB)

**Comment by latkin** [comment]
Applied to the OOB branch, thanks!

**Pull request closed without merging**
