### PR TITLE
bring qualified assembly name in error message to disambiguate types

### PR DESCRIPTION
**Pull request by smoothdeveloper**
This is proposed fix for #2561, I need to figure out if the test is correct.

Please let me know if anything needs to be taken care of.

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
before:

image

after

image

I'm sure it won't work in all the case we might face but this seems like a good start.

**Comment by dsyme** [comment]
This looks right, thanks, it's certainly OK to add that as another attempt to disambiguate

**Comment by smoothdeveloper** [comment]
I'd like some help on how to formulate the `<Expect>` message match in `app.fs`, I'm not able to figure it out, should I split those in several simpler ones?

**Comment by KevinRansom** [comment]
@smoothdeveloper 

Hey mate ... the test doesn't produce any error output unless I am missing something ...

````
c:\microsoft\visualfsharp\tests\fsharpqa\Source\ErrorMessages\ConfusingTypeName>csc -t:library -out:liba.dll liba-and-b.cs && csc -t:library -out:libb.dll liba-and-b.cs && c:\microsoft\visualfsharp\release\net40\bin\fsc --target:library -r:liba.dll --out:libc.dll libc.fs && c:\microsoft\visualfsharp\release\net40\bin\fsc --target:library -r:libb.dll --out:libd.dll libd.fs
Microsoft (R) Visual C# Compiler version 2.0.0.61501
Copyright (C) Microsoft Corporation. All rights reserved.

Microsoft (R) Visual C# Compiler version 2.0.0.61501
Copyright (C) Microsoft Corporation. All rights reserved.

Microsoft (R) F# Compiler version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.
Microsoft (R) F# Compiler version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

c:\microsoft\visualfsharp\tests\fsharpqa\Source\ErrorMessages\ConfusingTypeName>
````

Kevin

**Comment by smoothdeveloper** [comment]
@KevinRansom thanks for looking into this, I'm having trouble to run the tests locally (decided it wasn't worth making the CI server run for 30 minutes just to try one more thing).

I think you miss the last part of the test which compiling `app.fs` (can you check in compile.bat which I left for easy trial)?

What I get when I try to run the test:

```
C:\dev\src\projects\github.com\visualfsharp\tests\fsharpqa\Source>perl C:\dev\src\projects\github.com\visualfsharp\tests\fsharpqa\testenv\bin\runall.pl -resultsroot C:\dev\src\projects\github.com\visuOne or more output files exist from a previous test run and will be renamed:
        Renaming 'C:\dev\src\projects\github.com\visualfsharp\tests\TestResults\test-net40-fsharpqa-results.log' to 'C:\dev\src\projects\github.com\visualfsharp\tests\TestResults\test-net40-fsharpqa-results.log.03'
        Renaming 'C:\dev\src\projects\github.com\visualfsharp\tests\TestResults\test-net40-fsharpqa-errors.log' to 'C:\dev\src\projects\github.com\visualfsharp\tests\TestResults\test-net40-fsharpqa-errors.log.03'
        Renaming 'C:\dev\src\projects\github.com\visualfsharp\tests\TestResults\test-net40-fsharpqa-errors.env' to 'C:\dev\src\projects\github.com\visualfsharp\tests\TestResults\test-net40-fsharpqa-errors.env.03'
ClrFx\PseudoCustomAttributes\AssemblyAlgorithmId -- skipped : run.pl contains errors
ClrFx\PseudoCustomAttributes\AssemblyConfiguration -- skipped : run.pl contains errors
ClrFx\PseudoCustomAttributes\AssemblyVersion -- skipped : run.pl contains errors
Diagnostics\async -- skipped : run.pl contains errors
Diagnostics\General -- skipped : run.pl contains errors
Diagnostics\NONTERM -- skipped : run.pl contains errors
Diagnostics\ParsingAtEOF -- skipped : run.pl contains errors
EntryPoint -- skipped : run.pl contains errors
Globalization -- skipped : run.pl contains errors
Import -- skipped : run.pl contains errors
..\..\..\testsprivate\fsharpqa\Source\InteractiveSession\AssemblyLoading -- skipped : Skipping private test
InteractiveSession\Misc -- skipped : run.pl contains errors
Libraries\Control -- skipped : run.pl contains errors
Libraries\Core\collections -- skipped : run.pl contains errors
Libraries\Core\ExtraTopLevelOperators -- skipped : run.pl contains errors
Libraries\Core\LanguagePrimitives -- skipped : run.pl contains errors
Libraries\Core\NativeInterop\stackalloc -- skipped : run.pl contains errors
Libraries\Core\Operators -- skipped : run.pl contains errors
Libraries\Core\Reflection -- skipped : run.pl contains errors
Libraries\Core\Unchecked -- skipped : run.pl contains errors
Warnings -- skipped : run.pl contains errors
ErrorMessages\NameResolution -- skipped : run.pl contains errors
ErrorMessages\UnitGenericAbstractType -- skipped : run.pl contains errors
ErrorMessages\ConfusingTypeName -- skipped : run.pl contains errors


0 tests passed (0%)
0 tests failed (0%)
0 tests were cascaded failures (0%)
0 tests returned "no result" (0%)
0 tests timed out (0%)
0 tests had test errors (0%)
========
0 Total executed tests

24 tests were skipped
========
24 Total tests (executed & skipped)

1s Total time

C:\dev\src\projects\github.com\visualfsharp\tests\fsharpqa\Source>perl run.pl
GetExpectedResults::Can't open source file: : No such file or directory
FAIL

```

**Comment by vasily-kirichenko** [comment]
do you have active perl installed and in path?

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko 

> C:\dev\src\projects\github.com\visualfsharp\tests\fsharpqa\Source>perl --version

```
This is perl 5, version 18, subversion 1 (v5.18.1) built for MSWin32-x64-multi-thread
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Binary build 1800 [297570] provided by ActiveState http://www.ActiveState.com
Built Sep 20 2013 15:07:17

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by KevinRansom** [comment]
I pushed a test fix  to your branch.  I hope that fixes it.  That Expects stuff seems too hard for ordinary folk like me.

**Comment by smoothdeveloper** [comment]
@KevinRansom the test passed, thanks a lot!

**Pull request merged**
