### PR TITLE
[FS-1044] Add NativePtr.toByRef

### PR DESCRIPTION
**Pull request by mjmckp**
The `toByref` method fills a gap in the `NativePtr` module - converting typed native pointers to byref pointers.  This is necessary, e.g., to call methods such as `Thread.VolatileRead` or `Thread.VolatileWrite`.  This method was originally proposed here https://github.com/Microsoft/visualfsharp/issues/409 but wasn't incorporated into the `NativePtr` module.

RFC https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1044-add-nativeptr-tobyref.md

### CODE REVIEW

**Comment by abelbraaksma** [comment]
I think it is a good addition, but I'd suggest to name it `toByRef` in stead. If I look at the code base, that seems to be the common nomenclature (i.e., compare `System.MarshalByRefObject` or `member __.IsByRef` in Symbols.fs).

I don't know whether the compiled name should include the suffix `Inlined`?

**Comment by mjmckp** [comment]
@abelbraaksma I have changed the name as suggested.  I included the suffix 'Inlined' for the compiled name to be consistent with the compiled name for all the other inline methods in the module.

**Comment by abelbraaksma** [comment]
Before @dsyme or @KevinRansom  can merge this, you should probably fix the tests. I didn't check, but perhaps the surface area changed (there's a test that deliberately fails each time a public method is added, changed, removed)? I am not 100% sure what is required to add public methods to the core in terms of procedure.

**Comment by mjmckp** [comment]
Thanks @abelbraaksma, I had a look through the tests and there doesn't appear to be a single place in which the `NativePtr` module is tested, would you mind suggesting a location?  I was thinking of just a basic read/write test on the resulting `byref` for a few core types, would that be sufficient?

**Comment by dsyme** [comment]
Some tests come up in this search: https://github.com/Microsoft/visualfsharp/search?utf8=%E2%9C%93&q=NativePtr&type=

**Comment by mjmckp** [comment]
I've updated the tests, thanks.  No idea why the CI builds are failing, tho.

**Comment by mjmckp** [comment]
There is a similar method in  System.Runtime.CompilerServices.Unsafe [here](https://github.com/dotnet/corefx/blob/c910a3d969d271fb9dd14e55e19b642b8e661570/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L262), which has a nontrivial implementation for non .NET core (does a round-trip via a local).  Is there any chance the same thing applies here?

**Comment by realvictorprm** [comment]
@dotnet-bot test this please

**Comment by realvictorprm** [comment]
Triggering test because details ain't available.

**Comment by realvictorprm** [comment]
@mjmckp please rename the PR name to respect the changed naming.

**Comment by realvictorprm** [comment]
@dsyme all Checks have passed. Is this ready to merge now?

 @mjmckp thanks!

**Comment by realvictorprm** [comment]
@KevinRansom F# 4.3 ?

**Comment by dsyme** [comment]
Approved. But this should have a tracking RFC too

> @KevinRansom F# 4.3 ?

@realvictorprm It means F# 4.2 with FSharp.Core 4.4.3.0

**Comment by dsyme** [comment]
RFC is here https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1044-add-nativeptr-tobyref.md

**Pull request merged**
