### PR TITLE
Fix FSharpMemberOrFunctionOrValue.IsConstructor property for ctor definition

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/3943

### CODE REVIEW

**Comment by KevinRansom** [comment]
Nice,
Can we get a test to ensure this stays fixed pls?

**Comment by dsyme** [comment]
Agree this needs a test. Otherwise LGTM

**Comment by vasily-kirichenko** [comment]
@dsyme done.

**Comment by dsyme** [comment]
@vasily-kirichenko Lovely, thanks

**Pull request merged**
