### PR TITLE
ExportedTypes optimization

### PR DESCRIPTION
**Pull request by ncave**
Replacing the quadratic lookup with a linear one.

### CODE REVIEW

**Comment by dsyme** [comment]
@ncave Thanks, looks like an important optimization when there are lots of facades....

**Comment by vasily-kirichenko** [comment]
Any before-after measures?

**Comment by ncave** [comment]
@vasily-kirichenko No measures, as it only improves the type loading phase, and there is caching after lazy types are forced. But it does reduce the gc pressure by not allocating so many tuples.

**Comment by ncave** [comment]
Seems to be failing some tests on net462 assemblies, perhaps a small adjustment is needed, I'll take a look.

**Comment by ncave** [comment]
Ok, it works now.

**Pull request merged**
