### PR TITLE
Add more semantic highlighting

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
image

image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@dsyme Currently colorization uses sResolutions here https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L1416. In VFPT we used `GetAllUsesOfAllSymbols` https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L1880 Is using resolutions faster?

**Comment by saul** [comment]
This is fantastic - thank you

**Comment by vasily-kirichenko** [comment]
@dsyme I've failed to determine that a vref is of type `ref<_>`. Any points?

**Comment by vasily-kirichenko** [comment]
Ref cells are not highlighted as mutable vars, everything else is ready.

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
https://github.com/Microsoft/visualfsharp/pull/2348

**Pull request closed without merging**
