### PR TITLE
minimize use of state machine variables

### PR DESCRIPTION
**Pull request by dsyme**
@smoothdeveloper I think this is what is needed

ref https://github.com/Microsoft/visualfsharp/pull/5080, https://github.com/Microsoft/visualfsharp/issues/5073

Basically we collect up any free variables used in any code (excluding those up to the first emitted "label"), i.e. a "any free variables not on the synchronous path".

If a variable is not in this set, then it can be represented as a local.

### CODE REVIEW

**Comment by dsyme** [comment]
CodeGen baselines need updating:
```
+++ CodeGen\EmittedIL\GeneratedIterators (GenIter01.fs -) +++
+++ CodeGen\EmittedIL\GeneratedIterators (GenIter02.fs -) +++
+++ CodeGen\EmittedIL\GeneratedIterators (GenIter03.fs -) +++
+++ CodeGen\EmittedIL\GeneratedIterators (GenIter04.fs -) +++
+++ CodeGen\EmittedIL\ListExpressionStepping (ListExpressionSteppingTest4.fs -) +++
+++ CodeGen\EmittedIL\ListExpressionStepping (ListExpressionSteppingTest5.fs -) +++
+++ CodeGen\EmittedIL\ListExpressionStepping (ListExpressionSteppingTest6.fs -) +++
+++ CodeGen\EmittedIL\QueryExpressionStepping (Linq101Aggregates01.fs - CodeGen) +++
+++ CodeGen\EmittedIL\QueryExpressionStepping (Linq101ElementOperators01.fs - CodeGen) +++
+++ CodeGen\EmittedIL\QueryExpressionStepping (Linq101Ordering01.fs - CodeGen) +++
+++ CodeGen\EmittedIL\QueryExpressionStepping (Linq101Partitioning01.fs - CodeGen) +++
+++ CodeGen\EmittedIL\QueryExpressionStepping (Linq101Quantifiers01.fs - CodeGen) +++
+++ CodeGen\EmittedIL\QueryExpressionStepping (Linq101Select01.fs - CodeGen) +++
+++ CodeGen\EmittedIL\QueryExpressionStepping (Linq101SetOperators01.fs - CodeGen) +++
+++ CodeGen\EmittedIL\QueryExpressionStepping (Linq101Where01.fs - CodeGen) +++
+++ CodeGen\EmittedIL\SeqExpressionStepping (SeqExpressionSteppingTest4.fs -) +++
+++ CodeGen\EmittedIL\SeqExpressionStepping (SeqExpressionSteppingTest5.fs -) +++
+++ CodeGen\EmittedIL\SeqExpressionStepping (SeqExpressionSteppingTest6.fs -) +++
+++ CodeGen\EmittedIL\SeqExpressionStepping (SeqExpressionSteppingTest7.fs -) +++
```

**Comment by dsyme** [comment]
This is ready, the existing codegen tests are good enough to show the fields disappearing and code size reducing (hence the 800 lines removed in the IL diffs)

**Comment by forki** [comment]
Is this part of optimizer or IL generation? I wonder if it applies to fable as well.

**Comment by smoothdeveloper** [comment]
@forki this is called from IlxGen under GenExpr so I guess it won't change for fable.

**Comment by forki** [comment]
Got it. Thx

Gauthier Segay <notifications@github.com> schrieb am Mi., 6. Juni 2018,
10:59:

**Comment by dsyme** [comment]
> Is this part of optimizer or IL generation? I wonder if it applies to fable as well.
> 
> @forki this is called from IlxGen under GenExpr so I guess it won't change for fable.

I think we could optionally expose state machine implementations in the assembly contents revealed by FCS.  This would not be much harder than calling `LowerSeqExpr` in `Exprs.fs` (cc @ncave)

However the compiled form of state machines uses `Expr.Op(TOp.Label ...)` expressions that indicate entry points into the state machine and the entry code of `MoveNext` jumps to one of the entry points depending on the current state.  I don't think this can be expressed in Javascript in a nice way though perhaps [this](https://stackoverflow.com/questions/9751207/how-can-i-use-goto-in-javascript?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) indicates it can actually be done.

**Comment by cartermp** [comment]
Just clarifying that from a tracking perspective this is addressing #5073 and is slated for dev16.

**Comment by dsyme** [comment]
This is ready

**Pull request merged**
