### PR TITLE
Remove FSharp.Data.TypeProviders from build (moved to http://fsprojects.github.io/FSharp.Data.TypeProviders/)

### PR DESCRIPTION
**Pull request by dsyme**
With FSharp.Data.TypeProviders frozen at version 4.3.0.0, the community-managed project [FSharp.Data.TypeProviders](http://github.com/fsprojects/FSharp.Data.TypeProviders/) gives a place where the F# community to take this set of generative type providers forward.

Purely out of interest I took a look at what it would take to remove all remnants of FSharp.Data.TypeProviders.dll from this tree. This includes the item templates and any tests that use this component (there aren't many of those)

I'm not sure if this is what we would actually want to do: 
the Visual F# Tools would likely continue to ship with binary 4.3.0.0 for backwards compatibility purposes and that may mean that 4.3.0.0 continues to need to be built from this repo (to avoid checking in binary components that can't be rebuilt?)  

Anyway, this is what it would look like.  Please let me know if you'd like to pursue this otherwise I'll close in a couple of weeks.

### CODE REVIEW

**Comment by forki** [comment]
Instead of committing the binaries from the community repo we could just use nuget during the build here.

**Comment by enricosada** [comment]
:+1: for @forki, pls
we already download other packages at build time ( nunit, etc ), just add it in [$root/packages.config](https://github.com/Microsoft/visualfsharp/blob/master/packages.config).

**Comment by dsyme** [comment]
> Instead of committing the binaries from the community repo we could just use nuget during the build here.

Yes, it's possible. However to be clear I don't think Microsoft are planning to ship anything beyond 4.3.0.0 as part of the Visual F# Tools install itself. If we could somehow deprecate the use of 4.3.0.0 and point people to the nuget package in a warning message that would be great, though I don't know any specific way of doing that easily.

**Comment by enricosada** [comment]
well everyone use nuget these days. If f# doesnt install the assembly in gac anymore, we can just add the info to changelog ( in a breaking change section )

**Comment by dsyme** [comment]
> well everyone use nuget these days. 

This is not strictly true - onsite in customer locations I've seen Visual F# used without any internet connection to nuget.org, or only a particularly locked down set of packages are available.  I assume this is happening less and less though of course, but it's a scenario Microsoft must consider across the board since it's the sort of thing that some enterprise/government customers do.

> If f# doesnt install the assembly in gac anymore, we can just add the info to changelog ( in a breaking change section )

Just to be clear, this is not about the GAC - FSharp.Data.TypeProviders.dll has never been installed to the GAC.  It is, however, installed to ``Reference Assemblies``, specifically at

    C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers

On install, a registry entry pointing to this location is added to ``AssemblyFolders``. This makes this DLL appear in the list of available assemblies in Visual Studio, and also makes ``#r "FSharp.Data.TypeProviders.dll"`` work without a qualified path in a script (F# Interactive invokes MSBuild to resolve the assembly).  Both of these are lost when using the nuget package - which is OK but something to be aware of w.r.t. breaking change.

**Comment by enricosada** [comment]
i say gac like `c:\program files\Assemblies\etc`, a shared location by user/machine, and added to fsc/fsi includeDir to search for assemblies.

These can anyway copied there, the visualfsharp 4.1 bundle should use the latest stable and tests FSharp.Data.TypeProviders nuget (if ms want to bundle that assembly, dont know)

#### About warning

@dsyme i think **we can add an additional warning if "FSharp.Data.TypeProviders" is not found** (not only the usual assembly not found) saying

```FSharp.Data.TypeProviders is not distribuited anymore, get it from nuget or other method``

it's an if by assembly name, ok, but not too bad. 
And remove it next major version

> connection to nuget.org, or only a particularly locked down set of packages are available

locked down packages are ok (or internal nuget server).
No packages it's becoming really difficult to do

**Comment by dsyme** [comment]
Updated after the big header change

**Comment by dsyme** [comment]
I've updated this after recent changes in master.  I think we should consider just pushing the button on this given that http://fsprojects.github.io/FSharp.Data.TypeProviders/ is available.

**Comment by enricosada** [comment]
:+1: good, less code

**Comment by KevinRansom** [comment]
Just reactivated this, it broke a bunch of tests.

**Comment by dsyme** [comment]
@KevinRansom Yep, though looks like it is some problem with the build scripts, I'll take a look 

From https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.1820 the portable7 DLLs are no longer building:

```
[00:08:46] Could not load file or assembly 'file:///C:\projects\visualfsharp-radou\release\portable7\bin\FSharp.Core.Unittests.dll' or one of its dependencies. The system cannot find the file specified.
```

**Comment by dsyme** [comment]
@KevinRansom Very strange, I get the same error on "master".

**Comment by dsyme** [comment]
I nudged the master branch CI build here: https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.1827

**Comment by KevinRansom** [comment]
That passed quite nicely.

**Comment by dsyme** [comment]
Yep. Problem was the build wasn't failing when the ``build-everything.proj`` failed. https://github.com/Microsoft/visualfsharp/pull/1073/commits/d5b971d17821b985af2fe7ba66a788bb7596c0af so error was hard to see

**Pull request merged**
