### PR TITLE
Numbers with underscores cause compilation error sometimes

### LINKED ISSUE #2701: Numbers with underscores cause compilation error sometimes
image

I cannot reproduce it with code like:
```fsharp
[1..5] |> List.mapi (fun i n -> sprintf "%06d" (n + 1_000_000));;
```

### PR DESCRIPTION
**Pull request by forki**
fixes #2701

/cc @AviAvni

### CODE REVIEW

**Comment by AviAvni** [comment]
@forki thanks sorry for the missing need to add tests in https://github.com/Microsoft/visualfsharp/blob/master/tests/fsharpqa/Source/Conformance/BasicGrammarElements/Constants/BasicConstants.fs

**Comment by forki** [comment]
Could you please send a pull request to my fork? Or just add another pull
request to the main fork and merge my stuff. Thanks

Am 26.03.2017 3:42 nachm. schrieb "Avi Avni" <notifications@github.com>:

**Comment by AviAvni** [comment]
@forki I'll send PR with tests later

**Comment by AviAvni** [comment]
@forki @KevinRansom @dsyme 
After I checked it when I implemented this feature I added this https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L2523
but in the compilation of FSharp.Editing it uses the proto compiler and in ilSpy the FSharp.Core in the proto binary don't have this change

**Comment by forki** [comment]
@aviavni yes it seems it's only happening in proto

**Comment by AviAvni** [comment]
@forki so no need tests if they fix this proto thing all be ok if they want this to be implemented in the lexer and not dependent in the FSharp.Core they can merge this PR

**Comment by forki** [comment]
The thing is: we need to fix it in order to have it available in fsharp
itself. But good to know that other projects are not broken. So it's not
that urgent

Am 26.03.2017 7:50 nachm. schrieb "Avi Avni" <notifications@github.com>:

@forki <https://github.com/forki> so no need tests if they fix this proto
thing all be ok if they want this to be implemented in the lexer and not
dependent in the FSharp.Core they can merge this PR

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/pull/2702#issuecomment-289301897>,
or mute the thread

**Comment by KevinRansom** [comment]
@forki 
Thank you for this .

**Pull request merged**
