### PR TITLE
Do not provide completion after '

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/3901

### CODE REVIEW

**Comment by cartermp** [comment]
@KevinRansom I can't test this on 15.5 Preview 2: 

not-found-sci

I think the language service is uninitialized as well, because F# files are just plaintext.  Was there a recent change which made this so?

**Comment by KevinRansom** [comment]
@cartermp I would have expected the plain text on VS2017.4 per this issue: https://github.com/Microsoft/visualfsharp/issues/3900

However, VS2017.5 preview 3 should work fine.

**Comment by cartermp** [comment]
This is in Preview 3.

**Comment by vasily-kirichenko** [comment]
Master does not work on 15.5 pre 3 :)

**Comment by KevinRansom** [comment]
@vasily-kirichenko  Thanks for this.

Kevin

**Pull request merged**
