### PR TITLE
Remove branch specific jobs names

### PR DESCRIPTION
**Pull request by mmitche**
The branch info is encoded in the folder in Jenkins.

/cc @otawfik-ms

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by otawfik-ms** [comment]
@mmitche if we merge this, how can we reference specific branches in build? example: build status badges?

**Comment by mmitche** [comment]
Yep, so you merge it, and then the jobs will appear here:

http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/master/

You may click on a job and grab the build status badge link on the left side, for instance, here is the page of badge links for the generator:

http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/master/job/generator/badge/

**Comment by mmitche** [comment]
@otawfik-ms You'll need to integrate this into the vs2015 branch to get the updated netci there, since that is where the vs2015 job definition lies now.

**Comment by otawfik-ms** [comment]
@mmitche I'll leave the badge empty then until the integration happens. Thanks for the heads up!

**Comment by mmitche** [comment]
And coreclr :)

**Pull request merged**
