### PR TITLE
Signature help for VS2017

### PR DESCRIPTION
**Pull request by dsyme**
This implements signature help (method overload tips and parameter info). https://github.com/Microsoft/visualfsharp/issues/1767. Also fixes https://github.com/Microsoft/visualfsharp/issues/1856

This is mostly just wiring up the necessary things and copying across some of the nitty-gritty detail from the old language service.  Some additional information was propagated such as HasParamArrayArg.

We already have lots of unit tests, but just below the level being exercised here.  I will endeavor to add at least one smoke test at this level.

Here's a screen capture showing parity with VS2015

capture

### CODE REVIEW

**Comment by cartermp** [comment]
Fantastic

**Comment by dsyme** [comment]
I've now added some not-completely-trivial testing for this, see https://github.com/Microsoft/visualfsharp/pull/1855/files#diff-b9b8a5c1cfbb79988bfa13d92ce02993R61

I believe that suffices for smoke testing at this point

**Comment by dsyme** [comment]
This is ready to go in, once CI is green.

**Comment by dsyme** [comment]
@vasily-kirichenko @forki Please review this? thanks

**Comment by forki** [comment]
Why is it changing the parser?

**Comment by dsyme** [comment]
> Why is it changing the parser?

It gives accurate method info when pressing ``=`` at

    type T = SomeTypeProvider<NamedArgument=

Tests added at https://github.com/Microsoft/visualfsharp/pull/1855/commits/6796ead80ead6547daad2744cb231d06bfbbcfa6

**Comment by vasily-kirichenko** [comment]
Found a bug:

```fsharp
let _ = System.DateTime
```
Note that this line is _the last line in the file, there are no, even empty, lines below it.
Now type an open paren and you'll see this assertion:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unexpected exception seen in language service

System.ArgumentException: 'end' must not be less than 'start'

Parameter name: end

   at Microsoft.CodeAnalysis.Text.LinePositionSpan..ctor(LinePosition start, LinePosition end)

   at <StartupCode$FSharp-Editor>.$SignatureHelp.ProvideMethodsAsyncAux@70-2.Invoke(FSharpMethodGroup _arg2)

   at Microsoft.FSharp.Control.AsyncBuilderImpl.cont@825.Invoke(a a)

   at Microsoft.VisualStudio.FSharp.LanguageService.Assert.Exception(Exception e)

   at <StartupCode$FSharp-Editor>.$SignatureHelp.Microsoft-CodeAnalysis-SignatureHelp-ISignatureHelpProvider-GetItemsAsync@190-5.Invoke(Exception _arg8)

   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)

   at <StartupCode$FSharp-Core>.$Control.loop@428-38.Invoke(FSharpFunc`2 action)

   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)

   at Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)

   at <StartupCode$FSharp-Core>.$Control.-ctor@511-1.Invoke(Object state)

   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


---------------------------
Abort   Retry   Ignore   
---------------------------
```
No signature help apper.

**Comment by dsyme** [comment]
Great, thank you

**Comment by dsyme** [comment]
@vasily-kirichenko Fix for that test case is included, also fix for the GTD bug. And test cases for both

**Pull request merged**
