### PR TITLE
Custom operations are at the top of completion list & remove active pattern values from the list

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/4829

image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
It also fixes #4832 

image

(VS NUnit 3 Test Adapter is unable to discover any test, so I cannot run the new tests locally, chances are they will fail on CI).

**Comment by forki** [comment]
That's great news vasily. Hope to see it in FCS soon since we are about to
do a lot of Saturn soon.

Vasily Kirichenko <notifications@github.com> schrieb am Sa., 5. Mai 2018,
10:11:

**Comment by vasily-kirichenko** [comment]
@forki To move custom operations to the top of completion list in Ionide, it must sort items by kind itself (in FSAC, I think). This PR expose `CustomOpation` kind for items, but the sorting is done in FSharp.Editor, which is not a part of FCS and works in VS only.

**Comment by forki** [comment]
Ok thanks. Paging @Krzysztof-Cieslak who is conveniently in charge of
ionide and Saturn ;-)

Vasily Kirichenko <notifications@github.com> schrieb am Sa., 5. Mai 2018,
10:31:

**Comment by cartermp** [comment]
> VS NUnit 3 Test Adapter is unable to discover any test, so I cannot run the new tests locally, chances are they will fail on CI

Nope 😄

**Comment by cartermp** [comment]
Testing this out right now. I have two thoughts, neither of which are related to the PR:

1. Interesting that `CompletionItemKind` doesn't have a notion of a local, which you may want at the top of the completion list under some circumstances. But the placement of the priority makes sense to me given what exists.
2. _WOOF_, while we're here can we just make `bestAlmostIncludedSoFar` a mutable value instead of the ref cell? Pretty sure @dsyme wouldn't mind that change even if it's not this PR directly...

**Comment by cartermp** [comment]
Hmmm, building this PR against master on 15.7 results in #4832 and #4829 are still there. Maybe I just screwed up installing the VSIX into VS because I'm tired, but the version is 42.42.42.42 and your commits are in the log on the branch I built off of...

**Comment by vasily-kirichenko** [comment]
@cartermp I confirm the sorting does not work on Saturn's `application` CE, however it does work on `query` CE.

**Comment by vasily-kirichenko** [comment]
Ah, wait, the solution did not compile successfully, so it may be the outdated vsix.

**Comment by vasily-kirichenko** [comment]
The fix for #4832 was wrong. It turns out for the following code
```fsharp
let _ = 
  query {
    for i in 1..10 do
    <* cursor *>
  }
```
at the cursor position there is no name resolution environment for the entire CE, and the "smart" algorithm of `GetBestEnvForPos` picks the first lhs one, which spreads from `{` to `do` and has `eIsComputationExpression` set to `true`. My fix was to _not_ pick such nenvs specifically, to avoid polluting completion list with custom operations outside of the last CE. It results with no custom operations at cursor position above. So, I've reverted the fix and left only the sorting stuff.

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by vasily-kirichenko** [comment]
I also remove active patterns (as values) from completion list altogether.

Before

image

After

image

**Comment by cartermp** [comment]
@TIHan / @KevinRansom / @brettfo / @Pilchie we should consider this for 15.8 P4

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot no longer works :-(   so closing and reopen is the way until we get a new way.

**Comment by KevinRansom** [comment]
@vasily-kirichenko thanks for this mate.  Nice work.

Kevin

**Comment by Krzysztof-Cieslak** [comment]
❤️

**Pull request merged**
