### PR TITLE
Defer getting all entities as much as possible

### PR DESCRIPTION
**Pull request by dungpa**
This is a simple change to ensure that getting all entities (the most expensive operation) is only called if the symbol under cursor is valid.

/cc @vasily-kirichenko

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
I'm not sure it's neede because this code fix is activated on 039 error only.

**Comment by dungpa** [comment]
Ok, it might be needed if you extend to more error codes. I'm closing the PR then.

**Comment by forki** [comment]
Please don't close. It still looks sane.

**Comment by vasily-kirichenko** [comment]
Yes, it looks OK.

However, I was thinking about the opposite thing: loading entities from all assemblies in background to make the light bulb appear immediately the first time.

**Comment by KevinRansom** [comment]
@dungpa 
It's still a good change mate. Maybe aa future PR will improve it more ... but until then we think this is great.

Kevin

**Pull request merged**
