### PR TITLE
Suggest a function to implement if no abstract method matches

### PR DESCRIPTION
**Pull request by forki**
while working on #1229 I found this would be useful:

image

### CODE REVIEW

**Comment by isaacabraham** [comment]
Link to #1232

**Comment by forki** [comment]
One of the existing tests showed an interesting case. Here we don't have an implementation slot since the method is already implemented. I tried to improve the message for this case as well:

image

**Comment by forki** [comment]
I think this one is ready for review

**Comment by KevinRansom** [comment]
How about a small change to the Message:
````  The type Foo contains the member 'MyX' but it is not a virtual or abstract method that is available to override or implement.
Available methods to override or implement:
   Equals
   ...

**Comment by forki** [comment]
@KevinRansom I'd like to keep the "Maybe you want" part consistent. This allows emacs users to grep and use this as poor man's IntelliSense. 
That said: we should probably improve the concrete wording in that part.

**Comment by KevinRansom** [comment]
@forki "Maybe you want" is usually a question rather than a statement and so there should be a question mark there somewhere.  That is why I think "Available methods to override or implement:"  is preferable.

**Comment by forki** [comment]
Yep I agree. Current formulation is suboptimal. But I'd like to have the
same sentence for all of these suggestions. So I hope we can find one that
is better than the current and still works everywhere. (as said above this
might allow some tools to actually make sense out of this)

**Comment by TeaDrivenDev** [comment]
"You may want"?

**Comment by dsyme** [comment]
Thanks again @forki and @isaacabraham

**Pull request merged**
