### PR TITLE
Dedupe module names in fsi

### PR DESCRIPTION
**Pull request by forki**
Extension to #2772

### CODE REVIEW

**Comment by forki** [comment]
ci_part2 - agent went offline (unrelated)

**Comment by KevinRansom** [comment]
@dotnet-bot test Windows_NT Release_ci_part2 Build please

**Comment by dsyme** [comment]
LGTM. Needs a test pleae, thanks :)

**Comment by forki** [comment]
nope - it's not clear if it's good.

**Comment by dsyme** [comment]
@forki OK :)

**Comment by forki** [comment]
I in the paket PR I found a different solution

**Pull request closed without merging**
