### PR TITLE
Anonymous record support for expressions in FCS

### PR DESCRIPTION
**Pull request by dsyme**
Testing to follow

### CODE REVIEW

**Comment by dsyme** [comment]
Tests added, this is now ready.  It wasn't  hard change

**Comment by dsyme** [comment]
I've enabled `ExprTests.fs` in VisualFSharp.Unittests.dll - that was disabled for some reason - we should find out why from test failures

**Comment by dsyme** [comment]
FCS docs also updated

**Comment by cartermp** [comment]
Linking #6189

**Comment by dsyme** [comment]
OK this is ready

**Comment by cartermp** [comment]
@alfonsogarciacaro Does this look good enough? I imagine so, since Fable code just works off of the types that have been adjusted.

**Comment by baronfel** [comment]
Once this gets merged I can do a merge+release of FCS to support Fable.

**Comment by dsyme** [comment]
@cartermp I think it's all the info we're able to give :-)

**Comment by alfonsogarciacaro** [comment]
[Fable REPL](https://fable.io/repl/#?code=DYUwLgBAtghg1iAggOwPbIEogMYAoCUEAvAFATkQDeAPhABrEQCsA3BAJqMBEAYqqlzY9GAMwCuyCAA8IATwgBaAHzSIAajkRqAXxJ7QkAE6NYCFOix58JAA6GAlsjAiIXACohgwaCAgBSAGd-ewgweygQAK4IQwA6Tlw44TiGAGZrIA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLslRfXVYGOiQAd3EwujQwEFYzAAYE8RAkOgBzcFYANiTLa09vXyslJxd4RBVIWDggA&css=Q) (Try a hard reload to clear the browser cache if it doesn't work) 😸

**Pull request merged**
