### PR TITLE
update nuget.exe to 4.5.1.4879

### PR DESCRIPTION
**Pull request by dsyme**
We need an updated nuget.exe if we want to use it to push packages

### CODE REVIEW

**Comment by dsyme** [comment]
@dotnet-bot test this please

**Comment by dsyme** [comment]
@brettfo @KevinRansom We should do this update at some point, but it currently fails with this.  I think we can do this update after the final project.json files have been removed

```
   Invalid input 'project.json'. Provide the path of an msbuild solution file instead. Support for XProj and standalone project.json files has been removed, to continue working with legacy projects use NuGet 3.5.x from https://nuget.org/downloads
D:\j\w\release_ci_pa---3f142ccc\Tools\packageresolve.targets(35,5): error MSB3073: The command ""D:\j\w\release_ci_pa---3f142ccc\src\fsharp\Fsc\..\..\..\.nuget\NuGet.exe" restore -OutputDirectory "D:\j\w\release_ci_pa---3f142ccc\packages" -Config "D:\j\w\release_ci_pa---3f142ccc\src\fsharp\Fsc\..\..\..\.nuget\..\NuGet.Config" "D:\j\w\release_ci_pa---3f142ccc\src\fsharp\Fsc/project.json"" exited with code 1. [D:\j\w\release_ci_pa---3f142ccc\src\fsharp\Fsc\Fsc.fsproj]
```

**Comment by dsyme** [comment]
@brettfo Actually looks like we might just have `project.json` files still lying around the tree unnecessarily? can we remove them, e.g. in src/fsharp/Fsc?

**Comment by brettfo** [comment]
The ones under src/fsharp are still necessary, but that's what I'm currently working on; updating everything under src/fsharp to be SDK-based.  It's not yet ready, but I'm hoping to send this out for review sometime this week.  Spoiler alert, it's a net removal of 13k lines of XML.

https://github.com/Microsoft/visualfsharp/compare/master...brettfo:fsc-sdk-2

**Pull request closed without merging**
