### PR TITLE
Suggestions for misspelled values, namespaces, attributes, functions and more - fixes #1909

### LINKED ISSUE #1909: Suggestions for mispelled values are not applied against simple values.
The following code provides a valid suggestion: -
```fsharp
type Foo = { Name : string }
let bar = { Nam = "Isaac" }
```

However the following does not: -

```fsharp
let name = "Isaac"
let fullName = nam + " Abraham"
```

I would like the compiler to apply the same suggestions whenever any symbols cannot be identified.

### PR DESCRIPTION
**Pull request by forki**
image

### CODE REVIEW

**Comment by forki** [comment]
image

**Comment by forki** [comment]
I'm making good progress here, but this is also dependend on @rickasaurus's jaro-winkler impl. So please don't merge yet.

**Comment by forki** [comment]
@dsyme @KevinRansom the CI on jenkins is borked again

**Comment by forki** [comment]
since #1945 is merged, this is ready for review.
It's already enabling suggestions in many many new places and I intend to keep working on int in new Pull Requests. But I think this is already very useful and I'd like to see it in.

**Comment by dsyme** [comment]
@forki I think the new messages look a bit odd in VIsual Studio.  When --vserrors is on, I think they should not be formatted multi-line but rather "Perhaps you mean aaa, bbbb, ccc"
capture16

**Comment by forki** [comment]
Mhm. We could do that, but they they like look weird in onmouseover, right? 

@k_cieslak I guess for your smart tag feature it's not important, right?

**Comment by forki** [comment]
Can we detect where we are displayed? how?

**Comment by dsyme** [comment]
@forki Yes, Visual Studio passes the ``--vserrors`` option, you can track that through

**Comment by forki** [comment]
So if I understand correctly, you want me to format selectively. Should I
do that as part of this PR?

Am 08.12.2016 16:33 schrieb "Don Syme" <notifications@github.com>:

**Comment by dsyme** [comment]
@forki Yes, I think so.  @cartermp may want to give a more authoritative POV

I don't mind which PR, just pasted it here since I noticed while using ``bleeding-edge``

**Comment by cartermp** [comment]
I agree with this: 

> I think the new messages look a bit odd in VIsual Studio. When --vserrors is on, I think they should not be formatted multi-line but rather "Perhaps you mean aaa, bbbb, ccc"

I wish it was a bit easier to handle that only in the VS tools, but that doesn't seem to be the case?  Might be worth investigating, but if it's easier for you to format selectively @forki then I think that's the best option.

**Comment by forki** [comment]
Ok I think I found a way. Unfortunately I can't test it since I can't build for VS. @vasily-kirichenko could you please help me out here and try it in VS? 
The assumption is that suggestions should be comma separated in VS error window but error tooltips should still show suggestions with line breaks

**Comment by vasily-kirichenko** [comment]
@forki Unfortunately I will be home in 5 hours :(

**Comment by forki** [comment]
It's not time critical. We just need to make sure this thing works as
expected.

Am 10.12.2016 3:26 nachm. schrieb "Vasily Kirichenko" <
notifications@github.com>:

**Comment by forki** [comment]
I will also try to add an explicit test which uses - --vserrors, but I
think manual testing is still needed.

Am 10.12.2016 3:38 nachm. schrieb :

**Comment by vasily-kirichenko** [comment]
image

**Comment by forki** [comment]
ok thanks. will try another approach

**Comment by vasily-kirichenko** [comment]
What about the compiler output, it does not include the suggestions at all:

> 1>------ Build started: Project: Library1, Configuration: Debug Any CPU ------
1>C:\Users\vaski\OneDrive\Документы\Visual Studio 2017\Projects\Library1\Library1\Library1.fs(3,13): error FS0039: The namespace 'Collectons' is not defined
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by forki** [comment]
ok. I changed the infrastructure for this a bit and predictions are now formatted later (when we already know the error style).

**Comment by vasily-kirichenko** [comment]
@forki 
> 04:12:22 D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\vs\IncrementalBuild.fs(976,36): error FS0001: This expression was expected to have type    'unit'    but here has type    'bool -> unit' [D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\FSharp.LanguageService.Compiler\FSharp.LanguageService.Compiler.fsproj]
04:12:22   
04:12:22 D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\vs\IncrementalBuild.fs(976,54): error FS0001: This expression was expected to have type    'ErrorStyle'    but here has type    'Text.StringBuilder' [D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\FSharp.LanguageService.Compiler\FSharp.LanguageService.Compiler.fsproj]
04:12:22   
04:12:22 D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\vs\IncrementalBuild.fs(976,58): error FS0001: This expression was expected to have type    'Text.StringBuilder'    but here has type    'PhasedError' [D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\FSharp.LanguageService.Compiler\FSharp.LanguageService.Compiler.fsproj]
04:12:22   
04:12:22 D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\vs\IncrementalBuild.fs(976,62): error FS0001: This expression was expected to have type    'PhasedError'    but here has type    'bool' [D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\FSharp.LanguageService.Compiler\FSharp.LanguageService.Compiler.fsproj]
04:12:22   
04:12:22 D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\vs\IncrementalBuild.fs(976,36): error FS0001: This expression was expected to have type    'unit'    but here has type    'bool -> unit' [D:\j\workspace\release_ci_pa---3f142ccc\src\fsharp\FSharp.LanguageService.Compiler\FSharp.LanguageService.Compiler.fsproj]

**Comment by vasily-kirichenko** [comment]
I've fixed the build and the behavior has not changed.

**Comment by forki** [comment]
I wonder if the vserrors flag is correctly set

**Comment by forki** [comment]
@dsyme @vasily-kirichenko  https://github.com/Microsoft/visualfsharp/pull/1911/files#diff-f0419b80c1f1fdd154720212ea7da186 shows that --vserrors flag has the right effect on the error message. But I have no idea why this does not work in VS

**Comment by forki** [comment]
@kevinransom @dsyme is it possible that the new vs2017 doesn't use --vserrors command line parameter for solution build?

**Comment by forki** [comment]
OK this is ready for review/merge. Even without --vserrors flag this is a great improvement for out error reporting.

**Comment by forki** [comment]
Ok need to fix couple of tests again.

**Comment by forki** [comment]
@dsyme together with @vasily-kirichenko I found out that this error reporting comes from the FCS and not from build with -vserrors flag

so this is influenced by FSharpErrorInfo.CreateFromException in IncrementalBuild.fs

but if we set this to VSErrors over there then both error window + tool tips are influenced

**Comment by forki** [comment]
so things went green again, but I noticed a serious perf issue. TBF it was there before and I just made it more obvious. Trying to tackle it as well.

**Comment by Rickasaurus** [comment]
You may want to try a two-round approach (usually called blocking in entity resolution circles). It's not so easy though. One good approach if you're already doing Jaro Winkler is the algorithm described in this paper: http://www.semantic-web-journal.net/content/efficient-execution-bounded-jaro-winkler-distances

I'm not sure if you're able to persist state or not though.

**Comment by forki** [comment]
To clarify: the perf issue is in the name resolution code, not in the
distance function.

Am 15.12.2016 03:04 schrieb "Rick Minerich" <notifications@github.com>:

**Comment by forki** [comment]
I rebased on master, but it looks master is red again. @KevinRansom do you know something about this?

**Comment by forki** [comment]
anyways that perf issue is fixed

**Comment by forki** [comment]
ok. now suggestions are only calculated if really needed

**Comment by forki** [comment]
@KevinRansom I rebased on master. can you please take a look? I think this one is really important to get in soon so that we have a bt of time to dogfood.

**Comment by forki** [comment]
Something weird happened @KevinRansom did you merge in wrong direction?

**Comment by forki** [comment]
ok I rebased on master. let's see if that fixed things

**Comment by KevinRansom** [comment]
I usually press squash and merge. But it looks like it went the wrong way

**Comment by forki** [comment]
Yeah I think it ran into merge conflicts. Please wait for CI and try again.

Am 16.12.2016 7:33 nachm. schrieb "Kevin Ransom (msft)" <
notifications@github.com>:

**Comment by KevinRansom** [comment]
@forki ... 
ci_part1 error is unrelated to this pr.

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by forki** [comment]
ok loogs good now

**Comment by KevinRansom** [comment]
Thanks for taking care of this

Kevin

**Pull request merged**
