### PR TITLE
update mem perf driver

### PR DESCRIPTION
**Pull request by dsyme**
@vasily-kirichenko This updates the VS memory tester to allow command-line execution.  

    .\Release\net40\bin\LanguageServiceProfiling.exe tests\scripts\tmp\FSharp.Compiler.Service SCGS "commit-number"

where "SCGS" is the script of commands. We print a single line of results to stdout and rest of output to stderr:

  commit-number    TimeDelta: 26.95    MemDelta:  500     G0:  886     G1:  740     G2:   15

The aim is to collect a single line of data to append to a log file. Maybe we do this during CI, I'm not sure, I'm currently doing it manually.

For some reason I also needed to set .NET framework to 4.6 or else I get an unresolvable message that I must install 4.6.2

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Great! I tried to use ProjectChecker to make `FSharpProjectOptions` automatically, but I failed trying to port it to the latest FCS. However, for regression testing FCS repository is just what we need.

However, just running `ParseAndCheckProject` once is not enough, it does not test caches behavior at all. More interesting:
* check project, modify a file, recheck it
* repeat ^^ a number of times, say 5, collecting memory stats after each run
* do the same for a large _file_
* do the same for a number of files (say 10)

**Comment by dsyme** [comment]
> However, just running ParseAndCheckProject once is not enough, it does not test caches behavior at all. It tests what kind of data we store in the caches, not how smart we do it. More interesting:

Yes, I'm currently just testing retained memory in cases where the caches are holding stuff.  We need scenarios that stress the caching too.    Let's keep iterating and add more scenarios

**Comment by dsyme** [comment]
@vasily-kirichenko Added an X option to flush the caches. This is useful to help cut out the effect of JITting the contents of ``FSharp.LanguageService.Compiler.dll`` itself

**Comment by dsyme** [comment]
Merging as this is updating the testing tool only, there are no changes to the core build.

**Pull request merged**
