### PR TITLE
Add Roslyn 15.1 binaries to Roslyn branch, updating to latest from master

### PR DESCRIPTION
**Pull request by otawfik-ms**
@Microsoft/fsharp-compiler @cartermp

### CODE REVIEW

**Comment by dsyme** [comment]
Hard to review because of so many changed files inn the overall merge :)

**Comment by otawfik-ms** [comment]
@dsyme It is just bringing the latest changes from master, and updating all project references to Roslyn 2.0 beta version. No code changes. I'll fix the remaining references now as some are missing from jenkins/appveyor.

**Comment by dsyme** [comment]
Ah ok :)

**Comment by forki** [comment]
I'm not really sure what the purpose of this roslyn branch is. I propose the following:

* rebase the rosyln branch on the current master using `git pull --rebase origin master`
* create a WIP PR on master with the roslyn changes
* write an abstract with the purpose and plan of the roslyn branch
* create a checklist in the description of the PR which documents status of the roslyn features
* from time to time run `git pull --rebase origin master` and `git push origin roslyn -f` to update the PR with the latest bits that are commited to master

this is basically what I do with my PRs here and what I think allows others to review the code and the progress of a feature. Thanks,

**Comment by veikkoeeva** [comment]
@forki Should that be `git pull --rebase upstream master` (while in local branch `roslyn` and assuming the origin of fork is aliased conventially as upstream)? Maybe worth considering to use `git push --force-with-lease origin +roslyn`, `git push --force-with-lease origin roslyn` or `git push origin +roslyn`.

**Comment by forki** [comment]
@veikkoeeva yes if you are using second remote called upstream, then yes.

**Comment by oamsath** [comment]
@forki the work is described in #913 in detail. Please let me know if that doesn't answer your questions.

**Comment by smoothdeveloper** [comment]
@oamsath what @forki describes would allow people to actually review the changes from github, we have seen few of those "big merge" PR related to roslyn but I'm at loss as to how to review the code changes.

Doing what @forki describes there would be a single roslyn PR based off the same https://github.com/otawfik-ms/visualfsharp/tree/roslyn branch, that branch would be rebased from time to time off https://github.com/Microsoft/visualfsharp/tree/master. At any point, someone consulting the "files" tabs of this hypothetical PR, would see only the changes related to roslyn integration, with 0 noise related to merge or catching up with master (which represents the majority of the commits that are not related to roslyn in this current PR).

**Comment by smoothdeveloper** [comment]
@forki: found how to see the roslyn changes from github: https://github.com/Microsoft/visualfsharp/compare/roslyn

**Comment by otawfik-ms** [comment]
@smoothdeveloper this is just bringing the branch up to date. No feature work is done in this PR. Features are always sent in new PRs that just contain the changes being done.

**Comment by smoothdeveloper** [comment]
@otawfik-ms thanks for the notice, since I'm contributing a bit to VFPT which has few code suggestions, it might be useful to know where those features are being worked on to take inspiration from their structure / APIs used.

Also, is there a list of considered features (even if most/some won't ship)? this would give a hint of what we can expect the new roslyn workspace to provide Visual F# with.

**Comment by otawfik-ms** [comment]
Yes. Please check issue #913.
The previous PRs I sent were #974 and #993.

**Pull request merged**
