### PR TITLE
Reworkbuild

### PR DESCRIPTION
**Pull request by KevinRansom**
This is really scary.
============

It is an experiment to make a crossplatform build for the visual fsharp repo using the dotnet/cli/msbuild combo.

This merely deletes stuff that we know we won't need.  It currently does no build and runs no tests.

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@KevinRansom wondering if the plan includes a `build.fsx`?

**Comment by forki** [comment]
@smoothdeveloper no that's never going to happen :P

**Comment by smoothdeveloper** [comment]
@forki is this why there is a big "this is really scary" title? Maintaining batch/shell scripts in parallel really is to me.

**Comment by forki** [comment]
tbf if I understand this to get rid of project.json and that's ahuge win!

**Comment by cartermp** [comment]
Yep, this is getting rid of `project.json` from the build process.

**Comment by KevinRansom** [comment]
@forki, Ohhhh it's so much more than that.  I just have no idea if what I need to achieve is actually possible.

**Pull request closed without merging**
