### PR TITLE
No property getters and setters in extended completion

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/4008

image

### CODE REVIEW

**Comment by dsyme** [comment]
Please also add a test

**Comment by vasily-kirichenko** [comment]
Completion tests do not test extended completion. I think someone from the MS team should write them. No?..

**Comment by dsyme** [comment]
> Completion tests do not test extended completion. I think someone from the MS team should write them. 

Per CONTRIBUTING.md testing should be part of the PR implementing a feature or bug fix.

It's not exactly clear what we should do when a feature gets pulled without testing or docs being added - whenever we do that we build up technical debt that gets more and more expensive to pay back the longer we leave it, since people forget what testing needs to be added. But it's better to start late rather than never:  we shouldn't increase our technical testing debt, and should leave a path to allow future contributors to contribute tests.

**Comment by vasily-kirichenko** [comment]
I absolutely agree. @TIHan, could you please add some tests for the extended completion feature? Thanks.

**Comment by dsyme** [comment]
@KevinRansom @TIHan @vasily-kirichenko  As background, it looks like https://github.com/Microsoft/visualfsharp/pull/2067 (+1601 lines) was pulled about a year ago with no unit testing added.  My impression is a fair bit of this gets checked through the tests for FSharp.Editor functionality.  

I'll leave it up to @KevinRansom and @TIHan if they want to pull this specific fix without testing. In principle a test should always be added even if no other testing is present, but I've been as guilty of both submitting and pulling fixes without tests as anyone else.

**Comment by KevinRansom** [comment]
@dsyme @vasily-kirichenko @TIHan 

This is a small change, it would be nice to have a test, but it is more like a bug fix.  It is not Will's Job to write tests for OSS contributors.  He may choose to write additional tests when trying to understand a change, but that is because he is a thorough developer.

I am fine with pulling as is, due to the nature of the change.  However, more complex PR's or ones that are more fundamental will need testing.

Kevin

**Comment by KevinRansom** [comment]
@TIHan 

Can you please open an issue an d make it up for grabs, to provide testing for this area of the IDE and we will make it up for grabs.

Thanks 
Kevin

**Pull request merged**
