### PR TITLE
Enable Symplify Name analyzer

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
It should not be merged until https://github.com/Microsoft/visualfsharp/pull/2805 is merged and I added a setting to turn this analyzer off.

### CODE REVIEW

**Comment by cartermp** [comment]
Nice one - glad the slicing stuff was simple to fix.  Are you still concerned with performance now, or do you think it's better since the perf changes to FCS?

**Comment by vasily-kirichenko** [comment]
@cartermp I think the perf is the same as before. I cannot see a way to make it faster, but it's totally usable on non-huge files, so I think we should add a setting (see above) and turn it on by default, because most people don't deal with 10K+ files normally.

**Comment by cartermp** [comment]
Agreed.  I think we can turn it on and see what people think.  Plus thanks to @majocha it'll be easy to configure soon 😄

**Comment by vasily-kirichenko** [comment]
I added an option page for Code Fixes:

image

and make Simplify Name analyzer respect it.

Now this PR is ready.

**Comment by KevinRansom** [comment]
@vasily-kirichenko 

nice,

Thanks

Kevin

**Pull request merged**
