### PR TITLE
Correct writeXmlDoc.addMembers

### LINKED ISSUE #148: XML Doc comment generation adding empty garbage
Opened on [CodePlex](https://visualfsharp.codeplex.com/workitem/161) by [ReedCopsey](https://www.codeplex.com/site/users/view/ReedCopsey)

Given the latest 3.1.2 builds, the XML Documentation generated by the F# compiler is adding numerous extra "empty" entries, such as:
```
<doc>
<assembly><name>FSharp.Core</name></assembly>
<members>
<member name="">
</member>
<member name="">
</member>
<member name="">
</member>
<member name="">
</member>
<member name="">
</member>
<member name="">
</member>
<member name="T:Microsoft.BuildSettings.BuildDetails">
</member>
```
This causes some utilities that parse these files to have serious errors, such as the  build scripts to generate documentation included in the ProjectScaffolding project..

>comments
>latkin wrote Oct 22, 2014 at 6:50 PM [x] 
>Do you know if this is a new behavior in 3.1.2? Or has it been present for other releases?
>>ReedCopsey wrote Oct 22, 2014 at 7:25 PM [x] 
>>Not sure. Suspect it's relatively new, as those build scripts only recently started failing. Will try to narrow down when this occured originally, but it seems wrong in any case...
>>>latkin wrote Nov 25, 2014 at 5:17 PM [x] 
>>>Any update on this one? Do you have a repro solution so that we can check if this is a new behavior or longstanding issue?

### PR DESCRIPTION
**Pull request by ReedCopsey**
Prevent members from being added to the global member list when the
xmlDoc contains no content.

Fixes #148

### CODE REVIEW

**Comment by latkin** [comment]
Can you add a quick test under `tests\fsharpqa\Source\XmlDoc\Basic`? Just to make sure garbage elements are no longer generated.

**Comment by ReedCopsey** [comment]
@latkin Done.  New xmlDoc005.fs test checks to make sure that names are generated for "Class1" but that there are no empty member names.  This fails in current build, passes after this fix.

**Comment by latkin** [comment]
Some of the existing XMLDoc tests (under XmlDoc\UnitOfMeasure) are now failing due to the change. Can you take a look and see if the tests need updating to match new (correct) behavior, or if there is some regression?

**Comment by enricosada** [comment]
:+1: great

**Comment by ReedCopsey** [comment]
@latkin Corrected those tests. Sorry I missed that the first round.  This update should correct those tests to match the new, better generated content.

In general, these tests are fairly brittle.  They're all based on specific ordering of the XML (which, actually, is kind of backwards now, though fixing would break most of the tests again.)  It might make sense, in the longer run, to revisit how they're setup and run.

**Pull request closed without merging**
