### PR TITLE
Update Nuget package versions.  and compiler tools version

### PR DESCRIPTION
**Pull request by KevinRansom**
Compiler nuget pkg version / tools version :  **10.2.1**
FSharp nuget pkg version: **4.5.1**

### CODE REVIEW

**Comment by cartermp** [comment]
test Ubuntu16.04 Release_default Build

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Comment by KevinRansom** [comment]
@cartermp :  This just gets us in a position to ship new nuget packages.  For sure we won't actually do that until the ref scoping PR is pulled:  https://github.com/Microsoft/visualfsharp/pull/5240

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Comment by KevinRansom** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Pull request merged**
