### PR TITLE
Create Alt+Enter Keybinding only in the context of F# Editors

### LINKED ISSUE #1797: Make F#'s Alt-Enter keybinding local to F# files only
Currently F# registers it's Alt-Enter keybinding in the context of all text editors regardless of the language. From [source](https://github.com/Microsoft/visualfsharp/blob/6afc4f9776a5dba903ca6b11965a206fb8bc23d8/vsintegration/src/FSharp.VS.FSI/fsiCommands.vsct#L220-L225):

```XML
<!-- ALT-ENTER is used for the SendToInteractive command.
         ALT-ENTER is globally bound to Diagram.Property.
         Here we bind it in the Editor context of the standard TextEditor.
         Ideally, we would bind it for F# only editor.
    -->
<KeyBinding guid ="guidVSStd11" id ="cmdidExecuteSelectionInInteractive" editor="GUID_TextEditorFactory" key1="VK_RETURN" mod1="Alt"  />
```

This has worked so long as no other language services were interested in this key combination. However now C++ and C# are interested in using this keybinding. In Visual Studio 2017 RC, F#'s keybinding is being overriden by users who have the Visual C# or Visual C++ profiles selected in 
`Tools > Options > Environment > Keyboard`.

We can solve this by declaring an F# [`EditorFactory`](https://msdn.microsoft.com/en-us/library/bb166453.aspx) that is called every time an F# file (.fs or .fsx) is opened in Visual Studio. At this point, the editor factory would set the keybindings and they would appropriately live only in the context of F# files.

If this is OK with you guys, I will implement it and submit a PR after I've tested against various filetypes.

### PR DESCRIPTION
**Pull request by JoshVarty**
This fixes #1797 

The goal here is to give commands bound to the F# Editor Factory priority over the normal text editor commands. 

The shell uses [`IVsMonitorSelection`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsmonitorselection.aspx) to maintain its array of active key binding  scopes. The array is fixed in size and contains 5 slots.  In order of precedence they are:
 
1: Active Document’s CmdUI Guid 
2: Active WindowFrame’s CmdUI Guid
3: Active WindowFrame’s EditorType Guid 
4: Active WndowFrame’s InheritKeyBindings Guid
5: The Global scope.

The `cmdidExecuteSelectionInInteractive` keybinding is now tied to the context of the F# Editor Factory. The corresponding scope for this is `3: Active WindowFrame’s EditorType Guid.`

The `TextViewCreationListener` allows us to inherit the standard text editor commands at a lower priority than our F# Editor Factory commands. The corresponding scope for this is `4: Active WndowFrame’s InheritKeyBindings Guid`

Now that I know I have a working solution I have a couple questions:

 - Would you guys rather I re-implement this in F#?
 - Is everything in the proper place? I had to introduce a new Constants file which feels wrong.
 - Anything in particular you'd like me to document more clearly?

/cc @ryanmolden @olegtk

**Note:** This also requires a change to the Alt+Enter bindings in Visual Studio. So the fix won't be apparent until the next update to Visual Studio 2017 RC.

### CODE REVIEW

**Comment by KevinRansom** [comment]
I have no problem with it in C#.

Thanks for doing this Josh

**Comment by KevinRansom** [comment]
@JoshVarty ..
````
"D:\j\workspace\release_ci_pa---3f142ccc\build-everything.proj" (default target) (1) ->
"D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\src\FSharp.ProjectSystem.Base\Project\ProjectSystem.Base.csproj" (Build target) (16) ->
(CoreCompile target) -> 
  FSharpEditorFactory.cs(43,47): error CS1525: Invalid expression term 'throw' [D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\src\FSharp.ProjectSystem.Base\Project\ProjectSystem.Base.csproj]

    7 Warning(s)
    1 Error(s)

````

**Comment by JoshVarty** [comment]
Interesting, that build server doesn't like C# 7 (throw expressions). :)

I'll fix that.

**Comment by KevinRansom** [comment]
Much scarier error now:

It fails to load the language service for every test:

I wonder if nameof(Foo) when Foo is null is expected to work?

````
Errors and Failures

1) TearDown Error : Tests.LanguageService.AutoCompletion.UsingMSBuild
System.TypeInitializationException : The type initializer for '<StartupCode$VisualFSharp-Salsa>.$VsMocks' threw an exception.
  ----> System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at Salsa.VsMocks.get_vsTrackProjectDocuments2()
   at Salsa.VsMocks.MakeMockServiceProviderAndConfigChangeNotifierNoTargetFrameworkAssembliesService[a]() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\Salsa\VsMocks.fs:line 1528
   at Salsa.VsMocks.MakeMockServiceProviderAndConfigChangeNotifier40[a]() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\Salsa\VsMocks.fs:line 1559
   at Salsa.Salsa.CreateSimple(VsOps ops) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\Salsa\Salsa.fs:line 1511
   at Salsa.Salsa.MSBuildTestFlavor.Salsa-Salsa-VsOps-CreateVisualStudio() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\Salsa\Salsa.fs:line 1528
   at UnitTests.TestLib.LanguageService.LanguageServiceBaseTests.Init() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\TestLib.LanguageService.fs:line 389
--ReflectionTypeLoadException
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(Type type, Type metadataViewType, String contractName, ImportCardinality cardinality)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[T](String contractName, ImportCardinality cardinality)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[T](String contractName)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[T]()
   at <StartupCode$VisualFSharp-Salsa>.$VsMocks..cctor() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\Salsa\VsMocks.fs:line 1651
--TearDown
   at UnitTests.TestLib.LanguageService.LanguageServiceBaseTests.Cleanup() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\TestLib.LanguageService.fs:line 405


````

**Comment by JoshVarty** [comment]
>I wonder if nameof(Foo) when Foo is null is expected to work?

Yeah it should work fine as [it's turned into a string at compile-time](http://tryroslyn.azurewebsites.net/#b:features-throwexpr/f:r/K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmFK5bgG4B7MABMYAWSqQAFAEpmrdsqXK2EmRGBEicnMoC+qmMc4lyvfuWFjJMxiCHpUAeQIArBSzXt6QiI5EqAB0AOoATmBoADKQqJpUzkIAZjKOzm6eesZGBkA==).

Do you know if these tests are the same as the ones that are run with `build.cmd test`?

I just realized the tests weren't running to completion on my machine because I didn't have Perl installed. I'll install and see whether the tests fail locally as well.

**Comment by KevinRansom** [comment]
They are yes.

**Comment by JoshVarty** [comment]
So the tests pass locally but still seem to fail on the CI machine.

I dug into the logs some more and I see: 

```
1) Error : Tests.LanguageService.AutoCompletion.UsingMSBuild.AdjacentToDot_01
System.IO.FileLoadException : Could not load file or assembly 'Microsoft.VisualStudio.CoreUtility, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Salsa.Salsa.Privates.SimpleOpenFile.OnIdleTypeCheck()
   at Salsa.Salsa.Privates.SimpleOpenFile.OnIdle() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\Salsa\Salsa.fs:line 1120
   at Salsa.Salsa.Privates.SimpleVisualStudio.Salsa-Salsa-IVisualStudio-OnIdle() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\Salsa\Salsa.fs:line 855
   at Salsa.Salsa.Privates.SimpleVisualStudio.Salsa-Salsa-IVisualStudio-TakeCoffeeBreak() in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\Salsa\Salsa.fs:line 861
   at Salsa.Salsa.Privates.SimpleOpenProject.Salsa-Salsa-IOpenProject-OpenFile(String filename) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\Salsa\Salsa.fs:line 1086
   at UnitTests.TestLib.LanguageService.LanguageServiceBaseTests.CreateSingleFileProject(FSharpList`1 content, FSharpOption`1 references, FSharpOption`1 defines, FSharpOption`1 fileKind, FSharpOption`1 disabledWarnings, FSharpOption`1 fileName) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\TestLib.LanguageService.fs:line 326
   at Tests.LanguageService.AutoCompletion.UsingMSBuild.createFile(FSharpList`1 code, SourceFileKind fileKind, FSharpList`1 refs) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\Tests.LanguageService.Completion.fs:line 36
   at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoCompleteUsingExtraRefs(FSharpList`1 refs, Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\Tests.LanguageService.Completion.fs:line 43
   at Tests.LanguageService.AutoCompletion.UsingMSBuild.DoWithAutoComplete(Boolean coffeeBreak, SourceFileKind fileKind, BackgroundRequestReason reason, FSharpList`1 code, String marker, FSharpFunc`2 f) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\Tests.LanguageService.Completion.fs:line 54
   at <StartupCode$VisualFSharp-Unittests>.$Tests.LanguageService.Completion.AssertAutoCompleteContains@58-1.Invoke(FSharpList`1 code, String marker, FSharpList`1 should, FSharpList`1 shouldnot) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\Tests.LanguageService.Completion.fs:line 58
   at Tests.LanguageService.AutoCompletion.UsingMSBuild.testAutoCompleteAdjacentToDot@82(String op) in D:\j\workspace\release_ci_pa---3f142ccc\vsintegration\tests\unittests\Tests.LanguageService.Completion.fs:line 86
```

So it looks like it's having trouble with Microsoft.VisualStudio.CoreUtility in particular. Is it possible for me to remote to the machine to see what DLLs it has available to it?

**Comment by olegtk** [comment]
Looks like CI machine is using VS2015, while your bits want MS.VS.CoreUtilities.dll version 15.0.

**Comment by vasily-kirichenko** [comment]
Try to update VS NuGet packages to v. 15. Not everything is available though.

**Comment by JoshVarty** [comment]
>Looks like CI machine is using VS2015, while your bits want MS.VS.CoreUtilities.dll version 15.0 (VS2017).

Yeah I'm just not sure why my bits would need v15.0. I intentionally didn't add any explicit dependencies on v15.0.

**Comment by KevinRansom** [comment]
This looks great.

**Comment by KevinRansom** [comment]
Hmm!!!! somehow the fsharpqa suite has become flakey.

@dotnet-bot test this please

**Comment by KevinRansom** [comment]
Lets see if it will repeat that little trick
@dotnet-bot test this please

**Pull request merged**
