### PR TITLE
Attach build number to setup packages

### PR DESCRIPTION
**Pull request by OmarTawfik**
@Microsoft/fsharp-compiler

### CODE REVIEW

**Comment by brettfo** [comment]
Looks good, pending build completion.

**Comment by MattGertz** [comment]
Scenario meets the bar for consideration.

**Comment by natidea** [comment]
@OmarTawfik @brettfo Does merging this into master imply we are pulling in other changes that are not yet in the product?

**Comment by OmarTawfik** [comment]
@natidea no. this commit will be cherry picked into preview 5.

**Pull request merged**
