### PR TITLE
Make the FCS build work

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by KevinRansom** [comment]
@forki 
`````
error MSB4019: The imported project "D:\j\w\release_fcs_w---49a16363\packages\FSharp.Compiler.Tools.4.1.27\tools\Microsoft.FSharp.Targets" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk.
````

**Comment by forki** [comment]
yes. can you still please merge this. I activated for linux as well and will fix during the day

**Comment by KevinRansom** [comment]
Sure ...

**Comment by forki** [comment]
@KevinRansom dotnet --version shows 1.0.0 but we want 2.0.0

**Comment by forki** [comment]
ok I'm stuck. the groovy thing needs to go to master again. Damn this is tricky to do in PR ;-)

@KevinRansom please merge this ...

**Comment by forki** [comment]
[MERGE ME] [MERGE ME] [MERGE ME]

**Comment by KevinRansom** [comment]
@forki, sorry I had to go to bed, and then I had meetings this morning.

**Pull request merged**
