### PR TITLE
Do not commit autocomplete on comma and equals

### LINKED ISSUE #2835: Wrong completions for "member val x = 0 with get,"
#### Repro steps

Type in code:

```fsharp
type Foo() = 
    member val a = 12 with get
```

If you enter "," after the completion tooltip shows, code gets expanded to:

```fsharp
type Foo() = 
    member val a = 12 with Array.get,
```

The completion tooltip is shown here:

image

#### Expected behavior

When pressing ",", it should just leave "get" there as it's legal syntax. Current workaround is wait for the tooltip, dismiss it with ESC and then type in the ","

### PR DESCRIPTION
**Pull request by saul**
Fixes #2835, #3312, #2961

### CODE REVIEW

**Comment by dsyme** [comment]
This error looks complete unrelated:
>   D:\j\workspace\release_ci_pa---c6929ad7\packages\FSharp.Compiler.Tools.4.1.5\tools\Microsoft.FSharp.Targets(120,9): error MSB4062: The "CreateFSharpManifestResourceName" task could not be loaded from the assembly D:\j\workspace\release_ci_pa---c6929ad7\packages\FSharp.Compiler.Tools.4.1.5\tools\FSharp.Build.dll. Could not load file or assembly 'file:///D:\j\workspace\release_ci_pa---c6929ad7\packages\FSharp.Compiler.Tools.4.1.5\tools\FSharp.Build.dll' or one of its dependencies. The module was expected to contain an assembly manifest. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\j\workspace\release_ci_pa---c6929ad7\src\fsharp\FSharp.Core\FSharp.Core.fsproj]

**Comment by dsyme** [comment]
@dotnet-bot test Windows_NT Release_ci_part3 Build please

**Comment by dsyme** [comment]
@saul Odd error.  I wonder if something has changed in the CI system we are using

If we continue to get that error, maybe we should submit a separate PR to FSharp.Compiler.Tools 4.1.23

**Comment by cartermp** [comment]
Thanks for this @saul

**Pull request merged**
