### PR TITLE
Removed NoSourceCode at GetDeclarationLocation

### PR DESCRIPTION
**Pull request by amieres**
Removed check for NoSourceCode error from TypeCheckInfo.GetDeclarationLocation.
It was checking for a file to exist and failing if it did not.

https://github.com/fsharp/FSharp.Compiler.Service/issues/821

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@dotnet-bot test this please ..... timed out last time.

**Comment by cartermp** [comment]
Looks like a failing test on CI part 1

```
11:57:10 ProjectLineDirectives checkResults1 error file: <<<C:\Users\dotnet-bot\AppData\Local\Temp\tmpB106.fs>>>
11:57:10 => Tests.Service.ProjectAnalysisTests.Test Project21 whole project errors
11:57:10 Project21 error: <<<This expression was expected to have type
11:57:10     'int'    
11:57:10 but here has type
11:57:10     'string'    >>>
```

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@amieres,

Hi, I am going to close this.  This is an interesting PR, because the NavigateTo definition will still fail whether this check is done here or not.  The existing code has the benefit of causing the failure to happen before entering the Roslyn GotoDefinition Api.

So while this is mostly a useful simplification it can cause this dialog to appear:
image

As a consequence I am leaving the code as it currently is, to enable a quick failure where goto definition has no file.

If you think this is a mistake, please reactivate this and we can discuss it further.

Thanks

Kevin

**Comment by amieres** [comment]
Kevin
From what I understand, Roslyn requires actual physical file(s) and also expects GetDeclarationLocation to do the verification of its existence.

There are different ways to address the issue:
1.- fix Roslyn so that it verifies whether the file exists or not.
2.- add a runtime option to FCS as to whether or not to verify for the file, whereas by default it verifies.
3.- Add another version of GetDeclarationLocation that does not verify
4.- Maintain separate forks or versions of FCS
5.- Leave it as it is. Forcing the use of the workaround which is creating temporary file(s). 

From an FCS perspective option 1 seems to be the most logical, since Roslyn is the one with the requirement and it is an external module to FCS.  But if modifying Roslyn is out of the question and maintaining compatibility with it is a requirement then options 2 or 3 may be a good compromise.

Options 4 and 5 seem the least desirable to me, because they do not fix the issue.

**Comment by KevinRansom** [comment]
I'm not sure I quite understand what the issue is.  With and without this change the outcome is the same ... the symbol can't be navigated to. 

What seems to be needed is for a reference assembly or signature only file to be generated for the referenced assembly.  Wiring up that service would be quite interesting Roslyn does this generation for references, we should probably have a similar approach.  In the first instance we could probably wire up a C# or VB code generator, at least to try out the approach.

Brett and Will have more context on Roslyn and might be able to point you to and approach that works ...  unless I have misunderstood the issue of course.

/cc @brettfo , @TIHan

**Comment by brettfo** [comment]
If I'm understanding the issue correctly, what we're looking to enable is this scenario:

1.  In F# code I place the cursor on a type/method that we don't have source for.  E.g., `$$` represents the cursor location here: `let x = someString.Length$$`.
2.  Since we don't have the source for `System.String`, we're currently told we can't navigate to the symbol.
3.  If this same scenario is done in a C#/VB file, then a 'fake' file is shown in an editor which shows the `System.String` type and its public methods and properties.

In the Roslyn side this is handled by the [`IMetadataAsSourceService`](https://github.com/dotnet/roslyn/blob/a604cefecd2cba10803a872c580cfb7a9e0883ad/src/Features/Core/Portable/MetadataAsSource/IMetadataAsSourceService.cs) and C# directly exposes it through [`CSharpMetadataAsSourceServiceFactory`](https://github.com/dotnet/roslyn/blob/a604cefecd2cba10803a872c580cfb7a9e0883ad/src/Features/CSharp/Portable/MetadataAsSource/CSharpMetadataAsSourceServiceFactory.cs).

With this we have two steps to get this working for F#.

1.  Create a `FSharpMetadataAsSourceServiceFactory` that perfectly copies the C# one with the exception of using `LanguageNames.FSharp` in the `ExportLanguageServiceFactory` attribute.  The result of this step is that when I hit F12 on a framework type (or anything that I don't have source for) from an F# file, a 'fake' C# file will be shown.  This file should probably be created in the `FSharp.Editor` project.
2.  Modify the body of our `FSharpMetadataAsSourceServiceFactory` to return an F#-specific implementation of the `IMetadataAsSourceService` which would generate something that looks like an `.fsi` file.

**Comment by amieres** [comment]
My scenario is actually a little bit different and it doesn't involve Roslyn just FCS. 
It is like this:

- The source code does exist just not as an actual physical file. It resides in memory and was passed to FCS as a parameter.
- The symbol is defined in some location of the source code, so it can be navigated to.

What is happening now is that the function `GetDeclarationLocation` successfully locates the symbol, but just before returning its location, checks to see if the file actually exists, when it does not find it it returns an error message instead.

**Comment by KevinRansom** [comment]
@amieres ...

Ahh!!!! that is more cunning.  Can you add a test case so that we can be sure to keep it doing what you need it to do.  The current failing tests will need to be fixed up or eliminated as well.  And then we can pull this.

Does that sound right?

Kevin

**Comment by amieres** [comment]
Kevin
Sounds good.
I can try adding the new test case.
Would that involve creating a new PR or just modifying this one?

Someone else should fix the failing tests, right? 

Abe Mieres

**Comment by KevinRansom** [comment]
add it to this is fine.

**Comment by amieres** [comment]
Ok, I added the test to the PR

**Comment by realvictorprm** [comment]
@dotnet-bot test this please

Get an error on the details again.

**Comment by cartermp** [comment]
@dotnet-bot test this please

**Comment by cartermp** [comment]
@dotnet-bot test this please

**Comment by cartermp** [comment]
@amieres Could you rebase this against latest master? Thanks!

**Comment by amieres** [comment]
Is there a way to do a rebase purely from the github.com website?
If not, maybe it would be easier to create a new PR with my changes which only affect 2 files.

**Comment by cartermp** [comment]
Unfortunately you’ll need to use the CLI for a rebase, so feel free to
close this and recreate the PR.

On Sun, Jan 28, 2018, at 14:12, amieres wrote:
> Is there a way to do a rebase purely from the github.com website?
>  If not, maybe it would be easier to create a new PR with my changes
>  which only affect 2 files.> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/Microsoft/visualfsharp/pull/3719#issuecomment-361100880

**Comment by amieres** [comment]
Ok I'm closing this one and opening a new one, thanks!

**Pull request closed without merging**
