### PR TITLE
WIP Try to reproduce #1536

### PR DESCRIPTION
**Pull request by forki**
This reproduces the bug from #1536

### CODE REVIEW

**Comment by forki** [comment]
urghs this seems to happen in some COM component ISymUnmanagedWriter2 in method CloseMethod

**Comment by forki** [comment]
Ok this actually happening in ISymUnmanagedWriter2 when we add more then ~475 level deep scopes.

In ce077ea we keep track how deep we are in the scoping level and just skip the rest. This is probably not the the final solution, but at least we don't fail compiler when we write PDBs.

**Comment by forki** [comment]
@dsyme I just looked into a C# file with over 500 variables in a file. They just put that in the same scope so nobody ever noticed this ;-)

**Comment by dsyme** [comment]
This feels like a regression (?), if so we need to check the root cause and test coverage.

**Comment by forki** [comment]
It only happens when optimizer is disabled but debug is enabled. I assume methodsplitting stuff worked around this issue.

**Comment by forki** [comment]
7b0c127 is still green, but when running "build.cmd all" locally I see the stackoverflow happening. It's just that the fsharpQA suite doesn't care and goes on after a while.

**Comment by forki** [comment]
@enricosada any ideas where we can make fsharpqa stop on compiler throwing stackoverflow!?

**Comment by enricosada** [comment]
@forki the perl script should check the exit code of compiler, is not doing that?

**Comment by forki** [comment]
@enricosada I guess the thing is not exiting at all

**Comment by forki** [comment]
fun fact: the compiler is emitting the exe for the same and crashes. fsharpqa goes on with it's life. 

dca9fda3 reproduced it indirectly by running the exe (which is broken).

**Comment by forki** [comment]
Ok I think this a good enough test. Without the fix the CI is red and with fix applied it's green. 

Ready for review

**Comment by forki** [comment]
I rewrote @estokes sample (including nested scopes) in C# [NestedScopes.zip](https://github.com/Microsoft/visualfsharp/files/475026/NestedScopes.zip) and compiling/debugging works well. So there must exist a real solution.

**Comment by forki** [comment]
@dsyme something weird is happening here. We have one scope level per variable but the nesting is not ordered like the variables in the source file. I'm not sure if this is the root cause here, but it's definitely weird.

**Comment by KevinRansom** [comment]
@forki if you like I will take a look at this ... unless you want to follow up?

**Comment by forki** [comment]
Can't look at it before Monday. Have to run hipster F# conference at the
weekend ;-)

Am 16.09.2016 7:09 nachm. schrieb "Kevin Ransom (msft)" <
notifications@github.com>:

**Comment by KevinRansom** [comment]
I'm too old to do anything hipster ... so I suggest you have a good time.

**Comment by KevinRansom** [comment]
@dsyme @forki 

This is not a regression, this is using the oldest preview compiler on codeplex :

c:\temp\foo>"c:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Fsc.exe"  --debug:full --optimize- foo.fs
Microsoft (R) F# Compiler version 12.0.30623.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

 ....

Process is terminated due to StackOverflowException.

c:\temp\foo>

Interestingly it only happens when --optimize- is specified.


Kevin

**Comment by forki** [comment]
Yeah I'm already convinced optimizer is doing something so that this would
happen much later. One thing I wanted to try out was to use 500 variables
that have same name so that they shadow each other. So with that case the
optimizer could not remove scopes

Am 16.09.2016 21:41 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by KevinRansom** [comment]
@enricosada  @forki  @dsyme 

Okay I have a PR with a slightly different fix:  https://github.com/Microsoft/visualfsharp/pull/1545

The fix merges nested scopes that have the same dimensions.

**Pull request closed without merging**
