### PR TITLE
Port NUnit based tests to Core CLR and xUnit.net

### PR DESCRIPTION
**Pull request by PatrickMcDonald**
This is a work-in-progress PR for #690

- [ ] Pick xUnit.net or NUnit
- [X] Rebase PR against the HEAD of the coreclr branch.
- [X] Update coreunit tests
- [ ] Update IDE Unit tests
- [ ] Update FSharp.Compiler.Unittests
- [X] Get coreclr tests running.
- [X] Fix Profile47.

### CODE REVIEW

**Comment by KevinRansom** [comment]
That all looks good and not nearly as dramatic as I expected.

Experimental xunit portable stuff can be found here:  https://www.myget.org/gallery/dotnet-buildtools

**Comment by enricosada** [comment]
@PatrickMcDonald i upgraded my pr for fsharp suite to nunit 3 ( #90 ), the migration was easy.

maybe is worth a shot, see https://github.com/Microsoft/visualfsharp/issues/690#issuecomment-151009760 there is a nuget ready.

Btw the vs test runner adapter work only with beta 3, so you need to run tests from commandline, but the console was an easy upgrade too

**Comment by PatrickMcDonald** [comment]
I rebased this PR against the latest coreclr branch and have managed to get the tests running in the coreclr.

**Comment by KevinRansom** [comment]
Patrick, do you want me to pull this, or do you want to stick with it?  I'm liking what I see so far.

**Comment by PatrickMcDonald** [comment]
Kevin, I'm happier with this PR now that I have Profile47 working with xUnit. (We need to reference v1.9.2 of xUnit.net which thankfully is only 1 dll)

There are still 2 coreunit coreclr tests failing for me, both with reflection errors so not that surprising really.  I'm at a loss how to fix them though.  1 is the surface area test which I haven't seen running, so expect some differences there when we do get it running.

One of the Profile7 tests is failing for reason I haven't identified.

> System.ArgumentException : Ambiguous method named Equals in type FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Reflection.FSharpValueTests

Also the IDE and compiler unit tests are outstanding, but they can be dealt with in a separate PR.

On the NUnit vs xUnit.net debate, It seems to me that to get NUnit 3.0 running in the Core CLR we would have to change the test dlls to exes, which seems like overkill for a temporary solution. We can still port xUnit back to NUnit when NUnit is ready, but once the work is done to convert to xUnit, it all seems to work very well.

**Comment by enricosada** [comment]
Btw, [nunit 3 final](https://github.com/nunit/nunit/wiki/Release-Notes) is now released and should support coreclr

@PatrickMcDonald ide tests doesnt need to change test framework, these projects (vs extension) are not going to be compiled to coreclr.

About nunit lite, .dll to .exe is only few conditionals on msbuild files (see [nunit lite 3](http://nunit.org/index.php?p=nunitlite&r=3.0) ) and an additional program.fs. 
The program main already exists.

```csharp
public static void Main(string[] args)
    {
      new TextUI().Execute(args);
    }
```




Also nunit lite (modified by xamarin as  [touch.unit](https://developer.xamarin.com/guides/ios/deployment,_testing,_and_metrics/touch.unit/) ) is used to run tests on ios devices ( dont think this work with nunit lite 3 now but is going to )

**Comment by KevinRansom** [comment]
@PatrickMcDonald @enricosada 
It seems as if the nunit guys have some form of coreclr testing now:

* http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/
* https://www.nuget.org/packages/NUnitLite/3.0.0-rc

It would be nice, if we could see if we can make it work.

**Comment by PatrickMcDonald** [comment]
Okay that took longer than it should have, as the changes were simple enough.  Created #748 as the NUnit version of this PR.

**Comment by KevinRansom** [comment]
the nunit port looks like the way to go.  Thanks for taking care of this @PatrickMcDonald .

**Pull request closed without merging**
