### PR TITLE
Blockstructure Service

### PR DESCRIPTION
**Pull request by cloudRoutine**
blockstructure

Fixing Bugs from #2052
## TODO
- [x] BlockStructuring for `.fsi` file
- [x] Banner text for collapsed blocks

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Great stuff, keep going!

**Comment by cartermp** [comment]
Really great stuff @cloudRoutine.

**Comment by cloudRoutine** [comment]
@KevinRansom both the `.fs` & `.fsi` have guidelines and outlining implemented now

**Comment by KevinRansom** [comment]
Merged: https://github.com/Microsoft/visualfsharp/commit/98372ab1aeeabc5db6b7eebaab13065ecf887d88

Jared,

thanks for this work

Kevin

**Pull request closed without merging**
