### PR TITLE
Enable tests using Perl and build VS integration projects

### PR DESCRIPTION
**Pull request by dungpa**
**Edit:** It no longer requires to use Visual Studio 2015 CTP5 image.

### CODE REVIEW

**Comment by dungpa** [comment]
Don't know why builds run extremely slow on VS 2015 CTP 5 image (at least 2x slower than the normal one). Closing.

**Comment by latkin** [comment]
Your build script includes the VS Integration stuff - current fsharp4 build script does not. That is probably contributing much of the build time.

**Comment by dungpa** [comment]
Nope.

Default image: core solutions + some tests: ~14 min
VS 2015 CTP image: core solutions: ~27 min
                                   VS integration solutions: ~13 min

It's still 2x slower than default image. Strange since they both run MSBuild 12.0.

**Comment by latkin** [comment]
Yes, it's slower, but the build surpassed the 40 min limit largely due to adding in the vsintegration stuff.

We can at least seen how the Perl stuff works by removing vsintegration for now.

**Comment by dungpa** [comment]
I just tried. It timed out in the middle of FSharpQA Smoke tests.

**Comment by latkin** [comment]
Yes, but it worked at least :grinning: Thanks for helping test this out.

**Comment by dungpa** [comment]
The build script now uses the default image with Perl. Smoke tests run fine.

I've enabled VS integration builds again since we still have time budget for that.

**Comment by forki** [comment]
xlhl738

**Comment by dungpa** [comment]
It no longer works after #186 is merged :cry:.

**Comment by KevinRansom** [comment]
Working on a fix, it can't find rc because it's not a vs2014 shell.

**Comment by dungpa** [comment]
Thanks @KevinRansom. The tests succeed again.

**Comment by dsyme** [comment]
This is great!

**Comment by KevinRansom** [comment]
Appveyor runs custom images such as Visual Studio 2015 CTP only on Azure.  I have contacted them and they tell me that they will be adding pro support to those images next week, at that time I will switch us back to Visual Studio CTP 5 in the meantime we will use VS2013 for validation.

Kevin

**Pull request closed without merging**
