### PR TITLE
Fixed roslyn boundings

### PR DESCRIPTION
**Pull request by forki**
references #2231

### CODE REVIEW

**Comment by forki** [comment]
@vasily-kirichenko I really don't get that. This test shows that the compiler is indeed emmitting the correct range. How can the VS2017 RC fuck it up anyways? Any ideas what's going on here?

**Comment by vasily-kirichenko** [comment]
No. But I've almost fixed it :)

**Comment by forki** [comment]
image

**Comment by forki** [comment]
union

Ok the bug only appears if the union is the last char of the whole document and it's unrelated to double backticks:

union2

**Comment by forki** [comment]
just checked. this is a regression and worked in VS2015

**Comment by forki** [comment]
just checked with the compiler. it still emits the correct range. so this is broken in IDE

**Comment by forki** [comment]
ok found the bug - will send a fix soon

**Comment by forki** [comment]
fixed. please review and merge asap.

**Comment by forki** [comment]
after applying this error reporting and renaming works as expected:

**Pull request merged**
