### PR TITLE
Regression tests for comparers

### PR DESCRIPTION
**Pull request by manofstick**
This is a set of regression tests for #513. It's is branched from the point just before modifications in that pull requests began.

Possibly this is a bit of overkill, but I suppose that is the point of regression tests. This will be merged into #513, but is here to obviously prove that it was OK prior to the changes.

The data is mainly generated by running the CreateComparersRegression.fsx and pasting the results over the top of the bottom part of the ComparersRegression.fs file (I suppose it could have been a seperate file... Maybe that would have been better; but I'm hoping there really isn't much need to run it multiple times)

### CODE REVIEW

**Comment by manofstick** [comment]
@latkin,

Argh, the compiler is inlining these (obviously) and so no really achieving what I want. I will have to regenerate. Soon, soon....

**Comment by latkin** [comment]
> +47,167  -0

shades

This is actually right in line with what I think we need - a near-exhaustive set of regression tests that really nail down how things work.

Looking at the CI build, this doesn't appear to have too drastic of an effect on compilation or execution time, which I was a bit worried about.

**Comment by manofstick** [comment]
OK; hopefully this is a better test suite.

I have now ensured that there are both the potential for the compiler to do inlining optimizations as well as not. This has meant that the number of tests has doubled.

But, I have shrunk the format a little (limiting spaces, using 0,1 for false and true) and so the actual file is a little smaller than it was before.

**Comment by manofstick** [comment]
I'm feeling too lazy at the moment (and it's not really in scope of what I'm trying to achieve), but slight modifications to this suite could be used to pick up any inconsistencies between compiler optimizations and not, as well as between direct versions and wrapped versions, embedded in other types, etc...

i.e. for #576, #527 & #556

(on another note, when those items are fixed, then obviously this regression suite would need to be updated)

**Comment by latkin** [comment]
I'd like to merge this separately, and before, #513.  That way it's unambiguous that behavior remains  unchanged before/after 513 is applied.

**Comment by manofstick** [comment]
@latkin 

I agree, that was why I created this pull request :-)

(wow, it's almost like we're talking in real time!)

**Comment by latkin** [comment]
Ah ok, "this will be merged into 513" made me think you planned to keep them together.

**Comment by manofstick** [comment]
No, I just merged it in so that I could make sure it worked before and after.

**Comment by manofstick** [comment]
(like it has been merged in, but I still expected the regression tests to run in a unmolested state...)

Hmmm.. that make sense?

**Pull request closed without merging**
