### PR TITLE
Prepare for Dev 16 Preview 3

### PR DESCRIPTION
**Pull request by KevinRansom**
1.   Remove legacy F# templates
      * Replace them with NET Sdk templates that target the desktop framework.
      * Existing lgacy F# projects can be edited using the F# IDE, but all new projects should be NET Sdk
2.   Remove App.config Item template
      * NET Sdk generates an App.config when binding redirects are necessary.
3.   Update Net Sdk to use FSharp.Core from the 4.6.0 nuget package
4.   Fix title text of .nuspec package, add FSLangugeVersion property to build
5.   Remove VS deployment of nuget packages of FSharp.Core and System.ValueTuple.
      * Only necessary for new legacy projects.

/CC @jmarolf

### CODE REVIEW

**Comment by cartermp** [comment]
How much more difficult is it for us to simply "archive" the old ones for a time and change setup so that we point to brand-new templates using the .NET SDK?

**Comment by cartermp** [comment]
Also, we can remove the F# Desktop language support component with this change, since:

* This can be a part of the F# component itself
* It's impossible to get F# without .NET Core SDK in VS now
* It's impossible to get .NET Core SDK without F# in VS now

**Comment by KevinRansom** [comment]
@cartermp 

We need to continue to allow developers to edit their legacy projects.  So the Legacy Project System support, is likely in for "all time".

As for archiving the old templates, that's what source code control is for.  We could continue to ship the legacy projects alongside NET Sdk projects, however, that is what we have been doing for the last few years.

The dotnet cli, already has these templates and a mechanism for specifying dotnet frameworks.  The purpose of these templates is to give developers a trivial mechanism for getting a project to create a NET Framework app.

As for removing Desktop language support, I think yes we should probably do that because it is pretty much just about ensuring these templates are deployed, which is kind of wierd.

**Comment by cartermp** [comment]
> We need to continue to allow developers to edit their legacy projects. So the Legacy Project System support, is likely in for "all time".

I wasn't saying that we get rid of this. I'm saying that we should archive the existing templates rather than replace them as the current PR does

**Comment by KevinRansom** [comment]
@cartermp we should chat off-line I'm not quite getting the question.

**Comment by KevinRansom** [comment]
@cartermp, @brettfo reminded me why that check box exists.

It is possible to install VS with the managed development workload without the dotnet cli.  In that case there would be no F#.

We would either have to ensure that F# was installed whenever the managed code workload was installed or that the dotnet cli was always installed when the managed code workload.

Therefore the checkbox is still necessary.

**Comment by cartermp** [comment]
It's not. We're making the .NET Core SDK (which includes F#) required for the .NET Desktop workload in VS 2019.

**Comment by KevinRansom** [comment]
As soon as it is in, we can make that change.

**Pull request merged**
