### PR TITLE
[WIP] Enable VS unit tests in CI

### PR DESCRIPTION
**Pull request by dsyme**
This enables the VisualFSharp.Unittests suite in CI. All tests except ignored and "Expensive" (approx > 15sec) are run.

### CODE REVIEW

**Comment by dsyme** [comment]
Please don't merge this yet.

It's very strange - all tests are passing on my local machine, but we have 500 failures in AppVeyor. https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.1530/job/dyvijxk5sri13vm3/tests in the VisualFSharp.Unittests IDE suite.

However equally we have 2000 passing tests in that suite, so it's not a totally catastrophic error.  Strangely I can't see any specific diagnostics in the test that indicate the problem.

I've turned on as much loggin as possible and made the build.cmd ignore the overall failure so we can collect logs via artifacts as well, e.g. https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.1530/job/dyvijxk5sri13vm3/artifacts.

However I'm going to have to keep throwing slight variations at AppVeyor to try to work out what's going wrong.

**Comment by dsyme** [comment]
@enricosada pointed out that we can remote-desktop to the AppVeyor machine https://www.appveyor.com/docs/how-to/rdp-to-build-worker

I will do that.

```
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

```

**Comment by dsyme** [comment]
OK, the failing tests were due to LF (not CRLF) being used on AppVeyor checkout for the test files under vsintegration\...   

I've added a vsintegration\.gitattributes, hopefully that will do the trick

**Comment by dsyme** [comment]
Ugh, [so AppVeyor decides to use LF by default](http://help.appveyor.com/discussions/problems/1119-allow-changing-git-autocrlf-setting).  How silly, I have no idea why it is doing that for a Windows-based CI system.

This fixes that.  What a waste of time!

    init:
      - git config --global core.autocrlf true

Hopefully this will now go through

**Comment by dsyme** [comment]
I'll merge this, we're green on AppVeyor at last!  That means AppVeyor is now running all unit test suties (apart from "Expensive"). The Jenkins debug build timed out

**Comment by enricosada** [comment]
:tada: :tada: :tada: :tada:

**Comment by enricosada** [comment]
> Ugh, so AppVeyor decides to use LF by default. How silly, I have no idea why it is doing that for a Windows-based CI system

@dsyme that's should not be a problem with a .gitattributes file, it's strange (or file are committed before .gitattributes and used a different line ending in git). I'll check

**Comment by ctaggart** [comment]
Why do the tests fail due to LF? Why not fix the tests instead of changing core.autocrlf? Which types of files must be CRLF? Not .fs files. Perhaps .sln files. Better to update .gitattributes.

**Pull request merged**
