### PR TITLE
Fix for issue #30: Compilation error "Incorrect number of type arguments to local call"

### PR DESCRIPTION
**Pull request by andrewjkennedy**
Code was comparing a pre-erasure list of arguments with a post-erasure list

### CODE REVIEW

**Comment by dsyme** [comment]
This looks good.  I guess we will need to add a test too.

**Comment by andrewjkennedy** [comment]
Added test

**Comment by dsyme** [comment]
Hi Andrew, ignore the AppVeyor failure.  If you push another commit in, you should see it run and hopefully succeed

**Comment by andrewjkennedy** [comment]
Yep, just did that!

Any more?...

A

**Comment by dsyme** [comment]
I don't see the extra commit (just the second test commit, but AppVeyor wasn't et up when you pushed that one)

**Pull request closed without merging**
