### PR TITLE
fix rename file inside folder

### LINKED ISSUE #259: Renaming files in folders causes strange UI display
First we have two files inside a folder:
image

After renaming `File94.fs` to `File95.fs`, `File95.fs` moves on top (even on top of References nodes):

image

It's a UI bug since the project is in good state. Reopening the project fixes the display.

See this in both VF# 3.1.2 and VF# 4.0.0.

### PR DESCRIPTION
**Pull request by enricosada**
fix #259

### CODE REVIEW

**Comment by dungpa** [comment]
:+1:

Thanks for the fix. Is there any way to add tests for this?

**Comment by latkin** [comment]
@enricosada looks like master branch failure might be addressed by porting #301 to master (failure is in that same part of the build).  I'll give that a try.

**Comment by enricosada** [comment]
added test to check IVsHierarchyEvents

**Comment by latkin** [comment]
Nice, LGTM :+1:

**Comment by latkin** [comment]
Applied with https://github.com/Microsoft/visualfsharp/commit/b74853342c7df5a53bf13a4bc25bdcb294f9e949

**Pull request closed without merging**
