### PR TITLE
Rename collapsable to collapsible

### LINKED ISSUE #5247: Spelling: collapsable should be collapsible
In the Advanced tab: 
image

The preferred spelling is _collapsible_, not _collapsable_ (and Microsoft's spelling check agrees, as does the open source spelling check of Firefox). See [[1]](https://www.drupal.org/project/views_pdf/issues/1270346), [[2]](https://www.merriam-webster.com/dictionary/collapsible), [[3]](https://github.com/react-bootstrap/react-bootstrap/issues/425).

### PR DESCRIPTION
**Pull request by abelbraaksma**
This fixes #5247

### CODE REVIEW

**Comment by cartermp** [comment]
Thanks @abelbraaksma!

Can you run `msbuild /t:UpdateXlf` in your branch and then push again?

**Comment by abelbraaksma** [comment]
@cartermp, I'm not sure I understand. If I search for that term, I find it in the devguide.md, but that doesn't seem to apply (I didn't edit the compiler service):

image

But in the log of the build I see:

> D:\j\w\release_ci_pa---3f142ccc\packages\xlifftasks\0.2.0-beta-000081\build\XliffTasks.targets(90,5): error : 'xlf\Strings.en.xlf' is out-of-date with 'Strings.resx'. Run `msbuild /t:UpdateXlf` to update .xlf files or set UpdateXlfOnBuild=true to update them on every build, but note that it is strongly discouraged to set UpdateXlfOnBuild=true in official/CI build environments as they should not modify source code during the build. [D:\j\w\release_ci_pa---3f142ccc\vsintegration\src\FSharp.UIResources\FSharp.UIResources.csproj]

But if I do just that in the directory `vsintegration\src\FSharp.UIResources`, I receive an error:

```
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 29-6-2018 0:57:28.
Project "D:\Projects\OpenSource\VisualFSharp2\vsintegration\src\FSharp.UIResources\FSharp.UIResources.csproj" on node 1 (updatexlf target(s)).
D:\Projects\OpenSource\VisualFSharp2\vsintegration\src\FSharp.UIResources\FSharp.UIResources.csproj : error MSB4057: The target "updatexlf" does not exist in the project.
Done Building Project "D:\Projects\OpenSource\VisualFSharp2\vsintegration\src\FSharp.UIResources\FSharp.UIResources.csproj" (updatexlf target(s)) -- FAILED.


Build FAILED.

"D:\Projects\OpenSource\VisualFSharp2\vsintegration\src\FSharp.UIResources\FSharp.UIResources.csproj" (updatexlf target) (1) ->
  D:\Projects\OpenSource\VisualFSharp2\vsintegration\src\FSharp.UIResources\FSharp.UIResources.csproj : error MSB4057: The target "updatexlf" does not exist in the project.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.47
```

**Comment by cartermp** [comment]
If you run `build.cmd vs` from the command line (root of the repo) and push, I believe it should work as well. That's usually what I do.

**Comment by abelbraaksma** [comment]
Ok, running that now, see what happens ;)

**Comment by KevinRansom** [comment]
@abelbraaksma can you please remove those .resources files that were added.

**Comment by abelbraaksma** [comment]
Will do in the morning, was already surprised they 'needed' to be added. Shouldn't they be in ignore files? Or what am I missing?

**Comment by abelbraaksma** [comment]
I removed them for now. I am still wondering what about lines like these:

```diff
-        <target state="translated">Zobrazí osnovu a sbalitelné uzly kódu F#.</target>
+        <target state="needs-review-translation">Zobrazí osnovu a sbalitelné uzly kódu F#.</target>
```

It seems to be a bit redundant to request a review for all translations after fixing the typo. Can I change them back to `translated`? 

Sorry, I tried to find a guide on how the process with resources is supposed to happen, but couldn't find any, hence the bumpy road... learning by doing ;).

**Comment by forki** [comment]
Yes translation did not change.

Abel Braaksma <notifications@github.com> schrieb am Fr., 29. Juni 2018,
14:57:

**Comment by abelbraaksma** [comment]
@forki so what's the cause of action for trivial fixes like these, to prevent others needing to look at these translations again?

**Comment by forki** [comment]
I don't think there is a specific workflow here. Just don't commit changes
in the translation. Only commit the English strings

Abel Braaksma <notifications@github.com> schrieb am Fr., 29. Juni 2018,
15:35:

**Comment by abelbraaksma** [comment]
> I don't think there is a specific workflow here. Just don't commit changes in the translation. Only commit the English strings

Ok, tx. Plus running the build so that errors like `error : 'xlf\Strings.en.xlf' is out-of-date with 'Strings.resx'` do not appear, apparently. Though it feels a bit weird to have `needs-review-translation` in the source now.

Other than that, I think this is ready then.

**Comment by smoothdeveloper** [comment]
@abelbraaksma I think it is normal that if you change an english message, the matching translations are tagged "needs review" because the system doesn't know it was just a typo fix.

If you are just fixing a typo, it is OK to revert that part in the translations (assuming they didn't carry the typo).

**Comment by abelbraaksma** [comment]
@smoothdeveloper, thanks. And only now I see why I didn't see the `resx` file change, because running `build vs` reverted the changes in the `xlf` files, instead of leaving them:

```diff
-        <source>Show outlining and collapsible nodes for F# code</source>
-        <target state="new">Show outlining and collapsible nodes for F# code</target>
+        <source>Show outlining and collapsable nodes for F# code</source>
+        <target state="new">Show outlining and collapsable nodes for F# code</target>
```

Hmm, just changing the `xlf` files was a bad idea. Going back to the drawing board for fixing one character :P.

**Comment by abelbraaksma** [comment]
Ok, first `resx`, then rebuild, then check changes, then revert or fix where necessary the `xlf` files, then commit. 

That'd be the correct order of things for changing resource strings in this project (granted, I don't have projects with a similar setup for internationalization, clearly lacking experience in that regard ;).

Thanks for the patient helping hand!

**Comment by abelbraaksma** [comment]
I think this time around it is ready and can be merged @cartermp  ;).

**Comment by cartermp** [comment]
Thanks @abelbraaksma

**Pull request merged**
