### PR TITLE
Fix absence of Quick Info in case of malformed XML Doc

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/2506

### CODE REVIEW

**Comment by KevinRansom** [comment]
@dotnet-bot test this please

**Comment by vasily-kirichenko** [comment]
linux and mac don't love us :)

**Comment by cartermp** [comment]
@dotnet-bot test this please

**Comment by KevinRansom** [comment]
@vasily-kirichenko 

Thanks for this

Kevin

**Pull request merged**
