### PR TITLE
List average, averageBy perf

### PR DESCRIPTION
**Pull request by AviAvni**
Changing the implementation of List.average/averageBy from Seq.average/averageBy that use IEnumerable
to implementation like List.fold which is more native way to traverse the list implemented by recursion
that compiles to while loop
benchmarks: https://gist.github.com/AviAvni/0a3576a619ff9bf4acf1958b8ca1c63b

### CODE REVIEW

**Comment by KevinRansom** [comment]
Hi Avi,

thanks for this PR, have you any performance benchmarks to indicate the benefits of these changes.  
interesting metrics for performance:

1. Wall clock time changes
2. Working set changes
3. CPU
4. Allocations

Before we can accept performance based re-writes we are interested in understanding the benefits that the rewrite produces.  It is our experience that intuition is a pretty unreliable guide.

Thanks

Kevin

**Comment by isaacabraham** [comment]
@KevinRansom: @AviAvni has included a link to a gist with benchmarks in the comment.

**Comment by dsyme** [comment]
This looks good.  I'd like to see ``averageBy`` done in the same PR (so we keep consistency of performance)

**Comment by AviAvni** [comment]
MSBOT please build

**Comment by latkin** [comment]
Anything else on this one? I think it's in nice shape, good work @AviAvni .

**Comment by KevinRansom** [comment]
I’m just re-running the ci on them, preparatory for pulling.

**Comment by KevinRansom** [comment]
The CI failed with these errors that look related to this PR:
[00:18:03] "C:\projects\visualfsharp-radou\tests\..\packages\NUnit.Console.3.0.0\tools\nunit3-console.exe" /framework:V4.0 /result="C:\projects\visualfsharp-radou\tests\TestResults\CoreUnit_all_Xml.xml;format=nunit2" /output="C:\projects\visualfsharp-radou\tests\TestResults\CoreUnit_all_Output.log" /err="C:\projects\visualfsharp-radou\tests\TestResults\CoreUnit_all_Error.log" /work="C:\projects\visualfsharp-radou\tests\..\release\net40\bin" "C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\net40\bin\FSharp.Core.Unittests.dll" "C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\portable7\bin\FSharp.Core.Unittests.dll" "C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\portable47\bin\FSharp.Core.Unittests.dll" "C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\portable78\bin\FSharp.Core.Unittests.dll" "C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\portable259\bin\FSharp.Core.Unittests.dll"
[00:18:03] NUnit Console Runner 3.0.5797 
[00:18:03] Copyright (C) 2015 Charlie Poole
[00:18:03] 
[00:18:03] 
[00:18:03] Runtime Environment
[00:18:03]    OS Version: 
[00:18:03] Microsoft Windows NT 6.3.9600.0
[00:18:03] 
[00:18:03] 
[00:18:03]   CLR Version: 
[00:18:03] 4.0.30319.42000
[00:18:03] 
[00:18:03] 
[00:18:03] 
[00:18:04] Test Files
[00:18:04]     C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\net40\bin\FSharp.Core.Unittests.dll
[00:18:04]     C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\portable7\bin\FSharp.Core.Unittests.dll
[00:18:04]     C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\portable47\bin\FSharp.Core.Unittests.dll
[00:18:04]     C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\portable78\bin\FSharp.Core.Unittests.dll
[00:18:04]     C:\projects\visualfsharp-radou\tests\..\release\net40\bin\..\..\portable259\bin\FSharp.Core.Unittests.dll
[00:18:04] 
[00:23:24] 
[00:23:24] 
[00:23:24] Errors and Failures
[00:23:24] 
[00:23:24] 
[00:23:24] 1) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.average is consistent
[00:23:24] System.Exception : Falsifiable, after 1 test (0 shrinks) (StdGen (1919899964,296142332)):
[00:23:24] Original:
[00:23:24] [||]
[00:23:24]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:23:24]    at FsCheck.Runner.check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCh
[00:23:24] eck\Runner.fs:line 269
[00:23:24]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.average is consistent() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs:line 44
[00:23:24] 
[00:23:24] 2) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.averageBy is consistent
[00:23:24] System.Exception : Falsifiable, after 11 tests (0 shrinks) (StdGen (1922399971,296142332)):
[00:23:24] Original:
[00:23:24] [||]
[00:23:24] <fun:Invoke@3257>
[00:23:24]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:23:24]    at FsCheck.Runner.check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCh
[00:23:24] eck\Runner.fs:line 269
[00:23:24]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.averageBy is consistent() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs:line 56
[00:23:24] 
[00:23:24] 3) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.average is consistent
[00:23:24] System.Exception : Falsifiable, after 1 test (0 shrinks) (StdGen (1920681214,296142332)):
[00:23:24] Original:
[00:23:24] [||]
[00:23:24]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:23:24]    at FsCheck.Runner.check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCh
[00:23:24] eck\Runner.fs:line 269
[00:23:24]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.average is consistent() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs:line 44
[00:23:24] 
[00:23:24] 4) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.averageBy is consistent
[00:23:24] System.Exception : Falsifiable, after 11 tests (0 shrinks) (StdGen (1922399971,296142332)):
[00:23:24] Original:
[00:23:24] [||]
[00:23:24] <fun:Invoke@3257>
[00:23:24]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:23:24]    at FsCheck.Runner.check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCh
[00:23:24] eck\Runner.fs:line 269
[00:23:24]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.averageBy is consistent() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs:line 56
[00:23:24] 
[00:23:24] 5) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.average is consistent
[00:23:24] System.Exception : Falsifiable, after 28 tests (0 shrinks) (StdGen (1923181211,296142332)):
[00:23:24] Original:
[00:23:24] [||]
[00:23:24]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:23:24]    at FsCheck.Runner.check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCh
[00:23:24] eck\Runner.fs:line 269
[00:23:24]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.average is consistent() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs:line 44
[00:23:24] 
[00:23:24] 6) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.averageBy is consistent
[00:23:24] System.Exception : Falsifiable, after 5 tests (0 shrinks) (StdGen (1924899964,296142332)):
[00:23:24] Original:
[00:23:24] [||]
[00:23:24] <fun:Invoke@3257>
[00:23:24]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:23:24]    at FsCheck.Runner.check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCh
[00:23:24] eck\Runner.fs:line 269
[00:23:24]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.averageBy is consistent() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs:line 56
[00:23:24] 
[00:23:24] 7) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.average is consistent
[00:23:24] System.Exception : Falsifiable, after 4 tests (0 shrinks) (StdGen (1921462456,296142332)):
[00:23:24] Original:
[00:23:24] [||]
[00:23:24]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:23:24]    at FsCheck.Runner.check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCh
[00:23:24] eck\Runner.fs:line 269
[00:23:24]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.average is consistent() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs:line 44
[00:23:24] 
[00:23:24] 8) Error : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.averageBy is consistent
[00:23:24] System.Exception : Falsifiable, after 28 tests (0 shrinks) (StdGen (1923181211,296142332)):
[00:23:24] Original:
[00:23:24] [||]
[00:23:24] <fun:Invoke@3257>
[00:23:24]    at <StartupCode$FsCheck>.$Runner.get_throwingRunner@362-1.Invoke(String message) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 362
[00:23:24]    at FsCheck.Runner.check[a](Config config, a p) in c:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 269
[00:23:24]    at FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.averageBy is consistent() in C:\projects\visualfsharp-radou\src\fsharp\FSharp.Core.Unittests\FSharp.Core\Microsoft.FSharp.Collections\CollectionModulesConsistency.fs:line 56
[00:23:24] 
[00:23:24] Run Settings
[00:23:24]     RuntimeFramework: V4.0
[00:23:24]     WorkDirectory: C:\projects\visualfsharp-radou\tests\..\release\net40\bin
[00:23:24]     NumberOfTestWorkers: 4

Are these failures expected?

**Comment by AviAvni** [comment]
@latkin @KevinRansom thanks the error was because the test want that every thing need to be equal in Seq/List/Array.average even the error when sending emty collection but the name of the argument is different on each function but to be compatible I fix it now i think the build and tests be fine
thanks for the help

**Comment by KevinRansom** [comment]
@AviAvni Thank you for this contribution

Kevin

**Pull request merged**
