### PR TITLE
Remove duplicates from completion

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/3928 and https://github.com/fsharp/FsAutoComplete/issues/244

### CODE REVIEW

**Comment by cartermp** [comment]
@dotnet-bot test this please

**Comment by cartermp** [comment]
still down

**Comment by cartermp** [comment]
nope nvm

**Comment by KevinRansom** [comment]
Thank you for this.

**Pull request merged**
