### PR TITLE
update to FCT 4.1.5

### PR DESCRIPTION
**Pull request by dsyme**
FSharp.Compiler.Tools 4.1.5 has a fix for Mono

### CODE REVIEW

**Comment by dsyme** [comment]
Please don't merge.  The resource embedddings are **Still** wrong. sigh

I see this in the build log, this is wrong:

				--resource:obj/release/net40/obj.release.net40.FSBuild.resources

**Comment by dsyme** [comment]
OK, I checked this and understand what the difference between the two repos is - one was defining CROSS_PLATFORM_COMPILER (which is almost totally unused).  

I've adjusted two of the main uses of this to just do sensible things on Mono by default.

**Comment by dsyme** [comment]
@7sharp9 I think this should solve your OSX woes. I hope.

**Comment by KevinRansom** [comment]
CROSS_PLATFORM_COMPILER and ENABLE_MONO_SUPPORT ... still cleanup to do, but it can happen later.

**Comment by dsyme** [comment]
> CROSS_PLATFORM_COMPILER and ENABLE_MONO_SUPPORT ... still cleanup to do, but it can happen later.

yep

**Comment by 7sharp9** [comment]
@dsyme Just tried this and `mono fsi.exe` now works so its looking promising

**Comment by dsyme** [comment]
@7sharp9 That's a relief.  Apologies for the mistake.  Will try to get some decent test coverage going here

**Pull request merged**
