### PR TITLE
Fixes #3170

### LINKED ISSUE #3170: type solver fails with Linq .ToDictionary(fun,fun)
I would expect the following code to work and produce a Dictionary<Guid,Guid>:

```F#
open System
open System.Linq

type GuidWrapper = GuidWrapper of Guid
    with member x.Id =
            let (GuidWrapper id) = x
            x

let id = Guid.NewGuid()
let map = [GuidWrapper id, GuidWrapper id] |> Map

map.ToDictionary((fun m -> m.Key.Id), (fun m -> m.Value.Id))
```

## Actual:

> stdin(12,49): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.

## Workaround:

```F#
            let toId (m:KeyValuePair<GuidWrapper,GuidWrapper>) = m.Value.Id
            map.ToDictionary((fun m -> m.Key.Id), toId)
```

## Version:
FSI from
image

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
4f731a4 fixes #3170 it for me. but it needs REAL review by @dsyme and @kevinransom

**Comment by forki** [comment]
agent went offline. again.

**Comment by forki** [comment]
agent went where? yeah you guessed it.

**Comment by 0x53A** [comment]
Eh, you are so negative, I prefer the build server crashing a few times because of running on a preview OS to a production server crashing a few times because the bugs weren't caught. Or maybe I'm just too positive? I guess I need to start drinking more.

**Comment by KevinRansom** [comment]
I'm kind of with Steffen on this.  It's really irritating seeing a failure that is infra related.  There is, however, the joy of realizing that the failure isn't due to my own ineptness, which takes the sting off it.

But I'm sure the infra folks will figure it out before too long.

**Comment by forki** [comment]
@KevinRansom more importantly: could you try to review and let me know how stupid this change is?

**Comment by KevinRansom** [comment]
@forki this is going to take some investigation, It's not clear why NoInfo should indicate LambdaPropogation.

Perhaps the issue is in: ExamineArgumentForLambdaPropagation in methodcalls.fs

**Comment by forki** [comment]
oh it filters the NoInfo out. But if you have one NoInfo in the list then it just skipped adding type equations alltogether

**Comment by KevinRansom** [comment]
@forki ... okay this looks good.

**Comment by dsyme** [comment]
> ... but it needs REAL review by @dsyme and @KevinRansom

@KevinRansom Could we wait for two-person review before merging ones like this please?  Thanks

@forki The change looks highly plausible, but I'd like to understand more.  Could you explain which overload was giving ``NoInfo``? Thanks

**Comment by dsyme** [comment]
@forki As background, the F# 3.1 rule was originally quite conservative.  We loosened it a bit in F# 4.0 (IIRC) which means that more type variable arguments were inferred, but in very extreme situations (basically totally artificial) one might image an overload set where this loosening would have caused a change of behaviour

I believe this represents another losening, but probably an OK one.  But because it is a language change we should analyze it carefully.

**Comment by forki** [comment]
The weird thing is there is only one overload but 4 elements are in the
lambda info. I don't really understand how it's supposed to work. My fix
was probably just a workaround

Am 05.06.2017 17:43 schrieb "Don Syme" <notifications@github.com>:

**Comment by dsyme** [comment]
@forki I think there are 4 overloads, see https://msdn.microsoft.com/en-us/library/system.linq.enumerable.todictionary(v=vs.110).aspx

I've taken another look and I like this fix, it is appropriate.

**Comment by forki** [comment]
ah cool. I was looking at intellisense and it was not showing more than one.

> It will be interesting to see if/how it helps with other overload sets.

haha ;-) this code was ancient.

**Comment by dsyme** [comment]
@cartermp @forki Note that this change should have had an RFC for tracking

**Comment by forki** [comment]
Can't even remember what this was about...

**Pull request merged**
