### PR TITLE
[WIP] find msbuild 15 on Jenkins

### PR DESCRIPTION
**Pull request by ctaggart**
Just trying to figure out if MSBuild 15 is installed somewhere on Jenkins.
https://github.com/Microsoft/visualfsharp/pull/2666#issuecomment-287967268

### CODE REVIEW

**Comment by ctaggart** [comment]
So, `MSBuild` it is not in:
```
20:39:58  Directory of C:\Program Files (x86)\Microsoft Visual Studio 15.0
20:39:58 
20:39:58 05/06/2016  04:25 PM    <DIR>          .
20:39:58 05/06/2016  04:25 PM    <DIR>          ..
20:39:58 05/06/2016  04:21 PM                 0 clearcache.changed
20:39:58 05/06/2016  04:10 PM    <DIR>          Common7
20:39:58 05/06/2016  04:15 PM    <DIR>          DesignTools
20:39:58 05/06/2016  04:13 PM    <DIR>          DIA SDK
20:39:58 05/06/2016  04:12 PM    <DIR>          enterprise
20:39:58 05/06/2016  04:10 PM    <DIR>          ImportProjects
20:39:58 05/06/2016  04:16 PM    <DIR>          JavaScript
20:39:58 05/06/2016  04:10 PM    <DIR>          lib
20:39:58 05/06/2016  04:17 PM    <DIR>          Licenses
20:39:58 05/06/2016  04:22 PM    <DIR>          PreEmptive Solutions
20:39:58 05/06/2016  04:10 PM    <DIR>          SDK
20:39:58 05/06/2016  04:09 PM    <DIR>          Setup
20:39:58 05/06/2016  04:09 PM    <DIR>          shell
20:39:58 05/06/2016  04:11 PM    <DIR>          Team Tools
20:39:58 05/06/2016  04:11 PM    <DIR>          VB
20:39:58 05/06/2016  04:15 PM    <DIR>          VC
20:39:58 05/06/2016  04:11 PM    <DIR>          VC#
20:39:58 05/06/2016  04:10 PM    <DIR>          Visual Studio Tools for Office
20:39:58 05/06/2016  04:25 PM    <DIR>          VSSDK
20:39:58 05/06/2016  04:11 PM    <DIR>          Web
20:39:58 05/06/2016  04:11 PM    <DIR>          Xml
```

**Comment by KevinRansom** [comment]
@ctaggart
I already commented here: https://github.com/Microsoft/visualfsharp/pull/2666

Snip:
msbuild releases are now stored alongside VS, so for example on my machine it is at:

````C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
````
because I have vs community edition installed.
I believe these are the lines in the current build.bat that find it:
````
if exist "%VS150COMNTOOLS%\..\..\MSBuild\15.0\Bin\MSBuild.exe" (
    set _msbuildexe="%VS150COMNTOOLS%\..\..\MSBuild\15.0\Bin\MSBuild.exe"
    goto :havemsbuild
)
````

Kevin

**Comment by ctaggart** [comment]
@KevinRansom I understand how the new VS 2017 installations work. Is VS 2017 installed on the Jenkins images? I can't seem to find MSBuild 15 installed. Can ya'll add a Jenkins page to the [wiki](https://github.com/Microsoft/visualfsharp/wiki) for the Jenkins build environment. 

One thing I found really useful is the Get-VSSetupInstance PowerShell Module:
``` powershell
Install-Module VSSetup -Scope CurrentUser -Force
$vs = Get-VSSetupInstance
$vs | fl
```

On my laptop, this shows:
```
PS C:\Users\CameronTaggart\fs\visualfsharp> $vs | fl


InstanceId          : 82e730bf
DisplayName         : Visual Studio Build Tools 2017
InstallationVersion : 15.0.26228.9
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
InstallDate         : 3/21/2017 8:21:22 AM

InstanceId          : 9c34071f
DisplayName         : Visual Studio Professional 2017
InstallationVersion : 15.0.26228.9
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
InstallDate         : 3/7/2017 11:00:52 AM
```

I was hoping to run that tool on Jenkins, but `Install-Module` is not found. 👎 

I can even use it to see what FSharp packages are installed:
```
PS C:\Users\CameronTaggart\fs\visualfsharp> $vs.Packages | where {$_.Id -like '*FSharp*'} | ft

Id                                      Version         Chip Language Branch
--                                      -------         ---- -------- ------
Microsoft.VisualStudio.Component.FSharp 15.0.26208.0
Microsoft.FSharp.Dependencies           4.1.20170225.2
Microsoft.FSharp.VSIX.Full.Resources    4.1.20170225.2
Microsoft.FSharp.VSIX.Full.Core         15.4.1.17022502
Microsoft.FSharp.SDK.Resources          4.1.20170225.2
Microsoft.FSharp.SDK.Core               4.1.20170225.2
```

Are you able to install MSBuild on Jenkins? It comes with https://www.visualstudio.com/downloads/ > Other Downloads > Build Tools for Visual Studio 2017 too.

To help show that MSBuild is not found on Jenkins where it should be, I changed build.cmd to be:
``` cmd
echo "VS150COMNTOOLS: %VS150COMNTOOLS%"
dir "%VS150COMNTOOLS%\..\..\MSBuild"
```

In the [output](https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/debug_windows_nt_prtest/2128/console), you will see:
```
06:46:18 D:\j\workspace\debug_windows---2f360ea4>echo "VS150COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\Tools\" 
06:46:18 "VS150COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\Tools\"
06:46:18 
06:46:18 D:\j\workspace\debug_windows---2f360ea4>dir "C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\Tools\\..\..\MSBuild" 
06:46:18  Volume in drive C has no label.
```

**Comment by KevinRansom** [comment]
@mmitche 

Matt, why does VS150COMNTOOLS point to the wrong location on our Jenkins machines?

It points to:  **C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\Tools\\..\..\MSBuild**

It looks like it is using a vs command batch file from an early preview!

What are we doing wrong here?  


Thanks

Kevin


````
D:\j\workspace\debug_windows---2f360ea4>.\build.cmd debug  

D:\j\workspace\debug_windows---2f360ea4>echo "VS150COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\Tools\" 
"VS150COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\Tools\"

D:\j\workspace\debug_windows---2f360ea4>dir "C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\Tools\\..\..\MSBuild" 
 Volume in drive C has no label.
 Volume Serial Number is F074-BCDF

 Directory of C:\Program Files (x86)\Microsoft Visual Studio 15.0

File Not Found
````

**Comment by mmitche** [comment]
I think that's because it is an early preview :D. It looks like there probably is a dev15 RTM version around,  I'm trying to track down which one it is.

**Comment by mmitche** [comment]
You want to change the 'latest-dev15' here https://github.com/Microsoft/visualfsharp/blob/master/netci.groovy#L80
to 'latest-or-auto-vs15-0'

The other labels are sort of misleading here as far as I can tell.  You all are the only ones using this old image, so as soon as this is gone, I can remove the old confusing label there.

**Comment by ctaggart** [comment]
@mmitche Where is Visual Studio 2017 or MSBuild 15 installed on `latest-or-auto-vs15-0`? Is there a good example of using this image? Are the images documented anywhere where it says what is installed and where?

**Comment by ctaggart** [comment]
That is an appropriate titled final commit. I've located MSBuild 15. Now that the build image was updated today to `latest-or-auto-dev15-0`, it is possible to use it. I'll update #2666 appropriately.

```
20:14:16 "VS150COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\"
20:14:16 C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
20:14:16 C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
20:14:16 Microsoft (R) Build Engine version 15.1.548.43366
```

**Pull request closed without merging**
