### PR TITLE
Refactor IDE options into a MEF part

### PR DESCRIPTION
**Pull request by majocha**
This hopefuly improves over the previous convoluted design where Settings object was effectively global static singleton, yet depended on some imports to work and required manual initialization in the language service.

With this change editor options service can be accessed:
- by importinig `EditorOptions` 
- from the Workspace services. There is `FSharpOptions` extension on the `Document` for that.

### CODE REVIEW

**Comment by KevinRansom** [comment]
@majocha,  nice

**Comment by KevinRansom** [comment]
@TIHan can you take a look at this please.

**Comment by cartermp** [comment]
Withholding my review until `master` is unblocked from proper acceptance testing.

**Comment by cartermp** [comment]
@majocha can you handle the merge conflicts? Sorry for this taking so long, we'd been bogged down in shipping and had CI woes that have finally been fixed.

**Comment by majocha** [comment]
Ah, yes, right. I think I know what's going on. I'll take a look today.

**Comment by KevinRansom** [comment]
@majoch …. sorry mate ... you should definitely blame @cartermp for these.

**Comment by majocha** [comment]
OK, that fail is probably not related.

**Comment by KevinRansom** [comment]
@majocha,  

Thanks for this mate.

**Pull request merged**
