### PR TITLE
Fixed: IncrementalBuilder may be created simultaneously from multiple threads

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by dsyme** [comment]
This looks good as a fix.  However we should also think hard how we could have avoided this via some kind of static check.  I think we need to start to adopt a model where we explicitly pass a token indicating what thread/threads we assume/require.

**Comment by dsyme** [comment]
@vasily-kirichenko See https://github.com/Microsoft/visualfsharp/compare/master...dsyme:tame-conc?expand=1 for a draft of what I mean by taming concurrency by passing tokens.

It's not a perfect technique, but applying it reveals the bug in this PR precisely - search for ``BUG_NotOnCompilationThread`` for the place where the token to prove we are on the compilation thread is not available at the getBuilder call.

It also shows up exactly the places which you said could be run concurrently, e.g. search for ``DoesNotSpecificallyRequireCompilerThreadAndCouldLikelyBeConcurrent``.

The idea, if extended further, would be to use this technique for as many of the root sources of single-threadedness as possible, e.g. troublesome non-concurrent dictionaries, or troublesome mutable data structures, or type provider invocations, to continue to lock things down.  

The biggest problem with the technique is that the tokens can be captured by member or callbacks which are then stored and invoked on a different thread.  Unsafe transfer of ownership.  

Another problem is that applying the technique to the raw TAST data structures (which can be lazily expanded via type provider calls) we mean passing tokens all the way through almost every TAST-related operation in the compiler.  That's because so many paths ultimately lead to this:
```
    /// Try to find the entity corresponding to the given path, using type-providers to link the data
    static member TryDerefEntityPathViaProvidedType(ccu: CcuThunk, path:string[], i:int, entity:Entity) = 
```

via ``Deref`` and ``TryDeref`` on ``Entity`` and ``EntityRef``.  Propagating tokens to those points would be painful.  That's the whole magic of type providers of course - the symbol-linking operation is an extension point  calling user-defined code buried right in the guts of the compiler.  A judiciously placed set of ``RequireCompilationThread`` on higher level operations may be enough to deal with this issue.

BTW one major place where this problem reduces the effectiveness of this technique is in the FCS ``Symbol`` API.   We currently **don't**  lock things down correctly for that API - normally this isn't a problem since most of the backing TAST data is immutable and doesn't raise exceptions - but using the properties and methods on symbols **can** trigger type provider operations. Those should really go via the reactor thread or otherwise be made safe.  We'll need to take a close look at this soon since the use of symbols from caller threads will become much more common.  

Anyway - I think we should tighten our concurrency by static token passing - it finds bugs, even if imperfect.

**Comment by vasily-kirichenko** [comment]
This change is already in master (it came in https://github.com/Microsoft/visualfsharp/pull/2348, see https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L2525)

**Comment by dsyme** [comment]
@vasily-kirichenko I will prepare the token-based checking for review, and add a section on concurrency in the compiler and compiler service to the compiler guide.

**Comment by vasily-kirichenko** [comment]
@dsyme great.

**Pull request closed without merging**
