### PR TITLE
Additional testing for CoreCLR and make it easier to play with F# Compiler and Interactive on CoreCLR

### PR DESCRIPTION
**Pull request by dsyme**
I spent some time looking into FSI.EXE on CoreCLR

After this PR you can run

    fsi tests\scripts\fscc.fsx
    fsi tests\scripts\fsci.fsx

These are shims for CoreCLR fsc.exe and fsi.exe respectively

- the first ``fsi`` is the .NET Framework fsi used to run the shim
- these then respectively invoke the CoreCLR fsc.exe and fsi.exe with sensible defaults.  The fscc.fsx is an evolution of ``CompileProj.fsx`` and replaces it.

This also makes more improvements to the ``fsharp`` suite.

### CODE REVIEW

**Comment by dsyme** [comment]
@KevinRansom I did some more work on this

* Enable one "fsharp" suite test that drives the CoreCLR compiler
* Make some improvements to the ``fsci.fsx`` driver
* Make sure we only have one copy of FSharp.Compiler.Interactive.Settings loaded through the better techniques we discussed last night, where we no longer access this component directly from fsi.fs.  It turns out these changes were very similar to a set of changes in FSharp.Compiler.Service, so I incorporated those changes into ``fsi.fs``.

I think it's ready to go through once we're green

**Comment by mmitche** [comment]
@dotnet-bot test this please (test ci move)

**Comment by dsyme** [comment]
@mmitche Could you explain what the "test this please" thing is?  Do we need to do it or are you testing something?  Just curious.  Also should we update the badges on README.md?

**Comment by mmitche** [comment]
@dsyme it restarts all the tests on the PR.  I moved you to the other CI server and wanted them to kick off again there.

It looks pretty decent so far, so I'll probably update the badges in a bit.

**Comment by dsyme** [comment]
@dotnet-bot test this please (test ci move)

**Comment by KevinRansom** [comment]
@dsyme can you use Squash and Merge when accepting PR's pls.

**Comment by dsyme** [comment]
@KevinRansom Sorry my bad - I meant to

**Comment by KevinRansom** [comment]
@dsyme ... lol.  It's not a problem ...

**Pull request merged**
