### PR TITLE
Fix 99: remove restriction on static linking

### PR DESCRIPTION
**Pull request by dsyme**
This is our oldest [Urgency-Soon](https://github.com/Microsoft/visualfsharp/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Abug%20label%3AUrgency-Soon%20) bug https://github.com/Microsoft/visualfsharp/issues/99.  There is simply no need for this restriction any more after previous fixes in this area.  I've verified by hand that it fixes the problem and the resulting DLL is verifiable.

Also includes a bunch of further simplifications to the "fsharp" test suite

### CODE REVIEW

**Comment by dsyme** [comment]
@KevinRansom Good question.  

The specific case we're aiming to enable is static linking say a Profile 7 DLL into the compilation of a .NET 4.x component.  That will work fine after this change (things like System.String are emitted as ELEMENT_TYPE_STRING, and new dependencies are injected on things like System.IO.dll and System.Threading.Tasks.dll).  I can add a test for this case.

Now you're worried about the other way around: linking a .NET 4.x component into a Profile 7 component .  However (when using an F# project file),  MSBuild won't allow you to reference the .NET 4.x component from a Profile 7 component, so this should never happen.

So I think the compatibility checks basically are up to MSBuild, not the F# compiler.

**Comment by dsyme** [comment]
@KevinRansom I've added a test case here: https://github.com/Microsoft/visualfsharp/pull/1741/commits/ca264b785d10230ed6bfec3272ab266adbd8c53c#diff-2dc1b4dc7af7a030af46349856047de0R1122

**Comment by dsyme** [comment]
@KevinRansom OK will add that check, makes sense that way around

**Comment by dsyme** [comment]
OK, check added, thanks.

**Comment by KevinRansom** [comment]
This is great ... thanks

**Comment by dsyme** [comment]
Just to mention that the CI run got this unrelated error during testing:
```
+++ ClrFx\PseudoCustomAttributes\AssemblyVersion (AssemblyVersion_001.fs) +++
Failed to Find Any Target:  
FAIL
```

**Pull request merged**
