### PR TITLE
[WIP] Fix inlline rename at end of file

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This is how the editor looks (the bug):

image

This is how the preview looks (OK):

image

This is new document text in the debugger (OK):

image

The renaming works correctly as well (I mean it changes the document properly after committing).

So the only place where we have bad behavior is the green spans. 

@Pilchie @dsyme Maybe it helps to narrow areas where the bug can sit? Thanks.

### CODE REVIEW

**Comment by Pilchie** [comment]
@dpoeschl or @jasonmalinowski Either of you have any idea?

**Comment by jasonmalinowski** [comment]
Just clarifying: does this PR fix the behavior you're seeing (and we're trying to understand why) or fails to do so and we're still trying to understand what's wrong?

**Comment by vasily-kirichenko** [comment]
@jasonmalinowski This PR does not fix the bug.

**Comment by vasily-kirichenko** [comment]
This is how it works at the moment:



that is, the renaming itself works, but the preview (green spans) are wrong.

**Comment by cartermp** [comment]
@dotnet-bot test this please

**Pull request merged**
