### PR TITLE
WIP: Enable OPTIMIZE_LIST_MATCHING and make it compile

### PR DESCRIPTION
**Pull request by forki**
EXPERIMENTAL - Please don't merge

releates to #1267

### CODE REVIEW

**Comment by dsyme** [comment]
@forki  I took a look at this. The code was very old, based on F# 1.0 where lists used separate types "List.Nil" and "List.Cons", and discrimination was done by an isinst test.  In F# 2.0 we moved to doing discrimination by looking for a "nil" in the "TailOrNull" cell to indicate the empty list.

I updated the code here, at least to a first approximation, and tried it on a very small test case.   I have no idea if it is faster as yet, and certainly there are more locals created.  More locals are not necessrily bad for a good JIT compiler that does register allocation properly.  

(NOTE: Using the compiler as a perf test case can be tricky in cases like this, because the fact that there are more locals might mean that the bootstrapped compiler takes longer to emit a binary or PDB, i.e. you have to be careful to compare like-for-like )

https://github.com/dsyme/visualfsharp/compare/struct-unions-2...dsyme:list-match?expand=1


The branch is based on the "struct-unions-2" branch for PR #1262 since there were some changes in this region. It probably doesn't have to be

**Comment by forki** [comment]
@dsyme I updated my PR with your changes.

* the compiled code brings the correct result
* the compiled code is still slower

image

My guess is that the additional call to get_HeadOrDefault is the issue.

**Comment by forki** [comment]
If I change the code slightly to

    let add_rec xs =
        let rec add xs acc =
            match xs with
            | [] -> acc
            | _::t -> add t (acc + 1)
        add xs 0

(I used _::t instead of h::t) - then I get:

image

so in this case the get_HeadOrDefault is not generated. But it's still the same slow runtime.

**Comment by dsyme** [comment]
@forki It's really hard to tell why that loop is not handled just as efficiently as the one generated for the imperative ``for`` loop.  It must surely be either

* the x86 JIT preferring some looping forms over others
* the x86 JIT not liking functions that mutate arguments
* branch prediction, alignment or some other processor effect

I note that this code is fast:
```
let add_mutable2 (xs: 'T list) =
    let mutable count = 0
    let mutable xs = xs
    let mutable fin = false
    while not fin do 
        match xs with 
        | [] -> fin <- true
        | _::t -> count <- count + 1
                  xs <- t
    count
```

One methodology from here would be to switch to mucking with IL by hand (i.e. using an editor and ILASM), and incrementally change the IL of the "for" loop to the IL of the "rec" code, and see which change introduces the performance change. There's only a limit to how much we can second-guess the JIT though.

**Comment by forki** [comment]
wow. you are right add_mutable2 is same perf like the for loop.

weird

**Comment by liboz** [comment]
@dsyme So I did some of that manual IL massaging. And found that not store/loading the FSharpList `xs` from the arguments seems to have been what is the key to the performance differences. 

It didn't seem to be a general problem with mutating arguments, because changing the int32 `acc` to a local didn't help at all.

Here's what I had:

```
.method assembly static 
		int32 add@17<b> (
			class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!b> xs,
			int32 acc
		) cil managed 
	{
		// Method begins at RVA 0x20d8
		// Code size 32 (0x20)
		.maxstack 5
		.locals init (
			[0] class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!b>
		)
        IL_0000: ldarg.0
		IL_0001: call instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!b>::get_TailOrNull()
		IL_0006: stloc.0
		// loop start
			IL_0007: ldloc.0
			IL_0008: brfalse.s IL_001e
			IL_0014: ldloc.0
            IL_00019: call instance class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!0> class [FSharp.Core]Microsoft.FSharp.Collections.FSharpList`1<!!b>::get_TailOrNull()
            IL_00020: stloc.0
            IL_00021: ldloc.0
		
			IL_0015: ldarg.1
			IL_0016: ldc.i4.1
			IL_0017: add
			IL_0018: starg.s acc
			IL_001a: stloc.0
			IL_001c: br.s IL_0007
		// end loop

		IL_001e: ldarg.1
		IL_001f: ret
	} // end of method Program::add@17
```

**Comment by dsyme** [comment]
@liboz Thanks, that's hugely interesting.  It seems plausible that mutating reference-typed arguments causes the performance problem.

Is it correct that this is only a problem when using the 32-bit JIT?

**Comment by liboz** [comment]
@dsyme Yes, the problem only appears for the 32-bit JIT. The 64-bit JIT doesn't appear to have the problem.

**Comment by dsyme** [comment]
I'm in two minds as to whether to try to fix this (by inserting fake locals in tail-calling functions rather than assigning to args).  There's a chance it will help performance of FSharp.Core functions and even the F# compiler itself (which runs as a 32-bit process).  On the other hand it feels like a nasty limitation of the Microsoft 32-bit JIT (which is not really being changed or updated much these days AFAIK).  It feels awkward to insert extra locals just for one JIT.  But equally if the perf of the F# compiler depends upon it then....

**Comment by forki** [comment]
I think would be worth a try, but I don't know how ;-)

**Comment by dsyme** [comment]
@forki The change would be in IlxGen.fs.  

The aim would be to get rid of the use of ``Arg`` representations for the arguments of self-tailcalling functions and methods and use ``Local`` representations instead.

Here is [the ``Arg`` representation](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/IlxGen.fs#L626)

Here is [where we store updated values into the arguments when a direct tailcall to the method currently being emitted](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/IlxGen.fs#L2385).  These would become ``stloc`` oeprations.

This is where we give the Arg representation (st least for functions/methods - closures, delegates and object expression methods would still keep using ``Arg``):

    let eenvForMeth = AddStorageForLocalVals cenv.g (List.mapi (fun i v -> (v,Arg (numImplicitArgs+i))) nonUnitMethodVars) eenvForMeth

So the idea would be to use ``Local`` representations for the values corresponding to the arguments of tailcalling methods and functions.  We'd then emit a whole bunch of ``ldarg``/``stloc`` calls at the head of the method [before emitting the ``start`` mark at the head of the method code](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/IlxGen.fs#L1553).  

One annoying thing is that determining when a method or function is self-tailcalling is a PITA. The TAST doesn't have that information in it.  At the moment we just discover it along the way.  

As an aside, the way we currently store into the arguments could plausibly be the problem - we evaluate arg1, arg2, arg3 on the IL stack then store them into arguments 3,2,1 in reverse order.  This might confuse a JIT I guess

**Comment by dsyme** [comment]
@forki I will close this PR for now since the performance issue wasn't what we thought it was :)  If we want to resurrect this later we can come back to it

**Pull request closed without merging**
