### PR TITLE
Put nupkgs into artifacts

### PR DESCRIPTION
**Pull request by forki**
/cc @KevinRansom please merge

### CODE REVIEW

**Comment by KevinRansom** [comment]
@forki ... shortly we are playing release train branch bingo right now.  I will get both this and the fcs pr as soon as I can.

**Comment by forki** [comment]
Can you please merge just this one for now then. Then pull requests of
other stakeholder like fable, ionide, rider, fake and Co. can actually
temporarily rebase on the other one and produce nupkg on CI to use fcs
custom builds  downstream.


Am 24.10.2017 22:23 schrieb "Kevin Ransom (msft)" <notifications@github.com
>:

*@KevinRansom* approved this pull request.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/pull/3806#pullrequestreview-71659645>,
or mute the thread

**Comment by KevinRansom** [comment]
As soon as this goes green and is merged :  https://github.com/Microsoft/visualfsharp/pull/3810

Will be less than an hour.

**Comment by forki** [comment]
Awesome. Thanks

Am 24.10.2017 22:29 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by KevinRansom** [comment]
thanks for this.

**Pull request merged**
