### PR TITLE
Allow WsdlTypeProvider to work on a fresh install of Windows 10/VS2015.

### LINKED ISSUE #637: Wsdl type provider doesn't work on clean install of Windows 10
Following the tutorial at https://msdn.microsoft.com/en-us/library/hh156503.aspx, I'm in trouble early on:
screenshot 2015-09-19 22 55 52

> The type provider 'Microsoft.FSharp.Data.TypeProviders.DesignTime.DataProviders' reported an error: The .NET SDK 4.0 or 4.5 tools could not be found	ConsoleApplication2	c:\users\robert\documents\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.fs	8

This is related to finding sdk locations in https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Data.TypeProviders/Util.fs#L105

I imagine the Sql TP has the same problems for the same reason (finding SqlMetal.exe), but I haven't tested it.

### PR DESCRIPTION
**Pull request by rojepp**
I replaced the nesting with a list of candidates. Fixes #637

### CODE REVIEW

**Comment by KevinRansom** [comment]
We are not too sure what to do about this.  We have basically frozen those type providers.  As of the VS 2012 release.  We have long wanted to move them to an open source, deployed by nuget model, but due to many conflicting priorities haven't got around to it.

**Comment by rojepp** [comment]
Well, this PR makes it work, at least, so I feel it should be included in the OOB update. They're not being pulled out now anyway?

**Comment by rojepp** [comment]
Ripping these out is discussed in #441. It seems the change in this PR is also discussed there.

**Comment by KevinRansom** [comment]
I will take another look, fwiw … I agree that shipping a dll broke against the latest version of our tools is not ideal.

**Comment by KevinRansom** [comment]
Committed, thank you for your contribution.

**Pull request closed without merging**
