### PR TITLE
Hotfix for Code / Line Lens

### PR DESCRIPTION
**Pull request by realvictorprm**
This commit provides last but important fixes for the code / line lens. See the commit message.

cc  @KevinRansom 

There are only 2 known UI issues to me which luckily only appear on entering new lines.
1. Code Lens are misaligned if a new line is entered before a line of e.g. member definitions (They jump to the left). This is due to a visual studio bug and I'm going to figure out what's going wrong with a VS dev (hopefully).
Workaround: 
a) Enter another line and remove the line afterwards. They now should be correctly aligned.
or
b) Use Line Lens
2. Code / Line Lens are misaligned after a newline is entered before a couple of lines containing them (I'm trying to find out what's wrong right now...)
Workaround:
a) from above
b) Enter a line between each definition, the bug shouldn't appear anymore.

PS:
I was surprised by the merge as I was working on the fix and didn't notice it! 😄 
Thank you very much for merging!

### CODE REVIEW

**Comment by realvictorprm** [comment]
Okay I've resolved the conflicts...

**Comment by KevinRansom** [comment]
@realvictorprm I am going to move it to the code to the branch dev15.8, then we can stabilize it, without having to rush for 15.7

**Comment by realvictorprm** [comment]
Good idea, many thanks @KevinRansom

**Comment by realvictorprm** [comment]
Side note, performance etc. isn't a problem with the Code Lens :)

**Comment by realvictorprm** [comment]
Going to put a new PR for the dev branch including a new branch on my side.

**Comment by KevinRansom** [comment]
Okay.

**Pull request closed without merging**
