### PR TITLE
[FS-1030] - Anonymous records

### PR DESCRIPTION
**Pull request by dsyme**
Replaces https://github.com/Microsoft/visualfsharp/pull/2671

This adds anonymous records to the F# compiler per [RFC FS-1030](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1030-anonymous-records.md).

Please discuss on [the RFC](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1030-anonymous-records.md) or below - if the discussion gets long we will move to the RFC discussion thread.

The implementation is now complete (apart from copy-and-update) and I believe it to be stable and usable.

Implementation:
* [x] Equality, hash and comparison on ``{| X = 1; Y = 2 |}`` Kind B types 
* [x] ToString on ``{| X = 1; Y = 2 |}`` Kind B types 
* [x] ``sprintf "%A"`` on ``{| X = 1; Y = 2 |}`` Kind B types 
* [x] Quick info 
* [x] Auto complete
* [x] Highlight symbols
* [x] F# Interactive multiple fragments
* [x] Find all references 
* [x] Field ordering is no longer significant
* [x] Quotations
* [x] Reflection
* [x] Additions to Symbols.* FCS API 
* [x] Allow cross assembly references via known types
* [x] Generate ToString method for better debugging
* [x] Go-to-definition
* [x] Copy-and-update
* [ ] suggestions

Testing:
* [x] Unit testing for language service features 
* [x] LINQ queries 
* [x] Add tests for negative case error messages
* [x] Add more testing where anon types are mentioned in types but not expressions
* [x] Add more testing for cross-assembly cases
* [x] Testing for Symbols.* FCS API 

For trial:
* [ ] Test suitability of ``{| X = 1; Y = 2 |}`` types for working with known common libraries accepting C# anonymous types (e.g. ASP.NET routing? ML.NET?)

Here is the view of an anonymous value in the VS2017 debugger:

image

If anyone wants to give a hand with the testing that would be great. I think it's really important that someone else besides myself do serious testing on this feature. I'd love someone to try this out and give early feedback on usability and "fit and polish".

### CODE REVIEW

**Comment by dsyme** [comment]
Updated to master, and now F# Interactive now works properly:

```
> let a = {|  X = 1 |};;
val a : {|X : int|} = {X = 1;}

> a = {|  X = 1 |};;
val it : bool = true

> #q;;
```

**Comment by majocha** [comment]
What is the story with type inference?
At the moment stuff like this 
```
let y = {| V = "hi!" |}
let f x = x.V
```
doesn't work (asks for type annotation) but lambdas are inferred fine. Is this by design?

**Comment by smoothdeveloper** [comment]
@majocha I think in the example you give, the type inference will only work with record types.

I don't see why it would infer from anonymous type that happens to be defined in same scope.

Lambdas are infered because they actually carry the type of the expression at their usage spot.

the following type annotation should work:
```fsharp
let y = {| V = "hi!" |}
let f (x: {|V:string|}) = x.V
```

**Comment by dsyme** [comment]
@majocha Yes, type annotations are necessary in cases where type information has not flowed to the point of use.

**Comment by dsyme** [comment]
OK, this feature is now ready.  It would be great if someone could give this a full review, and if people could read the RFC very, very carefully.

**Comment by Savelenko** [comment]
1) The RFC is a bit unclear about adding fields, seemingly putting this out of scope/orthogonal in one section and giving examples in another. So is it or is it not possible to add fields with `with`?

2) Why no pattern matching, is there some technical limitation? Is this somehow connected to “no row polymorphism”, as nominal record pattern matching allows leaving out fields? Especially with nested pattern matching this seems like an “ad-hoc” limitation given that other pattern matching forms are so nicely combinable. I think this special case may be quite annoying to many F# programmers and limits expressivity. For example, not being able to do this:

```
| Some {| X = x |} -> f x
| None -> y
```

**Comment by dsyme** [comment]
@Savelenko Thanks for that feedback - I will clarify the RFC and think about pattern matching.  You are right that matching a subset of fields is already valid for records and makes sense for anonymous records too. It would not be hard to add.

**Comment by dsyme** [comment]
@Savelenko  See https://github.com/fsharp/fslang-design/pull/265, thanks

**Comment by forki** [comment]
image

I personally would prefer if would just print the set difference here.

**Comment by isaacabraham** [comment]
The RFC mentions abbreviations a couple of times with regards to anonymous records - but I couldn't find any examples of how one would actually define such an abbreviation?

Related to this - how will this function with regards to type inference e.g. imagine calling a function `foo`:

```fsharp
let foo bar =
    bar.X + bar.Y
```

where `bar` is an anonymous record created elsewhere (not in scope). What are our options for type hint to tell the compiler that this is an anonymous record? Will the compiler just assume that this is an anonymous type (which would be a change to current behaviour which would be a compiler error)? If not, how would we indicate this to the compiler - like this?

```fsharp
let foo (bar : {| X : int; Y : int |}) =
    bar.X + bar.Y
```

**Comment by forki** [comment]
image

we are missing suggestions here.

**Comment by forki** [comment]
Is it expected that we don't have the pipes in ToString() ?

image

**Comment by forki** [comment]
image

maybe we should print the field name in this case?

**Comment by realvictorprm** [comment]
Would be so much fun to change this but I've not enough time :(


I agree with your feedback so far @fork!
Also pattern matching would be superb.

Anyways I'm still not sure how often I'm going to use anonymous records...

Am 15.03.2018 9:07 vorm. schrieb "Steffen Forkmann" <
notifications@github.com>:

**Comment by realvictorprm** [comment]
The CI failes with:
```
17:16:59 1>    Compiling assembly FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:16:59 2>    Compiling assembly System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (CLR v4.0.30319) ...
17:16:59 Failed to load dependency System.Threading.Tasks.Dataflow of assembly Microsoft.Build, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
17:16:59 2>    Compiling assembly System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (CLR v4.0.30319) ...
17:17:03 2>    Compiling assembly FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:17:03 1>    Compiling assembly FSharp.Compiler.Private, Version=10.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:17:03 3>    Compiling assembly FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:17:03 2>    Compiling assembly D:\j\w\release_ci_pa---866fd2c3\release\net40\bin\FSharp.Build.dll (CLR v4.0.30319) ...
17:17:03 3>    Compiling assembly FSharp.Compiler.Server.Shared, Version=15.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:17:33 1>    Compiling assembly D:\j\w\release_ci_pa---866fd2c3\release\net40\bin\fsc.exe (CLR v4.0.30319) ...
17:17:33 2>    Compiling assembly FSharp.Compiler.Private, Version=10.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:17:33 2>    Compiling assembly D:\j\w\release_ci_pa---866fd2c3\release\net40\bin\fsi.exe (CLR v4.0.30319) ...
17:17:33 Failed to load dependency System.Threading.Tasks.Dataflow of assembly Microsoft.Build, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
17:17:33 1>    Compiling assembly FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:17:34 2>    Compiling assembly System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (CLR v4.0.30319) ...
17:17:39 1>    Compiling assembly D:\j\w\release_ci_pa---866fd2c3\release\net40\bin\FSharp.Build.dll (CLR v4.0.30319) ...
17:17:39 2>    Compiling assembly FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:17:39 3>    Compiling assembly FSharp.Compiler.Server.Shared, Version=15.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:17:39 2>    Compiling assembly FSharp.Compiler.Private, Version=10.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (CLR v4.0.30319) ...
17:18:15 1>    Compiling assembly D:\j\w\release_ci_pa---866fd2c3\release\net40\bin\fsiAnyCpu.exe (CLR v4.0.30319) ...
```

**Comment by gibranrosa** [comment]
@isaacabraham some posts before @dsyme already clarify this: 
"@majocha Yes, type annotations are necessary in cases where type information has not flowed to the point of use. This is a major limitation of the feature

You can leave the types incomplete like this

let f (x: {|V: _|} ) = x.V"

**Comment by isaacabraham** [comment]
@gibranrosa cheers, I thought as much, but wasn't 100% sure what "abbreviations" meant though :-)

**Comment by dsyme** [comment]
@dotnet-bot Test Windows_NT Release_ci_part2 Build please

**Comment by dsyme** [comment]
Current failure is peverify for the anon test:
```
1) Failed : FSharp-Tests-Core+CoreTests.anon-FSC_BASIC
Error running command 'D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\..\fsharpqa\testenv\src\PEVerify\bin\release\net46\PEVerify.exe' with args 'lib.dll /nologo' in directory 'D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\core\anon'. ERRORLEVEL 4
at TestFramework.checkResult(CmdResult result) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 235
at TestFramework.exec@415-22.Invoke(CmdResult result) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 415
at TestFramework.peverify@431-3.Invoke(String path) in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\test-framework.fs:line 431
at FSharp-Tests-Core.CoreTests.anon-FSC_BASIC() in D:\j\w\release_ci_pa---866fd2c3\tests\fsharp\tests.fs:line 243
```

**Comment by forki** [comment]
@dsyme I was looking into adding suggestions and making the following case work:

  let x = {| Name = "Isaac" |};;
  let foo v = v.Name;;  // type inference issue

But then I noticed that the anon type is never added to the Name Res environment for lookup. I would have expected to find the "Name" in nenv.eFieldLabels (or a new eAnonTypeFieldLabels), this would allow me to do reverse lookup in NameResolution.fs

**Comment by isaacabraham** [comment]
@forki whilst I can imagine that this could cause more complexity, I see it as being an important feature to make anonymous records much more usable. Otherwise, we need to fall back to type hints, and the lack of structural typing / row polymorphism could make this too onerous to use except for in the most trival cases.

**Comment by dsyme** [comment]
> @forki whilst I can imagine that this could cause more complexity, I see it as being an important feature to make anonymous records much more usable. Otherwise, we need to fall back to type hints, and the lack of structural typing / row polymorphism could make this too onerous to use except for in the most trival cases.

We need to be clear about what this feature is and isn't. As designed, you will very often find yourself moving quickly from anonymous records (a prototype) to records for any data you start to write functions over, i.e. which is not ephemeral (temporary in a query, immediately consumed by printing/display/UI/..., returned as a structured result etc. etc.).  That's pretty explicit in the RFC but I'll make it more so.

That would apply in a number of many ways: where else are you going to put documentation?  Where else are you going to put attributes?   Those very fundamental practicalities of software engineering would apply even if we had more powerful record-calculus features: row-polymorphism doesn't give you a strong place to put the documentation, and doesn't particularl

The feature is _not_ a data modelling feature.  It's a I-can't-be-bothered-to-write-the-record-type-feature

**Comment by forki** [comment]
Oh yes absolutely agree with that idea. But still think suggestions would be important. It's one of the things that really really helped my team to get things working very fast.

**Comment by isaacabraham** [comment]
@dsyme I generally agree with what you're saying here. I'm not proposing adding everything to anonymous records that "full" records have etc. - but I can imagine e.g. several private functions in a module that all share the same type which is local to those functions.

Consider the following:

```fsharp
[ 1 .. 10 ]
|> List.map(fun n -> {| Square = n * n; Number = n; |}) // create anonymous record
|> List.filter(fun n -> n.Square < 10) // use it here - all compiles, happy
```

Now the developer decides to move those lambdas in let-bound functions:

```fsharp
let toSquare n = {| Square = n * n; Number = n; |}
let isSmallSquare n = n.Square < 10 // will this compile?

[ 1 .. 10 ]
|> List.map toSquare
|> List.filter isSmallSquare
```

From the developer point-of-view, they've simply moved from a lambda to a let-bound function, nothing should change. But in this case it will, I suppose.

I know that there are cases where stuff like this already happens in the compiler - I'm just thinking that if the boundaries of what anonymous records are pushed just a *little bit* further, then they may become even more useful than they undoubtedly already will be.

**Comment by matthid** [comment]
@isaacabraham I think it is fine if your example doesn't compile. Similar things already happen on other places in the language.

I think the general "fix" for this is to extend `inline` as suggested by @drvink here: https://github.com/Microsoft/visualfsharp/pull/4563#issuecomment-373846513

**Comment by 7sharp9** [comment]
Language with first class row-polymorphism generally have a mechanism to constrain a function to accept a record with a certain named label and type, or a mechanism to extend/subtract a record by adding a new label etc.  I don't think anonymous records should be associated with row polymorphism otherwise people will be expecting features that are never going to exist in this context.  Row polymorphism is not about being lazy with documentation its about abstracting the concept of a record.  

Perhaps moving `Design Principle: No row polymorphism` in the RFC to the top of the list will give that intension faster.

**Comment by dsyme** [comment]
@dotnet-bot test Ubuntu16.04 Release_fcs Build please

**Comment by dsyme** [comment]
@dotnet-bot test Ubuntu16.04 Release_default Build please

**Comment by dsyme** [comment]
I've updated this and integrated it with master

**Comment by jackfoxy** [comment]
When will we see this in an F# release?

**Comment by panesofglass** [comment]
Will anonymous records play well with quotations and query expressions? I could see a very large use case around using these in the same way anonymous objects are used in C# LINQ expressions. I'll try to have a play with that and add tests if time permits.

**Comment by cartermp** [comment]
@jackfoxy We're striving for a release of the language for VS 2019 RTW. We'll merge this when it is ready (likely after VS 15.9 RTW), and it'll be in the nightly feed once that happens.

@panesofglass We'll gladly await that feedback when this is merged 🙂

**Comment by dsyme** [comment]
Finally updated, lets get this baby green

**Comment by dsyme** [comment]
@cartermp This is ready, I believe we should merge now.

There are a couple of other possible extensions which I'd like us to consider, e.g. can you construct nominal record instances from anonymous record instances:

    type R = { X : int; Y: int; Z: int }
    let data = {| X = 1; Y = 2 |}
    let data2 : R = { data with Z = 3 }

As mentioned in the RFC this breaks the principle of "easy nominalization" since the following is not allowed:


    type R = { X : int; Y: int; Z: int }
    type Data = { X : int; Y: int }
    let data = { X = 1; Y = 2 }
    let data2 : R = { data with Z = 3 }

because the last line constrains "data" and "data2" to be the same type.  However in the presence of enough type annotations like above we could lift this restriction.

I'll mention this in the RFC and consider it, however what we have in this PR seems feature complete given the RFC and would allow extensions like the above.

**Comment by auduchinok** [comment]
@dsyme Could we please consider adding language versioning before merging features that older compilers (and FCS versions) won't be able to work with? I proposed it in https://github.com/Microsoft/visualfsharp/issues/5496 and got no discussion about environments other than VS.

**Comment by dsyme** [comment]
@auduchinok It's a very sensible question and I think we have to discuss this in #5496 - we won't stop language development just because of the reply that's been given there.

**Comment by auduchinok** [comment]
@dsyme Sure, I didn't mean to stop the development at all. :) I just think it was the right moment to mention the problem.

**Comment by dsyme** [comment]
Odd failure in CI run above when previous run had been green, I've not seen this fail before and seems unrelated:
```
2018-10-24T11:55:58.1320022Z 1) Failed : Tests.LanguageService.Script.UsingMSBuild.TypeProvider.Disposal.SmokeTest2
2018-10-24T11:55:58.1320127Z   Check3, countCreations() = i, iteration 43
2018-10-24T11:55:58.1320189Z   Expected: True
2018-10-24T11:55:58.1320316Z   But was:  False
2018-10-24T11:55:58.1320540Z at Tests.LanguageService.Script.UsingMSBuild.TypeProviderDisposalSmokeTest(Boolean clearing)
2018-10-24T11:55:58.1320647Z at Tests.LanguageService.Script.UsingMSBuild.TypeProvider.Disposal.SmokeTest2()
```

**Comment by dsyme** [comment]
@cartermp Should we go ahead with this?  I'd be happy not to have to maintain the branch any more :)

**Comment by cartermp** [comment]
I'd like to get one last @KevinRansom checkoff but otherwise yes we should get this in so we can flight it in previews.

**Comment by alfonsogarciacaro** [comment]
Please move this quickly to FCS when it's merged so we can see how anonymous records work in Fable and give our feedback :)

**Comment by forki** [comment]
Summoning mighty @ncave ;-)

Alfonso Garcia-Caro <notifications@github.com> schrieb am Di., 30. Okt.
2018, 16:31:

**Comment by ncave** [comment]
@forki Needs to trickle down to FCS first in order for Fable to use it, hopefully soon after it's merged.

**Comment by forki** [comment]
Yes I know ;-)

ncave <notifications@github.com> schrieb am Di., 30. Okt. 2018, 17:40:

**Comment by cartermp** [comment]
@TIHan @KevinRansom can we get a review here? I really want to get this into 16.0 preview 2.

**Comment by baronfel** [comment]
would be great to get a prerelease of FSharp.Compiler.Tools for us non-VS-usable folks to test as well. What's the process there?

**Comment by forki** [comment]
Yes it needs to go to fcs and then we test it in fable. Transpile to
dynamic language will be best test that you can get.

Am Di., 6. Nov. 2018, 19:29 hat Chet Husk <notifications@github.com>
geschrieben:

**Comment by vasily-kirichenko** [comment]
To test it, we need FSharp.Compiler.Tools built from master.

**Comment by boeremak** [comment]
Wow, this is great, I was having an issue where I could really use this feature and now I come to find out it has been merged an hour ago. Way to go guys. :)

**Comment by cartermp** [comment]
@vasily-kirichenko Feel free to build FCT out of master.

@forki you can build FCS out of master today - AFAIK this is what @Krzysztof-Cieslak does for some Ionide releases.

We'll pull in other PRs related for an F# 4.6 and rev the versions of all assets so we can start shipping an F# 4.6 preview through the .NET CLI as well.

**Comment by vasily-kirichenko** [comment]
good trolling

**Comment by dsyme** [comment]
As we've discussed before in a few places it is fairly difficult to roll out updates to all of the required tooling for all editor stacks instantly,  even for master branch.  FCT (fsharp/fsharp) and FCS (fsharp/FSharp.Compiler.Service) are built and released from master but I only tend to do that once the corresponding VS release corresponding to that master is near final.

But I understand why it would be great to roll these out immediately.

**Comment by cmeeren** [comment]
Has this been released in relative silence? I'm using VS 15.9.5 (no VF# nightlies) and am able to use anonymous records, but I can't find anything about this fantastic feature in any VS release notes.

**Comment by cartermp** [comment]
@cmeeren If you're using it then you have either a nightly build or a self-built VSIX installed. This was not released yet.

**Comment by cmeeren** [comment]
Hm, strange. Does the information below indicate a more version other than the one shipped with VS?

```
Microsoft Visual Studio Professional 2017 
Version 15.9.5
VisualStudio.15.Release/15.9.5+28307.280
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

...

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: ace88e6d3ffaf5e4ada0153a56e78ad0a75e82c8.
Microsoft Visual F# Tools 10.2 for F# 4.5

...
```

**Comment by cartermp** [comment]
Check the extensions page (Tools > Extensions and Updates) to see the version there.

**Comment by cmeeren** [comment]
Would you look at that, I did in fact have a nightly installed... 😅😳 I was certain I had uninstalled it long ago. Sorry for the trouble!

**Comment by alfonsogarciacaro** [comment]
I'm a bit sad about this. Without getting any hint from the F# team and after spending a lot of time to investigate this myself, I've finally realized this has shipped without including anonymous records in the AST exposed by `FSharpImplementationFileContents` (`src/fsharp/symbols/Exprs.fs` hasn't be updated except for a couple of lines) so anonymous records remain invisible to Fable. There's only support for symbols in editors 😞

**Comment by cartermp** [comment]
@dsyme any idea what it would take to add the relevant case to this so that `fsExpr` is updated for Fable?

@alfonsogarciacaro Since it's still in preview things aren't quite baked yet. Though even if this were shipped I believe we could update FCS after the fact.

**Comment by alfonsogarciacaro** [comment]
@cartermp All the signs are the fsharp/FSharp.Compiler.Service repo and the corresponding nuget package are being abandoned. When someone wants to use FCS to test latest features they're encouraged to build it from this repository. However, there's no incentive to maintain the FCS API (beyond the symbols for editor support) when the developing in this repository, as the current situation has shown.

The feeling is that anyone with a project relying on the Expression tree API from FCS should be prepared to become a maintainer of this repository to make sure new features get implemented in the Expression tree too. Something that my already stretched-too-thin time budget for OSS doesn't allow me to do.

**Comment by Krzysztof-Cieslak** [comment]
> As for the FCS package/repo, we can put together a proposal to publish from this repository and make it a part of our release checklist.

I’d rather not have release cycle of FCS coupled with VF#. Don has given NuGet release access to @baronfel so maybe we will see new releases more often. And TBF, we probably just need to write some automated sync process (for example using GitHub actions when they are out of closed preview).

And as of omitting anon records in expression tree... it seems that was just small mistake, no need to make this as example of some deeper problem (https://twitter.com/dsyme/status/1091311874514321408?s=21)

**Comment by baronfel** [comment]
I'd echo what @Krzysztof-Cieslak has said. I'm on top of (and motivated to!) merge FCS with a more regular cadence and I look forward to automating/documenting that flow even moreso than has already been done in that repo.  I'm working on making the periodic resyncs of FCS and fsharp/fsharp more painless for the community, but the first step from my perspective to to establish a routine of doing them quickly and painlessly, before automating it all away.

**Pull request merged**
