### PR TITLE
Better error reporting in case of object initializers

### LINKED ISSUE #1218: Improve error reporting: Missing , from object initializer
## What

The following code leads to the resulting misleading error message: -

``` fsharp
type Person() =
    member val Name = "" with get,set
    member val Age = 0 with get,set


let p =
    Person(Name = "Fred"
           Age = 18)
```

`error FS0501: The member or object constructor 'Person' takes 0 argument(s) but is here given 1. The required signature is 'new : unit -> Person'`
## Why

The error above gets confused - it firstly assumes that we're trying to call a constructor with arguments when in fact we're trying to set properties on the object. Also it suggests 1 argument is provided but as far as the developer is concerned they have provided 2. The last point is that the error has nothing to do with this - it's simply that we've missed out the `,` between the two property assignments.
## How

I'm not entirely sure what the real syntax error should be - let's start by my suggesting rewording the error to something like this: -

`Syntax error. Were you trying to set the value of multiple properties on the object with object initializer syntax? If so, consider separating arguments with a ,.`

### PR DESCRIPTION
**Pull request by forki**
fixes #1218

image

### CODE REVIEW

**Comment by isaacabraham** [comment]
Boah. Is that like the quickest F# compiler PR ever? :-)

**Comment by forki** [comment]
only took me so long since I worked on https://github.com/Microsoft/visualfsharp/pull/1220 :tongue: 

No back to that scanner API crap  that I'm supposed to fix. I needed short break. because

pile

**Comment by forki** [comment]
@enricosada is there a chance that we print out the err and bsl files if the diff is non-zero? Would help me a lot

**Comment by dsyme** [comment]
We only want to show the new extra message if an "id = expr" is really present in some way.  

Could you add a test matrix,e.g.

    Person(1) // extra argument, not equality
    Person(A=b) // extra argument, id=expr equality
    Person(1=b) // extra argument, not-id=expr equality
    Person(A=b, C=d) // extra argument, two id=expr equality
    Person(A=b
            C=d) // extra argument, two id=expr equality, no comma

and there are probably other cases to add too.

For the wording I suggest:

```
The object constructor '%s' takes %d argument(s) but is here given %d. The required 
signature is '%s'. If some of the arguments are assigning values to properties, consider separating those arguments with a comma (',').
```

**Comment by enricosada** [comment]
@forki what test? i think was removed because bsl/diff usually are big and just a single line addition make big diff in the output of test, fsdiff was not too smart with minimize diff.
maybe we can add to test ouput a cmd like `kdiff3 path/to/file.bsl path/to/file.err` ready to be executed, that's better?

**Comment by forki** [comment]
No the issue is that I don't get to that point locally. I need to see what
was wrong on CI

**Comment by enricosada** [comment]
ok got it, because

```xml
<test-case name="sigs" executed="True" result="Failure" success="False" time="708.227" asserts="0">
<properties>
<property name="Category" value="typecheck/sigs"/>
<property name="Category" value="Misc02"/>
<property name="Category" value="TypeChecker"/>
<property name="Category" value="TypeCheckerSigs"/>
<property name="DIRECTORY" value="D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\typecheck\sigs"/>
</properties>
<properties>...</properties>
<failure>
<message>
<![CDATA[
Error running command 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharpqa\testenv\bin\diff.exe' with args 'neg15.err neg15.bsl normalize' in directory 'D:\j\workspace\release_ci_pa---866fd2c3\tests\fsharp\typecheck\sigs'. ERRORLEVEL 1 ERRORLEVEL 1
]]>
```

doesnt help when using ci server, right.

So i think the solution can be adding the err/bsl to build artifacts of jenkins/appveyor as additional test results, so can be downloaded (and diff).
i'll try

**Comment by forki** [comment]
Yes that would solve it as well. Thanks

**Comment by forki** [comment]
@dsyme I can't find a way to distinguish the cases

    Person(1) // extra argument, not equality
    Person(A=b
                C=d) 

So we need to find a way or we adjust the message to include both cases.

**Comment by KevinRansom** [comment]
@forki @dsyme Is there any more to do for this PR?  it has been untouched for almost 6 Months.

Thanks

Kevin

**Comment by forki** [comment]
Yes as described above I can't find a way to distinguish the two cases and need help

**Comment by forki** [comment]
ok found a way. @KevinRansom this is ready

**Pull request merged**
