### PR TITLE
Notify nameresenv about partially checked namespaces or modules

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This fixes https://github.com/Microsoft/visualfsharp/issues/4011

image

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test Ubuntu14.04 Release_fcs Build please

**Comment by vasily-kirichenko** [comment]
ready.

**Comment by vasily-kirichenko** [comment]
Yes, but there are a lot of duplicate symbol uses now. I don't care though 'coz it's not clear how to filter them out on-the-fly because there is no comparison for symbol uses and even symbols, so it's not possible to make a set.

**Comment by dsyme** [comment]
> Yes, but there are a lot of duplicate symbol uses now. I don't care though 'coz it's not clear how to filter them out on-the-fly because there is no comparison for symbol uses and even symbols, so it's not possible to make a set.

Ah, I see, yes, there are [examples of newly introduced duplicates here](https://github.com/Microsoft/visualfsharp/pull/4012/files#diff-b7b17a5c883fd3df717ffad57586ecf6R2064)

Introducing new duplicates feels wrong.  Have you tried de-duplicating using ``ItemsAreEffectivelyEqual`` plus range comparisons?

**Comment by vasily-kirichenko** [comment]
@dotnet-bot test Ubuntu14.04 Release_fcs Build please

**Comment by vasily-kirichenko** [comment]
@dsyme done. It's ready.

**Comment by vasily-kirichenko** [comment]
There is a large green button labeled "Merge", you know...

**Comment by cartermp** [comment]
@dsyme do the latest changes here meet your bar for merge?

**Comment by vasily-kirichenko** [comment]
@KevinRansom so this is not going to be a part of even 15.6?..

**Comment by cartermp** [comment]
We're awaiting @dsyme to sign off on the changes that he requested.  I've used it, though, and it works well from a user acceptability standpoint.

**Comment by dsyme** [comment]
Super, thank you for doing the de-duplication

**Pull request merged**
