### PR TITLE
Update DEVGUIDE.md

### PR DESCRIPTION
**Pull request by isaacabraham**
Add sample error message when failing to install SDK tools.

### CODE REVIEW

**Comment by cartermp** [comment]
>  Agent went offline during the build

<3 jenkins

@dotnet-bot test this please

**Comment by cartermp** [comment]
> 15:26:13 Agent went offline during the build

<3 jenkins again

@dotnet-bot test this please

**Comment by cartermp** [comment]
If this fails again I'm just going to merge because it only touches a readme

**Comment by realvictorprm** [comment]
@cartermp just yesterday I wondered why we need a build if it only touches Readme.

**Comment by forki** [comment]
This thing is unbelievably flaky

**Comment by cartermp** [comment]
Yeah, IDK what's going on.  Usually it's a NuGet issue 😸

**Pull request merged**
