### PR TITLE
Use Roslyn's PatternMatcher in Navigate To service

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
This implements https://github.com/Microsoft/visualfsharp/issues/2242

### CODE REVIEW

**Comment by KevinRansom** [comment]
@vasily-kirichenko the C# code is it copied directly from Roslyn?  Would we be better off getting additional internals visible or public Apis?

**Comment by vasily-kirichenko** [comment]
@KevinRansom yes, it's copied. I ask to open it month or more ago, no progress. I have issues on loading types at runtime in this PR (ImmutableCollections?..) It would be much much better if they added FSharp.Editor to internals visible to list.

**Comment by KevinRansom** [comment]
@vasily-kirichenko 
The best thing to do is to make sure Phillip or I know when you have an ask on the Roslyn team.  email me to ensure that I see it my email address is kevinr at microsoft .com  we can follow up in person.

@Pilchie 
It seems a shame for us to be copying Roslyn code in order to implement our editor features,  We should work on a way to make this easier moving forward.

Kevin

**Comment by KevinRansom** [comment]
@vasily-kirichenko 

can you submit PR's to Roslyn making the stuff we need public, please /cc @Pilchie , @CyrusNajmabadi, @mattwar

Then resubmit this, when the bits are in ... the round trip will certainly be a while ... but is probably going to be better long term.

Thanks

Kevin

**Comment by CyrusNajmabadi** [comment]
> It seems a shame for us to be copying Roslyn code in order to implement our editor features, We should work on a way to make this easier moving forward.

Some types are simply not ready to be made Public.  PatternMatcher, especially, is extremely obstruse and not suitable for being made public.

 > can you submit PR's to Roslyn making the stuff we need public

IN the case of PatternMatcher, please do not.  Just copy the code for now.  The editor team and I intend to come up with something that the platform can expose in the future with a suitably clean API that serves all these needs.

**Comment by KevinRansom** [comment]
@vasily-kirichenko 

@CyrusNajmabadi Just dropped by, it seems that these APIs are not in the right shape to be made public, but there is a plan to produce public versions of them at some stage, with the necessary polishing.  Given that state of affairs copying the code for now until roslyn or vs can get these apis in the right shape is the "right thing" to do.

Thanks for stickjng with this, and I apologize for the mess up.

Kevin

**Comment by smoothdeveloper** [comment]
I'm not sure if that makes sense in context of roslyn / shipping VS, but replacing actual `internal` by just putting classes/members under an `Internals` namespace seems it would help getting more feedback on API that will eventually become public after some maturation period.

**Comment by vasily-kirichenko** [comment]
image 

I removed dependencies on Microsoft.CodeAnalysis.xxx. The only reference left is System.Collections.Immutable. 

Assembly Binding Log Viewer shows the following:
```
*** Assembly Binder Log Entry  (04-Feb-17 @ 17:47:11) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\ServiceHub\Hosts\ServiceHub.Host.CLR.x86\ServiceHub.SettingsHost.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = NULL
Calling assembly : Microsoft.Developer.IdentityService.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\ServiceHub\Services\Microsoft.Developer.Settings\Microsoft.Developer.Settings.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Binding succeeds. Returns assembly from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\System.Collections.Immutable.dll.
LOG: Assembly is loaded in default load context.
```
```
*** Assembly Binder Log Entry  (04-Feb-17 @ 17:47:41) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\ServiceHub\Hosts\ServiceHub.Host.CLR.x86\ServiceHub.RoslynCodeAnalysisService32.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = NULL
Calling assembly : System.Reflection.Metadata, Version=1.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\vaski\AppData\Local\Microsoft\VisualStudio\15.0_183b437fFSharpDev\devenv.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Binding succeeds. Returns assembly from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\System.Collections.Immutable.dll.
LOG: Assembly is loaded in default load context.
```
```
*** Assembly Binder Log Entry  (04-Feb-17 @ 17:47:42) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\ServiceHub\Hosts\ServiceHub.Host.CLR.x86\ServiceHub.RoslynCodeAnalysisService32.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\vaski\AppData\Local\Microsoft\VisualStudio\15.0_183b437fFSharpDev\devenv.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Binding succeeds. Returns assembly from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\System.Collections.Immutable.dll.
LOG: Assembly is loaded in default load context.
```
ILSpy shows the following references:

image

I tried to update the NuGet package to version 1.3.1 with no result.

I'm out of ideas what to do next.

**Comment by vasily-kirichenko** [comment]
I've removed `Microsoft.Collections.Immutable` dependency and it still crashes in the same way. 

I thought it's because `PatternMatcher` assembly is not signed with the MS key, I've fix this and now it refuses to build:
```
1> ... error : CreatePkgDef : error : FileLoadException: Could not load file or assembly 'PatternMatcher, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
1> ... error :    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1> ... error :    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1> ... error :    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
1> ... error :    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
1> ... error :    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
1> ... error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.ProcessAssembly(String fileName, Hive hive, PkgDefContext context, Boolean register, RegistrationMode mode) in F:\dd\src\vssdk\VSIntegration\Tools\src\CreatePkgDef\CreatePkgDef.cs:line 206
1> ... error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments) in F:\dd\src\vssdk\VSIntegration\Tools\src\CreatePkgDef\CreatePkgDef.cs:line 164
1> ... error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments) in F:\dd\src\vssdk\VSIntegration\Tools\src\CreatePkgDef\CreatePkgDef.cs:line 85
1> ... error : SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```
What am I doing wrong?

**Comment by vasily-kirichenko** [comment]
OK, I've removed PatternMatcher project and put code into FSharp.LanguageService.Base. It works:

image

image

**Comment by vasily-kirichenko** [comment]
It's ready.

**Comment by cartermp** [comment]
Very nice.

**Comment by KevinRansom** [comment]
Thank you for doing this.

**Pull request merged**
