### PR TITLE
use .net core sdk preview1. Dont download it if already installed

### PR DESCRIPTION
**Pull request by enricosada**
ref #1140

if the required version of .net core sdk is already installed, use that instead of download + install
if is not installed, like before, is installed in `Tools` subdirectory

bumped required version to `preview1` (f# in that version works xplat osx/ubuntu/win/docker, so is nice to use)

this should speedup appveyor too because .net core sdk preview1 is already installed by default.

for development that mean less download/time after `git clean`

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@enricosada thanks!

Wondering also if the idea of having a single "devtools.zip" downloaded (and prepared by VisualFsharp team whenever we change that dependency) is getting any traction?

It seems that issues with `dotnet restore` will take time to get addressed, the bug in network stack was reported in march and still affecting users of windows 7 AFAIK, having that done seems like a good stop-gap measure and shouldn't cost much to maintain in the meantime.

**Comment by enricosada** [comment]
dotnet restore is fast enough, but depends on packages count (we really need all these?) and number of feeds.
after first restore all packages are caches in ~/.nuget/packages so no download from internet (only resolve version from feeds)

**Comment by KevinRansom** [comment]
Please don't muck with init-tools.cmd it originally came from the internal dotnet OSS build.  I want it to be substantially identical to their's at least for the foreseeable future.  Especially since we are not yet using the coreclr version of msbuild.

By all means propose this change in their repo:  https://github.com/dotnet/corefx and while you are at it, update their init-tools.sh as well.

Thanks

https://github.com/dotnet/corefx

**Comment by enricosada** [comment]
sure

**Pull request closed without merging**
