### PR TITLE
Fix inlining on subtypes

### PR DESCRIPTION
**Pull request by dsyme**
This fixes bug https://github.com/Microsoft/visualfsharp/issues/740

As can be seen from the implementation, the restriction checking for lambdas with an implicit "base" variable (which allows base calls) were too strong - if the base variable is not used then the lambda can be propagated, which allows the inline keyword to be respected.

Suggestions for further testing welcome.

### CODE REVIEW

**Comment by abelbraaksma** [comment]
Since the original bug was reported by me, I wouldn't mind checking the fix, but I'm not quite sure where to start. I'd assume I need a copy of this commit (easy enough), compile and then somehow use it to compile the projects / tests I have that showed exemplified this problem. My guess is the typical way to do this is by taking the compiled binaries and call fsc.exe directly? Or can I configure MSBuild to use another location for fsc?

Sorry if this sounds basic, but I've been a consumer of F# until now, as opposed to being a contributor (other than reporting a handful of bugs).

**Comment by KevinRansom** [comment]
@abelbraaksma Take a look at the test cases here:  https://github.com/Microsoft/visualfsharp/tree/master/tests/fsharpqa/Source/Optimizations/Inlining

If you can add your test cases here then it will be in about the right place.

Thank you for helping out

Kevin

**Comment by abelbraaksma** [comment]
According to @mpetruska, this PR also fixes #614, next to #740, as [he mentions in that issue](https://github.com/Microsoft/visualfsharp/issues/614#issuecomment-167008279).

**Comment by KevinRansom** [comment]
@dsyme Is this PR ready to pull?

**Comment by dsyme** [comment]
Yes, it's ready

**Comment by KevinRansom** [comment]
Thanks for this contribution

**Pull request merged**
