### PR TITLE
convert FCS MSBuild references to a NuGet package

### PR DESCRIPTION
**Pull request by brettfo**
An internal audit found some binaries that shouldn't be in this repo that need to be retrieved externally.  One probable group are the MSBuild 12 binaries used under `fcs/`.

PR marked as draft until we get the final word on if the `Microsoft.Build.*.dll` binaries need to be removed.

Other PRs to follow for other offending binaries.

### CODE REVIEW

**Comment by dsyme** [comment]
@baronfel Note this one

Also I'm pretty sure this while v12 DLL can be well and truly nuked from FCS.

**Comment by dsyme** [comment]
> @dsyme do you mean during the integration that we move this reference to paket dependencies? Or that we can remove the creation of the FSharp.Compiler.Service.MSBuild.v12 component entirely?

Ideally we should remove this DLL entirely.  Also the ProjectCracker DLL, which deals with legacy project formats.

I need to understand of Ionide depends on this in any way

**Comment by cartermp** [comment]
Ionide does depend on it for non-SDK style projects

**Comment by dsyme** [comment]
> Ionide does depend on it for non-SDK style projects

DO you know if it depends on FSharp.Compiler.Service.MSBuild.v12?  There is the "SimulatedMSBuildReferenceResolver" which is normally an adequate replacement

cc @Krzysztof-Cieslak

**Comment by auduchinok** [comment]
It would be great to have the same code used in assembly resolution for scripts in VS and other tools. If we're to use the simulated resolve everywhere it'd be great to update the VS integration too.

**Comment by Krzysztof-Cieslak** [comment]
> FSharp.Compiler.Service.MSBuild.v12

As far as I remember FCS ProjectCracker depends on it for cracking any projects with ToolsVersion < 14.0. The good news is:
1. It may not be needed in practice because it’s basical about projects created in VS 2012 that weren’t updated at all since then
2. @enricosada project cracker handles also old-style projects and we will move to it for all cases ( we already are using it - there is just one combination where Cracker is used - FSAC Net runtime and old-style project) dropping Cracker dependency completely

**Pull request merged**
